- index.js
- lib/rules/index.js
- lib/rules/value-trailing-semicolon.js
- package.json
- test/index.js
- test/rules/value-trailing-semicolon.js
- test/util/testRule.js
@MoOx @jeddy3 @necolas --- anybody else interested in this repo --- I thought we could get some juices flowing if I PR'ed a little code to consider. value-trailing-semicolon is a ridiculously simple rule, since postcss already takes care of it, essentially (thanks @ai).
I figured that the approach could be to keep it very simple. Rules could be much like postcss plugins: functions that accept options, which return functions that accept css AST and the result object. They run their checks and register warnings on the result. They are tested individually --- probably most of the time you'd want to check that given some input the length of the warnings array is what you'd expect and that the message is what you'd expect.
What do you think? Does this seem like a decent setup to start writing …
> Initial experiment with value-trailing-semicolon

- docs/naming-rules.md
Ha, this was harder than I thought! :)
I'm not happy with how I've described the difference between "normal" rules and `*-no-*` rules. Any ideas?
> Add naming rules doc

- .eslintrc
Getting things ready in case other people want to help out...
I've enabled a couple of rules for consistent whitespace in the code e.g. after the `function` keyword and within parentheses etc
The current code in master is nice and consistent, so no changes were needed there. :)
Ok with you guys?
Ref #15
> Tighten-up eslint config

- .eslintrc
- package.json
I think you'll need to do an `npm install`.
I've configured it to match the current code style. I've run it against master and @davidtheclark [PR 33](https://github.com/stylelint/stylelint/pull/33) with no warnings.
We might need to tweak the [exceptions](https://github.com/eslint/eslint/blob/master/docs/rules/space-in-brackets.md#exceptions) as we go on.
Ref: #15
> Enable and configure eslint's space-in-brackets

- src/rules/declaration-no-important/README.md
- src/rules/declaration-no-important/__tests__/index.js
- src/rules/declaration-no-important/index.js
Updates `declaration-no-important` for the new config e.g.
```js
declaration-no-important: 2
```
Am I right to pass `null` into `testDeclarationNoImportant()` in the tests?
Adds a couple of extra tests too and updated the readme accordingly.
> Adapt declaration-no-important to new config structure

- src/rules/block-opening-brace-newline/__tests__/index.js
- src/rules/block-opening-brace-newline/index.js
- src/utils/standardWhitespaceChecker.js
The new assumption here is that in situations where we can't know precisely what the user wants, we will limit the scope of our checking. This case is that after the opening brace, we can demand a newline, but then can't demand that there be no space, one space, a tab, etc. after that newline and before the first declaration. That's the domain of another rule. So I added the `oneBefore()` and `oneAfter()` functions to the `ruleChecker`, which only checks one before/after, instead of also checking 2.
> Create and test block-opening-brace-newline

- src/rules/block-opening-brace-newline-after/index.js
- src/rules/block-opening-brace-space-after/index.js
- src/rules/block-opening-brace-space-before/__tests__/index.js
- src/rules/block-opening-brace-space-before/index.js
- src/utils/whitespaceChecker.js
@MoOx is this what you were talking about with two successive PRs? I think I got it right ...
Needs to be merged after #75.
`block-opening-brace-space-before` now exemplifies the single-multi options. This involved some changes to `whitespaceChecker()`. I tried to comment it up to help you all read/understand what's going on. Please provide feedback if you think anything could be done in a clearer or more efficient way!
Note that this also exemplifies point one from https://github.com/stylelint/stylelint/issues/72 ---- selecting what part of the string to check for newlines when making the single-multi distinction.
> Proof of concept single-multi

- src/rules/block-closing-brace-newline-after/__tests__/index.js
- src/rules/block-closing-brace-space-after/__tests__/index.js
As mentioned in #71: I actually didn't need to change any of the code to make it work as we discussed. So I just added tests to ensure it continues to do that.
> Test block-closing-brace-*-after nested; closes #71

- src/utils/__tests__/valueIndexOf-test.js
- src/utils/valueIndexOf.js
One thing worth noting: I altered the function a little bit so that if you are specifying inside/outside function, it *should* ignore the function name --- e.g. if you look for `a` in the value `calc(var(--number) * 2))` you'll get no results.
> Valueindexof tests

- src/rules/eol-no-whitespace/__tests__/index.js
- src/rules/eol-no-whitespace/index.js
- src/utils/valueIndexOf.js
Well ... the "hacky" parts about this attempt is that I'm just running through the entire source as a string, looking for newlines (or carriage returns) and independently accumulating a line count for the warning, which gets attached to the root instead of a specific node.
Maybe there's a better way to do it? Maybe not?
If we wanted to attach the warnings to more localized nodes, we'd have to cycle through a variety of node types, instead of running through every character in the source string. We'd have to calculate line numbers relative to the parsed line number for each node. (I don't know whether that would ever turn out to be accurate where this current method, of just counting `\n` and `\r` would be inaccurate.)
@ai I wonder if in your work on PostCSS's parser you've developed some …
> Create and test eol-no-whitespace

- src/rules/string-quotes/__tests__/index.js
- src/rules/string-quotes/index.js
- src/utils/index.js
- src/utils/lineCount.js
- src/utils/ruleMessages.js
- src/utils/valueIndexOf.js
For this I also made a utility function that gets the line count. It's probably more reliable than the method I used in `eol-no-whitespace`, so I should switch that out.
> Create and test string-quotes; closes #96

- package.json
- src/rules/property-no-vendor-prefix/__tests__/index.js
- src/rules/property-no-vendor-prefix/index.js
- src/utils/index.js
- src/utils/isAutoprefixable.js
Exemplifies method devised in #103. After this is merged, `isAutoprefixable()` can be used for other `no-vendor-prefix` rules.
> Create and test property-no-vendor-prefix

- package.json
- src/rules/color-no-invalid-hex/__tests__/index.js
- src/rules/color-no-invalid-hex/index.js
I pulled in the `color` module here. I'm sure it will be useful for the other color-related rules.
> Create and test color-no-invalid-hex; closes #121

- src/rules/color-no-invalid-hex/index.js
- src/rules/declaration-comma-space-after/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/function-parentheses-inside-space/index.js
- src/rules/function-space-after/index.js
- src/rules/function-token-no-space/index.js
- src/rules/indentation/index.js
- src/rules/media-feature-colon-space-after/index.js
- src/rules/media-query-parentheses-inside-space/index.js
- src/rules/no-eol-whitespace/index.js
- src/rules/property-value-no-vendor-prefix/index.js
- src/rules/selector-delimiter-space-after/index.js
- src/rules/selector-no-vendor-prefix/index.js
- src/rules/string-quotes/__tests__/index.js
- src/rules/string-quotes/index.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/functionArguments.js
- src/utils/styleSearch.js
This refactor of styleSearch means that it now passes the callback an object instead of just the index. That way we can tack more information onto this object as needed. For example, if I passed in an array as the `target` argument I wanted to be able to know which string in the array a particular match pertains to.
> Stylesearch match object

- src/rules/selector-pseudo-element-colon-notation/README.md
- src/rules/selector-pseudo-element-colon-notation/__tests__/index.js
- src/rules/selector-pseudo-element-colon-notation/index.js
I finally got around to doing this one :)
Is there a better way to do this conditional?
```js
if (expectation === "single" && prevChar === ":") {
result.warn(messages.expected("single"), { node: rule })
} else if (expectation === "double" && prevChar !== ":") {
result.warn(messages.expected("double"), { node: rule })
}
```
Closes #74
> Add selector-pseudo-element-colon-notation

- README.md
- docs/rules.md
- package.json
- scripts/rules.js
Quick fix for `0.1.0` so that a list of all the rules is easily accessible.
`npm run docs-build`
> Add rules.md generator. Closes #137

- src/rules/declaration-no-important/__tests__/index.js
- src/rules/number-leading-zero/__tests__/index.js
- src/rules/rule-no-single-line/__tests__/index.js
- src/rules/rule-trailing-semicolon/__tests__/index.js
I accidentally missed doing this when I merged and renamed the `declaration-block` and `rule-set` rules.
> Standardise structure of test files

- src/rules/color-no-invalid-hex/index.js
- src/rules/declaration-colon-space-after/index.js
- src/rules/declaration-colon-space-before/index.js
- src/rules/declaration-comma-space-after/index.js
- src/rules/declaration-comma-space-before/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/function-comma-space-before/index.js
- src/rules/function-parentheses-inside-space/index.js
- src/rules/function-space-after/index.js
- src/rules/media-feature-colon-space-after/index.js
- src/rules/media-feature-colon-space-before/index.js
- src/rules/media-feature-range-operator-space-after/index.js
- src/rules/media-feature-range-operator-space-before/index.js
- src/rules/media-query-parentheses-inside-space/index.js
- src/rules/number-leading-zero/index.js
- src/rules/number-zero-length-no-unit/index.js
- src/rules/root-no-standard-properties/index.js
- src/rules/selector-combinator-space-after/index.js
- src/rules/selector-combinator-space-before/index.js
Corrects a few typos,  standardises the structure of the warning messages and removes redundant text from the warning messages when it can be determined by the rule name e.g.
```console
Expected single space before "${o}" operator within calc function (function-calc-no-unspaced-operator)
```
Becomes
```console
Expected single space before "${o}" operator (function-calc-no-unspaced-operator)
```
> Standardise warnings

- docs/rule-guidelines.md
Some of the rule names were out of date and the `*-space-*` section needed revising.
> Update rule-guidelines to reflect latest conventions

- src/rules/custom-property-no-outside-root/index.js
- src/rules/custom-property-pattern/index.js
- src/rules/media-query-list-comma-newline-before/index.js
- src/rules/media-query-list-comma-space-after/index.js
- src/rules/number-zero-length-no-unit/index.js
Oops, not sure what happened but it looks like I missed a few `warn()`'s last time. I think this is the last of them.
> Refactor remaining rules to use report()

- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-closing-brace-newline-before/__tests__/index.js
- src/rules/block-closing-brace-newline-before/index.js
- src/rules/block-closing-brace-space-after/index.js
- src/rules/block-closing-brace-space-before/__tests__/index.js
- src/rules/block-closing-brace-space-before/index.js
- src/rules/block-no-empty/__tests__/index.js
- src/rules/block-no-empty/index.js
- src/rules/block-opening-brace-newline-after/__tests__/index.js
- src/rules/block-opening-brace-newline-after/index.js
- src/rules/block-opening-brace-newline-before/__tests__/index.js
- src/rules/block-opening-brace-newline-before/index.js
- src/rules/block-opening-brace-space-after/__tests__/index.js
- src/rules/block-opening-brace-space-after/index.js
- src/rules/block-opening-brace-space-before/__tests__/index.js
- src/rules/block-opening-brace-space-before/index.js
- src/rules/function-url-quotes/index.js
- src/rules/rule-properties-order/index.js
- src/utils/__tests__/hasBlock-test.js
- src/utils/__tests__/hasEmptyBlock-test.js
- src/utils/hasBlock.js
- src/utils/hasEmptyBlock.js
- src/utils/index.js
I've looked a little deeper into how the `block-*` rules deal with blockless statements.
We access blocks via postcss's `eachRule` and `eachAtRule`, which give us access to "statements" ([ref](http://apps.workflower.fi/vocabs/css/en#statement)) . As such, I've added two utils:
1. One to test if a statement has a block
2. The other to test if a statement has an empty block.
These two utils provide the necessary flexibility to support both the `block-*-*-brace-*` whitespace rules and the `block-no-empty` rule.
I've refactored a few of the rules (mostly just renaming variable) to reflect the use of statements. 
Ok with you guys?
Wasn't sure if it should be `isBlockless` or `hasBlock`.
> Clarify block/statement relationship. Cope with blockless statements

- src/rules/at-rule-empty-line-before/__tests__/index.js
- src/rules/at-rule-empty-line-before/index.js
Adds new option that enforces an empty line before at rules unless it is a blockless pair. E.g:
```css
@import url(x.css); /* a blockless pairs have no empty lines */
@import url(y.css);
@import url(z.css);
@media print { /* at rule with block has empty line */
}
```
> Add always-except-blockless-pair option

- src/rules/rule-semicolon-newline-after/README.md
- src/rules/rule-semicolon-newline-after/__tests__/index.js
- src/rules/rule-semicolon-newline-after/index.js
Apologies for the eol-whitespace deletion that bloats the diff a bit.
> rule-semicolon-newline-after allows eol comments; fixes #208

- src/rules/block-opening-brace-newline-after/README.md
- src/rules/block-opening-brace-newline-after/__tests__/index.js
- src/rules/block-opening-brace-newline-after/index.js
- src/rules/block-opening-brace-newline-before/__tests__/index.js
- src/rules/block-opening-brace-newline-before/index.js
I had to rewrite the `-before` rule, as well, because it could no longer simply re-use `-after`'s code.
> eol-comments after opening brace; fixes #210

- src/rules/block-closing-brace-newline-after/__tests__/index.js
- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-closing-brace-newline-before/index.js
- src/rules/block-closing-brace-space-after/index.js
- src/rules/block-closing-brace-space-before/index.js
I applied the same logic to other brace-related rules that seemed vulnerable to the same problem.
> Fix phantom brace problem; closes #218

- src/__tests__/index.js
- src/__tests__/integration.js
- src/index.js
Guess I forgot to integrate disableRanges into the code that people actually use. Should be there now, fixing #223. 
To test that it indeed was I created the minimal integration tests discussed in #202. So if we're happy with what they look like we could close that one, as well.
> Add disableRanges to real-life #223 and minimal integration tests #202

- src/rules/selector-delimiter-newline-after/__tests__/index.js
- src/rules/selector-delimiter-newline-after/index.js
I think the same problem would have applied to media queries, not just rules within rules. So I applied a test for both.
> Allow for indentation of delimited selectors; fixes #217

- src/rules/selector-delimiter-newline-after/README.md
- src/rules/selector-delimiter-newline-after/__tests__/index.js
- src/rules/selector-delimiter-newline-after/index.js
- src/rules/selector-delimiter-newline-before/README.md
- src/rules/selector-delimiter-newline-before/__tests__/index.js
- src/rules/selector-delimiter-newline-before/index.js
- src/rules/selector-delimiter-space-after/README.md
- src/rules/selector-delimiter-space-after/__tests__/index.js
- src/rules/selector-delimiter-space-after/index.js
- src/rules/selector-delimiter-space-before/README.md
- src/rules/selector-delimiter-space-before/__tests__/index.js
- src/rules/selector-delimiter-space-before/index.js
Lets us use the new funky standardised whitespace options ( https://github.com/stylelint/stylelint/blob/master/docs/user-guide.md#whitespace-rules-work-together) with selector delimiters.
Ref #231
> Update the selector-delimiter- rules to use standard whitespace options

- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-closing-brace-newline-before/__tests__/index.js
- src/rules/block-closing-brace-space-after/index.js
- src/rules/block-closing-brace-space-before/index.js
- src/rules/block-opening-brace-newline-after/index.js
- src/rules/block-opening-brace-newline-before/__tests__/index.js
- src/rules/block-opening-brace-newline-before/index.js
- src/rules/block-opening-brace-space-after/index.js
- src/rules/declaration-bang-space-after/index.js
- src/rules/declaration-block-semicolon-newline-after/index.js
- src/rules/declaration-block-semicolon-newline-before/index.js
- src/rules/declaration-block-semicolon-space-after/index.js
- src/rules/declaration-block-semicolon-space-before/index.js
- src/rules/declaration-colon-space-after/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/media-feature-colon-space-after/index.js
- src/rules/media-feature-range-operator-space-after/index.js
- src/rules/media-feature-range-operator-space-before/index.js
- src/rules/media-query-list-comma-space-after/index.js
- src/rules/selector-combinator-space-after/index.js
- src/rules/selector-delimiter-newline-after/index.js
- src/rules/selector-delimiter-newline-before/__tests__/index.js
- src/rules/selector-delimiter-newline-before/index.js
- src/rules/selector-delimiter-space-after/index.js
- src/rules/value-list-comma-newline-before/__tests__/index.js
- src/rules/value-list-comma-newline-before/index.js
- src/rules/value-list-comma-space-after/index.js
- src/utils/whitespaceChecker.js
Ref: #231 
@davidtheclark I was hoping to get your advice on this as you're closest to the whitespace rules and the `whitespaceChecker`.
There's so much good stuff going on in the whitespace rules. I think this is a last minor hurdle we need to get over before we can release `0.1.0`. :)
So, both:
* `block-closing-brace-newline-before`
* `media-query-list-comma-newline-before`
Can deal with an arbitrary amount of indentation after the newline and before the comma/brace.
```css
@media print
,screen { }
↑
This indentation before the comma
```
```css
@media print {
a {
color:pink;
}
}↑
↑
And this indentation before the closing brace
```
As they have special clauses to deal with it:
* https://github.com/stylelint/stylelint/blob/master/src/rules/block-closing-brace-newline-before/index.js#L47
* …
> Tests for *-newline-before

- src/rules/block-opening-brace-newline-after/README.md
- src/rules/block-opening-brace-newline-after/__tests__/index.js
- src/rules/block-opening-brace-newline-after/index.js
- src/rules/block-opening-brace-newline-before/README.md
- src/rules/block-opening-brace-newline-before/__tests__/index.js
- src/rules/block-opening-brace-newline-before/index.js
- src/rules/block-opening-brace-space-after/README.md
- src/rules/block-opening-brace-space-before/README.md
Oh wow, it's taken me long enough but I *finally* understand why these rules need a different set of options to those in all the `*-comma-*` rules. All the `*-comma-*` rules look at the commas *in* single and multi-line lists, whereas these `*-brace-*` rules look at the braces *of* single or multi-line blocks. It's a subtle difference, which has only just clicked for me, but it means these rules do need their larger set of options as you can have a newline before and after a *single-line* block.
e.g. `block-opening-brace-space-before`:
```css
```
```css
a {
color: pink; 
}
```
```css
a{ color: pink; }
```
```css
a{
color: pink; 
}
```
```css
```
```css
a{
color: pink; 
}
```
```css
a{ color: pink; }
```
```css
a {
color: pink; 
}
```
```css
a{ color: …
```
> Standardise block-opening-brace-* options

- src/rules/block-closing-brace-newline-after/README.md
- src/rules/block-closing-brace-newline-after/__tests__/index.js
- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-closing-brace-newline-before/README.md
- src/rules/block-closing-brace-newline-before/__tests__/index.js
- src/rules/block-closing-brace-newline-before/index.js
- src/rules/block-closing-brace-space-after/README.md
- src/rules/block-closing-brace-space-after/__tests__/index.js
- src/rules/block-closing-brace-space-after/index.js
- src/rules/block-closing-brace-space-before/README.md
Same as #247 but for `closing-brace`
> Standardise options for block-closing-brace-* rules

- src/rules/index.js
- src/rules/selector-list-comma-newline-after/README.md
- src/rules/selector-list-comma-newline-after/__tests__/index.js
- src/rules/selector-list-comma-newline-after/index.js
- src/rules/selector-list-comma-newline-before/README.md
- src/rules/selector-list-comma-newline-before/__tests__/index.js
- src/rules/selector-list-comma-newline-before/index.js
- src/rules/selector-list-comma-space-after/README.md
- src/rules/selector-list-comma-space-after/__tests__/index.js
- src/rules/selector-list-comma-space-after/index.js
- src/rules/selector-list-comma-space-before/README.md
- src/rules/selector-list-comma-space-before/__tests__/index.js
- src/rules/selector-list-comma-space-before/index.js
A group of selectors has changed to "a selector list separated by commas" in the CSS Selectors Level 4 Spec ([ref](http://dev.w3.org/csswg/selectors-4/#grouping)). 
Which is super convenient for us as it lets us rename the `selector-delimiter-*` rules match our other lists rules: `media-query-list-*`, `value-list-*` :)
You've gotta love that level of consistency :)
> Rename the selector-delimiter rules to selector-list-comma

- README.md
I was having to update (on each change to the rules) each of my config files spread across the projects I'm testing stylelint on, so I figured I'd create a shareable config to make things easier for myself:
https://github.com/stylelint/stylelint-config-suitcss
I think it's worth having this section in the main `README.md`, rather than the user guide, as it means first-time users can get going quickly with something that works out-of-the-box, rather than having to take the time to hand-craft their own configs before they see anything happening. What do you guys think?
Also, if you have any thoughts on the config itself (or the (minimal) code behind it) please flag that up in the repo :)
> Add small section about shareable configs

- src/rules/rule-no-duplicate-properties/__tests__/index.js
- src/rules/rule-no-duplicate-properties/index.js
@benfrain this should address the problem you mentioned [here](https://github.com/stylelint/stylelint/issues/133#issuecomment-120550968), I think.
Relates to #266: If we want to start trying to accommodate non-standard syntaxes, here we go.
> Accurately check nested blocks for duplicate properties

- README.md
Figured it'd be nice to get something in the readme about the disable comments in the readme before `0.1.1` gets cut :)
Ref: #271
> Add details of turing off rules to readme

- src/rules/block-opening-brace-space-before/__tests__/index.js
- src/rules/block-opening-brace-space-before/index.js
- src/utils/__tests__/cssStatementIsNestingBlock-test.js
- src/utils/cssStatementIsNestingBlock.js
- src/utils/index.js
There appears to be a couple more issues with *nesting blocks*. This PR looks at the opening braces of them.
```
a {
color: red;
{ /* <-- this brace */
&:hover {
color: pink;
}
}
}
```
I'm thinking we should treat the opening brace of a *nesting block* as a special case. Perhaps with it's own whitespace rules e.g. `nesting-block-opening-brace-space|newline-before`.
In the meantime, this PR excludes *nesting blocks* from the `block-opening-brace-space-before` rule as it currently flags up warnings against these nesting block braces.
What does everyone think?
> Exclude nesting blocks from opening-brace-space-before rule

- src/rules/rule-trailing-semicolon/__tests__/index.js
- src/rules/rule-trailing-semicolon/index.js
We're revisiting the very first rule :)
`rule.semicolon` doesn't seem to play well with *nesting blocks*. I've added some breaking tests accordingly.
I've had a think about how to resolve this, but nothing obvious sprung to mind. 
Any ideas?
> Add nesting tests to rule-trailing-semicolon

- src/rules/color-hex-case/README.md
- src/rules/color-hex-case/__tests__/index.js
- src/rules/color-hex-case/index.js
A little tweak so configs read:
```js
"color-hex-case": [2, "upper"]
```
Rather than duplicating "case" e.g. :
```js
"color-hex-case": [2, "uppercase"]
```
> Tweak color-hex-case option names

- src/rules/selector-no-attribute/README.md
This is a small fix for the `selector-no-attribute` rule description title. Current was `selector-no-type`.
> Fix `selector-no-attribute` rule description title.

- CHANGELOG.md
- docs/rules.md
- src/rules/color-hex-length/README.md
- src/rules/color-hex-length/__tests__/index.js
- src/rules/color-hex-length/index.js
- src/rules/index.js
I've tried to:
1. keep regexs to a minimum
2. avoid flagging invalid hex
> Add color-hex-length. Closes #283

- src/rules/indentation/README.md
- src/rules/indentation/__tests__/index.js
- src/rules/indentation/__tests__/rules.js
- src/rules/indentation/__tests__/selectors.js
- src/rules/indentation/index.js
- src/rules/selector-list-comma-newline-after/__tests__/index.js
- src/rules/selector-list-comma-newline-after/index.js
- src/rules/selector-list-comma-newline-before/__tests__/index.js
ignore it in newline check;
fixes #285 
Because the `newline` rule was kind of checking indentation of the selector, and that was causing the problem, I formalized selector-indentation-checking within the `indentation` rule and allowed for arbitrary whitespace after the newline in the `selector-list-comma-newline-*` rules.
> Check selector indentation with indentation;

- CHANGELOG.md
- src/rules/color-hex-case/__tests__/index.js
- src/rules/color-hex-case/index.js
Changes the message from:
`Expected a lowercase hex color #FFF (color-hex-case)`
to
`Expected "#FFF" to be "#fff" (color-hex-case)`
> Change color-hex-case message to be consistent with color-hex-length

- README.md
- src/__tests__/index.js
- src/__tests__/plugins-test.js
- src/index.js
- src/plugin.js
- src/utils/report.js
As discussed in #295 ...
You should be able to do the following in a config:
```js
module.exports = {
plugins: {
foo: function(expectation) { .. },
bar: function(expectation, options) { .. },
baz: {
bazFoo: function(expectation) { .. },
bazBar: function(expectation, options) { .. }
}
},
rules: [ .. ]
}
```
And `rules` would contain configuration for all rules, including the plugin rules `foo` and `bar` and also those within the set `baz`.
> Simple pluggability; closes #295

- CHANGELOG.md
- package.json
- src/testUtils/ruleTester.js
Anybody object to this?
I did it so that it would be a little easier for custom plugin authors to use `ruleTester` --- they just need to have postcss and tape installed as devDependencies ... not `jsesc`, too. Besides, I think `JSON.stringify()` does what we need.
> Remove jsesc devDependency

- README.md
- docs/developer-guide.md
- docs/plugins.md
* Add `plugins.md`.
* Tried to clarify the difference between rules and plugin rules for the user.
* Moved the "creating a plugin rule" into the developer guide.
> Add list of plugins to doc and restructure developer guidelines

- .eslintrc
- package.json
- src/rules/function-url-quotes/index.js
- src/utils/styleSearch.js
- src/utils/whitespaceChecker.js
Something seems to be going wrong with babel-eslint that is breaking the build. We don't need it, anyway, because ESLint understands the syntax we're using -- except, I guess, IIFE arrow functions.
> Remove babel-eslint

- src/rules/at-rule-empty-line-before/index.js
- src/utils/__tests__/validateOptions-test.js
- src/utils/index.js
- src/utils/validateOptions.js
I have here a proof-of-concept for the ideas I tried to describe in #30.
I wrote the validating function and its tests, and tried it out in one rule.
So you can see in `at-rule-empty-line-before/index.js` how it would look to put this kind of validation into a file.
And you can see in `src/utils/__tests__/validateOptions-test.js` some other possibilities for validation schemas.
I *think* (though I'm not 100% sure) that this would be flexible enough to accommodate the varieties of options we currently have and plan for.
I'm interested in your feedback. And if we decide that it will work for us, I guess we'll have to add it to every rule. (It could also be an exposed utility, so 3rd party rules could use it.)
> PoC for validating options; addresses #30

- README.md
A top-level overview so potential new users can see what's available without having to pick through the rest of the docs.
I think the quantity of rules, latest css syntax support, being unopinionated, shareable configs, plugin and the options validator are the main features. Have a missed any, or would you replace any?
@davidtheclark I'd appreciate your language skills in fine-tuning this one :)
> Add list of features to README

- src/rules/custom-property-pattern/__tests__/index.js
- src/rules/custom-property-pattern/index.js
I missed this one when I standardised all the messages of the rules a while back.
Only the `*-no-*` and `*-black/whitelist` rules have single rejection messages. Everything else has "expected", especially when the user specifies something via an option.
> Bring custom-property rule message inline with conventions

- .npmignore
- package.json
So, the npm docs aren't totally clear:
https://docs.npmjs.com/files/package.json#files
> "You can also provide a ".npmignore" file in the root of your package, which will keep files from being included, *even if they would be picked up by the files array*."
But it doesn't seem to work that way.
> "If you name a folder in the array, then it will also include the files inside that folder. *(Unless they would be ignored by another rule.)*"
Anyway, it turns out the files array allows negation, which is handy as a whitelist + nested exclusions seems to produce the cleanest release. Plus choosing what files and included and excluded is consolidated within `package.json`.
> Certain files are always included, regardless of settings: package.json,README (and its variants), CHANGELOG (and its …
> Consolidate list of npm published files into package.json. Closes #332.

- src/rules/rule-no-duplicate-properties/__tests__/index.js
- src/rules/rule-no-duplicate-properties/index.js
- src/rules/rule-properties-order/__tests__/index.js
- src/rules/rule-properties-order/index.js
A typo in the value of `node.type` was preventing `rule-properties-order` and `rule-no-duplicate-properties` from running when the root node was an at-rule.
Closes #336
> Allow tests to run when root node is an at-rule

- src/rules/rule-no-shorthand-property-overrides/index.js
Small tweak to make the `rule-no-shorthand-property-overrides` message consistent with other messages:
* no longer repeats the gist of the rule name in the message.
* now uses the word "after", similar to how `rule-properties-order` uses "before" - another rule dealing with property orders.
Becomes:
`Unexpected shorthand "margin" after "margin-bottom" (rule-no-shorthand-property-overrides)`
> Make override message consistent

- package.json
- src/utils/isAutoprefixable.js
Looks like `autoprefixer-core` is deprecated in favour of `autoprefixer` in `6.0`
Everything else was hunky-dory.
> Update deps, including swapping autoprefixer-core to autoprefixer

- CHANGELOG.md
- package.json
- src/rules/selector-no-attribute/__tests__/index.js
- src/rules/selector-no-attribute/index.js
- src/rules/selector-no-combinator/__tests__/index.js
- src/rules/selector-no-combinator/index.js
- src/rules/selector-no-id/__tests__/index.js
- src/rules/selector-no-id/index.js
- src/rules/selector-no-type/__tests__/index.js
- src/rules/selector-no-type/index.js
- src/rules/selector-no-universal/__tests__/index.js
- src/rules/selector-no-universal/index.js
I put some work into adding position data to postcss-selector-parser, so now we can have precise locations for *everything*.
I added note to changelog. If you feel good about this and merge it, let's have a patch release. Sound good?
> Improve selector warning location accuracy

- CHANGELOG.md
- src/rules/at-rule-empty-line-before/index.js
- src/rules/block-closing-brace-newline-before/index.js
- src/rules/block-opening-brace-newline-after/index.js
- src/rules/comment-empty-line-before/index.js
- src/rules/comment-space-inside/index.js
- src/rules/custom-media-pattern/index.js
- src/rules/declaration-block-semicolon-newline-after/index.js
- src/rules/declaration-block-semicolon-newline-before/index.js
- src/rules/declaration-block-semicolon-space-after/index.js
- src/rules/declaration-block-semicolon-space-before/index.js
- src/rules/function-url-quotes/index.js
- src/rules/indentation/index.js
- src/rules/media-feature-colon-space-after/index.js
- src/rules/media-feature-range-operator-space-after/index.js
- src/rules/media-feature-range-operator-space-before/index.js
- src/rules/media-query-list-comma-space-after/index.js
- src/rules/media-query-parentheses-space-inside/index.js
- src/rules/rule-non-nested-empty-line-before/index.js
- src/rules/rule-trailing-semicolon/index.js
- src/utils/cssStatementStringBeforeBlock.js
- src/utils/index.js
- src/utils/mediaQueryParamIndexOffset.js
- src/utils/rawNodeString.js
@jeddy3 This isn't done, so don't merge. But I thought I'd throw it up in case you felt like working on it. I made a lot of revisions but I haven't been very systematic about it yet, and `indentation` and `rule-trailing-semicolon` tests are failing — most likely because of the revealed truth that `raw("after")` will not always be the same as `raws.after`. Anyway, I have to go to work, so won't get to finishing this for at least the rest of the day. Just thought I'd post it.
> Start on raws-raw revision

- src/rules/color-hex-case/__tests__/index.js
- src/rules/color-hex-case/index.js
- src/rules/color-hex-length/__tests__/index.js
- src/rules/color-hex-length/index.js
- src/rules/color-no-invalid-hex/__tests__/index.js
- src/rules/color-no-invalid-hex/index.js
In Sass, interpolation syntax is `#{$variable}`, which looks like the start of a hex code to the color linters, but fails to match the pattern for hex codes. This results in a "Cannot read property '0' of null" error
This just checks to make sure that the hex code pattern returns a match before proceeding
> allow sass interpolation in color linters

- src/rules/indentation/README.md
- src/rules/indentation/__tests__/at-rules.js
- src/rules/indentation/__tests__/rules.js
- src/rules/indentation/index.js
Sass has cases where the current rules for `value` and `param` might not make sense.
Maps:
```scss
$foo: (
a: 1,
b: 2
);
```
Mixin params:
```scss
@mixin foo(
$a: 1,
$b: 2
) {
@content;
}
```
Also, *scss-lint* doesn't check for indentation in these cases, so ignoring helps migrating from there
> add ignore value and param to indentation

- CHANGELOG.md
- docs/user-guide/cli.md
- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
- package.json
- src/__tests__/standalone-test.js
- src/cli.js
- src/standalone.js
Additionally, I changed the `css` option to `code` (because it might be not straight CSS).
I also added ticks around some option headings in the api docs. @jeddy3, not sure if you want to do that consistently across the files?
> Add syntax config with scss option to API and CLI; closes #410

- CHANGELOG.md
- docs/user-guide/rules.md
- src/rules/index.js
- src/rules/rule-single-line-max-declarations/README.md
- src/rules/rule-single-line-max-declarations/__tests__/index.js
- src/rules/rule-single-line-max-declarations/index.js
Thought I’d make a start on the rules that don't need `postcss-value-parser`, while we wait to see what happens with https://github.com/TrySound/postcss-value-parser/issues/12
> Add rule-single-line-max-declarations rule

- CHANGELOG.md
- docs/user-guide/rules.md
- package.json
- src/rules/color-no-named/README.md
- src/rules/color-no-named/__tests__/index.js
- src/rules/color-no-named/index.js
- src/rules/index.js
- src/utils/declarationValueIndexOffset.js
- src/utils/index.js
ref : #424
> is-named-css-color might be useful here.
I used [is-css-color-name](https://www.npmjs.com/package/is-css-color-name).
[is-named-css-color](https://www.npmjs.com/package/is-named-css-color) returns `true` if the color value such as `$color-name-black` and `var(--color-name-white)`. I think that the variables like `$color-name-black` should be valid in this rule because the variable that contains with color name is not always color name.
> Add rule : color-no-named

- src/rules/unit-blacklist/README.md
Added examples within non-length units as the same way in [unit-whitelist](https://github.com/makotot/stylelint/commit/5412308cdf3d3213415d59a6fcfd73cd63a6b18d).
> Add non-length units

- src/rules/function-whitelist/__tests__/index.js
- src/rules/function-whitelist/index.js
- src/rules/property-blacklist/index.js
- src/rules/property-whitelist/index.js
- src/rules/unit-blacklist/index.js
- src/rules/unit-whitelist/index.js
This address #449. As discussed: We don't need to validate for arrays because we have no reason not to accept single values. So this slight change to the code for the whitelist/blacklist rules allows it to accept single values or arrays.
The same logic could be applied to future rules, of course.
> Anticipate single values in white- and blacklist rules

- CHANGELOG.md
- src/rules/function-comma-newline-after/__tests__/index.js
- src/rules/function-comma-space-after/__tests__/index.js
- src/rules/function-comma-space-after/index.js
We needed to check the function string itself for whether to enforce single- or multi-line options. We were erroneously checking the whole declaration.
> Fix line judgment for function-comma whitespace rules; fixes #462

- CHANGELOG.md
- docs/user-guide/rules.md
- src/rules/index.js
- src/rules/max-line-length/README.md
- src/rules/max-line-length/__tests__/index.js
- src/rules/max-line-length/index.js
Addresses #423.
Here's a draft of the rule. While working out the tests I decided that the only long lines I thought should be accommodated were those with no whitespace except at the line's start. I think that in all the other situations you actually could make something multiline --- and the purpose of the rule is to force that, so I didn't want to make a limited set of punctuation marks that evaded the rule.
I did not write documentation. First I just wanted to see what @jeddy3 and @MadLittleMods thought of what's there. Thanks!
> Add rule: max-line-length

- CHANGELOG.md
- src/rules/function-comma-newline-after/__tests__/index.js
- src/rules/function-comma-newline-after/index.js
- src/rules/function-comma-newline-before/__tests__/index.js
- src/rules/function-comma-newline-before/index.js
- src/rules/function-comma-space-after/__tests__/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/function-comma-space-before/__tests__/index.js
- src/rules/function-comma-space-before/index.js
A failing test to go along with #494.
I briefly tried to find a resolution to this one, but I ended up abusing the `outsideFunctionalNotation` option of `styleSearch`. So, I was hoping you’d be able to take a look at it.
P.S. Also updates the messages.
> Nested function comma

- src/rules/color-hex-length/README.md
If it's not possible to write a color any shorter, stylelint will rightly not report it as an error. That's the expected behaviour, but maybe this can be explicitely stated in the docs.
> Clarify which patterns aren't warnings

- CHANGELOG.md
- docs/developer-guide/plugins.md
- docs/user-guide/configuration.md
- src/__tests__/fixtures/config-relative-plugin.json
- src/__tests__/fixtures/plugin-warn-about-foo.js
- src/__tests__/plugins-test.js
- src/buildConfig.js
- src/createPlugin.js
- src/index.js
- src/postcssPlugin.js
This involves some change to the plugin API, so I'll have to refactor the two existing plugins :)
In order for plugin rules to work just like any other rules (including, e.g., being able to be disabled by comments), they need to have a standard rule name. Previously, config's `plugins` argument accepted an object, which gave the illusion that it would be a good idea to use whatever name you want to refer to your plugin rules. Instead, plugins need to document their names.
With that established I thought there was no reason not to use an array instead of an object. I did run across one bump, though, which I solved by making the `stylelint.createPlugin()` function. Much like `postcss.plugin()`, I figure this could be handy down the line if for any reason we need to add extra steps when …
> New plugin API draft; closes #497

- CHANGELOG.md
- src/rules/number-no-trailing-zeros/__tests__/index.js
- src/rules/number-no-trailing-zeros/index.js
Best way to deal with https://github.com/stylelint/stylelint/issues/516 ?
> Exclude at-import from number-no-trailing-zeros

- package.json
- src/rules/comment-empty-line-before/README.md
- src/rules/comment-empty-line-before/__tests__/index.js
- src/rules/comment-empty-line-before/index.js
- src/rules/comment-space-inside/README.md
- src/rules/comment-space-inside/__tests__/index.js
- src/rules/comment-space-inside/index.js
Implements what's proposed in https://github.com/stylelint/stylelint/pull/520
This PR uses my private fork of stylelint-rule-tester which allows usage of a custom parser. If something like https://github.com/stylelint/stylelint-rule-tester/pull/3 would be released I'll update the dependency.
> Ignore line comments when checking comment-related rules

- docs/user-guide/cli.md
files are not passed to `node-glob`
__update:__ they are when passed as a string
> add example usage to cli readme

- src/rules/declaration-colon-space-after/README.md
```css
box-shadow: 0 0 0 1px #5b9dd9, 0 0 2px 1px rgba(30, 140, 190, 0.8);
```
not throw error `declaration-colon-space-after` and add example with single-line declaration
> typo in docs

- src/rules/rule-properties-order/__tests__/flat.js
- src/rules/rule-properties-order/index.js
> Make rule-properties-order account for property names containing multiple hyphens

- CHANGELOG.md
- src/rules/string-quotes/__tests__/index.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/styleSearch.js
If `//` is not parsed, then it results in a syntax error; so I thought this simple little modification to `styleSearch()` was a safe bet. Any objections?
> Support single-line comments in styleSearch; fixes #547

- CHANGELOG.md
- src/rules/function-calc-no-unspaced-operator/__tests__/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
This creates a simple little function to obfuscate Sass/Less-style variables, so their hyphens (or other special characters) don't confuse the rule. This rule already was making an exception for these specific types of variables, so I think this is appropriate.
(If it turns out that we need this functionality elsewhere, we could extract the function to a utility.)
> Ignore variables when looking for operators; fixes #548

- docs/user-guide/complementary-tools.md
The Atom linter-stylelint plugin is now part of the @AtomLinter GitHub organization, even though this happened in July and the URL redirects have been working fine this updates the URL to the new URL.
See https://github.com/AtomLinter/linter-stylelint/issues/3
> Updated Atom linter-stylelint repo link

- src/buildConfig.js
- src/cli.js
- src/standalone.js
Cosmic config evaluates the `process.argv` array, if an `--config` argument is available it takes precedence over other config sources. This has the consequence that my `.stylelintrc` file is no longer found. I run webpack with `--config`.
My pull request should fix this.
> Fix cosmiconfig config file detection

- CHANGELOG.md
- src/rules/block-opening-brace-newline-after/README.md
- src/rules/block-opening-brace-newline-after/__tests__/index.js
- src/rules/block-opening-brace-newline-after/index.js
- src/rules/declaration-block-semicolon-newline-after/README.md
- src/rules/declaration-block-semicolon-newline-after/__tests__/index.js
- src/rules/declaration-block-semicolon-newline-after/index.js
This allows for multiple spaces between the punctuation and the end-of-line comment.
It also enforces the implicit assumption that these exception-triggering end-of-line comments should themselves contain no newlines.
> Improve handling of end-of-line comment exceptions; fixes #598

- src/rules/rule-non-nested-empty-line-before/README.md
Fix readme for rule-non-nested-empty-line-before (http://stylelint.io/?/src/rules/rule-non-nested-empty-line-before/README.md).
Last part was the same as http://stylelint.io/?/src/rules/rule-nested-empty-line-before/README.md
> docs(readme): rule-non-nested-empty-line-before

- docs/user-guide/complementary-tools.md
I was catching up on the stylelint twitter feed when I saw there’s now a webpack loader and a gulp plugin for stylelint.
I also removed bem-linter as that’s on the plugin page.
> Add runners/loaders and remove bem-linter from comp tools

- README.md
A standard config was mentioned over in https://github.com/stylelint/stylelint.github.io/issues/3#issuecomment-164299883. It doesn’t looks like it’s been started by anyone in the last month, and so I figured I’d take a stab at it.
It’s a looser version of the currently recommended `config-suitcss`, and it is based on the most common rules I found across a number of style guides. SuitCSS is an excellent framework/methodology, but I’m unsure how well-known it is, and so figured we might as well recommend something else on the home page.
@davidtheclark It’s up to you if this one goes in now, or if we should wait for (or if you have any) feedback on the `config-standard` [repo itself](https://github.com/stylelint/stylelint-config-standard)?
> Swap config-suitcss to config-standard

- CHANGELOG.md
- src/rules/max-line-length/README.md
- src/rules/max-line-length/__tests__/index.js
- src/rules/max-line-length/index.js
- src/utils/__tests__/styleSearch-test.js
Closes #617.
I ran into a difficult conundrum with this one, and ended up accepting the limitation the it will only enforce the rule for lines that *start* with comments (either the beginning of a comment or the middle of one).
See the docs and tests for more examples.
@ntwb, it would be great if you could try this branch out and see if it works the way you would want it to.
> Add ignore non-comments option to max-line-length

- src/rules/selector-no-id/__tests__/index.js
- src/rules/selector-no-id/index.js
This fixes a problem where `selector-no-id` warns about Sass interpolation when multiple interpolations are used in a selector:
```scss
.n#{$n}-#{$n} {
}
```
The fix brings back the regex `/#{.+}/.test(id)` that was changed to `id.value[0] === "{" && id.value.slice(-1) === "}"` for better perf in PR #593. Too bad that checking for the first and last character did not work for all cases.
> selector-no-id: Don't warn about multiple interpolations in Sass loops

- CHANGELOG.md
- src/rules/indentation/__tests__/rules.js
- src/rules/indentation/index.js
The indentation rule is now going to ignore semicolons appearing on their own line after declarations. That should enable @MoOx to do whatever crazy stuff he wants :)
> Indentation and lonesome semicolons; fixes #646

- docs/user-guide/postcss-plugin.md
Ref: https://github.com/stylelint/stylelint/issues/654
Expanding the Quick Start felt a little like overkill when I tried it.
So this PR tweaks the PostCSS Plugin doc page and expands the usage instructions. 
PostCSS version compatibility gets bumped to the bottom as not so relevant now.
> Expand PostCSS plugin usage instructions

- CHANGELOG.md
- docs/user-guide/configuration.md
- src/__tests__/fixtures/config-color-no-named-custom-message.yaml
- src/__tests__/integration.js
- src/__tests__/standalone-test.js
- src/postcssPlugin.js
- src/utils/report.js
- src/utils/validateOptions.js
Easy custom messages: just add them as a secondary `message` option to any rule.
Anybody who feels like testing this out and trying to break it before we release --- that would be grand!
cc/ @bluetidepro, @kangax, @jeddy3
> Allow for custom messages; closes #400

- src/rules/comment-empty-line-before/README.md
- src/rules/comment-empty-line-before/__tests__/index.js
- src/rules/comment-empty-line-before/index.js
This PR adds a new `ignore: ["between-comments"]` option to `comment-empty-line-before` (#647).
> Add ignore between comments option to comment-empty-line-before, closes #647

- CHANGELOG.md
- docs/user-guide/rules.json
- docs/user-guide/rules.md
- src/rules/font-weight-notation/README.md
- src/rules/font-weight-notation/__tests__/index.js
- src/rules/font-weight-notation/index.js
@jeddy3: I did not add this to the rule index because there was not an obvious category for it. Where would you like to put it?
> Add font-weight-notation rule; closes #595

- docs/user-guide/node-api.md
Code example now matches the example description, i.e. switch from a CSS string to .scss files glob
> Update `.scss` example in Node API docs

- src/rules/property-value-blacklist/README.md
- src/rules/property-value-blacklist/__tests__/index.js
- src/rules/property-value-blacklist/index.js
As discussed in https://github.com/stylelint/stylelint/issues/551
> Add property-value-blacklist rule

- CHANGELOG.md
- src/standalone.js
When we pass an empty string to `code`,
```js
const stylelint = require('stylelint');
stylelint.lint({code: '', config: {
rules: {
indentation: [2]
}
}}).lint().catch(console.error);
```
We get the error like this:
```
Error: You must pass stylelint a `files` glob or a `code` string, though not both
```
I think it's not a proper behavior because 0 byte CSS is also a valid CSS. Due to this [I must include a workaround in a VSCode plugin](https://github.com/shinnn/stylelint-vscode/blob/7b008e4a7f6ea28bedf517e578e8de4895bf7f81/index.js#L22-L26) currently.
This pull request lets stylelint regard an empty string as a valid CSS.
> Accept 0 byte CSS code

- CHANGELOG.md
- docs/developer-guide/plugins.md
- package.json
- src/__tests__/importableApi-test.js
- src/index.js
- src/testUtils/index.js
- src/testUtils/ruleTester.js
I also added tests to ensure that what you get when you import `stylelint` is what we expect it to be.
Once this is released, I will deprecate the stylelint-rule-tester package.
> Incorporate and expose ruleTester; closes #702

- src/rules/media-feature-no-missing-punctuation/__tests__/index.js
Added 3 failing tests to `src/rules/media-feature-no-missing-punctuation/__tests__/index.js`
See #742
> Add initial media-query-parentheses-space-inside tests for media-feature-no-missing-punctuation

- src/utils/cssStatementStringBeforeBlock.js
Jsdoc was saying it returns undefined, but this can never happen.
> cssStatementStringBeforeBlock: Correct jsdoc

- CHANGELOG.md
- docs/user-guide/rules.md
- src/rules/index.js
- src/rules/string-no-newline/README.md
- src/rules/string-no-newline/__tests__/index.js
- src/rules/string-no-newline/index.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/styleSearch.js
This involved some enhancements to styleSearch, too. One that was necessary (adding `withinComments` option), and the rest for consistency.
> Add string-no-newline; closes #739

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/color-no-named/README.md
- src/rules/color-no-named/__tests__/index.js
- src/rules/color-no-named/index.js
Removes it from the examples config and the rules list in the docs. The README will still generate a page at http://stylelint.io/user-guide/rules/color-no-named/ (with a deprecated note added)- so that we remain accessible until the rule is removed in `5.0`.
> Deprecate color-no-named

- CHANGELOG.md
- src/rules/block-closing-brace-newline-after/README.md
- src/rules/block-closing-brace-newline-after/__tests__/index.js
- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-opening-brace-space-before/README.md
- src/rules/block-opening-brace-space-before/__tests__/index.js
- src/rules/block-opening-brace-space-before/index.js
Closes #561
Figured I’d square away some of the older issues.
These changes will *allow* (but not *enforce*) a code style of:
```css
a {
@if $x = 1 {
color: green;
} @else if $y = 2 {
color: blue;
} @else {
color: red;
}
}
@for $i from 1 to 3 
{
.b-$i { 
width: $(i)px; 
}
}
@media (color) {
a {
color: red;
}
}
```
> Add ignoreAtRules option

- CHANGELOG.md
- src/rules/no-duplicate-selectors/README.md
- src/rules/no-duplicate-selectors/__tests__/index.js
- src/rules/no-duplicate-selectors/index.js
I guess I'd consider this a bug fix even though it's a fairly substantial change, just because I don't think the rule was being very useful before this.
> Improve no-duplicate-selectors; closes #807

- src/rules/selector-max-specificity/README.md
My bad. We *do* list css processor caveats e.g. [here](https://github.com/stylelint/stylelint/tree/master/src/rules/rule-no-duplicate-properties#rule-no-duplicate-properties). Not sure why I was convinced otherwise.
Anyhow, this PR adds a note to `selector-max-specificity` about variable interpolation.
@davidtheclark You were right. If I was a CSS Processor user, it’s likely one the first questions I’d ask.
> Add note about ignoring var interpolation

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/block-no-single-line/README.md
- src/rules/block-no-single-line/__tests__/index.js
- src/rules/block-no-single-line/index.js
- src/rules/declaration-block-no-single-line/__tests__/index.js
- src/rules/declaration-block-no-single-line/index.js
- src/rules/index.js
Ref: https://github.com/stylelint/stylelint/issues/664
Now applies to all blocks i.e. both those belonging to at-rules and rule-sets.
( I’ll update the changelog afterwards…. :) )
> Rename (and change behaviour) of declaration-block-no-single-line

- CHANGELOG.md
- src/rules/rule-properties-order/README.md
- src/rules/rule-properties-order/__tests__/grouped-flexible.js
- src/rules/rule-properties-order/__tests__/grouped-strict.js
- src/rules/rule-properties-order/index.js
I have 355/355 tests passing at https://github.com/dan-gamble/stylelint/tree/feature/578
I basically duplicated every `emptyLineBefore` test i found and changed the option to `never` and then made the tests pass from there.
> Change emptyLineBefore to take a never option

- CHANGELOG.md
- src/rules/selector-no-id/__tests__/index.js
- src/rules/selector-no-id/index.js
> Fix selector-no-id false positive on Sass interpolation; closes #829

- src/rules/selector-no-type/__tests__/index.js
- src/rules/selector-no-type/index.js
Closes #834.
Simply changes the behaviour from testing the whole value to just the 1st character. This accounts for when the nesting selector is used as a prefix.
I think we now cover off how [scss nesting can be used](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_rules).
P.S. Will update changelog once https://github.com/stylelint/stylelint/pull/833 is in.
> Add support for prefixed nesting selector

- src/rules/declaration-block-no-duplicate-properties/README.md
- src/rules/declaration-block-properties-order/README.md
- src/rules/function-whitespace-after/README.md
- src/rules/no-duplicate-selectors/README.md
- src/rules/property-value-whitelist/README.md
- src/rules/property-whitelist/README.md
- src/rules/root-no-standard-properties/README.md
- src/rules/selector-max-specificity/README.md
- src/rules/time-no-imperceptible/README.md
And how we refer to the rule itself. I’ve gone with “This rule” as it was more prevalent. We also use “The rule” [in places](https://github.com/stylelint/stylelint/tree/master/src/rules/rule-non-nested-empty-line-before) to refer to *rule-sets*. This PR removes any ambiguity. 
Ref: https://github.com/stylelint/stylelint/issues/835#issuecomment-191840511
> Consistent phrasing for resolving nested selectors

- docs/user-guide/rules.md
- src/rules/color-named/README.md
- src/rules/custom-media-pattern/README.md
- src/rules/custom-property-no-outside-root/README.md
- src/rules/custom-property-pattern/README.md
- src/rules/font-weight-notation/README.md
- src/rules/function-blacklist/README.md
- src/rules/function-whitelist/README.md
- src/rules/media-feature-no-missing-punctuation/README.md
- src/rules/no-browser-hacks/README.md
- src/rules/number-no-trailing-zeros/README.md
- src/rules/property-value-blacklist/README.md
- src/rules/property-value-whitelist/README.md
- src/rules/root-no-standard-properties/README.md
- src/rules/selector-no-universal/README.md
- src/rules/selector-root-no-composition/README.md
More tidying.
This PR makes sure the descriptions are consistent across similar types of rules e.g. `pattern` rules.
> Use consistent rule descriptions

- src/rules/no-descending-specificity/__tests__/index.js
- src/rules/no-descending-specificity/index.js
I was testing `master` against the stylelint.io (in prep for the `4.5` release) when I ran into a issue with `no-descending-specificity` pseudos (and, bizarrely, specific class names).
I had a poke around and I’ve narrowed it down to two failing tests. I wanted to push this up in case you had any quick ideas, before I try to properly grok how this rule works.
> Add tests for pseudos to no-descending-specificity

- CHANGELOG.md
- src/rules/function-comma-space-after/__tests__/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/function-comma-space-before/__tests__/index.js
- src/rules/number-leading-zero/__tests__/index.js
- src/rules/number-leading-zero/index.js
- src/utils/__tests__/blurFunctionArguments-test.js
- src/utils/blurFunctionArguments.js
- src/utils/index.js
Addresses #841.
To make number-leading-zero work I created a `blurFunctionArguments()` util, which makes it easier to use regular expressions without getting false positives within function arguments.
@ntwb: Does this address all of the problems in #841 or is there something I missed?
> Fix false positives in url() arguments

- package.json
- src/buildConfig.js
- src/rules/at-rule-empty-line-before/index.js
- src/rules/color-named/index.js
- src/rules/comment-empty-line-before/index.js
- src/rules/declaration-block-no-duplicate-properties/index.js
- src/rules/declaration-block-trailing-semicolon/index.js
- src/rules/font-weight-notation/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/indentation/index.js
- src/rules/index.js
- src/rules/no-duplicate-selectors/index.js
- src/rules/no-unknown-animations/index.js
- src/rules/rule-no-duplicate-properties/index.js
- src/rules/rule-non-nested-empty-line-before/index.js
- src/rules/rule-trailing-semicolon/index.js
- src/rules/selector-max-specificity/index.js
- src/rules/time-no-imperceptible/index.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/rawNodeString.js
- src/utils/report.js
This adds a couple of es2015 specific eslint rules to the main stylelint repo. I’ve added them to catch a few idiomatic things we’ve pointed out in recent PRs, mainly:
- using `const` and `let` instead of `var`
- using shorthand object notation.
> Eslint es2015

- src/rules/no-descending-specificity/index.js
- src/testUtils/warningFreeBasics.js
@davidtheclark When you have a moment, are you able to look into this?
`getLastNonPseudoSelectorNode` in `no-descending-selector` is tripping up (`TypeError: Cannot read property 'type' of undefined`) on `:global {}` [from CSS Modules](https://github.com/css-modules/css-modules#usage-with-preprocessors) - which we use in stylelint.io
I’ve added the test to `warningFreeBasics` as it’s a non-standard thing that I suspect we’ll easily forget about when building a new rule that handles pseudos in some way.
> Add :global to basic tests

- CHANGELOG.md
- src/rules/no-unsupported-browser-features/__tests__/index.js
- src/rules/no-unsupported-browser-features/index.js
This there a cleaner way to build the doiuse options? Or shall we just get this hotfix in and address later?
> Account for options being optional. Closes #870

- CHANGELOG.md
- src/rules/function-comma-newline-after/__tests__/index.js
- src/rules/no-unsupported-browser-features/__tests__/index.js
- src/utils/__tests__/isSingleLineString-test.js
- src/utils/isSingleLineString.js
`isSinglneLineString()` was trimming its input, and that caused the #893 bug. I do not remember why this was done --- and apparently it wasn't essential or its effect was poorly tested, because when I removed the trim all rule tests still passed. So I removed the trim to fix the bug.
I also had to fix another unrelated test to get the green light.
> Remove trim from isSingleLineString and fix test bug; closes #893

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/index.js
I am not sure if we need a major release or not for this. I guess we are removing a feature, even if it's been buggy and short-lived.
Seems that if we are removing the feature, maybe we should cut 5.0 and thereby fix the postcss-reporter problems caused by the deprecation warnings (deprecations causing build failure). Next time we can figure out a better way to do those.
Of the significant possible changes on the horizon -- the more powerful custom messages and the test-engine-agnostic stylelint assert -- neither of those should introduce breaking changes. So I don't know of anything in the pipeline that would force us into another breaking change soon. 
Do you? Thoughts?
> Remove color-no-indistinguishable; closes #891

- src/buildConfig.js
There were some isntances where a plugin could be specified by name, and end up not being resolved as a later merge of extended configs would drop the fixed path.
I'm not sure of the best way to write a spec for this, as this will only show up when a module name is used for the plugin, where currently all the specs seem to test relative paths.
This was originally reported by @davidtheclark [over here](https://github.com/AtomLinter/linter-stylelint/issues/104), which provides a nice setup of how to expose this issue.
> Use absolute plugin path in configs

- docs/user-guide/example-config.md
Just set up stylelint for work and got an error about this depreciated rule. Figured I'd submit a PR for anyone else who was looking for the comprehensive list of rules as they exist today.
> Remove declaration-block-no-single-line

- docs/user-guide/example-config.md
> Fix example documentation for selector-pseudo-element-colon-notation.

- docs/user-guide/complementary-tools.md
**stylelint-loader** lints the files you `require` or the ones you define as an `entry`  in your webpack config. But `@imports` in those files are not followed, so just the main file is linted (for each require/entry).
Instead, with **stylelint-webpack-plugin** you just define file globs, like stylelint does by default. So you get all your files linted.
> Add stylelint-webpack-plugin to the list of Complementary tools

- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/user-guide/example-config.md
Fixes #944
I used the regex `/stylelint/stylelint((\/[\w\-]+)*)\.md` to find urls that needed updating.
> Convert absolute documentation urls to relative urls

- README.md
in README as “Help out” in the middle breaks the flow.
> Make Guides follow Quick start

- CHANGELOG.md
- src/rules/max-line-length/__tests__/index.js
- src/rules/max-line-length/index.js
I ran across some weird stuff in this rule, including completely faulty options validation, so I thought I'd fix it up a little.
> Cleanup max-line-length

- CHANGELOG.md
- src/rules/function-calc-no-unspaced-operator/README.md
- src/rules/function-calc-no-unspaced-operator/__tests__/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
Tried to explain what I did in the readme.
Any objections to a release after this is merged? I noticed that the changelog includes a lot of things.
> Newlines for function-calc-no-unspaced-operator; closes #857

- appveyor.yml
Keeping it already as a safety net, but speeding up pull request green lights.
> Only test node 5 on appveyor

- CHANGELOG.md
- src/rules/no-duplicate-selectors/index.js
- src/rules/selector-no-id/__tests__/index.js
- src/rules/selector-no-id/index.js
- src/rules/selector-no-type/index.js
- src/rules/selector-type-case/index.js
- src/utils/__tests__/cssRuleIsKeyframe-test.js
- src/utils/cssRuleIsKeyframe.js
- src/utils/index.js
Closes #1005.
The structure of the test file for `cssRuleIsKeyframe` doesn’t feel right. Is there a neater way of structuring the tests when we need to use PostCSS’s `walkRules`?
> Identify and ignore keyframe rules

- CHANGELOG.md
- src/rules/no-descending-specificity/README.md
- src/rules/no-descending-specificity/__tests__/index.js
- src/rules/no-descending-specificity/index.js
- src/testUtils/createRuleTester.js
Ran into this bug while trying to use this rule on my codebase.
I think the intention was right to isolate the last compound selector and strip it of pseudos, but the logic was wrong.
> Fix no-descending-specificity bug

- CHANGELOG.md
- src/rules/indentation/__tests__/functions.js
- src/rules/indentation/index.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/styleSearch.js
Added the `outsideParens` option to `styleSearch()` so indentation can ignore *anything* inside parens, whether its a function or not.
> Indentation ignores all parens; closes #1034

- CHANGELOG.md
- src/rules/declaration-block-no-ignored-properties/__test__/index.js
- src/rules/declaration-block-no-ignored-properties/index.js
`declaration-block-no-ignored-properties` now ignore `clear` for `position: absolute` and `position: relative` and not ignore `float` on `display: table-*`
> `declaration-block-no-ignored-properties` fixes

- CHANGELOG.md
- src/rules/declaration-block-no-duplicate-properties/README.md
- src/rules/declaration-block-no-duplicate-properties/__tests__/index.js
- src/rules/declaration-block-no-duplicate-properties/index.js
[Add ignore: ["consecutive-duplicates"] option to declaration-block-no-duplicate-properties](https://github.com/stylelint/stylelint/issues/1021).
I didn’t go into much code. Mostly tried to make it work first. :)
So I’m not sure at all if the [modification to the option validation](https://github.com/stylelint/stylelint/pull/1038/files#diff-fedff11957046c1b70142988dde39426R17) is OK, for example.
If you have any comments on the format or the logic, please fire comments!
> [option] Add consecutive-duplicates option.

- package.json
- src/rules/declaration-block-single-line-max-declarations/__tests__/index.js
- src/rules/declaration-block-single-line-max-declarations/index.js
Closes #1040 
I added a defensive property check into `declaration-block-single-line-max-declarations` as it tripped up using `0.9.0`.
This rules appears to be the only place we don’t check of the existence of the `nodes` property before using it.
> Less empty blocks

- src/rules/unit-blacklist/index.js
- src/rules/unit-no-unknown/index.js
- src/rules/unit-whitelist/index.js
use `cssWordIsVariable` for skip check variables (best performance), also check on `false`  `valueParser.unit` https://github.com/TrySound/postcss-value-parser#valueparserunitquantity
> refactoring unit rules

- CHANGELOG.md
- docs/user-guide/cli.md
- docs/user-guide/node-api.md
- src/__tests__/standalone-test.js
- src/standalone.js
stylelint would throw the postcss `CssSyntaxError` whenever a given code
(file) contained a syntax error. Since it rather is a problem in the
users CSS it makes sense to display this error alongside stylelint
warnings (with line and column information). This should also improve
third party IDE integrations where code is usually checked while typing,
which makes syntax errors more likely.
This code just catches a `CssSyntaxError` and translates it into a stylelint warning.
A typical `CssSyntaxError` object would look like this:
``` JavaScript
CssSyntaxError 
{
name: 'CssSyntaxError',
reason: 'Reason',
file: '/path/syntax-error.css', // only defined when called with a file
source: 'a { color: \'red; }',
line: 2,
column: 12,
message: '/path/syntax-error.css:2:12: Reason',
input: { 
line: 2, …
```
> Report CssSyntaxError alongside stylelint warnings

- CHANGELOG.md
- src/rules/number-zero-length-no-unit/__tests__/index.js
- src/rules/number-zero-length-no-unit/index.js
`number-zero-length-no-unit` now work with `q` unit and ignores `s`, `ms`, `kHz`, `Hz`, `dpcm`, `dppx`, `dpi` units
https://developer.mozilla.org/ru/docs/Web/CSS/resolution
https://developer.mozilla.org/en-US/docs/Web/CSS/time
https://developer.mozilla.org/ru/docs/Web/CSS/frequency
see `incorrect uses`
> `number-zero-length-no-unit` refactoring

- CHANGELOG.md
- src/rules/function-name-case/__test__/index.js
- src/rules/function-name-case/index.js
`function-name-case` now better handling functions `translateX`, `translateY`, `translateZ`, `scaleX`, `scaleY`, `scaleZ`, `rotateX`, `rotateY`, `rotateZ`, `skewX`, `skewY` with `lower` option.
> `function-name-case` handling camel case function

- docs/user-guide/example-config.md
```
"unit-case": "single"|"double",
```
to
```
"unit-case": "lower"|"upper",
```
> Fix a wrong example

- src/__tests__/standalone-test.js
- src/standalone.js
CssSyntaxErrors are reported as a linting error (see #1023). Errors
should set errored to true. The error handler for CssSyntaxErrors did
not set errored to true which lead to unwanted behavior (e.g. the CLI
returns 0 instead of 2 although an error occured).
See: https://github.com/stylelint/stylelint/pull/1023#issuecomment-212418375
> Set errored to true on CssSyntaxError

- CHANGELOG.md
- src/rules/max-empty-lines/__tests__/index.js
- src/rules/max-empty-lines/index.js
Addresses #1081.
There are probably a bunch of other rules that need this same treatment. If we can identify them, we can either add them to this PR or create others.
> Fix CRLF positioning for max-empty-lines

- CHANGELOG.md
- docs/user-guide/configuration.md
- src/__tests__/fixtures/ignore_config/.stylelintignore
- src/__tests__/standalone-test.js
- src/buildConfig.js
- src/postcssPlugin.js
- src/standalone.js
Hi,
This change adds the ability to create a `.stylelintignore` file in the CWD of stylelint and the patterns will be added to `ignoreFiles`
Also, it will add a small notice to say that a file is ignored.
Finally, two small things that I discovered while testing : the configuration and postcss plugin where re-instantiated for each file that was linted, this isn't useful the configuration doesn't change between runs.
> Reads `.stylelintignore` for files to ignore in the run

- CHANGELOG.md
- src/rules/max-empty-lines/__tests__/index.js
- src/rules/max-empty-lines/index.js
The only good way I could think of to fix all the problems associated with positioning the warning was to move the warning from *before* the violation (where it currently resides) to *after* the violation. That way it should be in the same place whether there are `\n`s or `\r\n`s and whether a comment is `/*` or `//`.
I think that since only the positioning of the error changes I would not consider it a "breaking change" that demands a major release. Any disagreement?
> Change max-empty-lines error position; fixes #1100

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/comment-word-blacklist/README.md
- src/rules/comment-word-blacklist/__test__/index.js
- src/rules/comment-word-blacklist/index.js
- src/rules/index.js
What best solution for search disallowed comment? Modify `matchesStringOrRegExp` function (example add param `meta`, which return object with position and founded string) or repeat logic from `matchesStringOrRegExp` inside in rule? What do you think guys?
> `comment-word-blacklist` rule

- README.md
The css-tricks article neatly illustrated that stylelint’s rule fall into roughly four categories.
Previously we only highlighted the catching errors and stylistic capabilities, but I think the “best practises” and “controlling which css features can be used” capabilities were being over looked.
> Detail categories of rules in README Features section

- CHANGELOG.md
- src/rules/number-leading-zero/__tests__/index.js
- src/rules/number-leading-zero/index.js
Just realized that this:
```css
@import "test-file.0.3.1.css"
```
Gets picked up at the `number-leading-zero` rule and might throw lint warnings/errors. Either we do a blacklist of at-rules with this PR or I can edit it to whitelist `@media` as the only at-rules checked with this perhaps?
> Ignore @import at-rules for number-leading-zero rule

- CHANGELOG.md
- src/rules/selector-class-pattern/README.md
- src/rules/selector-class-pattern/__tests__/index.js
- src/rules/selector-class-pattern/index.js
Ref: https://github.com/stylelint/stylelint/issues/1077
We can’t do much about “outputting” Less mixin definitions, but we can ignore “non-outputting” definitions and when mixins are called.
> Ignore less mixins in selector-class-pattern

- src/rules/at-rule-no-vendor-prefix/index.js
- src/rules/block-no-empty/index.js
- src/rules/color-no-invalid-hex/index.js
- src/rules/custom-media-pattern/index.js
- src/rules/custom-property-no-outside-root/index.js
- src/rules/custom-property-pattern/index.js
- src/rules/declaration-block-no-shorthand-property-overrides/index.js
- src/rules/function-blacklist/index.js
- src/rules/function-linear-gradient-no-nonstandard-direction/index.js
- src/rules/no-unknown-animations/index.js
- src/rules/property-no-vendor-prefix/index.js
- src/rules/property-unit-whitelist/index.js
- src/rules/property-value-blacklist/index.js
- src/rules/property-value-whitelist/index.js
- src/rules/property-whitelist/index.js
- src/rules/selector-class-pattern/index.js
- src/rules/selector-id-pattern/index.js
In the more recent rules we return early, mainly to reduce the amount of nesting.
I checked through the first 50 rules and this PR updates the older ones to use this pattern.
Going through the rest of the rules is a task for another time :)
> Refactor to return early

- src/rules/block-opening-brace-newline-before/README.md
> Fix `block-opening-brace-newline-before` docs option `always-multi-line`

- .travis.yml
- appveyor.yml
> Node.js v5 will continue to be supported for the next two months in order to give developers currently using v5 time to transition to Node.js v6. - https://nodejs.org/en/blog/release/v6.0.0/
> Travis CI: Use the latest NodeJS on Travis CI

- package.json
- src/rules/no-indistinguishable-colors/__tests__/index.js
> Ignore color names in URLs in no-indistinguishable-colors

- docs/user-guide/postcss-plugin.md
See https://github.com/nDmitry/grunt-postcss/blob/master/Gruntfile.js#L26-L32 - if there are subtasks the syntax is different then without subtasks, you do not need to wrap `src` and `dest` in `dist`
> Fix syntax of grunt postcss example

- CHANGELOG.md
- src/rules/no-descending-specificity/__tests__/index.js
- src/rules/no-descending-specificity/index.js
https://github.com/stylelint/stylelint/issues/1156
> `no-descending-specificity` now ignores selectors ending on `,`

- CHANGELOG.md
- docs/developer-guide/plugins.md
- docs/user-guide/configuration.md
- docs/user-guide/plugins.md
- src/__tests__/fixtures/config-relative-plugin.json
- src/__tests__/fixtures/plugin-conditionally-check-color-hex-case.js
- src/__tests__/fixtures/plugin-slashless-warn-about-foo.js
- src/__tests__/fixtures/plugin-warn-about-foo.js
- src/__tests__/plugins-test.js
- src/postcssPlugin.js
Closes #1174
@davidtheclark Is this what you had in mind?
When `7.0` comes around we can replace the deprecation warning with a `configurationError`
> Deprecate unprefixed plugin rule names

- CHANGELOG.md
- src/rules/function-comma-newline-after/__tests__/index.js
- src/rules/function-comma-newline-before/__tests__/index.js
- src/rules/function-comma-space-after/__tests__/index.js
- src/rules/function-comma-space-after/index.js
- src/rules/function-comma-space-before/__tests__/index.js
- src/rules/string-no-newline/__tests__/index.js
@evilebottnawi 
Does this look better?
This should fix #1022 and following rule with it:
- `function-comma-newline-after`
Fix location:
- `functionCommaSpaceChecker`
As this method is also used in some other places, I've added some tests to ensure that nothing is broken in following rules:
- `function-comma-space-after`
- `function-comma-newline-before`
- `function-comma-space-before`
I've also extracted all tests related to syntax `scss` into separate testing blocks.
> fixes #1022

- src/rules/shorthand-property-no-redundant-values/__tests__/index.js
- src/rules/shorthand-property-no-redundant-values/index.js
> fix upper case value in shorthand-property-no-redundant-values

- CHANGELOG.md
- src/rules/declaration-block-no-ignored-properties/README.md
- src/rules/declaration-block-no-ignored-properties/__tests__/index.js
- src/rules/declaration-block-no-ignored-properties/index.js
Improves detection of use `vertical-align` with block-level elements and implements #1204.
> Improves vertical-align detection in declaration-block-no-ignored-properties

- CHANGELOG.md
- src/rules/declaration-block-no-ignored-properties/__tests__/index.js
- src/rules/declaration-block-no-ignored-properties/index.js
> Rule `declaration-block-no-ignored-properties` now detects use of `overflow`, `overflow-x` and `overflow-y` with inline elements.

- CHANGELOG.md
- package.json
- src/formatters/stringFormatter.js
I found stringFormatter bug with multi-byte message.
For example, this rule setting got error.
```json
"rules":{
"declaration-no-important": [ true, {
severity: "warning",
message: "間違っています"
} ],
```
```
Error: Subject parameter value width cannot be greater than the container width.
at exports.default (/project/node_modules/table/dist/alignString.js:100:15)
at /project/node_modules/table/dist/alignTableData.js:37:50
at arrayMap (/project/node_modules/lodash/_arrayMap.js:16:21)
at map (/project/node_modules/lodash/map.js:51:10)
at /project/node_modules/table/dist/alignTableData.js:29:34
at arrayMap (/project/node_modules/lodash/_arrayMap.js:16:21)
at map (/project/node_modules/lodash/map.js:51:10)
at exports.default (/project/node_modules/table/dist/alignTableData.js:28:30)
at …
```
> Fix stringFormatter bug with multi-byte error message

- src/formatters/stringFormatter.js
Before:
```shell
test.css
2:3  ✖  Expected single quotes around font-family name "冬青黑体简体中文"   font-family-name-quotes
4
```
After:
```shell
test.css
2:34  ✖  Expected single quotes around font-family name "冬青黑体简体中文"   font-family-name-quotes
```
> Fix stringFormatter

- src/formatters/stringFormatter.js
https://github.com/gajus/table/blob/master/src/validateTableData.js#L44
Inside cell all range this characters are invalid, because we remove their from message. Why? Some package used stylelint (example `stylehacks` and other) may return their error with characters in this range.
> Fix issue 1241

- CHANGELOG.md
- package.json
- src/cli.js
- src/index.js
Looks like #1243 resulted from the apparently unprecedented use the ES2015 spread operator in a recent feature — which [needs `Array.from()`](http://babeljs.io/docs/usage/caveats/), which [Node 0.12 (only) doesn't support](http://node.green/#Array-static-methods).
So we have two choices: don't use spread, or include the Babel polyfill.
I think we're less likely to run into similar confusion in the future if we just include the polyfill, so that's the path I chose.
cc/ @Lucas-C
> Add babel polyfill; fixes #1243

- package.json
I couldn't see any [breaking change](https://github.com/mysticatea/npm-run-all/releases) that would affect stylelint's use of this cool module :+1
> Update devDependency `npm-run-all` to `^2.1.0`

- docs/user-guide/rules.md
- src/rules/keyframe-declaration-no-important/README.md
- src/rules/keyframe-declaration-no-important/index.js
This PR puts this rule into a “Keyframe declaration” section (above the “Declaration” section), so that the *general to specific* organisation is maintained i.e.  `keyfame-declaration-no-important` is specific to keyframe declarations, where as `declaration-no-important` (which now appears below it) is applicable to *all* declarations.
Please excuse the end-of-line noise in the diff. I'm going to update the stylelint eslint rules to catch these things.
> Recategorise keyfame-declaration-no-important

- docs/user-guide/rules.md
It’s a specific type of comment, an so belongs above the “Comment” section.
It felt like the odd-one-out in the “General / sheet” section.
> Recategorise stylelint-disable-coment

- src/formatters/stringFormatter.js
- src/rules/comment-empty-line-before/__tests__/index.js
- src/rules/declaration-block-no-ignored-properties/__tests__/index.js
- src/rules/declaration-block-properties-order/index.js
- src/rules/font-weight-notation/index.js
- src/rules/function-url-quotes/index.js
- src/rules/indentation/index.js
- src/rules/no-extra-semicolons/__tests__/index.js
- src/rules/number-no-trailing-zeros/index.js
- src/rules/selector-attribute-operator-space-after/index.js
- src/rules/value-keyword-case/__tests__/index.js
- src/utils/__tests__/beforeBlockString-test.js
- src/utils/beforeBlockString.js
- src/utils/blurComments.js
- src/utils/blurFunctionArguments.js
- src/utils/blurInterpolation.js
- src/utils/whitespaceChecker.js
Brings codebase inline with new whitespace rules in https://github.com/stylelint/eslint-config-stylelint/pull/5
The majority of the new rules didn’t require any changes (good work everyone! 😄). Only spaces around operators and commas, and eol whitespace needed addressing.
> Consistent whitespace

- src/rules/color-hex-length/index.js
- src/rules/color-no-hex/index.js
- src/rules/color-no-invalid-hex/index.js
- src/rules/declaration-block-no-duplicate-properties/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
- src/rules/property-blacklist/index.js
- src/rules/property-no-vendor-prefix/index.js
- src/rules/property-unit-blacklist/index.js
- src/rules/property-unit-whitelist/index.js
- src/rules/property-value-blacklist/index.js
- src/rules/property-value-whitelist/index.js
- src/rules/property-whitelist/index.js
- src/rules/root-no-standard-properties/index.js
- src/rules/selector-combinator-space-after/index.js
- src/rules/selector-combinator-space-before/index.js
- src/rules/selector-no-vendor-prefix/index.js
- src/rules/selector-pseudo-class-no-unknown/index.js
- src/rules/selector-pseudo-element-no-unknown/index.js
- src/rules/selector-type-no-unknown/index.js
- src/rules/unit-blacklist/index.js
- src/rules/unit-no-unknown/index.js
- src/rules/unit-whitelist/index.js
- src/rules/value-no-vendor-prefix/index.js
I noticed in a couple of the new rules the parameters in the rule messages weren’t very clear, mainly `u` being used when the thing being passed in was a value or a selector.
I’ve quickly gone through the rules and replace the use of single letter parameters where appropriate.
> Use clearer parameter names in rule messages

- CHANGELOG.md
- src/rules/block-opening-brace-newline-before/README.md
The `block-opening-brace-newline-before` contained a wrong example for the `always-multi-line section` that showed a pattern that would be considered a warning as not being considered a warning:
```css
a {
color: pink; }
```
That's why I moved it to the considered as a warning section and replaced it with a pattern that is actually not considered a warning.
I also added two single-line version that are not considered a warning to make it extra clear that single line whitespace does not matter with this setting.
> Fix block-opening-brace-newline-before documentation

- CHANGELOG.md
- src/rules/unit-no-unknown/__tests__/index.js
- src/utils/__tests__/getUnitFromValueNode-test.js
- src/utils/getUnitFromValueNode.js
New version have two bugs with `unit-no-unknown` and `shorthand-property-no-redundant-values`. Now i work on PR on two.
> Ignore color hex in `unit-no-unknown`.

- CHANGELOG.md
- src/rules/shorthand-property-no-redundant-values/__tests__/index.js
- src/rules/shorthand-property-no-redundant-values/index.js
> Rule `shorthand-property-no-redundant-values` ignore some properties.

- CHANGELOG.md
- src/rules/selector-type-no-unknown/__tests__/index.js
- src/rules/selector-type-no-unknown/index.js
Why we use `if (isKeyframeRule(rule)) { return }` in selectors rule?
> Ignore nesting selectors.

- src/rules/media-query-list-comma-newline-before/README.md
In `media-query-list-comma-newline-before`:
"There *must never* be a __white__ before the commas in multi-line media query lists."
I think this should probably be:
"There *must never* be a __newline__ before the commas in multi-line media query lists."
> Docs: media-query-list-comma-newline-before typo

- src/rules/property-unit-blacklist/index.js
- src/rules/property-unit-whitelist/index.js
I can write tests for it, but I think it's a bit unnecessary as all the rules of the properties should not ignore the non standard syntax and it will clog the tests we have, where you can do it once in https://github.com/stylelint/stylelint/issues/1313  for all property rules.
> Add standard checks for property rules.

- CHANGELOG.md
- package.json
- src/cli.js
- src/index.js
- src/reference/keywordSets.js
I removed `babel-polyfill` and replaced the spread operator usage with a simple function.
Tested to ensure I didn't repeat bug #1243, and I do think it's not coming back. We just have to not use spread operators.
> Remove babel-polyfill and spread usage; fixes #1316

- src/rules/time-no-imperceptible/README.md
The rule prohibits animation/transition times equal to 100ms or less with the addition of https://github.com/stylelint/stylelint/commit/530c1d3f40378bdd5492f0e296089ba9d34da872
> Update time-no-imperceptible README

- src/rules/at-rule-empty-line-before/README.md
- src/rules/comment-empty-line-before/README.md
- src/rules/rule-nested-empty-line-before/README.md
- src/rules/rule-non-nested-empty-line-before/README.md
A few rule docs have the text "There must never be an _empty before_ rules"
Presume these should all be "There must never be an _empty **line** before_ rules"?
> Docs: fix "empty before"

- docs/user-guide.md
- docs/user-guide/release-planning.md
Example deprecation warning would read:
"The 'hierarchicalSelectors' option within 'indention' is deprecated and will be moved in 7.0.0. If you use this option please consider creating a plugin for the community. See: http://stylelint.io/user-guides/release-planning/”
@davidtheclark I wouldn’t mind your wordsmith check on this :)
> Add release planning doc

- CHANGELOG.md
- src/rules/selector-max-compound-selectors/__tests__/index.js
- src/rules/selector-max-compound-selectors/index.js
Closes #1348
We were checking properties of the node *before* checking that it was a standard rule.
> Ignore less mixins within selector-max-compound-selectors

- CHANGELOG.md
- src/rules/function-url-quotes/README.md
- src/rules/function-url-quotes/__tests__/index.js
- src/rules/function-url-quotes/index.js
Ref: https://github.com/stylelint/stylelint/issues/1331
Whoops… I forgot that changing the behaviour of the contextual quotes rules was in this milestone.
As with `declaration-block-properties-order` I’m testing that the original options still work alongside the deprecation notices.
I smoke tested this one. It’s nice not having duplicated warnings :)
> Change function-url-quote options

- CHANGELOG.md
- src/rules/selector-list-comma-newline-after/__tests__/index.js
- src/rules/selector-list-comma-newline-after/index.js
- src/rules/selector-list-comma-space-after/__tests__/index.js
- src/rules/selector-list-comma-space-after/index.js
- src/utils/__tests__/isStandardRule-test.js
Closes #1321
`isStandardRule()` to the rescue :)
> Ignore Less mixins `selector-list-comma-*

- CHANGELOG.md
- src/rules/font-family-name-quotes/README.md
- src/rules/font-family-name-quotes/__tests__/index.js
- src/rules/font-family-name-quotes/index.js
Ref: #1331
@davidtheclark Here’s the other contextual quote rule (other one in https://github.com/stylelint/stylelint/pull/1354). I think once these are in we can defo release `6.5.1` :)
As with the other rule changes, I’m testing the original options alongside the deprecation warnings.
Once `7.0` comes around and we strip out all the deprecated options code, this rule is going to look very neat and tidy :)
> Change font-family-name-quotes options

- CHANGELOG.md
- src/reference/keywordSets.js
- src/rules/selector-type-no-unknown/__tests__/index.js
- src/utils/__tests__/isStandardTypeSelector-test.js
- src/utils/isStandardTypeSelector.js
Ref: #1352
FYI, sets names [from spec](https://drafts.csswg.org/selectors-4/)
P.S. I'm loving the reference sets. That was a great initiative :)
> Ignore An+B notation and linguistic pseudo-classes.

- CHANGELOG.md
- src/formatters/stringFormatter.js
Closes: #1347 
Value can sometimes be undefined if displaying a parse error e.g. “selector can not be parsed”
> Fix string formatter handling of parse errors

- CHANGELOG.md
- src/rules/selector-type-no-unknown/README.md
- src/rules/selector-type-no-unknown/__tests__/index.js
- src/rules/selector-type-no-unknown/index.js
Ref: #1352
Slightly odd rule this btw. I think it’s the only one where we checking against HTML specs, rather than CSS ones.
I guess no biggy as this rule can be “finished” if we don’t distinguish obsolete tags.
> Ignore obsolete HTML tags and hgroup selector-type-no-unknown

- src/rules/selector-no-combinator/__tests__/index.js
- src/utils/__tests__/isStandardRule-test.js
- src/utils/isStandardRule.js
https://github.com/stylelint/stylelint/issues/1342
Now a lot of rules(especially `selector-*` rules) not correctly.
> Util `isStandardRule` now ignore Less mixins and extends.

- .github/ISSUE_TEMPLATE.md
I was linked to this a couple of days ago, I think a hidden comment at the end of the GitHUb issue template would be a great.
> https://twitter.com/sindresorhus/status/579306280495357953
> > _"OSS tip: If you want a bug fixed faster, submit a PR with a failing test rather than an issue."_
Currently I've got the text slightly modified reading:
> _"Tip: If you can submit a pull request that includes a failing test this would be really helpful"_
> Add a tip to submit PR's with failing tests GH issue template

- CHANGELOG.md
- src/rules/function-whitespace-after/__tests__/index.js
- src/rules/function-whitespace-after/index.js
- src/testUtils/createRuleTester.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/styleSearch.js
Addresses #1370.
Turns out this helped us find a subtle bug in styleSearch, where the options about which matches to attend to and which to ignore were themselves being ignored when `(` or `)` were being targeted.
While debugging this I fixed a problem with `createRuleTester`.
> Ignore postcss-simple-var interpolation; fixes #1370

- CHANGELOG.md
- docs/developer-guide/formatters.md
- src/__tests__/standalone-test.js
- src/formatters/verboseFormatter.js
- src/postcssPlugin.js
- src/rules/function-whitespace-after/__tests__/index.js
- src/rules/function-whitespace-after/index.js
- src/standalone.js
- src/testUtils/createRuleTester.js
- src/utils/__tests__/styleSearch-test.js
- src/utils/styleSearch.js
Addresses #1144.
While going through this I also noticed that many `standalone-test.js` cases were needlessly grabbing the `output` object, which is a JSON string, and parsing it, when they should have just been looking at the `results` objects, independent of the formatter.
Here is an screenshot showing what this does. The first is verbose mode, the second regular:
> Change registering of ignored files

- src/rules/declaration-block-properties-order/index.js
In the `declaration-block-properties-order` rule all instances of the messages `expectedEmptyLineBetween` and `rejectedEmptyLineBetween` were removed in https://github.com/stylelint/stylelint/pull/1385/commits/9919b34c3c0794321af876abb495cc8934ff9c31 as part of #1385, I don't believe these are required anymore, this PR removes these.
> Remove unused `declaration-block-properties-order` messages

- src/rules/font-family-name-quotes/index.js
There is no need for the `default` case statement in the switch statement in `checkFamilyName` as one of the three `always-unless-keyword`, `always-where-recommended`, or `always-where-required` options are always required by the `font-family-name-quotes` rule.
All going well and my thought process here isn't flawed this will update the `font-family-name-quotes` rule code coverage to 100% from 98.15% here in the `v7` branch 😄
> Remove `default` case from switch in `checkFamilyName`

- CHANGELOG.md
- src/rules/at-rule-empty-line-before/__tests__/index.js
- src/rules/at-rule-empty-line-before/index.js
Closes #1413
(Cleaned follow-up PR for #1415)
> Add `ignore: "blockless-group"` option for `at-rule-empty-line-before`

- CHANGELOG.md
- src/formatters/stringFormatter.js
Fixes #1405.
OSX on Travis reports `process.stdout.columns` and `rows` as 0, so it causes a "Error: Column width must be greater than 0." crash.
> Set default column width when stdout.columns is not set

- CHANGELOG.md
- src/rules/at-rule-blacklist/README.md
- src/rules/at-rule-whitelist/README.md
- src/rules/comment-word-blacklist/README.md
- src/rules/comment-word-blacklist/__tests__/index.js
- src/rules/function-blacklist/README.md
- src/rules/function-blacklist/__tests__/index.js
- src/rules/function-blacklist/index.js
- src/rules/function-whitelist/README.md
- src/rules/function-whitelist/__tests__/index.js
- src/rules/function-whitelist/index.js
- src/rules/property-blacklist/README.md
- src/rules/property-blacklist/__tests__/index.js
- src/rules/property-blacklist/index.js
- src/rules/property-whitelist/README.md
- src/rules/property-whitelist/__tests__/index.js
- src/rules/property-whitelist/index.js
- src/rules/selector-attribute-operator-blacklist/README.md
- src/rules/selector-attribute-operator-whitelist/README.md
- Added regex support to `function-whitelist` and `function-blacklist`. 
- Updated the all the black/whitelist READMEs to show that they all accept single strings.
- Clearly show if a rule supports regex.
- Tweak few other tests to show the single string options work.
> Use consistent options for white/blacklist rules

- CHANGELOG.md
- src/rules/at-rule-name-newline-after/__tests__/index.js
- src/rules/at-rule-name-newline-after/index.js
- src/rules/block-closing-brace-newline-after/__tests__/index.js
- src/rules/block-closing-brace-newline-before/__tests__/index.js
- src/rules/block-opening-brace-newline-after/__tests__/index.js
- src/rules/block-opening-brace-newline-before/__tests__/index.js
- src/rules/declaration-block-semicolon-newline-after/__tests__/index.js
- src/rules/declaration-block-semicolon-newline-before/__tests__/index.js
- src/rules/declaration-block-semicolon-newline-before/index.js
- src/rules/declaration-colon-newline-after/__tests__/index.js
- src/rules/function-comma-newline-after/__tests__/index.js
- src/rules/function-comma-newline-before/__tests__/index.js
- src/rules/function-parentheses-newline-inside/__tests__/index.js
- src/rules/media-query-list-comma-newline-after/__tests__/index.js
- src/rules/media-query-list-comma-newline-before/__tests__/index.js
- src/rules/selector-list-comma-newline-after/__tests__/index.js
- src/rules/selector-list-comma-newline-before/__tests__/index.js
- src/rules/value-list-comma-newline-after/__tests__/index.js
- src/rules/value-list-comma-newline-before/__tests__/index.js
Closes #1374
@davidtheclark Good news. It was just the `at-rule-name-newline-after` and `declaration-block-semicolon-newline-before` rules that weren’t behaving as expected.
As these fixes make both those rule more permissive, then this can be released as a fix in `6.6`.
I also checked through the docs. We correctly use “single space” when one *and only one* space is allowed, and we use “a newline” to indicate that one or more newlines are allowed.
> Ensure one or more newlines are accepted

- docs/developer-guide/plugins.md
Closes #1365
As well as starting the list of external modules and adding a call-to-help extracting utils out, this PR:
- emphases adhering to the “working on rules” conventions.
- expands the plugin example to include the exposed utils.
- remove redundancy between this doc and the “working on rules” one.
> Expand plugin docs

- CHANGELOG.md
- src/cli.js
@davidtheclark `-f verbose` already worked, so it was just a case of updating the CLI help docs and adding the deprecation warning.
Ref: https://github.com/stylelint/stylelint/issues/1439
> Deprecate verbose flag

- src/rules/at-rule-empty-line-before/README.md
- src/rules/comment-empty-line-before/README.md
- src/rules/indentation/README.md
- src/rules/selector-no-qualifying-type/README.md
- src/rules/selector-no-type/README.md
Can you guys view these two markdown files and check that this approach is clearer (i.e. using a subheading for each `ignore` and `except` keyword)? If it is, I’ll roll it out for the other rules.
Ref: #1467
> Make except and ignore option docs clearer

- appveyor.yml
This change has AppVeyor only run one build per pull request rather than previously two builds were ran per pull request, one against `master` and one against the pull request `branch-name`.
See http://www.appveyor.com/docs/branches#white-and-blacklisting
> AppVeyor: Only test `master` branch

- CHANGELOG.md
- src/rules/indentation/__tests__/functions.js
- src/rules/indentation/index.js
Took a lot of tinkering but I seem to have a solution here that solves the problematic use-cases provided in #1149 and #1451.
> Improve indentation's understanding of parentheticals, again

- package.json
- src/rules/selector-max-specificity/__tests__/index.js
- src/rules/selector-max-specificity/index.js
The `selector-max-specificity` rule is incorrectly reporting that a selector with 11 elements has a higher specificity than a selector with a single classname. This is not an issue with the [specificity calculator](https://www.npmjs.com/package/specificity) module but in the way that this rule compares specificity as a base 10 number.
I have updated the unit tests and added a fix for this issue.
I recently updated the specificity calculator module to include a "compare" function, so I have used that function in this rule.
It doesn't appear to have had any negative performance impact.
Before:
```
MacBook:stylelint keegan$ npm run benchmark-rule -- selector-max-specificity "0,2,0"
> stylelint@6.6.0 benchmark-rule /Users/keegan/Projects/Tools/stylelint
> babel-node scripts/benchmark-rule.js …
```
> selector-max-specificity rule incorrectly reporting specificity

- CHANGELOG.md
- src/rules/selector-type-no-unknown/__tests__/index.js
- src/rules/selector-type-no-unknown/index.js
https://github.com/stylelint/stylelint/pull/1496
@davidtheclark If you’re ok to quickly give this the once over I’ll get out `6.7` - we’ve merged in the `ignoreFunction:[]` option so this will be a minor, rather than patch, release.
> Ignore complex keyframe selectors

- src/rules/font-family-name-quotes/index.js
I missed this one in the `v7` branch when doing https://github.com/stylelint/stylelint/pull/1422
> Remove redundant details from message

- CHANGELOG.md
- src/rules/block-closing-brace-newline-before/__tests__/index.js
- src/rules/block-closing-brace-newline-before/index.js
- src/rules/block-closing-brace-space-before/__tests__/index.js
- src/rules/block-closing-brace-space-before/index.js
- src/rules/block-opening-brace-newline-before/__tests__/index.js
- src/rules/block-opening-brace-newline-before/index.js
- src/rules/block-opening-brace-space-before/__tests__/index.js
- src/rules/block-opening-brace-space-before/index.js
Closes #1502
It feels like a while since I actually squished a bug.
Anyhow, turns out this issue effect all four of the `block-*-brace-*-before` rules.
> Fix CRLF warning positioning

- CHANGELOG.md
- src/rules/selector-no-type/__tests__/index.js
- src/rules/selector-no-type/index.js
- src/rules/selector-type-case/__tests__/index.js
- src/rules/selector-type-case/index.js
- src/rules/selector-type-no-unknown/__tests__/index.js
- src/rules/selector-type-no-unknown/index.js
https://github.com/stylelint/stylelint/issues/1513 - we were testing if a selector was a keyframe *after* running it through the selector parser, which correctly treats something like `50.0%` as a tag and class compound selector. I’ve moved the conditional to before the parser.
The `.every()` is needed for complex keyframe selectors like `0%, 50% {}`
At the same time I updated `selector-no-type` and `selector-type-case` to use the same approach as the https://github.com/stylelint/stylelint/issues/1383 bug was present in them.
@davidtheclark Shall I put out a patch release (`6.7.1`) once this is in?
> Ignore factional keyframes and non-standard usage in selector-type-*

- src/rules/selector-max-specificity/README.md
I could be wrong here, but I am guessing that the format example should use `class` instead of `foo`.
This PR changes the format to match what is outlined in the W3C spec documentation.
> Fixes typo in selector-max-specificity documentation.

- package.json
- src/formatters/__tests__/stringFormatter-test.js
- src/formatters/__tests__/verboseFormatter-test.js
Ref: https://github.com/stylelint/stylelint/issues/1359
As the verbose formatter uses the string one, I’ve used the former to test most things.
If we’re happy with this, and once it’s merged I’ll rebase `v7` and update the ignore tests because we treat ignored files differently there.
> Add string and verbose formatter tests

- .github/ISSUE_TEMPLATE.md
Now starts with no distractions to answering questions. 
The hints on how to help resolve this issue are now at the bottom of the template.
> Emphases answering questions in issue template

- .github/ISSUE_TEMPLATE.md
Via Gitter: `I didn’t thoroughly understand what stackoverflow is our preferred QA forum meant.`
• https://gitter.im/stylelint/stylelint?at=576d7b4f165412787f1ac447
> Tweak Stack Overflow support info

- src/rules/declaration-block-properties-order/__tests__/validate-options.js
- src/rules/declaration-block-properties-order/index.js
It looks like the additional options validation in this rule would let anything that looks like an array pass. I’ve patched it up.
This PR brings coverage up to 100% for this rule.
And overall to 99.8% on this branch.
(the failing tests are the `indentation` ones mentioned in the other PR).
> Fix decl-block-prop-order options validation

- src/formatters/__tests__/stringFormatter-test.js
- src/formatters/__tests__/verboseFormatter-test.js
- src/formatters/verboseFormatter.js
@davidtheclark After the rebase from master there are couple of failing `indentation` tests around parens. 
I took a quick look, but figured you might be able to spot the gaff quicker than I. Would you mind taking a look?
> Update ignoreFiles formatter tests

- src/rules/selector-no-qualifying-type/index.js
/cc @davidtheclark @jeddy3 
Close https://github.com/stylelint/stylelint/issues/1545
Why i remove this line? Because `getLeftNodes` get left nodes (until combinator selector) relatively type selector (`div`, `a` and etc), e. g.
```css
[attribute]div {}
#iddiv
.classdiv
```
But first selector is not valid, second and third is interpreted as `id` and `class` selector. Honestly I do not know why it did, perhaps suggested the possibility the first variant.
> Refactoring `selector-no-qualifying-type` - remove unnecessary `getLeftNodes` function.

- src/utils/whitespaceChecker.js
I’ve been poking around for a while in the whitespaceChecker as three lines there were being flagged as uncovered. I've been scratching my head trying to work out how to test the lines, but I now think they are redundant as I can’t think of a situation where’d you either:
- disallow indentation if targeting before a newline.
- allow indentation if targeting before a space.
This PR removes those conditionals and brings coverage up to 100% across the board in `v7`.
> Remove redundant whitespaceChecker code

- src/rules/at-rule-no-vendor-prefix/__tests__/index.js
- src/rules/block-no-empty/__tests__/index.js
- src/rules/block-no-single-line/__tests__/index.js
- src/rules/color-no-hex/__tests__/index.js
- src/rules/color-no-invalid-hex/__tests__/index.js
- src/rules/custom-property-no-outside-root/__tests__/index.js
- src/rules/declaration-block-no-duplicate-properties/__tests__/index.js
- src/rules/declaration-block-no-ignored-properties/__tests__/index.js
- src/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.js
- src/rules/declaration-no-important/__tests__/index.js
- src/rules/function-calc-no-unspaced-operator/__tests__/index.js
- src/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js
- src/rules/length-zero-no-unit/__tests__/index.js
- src/rules/media-feature-name-no-vendor-prefix/__tests__/index.js
- src/rules/no-duplicate-selectors/__tests__/index.js
- src/rules/no-eol-whitespace/__tests__/index.js
- src/rules/no-invalid-double-slash-comments/__tests__/index.js
- src/rules/no-missing-eof-newline/__tests__/index.js
- src/rules/no-unknown-animations/__tests__/index.js
- src/rules/number-no-trailing-zeros/__tests__/index.js
- src/rules/property-no-vendor-prefix/__tests__/index.js
- src/rules/root-no-standard-properties/__tests__/index.js
- src/rules/selector-no-attribute/__tests__/index.js
- src/rules/selector-no-combinator/__tests__/index.js
- src/rules/selector-no-id/__tests__/index.js
- src/rules/selector-no-universal/__tests__/index.js
- src/rules/selector-no-vendor-prefix/__tests__/index.js
- src/rules/selector-root-no-composition/__tests__/index.js
- src/rules/string-no-newline/__tests__/index.js
- src/rules/time-no-imperceptible/__tests__/index.js
We were using `undefined`, `null` and `true`. This PR standardises them all to `true`.
> Standardise no-* rules test options

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/index.js
- src/rules/no-empty-source/README.md
- src/rules/no-empty-source/__tests__/index.js
- src/rules/no-empty-source/index.js
I think we should change name for this rule, because this rule work too on 
```html
<style></style>
``` 
and it is no file, maybe rename `no-empty-stylesheet`. Also i think be good add option `ignoreComment`, maybe something check only empty files, another check empty files with comments.
> New rule `no-empty-source`

- CHANGELOG.md
- src/rules/block-no-empty/__tests__/index.js
- src/rules/block-no-empty/index.js
- src/utils/__tests__/beforeBlockString-test.js
- src/utils/beforeBlockString.js
> Fix warning positioning of `block-no-empty` when using sugarss syntax

- CHANGELOG.md
- src/rules/rule-non-nested-empty-line-before/README.md
- src/rules/rule-non-nested-empty-line-before/__tests__/index.js
- src/rules/rule-non-nested-empty-line-before/index.js
Ref #1351 Initial pass, got one remaining issue to fix, make the rule option actually work 😏
> Initial pass adding `except: ["after-single-line-comment"]` option to`rule-non-nested-empty-line-before` rule

- CHANGELOG.md
- src/rules/time-no-imperceptible/__tests__/index.js
- src/rules/time-no-imperceptible/index.js
Some properties supports negative time values. [`animation-delay`, for example](https://drafts.csswg.org/css-animations/#valdef-animation-delay-time).
> Add support for negative time values

- src/rules/max-line-length/README.md
It seems to me that this is a better example, since the original one is listed below as generating no warning.
> Fix max-line-length example for url in Documentation

- CHANGELOG.md
- src/rules/number-max-precision/__tests__/index.js
- src/rules/number-max-precision/index.js
> `number-max-precision` now better handle case insensitive `@import` at-rules

- src/cli.js
I found a fairly nasty bug when testing out stylelint with a large project:  `process.exit` aborts any pending `process.stdout.write` calls, causing output to be truncated.  Therefore any code that parses the reported output will generate invalid results.
The existing code is almost identical to the "what not to do" example in the [`process.exit` docs](https://nodejs.org/api/process.html#process_process_exit_code):
```js
if (someConditionNotMet()) {
printUsageToStdout();
process.exit(1);
}
```
> The reason this is problematic is because writes to `process.stdout` in Node.js are usually *non-blocking* and may occur over multiple ticks of the Node.js event loop.  Calling `process.exit()`, however, forces the process to exit *before* those additional writes to `stdout` can be performed.
> …
> Avoid truncated stdout

- CHANGELOG.md
- src/rules/no-extra-semicolons/README.md
- src/rules/no-extra-semicolons/__tests__/index.js
Closes #1409 and closes #1389
Smoked tested locally using the CSS provided in those two configs. Looks good to me.
> Add tests for less mixin semicolons

- .travis.yml
Currently installing NodeJS modules in Travis CI takes anywhere between ~120 and ~180 seconds, this PR should eliminate most of that time
> Add `node_modules` caching support for Travis CI

- CHANGELOG.md
- src/rules/declaration-block-no-ignored-properties/README.md
- src/rules/declaration-block-no-ignored-properties/__tests__/index.js
- src/rules/declaration-block-no-ignored-properties/index.js
Close https://github.com/stylelint/stylelint/issues/1238
> `declaration-block-no-ignored-properties` now ignore `display: inline-block` with `float` property.

- package.json
- src/rules/no-unsupported-browser-features/README.md
- src/rules/no-unsupported-browser-features/__tests__/index.js
- src/rules/no-unsupported-browser-features/index.js
doiuse 2.4.0 updated the message format returned, this PR updates the one test message in our `no-unsupported-browser-features` tests that is affected.
https://github.com/anandthakker/doiuse/compare/v2.3.0...v2.4.0
Note: There are two spaces between `and` and `only` in the test, see https://github.com/anandthakker/doiuse/issues/48
> Updated `no-unsupported-browser-features` test message for doiuse 2.4.0

- CHANGELOG.md
- src/rules/unit-no-unknown/__tests__/index.js
- src/utils/__tests__/getUnitFromValueNode-test.js
- src/utils/getUnitFromValueNode.js
Close https://github.com/stylelint/stylelint/issues/1645
> Rules `unit-*` correctly handles browser hacks.

- CHANGELOG.md
- src/rules/at-rule-blacklist/index.js
- src/rules/at-rule-whitelist/index.js
- src/rules/comment-word-blacklist/index.js
- src/rules/selector-attribute-operator-blacklist/index.js
- src/rules/selector-attribute-operator-whitelist/index.js
Rules `at-rule-blacklist`, `at-rule-whitelist`, `comment-word-blacklist`, `selector-attribute-operator-blacklist`, `selctor-attribute-operator-whitelist` now accept array as first option.
Close https://github.com/stylelint/stylelint/issues/1644
> Some rules now accept array as first option.

- src/rules/at-rule-blacklist/README.md
- src/rules/at-rule-whitelist/README.md
- src/rules/selector-attribute-operator-blacklist/README.md
- src/rules/selector-attribute-operator-whitelist/README.md
There was an extra double quote in these 4 rule option docs:
https://github.com/stylelint/stylelint/tree/master/src/rules/at-rule-blacklist/README.md
https://github.com/stylelint/stylelint/tree/master/src/rules/at-rule-whitelist/README.md
https://github.com/stylelint/stylelint/tree/master/src/rules/selector-attribute-operator-blacklist/README.md
https://github.com/stylelint/stylelint/tree/master/src/rules/selector-attribute-operator-whitelist/README.md
This change brings the above files in line with the following rule option docs for consistency:
https://github.com/stylelint/stylelint/tree/master/src/rules/comment-word-blacklist/README.md
https://github.com/stylelint/stylelint/tree/master/src/rules/function-blacklist/README.md
https://github.com/stylelint/stylelint/tree/master/src/rules/fu …
> Remove superfluous quote from various rule options docs

- CHANGELOG.md
- src/__tests__/buildConfig-test.js
- src/__tests__/extends-test.js
- src/__tests__/fixtures/config-at-rule-empty-line-before.json
- src/buildConfig.js
Ref #1646.
Looks to me like this has probably been a longstanding bug that nobody's run into (and reported) yet.
In the diff here, most of the changes to test files are just minor refactoring I did while debugging some failing tests. The key here is the new test and the logic changes in `src/buildConfig.js`.
> Fix rule extension; closes #1646

- CHANGELOG.md
- src/rules/selector-class-pattern/__tests__/index.js
- src/rules/selector-class-pattern/index.js
Relates to #1583, #1513. `selector-class-pattern` was yielding false positive
for fractional keyframes. This commit fixes this issue, essentially copying
the work done in PR #1514.
> Ignore fractional keyframes in selector-class-pattern

- CHANGELOG.md
- src/rules/selector-no-type/README.md
- src/rules/selector-no-type/__tests__/index.js
- src/rules/selector-no-type/index.js
This PR addresses #1654.
These changes will automatically resolve nested selectors automatically if the `ignore: ["descendant"]` option is enabled. 
And since this is my first PR on this project, please let me know if there's anything else I may have missed or of there is any other pertinent information I should add to the PR.
```
❯ npm run benchmark-rule -- selector-no-type "[true, {\"ignore\": [\"descendant\"]}]"
Warnings: 406
Mean: 171.1881831515151 ms
Deviation: 38.763392889220015 ms
```
```
❯ npm run benchmark-rule -- selector-no-type "[true, {\"ignore\": [\"descendant\"]}]"
Warnings: 406
Mean: 156.6367916 ms
Deviation: 25.370745159382917 ms
```
> Changes `selector-no-type` to automatically resolve nested selectors when `ignore: ["descendant"]` option is enabled.

- src/rules/custom-media-pattern/README.md
- src/rules/custom-property-pattern/README.md
- src/rules/selector-class-pattern/README.md
- src/rules/selector-id-pattern/README.md
Closes #1650
I standardised on string options as JSON configs seem most popular.
> Clarify *-pattern rule options in docs

- src/rules/at-rule-name-newline-after/index.js
- src/rules/declaration-colon-newline-after/index.js
@jeddy3 @ntwb 
This two are not having `never` in their possible values. So there is no need of `rejectionAfter()` message. 
When we remove those two, the test coverage is increased to `100%`
> newline-after without never option - increased test coverage

- CHANGELOG.md
- src/rules/selector-combinator-space-after/__tests__/index.js
- src/rules/selector-combinator-space-after/index.js
- src/rules/selector-combinator-space-before/__tests__/index.js
Closes #1681
By switching to `style-search`’s broader [`parentheticals`](https://github.com/davidtheclark/style-search#parentheticals).
As an aside, I’m glad we have `style-search` and our `isStandardSyntax*` utils :)
> Ignore non-standard constructs in selector-combinator-space-*

- docs/user-guide/configuration.md
- src/rules/comment-empty-line-before/README.md
- src/rules/comment-no-empty/README.md
- src/rules/comment-whitespace-inside/README.md
- src/rules/comment-word-blacklist/README.md
Closes #1700. Closes #1628.
I went with “Caveat: xyz” as we’ve used it [before](https://github.com/stylelint/stylelint/blob/master/src/rules/font-family-name-quotes/README.md) to highlight a current limitation.
> Document selector and value list comment limitation

- src/rules/custom-property-empty-line-before/README.md
- src/rules/custom-property-empty-line-before/__tests__/index.js
- src/rules/custom-property-empty-line-before/index.js
Ref: https://github.com/stylelint/stylelint/pull/1694#issue-166875781
Last PR to go into `7.1`.
> Align custom-prop-empty-line-before with declaration variety

- src/rules/custom-property-empty-line-before/README.md
- src/rules/custom-property-empty-line-before/__tests__/index.js
- src/rules/custom-property-empty-line-before/index.js
- src/rules/declaration-empty-line-before/README.md
- src/rules/declaration-empty-line-before/__tests__/index.js
- src/rules/declaration-empty-line-before/index.js
Ref: https://github.com/stylelint/stylelint-config-standard/pull/32#issuecomment-235297574
Using these options in `config-standard`, rather than `except`, will be a little less restrictive and inline with how we handle preceding comments for other `*-empty-line-before` rules.
> Add ignore: ["after-comment"] option to *-empty-line-before

- src/rules/selector-type-no-unknown/index.js
Closes #1733.
I checked the other `*-no-unknown` rules. This was the only one where I forgot to remove old ignore code.
> Remove redundant ignore code from selector-type-no-unknown

- package.json
- src/__tests__/standalone-test.js
See: https://github.com/eslint/eslint/blob/master/README.md#semantic-versioning-policy
And: https://github.com/eslint/eslint/issues/6795
> Use tilde for eslint dependency

- CHANGELOG.md
- src/rules/at-rule-empty-line-before/README.md
- src/rules/at-rule-empty-line-before/__tests__/index.js
- src/rules/at-rule-empty-line-before/index.js
Closes #1366
The diff changes for the ignore option of the README is just because I ordered the options alphabetically to be consistent with the `except` options (and in other rule READMEs).
> Add except: blockless-after-same-name-blockless option

- CHANGELOG.md
- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
- package.json
- src/__tests__/fixtures/needlessDisables/disabled-ranges-1.css
- src/__tests__/fixtures/needlessDisables/disabled-ranges-2.css
- src/__tests__/ignoreDisables-test.js
- src/__tests__/needlessDisables-test.js
- src/cli.js
- src/formatters/__tests__/needlessDisablesStringFormatter-test.js
- src/formatters/needlessDisablesStringFormatter.js
- src/needlessDisables.js
- src/postcssPlugin.js
- src/standalone.js
- src/utils/report.js
Ref #1184. cc @jonrohan
I've done several things here, all pointing towards the goal of #1184:
- Added an `ignoreDisables / --ignore-disables` option which you can use to ignore your `stylelint-disable` comments and see what lint results would be like without them.
- Added a `reportNeedlessDisables / --report-needless-disables` option to CLI and Node API (not the PostCSS plugin) which you can use to get a report of which `stylelint-disable` comments are not actually protecting you from any lint warnings.
- Added a little string formatter for the needless disables so that from the CLI you get nice legible output. Looks like this:
```
src/__tests__/fixtures/needlessDisables/disabled-ranges-1.css
start: 1, end: 3
start: 5, end: 7
start: 10, end: 10 …
```
> Add ignoreDisableComments and reportNeedlessDisables

- src/rules/unit-no-unknown/README.md
Just a little doc fix, looks like the option is really ignoreUnits: https://github.com/stylelint/stylelint/blob/master/src/rules/unit-no-unknown/index.js#L25
> Fix ignoreUnits option being listed as ignoreTypes

- src/rules/at-rule-no-vendor-prefix/__tests__/index.js
- src/rules/comment-word-blacklist/__tests__/index.js
- src/rules/declaration-block-semicolon-space-after/__tests__/index.js
- src/rules/function-comma-newline-after/__tests__/index.js
- src/rules/function-max-empty-lines/__tests__/index.js
- src/rules/function-url-data-uris/__tests__/index.js
- src/rules/function-url-no-scheme-relative/__tests__/index.js
- src/rules/function-url-quotes/__tests__/index.js
- src/rules/keyframe-declaration-no-important/__tests__/index.js
- src/rules/no-empty-source/__tests__/index.js
- src/rules/selector-attribute-operator-space-after/__tests__/index.js
- src/rules/selector-attribute-operator-space-before/__tests__/index.js
- src/rules/selector-max-empty-lines/__tests__/index.js
- src/rules/selector-no-qualifying-type/__tests__/index.js
- src/rules/selector-pseudo-class-parentheses-space-inside/__tests__/index.js
- src/rules/time-no-imperceptible/__tests__/index.js
- src/rules/value-keyword-case/__tests__/index.js
- src/rules/value-list-max-empty-lines/__tests__/index.js
It would be good to add `no-multi-spaces` in `eslint-config-stylelint`.
> Chore: correction stylistic errors.

- src/rules/unit-blacklist/__tests__/index.js
- src/rules/unit-case/__tests__/index.js
- src/rules/unit-no-unknown/__tests__/index.js
- src/rules/unit-whitelist/__tests__/index.js
Ref: https://github.com/stylelint/stylelint/issues/1773 https://github.com/stylelint/stylelint/issues/1771
> Chore: add tests to check units with and without leading zero to `unit-*` rules

- src/rules/selector-combinator-space-after/README.md
- src/rules/selector-combinator-space-before/README.md
> Docs: fixed typos `descendent` to `descendant`.

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/reference/keywordSets.js
- src/rules/index.js
- src/rules/media-feature-name-no-unknown/README.md
- src/rules/media-feature-name-no-unknown/__tests__/index.js
- src/rules/media-feature-name-no-unknown/index.js
Close https://github.com/stylelint/stylelint/issues/1698
/cc @davidtheclark @jeddy3 
Two question:
1. Should we test `scss` and `less` in this rule? (maybe be remove all non standard syntax tests and have tests only in `isStandard*`, it is decrease tests and do this more readable and supported, we can do this in future major release).
2. In all `*-no-unknown` rules, excluding `property-no-unknown`, we ignore all vendor specific construction, we have to deal with the matter - we ignore or not vendor specific construction in `*-no-unknown` rules. I vote for check vendor specific everywhere and add options `ignoreVendor: true|false`(maybe other name) to disable check. In future major release we can change behavior this rules. Often code have vendor prefixes, which can't handle autoprefixer …
> Added: new rule `media-feature-name-no-unknown`.

- src/rules/selector-type-no-unknown/__tests__/index.js
Closes #1791
My bad, I totally didn’t see the missing semicolon in code.
> Add custom-property-set test to selector-type-no-unknown

- CHANGELOG.md
- src/rules/root-no-standard-properties/__tests__/index.js
- src/rules/root-no-standard-properties/index.js
Closes #1789
Replaces https://github.com/stylelint/stylelint/pull/1794
The new tests were failing even with the correct syntax i.e. colon and semicolon. So, patch was needed.
> Fix custom property sets in root-no-standard-properties

- src/rules/selector-attribute-operator-blacklist/__tests__/index.js
- src/rules/selector-attribute-operator-whitelist/__tests__/index.js
- src/rules/unit-blacklist/README.md
- src/rules/unit-blacklist/__tests__/index.js
- src/rules/unit-whitelist/README.md
- src/rules/unit-whitelist/__tests__/index.js
I noticed a couple of docs inconsistencies while working on #1807. This updates the docs and adds a few basic tests to ensure that rules that accept `array` or `string` will work as expected when passed a `string`.
> Document and test `string` options for rules that accept `array`|`string`

- package.json
It appears to be unneeded and removing it halves the npm package size.
Ref: https://github.com/mxstbr/react-boilerplate/issues/893
> Remove src folder from npm package

- src/rules/media-feature-name-no-vendor-prefix/README.md
`media-feature-name-no-vendor-prefix` was styling both set of examples invalid as it looks for the exact phrase (https://github.com/stylelint/stylelint.io/blob/f38a22e9a234f1a314982d56926ae6f5d172a0ce/web_modules/layouts/Page/index.js#L10).
> Add colon to trigger valid-pattern style in docs.

- src/__tests__/buildConfig-test.js
- src/__tests__/fixtures/config-relative-plugin-nested.json
- src/__tests__/fixtures/nested-plugin/plugin-nested-warn-about-foo.js
- src/buildConfig.js
Initial work on issue #1801
I'm not confident that these two tests are comprehensive. I wonder if splitting `augmentConfig` (and associated functions) out into a separate util would make this easier to test?
Refs #1801
> Allow `configFile` and `configBasedir` to be used together

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/declaration-block-no-redundant-longhand-properties/README.md
- src/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
- src/rules/declaration-block-no-redundant-longhand-properties/index.js
- src/rules/index.js
Close https://github.com/stylelint/stylelint/issues/1735.
/cc @davidtheclark @jeddy3 @ntwb 
Maybe add tests to check on non standard syntax? or it is overly?
> Add declaration-block-no-redundant-longhand-properties

- package.json
To our standard “PR: review needed” one.
It’ll save us click or two each time :)
> Update the greenkeeper label

- CHANGELOG.md
- src/__tests__/fixtures/needlessDisables/.stylelintignore
- src/__tests__/fixtures/needlessDisables/ignored-file.css
- src/__tests__/needlessDisables-test.js
- src/needlessDisables.js
Close https://github.com/stylelint/stylelint/issues/1867.
> Fixed: `--ignore-path` and `--report-needless-disables` no longer fails when used together.

- CHANGELOG.md
- src/rules/indentation/__tests__/rules.js
- src/rules/indentation/index.js
Close https://github.com/stylelint/stylelint/issues/1787.
> Fixed: the `indentation` rule now correctly handles `_` hacks on property names.

- CHANGELOG.md
- src/rules/block-no-single-line/__tests__/index.js
- src/rules/block-no-single-line/index.js
> Fixed: `block-no-single-line` now ignores empty blocks (#1828)

- CHANGELOG.md
- src/rules/declaration-block-no-ignored-properties/__tests__/index.js
- src/rules/declaration-block-no-ignored-properties/index.js
Follow up of #1880. Sorry, I somehow messed up the rebase, and had to create a new branch.
> Fixed: False positives when triggering property is overriden in declaration-block-no-ignored-properties

- CHANGELOG.md
- src/rules/block-closing-brace-newline-after/README.md
- src/rules/block-closing-brace-newline-after/__tests__/index.js
- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-closing-brace-space-after/README.md
- src/rules/block-closing-brace-space-after/__tests__/index.js
- src/rules/block-closing-brace-space-after/index.js
> Allow a trailing semicolon in block-closing-brace-*-after (#1806)

- CHANGELOG.md
- src/utils/__tests__/isStandardSyntaxDeclaration-test.js
- src/utils/isStandardSyntaxDeclaration.js
Should closes #1914
Not sure why but until I update t.plan I got no failure by doing `babel-tape-runner src/utils/__tests__/isStandardSyntaxDeclaration-test.js`: the test was just not in the result, this was a weird experience :)
> Fixed: regression of 7.3.0 which caused a "Cannot read property 'length' of undefined" error on certain selector

- src/rules/custom-property-empty-line-before/README.md
Just a small formatting fix in the README.md of `custom-property-empty-line-before`
[Visible on the corresponding stylelint.io page](http://stylelint.io/user-guide/rules/custom-property-empty-line-before/)
> Fix minor formatting problem in documentation

- src/rules/no-unknown-animations/__tests__/index.js
- src/rules/no-unknown-animations/index.js
Close https://github.com/stylelint/stylelint/issues/1902
> Fixed: `no-unknown-animations` no longer delivers false positives for multiple animation names

- src/rules/function-url-quotes/README.md
- src/rules/function-url-quotes/__tests__/index.js
- src/rules/function-url-quotes/index.js
`function-url-quotes` rule throw error `Expected quotes around url-prefix argument` when no arguments in brackets.
Example:
```css
@-moz-document url-prefix() { // Error: Expected quotes around url-prefix argument
/* styles for Firefox */
}
```
> Fix error when no args in url-prefix() brackets

- src/rules/declaration-block-properties-order/README.md
- src/rules/declaration-block-properties-order/__tests__/flat.js
Closes #1751
I think how we handle proprietary browser and user-defined properties within `declaration-block-properties-order` is fine. 
This PR adds tests for a user-defined shorthand property, and adds an example to the README that shows this and how all properties, regardless of whether they are proprietary or standard, should be unprefixed in the config.
> Clarify proprietary browser and user-defined properties configuration

- src/__tests__/fixtures/config-no-pixels.json
- src/__tests__/integration.js
- src/__tests__/normalizeRuleSettings-integration-test.js
- src/__tests__/normalizeRuleSettings-test.js
- src/utils/__tests__/validateOptions-test.js
- src/utils/validateOptions.js
Fixes #1964 and adds several tests to prevent future regressions.
Most of the diff in `validateOptions.js` is the result of pulling an unnecessarily nested function to the top level. The key difference is that I added this line (47):
```js
if (actual === null || _.isEqual(actual, [null])) { return }
```
@jeddy3: If you think this looks good let's release the patch right away.
> Fix option validation of null

- src/rules/block-no-empty/__tests__/index.js
- src/rules/block-no-empty/index.js
- src/utils/beforeBlockString.js
Ref https://github.com/stylelint/stylelint/issues/1889
We don't use `raw()`, because it is call `stringify` (https://github.com/postcss/postcss/blob/979409b215bc70f5b69efe49a09dbc703642babe/lib/node.es6#L378) and return wrong node (`.a` -> `.a{}`)
> Fixed: `block-no-empty` warning positioning when using SugarSS parser.

- src/rules/no-missing-end-of-source-newline/__tests__/index.js
- src/rules/no-missing-end-of-source-newline/index.js
Ref https://github.com/stylelint/stylelint/issues/1892
> Fixed: `no-missing-end-of-source-newline` warning positioning when using SugarSS parser.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Single comment block.
Q&A format.
Remove the checklist as confusing i.e. it looks like their are two remaining tasks when one of the items is checked.
> Make the issue and pr templates consistent

- src/__tests__/standalone-test.js
- src/getConfigForFile.js
Closes #1985.
If no config is found relative to the file being linted, we look for a config relative to `process.cwd()`.
> If no file config found lookup from process.cwd

- src/__tests__/disableRanges-test.js
- src/assignDisabledRanges.js
Closes #1917. Also adds better error handling to the `disabledRanges-test` tests.
> Better nested disabled ranges

- src/reference/keywordSets.js
https://github.com/stylelint/stylelint/issues/1997
Ref to properties and their values:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-rendering
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/image-rendering
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events
> Fixed: false positives for some properties in `value-keyword-case`.

- src/rules/function-calc-no-unspaced-operator/__tests__/index.js
- src/rules/function-calc-no-unspaced-operator/index.js
> Fixed: false positives for hyphenated function names in `function-calc-no-unspaced-operator`.

- src/rules/no-descending-specificity/__tests__/index.js
- src/rules/no-descending-specificity/index.js
> `no-descending-specificity` - added exception for custom property sets

- src/formatters/stringFormatter.js
- src/formatters/verboseFormatter.js
> Remove explicit gray color and use dim instead

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- src/rules/font-family-no-duplicate-names/README.md
- src/rules/font-family-no-duplicate-names/__tests__/index.js
- src/rules/font-family-no-duplicate-names/index.js
- src/rules/index.js
> Add font-family-no-duplicate-names rule

- src/utils/isStandardSyntaxRule.js
> Chore: use `isStandardSyntaxRule` instead pure check.

- src/rules/at-rule-empty-line-before/index.js
- src/rules/block-closing-brace-empty-line-before/index.js
- src/rules/block-closing-brace-newline-after/index.js
- src/rules/block-closing-brace-newline-before/index.js
- src/rules/comment-empty-line-before/index.js
- src/rules/declaration-block-properties-order/index.js
- src/rules/declaration-block-semicolon-newline-after/index.js
- src/rules/declaration-block-semicolon-newline-before/index.js
- src/rules/declaration-block-semicolon-space-after/index.js
- src/rules/declaration-block-semicolon-space-before/index.js
- src/rules/declaration-colon-newline-after/index.js
- src/rules/declaration-colon-space-after/index.js
- src/rules/indentation/index.js
- src/rules/max-empty-lines/index.js
- src/rules/rule-non-nested-empty-line-before/index.js
- src/utils/atRuleParamIndex.js
- src/utils/rawNodeString.js
no
We don't use `raw()` because it is call `stringify` and return `stringifier` value, it is potential error in all non-standard syntax, special `sugarss`. Related commit: https://github.com/stylelint/stylelint/commit/f4bd57a0c4aaa0faae36eb71a88a956102497d19 .
/cc @davidtheclark @jeddy3 
I think we should add note about this in docs.
> Chore: use `raws` instead `raw()`.

- src/rules/selector-no-qualifying-type/__tests__/index.js
- src/rules/selector-no-qualifying-type/index.js
https://github.com/stylelint/stylelint/issues/2041
> Fixed: `selector-no-qualifying-type` rule now ignore SCSS placeholder selectors.

- .travis.yml
In https://github.com/stylelint/stylelint/commit/d4e461552324b37067b6e8582914bbafbf4f23a1 Travis CI _cache maintainence_ `npm prune`, and `npm update` along with Coveralls support via `npm run coveralls` was removed, this PR restores this functionality.
> Restore Travis CI NPM Cache & Coveralls setup

- .travis.yml
I've added some Travis CI environment variables to the build matrix.
I've added these as "hacky docs labels"  as when investigating Travis CI builds there is are no "labels" per se describing what each of the 5 jobs are, at the moment differentiating between which of the 3 NodeJS jobs are running what task (lint+flow, jest, or test) is guess work:
By adding these "hacky environment labels" we can now identify which npm task is ran by each job a little quicker:
p.s. These have no effect on the actual Travis CI jobs
> Add `env` values to Travis CI

- decls/stylelint.js
- src/__tests__/standalone.test.js
- src/cli.js
- src/standalone.js
#2048 
FIrst pass at this, welcome comments on coding conventions, styles etc.
> [2048] - Adds cli argument to fail silently when no files matched

- package.json
- src/formatters/stringFormatter.js
> fix(package): update table to version 4.0.1

- src/rules/comment-whitespace-inside/__tests__/index.js
- src/rules/comment-whitespace-inside/index.js
- system-tests/001/__snapshots__/001.test.js.snap
#2120
I opted for a regexp to check for any kind of whitespace so it will accept tabs as well. Let me know if you want tests for tabs too.
> Allow leading newlines for source map and copyright comments

- src/rules/selector-max-compound-selectors/__tests__/index.js
- src/rules/selector-max-compound-selectors/index.js
- src/utils/isStandardSyntaxRule.js
https://github.com/stylelint/stylelint/issues/2093
I believe that the rule does not work correctly and we should fix this in `8.0.0`.
Example:
```scss
.foo .bar > .foobar { & .test { @media screen { color: red; } } }
```
We this line use for check on nested
```if (rule.nodes.some(node => node.type === "rule" || node.type === "atrule")) { return }```
And we get:
1. We use `walkRules`.
2. Here we have 2 selector `.foo .bar > .foobar` and `& .test`
First selector have `nodes` and return.
Second selector have `nodes` and return.
But we should get error here.
Also rule don't work with nested properties.
> Fixed: false positives Scss selector with nested properties.

- src/__tests__/standalone.test.js
- src/lintSource.js
Closes #2064.
This was a little tricky to track down and fix without breaking other tests, but I think I got it.
The key is that we need to anticipate non-existent files in `lintSource` if `code` and `codeFilename` are being used.
> Allow non-existent codeFilenames

- src/rules/selector-max-compound-selectors/README.md
> Fixed: typo in `selector-max-compound-selectors` docs.

- src/rules/block-opening-brace-newline-after/README.md
> Fixed: typo in `block-opening-brace-newline-after` docs.

- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
- lib/rules/selector-pseudo-class-no-unknown/index.js
- lib/utils/__tests__/isCustomSelector-test.js
- lib/utils/isCustomSelector.js
#2141
First commit proves it's failing. 2nd fix it.
Hope I fixed this the right way.
Closes #2141
> Fixed: False positive for custom selectors in `selector-pseudo-class-no-unknown` #2141

- lib/cli.js
- system-tests/004/004.test.js
- system-tests/004/stylelint.config.js
Fixes #2115 
When there is an error in require() in configuration file, cli gets an error code which is not actually integer, so passing it to process.exit is not a good idea.
Now value is getting checked if it's a number or not, and if it's not a number, it's replaced with plain `1`.
System test added that runs cli in ensures that exit code != 0
> Handle non-integer error codes as exit code 1 (#2115)

- docs/developer-guide/rules.md
- package.json
As an aside, by default I think the `--watch` is only suppose to run the tests on _changed_ files. However, it currently triggers a complete run on my machine. Perhaps I'm missing something?
> Updates docs for testing set of rules

- lib/__tests__/ignore.test.js
- lib/isPathIgnored.js
- lib/standalone.js
Closes #2149.
Managed to reproduce that problem in a test case, and made it pass. I'm not sure if this feature ever worked *before* in the PostCSS plugin; but we always intended it to, assumed it did, so I'd consider this a bug fix.
cc @simonsmith
> Ignore node_modules effectively

- .travis.yml
- appveyor.yml
- package.json
Now that Tape was removed in #2158 there's no need for multiple `tape:*` scripts.
> Simplify NPM test scripts now that Tape has been removed

- lib/cli.js
#2184
No.
Fixes #2184
This change states that --allow-empty-input, --color, --help,
--ignore-disables, --no-color, --quiet, --version has no arguments
> CLI: Mark some parameters as booleans explicitly

- docs/developer-guide/formatters.md
- lib/__tests__/formatters.test.js
- lib/index.js
#2181
Not really, I added a basic test. Let me know if you want something more.
> Expose available formatters in the Node API

- lib/rules/checkRuleEmptyLineBefore.js
- lib/rules/rule-nested-empty-line-before/README.md
- lib/rules/rule-nested-empty-line-before/__tests__/index.js
- lib/rules/rule-nested-empty-line-before/index.js
> Add except: ["after-rule"] to rule-nested-empty-line-before

- docs/developer-guide/plugins.md
- lib/index.js
- lib/normalizeRuleSettings.js
- lib/testUtils/createRuleTester.js
- lib/utils/__tests__/checkAgainstRule.test.js
- lib/utils/checkAgainstRule.js
Here's an idea to solve #2139.
It exposes another function `stylelint.checkAgainstRule`, which you can use to run a PostCSS `Root` object through a rule, and invoke a callback with every warning that is created.
What I'd like to see in a situation liked #2139 is that the plugin rule that uses a core rule is the only one that calls `report()`. *It* is the reporting rule, and its severity should be used.
I have not yet added documentation, but did add some tests.
@hudochenkov would you please try this branch out and see if it works for your use-case?
@stylelint/core any input on this?
> Add checkAgainstRule util

- lib/rules/color-named/__tests__/index.js
- lib/rules/color-named/index.js
https://github.com/stylelint/stylelint/issues/2009
> Ignore maps and lists in color-named

- lib/isPathIgnored.js
- lib/utils/getIsFileIgnored.js
- package.json
None, this is to switch to using `micromatch`.
The PR is straight forward, however, [this section](https://github.com/jonschlinkert/micromatch#why-switch-to-micromatch) in the `micromatch` readme provides some of the benefits of switching to `micromatch`.
> update to use micromatch

- docs/user-guide/node-api.md
- lib/augmentConfig.js
- lib/lintSource.js
- lib/postcssPlugin.js
- lib/standalone.js
Closes #2194, closes #2195.
Although this does not add more tests, it does add some errors that break things (causing tests to fail) if absolute paths are for some reason not coming through. More focused unit tests looked like more trouble to figure out than they were worth, so I think this does the trick.
I'd like to cut a release for this as soon as possible, so processors stop failing. How about finishing up this and #2197 and then releasing?
> Ensure absolute paths to processors

- lib/rules/selector-attribute-operator-space-before/README.md
Just a typo fix 👍 
"... single before after the operator." –> "... single space before the operator."
> Typo Correction

- lib/rules/at-rule-empty-line-before/README.md
- lib/rules/at-rule-empty-line-before/__tests__/index.js
- lib/rules/at-rule-empty-line-before/index.js
#2211
Maybe `"after-same-name"` should be placed before `"blockless-after-same-name-blockless"` in docs, because of its broader nature?
Should I add `ignore: ["after-same-name"]` also?
> Add except: ["after-same-name"] option to at-rule-empty-line-before

- .github/ISSUE_TEMPLATE.md
https://github.com/stylelint/stylelint/issues/2256
I didn't check the v8 changelog before creating a duplicate bug report. Having this message in the issue template could help prevent myself and others from doing that in the future.
> Added milestones and issue search links to the issue template

- lib/rules/max-nesting-depth/README.md
- lib/rules/max-nesting-depth/__tests__/deprecate-at-rules-without-declaration-blocks.js
- lib/rules/max-nesting-depth/__tests__/index.js
- lib/rules/max-nesting-depth/index.js
- system-tests/deprecations/002/__snapshots__/002.test.js.snap
- system-tests/deprecations/002/config.json
> Rename "at-rules-without-declaration-blocks" to "blockless-at-rules" in max-nesting-depth

- system-tests/005/__snapshots__/005.test.js.snap
- system-tests/005/config.json
Regarding the system test 005 added in #2192
The rule `value-no-vendor-prefix` was added with the incorrect option `always` rather than `true`
@m-allanson Do you remember if you explicitly added the invalid option to explicitly test the _invalid option_ syntax? 
Here's the [snapshot message](https://github.com/stylelint/stylelint/blob/master/system-tests/005/__snapshots__/005.test.js.snap#L11-L13):
```
"text": "Unexpected option value \"always\" for rule \"value-no-vendor-prefix\"",
```
Similarly, the same case for the `selector-pseudo-element-no-unknown` rule, [snapshot message](https://github.com/stylelint/stylelint/blob/master/system-tests/005/__snapshots__/005.test.js.snap#L9):
```
"text": "Unexpected option value \"always\" for rule \"selector-pseudo-element-no-unknown\"",
```
If …
> Maybe update invalid rule options in system test 005?

- .gitignore
- .travis.yml
- package.json
I heard ESLint can do caching via #2270
```shell
> eslint . --cache
5.16 real         5.34 user         0.25 sys
```
Subsequent runs are approx 3 times faster
2nd run
```
> eslint . --cache
1.78 real         1.69 user         0.16 sys
```
3rd run
```
> eslint . --cache
1.78 real         1.69 user         0.17 sys
```
cc @sergesemashko
> Setup ESLint for local caching

- lib/__tests__/standalone.test.js
- lib/augmentConfig.js
Closes #2280.
Adds a test that failed before the small change, reflecting the bug in #2280. 
cc @veej
> Fix extends in configOverrides

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/time-min-milliseconds/README.md
- lib/rules/time-min-milliseconds/__tests__/index.js
- lib/rules/time-min-milliseconds/index.js
> Add "time-min-milliseconds" rule

- lib/reference/keywordSets.js
- lib/rules/unit-no-unknown/__tests__/index.js
> Add fr to known units

- docs/user-guide/rules.md
https://github.com/stylelint/stylelint/pull/2309#discussion_r98871345
These rules still in stylelint, despite the fact they are deprecated. When user will see a deprecation message, she may want to read what this rule for. But it will be very difficult to find.
> Put back links to deprecated rules

- docs/user-guide/configuration.md
If my understanding of the default behavior is correct.
> Add a note that node_modules and bower_components are always ignored

- lib/rules/color-hex-case/__tests__/index.js
- lib/rules/color-hex-case/index.js
> Fixed: `color-hex-case` rule is now respect SVG reference interaction.

- lib/rules/shorthand-property-no-redundant-values/__tests__/index.js
> Tests: `shorthand-property-no-redundant-values` rule produces normal message (#2330).

- lib/rules/max-line-length/__tests__/index.js
- lib/rules/max-line-length/index.js
> Fixed: `max-line-length` rule is now reported correct column for `SASS` comments.

- lib/rules/selector-class-pattern/__tests__/index.js
- lib/rules/selector-class-pattern/index.js
#2334
For `selector-class-pattern`.
> Fixed: false positives for resolved and interpolated selectors in `selector-class-pattern`.

- lib/alwaysIgnoredGlobs.js
- lib/isPathIgnored.js
- lib/standalone.js
This improves the performance greatly in projects where we have a lot of dependencies in node modules.
e.g. "#000" or "None, as it's a documentation fix."
> exclude always ignored globs from globby search.

- lib/rules/selector-max-compound-selectors/__tests__/index.js
- lib/rules/selector-max-compound-selectors/index.js
#2136
The only way I see to avoid incorrectly resolved selector in custom syntaxes is report every resolved selector rather the deeper one. Because variation of nesting may be very different.
I have a question about testing new behaviour. The rule now produced more than one warning and we should test for more than one warning. E. g. [this test](https://github.com/stylelint/stylelint/blob/db2098115a3b53fbc1a2c218328159701057b649/lib/rules/selector-max-compound-selectors/__tests__/index.js#L177) produce two warnings, but we can test only the first one.
> Report every selector resolved selector in selector-max-compound-selectors

- lib/rules/max-line-length/README.md
- lib/rules/max-line-length/__tests__/index.js
- lib/rules/max-line-length/index.js
#2219 
Pretty straightforward.
> Adds ignorePattern option to max-line-length

- docs/developer-guide/plugins.md
- lib/__tests__/fixtures/plugin-async.js
- lib/__tests__/plugins.test.js
- lib/lintSource.js
PR with the intention of solve #2296: add support for async rules.
> Add support for async rules

- lib/__tests__/standalone.test.js
- lib/standalone.js
Issue #2251 
The formatting of multiple filenames/globs into a string is non-trivial. I addressed this with an immediately-executing anonymous function in the globby promise handler, because I wasn't sure if there's a standard place pure helper functions like this. Let me know if it could be improved.
> Print out filenames/globs when files do not exist

- lib/rules/no-extra-semicolons/__tests__/index.js
- lib/rules/no-extra-semicolons/index.js
#2395
Just failing tests. Have no time to look into the problem yet.
> Fix custom properties sets followed by comments in no-extra-semicolons

- lib/reference/keywordSets.js
- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
- lib/utils/__tests__/isCounterResetCustomIdentValue.test.js
- lib/utils/isCounterResetCustomIdentValue.js
> Fixed: `value-keyword-case` is now ignore counter-reset property and counter, counters and attr functions.

- .gitignore
None.
Jest can make coverage reports. It's not convenient to delete them every time. Also there is no `nyc` in the project.
> gitignore coverage report

- docs/user-guide/configuration.md
- lib/cli.js
Turns out cosmiconfig supports the .yml extension so it's worth mentioning it.
> Docs: Mention supported .yml extension for config files

- jest-setup.js
- lib/rules/function-comma-newline-after/__tests__/index.js
- lib/rules/function-comma-newline-before/__tests__/index.js
- lib/rules/function-comma-space-after/__tests__/index.js
- lib/rules/function-comma-space-before/__tests__/index.js
- lib/rules/function-url-quotes/__tests__/index.js
- lib/rules/selector-no-type/__tests__/index.js
- lib/rules/unit-no-unknown/__tests__/index.js
`testRule` is not fully reliable. It won't catch `rejected` test case if this test case has no `message`, `line`, and `column` defined. For example, it's possible to put any `accepted` test case with `code` property only to `rejected` array. And this test would pass!
To find unreliable tests I wrote two custom matchers. I'm not sure which one is better.
Some tests are failing now, and it's a result of improved test reliability. I'll fix failing tests as soon better matcher is chosen.
What matcher is better? Should I change selected matcher's message?
> Improve testRule reliability

- lib/rules/max-empty-lines/README.md
- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-empty-lines/index.js
Add ignore: ["comments"] option to max-empty-lines
fixes #2356 
Adds ignore comments option to max-empty-lines
> Add ignore: ["comments"] option to max-empty-lines

- decls/stylelint.js
- docs/user-guide/cli.md
- docs/user-guide/node-api.md
- lib/__tests__/fixtures/cache/valid.css
- lib/__tests__/standalone-cache.test.js
- lib/cli.js
- lib/standalone.js
- lib/utils/FileCache.js
- lib/utils/getCacheFile.js
- lib/utils/hash.js
- package.json
https://github.com/stylelint/stylelint/issues/2270
UPDATED:
Tests are ~~in progress~~ **done**.
~~I decided to submit a PR for initial feedback before going too deep into woods with tests.~~
New dependencies:
- [debug](https://www.npmjs.com/package/debug) - for easy debugging/execution time profiling. To profile lint time just prefix you stylelint command with `DEBUG=stylelint:standalone stylelint "*.scss"`
- [imurmurhash](https://www.npmjs.com/package/imurmurhash) - see [eslint requires nodejs built with ssl support #5522](https://github.com/eslint/eslint/issues/5522)
- [file-entry-cache](https://www.npmjs.com/package/file-entry-cache) - required to get and cache file metadata
- …
> Implement caching

- lib/cli.js
#2325 
It is very strange :smile:  `reportNeedlessDisables` can be only `true` or `false`.
/cc @jeddy3 @davidtheclark
> Fixed: `report-needless-disables` argument is now exit with non-zero code.

- lib/rules/function-url-scheme-whitelist/index.js
https://github.com/stylelint/stylelint/issues/2446
For some strange reason it wasn't defined, that rule can accept an array as primary option. Test didn't break, though. I wonder why? I believe we should have tests to test this behavior, but I have no idea how to do them.
I've tested results before and after this change via Node API. It stopped throwing warnings.
> Fix not specified array as primary option for "function-url-scheme-whitelist"

- lib/testUtils/__tests__/createRuleTester.test.js
- lib/testUtils/createRuleTester.js
When creating a `ruleTester`, a `schema` can be passed in the test setup, e.g.:
```js
const postCssModuleValues = require('postcss-modules-values');
{
preceedingPlugins: [postCssModuleValues],
ruleName: cssImportsOrder.ruleName,
config: { preset: 'suit' },
skipBasicChecks: true,
accept: [...]
reject: [...]
}
```
when using `preceedingPlugins`, this currently fails with: 
```
Uncaught TypeError: Cannot read property 'plugins' of undefined
at use (node_modules/postcss/lib/processor.js:86:24)
at Array.forEach (native)
at postcssProcess (node_modules/stylelint/lib/testUtils/createRuleTester.js:163:32)
at passingTestCases.forEach.acceptedCase (node_modules/stylelint/lib/testUtils/createRuleTester.js:179:29)
at Array.forEach (native)
at …
```
> fix: keep scope when using `schema.preceedingPlugins`

- lib/rules/at-rule-blacklist/__tests__/index.js
- lib/rules/at-rule-whitelist/__tests__/index.js
- lib/rules/comment-word-blacklist/__tests__/index.js
- lib/rules/function-blacklist/__tests__/index.js
- lib/rules/function-url-scheme-whitelist/__tests__/index.js
- lib/rules/function-whitelist/__tests__/index.js
- lib/rules/property-blacklist/__tests__/index.js
- lib/rules/property-whitelist/__tests__/index.js
- lib/rules/selector-attribute-operator-blacklist/__tests__/index.js
- lib/rules/selector-attribute-operator-whitelist/__tests__/index.js
- lib/rules/selector-pseudo-class-blacklist/__tests__/index.js
- lib/rules/selector-pseudo-class-whitelist/__tests__/index.js
- lib/rules/unit-blacklist/__tests__/index.js
- lib/rules/unit-whitelist/__tests__/index.js
Relates to #2459, followup to #2447.
@hudochenkov, I think this is what should be done for every rule with `primaryOptionArray`: ensure there is a test that would fail if the primary option were not interpreted correctly.
Without `rule.primaryOptionArray` for `function-ur-schema-whitelist`, this test will fail, because it relies on a correct interpretation of the array as the primary option. *With* `rule.primaryOptionArray` in that rule, the test passes.
All `primaryOptionArray` rules should have something similar.
> Exemplify testing of primaryOptionArray

- docs/user-guide/complementary-tools.md
Flycheck is a popular syntax checking extension for Emacs. It recently added support for stylelint.
See: https://github.com/flycheck/flycheck/pull/903
I did not create an issue because it is just a minor addition to the documentation. Hope that is OK 😌
> Add Flycheck to the list of editor plugins

- docs/user-guide/rules.md
I think it is better to keep them highlighted.
> Made all instances of (deprecated) bold

- lib/rules/selector-type-no-unknown/README.md
- lib/rules/selector-type-no-unknown/__tests__/index.js
- lib/rules/selector-type-no-unknown/index.js
- package.json
> Fixed: `selector-type-no-unknown` now ignores MathML tags.

- lib/rules/length-zero-no-unit/__tests__/index.js
- lib/rules/length-zero-no-unit/index.js
> Fixed: `length-zero-no-unit` now correctly handles newlines and no spaces after colon.

- docs/user-guide/plugins.md
- docs/user-guide/rules.md
- lib/rules/no-unsupported-browser-features/README.md
- lib/rules/no-unsupported-browser-features/__tests__/index.js
- lib/rules/no-unsupported-browser-features/index.js
- system-tests/005/__snapshots__/005.test.js.snap
- system-tests/deprecations/001/__snapshots__/001.test.js.snap
None, as it's an addition to the documentation (added the new no-unsupported-browser-features plugin to docs).
Don't think so. Just added the new plugin for discoverability.
> Add no-unsupported-browser-features plugin to docs

- README.md
- decls/postcss.js
- decls/stylelint.js
- docs/developer-guide/rules.md
- docs/user-guide/cli.md
- docs/user-guide/node-api.md
- docs/user-guide/rules.md
- jest-setup.js
- lib/cli.js
- lib/lintSource.js
- lib/rules/at-rule-name-case/README.md
- lib/rules/at-rule-name-case/__tests__/index.js
- lib/rules/at-rule-name-case/index.js
- lib/rules/comment-empty-line-before/README.md
- lib/rules/comment-empty-line-before/__tests__/index.js
- lib/rules/comment-empty-line-before/index.js
- lib/standalone.js
- lib/utils/__tests__/addEmptyLineBefore.test.js
- lib/utils/__tests__/removeEmptyLineBefore.test.js
- lib/utils/addEmptyLineBefore.js
- lib/utils/checkAgainstRule.js
- lib/utils/findAtRuleContext.js
- lib/utils/removeEmptyLinesBefore.js
- package.json
- system-tests/fix/__snapshots__/fix.test.js.snap
- system-tests/fix/config.json
- system-tests/fix/fix.test.js
- system-tests/fix/stylesheet.css
- system-tests/systemTestUtils.js
This builds off of #2427, but I thought it would be cleaner and a little easier for me to create a new PR, modifying things as I copy over changes, instead of adding another commit over there. Much of these changes are lifted from that PR and slightly modified.
This illustrates a way I think we could go about implementing autofixing. Here are the key elements:
- New `fix` option in Node API, `--fix` in CLI.
- Third argument, `context`, passed to rule functions. This is an object so that we can continue adding things to it, as needed. Right now it has `fix: boolean`, indicating whether to fix or not, and `newline: \n | \r\n`, determined by the first newline found in the file, which we'll use to add new newlines when fixing.
- Code in `at-rule-name-case` and `comment-empty-line-before` that …
> Add autofixing

- lib/reference/keywordSets.js
- lib/rules/selector-type-no-unknown/README.md
- lib/rules/selector-type-no-unknown/__tests__/index.js
- lib/rules/selector-type-no-unknown/index.js
- lib/utils/__tests__/isCustomElement.test.js
- lib/utils/isCustomElement.js
#2348
Btw, i think be good add option `resolve: ['custom-element']` (maybe best name). Because `not-my-type` is valid as custom element but invalid as known type selector :sob:
> Add ignore:["custom-element"] option to selector-type-no-unknown

- lib/rules/selector-max-compound-selectors/index.js
Just code improved. See https://github.com/stylelint/stylelint/issues/1247
> Chore: use `parseSelector` instead `postcss-selector-parser` directly.

- lib/__tests__/standalone-cache.test.js
- lib/standalone.js
Issue #2492
it's self explanatory
@jeddy3, @davidtheclark, @evilebottnawi, please take a look when you have time.
> Fix error when linting CSS string with cache enabled (issue #2492)

- lib/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js
- lib/rules/function-linear-gradient-no-nonstandard-direction/index.js
Closes issue #2481
Replaces PR https://github.com/stylelint/stylelint/pull/2482
Thanks to @pfructuoso. This is their code in a clean PR.
> Check all linear-gradients in a value list

- lib/rules/selector-type-no-unknown/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js
- lib/utils/isStandardSyntaxTypeSelector.js
#2506
Maybe need update docs :question: or just add example to `valid` :question:
> Fixed: `selector-type-no-unknown` is now ignore `/deep/` shadow-piercing descendant combinator.

- lib/reference/punctuationSets.js
- lib/rules/selector-combinator-space-after/README.md
- lib/rules/selector-combinator-space-after/__tests__/index.js
- lib/rules/selector-combinator-space-after/index.js
- lib/rules/selector-combinator-space-before/README.md
- lib/rules/selector-combinator-space-before/__tests__/index.js
- lib/rules/selector-combinator-space-before/index.js
- lib/rules/selector-descendant-combinator-no-non-space/__tests__/index.js
- lib/rules/selectorCombinatorSpaceChecker.js
> Fixed: descendant combinator in `selector-descendant-combinator-no-non-space` and `selector-combinator-space-before/after`

- jest-setup.js
- lib/lintSource.js
- lib/rules/comment-empty-line-before/__tests__/index.js
- lib/utils/getOsEol.js
If source file have no line endings, autofixing will set `newline` depends on current OS. There is no problem for users, I think. But there is problems for tests, because lots of our `code` doesn't have line endings in it. We always assume in tests that it will be `\n`, but on AppVeyor [tests are failing](https://github.com/stylelint/stylelint/pull/2500).
@davidtheclark what do you think?
> Fix newline for autofixing

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/selector-max-class/README.md
- lib/rules/selector-max-class/__tests__/index.js
- lib/rules/selector-max-class/index.js
This rule verifies that the number of classes in a selector doesn't exceed some maximum. Rather than measuring specificity, it counts classes explicitly.
#2458
- ~~I'll add a README once we agree this is ready~~
- Based this rule on [`selector-max-compound-selectors`](https://stylelint.io/user-guide/rules/selector-max-compound-selectors/), since the operation is similar
- Could write a util, `isFullyResolvedSelector()`, but I'm not sure I want to write a bunch of tests for it 😅
> Add `selector-max-class` rule

- docs/user-guide/rules.md
- lib/rules/at-rule-empty-line-before/README.md
- lib/rules/at-rule-empty-line-before/__tests__/index.js
- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/comment-empty-line-before/README.md
- lib/rules/comment-empty-line-before/index.js
- lib/rules/custom-property-empty-line-before/README.md
- lib/rules/custom-property-empty-line-before/__tests__/index.js
- lib/rules/custom-property-empty-line-before/index.js
- lib/rules/declaration-empty-line-before/README.md
- lib/rules/declaration-empty-line-before/__tests__/index.js
- lib/rules/declaration-empty-line-before/index.js
- lib/rules/rule-empty-line-before/README.md
- lib/rules/rule-empty-line-before/__tests__/index.js
- lib/rules/rule-empty-line-before/index.js
`comment-empty-line-before` done in initial autofix PR #2467.
I didn't do `block-closing-brace-empty-line-before`, because it's quite different from rules above. Also it's not possible to use [`addEmptyLineBefore`](https://github.com/stylelint/stylelint/blob/1cdd2469a63d6b9751bce191c1478b4893fc6679/lib/utils/addEmptyLineBefore.js) and [`removeEmptyLinesBefore`](https://github.com/stylelint/stylelint/blob/1cdd2469a63d6b9751bce191c1478b4893fc6679/lib/utils/removeEmptyLinesBefore.js) utils, because they change `node.raws.before`, but for this rule `node.raws.after` should be changed.
I'm not sure why [`result` returns in `comment-empty-line-before`](https://github.com/stylelint/stylelint/blob/1cdd2469a63d6b9751bce191c1478b4893fc6679/lib/rules/comment-empty-line-before/index.js#L128). I've …
> Add autofixing for *-empty-line-before rules

- lib/utils/beforeBlockString.js
- package.json
https://github.com/stylelint/stylelint/issues/2515
I added `?` in Flow comments, because variable isn't initialized, that's why error was thrown from Flow side.
> Updated flow and fixed flow errors

- lib/cli.js
None, as it's a teeny-tiny CLI help text fix. But it threw me off for a second 😄 
> Correct --allow-empty-input alias in CLI help

- lib/rules/property-case/__tests__/index.js
- lib/rules/property-no-unknown/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxProperty.test.js
- lib/utils/isStandardSyntaxProperty.js
No
I don't known why we check non standard less properties, i think we should ignore this.
> Fixed: ignore mergeable less property.

- lib/utils/__tests__/isStandardSyntaxSelector.test.js
- lib/utils/isStandardSyntaxSelector.js
No
Ref: http://lesscss.org/features/#import-options-reference-example
> Fixed: ignore `extend` in less.

- lib/rules/function-parentheses-space-inside/__tests__/index.js
- lib/rules/function-parentheses-space-inside/index.js
> Ignore functions without parameters in function-parentheses-space-inside

- .travis.yml
Node.js v8 was released today: https://nodejs.org/en/blog/release/v8.0.0/
A couple of highlights from the release post:
> _"npm, Inc. recently announced the release of version 5.0.0 of the npm client and we are happy to include this significant new version within Node.js 8.0.0."_
> _"Node.js 8 is the next release line to enter Long Term Support (LTS). This is scheduled to happen in October 2017. Once Node.js 8 transitions to LTS, it will receive the code name Carbon."_
> _"Note that, when referring to Node.js release versions, we have dropped the "v" in Node.js 8. Previous versions were commonly referred to as v0.10, v0.12, v4, v6, etc. In order to avoid confusion with V8, the underlying JavaScript engine, we've dropped the "v" and call it Node.js 8."_
> Add NodeJS v8 to Travis CI build matrix

- lib/rules/value-keyword-case/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxValue.test.js
- lib/utils/isStandardSyntaxValue.js
> Fixed: ignore variables with signs in `value-keyword-case`.

- lib/rules/selector-descendant-combinator-no-non-space/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxRule.test.js
- lib/utils/isStandardSyntaxRule.js
> Fixed: ignore less guards in `selector-descendant-combinator-no-non-space`.

- docs/user-guide/rules.md
- jest-setup.js
- lib/rules/at-rule-empty-line-before/README.md
- lib/rules/comment-empty-line-before/README.md
- lib/rules/custom-property-empty-line-before/README.md
- lib/rules/declaration-empty-line-before/README.md
- lib/rules/indentation/README.md
- lib/rules/indentation/__tests__/at-rules.js
- lib/rules/indentation/__tests__/comments.js
- lib/rules/indentation/__tests__/functions.js
- lib/rules/indentation/__tests__/rules.js
- lib/rules/indentation/__tests__/selectors.js
- lib/rules/indentation/index.js
- lib/rules/index.js
- lib/rules/rule-empty-line-before/README.md
I've made autofixing for most use cases. These use cases was analyzed with PostCSS AST, so I could easily apply fixes. But for big number of other use cases this rule uses `style-search`. It's used for indentation inside declaration values, selectors, and at-rule parameters.
I haven't figured out how to deal with this yet. I've commented all `reject` cases which isn't covered by current autofixing.
Any suggestions how to deal with this problem?
Also there is a problem with Less syntax. I haven't investigate what causes the problem yet.
In order to finish this PR we need:
P. S. It was total surprise to me, that this rule has secondary options 😯
<details>
<summary>Error log with Less mixins and autofixing</summary>
Semicolon gets removed.
```
FAIL …
```
> Indentation autofixing

- docs/user-guide/rules.md
- lib/__tests__/fixtures/plugin-conditionally-check-color-hex-case.js
- lib/rules/color-hex-case/README.md
- lib/rules/color-hex-case/__tests__/index.js
- lib/rules/color-hex-case/index.js
None.
Tests throw an error on `plugins.test.js`. I'm not sure how to fixed it. The problem in tests themselves, or maybe `context` doesn't go to some areas of stylelint core.
> Add autofixing for color-hex-case

- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxSelector.test.js
- lib/utils/isStandardSyntaxSelector.js
> Fixed: ignore less `:extend` in `selector-pseudo-class-no-unknown`.

- lib/rules/media-feature-name-blacklist/__tests__/index.js
- lib/rules/media-feature-name-blacklist/index.js
- lib/rules/media-feature-name-whitelist/__tests__/index.js
- lib/rules/media-feature-name-whitelist/index.js
#2536
Let's close all major bugs with new version and release `patch` version asap.
@hudochenkov @jeddy3
> Fixed: `media-feature-name-whitelist` and `media-feature-name-blacklist` now accept array as first option.

- lib/rules/max-line-length/__tests__/index.js
> Add an `ignorePattern` test for URLs in comments in `max-line-length`

- lib/rules/max-line-length/README.md
> Add an `ignorePattern` example for URL in comments in `max-line-length`

- .travis.yml
- appveyor.yml
This should lop a few minutes off the total time. It was pretty painful watching the CI tick over after merging the various pre-`7.11.1` branches.
- Drops 7
- The coverage task also runs the tests on 8, so we don’t need a specific 8 one.
- Bumps coverage up the order as it takes the longest.
- Uses 8 for pretests and coverage quicker than 7.
- Uses 8 on appveyor for speed.
> Update CI engines

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/selector-max-attribute/README.md
- lib/rules/selector-max-attribute/__tests__/index.js
- lib/rules/selector-max-attribute/index.js
- lib/rules/selector-max-class/README.md
- lib/rules/selector-max-class/__tests__/index.js
#2528
Some Fixes in test `selector-max-class`:
1. Remove properties, because it is unused for tests.
2. Set `config: [0]` for less/sass syntax, because this construction should be ignored **always**, using `1` potential can to skip something, what we should ignore.
3. `.ab { .cd: { left: 0; top: 0; } }` -> `.ab { .cd { left: 0; top: 0; } }` (seems just typo)
4. `.ab, .cd { &:hover > .ef.gh { left: 0; top: 0; } }` -> `.ab { &:hover > .ef.gh { left: 0; top: 0; } }`, because for this case we have two errors, one for `.ab`, second for `.cd`. @davidtheclark @hudochenkov @jeddy3 can we throw error if we have more than one error on test block?
> Added: `selector-max-attribute` rule.

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/function-url-scheme-blacklist/README.md
- lib/rules/function-url-scheme-blacklist/__tests__/index.js
- lib/rules/function-url-scheme-blacklist/index.js
- lib/rules/index.js
- lib/rules/property-blacklist/__tests__/index.js
- lib/rules/property-whitelist/__tests__/index.js
- system-tests/005/__snapshots__/005.test.js.snap
> Added: `function-url-scheme-blacklist` rule.

- docs/user-guide/css-processors.md
- docs/user-guide/postcss-plugin.md
- lib/utils/isStandardSyntaxRule.js
Pulls in the doc only changes for the new URL of the PostCSS Less repo from #2547
> docs: Update PostCSS Less repo URL

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/selector-max-universal/README.md
- lib/rules/selector-max-universal/__tests__/index.js
- lib/rules/selector-max-universal/index.js
- package.json
> Added: `selector-max-universal` rule.

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/selector-max-combinators/README.md
- lib/rules/selector-max-combinators/__tests__/index.js
- lib/rules/selector-max-combinators/index.js
> Added: `selector-max-combinators` rule.

- docs/user-guide/faq.md
Closes #2669
We consistently use the term “turn off”. I suggest we keep it that way in the main docs for consistency.
However, this PR adds “ignore” to the FAQ heading, so that it will appear in the search results.
As we position the FAQ as the first port of call for help, I think it makes sense to make searching improvements only there. It then acts as the jumping off point to the consistent docs.
> Improve search keywords for turning off a rule

- docs/user-guide/cli.md
- docs/user-guide/node-api.md
https://github.com/stylelint/stylelint/issues/2643#issuecomment-309893126
Maybe we should even tweet about this, because it's pretty serious caveat.
> Add autofixing caveats explanation

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/selector-max-type/README.md
- lib/rules/selector-max-type/__tests__/index.js
- lib/rules/selector-max-type/index.js
#2528
Need resolve:
1. `html { --foo: 1px; }` and `html { --custom-property-set: {} }` should be rejected? I think yes, because we can have `html { --some-here: 1px; --custom-property-set: { color: red; display: block; }; color: red;}` Later we can add option `ignoreContaintCustom` (or best name for this purpose).
2. After resolve selector some non standard (example scss: `@for $n from 1 through 5 { .foo-#{$n} { div { content: \"#{$n}\"; } } }`) output error `.foo-#{$n} div`, it is valid because we contain `div`, but message is very weird. It is normal or not?
Some tests are commented.
> Added: `selector-max-type` rule

- lib/rules/selector-class-pattern/README.md
- lib/rules/selector-class-pattern/__tests__/index.js
- lib/rules/selector-class-pattern/index.js
> Fix inconsistent behaviour for escaped characters in selector-class-pattern

- lib/__tests__/postcssPlugin.test.js
In 6.0 the `plugin.process` shortcut splits the process and plugin options.
> Fix postcssPlugin tests for postcss@6

- lib/rules/selector-max-specificity/README.md
- lib/rules/selector-max-specificity/__tests__/index.js
- lib/rules/selector-max-specificity/index.js
> Ignore nested non-standard selectors in selector-max-specificity

- lib/rules/selector-combinator-space-after/__tests__/index.js
- lib/rules/selector-combinator-space-before/__tests__/index.js
- lib/rules/selectorCombinatorSpaceChecker.js
Closes #2711
Use the original selector string, rather than stringify the selector tree. Stringifying the tree also seemed wasteful.
> Issue 2711

- lib/rules/selector-max-attribute/README.md
- lib/rules/selector-max-attribute/__tests__/index.js
- lib/rules/selector-max-attribute/index.js
This adds an `ignoreAttributes` option to the `selector-max-attribute` rule, similar to the [`ignoreTypes` option of the `selector-max-type` rule](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-max-type#ignoretypes-regex-string).
References https://github.com/stylelint/stylelint/issues/1706
> add ignoreAttributes for selector-max-attribute

- VISION.md
- docs/developer-guide/rules.md
- docs/user-guide/rules.md
Ref: https://github.com/stylelint/stylelint/issues/2259#issuecomment-279272009
I’ve been mulling this over for a while now. More so since prettier introduced support for CSS and CSS-like languages. This PR is part of a [wider effort](https://twitter.com/slicknet/status/877194938508656641) to help developers understand the benefits of each tool.   
The `VISION.md` document touches on, what I believe to be, the recurring things from the issue tracker. I’ve tried to build on top of the original goals of the project (completeness, extensibility, consistency etc), while taking into account the changes to those goals and the new goals that have emerged over the last two years (performance, support for non-standard syntax etc). I’ve also tried to address some of the confusion around what are the …
> Add VISION.md

- lib/lintSource.js
- lib/rules/no-extra-semicolons/__tests__/index.js
- lib/rules/no-extra-semicolons/index.js
- lib/utils/isStandardSyntaxRule.js
- package.json
Superseeds #2637.
This is still a WIP, two issues in `no-extra-semicolons` remains.
The big thing however, which isn't reflected by the tests are stringifying of the new `Import` node type in a couple of rules (`string-quotes` for example) and the use of `node.positionBy()` in `utils/report`. It would fail with the same `TypeError: this[node.type] is not a function` errors since the `Root` node there wasn't from `postcss-less` but from `postcss`. I found those issues while running `stylelint` via the CLI. However, I have a fix for that pending in https://github.com/shellscape/postcss-less/pull/82. So as soon as that is merged and a new version is tagged there we should be good to …
> Update postcss-less to 1.0

- lib/rules/keyframe-declaration-no-important/README.md
Added link to clarify that using !important within keyframes declarations is completely ignored in some browsers.
> Docs: keyframe-declaration-no-important

- decls/stylelint.js
- lib/__tests__/standalone-parseErrors.test.js
- lib/__tests__/standalone.test.js
- lib/createStylelintResult.js
- lib/formatters/stringFormatter.js
- lib/rules/selector-max-specificity/__tests__/index.js
- lib/rules/selector-max-specificity/index.js
- lib/rules/selector-type-case/__tests__/index.js
- lib/standalone.js
- lib/utils/parseSelector.js
- system-tests/001/__snapshots__/001.test.js.snap
- system-tests/002/__snapshots__/002.test.js.snap
- system-tests/003/__snapshots__/003.test.js.snap
- system-tests/005/__snapshots__/005.test.js.snap
- system-tests/fix/__snapshots__/fix.test.js.snap
https://github.com/stylelint/stylelint/issues/2545
I think we should be default exist with non zero code on all postcss warnings. But we can use regexp to filter only `Cannot parse selector`.
> Exit with non-zero code on postcss warnings

- lib/standalone.js
Based on https://github.com/kaelzhang/node-ignore#addignorefilepath
> Refactor: simplify ignore logic.

- README.md
Removing this disclaimer because:
* LESS support was added over a year ago (https://github.com/stylelint/stylelint/issues/810)
* [`postcss-less`](https://github.com/shellscape/postcss-less) is recommended by [`postcss`](https://github.com/postcss/postcss#syntaxes)
* The [CSS processors](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/css-processors.md) section of the stylelint user guide gives no indication that LESS support is experimental
> remove LESS support experimental disclaimer

- lib/rules/at-rule-blacklist/README.md
- lib/rules/at-rule-blacklist/__tests__/index.js
- lib/rules/at-rule-empty-line-before/README.md
- lib/rules/at-rule-empty-line-before/__tests__/index.js
- lib/rules/at-rule-name-case/README.md
- lib/rules/at-rule-name-case/__tests__/index.js
- lib/rules/at-rule-name-newline-after/README.md
- lib/rules/at-rule-name-newline-after/__tests__/index.js
- lib/rules/at-rule-name-space-after/README.md
- lib/rules/at-rule-name-space-after/__tests__/index.js
- lib/rules/at-rule-semicolon-newline-after/README.md
- lib/rules/at-rule-semicolon-newline-after/__tests__/index.js
- lib/rules/at-rule-semicolon-space-before/README.md
- lib/rules/at-rule-semicolon-space-before/__tests__/index.js
- lib/rules/at-rule-whitelist/README.md
- lib/rules/at-rule-whitelist/__tests__/index.js
- lib/rules/function-url-quotes/README.md
- lib/rules/function-url-quotes/__tests__/index.js
#2703
I think I got all of the affected rules, but an extra set of eyes would be appreciated.
> Document rules that ignore @import in Less

- package.json
Closes #2518
To be merged once `v8` is merged into `master`.
Additionally, prettier will need to be run once on the code base as part of this PR.
I’ve a pending PR in `eslint-config-stylelint` to prepare eslint to work along side prettier - https://github.com/stylelint/eslint-config-stylelint/pull/31
> Use prettier

- package-lock.json
- package.json
> chore: Update `balance-match` to `1.0.0`

- package-lock.json
- package.json
> chore: Update `pify` to `3.0.0`

- package.json
I’m afraid that experiment didn’t last long. It seemingly broke adding commits to Github Desktop.
> Revert jest lint staged

- lib/rules/indentation/__tests__/functions.js
- lib/rules/indentation/index.js
#2271
This is the most naive fix I could come up with for the less parametric mixin.  It's entirely likely that I've gone in the wrong direction.  If so, please give some hints on where to focus.  I added tests for the failing cases and ensure they all pass.  I did discover another false positive I will open an issue on, but it resisted my early attempts at resolution.
~~I'll also note that I just merged master and things are a hot mess.  linting rules are failing left and right due to new code style but non-updated lint rules.  Tests are failing everywhere.  I did check that none of the indentation tests are failing.~~  Apparently I didn't do an `npm install` after merging …
> First pass at fix

- lib/rules/selector-max-specificity/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxSelector.test.js
- lib/utils/isStandardSyntaxSelector.js
#2677
While the original issue only covered `.myMixin(@a, @b).bar` I discovered that any nested selector would fail with a `Cannot parse selector` error. 
For example:
```less
.myMixin() {
& > .bar {
}
}
```
would fail as well. 
I added a check to `isStandardSyntaxSelector` to check anything that matches `.foo()` since I can't find an instance where that would be valid CSS.
> isStandardSyntaxSelector should not check rules resolved as nested Less mixins

- docs/user-guide/complementary-tools.md
Adding [plugin support](https://github.com/w0rp/ale) for Vim.
> Adding plugin for Vim

- lib/rules/no-empty-source/index.js
- Performance optimization for `no-empty-source` 
- bug fix #2798
> Performance optimization  for `no-empty-source` and bug fix.

- CHANGELOG.md
- docs/user-guide/rules.md
- lib/rules/no-missing-end-of-source-newline/README.md
- lib/rules/no-missing-end-of-source-newline/__tests__/index.js
- lib/rules/no-missing-end-of-source-newline/index.js
> add autofixing support to no-missing-end-of-source-newline

- lib/rules/no-extra-semicolons/__tests__/index.js
- lib/rules/no-extra-semicolons/index.js
> Fixed: false negatives for semicolons followed by two comments in `no-extra-semicolons` rule.

- docs/user-guide/postcss-plugin.md
PostCSS example usage included a json style attribute in the parameters and was missing a comma.
> Fixes error in postcss example

- docs/user-guide/configuration.md
Copying this example into my configuration caused an error on build (`stylelint-commands` is expected):
`Invalid value "stylelint-command" for option "ignore" of rule "comment-empty-line-before"`
> Fix outdated example rules object in config docs

- lib/__tests__/ignore.test.js
- lib/cli.js
- lib/standalone.js
> feat: Add ignorePattern option.

- lib/rules/at-rule-empty-line-before/__tests__/index.js
- lib/rules/comment-empty-line-before/__tests__/index.js
- lib/rules/custom-property-empty-line-before/__tests__/index.js
- lib/rules/declaration-empty-line-before/__tests__/index.js
- lib/rules/rule-empty-line-before/__tests__/index.js
- lib/rules/rule-empty-line-before/index.js
- lib/utils/__tests__/isFirstNested.test.js
- lib/utils/isFirstNested.js
Fixes #2764
This changes the `isFirstNested` util to ignore comments that are on the same line as the opening brace of a block when checking if the provided node is the first node in the block.
> Fix `isFirstNested` util to handle shared-line comments

- .travis.yml
npm 5.4.0 is currently stripping execute permissione from package binaries.
See:
• https://github.com/facebook/flow/issues/4733 Flow doesn't work with npm v5.4.0
• https://github.com/npm/npm/issues/18324 npm 5.4.0 removes executable permission
• https://github.com/npm/npm/issues/18322 Npm5 destroys permissions.
See also: https://github.com/stylelint/stylelint/pull/2842#discussion_r136717774
> chore: Pin npm to version 5.3.0 for Travis CI

- docs/developer-guide/rules.md
This PR adds two new paragraphs to the working with rules guide:
- ensuring methodology stuff stays out of the rules (ref https://github.com/stylelint/stylelint/pull/2858#issuecomment-327447080)
- ensuring we only add requested features (ref https://github.com/stylelint/stylelint/issues/2789)
This PR is part of effort to orientate new members around past design decisions.
> 	Add paragraphs on methodologies and adding features

- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/unit-no-unknown/index.js
Issue #2551 
The solution is stupidly simple but it works (as in the tests pass). There might be edge cases I haven't thought of though.
> Handle valid calc functions with no whitespace in unit-no-unknown (issue #2551)

- docs/developer-guide.md
- docs/developer-guide/issues.md
- docs/developer-guide/prerequisites.md
- docs/developer-guide/pull-requests.md
- docs/developer-guide/releases.md
- docs/user-guide.md
Ref: https://github.com/stylelint/stylelint/issues/2866
@hudochenkov Thanks for [digging out](https://github.com/stylelint/stylelint/issues/2866#issuecomment-328209568) those comments. I had completely forgotten about them :)
I’ve tried to streamline the pr and issue processes where I can e.g. I’ve removed the labels which we add to closed issues. Adding these labels is unnecessary work as this info is either: 
1. Communicated in the closing comment e.g. “Best suited as a plugin”, “Dupe of xxxx” etc.
2. Implicit e.g. the PR was merged after a review, the PR is open and doesn’t have a “PR: needs tests/docs/revision” label and therefore needs reviewing.
The actual documents themselves are pretty terse (and a bit dry I’m afraid) as I wanted to get something up before we add any new members …
> Add pull request and issue sections to Dev Guide

- lib/rules/selector-max-specificity/README.md
- lib/rules/selector-max-specificity/__tests__/index.js
- lib/rules/selector-max-specificity/index.js
This also adds `ignoreSelectors` option.
https://github.com/stylelint/stylelint/issues/2857#issuecomment-328304228
> Add support for level 4 selectors in selector-max-specificity

- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
- lib/rules/selector-pseudo-class-no-unknown/index.js
> Fixed: respect multiple pseudo classes for `webkit` pseudo elements in `selector-pseudo-class-no-unknown` rule.

- lib/__tests__/fixtures/at-rule-empty-line-before.html
- lib/__tests__/fixtures/comment-empty-line-before.html
- lib/__tests__/fixtures/rule-empty-line-before.html
- lib/__tests__/standalone-syntax.test.js
- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/comment-empty-line-before/index.js
- lib/rules/rule-empty-line-before/index.js
- lib/utils/isFirstNodeOfRoot.js
> Fix support for *-empty-line-before in HTML

- lib/utils/__tests__/isCustomElement.test.js
A quick refactor of the `isCustomElement` tests to aid in investigating code coverage issues of `lib/utils/isCustomElement.js ` 
https://coveralls.io/builds/13227466/source?filename=lib%2Futils%2FisCustomElement.js
> tests: Refactor `isCustomElement` tests

- docs/developer-guide/rules.md
Closes #2804
Closes #2622 
Documenting this so that we can close the above two issues.
> Document key deprecating rule points

- jest-setup.js
Ref: https://github.com/stylelint/stylelint/issues/2783#issuecomment-328334610
The rule tester should always fail on any unexpected `parseError`s - for both `reject` and `accept` tests.
This change correctly triggers a fail for the problem in https://github.com/stylelint/stylelint/issues/2783:
```console
FAIL  lib/rules/selector-max-id/__tests__/index.js
● selector-max-id › accept › [0] › ":root { --test-property-set: { & any-selector { & any-selector { color: #00ff00; } } }; }" › custom property set in root with nested selectors
```
Testing for legitimate `parseError`s should be handled on a per rule basis, as in this example from [here](https://github.com/stylelint/stylelint/blob/c63b50d90b5e2d49dbe0b10397979d96e63de453/lib/rules/selector-max-specificity/__tests__/index.js#L267-L286): …
> Fail the rule tester on any parseErrors

- lib/__tests__/fixtures/rule-empty-line-before.html
- lib/__tests__/standalone-syntax.test.js
- lib/rules/rule-empty-line-before/index.js
> Fix false negatives for ignore: ["inside-block"] in rule-empty-line-before

- lib/rules/string-quotes/README.md
- lib/rules/string-quotes/__tests__/index.js
- lib/rules/string-quotes/index.js
> Fix false positives for at-charset and single quotes in string-quotes #2788 

- CHANGELOG.md
- lib/rules/selector-list-comma-newline-after/__tests__/index.js
- lib/rules/selector-list-comma-newline-after/index.js
> Accept multiple spaces before comment in selector-list-comma-newline-after rule

- lib/rules/custom-property-empty-line-before/__tests__/index.js
- lib/rules/custom-property-empty-line-before/index.js
- lib/rules/declaration-empty-line-before/__tests__/index.js
- lib/rules/declaration-empty-line-before/index.js
- lib/rules/rule-empty-line-before/__tests__/index.js
- lib/rules/rule-empty-line-before/index.js
- lib/utils/__tests__/isAfterSingleLineComment.test.js
- lib/utils/isAfterSingleLineComment.js
Fixes #2919
The bug reported in #2919 was being caused by multiple "except" options being checked individually, which caused the expectation to flip-flop and be incorrect if an even number of exceptions were satisfied.
This PR fixes that type of code in the various `*-empty-line-before` rules so that as soon as one exception is satisfied, it skips the rest. The other `*-empty-line-before` rules that I did not touch were already doing this correctly.
> Fix how "except" options are checked in *-empty-line-before rules

- docs/developer-guide/plugins.md
- docs/user-guide/node-api.md
- lib/rules/property-no-unknown/README.md
- package.json
None as it is a remark- linting fix.
Please [check comments here](https://github.com/stylelint/stylelint/pull/2941#discussion_r142831325)
> adding remark lint for space above headers

- lib/rules/number-max-precision/README.md
- lib/rules/number-max-precision/__tests__/index.js
- lib/rules/number-max-precision/index.js
> Add ignoreUnits option to number-max-precision rule

- lib/rules/value-keyword-case/README.md
- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
> Add ignoreProperties option to value-keyword-case rule

- docs/user-guide/rules.md
Within the list of rules as it’s a “limiting” rule like the other `max` rules.
> Move max-nesting-depth into limiting rules

- lib/rules/number-no-trailing-zeros/README.md
- lib/rules/number-no-trailing-zeros/__tests__/index.js
- lib/rules/number-no-trailing-zeros/index.js
> [#2829] add autofix for number-no-trailing-zeros

- lib/rules/unit-blacklist/__tests__/index.js
- lib/rules/unit-blacklist/index.js
- lib/rules/unit-case/__tests__/index.js
- lib/rules/unit-case/index.js
- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/unit-no-unknown/index.js
- lib/rules/unit-whitelist/__tests__/index.js
- lib/rules/unit-whitelist/index.js
#2875 
Wrote failing tests but haven't implemented fixes yet.
> Handle spaceless multiplication in unit-* rules

- docs/user-guide/rules.md
- lib/rules/shorthand-property-no-redundant-values/README.md
- lib/rules/shorthand-property-no-redundant-values/__tests__/index.js
- lib/rules/shorthand-property-no-redundant-values/index.js
> [#2829] add autofix for fix-shorthand-property-no-redundant-values

- docs/user-guide/complementary-tools.md
I would reccomend _d plugin over normal stylelint
> Added sublime stylelint_d plugin to documentation

- lib/rules/selector-attribute-operator-blacklist/index.js
- lib/rules/selector-attribute-operator-whitelist/index.js
- lib/rules/selector-attribute-quotes/__tests__/index.js
- lib/rules/selector-attribute-quotes/index.js
- lib/rules/selector-type-no-unknown/index.js
- lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js
- lib/utils/parseSelector.js
- package.json
This is a courtesy PR that updates to postcss-selector-parser 3.0 which is just released.
This addresses the issue for the upgrade originally created here:
https://github.com/stylelint/stylelint/issues/2757
The problems with attribute operators are fixed.
Two test cases were updated, the assertions for the column number were actually invalid to begin with and are now correct in this release.
There's still two failing tests, but as noted in this comment:
https://github.com/stylelint/stylelint/issues/2757#issuecomment-331698623
The syntax is non-standard and postcss-selector-parser does not plan to handle it, the suggested  workarounds in that comment seem reasonable.
> Upgrade to postcss-selector-parser 3.1.0

- lib/utils/__tests__/isSharedLineComment.test.js
- lib/utils/isSharedLineComment.js
> Fix false positives for shared-line comments in comment-empty-line-before

- lib/standalone.js
- system-tests/fix/fix.test.js
> Add autofix support for stdin input

- lib/rules/rule-empty-line-before/README.md
- lib/rules/rule-empty-line-before/__tests__/index.js
- lib/rules/rule-empty-line-before/index.js
#2887
Maybe this case needs more tests, feel free to point me.
> Add except: ["inside-block"] to rule-empty-line-before

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/no-duplicate-at-import-rules/README.md
- lib/rules/no-duplicate-at-import-rules/__tests__/index.js
- lib/rules/no-duplicate-at-import-rules/index.js
#2954
I don't think so. It's a first draft, I could use some guidelines how to improve the code.
> Add no-duplicate-at-import-rules first draft

- lib/rules/value-no-vendor-prefix/README.md
- lib/rules/value-no-vendor-prefix/__tests__/index.js
- lib/rules/value-no-vendor-prefix/index.js
#3009
No, I don't think so.
Let me know what you think.
> Add ignoreValues: [] to value-no-vendor-prefix

- docs/user-guide/rules.md
Move `declaration-block-no-redundant-longhand-properties` and `shorthand-property-no-redundant-values` to Limit language features.
https://github.com/stylelint/stylelint-config-recommended/issues/14
> Move *-redundant-* rules to Limit language features

- lib/rules/unit-blacklist/README.md
- lib/rules/unit-blacklist/__tests__/index.js
- lib/rules/unit-blacklist/index.js
#3006 
The PR is easy to understand.
NB:
I am not sure this solution is the most optimized since I have one loop for the value `valueParser` inside the one for the media `mediaParser` but it feels safer than doing matches only on the returned `mediaFeatureNode` and having to add `column` size for error handling.
Since this is my first PR for stylelint, this is widely open to discussion. I may have missed a util or anything else that could be used.
> Add ignoreMediaFeatureNames for unit-blacklist

- package.json
https://github.com/stylelint/stylelint/issues/3035
We don't use `postcss-sass` in our codebase, but it's a peer dependency of `postcss-html`, which we use. Luckily `postcss-html` doesn't fail if not every its dependency installed. But it might change theoretically, and we'll have a problem. Also we don't want annoy people by unmeet dependency messages.
> Add postcss-sass as dependency, because postcss-html needs it

- lib/rules/font-family-no-missing-generic-family-keyword/index.js
- lib/utils/__tests__/validateOptions.test.js
- lib/utils/validateOptions.js
https://github.com/stylelint/stylelint/issues/3038
I've added a test to `validateOptions`, but it doesn't catch an error. It will only show an error if test with configuration like in #3038 run.
I think we can add a new type of test in `jest-setup.js`. Take first `accept` test, add `severity` secondary option, and run test. There is a little warning: most test cases use `config: ["value"]`, while very few use `config: [["value"]]` (which is probably should be fixed). I can't think straight anymore today, so I'm not including this change for `jest-setup.js` in this PR.
> Fix incorrect font-family-no-missing-generic-family-keyword configuration #3038

- lib/cli.js
It seems like meow was perhaps misconfigured. As such, the `default` values for the flags weren’t being set. This meant that the `”json”` formatter was being used by default on the CLI, rather than the `”string”` formatter. 
I’ve moved the `flags` object into the `meow` options object (as per the [docs](https://github.com/sindresorhus/meow#flags)). The `default` property now works and the `”string”` is now correctly used by default on the CLI.
@stylelint/core Please test this branch locally as part of the review process so we can be sure everything is A-OK :)
> Fix meow configuration for default values

- .eslintignore
- lib/standalone.js
- lib/utils/writeFileAtomic.js
- lib/vendor/writeFileAtomic.js
- package.json
Fixes #2991 
This makes writing back the linted results when `--fix` is used atomic - previously if the operation was cancelled or crashed while the styles were been written, the sources could be left in an inconsistent state. 
The correct way to write file is to write it to a temp file first, then replace the original. As it turns out the nice folks at npm has written a package to do just that, and hey, if it's good enough for npm then it's probably good enough for Stylelint :wink:
> Use write-file-atomic for writing fixed styles to filesystem

- lib/rules/property-no-vendor-prefix/README.md
- lib/rules/property-no-vendor-prefix/__tests__/index.js
- lib/rules/property-no-vendor-prefix/index.js
#3007 
No, it's self explanatory. Very similar to #3015.
> property-no-vendor-prefix: Add ignoreProperties

- lib/__tests__/defaultSeverity.test.js
- lib/__tests__/disableRanges.test.js
- lib/__tests__/ignoreDisables.test.js
- lib/__tests__/integration.test.js
- lib/__tests__/plugins.test.js
- lib/__tests__/postcssPlugin.test.js
- lib/testUtils/createRuleTester.js
- lib/utils/__tests__/addEmptyLineBefore.test.js
- lib/utils/__tests__/atRuleParamIndex.test.js
- lib/utils/__tests__/declarationValueIndex.test.js
- lib/utils/__tests__/findAtRuleContext.test.js
- lib/utils/__tests__/isCustomPropertySet.test.js
- lib/utils/__tests__/isKeyframeRule.test.js
- lib/utils/__tests__/isStandardSyntaxAtRule.test.js
- lib/utils/__tests__/isStandardSyntaxDeclaration.test.js
- lib/utils/__tests__/isStandardSyntaxFunction.test.js
- lib/utils/__tests__/isStandardSyntaxRule.test.js
- lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js
- lib/utils/__tests__/nextNonCommentNode.test.js
- lib/utils/__tests__/removeEmptyLineBefore.test.js
- package.json
After updating to PostCSS v6.0.15 a bunch of console warnings are displayed during test runs:
```shell
PASS  lib/testUtils/__tests__/createRuleTester.test.js
● Console
console.warn node_modules/postcss/lib/warn-once.js:11
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
```
[PostCSS v6.0.15 release notes](https://github.com/postcss/postcss/releases/tag/6.0.15): _"Add warning about missed from option on `process().then()` call."_
> Update PostCSS to v6.0.15

- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/user-guide/about-rules.md
- docs/user-guide/cli.md
- docs/user-guide/configuration.md
- docs/user-guide/faq.md
- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
- docs/user-guide/rules.md
Continue making our site better https://github.com/stylelint/stylelint.io/issues/42. Added TOC for pages, where it makes sense.
Looks pretty good:
I have concerns about List of rules, though:
> Add Table of Contents marker to docs

- lib/rules/custom-property-empty-line-before/README.md
- lib/rules/custom-property-empty-line-before/__tests__/index.js
- lib/rules/custom-property-empty-line-before/index.js
> Add ignore: ["first-nested"] to custom-property-empty-line-before

- lib/utils/__tests__/isStandardSyntaxCombinator.test.js
- package.json
After merge #3088, a console warnings are displayed during test runs:
```shell
PASS lib/utils/__tests__/isStandardSyntaxCombinator.test.js
● Console
console.warn node_modules/postcss/lib/warn-once.js:11
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
```
https://ci.appveyor.com/project/stylelint/stylelint/build/5255#L213
>  Remove PostCSS console warnings

- lib/rules/selector-max-id/__tests__/index.js
None.
Some tests are using incorrect config value. As it fixes tests, which were not run previously, #3113 might break.
> Fix selector-max-id tests

- .travis.yml
- appveyor.yml
- package.json
https://github.com/stylelint/stylelint/pull/3069
Jest running in parallel consumes less memory. I didn't find why we use `--runInBand` flag in the first place. We just started using it in https://github.com/stylelint/stylelint/pull/2134
> Run Jest in parallel

- package.json
> Add `jest:detectleaks` npm script for Jest memory leak testing.

- decls/stylelint.js
- lib/__tests__/processors.test.js
- lib/createStylelintResult.js
- lib/standalone.js
resolves #3050 
I think it's pretty self explanatory, I have a few things I was in doubt about style wise / API wise that I would just like to ask / point out though:
1. Is there a specific commit format you'd like me to adhere to?
2. There are a few places I copy pasted from another file, so it therefore wasn't completely straight forward whether to modularize in order to apply DRY, specifically the flow type `resultType`, and the whole `stylelint.getConfigForFile(...).then(...)` block. I thought I'd see what you guys thought as I didn't know exactly which file I would put modularized functions/definitions in etc.
3. Since handleError can also throw an error did I get the return …
> Let processors modify the stylelintResult in case of CssSyntaxError

- lib/rules/font-family-name-quotes/__tests__/index.js
- lib/rules/font-family-name-quotes/index.js
\u doesn't support 10000+
e.g.
```js
/[\u0000-\u10FFFF]/.test("\u1100");         // false
/[\u{0000}-\u{10FFFF}]/u.test("\u1100")  // true
```
#2974
> Is there anything in the PR that needs reviewer focus?
u flag only supported in node.js v6+.
> Fix high-range unicode characters in font-family-name-quotes

- package.json
Follow up to #3141
Running `npm run flow-defs` will automatically pull in any changes to the Flow Typed definitions (JEst and Lodash) that I've been manually perform.
It's not perfect, requires npm 5.x's `npx` binary
Will need updating when a major release of Jest or Lodash is released
The file header comments will be changed from our custom header to that of flow-typed's which I see no issue using, e.g.:
```diff
-// https://raw.githubusercontent.com/flowtype/flow-typed/master/definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
+// flow-typed signature: ecb7b8a61ec89cf960fc7107c631a878
+// flow-typed version: 4bb4517f17/lodash_v4.x.x/flow_>=v0.63.x
```
> chore: Add a npm script to help update flow-type definitions

- README.md
- docs/user-guide/cli.md
- docs/user-guide/css-processors.md
- docs/user-guide/faq.md
- docs/user-guide/node-api.md
- lib/utils/isStandardSyntaxDeclaration.js
> Add SASS related content to the document

- package.json
Comment at https://github.com/stylelint/stylelint/pull/2955#issuecomment-366766373
This removes the stylelint / Open Collective banner that appears after installing stylelint.
As stylelint is designed to be installed alongside other tools, we should probably err on the side of subtlety. What do you think @stylelint/core? I'm ok with this being closed if folks think we should keep the banner.
> Remove Open Collective postinstall message

- lib/rules/at-rule-empty-line-before/README.md
- lib/rules/at-rule-empty-line-before/__tests__/index.js
- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/rule-empty-line-before/README.md
- lib/rules/rule-empty-line-before/__tests__/index.js
- lib/rules/rule-empty-line-before/index.js
> Add ignore: ["first-nested"] options

- package.json
https://github.com/stylelint/stylelint/issues/3185
I don't know how to test it. Or recreate a problem. But this package is required in our code. Even, though, we don't use `sync` method in [`writeFileAtomic.js`](https://github.com/stylelint/stylelint/blob/master/lib/vendor/writeFileAtomic.js), which is the only place uses this package.
> Move signal-exit from devDependencies to dependencies. Fixes #3185

- package.json
None, as it's a GitHub labelling fix.
Greenkeeper also creates issues (e.g. https://github.com/stylelint/stylelint/issues/3172), so it doesn't make sense to prefix with `PR: `. We can treat the `greenkeeper` label like the `help wanted` and `good first issue` ones i.e. they're standard meta labels used by other systems.
> Use default greenkeeper label

- docs/user-guide/plugins.md
None, this is a small documentation addition.
> Add link to stylelint-selector-tag-no-without-class plugin

- docs/user-guide/plugins.md
Adding `stylelint-z-index-value-constraint` to the list of stylelint plugins.
> Add link to stylelint-z-index-value-constraint plugin

- lib/cli.js
None, as it's a CLI help info fix.
> Add description of Sass to CLI help info.

- package.json
Change was made to precommit hook in #3184. This change wasn't needed.
People reported this problem: https://github.com/stylelint/stylelint/pull/3225#issuecomment-374129446.
Also, I see that Prettier wasn't run on a code: https://github.com/stylelint/stylelint/pull/3229/files#diff-c65b73210ee92c6286a9cee09c912513.
> Fix git commit hook for Prettier

- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-empty-lines/index.js
> Fix false positives for non-CSS blocks in max-empty-lines

- lib/rules/string-no-newline/__tests__/index.js
- lib/rules/string-no-newline/index.js
#3219 #3226
Refactoring the code for rule `string-no-newline`
> Fix false positives for non-CSS blocks in string-no-newline

- lib/rules/indentation/__tests__/selectors.js
- lib/rules/indentation/index.js
> Fix false positives for at-root in indentation

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/selector-max-pseudo-class/README.md
- lib/rules/selector-max-pseudo-class/__tests__/index.js
- lib/rules/selector-max-pseudo-class/index.js
#2805 
I had to use --no-verify flag when committing, as I was getting:
✖ npm run prettier --write found some errors. Please fix them and try committing again.
But no errors were listed and I did not know how to fix this.
> Add selector-max-pseudo-class rule

- lib/rules/declaration-property-value-blacklist/__tests__/index.js
- lib/rules/function-url-quotes/__tests__/index.js
#3124
`description` should be string only.
To verify it fixes leaks, also, run following commands for `master` and for this PR:
```bash
$ npm run jest:detectleaks -- lib/rules/declaration-property-value-blacklist/__tests__/index.js
$ npm run jest:detectleaks -- lib/rules/function-url-quotes/__tests__/index.js
```
> Fix memory leaks in tests

- lib/__tests__/standalone-cache.test.js
- lib/standalone.js
Close #3254
I think we should remove files from cache on any types of error, not only `CssSyntaxError`, however I don't know how to create other types of error, so the test case only covers `CssSyntaxError`
> Remove files with syntax errors from cache

- docs/user-guide/processors.md
Ref: https://github.com/stylelint/stylelint/pull/3261
As deprecated by `stylelint-processor-arbitrary-tags`
> Remove link to stylelint-processor-html

- docs/user-guide/plugins.md
Adding `stylelint-high-performance-animation` to the list of stylelint plugins.
This is another fork of an existing plugin because I wanted the rule to work a bit differently to avoid false positives.
> Add link to stylelint-high-performance-animation plugin

- lib/rules/no-descending-specificity/__tests__/index.js
- lib/rules/no-descending-specificity/index.js
- lib/utils/__tests__/isNestedProperty.test.js
- lib/utils/isNestedProperty.js
issues #3230 #3130 #2642  
The problem was in the `no-descending-specificity` rule. When it was calling PostCSS API method `root.walkRules` it was treating `padding:` as a selector and passing it to parseSelector directly, which was throwing the error `✖ Cannot parse selector parseError`.
> Fix nested property scss syntax false positive

- appveyor.yml
This PR caches the node_modules directory on Appveyor which is not the case currently.
> chore: cache node_modules

- lib/__tests__/standalone-syntax.test.js
- lib/getPostcssResult.js
> fix CssSyntaxError when config processors is a empty array

- docs/user-guide/plugins.md
As discussed [here], I've created a `stylelint-color-format` plugin. This adds the plugin link to the `plugins.md` file. :)
[here]: https://github.com/stylelint/stylelint/pull/3292#discussion_r188789340
> Add link to stylelint-color-format plugin

- lib/rules/function-whitespace-after/README.md
- lib/rules/function-whitespace-after/__tests__/index.js
- lib/rules/function-whitespace-after/index.js
> fix: allow `/` after function right parenthesis

- lib/rules/max-nesting-depth/__tests__/index.js
- lib/rules/max-nesting-depth/index.js
> fix: `max-nesting-depth` now ignores `SCSS` nester properties

- lib/rules/selector-pseudo-element-colon-notation/README.md
- lib/rules/selector-pseudo-element-colon-notation/__tests__/index.js
- lib/rules/selector-pseudo-element-colon-notation/index.js
selector-pseudo-element-colon-notation allows you to enforce using double or single colons on level 1 and level 2 pseudo-elements (back when `:before` and `:after` were considered valid before spec updates made ::before and ::after the preferred format).
For example using the "double" value, `a::before { display: block; }` is valid, while `a:before { display:block; }` is invalid.
This PR adds autofix support to the rule so that:
- If the value of double is set then `a:before { display: block; }` will be automatically fixed to `a::before { display: block; }`
- If the value of single is set then `a::before { display: block; }` will be automatically fixed to `a:before { display: block; }`
Fixes #3344
> Add autofix for selector-pseudo-element-colon-notation

- docs/user-guide/node-api.md
- flow-typed/stylelint.js
- lib/__tests__/standalone.test.js
- lib/standalone.js
> New feature: add `globbyOptions` in option.

- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-line-length/__tests__/index.js
- lib/rules/max-line-length/index.js
- lib/rules/no-eol-whitespace/__tests__/index.js
- lib/rules/no-eol-whitespace/index.js
- lib/rules/no-extra-semicolons/__tests__/index.js
- lib/rules/no-extra-semicolons/index.js
- lib/rules/no-missing-end-of-source-newline/__tests__/index.js
- lib/rules/no-missing-end-of-source-newline/index.js
#3365 
Rules where i fix problems:
- max-line-length
- no-eol-whitespace
- no-extra-semicolons
- no-missing-end-of-source-newline
> Fix compatibility with non css PostCSS syntaxes

- docs/developer-guide/rules.md
Ref: https://github.com/stylelint/stylelint/pull/3320#discussion_r192897819
I felt like these two conventions were the most non-obvious and difficult to glean from the existing READMEs.
For anyone interested, we use "This rule" to help distinguish the stylelint rule from CSS rules.
> Add non-obvious list of rule README conventions

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/media-feature-name-value-whitelist/README.md
- lib/rules/media-feature-name-value-whitelist/__tests__/index.js
- lib/rules/media-feature-name-value-whitelist/index.js
> Add media-feature-name-value-whitelist

- docs/user-guide/plugins.md
Rule `no-indistinguishable-colors` [was deprecated](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#780) in favour of plugin. So I created plugin `stylelint-no-indistinguishable-colors` and added it to the list in `plugins.md`.
> Add link to stylelint-no-indistinguishable-colors plugin

- lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
- lib/rules/declaration-block-no-duplicate-properties/index.js
- lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
- lib/rules/declaration-block-no-redundant-longhand-properties/index.js
- lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.js
- lib/rules/declaration-block-no-shorthand-property-overrides/index.js
- lib/utils/eachDeclarationBlock.js
#3380 
emotion-js/emotion#686 (comment)
> Fix false positives on non-standard syntax in declaration-block-no-*

- docs/user-guide/rules.md
- lib/rules/declaration-block-trailing-semicolon/README.md
- lib/rules/declaration-block-trailing-semicolon/__tests__/index.js
- lib/rules/declaration-block-trailing-semicolon/index.js
#3369 Add auto fix.
No.
/cc @evilebottnawi
> Add autofix to declaration-block-trailing-semicolon

- flow-typed/stylelint.js
- lib/cli.js
Ref: https://github.com/stylelint/stylelint/pull/2117#issuecomment-398280562
The `allowEmptyInput` option [was removed](https://github.com/stylelint/stylelint/pull/2464) in `8.0.0`, but the option still lingers in the CLI `--help` and type defs. I suspect this happened during some conflict resolution work.
> Remove aei references

- lib/reference/keywordSets.js
> Fix level 5 media queries in media-feature-name-no-unknown

- lib/rules/block-opening-brace-newline-after/__tests__/index.js
- lib/rules/block-opening-brace-newline-after/index.js
> Fix bug with quasi-qualified selector in block-opening-brace-newline-after

- lib/rules/no-descending-specificity/__tests__/index.js
- lib/rules/no-descending-specificity/index.js
> Fix false positives for no-descending-specificity and scss syntax

- lib/rules/keyframes-name-pattern/__tests__/index.js
- lib/rules/keyframes-name-pattern/index.js
Closes https://github.com/stylelint/stylelint/issues/3436
> Fix keyframes-name-pattern not supporting RegExp notation

- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/user-guide/node-api.md
No, it's pretty self explanatory. Just saves users a click through to the new links.
> Update node api docs to have new postcss api docs link

- docs/user-guide/rules.md
- lib/rules/block-opening-brace-space-before/README.md
- lib/rules/block-opening-brace-space-before/__tests__/index.js
- lib/rules/block-opening-brace-space-before/index.js
`block-opening-brace-space-before` in #2829
ex.
code:
```css
a{ color: pink; }
```
fixed:
```css
```
code:
```css
```
fixed:
```css
a{ color: pink; }
```
> Add autofix to `block-opening-brace-space-before`

- docs/user-guide/rules.md
- lib/rules/selector-combinator-space-after/README.md
- lib/rules/selector-combinator-space-after/__tests__/index.js
- lib/rules/selector-combinator-space-after/index.js
- lib/rules/selector-combinator-space-before/__tests__/index.js
- lib/rules/selectorCombinatorSpaceChecker.js
- lib/utils/parseSelector.js
`selector-combinator-space-after` in #2829
ex.
code:
```css
a >.b {}
```
fixed:
```css
a > .b {}
```
code:
```css
a > .b {}
```
fixed:
```css
a >.b {}
```
> Add autofix to selector-combinator-space-after

- docs/user-guide/rules.md
I added (Autofixable) mark to `selector-pseudo-element-colon-notation` in `user-guide/rules.md`.
[selector-pseudo-element-colon-notation](https://github.com/stylelint/stylelint/blob/master/lib/rules/selector-pseudo-element-colon-notation/README.md) can be automatically fix.
> Added (Autofixable) mark to selector-pseudo-element-colon-notation

- docs/user-guide/rules.md
- lib/rules/property-case/README.md
- lib/rules/property-case/__tests__/index.js
- lib/rules/property-case/index.js
N/A
We enable fix option for `property-case`.
> Add autofix to property-case

- docs/user-guide/rules.md
- lib/rules/selector-list-comma-newline-before/__tests__/index.js
- lib/rules/selector-list-comma-space-after/__tests__/index.js
- lib/rules/selector-list-comma-space-before/README.md
- lib/rules/selector-list-comma-space-before/__tests__/index.js
- lib/rules/selector-list-comma-space-before/index.js
- lib/rules/selectorListCommaWhitespaceChecker.js
`selector-list-comma-space-before` in #2829
ex.
code:
```css
a,b {}
```
fixed:
```css
a ,b {}
```
code:
```css
a ,b {}
```
fixed:
```css
a,b {}
```
> Add autofix to selector-list-comma-space-before

- docs/user-guide/rules.md
- lib/rules/declaration-colon-space-before/README.md
- lib/rules/declaration-colon-space-before/__tests__/index.js
- lib/rules/declaration-colon-space-before/index.js
- lib/rules/declarationColonSpaceChecker.js
`declaration-colon-space-before` in #2829
ex.
code:
```css
```
fixed:
```css
a { color : pink; }
```
code:
```css
a { color : pink; }
```
fixed:
```css
```
> Add autofix to declaration-colon-space-before

- docs/user-guide/rules.md
- lib/rules/selector-combinator-space-before/README.md
- lib/rules/selector-combinator-space-before/__tests__/index.js
- lib/rules/selector-combinator-space-before/index.js
`selector-combinator-space-before` in #2829
ex.
code:
```css
a> .b {}
```
fixed:
```css
a > .b {}
```
code:
```css
a > .b {}
```
fixed:
```css
a> .b {}
```
> Add autofix to selector-combinator-space-before

- docs/user-guide/rules.md
- lib/rules/block-closing-brace-newline-after/README.md
- lib/rules/block-closing-brace-newline-after/__tests__/index.js
- lib/rules/block-closing-brace-newline-after/index.js
`block-closing-brace-newline-after` in #2829
ex.
code:
```css
a { color: pink; } .b { color: red; }
```
fixed:
```css
.b { color: red; }
```
code:
```css
.b { color: red; }
```
fixed:
```css
a { color: pink; }.b { color: red; }
```
> Add autofix to block-closing-brace-newline-after

- docs/user-guide/node-api.md
- flow-typed/stylelint.js
- lib/formatters/__tests__/compactFormatter.test.js
- lib/formatters/compactFormatter.js
- lib/formatters/index.js
- lib/standalone.js
Fixes #3415
This PR seeks to add a new _compact_ formatter.
This _compact_ formatter was previously in its own repo at [ntwb/stylelint-formatter-compact](https://github.com/ntwb/stylelint-formatter-compact)
If this PR is accepted and  merged I'll deprecate the npm package [stylelint-formatter-compact](https://www.npmjs.com/package/stylelint-formatter-compact)
The tests are copied from the [__tests/stringFormatter.test.js](https://github.com/stylelint/stylelint/blob/2d380692173fb9c67d566d440c6cba0fc33d3b4d/lib/formatters/__tests__/stringFormatter.test.js)
> Add a "compact" formatter

- README.md
- docs/user-guide.md
- docs/user-guide/about-rules.md
- docs/user-guide/cli.md
- docs/user-guide/configuration.md
- docs/user-guide/semantic-versioning-policy.md
None, as it's a documentation fix
A lot of stylelint's users are not native English speakers. This PR tries to simplify the structure and the the language of the README (and one or two other pages). The British Government has good [research and guidance](https://www.gov.uk/guidance/content-design/writing-for-gov-uk) on writing for the web, and I've tried to incorporate it into this PR.
I had a cursory look through the other pages, but I decided to focus on main README for now as it has the high information density.
> Simplify README structure and language

- lib/cli.js
The `error` option to `--report-needless-disables, --rd` was removed in https://github.com/stylelint/stylelint/pull/2341 but the CLI output still references it.
> Remove unused error option from --rd docs

- jest-setup.js
- lib/rules/declaration-block-trailing-semicolon/index.js
Closes #3492
Fixed not to report errors `declaration-block-trailing-semicolon`, when using the `--fix` option.
> Fix reports of errors with the --fix option in declaration-block-trailing-semicolon

- docs/user-guide/complementary-tools.md
[SublimeLinter-contrib-stylelint](https://github.com/kungfusheep/SublimeLinter-contrib-stylelint) has been migrated to [SublimeLinter-stylelint](https://github.com/SublimeLinter/SublimeLinter-stylelint).
Change the old link of the document to the new link.
> Changed the link of `SublimeLinter-contrib-stylelint` to `SublimeLinter-stylelint`

- lib/rules/selector-descendant-combinator-no-non-space/__tests__/index.js
- lib/rules/selector-descendant-combinator-no-non-space/index.js
fixes #3449 
This rule is a little bit strange in that a descendent combinator is always whitespace, it's just not always a _single_ space. In fact the logic of the rule checks that the combinator is not one of the standard "non-space" combinators (+, >) and _passes_ if that is the case.
For this particular bug, PostCSS apparently determined that `+($column - 1)` is a combinator, which is odd, and it is not a non-space combinator nor is it a single space.
Anyway, since what are _really_ looking is whitespace combinators that are not single spaces, I changed the logic to do that instead. It's a bit of a work-around but it covers the case in question and most importantly does not …
> Fix false positives for selector-descendant-combinator-no-non-space

- lib/cli.js
- lib/formatters/needlessDisablesStringFormatter.js
- lib/utils/getCacheFile.js
- lib/utils/hash.js
- lib/utils/isAfterSingleLineComment.js
- lib/utils/whitespaceChecker.js
- package.json
#2935 
Add flow-type annotations into the files mentioned in #2935 except src/formatting/stringFormatter.js, which is blocked by an error in the libdefs for Lodash. (https://github.com/flow-typed/flow-typed/issues/2463)
It also updates flow-typed to the latest version, since atm `npm run flow-defs` just errors.
> Add flow-type annotations

- lib/cli.js
Related to #3488
Following the order of formatters in [the stylelint Node API documentation](https://github.com/stylelint/stylelint/blob/9.4.0/docs/user-guide/node-api.md#formatter):
```
Options: "compact"|"json"|"string"|"verbose", or a function. Default is "json".
```
> Fix missing `compact` formatter in CLI help

- docs/user-guide/rules.md
- lib/rules/selector-list-comma-newline-before/README.md
- lib/rules/selector-list-comma-newline-before/__tests__/index.js
- lib/rules/selector-list-comma-newline-before/index.js
`selector-list-comma-newline-before` in #2829
ex.
code:
```css
a,b {}
```
fixed:
```css
a
,b {}
```
* option: `never-multi-line`
code:
```css
a
,b {\n}
```
fixed:
```css
a,b {\n}
```
> Add autofix to selector-list-comma-newline-before

- lib/createStylelint.js
Summary
-------
By default `cosmiconfig` search a `.stylelintrc` file up to the home directory.
Thus, in test environments which include `.stylelintrc` in their home directory, some tests fail.
This commit fixes the failed tests, by setting project root to `stopDir` option of `cosmiconfig` on test only.
About `stopDir` option, please see <https://github.com/davidtheclark/cosmiconfig#stopdir>.
Reproduction
------------
1. Create following `Dockerfile`
```Dockerfile
FROM node:6
RUN git clone --depth=1 https://github.com/stylelint/stylelint.git /root/stylelint
WORKDIR /root/stylelint
RUN npm install
RUN echo '{"rules":{}}' > /root/.stylelintrc && \
$(npm bin)/jest lib/__tests__/standalone.test.js
RUN $(npm bin)/jest lib/__tests__/standalone.test.js
```
2. Run `docker build .` command
```
... …
```
> Fix failed tests when a `.stylelintrc` file exists in the home directory

- docs/user-guide/node-api.md
- flow-typed/stylelint.js
- lib/__tests__/standalone-formatter.test.js
- lib/cli.js
- lib/formatters/__tests__/unixFormatter.test.js
- lib/formatters/index.js
- lib/formatters/unixFormatter.js
- lib/standalone.js
- lib/utils/__tests__/getFormatterOptionsText.test.js
- lib/utils/getFormatterOptionsText.js
> Add `unix` formatter

- docs/user-guide/cli.md
- flow-typed/stylelint.js
- lib/__tests__/printConfig.test.js
- lib/cli.js
- lib/printConfig.js
- system-tests/cli/cli.test.js
- system-tests/cli/config.json
Resolves #3127.
> A nice feature of eslint's CLI is the option `--print-config` that will log to the console the parsed configuration object for a given configuration file, including all the extended rules. It's awesome for debugging configuration files.
This PR is largely inspired by the [ESLint implementation](https://github.com/eslint/eslint/blob/1e88170fa57656206a39d579fd0c176d414c275b/lib/cli.js#L156-L172). Also recycles its (succinct) [docs](https://eslint.org/docs/user-guide/command-line-interface#--print-config). Most of the functionality is taken care of by `getConfigForFile`, so what I added is mostly an integration of that into the CLI, replicating how `getConfigForFile` gets called [in `lintSource`](https://github.com/thibaudcolas/stylelint/blob/2584d15e514fc99fb473e8d24175012c …
> Add --print-config CLI flag (fixes #3127)

- docs/user-guide/rules.md
- lib/rules/declaration-colon-space-after/README.md
- lib/rules/declaration-colon-space-after/__tests__/index.js
- lib/rules/declaration-colon-space-after/index.js
`declaration-colon-space-after` in #2829
ex.
code:
```css
a { color:pink; }
```
fixed:
```css
```
code:
```css
```
fixed:
```css
a { color:pink; }
```
> Add autofix to declaration-colon-space-after

- docs/user-guide/rules.md
- lib/rules/declaration-block-semicolon-newline-after/README.md
- lib/rules/declaration-block-semicolon-newline-after/__tests__/index.js
- lib/rules/declaration-block-semicolon-newline-after/index.js
closes #3544
ex.
code:
```css
a { color: pink;top: 0; }
```
fixed:
```css
a { color: pink;
top: 0; }
```
* option: `never-multi-line`
code:
```css
a {
color: pink;
top: 0;
}
```
fixed:
```css
a {
color: pink;top: 0;
}
```
> Add autofix to declaration-block-semicolon-newline-after

- docs/user-guide/rules.md
- lib/rules/declaration-block-semicolon-space-before/README.md
- lib/rules/declaration-block-semicolon-space-before/__tests__/index.js
- lib/rules/declaration-block-semicolon-space-before/index.js
closes #3546
ex.
code:
```css
```
fixed:
```css
a { color: pink ; }
```
code:
```css
a { color: pink ; }
```
fixed:
```css
```
> Add autofix to declaration-block-semicolon-space-before

- docs/user-guide/rules.md
- lib/rules/value-list-comma-space-after/README.md
- lib/rules/value-list-comma-space-after/__tests__/index.js
- lib/rules/value-list-comma-space-after/index.js
- lib/rules/valueListCommaWhitespaceChecker.js
closes #3549 
ex.
code:
```css
a { background-size: 0,0; }
```
fixed:
```css
a { background-size: 0, 0; }
```
code:
```css
a { background-size: 0, 0; }
```
fixed:
```css
a { background-size: 0,0; }
```
> Add autofix to value-list-comma-space-after

- docs/user-guide/rules.md
- jest-setup.js
- lib/rules/no-extra-semicolons/README.md
- lib/rules/no-extra-semicolons/__tests__/index.js
- lib/rules/no-extra-semicolons/index.js
closes #3572
ex.
code:
```css
;
a {;}
a { color: red; };
```
fixed:
```css
a {}
a { color: red; }
```
> Add autofix to no-extra-semicolons

- docs/user-guide/rules.md
- lib/rules/value-list-comma-space-before/README.md
- lib/rules/value-list-comma-space-before/__tests__/index.js
- lib/rules/value-list-comma-space-before/index.js
closes #3550
ex.
code:
```css
a { background-size: 0,0; }
```
fixed:
```css
a { background-size: 0 ,0; }
```
code:
```css
a { background-size: 0 ,0; }
```
fixed:
```css
a { background-size: 0,0; }
```
> Add autofix to value-list-comma-space-before

- docs/user-guide/rules.md
- lib/rules/function-comma-space-before/README.md
- lib/rules/function-comma-space-before/__tests__/index.js
- lib/rules/function-comma-space-before/index.js
closes #3548
ex.
code:
```css
a { transform: translate(1, 1); }
```
fixed:
```css
a { transform: translate(1 , 1); }
```
code:
```css
a { transform: translate(1 , 1); }
```
fixed:
```css
a { transform: translate(1, 1); }
```
> Add autofix to function-comma-space-before

- docs/user-guide/rules.md
- lib/rules/declaration-colon-newline-after/README.md
- lib/rules/declaration-colon-newline-after/__tests__/index.js
- lib/rules/declaration-colon-newline-after/index.js
closes #3552
ex.
code:
```css
a { color :pink; }
```
fixed:
```css
a { color :
pink; }
```
> Add autofix to declaration-colon-newline-after

- README.md
- docs/developer-guide/issues.md
- docs/developer-guide/processors.md
- docs/user-guide/cli.md
- docs/user-guide/complementary-tools.md
- docs/user-guide/css-processors.md
- docs/user-guide/node-api.md
- docs/user-guide/processors.md
Ref: https://github.com/stylelint/stylelint/issues/3587
This PR deemphasizes processors and syntax option in the docs (and emphasizes stylelint's built-in support for inferring syntax and extracting styles). It also continues to roll-out the simplified writing styled we started using on the homepage.
> Deemphasize processors and syntax option in the docs

- lib/rules/selector-list-comma-newline-before/__tests__/index.js
- lib/rules/selector-list-comma-newline-before/index.js
- lib/rules/selector-list-comma-space-after/__tests__/index.js
- lib/rules/selector-list-comma-space-after/index.js
- lib/rules/selector-list-comma-space-before/__tests__/index.js
- lib/rules/selector-list-comma-space-before/index.js
- lib/rules/value-list-comma-space-after/__tests__/index.js
- lib/rules/value-list-comma-space-after/index.js
- lib/rules/value-list-comma-space-before/__tests__/index.js
- lib/rules/value-list-comma-space-before/index.js
> Fixed 5 autofixes #3620

- docs/user-guide/rules.md
- lib/rules/declaration-bang-space-after/README.md
- lib/rules/declaration-bang-space-after/__tests__/index.js
- lib/rules/declaration-bang-space-after/index.js
closes #3575
ex.
code:
```css
a { color: pink !important; }
```
fixed:
```css
a { color: pink ! important; }
```
code:
```css
a { color: pink ! important; }
```
fixed:
```css
a { color: pink !important; }
```
> Add autofix to  declaration-bang-space-after

- lib/__tests__/stylelintignore-test/stylelintignore.test.js
- lib/standalone.js
~Fixes #2833, and it also~ Fixes #3590 ~which is the same issue~.
Edit: my bad, #2833 is about `isPathIgnored`. This fixes the ignoring for the `lint()` API only, so #3590.
My tests showed everything working as expected, while the repro in #3590 did not. The difference between the two is that I was only checking `output` from the stylelint results… which is the only thing that (half) works.
For inputs via stdin, the results are ignored **after** linting, and it was only resetting [`output`](https://stylelint.io/user-guide/node-api/#output), not all other return values (`errored`, etc):
https://github.com/stylelint/stylelint/blob/2584d15e514fc99fb473e8d24175012c20627ff3/lib/standalone.js#L135-L156
…so all is well if you're using the CLI, or only look at `output` in your API integration …
> Reset whole return value when ignoring stdin. Fix #3590

- docs/user-guide/rules.md
- lib/rules/findMediaOperator.js
- lib/rules/media-feature-range-operator-space-after/__tests__/index.js
- lib/rules/media-feature-range-operator-space-after/index.js
- lib/rules/media-feature-range-operator-space-before/README.md
- lib/rules/media-feature-range-operator-space-before/__tests__/index.js
- lib/rules/media-feature-range-operator-space-before/index.js
closes #3580
if use the `--fix` option, to remove whitespace at the end of each line.
ex.
code:
```css
@media (width<600px) {}
```
fixed:
```css
@media (width <600px) {}
```
code:
```css
@media (width < 600px) {}
```
fixed:
```css
@media (width< 600px) {}
```
> Add autofix to media-feature-range-operator-space-before

- docs/user-guide/rules.md
- lib/rules/selector-attribute-operator-space-before/README.md
- lib/rules/selector-attribute-operator-space-before/__tests__/index.js
- lib/rules/selector-attribute-operator-space-before/index.js
- lib/rules/selectorAttributeOperatorSpaceChecker.js
closes #3578
ex.
code:
```css
[target="_blank"] { }
```
fixed:
```css
[target ="_blank"] { }
```
code:
```css
[ target = "_blank" ] { }
```
fixed:
```css
[ target= "_blank" ] { }
```
> Add autofix to selector-attribute-operator-space-before

- docs/user-guide/rules.md
- lib/rules/value-list-comma-newline-after/README.md
- lib/rules/value-list-comma-newline-after/__tests__/index.js
- lib/rules/value-list-comma-newline-after/index.js
Closes #3595
ex.
- option: always***
code:
```css
a { background-size: 0,0; }
```
fixed:
```css
a { background-size: 0,
0; }
```
- option: never-multi-line
code:
```css
a { background-size: 0
, 0; }
```
fixed:
```css
a { background-size: 0
,0; }
```
> Add autofix to value-list-comma-newline-after

- docs/user-guide/rules.md
- lib/rules/selector-attribute-brackets-space-inside/README.md
- lib/rules/selector-attribute-brackets-space-inside/__tests__/index.js
- lib/rules/selector-attribute-brackets-space-inside/index.js
closes #3583
ex.
code:
```css
[target="_blank"] { }
```
fixed:
```css
[ target="_blank" ] { }
```
code:
```css
[ target="_blank" ] { }
```
fixed:
```css
[target="_blank"] { }
```
> Add autofix to selector-attribute-brackets-space-inside

- docs/user-guide/rules.md
- lib/rules/no-eol-whitespace/README.md
- lib/rules/no-eol-whitespace/__tests__/index.js
- lib/rules/no-eol-whitespace/index.js
closes #3608
if use the `--fix` option, to remove whitespace at the end of each line.
ex.
code:
```css
a { color: pink; }····
```
fixed:
```css
```
> Add autofix to no-eol-whitespace

- docs/user-guide/rules.md
- lib/rules/media-query-list-comma-space-after/README.md
- lib/rules/media-query-list-comma-space-after/__tests__/index.js
- lib/rules/media-query-list-comma-space-after/index.js
- lib/rules/mediaQueryListCommaWhitespaceChecker.js
closes #3570
ex.
code:
```css
@media screen and (color),projection and (color) {}
```
fixed:
```css
@media screen and (color), projection and (color) {}
```
code:
```css
@media screen and (color), projection and (color) {}
```
fixed:
```css
@media screen and (color),projection and (color) {}
```
> Add autofix to media-query-list-comma-space-after

- docs/user-guide/rules.md
- lib/rules/block-closing-brace-empty-line-before/README.md
- lib/rules/block-closing-brace-empty-line-before/__tests__/index.js
- lib/rules/block-closing-brace-empty-line-before/index.js
- lib/utils/__tests__/addEmptyLineAfter.test.js
- lib/utils/__tests__/removeEmptyLineAfter.test.js
- lib/utils/addEmptyLineAfter.js
- lib/utils/addEmptyLineBefore.js
- lib/utils/removeEmptyLinesAfter.js
Closes #3614 
ex.
- option: `always-multi-line`  
code:  
```css
a {
color: pink;
}
```
fixed:  
```css
a {
color: pink;
}
```
- option: `never`  
code:  
```css
a {
color: pink;
}
```
fixed:  
```css
a {
color: pink;   
}
```
- option: `["never", { except: ["after-closing-brace"] }]`  
code:  
```css
@media print {
a {
color: aquamarine;
}
b {
color: hotpink;
}
}
```
fixed:  
```css
@media print {
a {
color: aquamarine;
}
b {
color: hotpink;
}
}
```
- option: `["always-multi-line", { except: ["after-closing-brace"] }]`  
code:  
```css
@media print {
a {
color: aquamarine;
}
b {
color: hotpink;
}
}
```
fixed:  
```css
@media print {
a {
color: aquamarine;
}
b {
color: hotpink;
} …
```
> Add autofix to block-closing-brace-empty-line-before

- lib/rules/indentation/README.md
- lib/rules/indentation/__tests__/html.js
- lib/rules/indentation/__tests__/javascript.js
- lib/rules/indentation/index.js
Closes #3427
Add setting `baseIndentLevel` for `indentation` rule. See: lib/rules/indentation/README.md
> Add baseIndentLevel to indentation

- lib/rules/max-empty-lines/README.md
- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-empty-lines/index.js
- system-tests/005/__snapshots__/005.test.js.snap
> Fix incorrect line in max-empty-lines

- docs/user-guide/rules.md
- lib/rules/media-query-list-comma-space-before/README.md
- lib/rules/media-query-list-comma-space-before/__tests__/index.js
- lib/rules/media-query-list-comma-space-before/index.js
closes #3571
ex.
code:
```css
@media screen and (color),projection and (color) {}
```
fixed:
```css
@media screen and (color) ,projection and (color) {}
```
code:
```css
@media screen and (color) , projection and (color) {}
```
fixed:
```css
@media screen and (color), projection and (color) {}
```
> Add autofix to media-query-list-comma-space-before

- docs/user-guide/rules.md
- lib/rules/media-query-list-comma-newline-after/README.md
- lib/rules/media-query-list-comma-newline-after/__tests__/index.js
- lib/rules/media-query-list-comma-newline-after/index.js
closes #3593
ex.
code:
```css
@media screen and (color),projection and (color) { }
```
fixed:
```css
@media screen and (color),
projection and (color) { }
```
code:
```css
@media screen and (color),
projection and (color) { }
```
fixed:
```css
@media screen and (color),projection and (color) { }
```
> Add autofix to media-query-list-comma-newline-after

- docs/user-guide/rules.md
- lib/rules/media-feature-range-operator-space-after/README.md
- lib/rules/media-feature-range-operator-space-after/__tests__/index.js
- lib/rules/media-feature-range-operator-space-after/index.js
closes #3579
ex.
code:
```css
@media (width<600px) {}
```
fixed:
```css
@media (width< 600px) {}
```
code:
```css
@media (width < 600px) {}
```
fixed:
```css
@media (width <600px) {}
```
> Add autofix to media-feature-range-operator-space-after

- docs/user-guide/rules.md
- lib/rules/function-name-case/README.md
- lib/rules/function-name-case/__tests__/index.js
- lib/rules/function-name-case/index.js
> Add autofix to function-name-case

- docs/user-guide/rules.md
- lib/rules/block-closing-brace-space-before/README.md
- lib/rules/block-closing-brace-space-before/__tests__/index.js
- lib/rules/block-closing-brace-space-before/index.js
closes #3567
ex.
* option: `always**`
code:
```css
a {color: pink;}
```
fixed:
```css
a {color: pink; }
```
* option: `never**`
code:
```css
```
fixed:
```css
a { color: pink;}
```
> Add autofix to block-closing-brace-space-before

- docs/user-guide/rules.md
- lib/rules/function-whitespace-after/README.md
- lib/rules/function-whitespace-after/__tests__/index.js
- lib/rules/function-whitespace-after/index.js
closes #3582
ex.
code:
```css
a { transform: translate(1, 1)scale(3); }
```
fixed:
```css
a { transform: translate(1, 1) scale(3); }
```
code:
```css
a { transform: translate(1, 1) scale(3); }
```
fixed:
```css
a { transform: translate(1, 1)scale(3); }
```
> Add autofix to function-whitespace-after

- docs/user-guide/rules.md
- lib/rules/selector-pseudo-class-parentheses-space-inside/README.md
- lib/rules/selector-pseudo-class-parentheses-space-inside/__tests__/index.js
- lib/rules/selector-pseudo-class-parentheses-space-inside/index.js
closes #3584
ex.
code:
```css
input:not([type='submit']) { }
```
fixed:
```css
input:not( [type='submit'] ) { }
```
code:
```css
input:not( [type='submit'] ) { }
```
fixed:
```css
input:not([type='submit']) { }
```
> Add autofix to selector-pseudo-class-parentheses-space-inside

- docs/user-guide/rules.md
- lib/rules/selector-type-case/README.md
- lib/rules/selector-type-case/__tests__/index.js
- lib/rules/selector-type-case/index.js
> feat: add autofix for rule "selector-type-case"

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/no-empty-first-line/README.md
- lib/rules/no-empty-first-line/__tests__/index.js
- lib/rules/no-empty-first-line/index.js
> Add no-empty-first-line rule

- lib/__tests__/defaultSeverity.test.js
- lib/__tests__/extends.test.js
- lib/__tests__/ignore.test.js
- lib/__tests__/ignoreDisables.test.js
- lib/__tests__/integration.test.js
- lib/__tests__/message.test.js
- lib/__tests__/needlessDisables.test.js
- lib/__tests__/normalizeRuleSettings-integration.test.js
- lib/__tests__/plugins.test.js
- lib/__tests__/postcssPlugin.test.js
- lib/__tests__/processors.test.js
- lib/__tests__/standalone-deprecations.test.js
- lib/__tests__/standalone-needlessDisables.test.js
- lib/__tests__/standalone-parseErrors.test.js
- lib/__tests__/standalone-syntax.test.js
- lib/__tests__/standalone.test.js
- lib/__tests__/stylelintignore-test/stylelintignore.test.js
- lib/rules/no-duplicate-selectors/__tests__/index.js
- lib/utils/__tests__/checkAgainstRule.test.js
- lib/utils/__tests__/isStandardSyntaxAtRule.test.js
- lib/utils/__tests__/isStandardSyntaxMediaFeatureName.test.js
- lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js
- lib/utils/__tests__/isStandardSyntaxUrl.test.js
- lib/utils/__tests__/validateOptions.test.js
Ref: https://github.com/stylelint/stylelint/issues/3638
Fixes up the 150 or so ESLint warnings in `master`. The just plugin is useful as it caught these mistakes.
Warnings cames from:
- https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/prefer-to-have-length.md
- https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-identical-title.md
> Fix ESLint Jest warnings

- docs/user-guide/complementary-tools.md
Thank you for the great tool! 
I am adding Codacy to the docs as a analysis platform engine section.
This way, more people can use stylelint analysis out of the box, for free.
> Add codacy as an analysis platform engine

- docs/user-guide/plugins.md
> Add stylelint-value-no-unknown-custom-properties to plugin list

- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-empty-lines/index.js
> Fix false positives for empty lines before </style> in max-empty-lines

- lib/rules/selector-no-vendor-prefix/__tests__/index.js
Closes https://github.com/stylelint/stylelint/issues/3712
It was an odd test as I believe that `moz-placeholder` is a pseudo _element_, rather than a class. It is used as an element in the subsequent test, so I just updated the failing test to match.
> Fix failing appveyor test

- docs/user-guide/rules.md
- lib/rules/media-feature-parentheses-space-inside/README.md
- lib/rules/media-feature-parentheses-space-inside/__tests__/index.js
- lib/rules/media-feature-parentheses-space-inside/index.js
- system-tests/005/__snapshots__/005.test.js.snap
> Add autofix to media-feature-parentheses-space-inside

- docs/user-guide/rules.md
- lib/rules/unit-case/README.md
- lib/rules/unit-case/__tests__/index.js
- lib/rules/unit-case/index.js
> Add autofix to unit-case rule

- lib/__tests__/printConfig.test.js
- lib/__tests__/standalone-deprecations.test.js
- lib/__tests__/standalone-parseErrors.test.js
We have this error for two months in tests:
```
PASS lib/utils/__tests__/isStandardSyntaxValue.test.js
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
244 | ) /*: stylelint$config*/ {
245 |   if (!config.plugins) return config;
> 246 | 
| ^
247 |   const normalizedPlugins = Array.isArray(config.plugins)
248 |     ? config.plugins
249 |     : [config.plugins];
at lazy (node_modules/import-lazy/index.js:2:51)
at Object.get (node_modules/import-lazy/index.js:10:11)
at baseGet (node_modules/lodash/lodash.js:3041:24)
at Function.get (node_modules/lodash/lodash.js:13128:49)
at Object.keys.forEach.ruleName (lib/augmentConfig.js:246:84)
at Array.forEach (<anonymous>)
at normalizeAllRuleSettings (lib/augmentConfig.js:238:29)
PASS …
```
> Fix error in tests

- lib/rules/selector-max-specificity/__tests__/index.js
- lib/rules/selector-max-specificity/index.js
> Fix false positives for functional psuedo-classes selector-max-specificity

- lib/utils/getModulePath.js
- package.json
Fixes #1973 
This patch fixes the following situation.
```
$ npm ls -g --depth 0 | grep stylelint
├── stylelint@9.5.0
├── stylelint-config-standard@18.2.0
$ cat ~/.stylelintrc.js
module.exports = {
extends: ['stylelint-config-standard'],
};
$ stylelint ~/tmp/*.css
Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/getModulePath.js:18:11)
at loadExtendedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:186:22)
at resultPromise.then.resultConfig …
```
> Allow global installed configuration

- lib/formatters/__tests__/stringFormatter.test.js
- lib/formatters/stringFormatter.js
> Fix SyntaxError when an empty string is used for a rule's custom message

- lib/rules/at-rule-blacklist/__tests__/index.js
- lib/rules/at-rule-blacklist/index.js
- lib/rules/at-rule-empty-line-before/__tests__/index.js
- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/at-rule-name-case/__tests__/index.js
- lib/rules/at-rule-name-case/index.js
- lib/rules/at-rule-no-unknown/__tests__/index.js
- lib/rules/at-rule-no-unknown/index.js
- lib/utils/__tests__/isStandardSyntaxAtRule.test.js
> Fix false positives for Less variables and mixins in at-rule-* (#3749)

- lib/rules/at-rule-semicolon-newline-after/__tests__/index.js
- lib/rules/at-rule-semicolon-newline-after/index.js
- lib/rules/at-rule-semicolon-space-before/__tests__/index.js
- lib/rules/at-rule-semicolon-space-before/index.js
- lib/rules/at-rule-whitelist/__tests__/index.js
- lib/rules/at-rule-whitelist/index.js
Closes #3764.
With this PR all `at-rule-*` rules should be ignoring Less mixins/variables.
> Fix false positives for Less variables and mixins in at-rule-* 

- lib/rules/unit-no-unknown/README.md
- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/unit-no-unknown/index.js
> Add ignoreFunctions: [] to unit-no-unkown

- lib/__tests__/stylelintignore-test/.stylelintignore
- lib/__tests__/stylelintignore-test/fixtures/config-block-no-empty.json
- lib/__tests__/stylelintignore-test/fixtures/config-color-no-invalid-hex.json
- lib/__tests__/stylelintignore-test/fixtures/empty-block.css
- lib/__tests__/stylelintignore-test/fixtures/invalid-hex.css
- lib/__tests__/stylelintignore-test/stylelintignore.test.js
- lib/standalone.js
- lib/utils/__tests__/filterFilePaths.test.js
- lib/utils/filterFilePaths.js
- package.json
Closes https://github.com/stylelint/stylelint/pull/3534.
`ignore` doesn't support paths starting with `../`, which makes sense, because it follows .gitignore [spec](https://git-scm.com/docs/gitignore). In previous version `ignore` ignored invalid paths. We use paths like this, because any path could be given to linter.
Fixed `.stylelintignore` tests, because `.stylelintignore` was invalid.
P. S. Created separate PR, because I don't won't to share credit to my work with a bot.
> Update ignore to version 5.0.3

- .travis.yml
- package.json
1\. Added much needed [jest-watch-typeahead](https://github.com/jest-community/jest-watch-typeahead). Very useful with our amount of tests.
~~2\. When developing locally we most likely use `npm run watch` (`jest --watch`), rather running full test suite all the time. With https://github.com/stylelint/stylelint/commit/67ad0e750e6bc1ad59d9d6ddbfbd650702d3a481 we can use `npm test` locally to run watch mode, but on CI it will run all tests and linters we have. What do you think, @stylelint/contributors?~~
P. S. Little known fact: `npm test` has an alias `npm t` ;)
> Jest enhancements

- docs/developer-guide/rules.md
Fixed two typos from "p*sue*do" to "p*seu*do"
> Fixed typo "psuedo" to "pseudo"

- CONTRIBUTING.md
I just noticed that I accidentally forgot to remove the open collective stuff from the contributing doc when we restructured the docs. The list of contributors, backers and sponsors is proudly displayed on the main README. We can reserve the contributing doc to information on, well, contributing.
> Remove open collective from contributing doc

- docs/user-guide/faq.md
The FAQ entry is out of date now that stylelint can lint `<style>` tags out-of-the-box (which we document in the main README)
> Remove out of date FAQ item

- lib/__tests__/stylelintignore-test/.stylelintignore
- lib/__tests__/stylelintignore-test/.stylelintignore2
- lib/__tests__/stylelintignore-test/stylelintignore.test.js
- lib/standalone.js
… in these files.
A replacement for https://github.com/stylelint/stylelint/pull/3778.
now, below codes will throw a parse error even the .stylelintignore has pattern /**
const stylelint = require('stylelint');
stylelint.lint({
code: 'var a = {',
codeFilename: 'test.js',
}).then(data => console.log(data));
because lintsource throw parse error even the file is ignored.
this PR ignore files before lint, so avoid that errors.
> Don't parse ignored files

- lib/rules/function-parentheses-space-inside/README.md
> Adding Missing Preposition

- lib/rules/font-weight-notation/README.md
This pull request, if successful, closes #3812 and is a documentation fix. As noted in the issue, the `font` shortcut lacks the `font-family` property in the tail of the shortcut.
> Add “sans-serif” to tail of font shortcut

- docs/user-guide/rules.md
- lib/rules/value-list-max-empty-lines/README.md
- lib/rules/value-list-max-empty-lines/__tests__/index.js
- lib/rules/value-list-max-empty-lines/index.js
Closes #3610
e.g.
code:
```css
a { padding: 10px
10px 10px 10px }
```
fixed:
```css
a { padding: 10px
10px 10px 10px }
```
> Add autofix to value-list-max-empty-lines

- docs/user-guide/rules.md
- lib/rules/selector-list-comma-newline-after/README.md
- lib/rules/selector-list-comma-newline-after/__tests__/index.js
- lib/rules/selector-list-comma-newline-after/index.js
Closes #3409
Closes #3421 (PR)
e.g.
- option `always`
code: 
```css
a,b {}
```
fixed: 
```css
a,
b {}
```
code: 
```css
a, /* comment */ b {}
```
fixed: 
```css
a, /* comment */
b {}
```
-  option `never`
code: 
```css
a,
b {
}
```
fixed: 
```css
a,b {
}
```
> Add autofix to selector-list-comma-newline-after

- lib/utils/__tests__/isStandardSyntaxDeclaration.test.js
- lib/utils/isStandardSyntaxDeclaration.js
- package.json
> Ignore Less &:extend in isStandardSyntaxDeclaration

- lib/rules/selector-no-vendor-prefix/README.md
- lib/rules/selector-no-vendor-prefix/__tests__/index.js
- lib/rules/selector-no-vendor-prefix/index.js
> Add ignoreSelectors: [] to selector-no-vendor-prefix

- docs/user-guide/cli.md
In my testing, this does not work as expected:
```shell
stylelint "foo/**/*.css bar/*.css" -q -f json --config bar/mySpecialConfig.json
```
Whereas this does:
```shell
stylelint "foo/**/*.css" "bar/*.css" -q -f json --config bar/mySpecialConfig.json
```
> Fix an example

- lib/getPostcssResult.js
> Disable --fix while using a processor and display message

- lib/rules/no-invalid-double-slash-comments/README.md
- lib/rules/no-invalid-double-slash-comments/__tests__/index.js
- lib/rules/value-list-comma-space-after/__tests__/index.js
Closes https://github.com/stylelint/stylelint/issues/3891
1. Looking again at https://www.xanthir.com/b4U10, I think our tests and examples were wrong because I don't think you can have a space after the slashes.
2. Remove an test of invalid CSS from `value-list-comma-space-after`
> Fix tests to account for new syntax errors in PostCSS

- lib/reference/keywordSets.js
- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
There is one known issue with this PR: the test passes even if the fix itself is reverted. Any ideas why?
Fixes: https://github.com/stylelint/stylelint/issues/3886
> Fix false positives for focus-visible in selector-pseudo-class-no-unknown

- .github/ISSUE_TEMPLATE/REPORT_A_BUG.md
- CHANGELOG.md
- README.md
- docs/developer-guide/processors.md
- docs/user-guide.md
- docs/user-guide/configuration.md
- docs/user-guide/css-processors.md
- docs/user-guide/faq.md
- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
- docs/user-guide/processors.md
`Node.js` is the official name. Also may be confused with the `Node` class in `PostCSS`
> Resolve the ambiguity of the `Node.js` name

- CHANGELOG.md
- docs/developer-guide/pull-requests.md
- docs/developer-guide/releases.md
Closes #3901 
Changes summary:
- Introduce a new 1st level heading
- Change headings (including each version number) from 1st level to 2nd level
- Add GitHub compare link between tags
- Update descriptions related to `CHANGELOG.md` in developer guide
<details>
<summary>I wrote the following Ruby script for this task:</summary>
```ruby
original_content = File.read("CHANGELOG.md")
versions = original_content.lines.
select { |line| line.start_with?("#") }.
map { |line| line.match(/# ([0-9\.-]+)\b/)[1] }
compare_urls = versions.map.with_index do |version, index|
prev_version = versions[index + 1]
next unless prev_version
if prev_version == "0.1.0"
prev_version = "v0.1.0"
end
if …
```
> Re-format CHANGELOG.md

- lib/__tests__/standalone-cache.test.js
- package.json
Closes #3877
Update `file-entry-cache` to avoid the deprecated warning
Just as the #3786 and #3779, the only thing to do is update the `standalone-cache.test.js`. Just use the `parse` method from the `flatted` which is used by `file-entry-cache` to create the cache to parse the content, then tests can pass.
> Update file-entry-cache to avoid the deprecated warning

- package.json
None. This PR aims to improve our DX (Developer eXperience).
Because we may not notice the lint errors until our CI occurs them.
> Lint staged files on pre-commit hook

- lib/__tests__/standalone-cache.test.js
- package.json
Closes #3786
Use `file-entry-cache#createFromFile` to create another instance of the cache, so that we can access to the cache without relying on the `flatted` which is the dependency of `file-entry-cache`
> Refactor standalone-cache.test.js to avoid relying on 'flatted'

- lib/reference/keywordSets.js
This is a new media query added to CSS Media Queries Level 5 to utilize the dark mode preference operating systems provide.
Closes #3950
Please see issue #3950
> Fix false positives for prefers-color-scheme in media-feature-name-no-unknown

- lib/rules/no-duplicate-selectors/README.md
- lib/rules/no-duplicate-selectors/__tests__/index.js
- lib/rules/no-duplicate-selectors/index.js
> Add disallowInList option to no-duplicate-selectors

- lib/rules/at-rule-no-unknown/__tests__/index.js
- lib/rules/color-no-invalid-hex/__tests__/index.js
- lib/rules/color-no-invalid-hex/index.js
- lib/rules/comment-word-blacklist/__tests__/index.js
- lib/rules/declaration-property-value-blacklist/__tests__/index.js
- lib/rules/font-family-no-duplicate-names/__tests__/index.js
- lib/rules/media-feature-name-no-unknown/__tests__/index.js
- lib/rules/media-feature-name-value-whitelist/__tests__/index.js
- lib/rules/media-feature-name-whitelist/__tests__/index.js
- lib/rules/number-max-precision/__tests__/index.js
- lib/rules/property-blacklist/__tests__/index.js
- lib/rules/property-no-vendor-prefix/__tests__/index.js
- lib/rules/unit-blacklist/__tests__/index.js
- lib/rules/unit-blacklist/index.js
- lib/rules/unit-whitelist/index.js
- lib/rules/value-keyword-case/__tests__/index.js
- lib/utils/__tests__/validateObjectWithArrayProps.test.js
- lib/utils/validateObjectWithArrayProps.js
- lib/utils/validateObjectWithStringArrayProps.js
- lib/utils/validateObjectWithStringOrRegexArrayProps.js
- lib/utils/validateOptions.js
Closes #3945
This solves the problem, but I'm not sure about tests.
> Fix false negatives for CSS-In-JS in color-no-invalid-hex #3945

- docs/user-guide/example-config.md
Need to add: function-calc-no-invalid  -  https://stylelint.io/user-guide/rules/function-calc-no-invalid/
> Missing: function-calc-no-invalid

- docs/developer-guide/rules.md
- scripts/benchmark-rule.js
Fixes #3804 
Not specifically. Addresses issue with current benchmark script throwing a TypeError - which looks like it was caused by a refactor here: https://github.com/stylelint/stylelint/commit/973e07b81244eb359cfe5ee8cdf63a2ab4fba72c#diff-1b5afd6b670c8bdd40102c599cbc9697
PR contains code fixes and updates to documentation for the benchmarking script.
> Fix TypeError with benchmark-rule script

- .gitignore
- lib/rules/selector-max-attribute/__tests__/index.js
- lib/rules/selector-max-attribute/index.js
- lib/rules/selector-max-class/__tests__/index.js
- lib/rules/selector-max-combinators/__tests__/index.js
- lib/rules/selector-max-combinators/index.js
- lib/rules/selector-max-compound-selectors/__tests__/index.js
- lib/rules/selector-max-id/__tests__/index.js
- lib/rules/selector-max-pseudo-class/__tests__/index.js
- lib/rules/selector-max-specificity/__tests__/index.js
- lib/rules/selector-max-type/__tests__/index.js
- lib/rules/selector-max-type/index.js
- lib/rules/selector-max-universal/__tests__/index.js
- lib/rules/selector-max-universal/index.js
- lib/utils/__tests__/hasUnresolvedNestedSelector.test.js
- lib/utils/hasUnresolvedNestedSelector.js
- system-tests/005/__snapshots__/005.test.js.snap
Closes #3947
This seems to solve the problem for selector-max-type, but I wanted to put up a POC before moving on to the other rules to see if I'm moving in the right direction. Feedback is appreciated.
> Fix false negatives for nested at-rules in selector-max-*

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/at-rule-property-requirelist/README.md
- lib/rules/at-rule-property-requirelist/__tests__/index.js
- lib/rules/at-rule-property-requirelist/index.js
- lib/rules/index.js
Resolves #3985. Adds new rule `at-rule-property-requirelist`.
Not specifically. Addresses request for new rule, with specs outlined in the discussion here: https://github.com/stylelint/stylelint/issues/3985#issuecomment-473578949. If theres any issues, just let me know!
> Add at-rule-property-requirelist

- lib/rules/property-no-unknown/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxUrl.test.js
- lib/utils/hasTplInterpolation.js
- lib/utils/isStandardSyntaxDeclaration.js
> Fix false negatives for `isStandardSyntaxDeclaration`

- .travis.yml
- docs/developer-guide/prerequisites.md
- package.json
Closes https://github.com/stylelint/stylelint/issues/4000.
Node.js 8.15.1 is the latest 8.x version at the moment.
Changed Travis configuration to use Node.js 10 for pretest and coverage, as it theoretically should be faster. Also, it's recommended Node.js version for most users.
> Drop support for Node.js 6

- lib/__tests__/disableRanges-integration.test.js
- lib/rules/block-no-empty/README.md
- lib/rules/block-no-empty/__tests__/index.js
- lib/rules/block-no-empty/index.js
Closes #3925. 
Adds secondary option of `ignore: ["comments"]` to rule `block-no-empty`
Not really. If there's any issues with it, let me know :+1:
> Add ignore: ["comments"] to block-no-empty

- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
The problem is that parsed.toString() converts `//` with `/*` I avoid this converting not calling the fixer in a expected case.
Fixes #3847
> Fix value-keyword-case in scss list

- lib/cli.js
Closes #4028
We forgot to add the flag to the available options.
> Fix allow-empty-input CLI flag

- lib/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js
- lib/rules/function-linear-gradient-no-nonstandard-direction/index.js
Closes #4014 
Returns early if the first value is non-standard syntax.
> Fix false positives for dollar variables in function-linear-gradient-no-nonstandard-direction

- docs/developer-guide/prerequisites.md
- package.json
Via https://github.com/stylelint/stylelint/issues/4000#issuecomment-483020108
As AWS Labda currenty only supports Node.js 8.10, let's drop the required version down to 8.0.0
We can add this to the next _minor_ release 10.0.1
> Drop Node.js required version from 8.15.0 to 8.7.0

- lib/rules/color-no-invalid-hex/__tests__/index.js
- lib/rules/color-no-invalid-hex/index.js
> Fix false positives for hashes in URLs in color-no-invalid-hex

- lib/rules/function-calc-no-invalid/__tests__/index.js
- lib/utils/parseCalcExpression/parser.jison
- lib/utils/parseCalcExpression/parser.js
> Fix false positives for interpolation in function-calc-no-invalid

- lib/rules/declaration-block-semicolon-space-before/__tests__/index.js
- lib/rules/declaration-block-semicolon-space-before/index.js
> fix: autofix `!important` in `declaration-block-semicolon-space-before`

- docs/user-guide/rules.md
- lib/rules/selector-max-empty-lines/README.md
- lib/rules/selector-max-empty-lines/__tests__/index.js
- lib/rules/selector-max-empty-lines/index.js
Closes #3611", added autofix to selector-max-empty-lines
After fix number empty lines in a row <= max
> Add autofix to selector-max-empty-lines

- flow-typed/stylelint.js
- lib/__tests__/needlessDisables.test.js
- lib/__tests__/standalone-needlessDisables.test.js
- lib/formatters/__tests__/needlessDisablesStringFormatter.test.js
- lib/formatters/needlessDisablesStringFormatter.js
- lib/needlessDisables.js
Closes #4066.
When running `stylelint` CLI with `--report-needless-disables`, the output:
Before
```
assets/foo.css
start: 2
```
After 
```
assets/foo.css
unused rule: color-named, start line: 2, end line: 4
```
> Better error output for --report-needless-disables

- .travis.yml
- appveyor.yml
Node.js 12 was released on 2019-04-23, which is the **Current Release** version.
See <https://github.com/nodejs/Release#release-schedule>.
Related to #3299.
See [Node.js 12 changelog](https://github.com/nodejs/node/blob/v12.1.0/doc/changelogs/CHANGELOG_V12.md).
> Add Node.js 12 to CIs

- lib/reference/keywordSets.js
- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
Best practice for eliminating FOUC when using custom elements [1]
```css
app-drawer:not(:defined) {
/* Pre-style, give layout, replicate app-drawer's eventual styles, etc. */
display: inline-block;
height: 100vh;
opacity: 0;
transition: opacity 0.3s ease-in-out;
}
```
[1]: https://developers.google.com/web/fundamentals/web-components/customelements#prestyle
Closes #4080 
> Enhancemenet: add `:defined` pseudo class, fix #4080

- package.json
Bumping `postcss-jsx` to include fix for template literal interpolation in CSS-in-JS. https://github.com/gucong3000/postcss-jsx/issues/49
> Bump postcss-jsx version

- appveyor.yml
Before [the change](https://github.com/stylelint/stylelint/pull/4072) AppVeyor took 5-7 minutes to complete.
https://ci.appveyor.com/project/stylelint/stylelint/builds/24925881
https://ci.appveyor.com/project/stylelint/stylelint/builds/24825609
After change it takes 13-23 minutes:
https://ci.appveyor.com/project/stylelint/stylelint/builds/24976236 13 minutes.
https://ci.appveyor.com/project/stylelint/stylelint/builds/25120885 23 minutes and false fail.
> Revert adding Node.js 12 in AppVeyor

- lib/rules/block-no-empty/__tests__/index.js
- lib/rules/block-no-empty/index.js
`block-no-empty` should allow `@import` statements, but it's currently crashing with error "Cannot read property 'every' of undefined"
Closes #4109
> Fix crash in block-no-empty

- docs/user-guide/faq.md
Dead link: https://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
New link: https://michael-kuehnel.de/tooling/2018/03/22/helpers-and-tips-for-npm-run-scripts.html
> Fix dead link about "npm run scripts" in FAQ

- lib/rules/selector-max-compound-selectors/README.md
HTTPS -> HTTP
NG: <https://smacss.com/book/applicability>
OK: <http://smacss.com/book/applicability>
> Fix dead "SMACSS book" link in a rule doc

- README.md
Contributors image is is 1.4mb. It's too heavy for our new website.
> Remove contributors image

- docs/user-guide/semantic-versioning-policy.md
Small typo I spotted while working on #4151.
> Fix typo in semantic versioning policy

- lib/rules/unit-no-unknown/__tests__/index.js
- lib/utils/getUnitFromValueNode.js
Closes #4162 
I noticed that lint-staged changed the way how it's configured. From [their document](https://github.com/okonet/lint-staged/blob/master/README.md#ignoring-files), they encourage to use ignore configuration of each linter. And since this file is already in `.eslintignore` and `.prettierignore`, I believe it's safe to remote corresponding line in lint-staged config.
> fix `no-unit-unknown` rule for variable usage

- package.json
Related discussion in #4163 
Quoted from #4163:
> I noticed that lint-staged changed the way how it's configured. From [their document](https://github.com/okonet/lint-staged/blob/master/README.md#ignoring-files), they encourage to use ignore configuration of each linter. And since this file is already in `.eslintignore` and `.prettierignore`, I believe it's safe to remote corresponding line in lint-staged config.
> fix: lint-staged config

- lib/rules/no-duplicate-selectors/__tests__/index.js
- lib/rules/no-duplicate-selectors/index.js
Fixes #4113 
current test cases can not find this problem, to reproduce in current `master` branch commit ->`1178f2d2d4c7d83d12ad4ec55b686a7bf7e28995` add:
```expect(output.results[0].warnings).toHaveLength(1);```
here https://github.com/stylelint/stylelint/blob/master/jest-setup.js#L92
run `node node_modules/jest/bin/jest.js lib/rules/no-duplicate-selectors/__tests__/index.js`
> fix no-duplicate-selectors

- lib/rules/max-line-length/__tests__/index.js
- lib/rules/max-line-length/index.js
> fix max-line-length rule

- lib/cli.js
- system-tests/cli/cli.test.js
- system-tests/cli/stylesheet.css
Fixes #4076, #2369, #4100. 
This PR does the same change as #2731, which was closed for cleanup and never reopened. The current behavior can be a source of confusion for people used to ESLint’s [`--report-needless-disables`](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives). It also seems a bit wasteful to have to run linting twice just to get the extra reporting of unused disable comments.
> Stop skipping linting when --report-needless-disables CLI flag is used. Fix #4076

- lib/rules/selector-max-attribute/index.js
- lib/rules/selector-max-class/index.js
- lib/rules/selector-max-compound-selectors/index.js
- lib/rules/selector-max-id/index.js
- lib/rules/selector-max-pseudo-class/index.js
- lib/rules/selector-max-type/index.js
- lib/rules/selector-max-universal/index.js
- lib/rules/selector-pseudo-class-blacklist/__tests__/index.js
- lib/rules/selector-pseudo-class-case/__tests__/index.js
- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
- lib/rules/selector-pseudo-class-parentheses-space-inside/__tests__/index.js
- lib/rules/selector-pseudo-class-whitelist/__tests__/index.js
- lib/utils/__tests__/isLogicalCombination.test.js
- lib/utils/isLogicalCombination.js
closes https://github.com/stylelint/stylelint/issues/2657
nothing
> support logical combinations

- docs/user-guide/rules.md
- lib/rules/max-empty-lines/README.md
- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-empty-lines/index.js
> Add autofix to max-empty-lines

- lib/__tests__/printConfig.test.js
Fixes Jest `jest/valid-expect` notices reported here: https://github.com/stylelint/stylelint/pull/4187#discussion_r310579444
cc @evilebottnawi
> Fix jest/valid-expect issues

- lib/rules/property-no-unknown/__tests__/index.js
- package.json
> Property no unknown

- docs/user-guide/complementary-tools.md
A while ago I created a [Jest runner](https://jestjs.io/docs/en/configuration#runner-string) that runs stylelint. I've been using it in several of my projects, have it well tested, and use dependabot to keep it up to date. Since I've found using Jest to run my projects' unit tests and ensure code style to be very convenient, I'd love to have [`jest-runner-stylelint`](https://github.com/keplersj/jest-runner-stylelint) listed in the documentation to better share this with other stylelint users.
> Add jest-runner-stylelint to build tool plugins

- lib/rules/no-eol-whitespace/__tests__/index.js
- lib/rules/no-eol-whitespace/index.js
> fix no-eol-whitespace

- lib/__tests__/standalone-cache.test.js
- lib/__tests__/standalone-syntax.test.js
- lib/standalone.js
- lib/vendor/writeFileAtomic.js
- lib/writeOutputFile.js
- package.json
- system-tests/fix/fix.test.js
- system-tests/outputFile/outputFile.test.js
remove [pify](https://github.com/sindresorhus/pify) in favor of node 8 [util.promisify](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original)
nothing
> remove pify in favor of node 8 util.promisify

- CHANGELOG.md
- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/unicode-bom/README.md
- lib/rules/unicode-bom/__tests__/index.js
- lib/rules/unicode-bom/index.js
Closes #3792.
I think it's better to add the auto-fix functionality separately, because first we need to fix the bug in stylelint that causes BOM to be cut out in any auto-fix run (https://github.com/stylelint/stylelint/issues/4228).
> Introduce unicode-bom rule

- lib/rules/function-calc-no-invalid/__tests__/index.js
- lib/rules/function-comma-space-after/__tests__/index.js
- lib/rules/function-parentheses-space-inside/__tests__/index.js
- lib/rules/function-whitespace-after/__tests__/index.js
- lib/rules/indentation/__tests__/html.js
- lib/rules/length-zero-no-unit/__tests__/index.js
- lib/rules/no-eol-whitespace/__tests__/index.js
- lib/rules/no-extra-semicolons/__tests__/index.js
- lib/rules/number-max-precision/__tests__/index.js
- lib/rules/number-no-trailing-zeros/__tests__/index.js
- lib/rules/selector-list-comma-space-after/__tests__/index.js
- lib/rules/selector-list-comma-space-before/__tests__/index.js
- lib/rules/selector-max-compound-selectors/__tests__/index.js
- lib/rules/selector-pseudo-class-blacklist/__tests__/index.js
- lib/rules/selector-pseudo-class-case/__tests__/index.js
- lib/rules/unit-case/__tests__/index.js
fixes mismatched warnings count.
PR provides fix for 
- `indentation`
- `number-max-precision`
- `number-no-trailing-zeros`
- `selector-pseudo-class-blacklist`
- `function-calc-no-invalid`
- `function-comma-space-after`
- `function-parentheses-space-inside`
- `function-whitespace-after`
- `length-zero-no-unit`
- `no-eol-whitespace`
- `no-extra-semicolons`
- `selector-list-comma-space-after`
- `selector-list-comma-space-before`
- `selector-pseudo-class-case`
- `unit-case`
nothing
> Check all reported warnings in tests

- lib/rules/block-closing-brace-empty-line-before/__tests__/index.js
- lib/rules/block-opening-brace-newline-after/__tests__/index.js
- lib/rules/media-feature-colon-space-after/__tests__/index.js
- lib/rules/media-feature-colon-space-before/__tests__/index.js
- lib/rules/media-feature-range-operator-space-after/__tests__/index.js
- lib/rules/media-feature-range-operator-space-before/__tests__/index.js
- lib/rules/media-query-list-comma-space-after/__tests__/index.js
- lib/rules/media-query-list-comma-space-before/__tests__/index.js
- lib/rules/number-leading-zero/__tests__/index.js
- lib/rules/selector-list-comma-newline-before/__tests__/index.js
- lib/rules/selector-max-id/__tests__/index.js
- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
- lib/rules/selector-pseudo-class-parentheses-space-inside/__tests__/index.js
- lib/rules/selector-pseudo-element-colon-notation/__tests__/index.js
- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/value-list-comma-space-after/__tests__/index.js
- lib/rules/value-list-comma-space-before/__tests__/index.js
fix tests for:
* block-closing-brace-empty-line-before
* block-opening-brace-newline-after
* media-feature-colon-space-after
* media-feature-colon-space-before
* media-feature-range-operator-space-after
* media-feature-range-operator-space-before
* media-query-list-comma-space-after
* media-query-list-comma-space-before
* number-leading-zero
* selector-max-id
* selector-list-comma-newline-before
* selector-pseudo-class-no-unknown
* selector-pseudo-class-parentheses-space-inside
* selector-pseudo-element-colon-notation
* unit-no-unknown
* value-list-comma-space-after
* value-list-comma-space-before
nothing
> enable strict warnings count check

- lib/formatters/stringFormatter.js
related to https://github.com/stylelint/stylelint/issues/2454
"Eager" Loading `table` costs about 30ms, see 
https://gist.github.com/vankop/f83bdeda2cae617b4a801d8e210454ef
nothing
> load table module lazy

- lib/__tests__/standalone.test.js
- lib/getPostcssResult.js
Avoid problems like https://github.com/stylelint/stylelint/pull/4264 and https://github.com/stylelint/stylelint/pull/4239.
Now all syntaxes could be found in the code by searching by package name.
> Explicitly specify syntax module name

- bin/stylelint.js
- package.json
inspired by https://github.com/eslint/eslint/pull/11921 =)
nothing
> feat: add v8-compile-cache

- lib/rules/property-no-unknown/index.js
minor rule performance fix
nothing
> use Set instead of Array in property-no-unknown

- lib/rules/selector-max-universal/README.md
- lib/rules/selector-max-universal/index.js
related to https://github.com/stylelint/stylelint/issues/4232
Nothing. I have also updated some info in README
> fix: selector-max-universal

- docs/developer-guide/rules.md
- lib/rules/property-no-unknown/README.md
- lib/rules/property-no-unknown/__tests__/index.js
- lib/rules/property-no-unknown/index.js
Closes #4270 
I think it's okay as-is. It's implementing what was discussed on the issue, with docs and tests (and a small typo fix).
> Add ignoreSelectors option to property-no-unknown

- .editorconfig
- .prettierrc.js
- package.json
Follow-up to https://github.com/stylelint/stylelint/pull/4259.
I've configured `*.md`, `*.css` and `package.json` to use spaces, so these files are not be broken by new configuration. They use spaces and in many places it's critical for alignment and/or correct test results (like system tests).
ESLint config change is to correct parsing trailing comma in function arguments.
> Use spaces for *.md, *.css and package.json formatting

- docs/user-guide/configuration.md
We quite often point people towards this section of the docs. It'll be easier if had a linkable heading.
> Make docs about turning rules off linkable

- docs/user-guide/complementary-tools.md
Hi!
I created GitHub Action to run stylelint with [reviewdog](https://github.com/reviewdog/reviewdog) which can posts review comments on GitHub PullRequests.
https://github.com/marketplace/actions/run-stylelint-with-reviewdog
In case you're interested in, I created this pull-request. Please feel free to close it if it's not worth mentioning this action.
> Add GitHub Action to run stylelint with reviewdog

- lib/__tests__/standalone.test.js
- lib/cli.js
- lib/getPostcssResult.js
Needed to fix https://github.com/stylelint/stylelint-demo/issues/155.
Currently there is no way to specify “css” syntax.
> Add "css" option to --syntax parameter

- lib/__tests__/ignore.test.js
- lib/__tests__/standalone-syntax.test.js
Closes https://github.com/stylelint/stylelint/issues/4303.
I rewrote tests to be less complex. Following common sense and inspired by [Avoid Nesting when you're Testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing).
And I fixed stability issues. They were pretty simple as it turned out. When we use glob for `files` we can't guarantee what order of files we get. Therefore results we get from stylelint could be in different order between two runs. That's why it was failing on Windows a lot. And luckily it was failing for me on macOS, so I could find the problem :)
> Improve test stability

- package.json
Closes #4322
I was trying to run tests (`npm test`) on Windows and it wouldn't finish. `npm run jest` worked, but did not include any prettier checks/fixes.
I tested this on WSL Bash (Ubuntu 19.04) and macOS 14.0 (also bash).
> add double quotes to prettier glob

- lib/rules/declaration-block-no-redundant-longhand-properties/README.md
The docs say:
> Flexbox-related properties can be ignored using `ignoreShorthands: ["/flex-/"]` (see below).
That doesn't work, however `ignoreShorthands: ["/flex/"]` does. This removes the hyphen in the documentation.
> fix(docs): remove hypen from flex regex

- lib/reference/keywordSets.js
- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
Closes #4236 
:is is still an experimental technology, but issue #4236 asked for a PR.
https://developer.mozilla.org/en-US/docs/Web/CSS/:is
> add :is to pseudo-class list. fixes #4236.

- lib/rules/no-eol-whitespace/__tests__/index.js
- lib/rules/no-eol-whitespace/index.js
fix https://github.com/stylelint/stylelint/issues/4309
Nothing
> Fix case when raws.after/before could be undefined or null

- lib/__tests__/standalone-syntax.test.js
- lib/getPostcssResult.js
Fixing my mistakes https://github.com/stylelint/stylelint-demo/pull/177#issuecomment-540594505
postcss-safe-parser is just a parser, so it needs a stringifier.
> Fix CSS syntax configuration when `--syntax css` is used

- README.md
This will fix following problem:
It will be fix after we release new stylelint version, though. Because content is generated from stylelint package.
> Fix markup issue for the website

- .github/workflows/nodejs.yml
- jest-setup.js
Temporary workaround for https://github.com/stylelint/stylelint/issues/4337.
Used [this](https://github.com/Microsoft/vscode/issues/9448#issuecomment-245024153) idea. Because for Windows case in a path is not important.
> Add workaround for failing Windows environment

- lib/vendor/writeFileAtomic.js
- lib/writeOutputFile.js
add types to writeOutputFile.js
Since `writeFileAtomic` is a fork, I decided to skip it from type checking and use it as blackbox and just define output interface
> How to check that TS works?
run `npm run lint:types | grep writeOutputFile`
run `npm run lint:types | grep writeFileAtomic`
> types: add types to writeOutputFile.js

- lib/cli.js
- lib/formatters/disableOptionsReportStringFormatter.js
- lib/formatters/stringFormatter.js
- lib/formatters/verboseFormatter.js
- lib/utils/__tests__/checkInvalidCLIOptions.test.js
- lib/utils/checkInvalidCLIOptions.js
chalk types
chalk flow types using `module.exports` instead of `default` exports, so I have used flowfixme in some places to prevent errors
> How to check that TS work correctly?
> types: use default export from chalk

- lib/rules/comment-empty-line-before/__tests__/index.js
- lib/utils/__tests__/isSharedLineComment.test.js
- lib/utils/isSharedLineComment.js
Fixes https://github.com/stylelint/stylelint/issues/2835.
There were false positives when beginning of the rule/at-rule was on a different line than start of the block (`{`).
> Fix false positives for shared-line comment as a first child

- .github/workflows/nodejs.yml
[Node.js 12 is LTS now.](https://nodejs.org/en/blog/release/v12.13.0/)
> Update default Node.js in CI

- lib/cli.js
- lib/createStylelint.js
- lib/formatters/stringFormatter.js
- lib/index.js
- lib/standalone.js
- lib/utils/configurationError.js
- lib/utils/getFileIgnorer.js
- lib/utils/noFilesFoundError.js
- package-lock.json
- package.json
- types/postcss/index.d.ts
- types/stylelint/index.d.ts
- types/table/index.d.ts
🎉 related to https://github.com/stylelint/stylelint/issues/4245 🥁, all TODOs we can resolve in separate PRs 
Nothing
> add types to standalone.js, cli.js, index.js, required utils

- docs/user-guide/cli.md
- docs/user-guide/configuration.md
- docs/user-guide/node-api.md
- lib/__tests__/ignore.test.js
- lib/cli.js
- lib/standalone.js
Closes https://github.com/stylelint/stylelint/issues/4383
> Remove ignoring bower_components folder by default

- lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.js
- lib/utils/__tests__/isStandardSyntaxValue.test.js
- lib/utils/isStandardSyntaxValue.js
Issue: Rules are not ignored when using SCSS namespace (https://github.com/stylelint/stylelint/issues/4378)
There is a rule to ignore SCSS variable in "lib/utils/isStandardSyntaxValue.js".
I added a rule there that also ignores the SCSS namespace.
> Fix to ignore SCSS namespace

- docs/developer-guide/formatters.md
- lib/__tests__/standalone-formatter.test.js
- lib/standalone.js
Fixes #4136. I've shuffled things around in the standalone `prepareReturnValue()` function so that the `output` is set last and the formatting function gets the `returnValue` object as its second argument, so that needless disables can be accessed like so in a custom formatter:
```js
module.exports = function customFormatter(results, returnValue) {
const errors = formatErrors(results)
if (returnValue.needlessDisables) {
errors.push(...formatNeedlessDisables(returnValue.needlessDisables))
}
return errors.join('\n')
}
```
The `returnValue` object includes:
- the `errored` flag
- a `needlessDisables` array if configured with `reportNeedlessDisables: true`
- an `invalidScopeDisables` array if configured with `reportInvalidScopeDisables: true`
- a `maxWarningsExceeded` object if configured …
> Pass returnValue to formatter with needlessDisables + invalidScopeDisables

- lib/rules/length-zero-no-unit/__tests__/index.js
- lib/rules/length-zero-no-unit/index.js
It should close #4250 . 
Nope, the logic of the PR is quite clear.
> Ignore some properties with 0 value (#4250)

- package-lock.json
- package.json
Closes https://github.com/AleshaOleg/postcss-sass/issues/120
Short description: Stylelint sometimes crashes while, users using some unsupported rules which starts from `@`.
> Update postcss-sass to 0.4.2

- docs/user-guide/node-api.md
The `css` syntax has been added since [v11.1.0](https://github.com/stylelint/stylelint/blob/11.1.0/CHANGELOG.md#1110).
See also:
https://github.com/stylelint/stylelint/blob/334f615149fe7b35aaf8b884097bbaf7d92837ad/lib/getPostcssResult.js#L95
> Add missing `css` to syntax list on Node API doc

- lib/rules/length-zero-no-unit/__tests__/index.js
- lib/rules/length-zero-no-unit/index.js
- lib/utils/__tests__/isLessVariable.test.js
- lib/utils/isLessVariable.js
> Ignore less variables (#4200)

- README.md
- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/user-guide/configuration.md
- docs/user-guide/faq.md
Inspired by [How to remove condescending language from documentation](https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p).
> Remove condescending language in documentation

- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
“The stylelint” part looks redundant. Screenshot from our website:
> Make docs titles more consistent

- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/user-guide/about-rules.md
- docs/user-guide/cli.md
- docs/user-guide/configuration.md
- docs/user-guide/faq.md
- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
We had these markers so previous version of our website knew where to put Table of Content. Now Table of Content renders separate from content area, in a sidebar.
> Remove unused TOC markers

- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/unit-no-unknown/index.js
> Ignore `x` unit in some cases

- docs/developer-guide/formatters.md
- docs/developer-guide/plugins.md
- docs/developer-guide/processors.md
- docs/developer-guide/rules.md
- docs/user-guide/about-rules.md
- docs/user-guide/css-processors.md
- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
Tried to make all JavaScript examples in a consistent code style.
> Use consistent code style for JavaScript examples

- package.json
It seems these aren't needed in production
> package.json: skip `testUtils` folder too.

- docs/user-guide/complementary-tools.md
None.
I've halted to maintain it as I'm now mainly working as an Android dev and no longer have much interest in stylelint.
Thanks for including my plugin to this list for a long time.
> Remove VSCode extension from the list of tools

- lib/rules/function-calc-no-invalid/index.js
> Remove `_.isNil`

- lib/formatters/stringFormatter.js
- lib/formatters/verboseFormatter.js
Refs #4412
@hudochenkov let's confirm the behavior is the same, i.e. we only want to loop through the object's own enumerable keys only and we don't care about the order
> Remove `_.forOwn`

- package-lock.json
- package.json
- scripts/benchmark-rule.js
Unfortunately this doesn't flatten our deps tree since request is included in other devDependencies:
```
C:\Users\xmr\Desktop\stylelint>npm ls request
stylelint@12.0.0 C:\Users\xmr\Desktop\stylelint
`-- jest@24.9.0
`-- jest-cli@24.9.0
`-- jest-config@24.9.0
`-- jest-environment-jsdom@24.9.0
`-- jsdom@11.12.0
`-- request@2.88.0
```
> Replace request with got

- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/unit-no-unknown/index.js
- lib/utils/__tests__/isMap.test.js
- lib/utils/isMap.js
> Ignore map property name (#4375)

- lib/rules/string-no-newline/__tests__/index.js
- lib/rules/string-no-newline/index.js
- lib/utils/__tests__/isStandardSyntaxSelector.test.js
- lib/utils/isStandardSyntaxSelector.js
Fixes #4489.
Problem lies in many places. We are passing selector `<% COLORS.each do |color| %>\na` to `postcss-selector-parser`, and the later falls into endless loop. Which is understandable. This case might be fixed in `postcss-selector-parser`, but it won't happen any time soon. Currently, we're using `postcss-selector-parser@3.1.0`, while the latest version is `6.0.2`. We can't [upgrade](https://github.com/stylelint/stylelint/pull/3988), because there are still some issues in new version of a parser which needs to be resolved in a parser.
So, the only choice we have is to fix problem in stylelint. My solution is not universal, but if will fix the problem. It might create …
> Ignore ERB template tags in selectors

- .gitignore
- lib/rules/selector-type-no-unknown/__tests__/index.js
- lib/rules/selector-type-no-unknown/index.js
Fix for `selector-type-no-unknown` rule
Closes #4472
> Fix SVG tags whitelist in selector-type-no-unknown rule (#4472)

- lib/__tests__/invalidScopeDisables.test.js
- lib/invalidScopeDisables.js
- lib/standalone.js
There was a comment in `lib/standalone.js:312` that `stylelint._options.config` might be `undefined`, but 
`invalidScopeDisables.js` function always expected an object as 2nd parameter.
For me there were 2 ways to fix that:
* adding  a conditional expression to `stylelint._options.config  || {}` for `invalidScopeDisables` call, or
* changing`invalidScopeDisables` interface to accept `undefined` as 2nd parameter.
I've chosen 2nd option, to prevent adding more conditions in the future in we need to call `invalidScopeDisables` somewhere else with the optional config param.
Closes #4479
> Fix stylelint config usage

- lib/__tests__/disableRanges.test.js
- lib/__tests__/needlessDisables.test.js
- lib/assignDisabledRanges.js
Closes #4328.
I'm not sure I understood the problem correctly ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯ But look like removing incorrect condition fixes types issue, and doesn't break any test.
> Remove unused condition

- .github/workflows/nodejs.yml
- docs/developer-guide/prerequisites.md
- package.json
> Drop Node.js 8

- package-lock.json
- package.json
[meow v6](https://github.com/sindresorhus/meow/releases/tag/v6.0.0) has own built-in type definitions.
See <https://github.com/stylelint/stylelint/pull/4504#issuecomment-572354918>
~~Blocked by #4517~~
> Remove unneeded `@types/meow` package

- jest-setup.js
- package-lock.json
- package.json
This brings package.json and package-lock.json versions up to date.
Do note that due to the way dependabot works, regenerating the lock file is needed after some time, otherwise the deps tree isn't flattened as much as it could be.
> Regenerate package-lock.json

- lib/rules/media-feature-parentheses-space-inside/__tests__/index.js
- lib/rules/media-feature-parentheses-space-inside/index.js
> Process multiple spaces in media (#4509)

- docs/user-guide/faq.md
None, as it's additional info in documentation FAQ section.
For the past 2 months I've met several issues about not reporting invalid syntax. May be it's good to add such info in the doc.
If it's completely irrelevant info feel free to close this PR.
> Add info about invalid syntax in FAQ

- lib/__tests__/cli.test.js
- lib/cli.js
- lib/utils/__tests__/checkInvalidCLIOptions.test.js
- lib/utils/checkInvalidCLIOptions.js
This aims to prepare for type-checking `cli.js` and does NOT type-check actually (I will do it on another PR).
- Camelize option names for type-checking.
- Add missing `type` for some options.
- Sort options alphabetically for readability.
- Add a unit test for the definition (A system test is too much for this purpose).
See <https://github.com/stylelint/stylelint/pull/4504#issuecomment-572354918> for details.
> Refactor CLI options definition

- lib/rules/font-family-no-missing-generic-family-keyword/README.md
Closes https://github.com/stylelint/stylelint.io/issues/120
The structure of the README was atypical as we [usually place these things](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#write-the-readme) in the expanded description.
> Fix atypical rule README structure

- .github/workflows/nodejs.yml
No functional change, just reindent the file.
Split from #4529
> Reindent nodejs.yml

- package-lock.json
- package.json
- system-tests/fix/fix.test.js
Fixes #4449
Bumps dependency to include this upstream PR (which has tests): https://github.com/gucong3000/postcss-jsx/pull/67
There's a bit of extra noice in the package-lock but that's just the result of me running `npm install` - seems something was outdated previously.
> Bump postcss-jsx to 0.36.4

- system-tests/cli/cli.test.js
What does this do:
- Remove the workaround for Node < 7. Now, Node 10 is required.
- Inline unnecessary `Promise.resolve()`.
- Convert to an arrow function for consistency in a file.
- Convert to `async` functions for readability.
None, as it's refactoring for the system test code.
> Refactor CLI system test

- scripts/benchmark-rule.js
I didn't switch to v4.x here, but let me know if you want to
> scripts/benchmark-rule.js: Switch to Bootstrap 4.4.1

- lib/rules/indentation/__tests__/rules.js
- lib/rules/indentation/index.js
Fixes #4551.
@jeddy3 Feel free to add more tests
> Fix RangeError in indentation regression

- lib/rules/string-quotes/__tests__/index.js
- lib/rules/string-quotes/index.js
> Fix wrong openIndex calculation in string-quotes (#4395)

- docs/maintainer-guide/releases.md
We should remove vscode extension from release template now that the vscode extension [is no longer tied](https://github.com/stylelint/vscode-stylelint/pull/26) to a particular release.
> Remove vscode extension from release template

- jest-setup.js
- lib/rules/selector-attribute-brackets-space-inside/__tests__/index.js
- lib/rules/selector-attribute-quotes/index.js
- lib/rules/selector-descendant-combinator-no-non-space/README.md
- lib/rules/selector-descendant-combinator-no-non-space/__tests__/index.js
- lib/rules/selector-descendant-combinator-no-non-space/index.js
- lib/rules/selector-pseudo-class-parentheses-space-inside/README.md
- lib/rules/selector-pseudo-class-parentheses-space-inside/__tests__/index.js
- lib/rules/selector-pseudo-class-parentheses-space-inside/index.js
- lib/rules/string-quotes/index.js
- lib/utils/isStandardSyntaxCombinator.js
- package-lock.json
- package.json
References https://github.com/orgs/stylelint/teams/core/discussions/18
Replaces https://github.com/stylelint/stylelint/pull/3988
I've ported over the changes from https://github.com/stylelint/stylelint/pull/3988. We changed our formatting and moved to TS JS Docs from flow since we made the original pull request
I believe only two rules are affected by this update:
- `selector-descendant-combinator-no-non-space` will now outright ignore selectors containing comments
- `selector-pseudo-class-parentheses-space-inside` can now longer autofix pseudo-classes that contain comments
I think these are minor limitations for the sake of updating. I've added a note to the READMEs of both …
> Update selector parser

- CONTRIBUTING.md
- README.md
- docs/about/linting.md
- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/maintainer-guide/issues.md
- docs/maintainer-guide/pull-requests.md
- docs/user-guide/configure.md
- docs/user-guide/get-started.md
- docs/user-guide/ignore-code.md
- docs/user-guide/integrations/editor.md
- docs/user-guide/integrations/other.md
- docs/user-guide/integrations/task-runner.md
- docs/user-guide/rules/about.md
- docs/user-guide/usage/cli.md
- docs/user-guide/usage/node-api.md
- docs/user-guide/usage/options.md
- docs/user-guide/usage/postcss-plugin.md
(If time is short, please review https://github.com/stylelint/stylelint/pull/4592 over over this pull request so that we can address https://github.com/stylelint/stylelint/issues/3514.)
Follow up from https://github.com/stylelint/stylelint/pull/4561
I went through the overhauled docs again now that they are live on the website.
I want to make sure the:
- sidebars worked well
- content was a clear as it could be when view on the website
In this pull request I:
- updated [some code examples](https://github.com/stylelint/stylelint/blob/3bc680e1c8c46942ff082da50966f36e4396d49f/docs/user-guide/configure.md#rules) to be more complete
- removed duplication in the [steps we link to from the saved replies](https://github.com/stylelint/stylelint/blob/3bc680e1c8c46942ff082da50966f36e4396d49f/docs/dev …
> Improve documentation

- docs/about/syntaxes.md
- docs/developer-guide/syntaxes.md
- docs/toc.md
- docs/user-guide/usage/options.md
- lib/lintSource.js
- lib/standalone.js
- system-tests/fix/fix.test.js
- types/postcss/extensions.d.ts
- types/stylelint/index.d.ts
(If time is short, please review this pull request over https://github.com/stylelint/stylelint/pull/4591 so that we can address https://github.com/stylelint/stylelint/issues/3514.)
Follow on from https://github.com/stylelint/stylelint/pull/4573
This pull request is also part of the [stream of work to better surface syntaxes](https://github.com/stylelint/stylelint/issues/4560#issuecomment-578907499) so that we can muster support for them. After we merge this pull request, I plan to post comments on the issues mentioned in https://github.com/stylelint/stylelint/issues/4574 pointing to this new feature.
--
I'm not sure how it happened, but buried at the bottom of …
> Reinstate and document workaround feature

- lib/formatters/stringFormatter.js
- lib/printConfig.js
- lib/rules/color-named/generateColorFuncs.js
- lib/rules/indentation/index.js
- lib/utils/checkInvalidCLIOptions.js
- lib/utils/declarationValueIndex.js
- package.json
See https://github.com/stylelint/stylelint/pull/4453#issuecomment-570963865
The issues detected by the addition of this rule will require updating
> Add `no-confusing-arrow` ESLint rule

- lib/reference/keywordSets.js
- lib/rules/selector-pseudo-element-no-unknown/__tests__/index.js
> Fix false positive for part pseudo-element in selector-pseudo-element-no-unknown

- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
It should close #4605 .
I think its necessary to convert prop to lower case before any comparison can be done.
> Fix false positives for longhand grid-column/row-* properties in value-keyword-case

- .github/ISSUE_TEMPLATE/REPORT_A_BUG.md
- CODE_OF_CONDUCT.md
- SECURITY.md
Following on from https://github.com/stylelint/stylelint/pull/4606.
These are [organisation-wide](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) community health files and live [in the `.github` repo](https://github.com/stylelint/.github).
> Remove org-level community health files

- lib/rules/selector-max-type/README.md
Currently at https://stylelint.io/user-guide/rules/selector-max-type, under the patterns that are not considered as violations, there is an extra `The following patterns are not considered violations:`
This PR removes that extra line of copy.
**Before:**
---- 
**After:**
> Documentation Fix -- Removing extra line of copy

- lib/rules/function-calc-no-invalid/__tests__/index.js
- lib/rules/function-calc-no-invalid/index.js
- lib/utils/__tests__/isStandardSyntaxMathFunction.test.js
- lib/utils/isStandardSyntaxMathFunction.js
Fixes #4114, #4533.
Closes #4534.
@jeddy3 [said](https://github.com/stylelint/stylelint/issues/4114#issuecomment-573375622):
> Built-in rules ignore non-standard syntax. This rule should only check the validity of `calc` functions containing standard CSS syntax.
To be honest, I don't think this is a good approach for users. `function-calc-no-invalid` catches many cases of invalid `calc` for preprocessor users. But with this PR, we reduce usefulness of this rule for these users.
> Ignore non-standard syntax in function-calc-no-invalid

- package-lock.json
None (I didn't felt it was necessary to open an issue for this unless you want me to reference other issues pointing to `stylelint`?).
It uses the `minimist` version (nested dependency of `postcss-sass`) where the patch for the [Prototype pollution](https://www.npmjs.com/advisories/1179) has been fixed.
> Fix the vulnerability in minimist

- lib/rules/font-family-no-missing-generic-family-keyword/README.md
- lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.js
- lib/rules/font-family-no-missing-generic-family-keyword/index.js
Closes #3288
Seems to work alright so far. Something I'm struggling with is how a font family name in quotes should be written. I couldn't tell if that works and I'm just writing the test poorly or this doesn't work with quoted names.
> Add ignoreFontFamilies option to `font-family-no-missing-generic-family-keyword`

- lib/rules/unit-no-unknown/__tests__/index.js
- lib/rules/unit-no-unknown/index.js
Fixes #4653
However, I'm not super familiar with the ASTs involved, and I'm super open to suggestions if this is not an optimal fix.
> Fix false positives for x unit within vendor-prefixed image-set in unit-no-unknown

- .dependabot/config.yml
Example https://github.com/stylelint/stylelint-demo/pull/217, also the VSCode extension just had 12 PRs also, there are too many landing monthly on the same day and the merge conflicts and lock files make this difficult and time consuming to manage so many, increasing the frequency should reduce this, at least worth a try
n/a
> Change dependabot schedule to `weekly`

- docs/developer-guide/syntaxes.md
- lib/getPostcssResult.js
- lib/lintSource.js
- lib/rules/indentation/__tests__/javascript.js
- lib/rules/indentation/index.js
- package-lock.json
- package.json
- system-tests/fix/fix.test.js
- types/stylelint__postcss-css-in-js.d.ts
- types/stylelint__postcss-markdown.d.ts
- types/svg-tags/postcss-safe-parser.ts
Closes https://github.com/stylelint/stylelint/issues/4645
Closes https://github.com/stylelint/stylelint/issues/4119
It doesn't work yet. First, we need to release `@stylelint/postcss-css-in-js` and `@stylelint/postcss-markdown`. Then we can test and make changes to this PR.
> Replace syntaxes with our forks

- docs/user-guide/get-started.md
This category of rules is often overlooked. This pull request tweaks the copy in the getting started guide to give examples of what the rules are.
> Emphasise limiting rules

- docs/developer-guide/formatters.md
Closes https://github.com/stylelint/stylelint/issues/4668
Keeps it simple. We can always expand on it later if there's a need.
> Document passings args to formatters

- README.md
- docs/user-guide/usage/options.md
- lib/lintSource.js
- lib/rules/block-closing-brace-newline-after/__tests__/index.js
- system-tests/fix/fix.test.js
Closes #4704
We were only disabling autofix on files containing unscoped disable comments. This pull request disables it for both scoped and unscoped.
> Fix turning off autofix for sources containing scoped disable comments

- docs/user-guide/usage/cli.md
Hey there,
This is a quick documentation addition that closes #4661 - in particular, documenting linting multiple file extensions. I basically copy-paste the suggestion verbatim from @jeddy3.
The new section looks like:
Linting all `.css`, `.scss`, and `.sass` files:
```shell
stylelint "**/*.{css,scss,sass}"
```
I also updated the Example indices for all the other affected examples.
Let me know if there's anything else I should implement!
> Adding CLI example on linting multiple file extensions

- lib/utils/findAnimationName.js
> Fix comments in findAnimationName to not refer to font

- lib/lintSource.js
None, it's a housekeeping change. This line appears to be unused.
This line was [removed in July 2017](https://github.com/stylelint/stylelint/pull/2735/files#diff-5ad37590092c2098f0fb6d72557720ddL49). It was [re-added a couple of months later](https://github.com/stylelint/stylelint/commit/5df5e4251d5484cc8181f00fe640c915e367a060#diff-5ad37590092c2098f0fb6d72557720ddR116).
I can't find any other references to `standaloneIgnored` in the current release. I'm guessing that it was re-added in error.
> Remove unused line in lintSource.js

- lib/rules/max-empty-lines/README.md
Great reference, but not grammatically, nor literately, accurate.
No, it's self-explanatory. But, here's some reference:
- [one, of many available, references to the original text](https://time.com/4534903/moby-dick-chapter-one/)
- [em dash is typically used without spaces](https://www.thepunctuationguide.com/em-dash.html)
> Fix typo and remove inaccurate spaces from quote

- lib/__tests__/fixtures/plugin-async.js
- lib/__tests__/fixtures/plugin-conditionally-check-color-hex-case.js
- lib/__tests__/fixtures/plugin-primary-array.js
- lib/__tests__/fixtures/plugin-slashless-warn-about-foo.js
- lib/__tests__/fixtures/plugin-warn-about-bar.js
- lib/__tests__/fixtures/plugin-warn-about-foo.js
- lib/__tests__/fixtures/processor-triple-question-marks.js
- lib/__tests__/integration.test.js
- lib/formatters/stringFormatter.js
- lib/rules/function-url-quotes/index.js
- lib/rules/indentation/index.js
- lib/rules/linebreaks/__tests__/integration.test.js
- lib/rules/max-line-length/index.js
- lib/rules/no-empty-first-line/index.js
- lib/utils/isStandardSyntaxSelector.js
- lib/utils/isStandardSyntaxUrl.js
* simplify regex
* use Unicode escape in regex
* use `trimStart()` instead of the `trimLeft()` alias
* remove unneeded path separator from imports
I split these from the `xo` branch, let me know if you want me to make any changes 🙂
PS. I didn't change the `0-9` to `\d` in regex for now since I wasn't sure if everyone would like this change.
> Minor lint tweaks

- docs/developer-guide/rules.md
Ref https://github.com/stylelint/stylelint/pull/4744#discussion_r420705135
> Document explicitly checking type property when using forEach

- lib/rules/at-rule-property-requirelist/__tests__/index.js
- lib/rules/at-rule-property-requirelist/index.js
Fixes #4638 
It's self-explanatory.
If the `undefined` values represent a bug upstream, I'd be glad for a hint as to which project that might be.
> Avoid comments in at-rule-property-requirelist

- lib/rules/time-min-milliseconds/README.md
- lib/rules/time-min-milliseconds/__tests__/index.js
- lib/rules/time-min-milliseconds/index.js
Fixes #4552
Certainly.
* Previously, this rule considered the value to the shorthand properties to be space-separated lists. It is more correct to view them as comma-separated lists of animations (or transitions) whose values themselves are space-separated lists. This distinction becomes important when ignoring delay values in specific animation (or transition) values. ([MDN: [transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition), [animation](https://developer.mozilla.org/en-US/docs/Web/CSS/animation))
* Some of the test cases had transposed the timing function and the delay. This is fixed.
> Add an ignore option to time-min-milliseconds

- lib/rules/value-keyword-case/README.md
- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
Hi there,
This is a PR that adds an `ignoreFunctions: []` option to the `value-keyword-case` rule, as requested in #4648! I did this by adding the option to the valid option list, and then using `matchesStringOrRegExp` on the passed-in options. I also added tests based off of the discussion in the issue comments, and added documentation on the option to the rule's documentation page.
On my end, I ran `npm run format` and `npm run test`, and everything seems to work as intended. Let me know if there are any edge-cases/tests that I should add to the PR!
Closes #4648.
Nope!
> Add ignoreFunctions: [] to value-keyword-case

- lib/__tests__/needlessDisables.test.js
- lib/__tests__/standalone-needlessDisables.test.js
- lib/lintSource.js
- lib/needlessDisables.js
- lib/utils/report.js
- types/stylelint/index.d.ts
Closes #4203
This PR modifies ignoreDisables to not be implicitly used when using the reportNeedlessDisables option.
> Make --report-needless-disables CLI flag respect stylelint-disable commands

- docs/user-guide/rules/list.md
Relates to https://github.com/stylelint/stylelint/pull/4760, https://github.com/stylelint/stylelint/issues/4721 and https://github.com/stylelint/stylelint/issues/4720.
These existing three rules belong in the limit language features category as none are just stylistic. For example, `selector-pseudo-element-colon-notation`, like the upcoming `color-function-notation` rule, is about compatibility.
The stylistic category becomes only concerned with whitespace, case, quotes and trailing/leading zeroes.
> Fix categorisation of notation rules

- lib/reference/keywordSets.js
- lib/rules/media-feature-name-no-unknown/__tests__/index.js
Closes #4773.
- Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors
- Spec: https://drafts.csswg.org/mediaqueries-5/#forced-colors
- ChromeStatus entry: https://www.chromestatus.com/feature/5757293075365888
> Fix false positives for forced-colors in media-feature-name-* rules

- lib/rules/declaration-block-trailing-semicolon/__tests__/index.js
- lib/rules/declaration-block-trailing-semicolon/index.js
Fixes #4650 
Yes; @jeddy3 suggests a solution in https://github.com/stylelint/stylelint/issues/4650#issuecomment-599205149 that did not work for me: `isStandardSyntaxRule` only accepts Rule nodes, but if used in `declaration-block-trailing-semicolon`, it would also be given AtRule nodes (like in the SCSS test case: `a { @foo { color: pink } }`). This complicates things further because `isStandardSyntaxRule` examines the `selector` of the Rule which it receives, and AtRule has no `selector`.
This simple solution seems to work for now.
> Fix false positives for objects in declaration-block-trailing-semicolon

- lib/utils/__tests__/isStandardSyntaxValue.test.js
- lib/utils/isStandardSyntaxValue.js
Hi there, 
This is a PR that aims to address #4707, by adding a regex match to `isStandardSyntaxValue` that ignores values of the form `/__MSG_[^\s]+__/`, a set of runtime values often used by browsers for internationalization (more information [here](https://developer.chrome.com/extensions/i18n), as mentioned in the issue discussion). I also added two tests, one that checks for the positive, and one that checks for case-sensitivity.
As `value-keyword-case` uses `isStandardSyntaxValue`, this should resolve the false positive originally brought up in the issue.
Locally, this PR passes `npm run format` and `npm run test`.
Closes #4707.
Not on my end! Let me know if I should change …
> Fix false positives for WebExtension replacement keywords in value-keyword-case

- lib/rules/time-min-milliseconds/__tests__/index.js
- lib/rules/time-min-milliseconds/index.js
Refs #4782
The TypeError is only triggered when the new `ignore: ["delay"]` option is used (which was added in https://github.com/stylelint/stylelint/pull/4743). So the actual problem in #4782 may be an unrelated regression.
---
We'll need to [refactor the code](https://github.com/stylelint/stylelint/pull/4743#pullrequestreview-406653509) for `time-min-milliseconds` to address https://github.com/stylelint/stylelint/issues/4751 at some point.
> Fix TypeError for shorthand animation in time-min-milliseconds

- docs/user-guide/rules/list.md
- lib/rules/hue-degree-notation/README.md
- lib/rules/hue-degree-notation/__tests__/index.js
- lib/rules/hue-degree-notation/index.js
- lib/rules/index.js
Closes #4721
The rule can autofix both primary options as this rule is about explicitness vs shorthand convenience (with neither option being more right than the other), unlike [`color-function-notation`](https://github.com/stylelint/stylelint/pull/4760) which is concerned with modern vs legacy syntax.
> Add hue-degree-notation
