stylelint/stylelint

- lib/rules/function-url-scheme-whitelist/README.md
> Removed erroneous violation entry

- package.json
> chore: Bump Jest to 22.0.6

- decls/flow-typed/jest.js
Follow up to https://github.com/stylelint/stylelint/pull/3069#issuecomment-354417880
> chore: Update Jest Flow library definitions

- package.json
Ref: https://github.com/stylelint/stylelint/pull/3120#issuecomment-357070151
> Update greenkeeper label

- docs/user-guide/plugins.md
Adding `stylelint-react-native` to the list of stylelint plugins.
> Add link to stylelint-react-native

- decls/flow-typed/lodash.js
> chore: Update Flow library definitions

- docs/user-guide/processors.md
> docs: add stylelint-processor-glamorous to processors list

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/developer-guide/rules.md
> Add CODE_OF_CONDUCT.md

- bin/stylelint.js
- lib/cli.js
- system-tests/004/004.test.js
- system-tests/cli/cli.test.js
> Add system tests for CLI

- package.json
> fix(package): update postcss-html to version 0.17.0

- lib/rules/max-empty-lines/index.js
- lib/rules/no-empty-source/__tests__/index.js
- lib/rules/no-empty-source/index.js
- lib/utils/eachRoot.js
> Fix false positives for non-CSS files in no-empty-source

- lib/standalone.js
> Fix autofix writing to files that aren't changed

- package.json
> chore(package): update chalk to version 2.4.0

- appveyor.yml
This PR uses shallow clones like it is the case for Travis CI.
> chore: clone only last commit

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/keyframes-name-pattern/README.md
- lib/rules/keyframes-name-pattern/__tests__/index.js
- lib/rules/keyframes-name-pattern/index.js
> Added keyframes-name-pattern rule

- lib/rules/length-zero-no-unit/__tests__/index.js
- lib/rules/length-zero-no-unit/index.js
> fix: autofix for `length-zero-no-unit`

- lib/rules/at-rule-empty-line-before/README.md
- lib/rules/comment-empty-line-before/README.md
- lib/rules/comment-no-empty/README.md
- lib/rules/comment-word-blacklist/README.md
- lib/rules/declaration-block-semicolon-newline-after/README.md
- lib/rules/declaration-block-semicolon-space-after/README.md
- lib/rules/declaration-block-trailing-semicolon/README.md
- lib/rules/function-url-scheme-blacklist/README.md
- lib/rules/function-url-scheme-whitelist/README.md
- lib/rules/media-feature-name-case/README.md
- lib/rules/media-feature-name-no-unknown/README.md
- lib/rules/media-feature-name-whitelist/README.md
- lib/rules/property-no-unknown/README.md
- lib/rules/rule-empty-line-before/README.md
- lib/rules/selector-pseudo-class-no-unknown/README.md
- lib/rules/selector-pseudo-element-blacklist/README.md
- lib/rules/selector-pseudo-element-no-unknown/README.md
- lib/rules/selector-pseudo-element-whitelist/README.md
> Fix ignores inconsistency in rule READMEs

- docs/user-guide/cli.md
- docs/user-guide/node-api.md
- lib/cli.js
> Fix mentions of glob library

- .travis.yml
- appveyor.yml
This PR adds Node.js to the builds to test against the current stable release of Node.js.
> Add Node.js 10 to CIs

- lib/rules/block-opening-brace-space-before/README.md
- lib/rules/declaration-block-trailing-semicolon/README.md
- lib/rules/no-missing-end-of-source-newline/README.md
https://github.com/stylelint/stylelint/pull/3447#discussion_r201040388
There was a similar mistake, so I fixed it.
> Fixed document about autofix.

- docs/user-guide/rules.md
- lib/rules/at-rule-semicolon-newline-after/README.md
- lib/rules/at-rule-semicolon-newline-after/__tests__/index.js
- lib/rules/at-rule-semicolon-newline-after/index.js
#2829
this was originally #3146 but i accidentally deleted the remote of the branch so i'm reopening it here.
> Add autofix to at-rule-semicolon-newline-after

- flow-typed/npm/lodash_v4.x.x.js
- package.json
> chore(package): update flow-bin to version 0.76.0

- docs/user-guide/plugins.md
> Add stylelint-prettier plugin

- package.json
> chore(package): update eslint to 5.1.0

- docs/user-guide/example-config.md
- docs/user-guide/rules.md
- lib/rules/index.js
- lib/rules/linebreaks/README.md
- lib/rules/linebreaks/__tests__/index.js
- lib/rules/linebreaks/index.js
Closes https://github.com/stylelint/stylelint/issues/3114
~It is a first draft. Needs some more test cases (e.g. newlines in the end of the file and empty newlines) and possibly some polishment. I will work on these as soon as possible this week. Any comments can be helpful. I will edit this description and title in the final version.~
First complete version available for review.
> Add linebreaks rule

- package.json
> Update npmpub to 4.1.0

- docs/user-guide/rules.md
- lib/rules/function-comma-space-after/README.md
- lib/rules/function-comma-space-after/__tests__/index.js
- lib/rules/function-comma-space-after/index.js
- lib/rules/functionCommaSpaceChecker.js
closes #3547 
ex.
code:
```css
a { color: rgb(0,0,0); }
```
fixed:
```css
a { color: rgb(0, 0, 0); }
```
code:
```css
a { color: rgb(0, 0, 0); }
```
fixed:
```css
a { color: rgb(0,0,0); }
```
> Add autofix to function-comma-space-after

- docs/user-guide/rules.md
- lib/rules/function-parentheses-space-inside/README.md
- lib/rules/function-parentheses-space-inside/__tests__/index.js
- lib/rules/function-parentheses-space-inside/index.js
closes #3561
ex.
code:
```css
a { transform: translate(1, 1); }
```
fixed:
```css
a { transform: translate( 1, 1 ); }
```
* option: `never-multi-line`
code:
```css
a { transform: translate( 1, 1 ); }
```
fixed:
```css
a { transform: translate(1, 1); }
```
> Add autofix to function-parentheses-space-inside

- docs/user-guide/rules.md
- lib/rules/declaration-bang-space-before/README.md
- lib/rules/declaration-bang-space-before/__tests__/index.js
- lib/rules/declaration-bang-space-before/index.js
- lib/rules/declarationBangSpaceChecker.js
closes #3576
ex.
code:
```css
a { color: pink!important; }
```
fixed:
```css
a { color: pink !important; }
```
code:
```css
a { color: pink !important; }
```
fixed:
```css
a { color: pink!important; }
```
> Add autofix to declaration-bang-space-before

- lib/rules/no-descending-specificity/__tests__/index.js
- package.json
> Support for CSS Modules in selector specificity rules (#3604).

- docs/user-guide/rules.md
- lib/rules/function-parentheses-newline-inside/README.md
- lib/rules/function-parentheses-newline-inside/__tests__/index.js
- lib/rules/function-parentheses-newline-inside/index.js
closes #3562
ex.
code:
```css
a { transform: translate(1, 1); }
```
fixed:
```css
a { transform: translate(
1, 1
); }
```
* option: `never-multi-line`
code:
```css
a { transform: translate(
1,
1
); }
```
fixed:
```css
a { transform: translate(1,
1); }
```
> Add autofix to function-parentheses-newline-inside

- docs/user-guide/rules.md
- lib/rules/media-feature-colon-space-after/README.md
- lib/rules/media-feature-colon-space-after/__tests__/index.js
- lib/rules/media-feature-colon-space-after/index.js
- lib/rules/mediaFeatureColonSpaceChecker.js
closes #3568
ex.
code:
```css
@media (max-width:600px) {}
```
fixed:
```css
@media (max-width: 600px) {}
```
code:
```css
@media (max-width: 600px) {}
```
fixed:
```css
@media (max-width:600px) {}
```
> Add autofix to media-feature-colon-space-after

- docs/user-guide/rules.md
- lib/rules/media-feature-colon-space-before/README.md
- lib/rules/media-feature-colon-space-before/__tests__/index.js
- lib/rules/media-feature-colon-space-before/index.js
closes #3569
ex.
code:
```css
@media (max-width:600px) {}
```
fixed:
```css
@media (max-width :600px) {}
```
code:
```css
@media (max-width : 600px) {}
```
fixed:
```css
@media (max-width: 600px) {}
```
> Add autofix to media-feature-colon-space-before

- lib/rules/linebreaks/__tests__/index.js
- lib/rules/linebreaks/__tests__/integration.test.js
- lib/rules/linebreaks/index.js
fixed #3635
Details are listed issue #3635.
> Fix TypeError in linebreaks

- docs/user-guide/rules.md
- lib/rules/selector-attribute-operator-space-after/README.md
- lib/rules/selector-attribute-operator-space-after/__tests__/index.js
- lib/rules/selector-attribute-operator-space-after/index.js
closes #3577
ex.
code:
```css
[target="_blank"] { }
```
fixed:
```css
[target= "_blank"] { }
```
code:
```css
[ target = "_blank" ] { }
```
fixed:
```css
[ target ="_blank" ] { }
```
> Add autofix to selector-attribute-operator-space-after

- docs/user-guide/rules.md
- lib/rules/at-rule-name-space-after/README.md
- lib/rules/at-rule-name-space-after/__tests__/index.js
- lib/rules/at-rule-name-space-after/index.js
- lib/rules/atRuleNameSpaceChecker.js
closes #3581
ex.
code:
```css
@media(width <= 100px) { }
```
fixed:
```css
@media (width <= 100px) { }
```
> Add autofix to at-rule-name-space-after

- lib/rules/media-query-list-comma-newline-after/__tests__/index.js
- lib/rules/media-query-list-comma-newline-after/index.js
- lib/rules/mediaQueryListCommaWhitespaceChecker.js
Fixed #3644 
explanation is on issue #3644.
> Fix false positives for trailing comment in media-query-list-comma-newline-after

- docs/user-guide/rules.md
- lib/rules/media-feature-name-case/README.md
- lib/rules/media-feature-name-case/__tests__/index.js
- lib/rules/media-feature-name-case/index.js
e.g. "Closes #3659 " or "None, as it's a documentation fix."
> feat: add autofix to media-feature-name-case

- lib/rules/number-leading-zero/README.md
> Document mixin parameter note

- docs/user-guide/plugins.md
> Add stylelint-media-use-custom-media to plugin list

- docs/user-guide/plugins.md
It is part of the prettier organization now
> Update docs link to stylelint-prettier

- docs/user-guide/plugins.md
> Add stylelint-8-point-grid plugin

- docs/user-guide/rules.md
- jest-setup.js
- lib/rules/selector-descendant-combinator-no-non-space/README.md
- lib/rules/selector-descendant-combinator-no-non-space/__tests__/index.js
- lib/rules/selector-descendant-combinator-no-non-space/index.js
closes #3564
ex.
code:
```css
.foo  .bar {}
```
fixed:
```css
.foo .bar {}
```
> Add autofix to selector-descendant-combinator-no-non-space

- docs/user-guide/configuration.md
Ref: https://github.com/hudochenkov/stylelint-order/issues/72#issuecomment-433418720
I missed the bits within the configuration docs [first time around](https://github.com/stylelint/stylelint/pull/3591).
> Fix processors docs

- lib/rules/selector-type-case/README.md
- lib/rules/selector-type-case/__tests__/index.js
- lib/rules/selector-type-case/index.js
> Add ignoreTypes option to selector-type-case

- docs/user-guide/rules.md
- lib/rules/value-keyword-case/README.md
- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
> Add autofix to value-keyword-case

- lib/rules/max-empty-lines/__tests__/index.js
- lib/rules/max-empty-lines/index.js
> Fix false positives for final newlines in max-empty-lines

- lib/__tests__/ignore.test.js
None
Seems to be another casting issue.
> Fix test for node 8 on win

- lib/rules/media-feature-parentheses-space-inside/__tests__/index.js
None, as it's will fix typos in the test case.
> Fixed: typo in media-feature-parentheses-space-inside test case

- docs/developer-guide/pull-requests.md
- docs/user-guide/about-rules.md
- docs/user-guide/complementary-tools.md
- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/color-named/__tests__/index.js
- lib/rules/function-comma-space-after/README.md
- lib/rules/function-comma-space-before/README.md
- lib/rules/media-query-list-comma-space-after/README.md
- lib/rules/media-query-list-comma-space-before/README.md
- lib/rules/property-no-unknown/__tests__/index.js
> Fixed typos in docs, comments and tests

- lib/cli.js
> Mark report-needless-disable as boolean

- docs/user-guide/rules.md
- lib/rules/function-comma-newline-after/README.md
- lib/rules/function-comma-newline-after/__tests__/index.js
- lib/rules/function-comma-newline-after/index.js
- lib/rules/function-comma-newline-before/README.md
- lib/rules/function-comma-newline-before/__tests__/index.js
- lib/rules/function-comma-newline-before/index.js
- lib/rules/function-comma-space-after/index.js
- lib/rules/function-comma-space-before/index.js
- lib/rules/functionCommaSpaceFix.js
Closes #3756 Original PR
Closes #3752 Added autofix to function-comma-newline-before
Closes #3594 Add autofix to function-comma-newline-after
> Add autofix to function-comma-newline-*

- docs/user-guide/rules.md
- lib/rules/declaration-block-semicolon-space-after/README.md
- lib/rules/declaration-block-semicolon-space-after/__tests__/index.js
- lib/rules/declaration-block-semicolon-space-after/index.js
> add autofix to declaration-block-semicolon-space-after

- docs/user-guide/complementary-tools.md
> Update url of `stylelint-webpack-plugin`

- lib/rules/shorthand-property-no-redundant-values/__tests__/index.js
- lib/rules/shorthand-property-no-redundant-values/index.js
> Allow negative values for shorthand-property-redundant-values (#3840)

- docs/user-guide/rules.md
> Remove duplicate spaces

- docs/developer-guide/releases.md
It looks like the extra OTP step is going to stick around for a while, so I've updated the release docs to reflect this.
> Update release process docs

- docs/user-guide/node-api.md
- docs/user-guide/postcss-plugin.md
Synchronize the same parts in both `node-api.md` & `postcss-plugin.md`
> Synchronize the same parts in both `node-api.md` & `postcss-plugin.md`

- docs/user-guide/postcss-plugin.md
> Add link for `PostCSS runner`

- docs/developer-guide/issues.md
> Fix link address in `docs/developer-guide/issues.md`

- package.json
- system-tests/005/__snapshots__/005.test.js.snap
- system-tests/005/stylesheet.css
Closes #3898.
Continue changes started in https://github.com/stylelint/stylelint/pull/3892 for the latest PostCSS.
> Fix failing tests. Closes #3898

- docs/user-guide/faq.md
> Use the name of Node.js correctly

- docs/user-guide/css-processors.md
> Uppercase `CSS`

- lib/rules/block-closing-brace-empty-line-before/index.js
> Remove useless code

- docs/user-guide/faq.md
Closes #3938
Adds an FAQ entry.
> Add FAQ entry for transition

- README.md
Closes #3942
Simply bumps "understands latest CSS syntax..." to the top of the feature list. This has the benefit of bringing the "160 rules" and "has plugins" items together.
> Fix emphasis of language support

- docs/user-guide/plugins.md
> Update plugins.md 

- package.json
Ref: https://github.com/stylelint/stylelint/pull/3957#pullrequestreview-206572436
We should use the CI to make sure everything is pretty-printed.
This will fail until https://github.com/stylelint/stylelint/pull/3957 is in and rebased.
> Run prettier:check as pretest

- lib/reference/keywordSets.js
- lib/rules/at-rule-no-unknown/__tests__/index.js
#3977. this is a PR with a currently failing test, as suggested I make in the issue template.
> Added test for at-rule-no-unknown for page margin at-rules

- lib/rules/unit-no-unknown/__tests__/index.js
> test: no-unit-unknown support scientific notation

- docs/developer-guide/rules.md
I think better to avoid hard-coded `master` branch as possible. 😃
> Make internal link URL relative in developer guide doc

- lib/reference/keywordSets.js
- lib/rules/no-descending-specificity/__tests__/index.js
fixes #3929
Unfortunately we don't have repo with list of this pseudo classes so we need maintain this manually
> fix: false positives for vendor specific prefixes in `no-descending-specificity` rule

- package.json
> Update cosmiconfig to v5.2.0

- lib/getPostcssResult.js
- lib/rules/max-empty-lines/index.js
> Remove `styled` and `jsx` syntax options

- lib/utils/getSchemeFromUrl.js
> Replace Node.js legacy API for URL parsing

- docs/developer-guide/releases.md
> Add note about GitHub token

- docs/user-guide/plugins.md
> docs: Add stylelint-plugin-ecss

- docs/user-guide/plugins.md
Ask to add [`stylelint-force-app-name-prefix`](https://github.com/SunHuawei/stylelint-force-app-name-prefix/)
> Add stylelint-force-app-name-prefix

- docs/user-guide/plugins.md
Hi, would you add [stylelint-no-unused-selectors](https://github.com/nodaguti/stylelint-no-unused-selectors) to the stylelint plugins list?
Thank you!
> Add stylelint-no-unused-selectors to the plugins list

- docs/user-guide/plugins.md
Addressed https://github.com/stylelint/stylelint/pull/4089#issuecomment-496042532.
> Sort plugins in alphabetical order

- lib/rules/declaration-colon-space-after/README.md
> Fix declaration-colon-space-after README

- docs/user-guide/cli.md
Closes #4077 
See the issue (I took this as it seems author doesn't reply over a week)
> Fix arguments in CLI guide

- flow-typed/npm/jest_v24.x.x.js
- flow-typed/npm/lodash_v4.x.x.js
- package.json
> chore(package): update flow-bin to version 0.100.0

- package.json
> Update postcss-sass to 0.4.1

- package.json
> Upgrade: upgrade lodash to 4.17.14 to prevent vulnerability (fixes #4150)

- package.json
Hopefully it will fix #4018.
Related PR https://github.com/gucong3000/postcss-jsx/pull/58
> Bump postcss-jsx

- CHANGELOG.md
- docs/developer-guide/pull-requests.md
- docs/developer-guide/releases.md
> Simplify changelog

- lib/rules/no-descending-specificity/README.md
- lib/rules/no-descending-specificity/__tests__/index.js
- lib/rules/no-descending-specificity/index.js
> add ignore selectors-within-list to no-descending-specificity rule

- lib/rules/indentation/__tests__/html.js
- lib/rules/indentation/index.js
> fix indentation rule

- lib/rules/declaration-block-no-shorthand-property-overrides/index.js
- package.json
> chore(package): update eslint to version 6.1.0

- lib/cli.js
> Improve --quiet flag wording in CLI help

- lib/rules/no-descending-specificity/README.md
Closes #2489 
Attempted to use simple English, but may need revision.
The example should cover a lot of the examples I've seen, but most people are using SASS instead of straight CSS.  I *think* this this is easy enough for the difference not to matter, but maybe we need different/additional examples.
> Update about DOM limitations

- jest-setup.js
- lib/rules/no-duplicate-selectors/__tests__/index.js
- lib/rules/selector-max-pseudo-class/__tests__/index.js
> Support several warnings in tests

- README.md
- Included a dedicated contributing guidelines section which would draw better attention than before.
- Minor typographical improvements.
> [Docs]: Minor tweaks

- lib/rules/max-line-length/__tests__/index.js
- lib/rules/max-line-length/index.js
- fix bug with max-line-length `EXCLUDED_PATTERNS`
- fix bug with `skippedSubStrings`
- more tests
Nothing
> fix max-line-length rule

- CHANGELOG.md
- docs/developer-guide/releases.md
- package.json
Closes https://github.com/stylelint/stylelint/issues/3499
I used `np` for a few recent stylelint and stylelint-order releases. Works pretty good.
> Use np for publishing

- lib/reportUnknownRuleNames.js
minor update that allows control amount of suggestions in one variable
nothing
> chore: move max suggestions count to const

- system-tests/fix/fix.test.js
- system-tests/fix/stylesheet-with-bom.css
This is the failing test for #4228. 
I am not sure that it is the right place for this test.
> Add the failing test for the stripping BOM bug

- .dependabot/config.yml
- .travis.yml
https://github.com/stylelint/stylelint/issues/4244
https://dependabot.com/docs/config-file/
> Add Dependabot config

- lib/rules/block-closing-brace-space-before/__tests__/index.js
- lib/rules/block-opening-brace-newline-before/__tests__/index.js
- lib/rules/function-parentheses-newline-inside/__tests__/index.js
- lib/rules/media-query-list-comma-newline-after/__tests__/index.js
- lib/rules/rule-empty-line-before/__tests__/index.js
- lib/rules/selector-attribute-brackets-space-inside/__tests__/index.js
- lib/rules/selector-attribute-operator-space-after/__tests__/index.js
- lib/rules/selector-attribute-operator-space-before/__tests__/index.js
- lib/rules/selector-combinator-space-after/__tests__/index.js
- lib/rules/selector-list-comma-newline-after/__tests__/index.js
- lib/rules/selector-max-combinators/__tests__/index.js
fix for:
* block-closing-brace-space-before
* block-opening-brace-newline-before
* function-parentheses-newline-inside
* media-query-list-comma-newline-after
* rule-empty-line-before
* selector-attribute-brackets-space-inside
* selector-attribute-operator-space-after
* selector-attribute-operator-space-before
* selector-combinator-space-after
* selector-list-comma-newline-after
* selector-max-combinators
nothing
> check warnings count in tests

- .dependabot/config.yml
Fixes https://github.com/stylelint/stylelint/issues/4257
> Add missing configuration to Dependabot config

- SECURITY.md
- package.json
#4221 
need to update emails list
> docs: add SECURITY.md

- lib/testUtils/createRuleTester.js
Supersedes https://github.com/stylelint/stylelint/pull/4265.
> Deprecate createRuleTester API

- .editorconfig
- .eslintignore
- .prettierrc.js
- package.json
https://github.com/stylelint/stylelint/issues/4246
Here is configuration only. I run Prettier with this settings and here the output: https://github.com/stylelint/stylelint/tree/new-code-formatting-output
Compare: https://github.com/stylelint/stylelint/compare/new-formatting-configuration...new-code-formatting-output
> New code formatting settings

- docs/user-guide/plugins.md
n/a
Adding `stylelint-scales` to the list of stylelint plugins.
> Add link to stylelint-scales plugin pack

- README.md
See https://help.github.com/en/articles/configuring-a-workflow
> Switch to GitHub Actions badge and remove Travis CI & AppVeyor badges

- docs/user-guide/cli.md
> add documentation for --output-file cli option. fixes #4319

- .github/workflows/nodejs.yml
Makes CI steps a little bit more granular.
> Separate dependency installation and test

- docs/user-guide/cli.md
Closes https://github.com/stylelint/stylelint/issues/4094.
I renamed title, because it's already obvious that it's a stylelint CLI :) And I decided to write expanded title and abbreviations for less experienced developers.
> Add CLI documentation

- lib/assignDisabledRanges.js
- package-lock.json
- package.json
- types/stylelint/index.d.ts
add types to `assignDisabledRanges`
nothing
> How to check that TS works?
> types: assign disabled ranges

- lib/reportUnknownRuleNames.js
- lib/requireRule.js
add types to requireRule, reportUnknownRuleNames
nothing
Blocked by:  https://github.com/stylelint/stylelint/pull/4354
> types: add types to requireRule, reportUnknownRuleNames

- lib/augmentConfig.js
- lib/createStylelintResult.js
- lib/dynamicRequire.js
- lib/formatters/compactFormatter.js
- lib/formatters/disableOptionsReportStringFormatter.js
- lib/formatters/jsonFormatter.js
- lib/formatters/unixFormatter.js
- lib/formatters/verboseFormatter.js
- lib/invalidScopeDisables.js
- lib/lintSource.js
- lib/needlessDisables.js
- lib/testUtils/createRuleTester.js
- lib/utils/FileCache.js
- lib/utils/checkAgainstRule.js
- lib/utils/checkInvalidCLIOptions.js
- lib/utils/configurationError.js
- lib/utils/filterFilePaths.js
- lib/utils/getFormatterOptionsText.js
- lib/utils/getModulePath.js
- lib/utils/hash.js
- lib/utils/report.js
- lib/utils/ruleMessages.js
- lib/utils/validateOptions.js
- package-lock.json
- package.json
- types/file-entry-cache/index.d.ts
- types/imurmurhash/index.d.ts
- types/stylelint/index.d.ts
related to https://github.com/stylelint/stylelint/issues/4245
Here is mutation of `disabledRange` https://github.com/stylelint/stylelint/blob/master/lib/needlessDisables.js#L52 that I handle in types `DisabledRange & {used?: boolean}`, but I think better avoid mutation here
~~I will add some types for utils too. I just need to check that all tests working correctly~~
> types for lintSource, createStylelintResult, needlessDisables

- jest-setup.js
Simplified Jest configuration. Removed a lot of nesting. Removed hacks, we don't need anymore.
> Improve Jest configuration

- .github/workflows/nodejs.yml
Trying to fix problem with Windows
> fix(CI): separate bash commands in yml syntax instead of &&

- lib/rules/at-rule-semicolon-space-before/README.md
> fix the missing invalidClass

- package.json
Available in `npm@6.13.0`.
More info:
- https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more
- https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md
- https://github.com/npm/cli/blob/latest/docs/content/configuring-npm/package-json.md#funding
> Add funding information to package

- package-lock.json
- package.json
We are using the coverallsapp action.
> Remove the coveralls devDependency.

- package-lock.json
Must be pretty new one since GitHub hasn't issued a fix.
Noticed it locally and thought I'd submit a patch.
> Fix handlebars vulnerability.

- lib/rules/length-zero-no-unit/index.js
- lib/rules/unit-case/index.js
- lib/utils/getUnitFromValueNode.js
These were found with lgtm.com https://lgtm.com/projects/g/stylelint/stylelint/?mode=list
lgtm is owned by GitHub now BTW, you could add it to the repo (just make sure you disable PR comments :))
PS. I kept the patches separate on purpose so maybe don't squash the PR.
> Fix lgtm.com issues

- lib/assignDisabledRanges.js
- lib/augmentConfig.js
- lib/formatters/__tests__/jsonFormatter.test.js
- lib/formatters/jsonFormatter.js
- lib/formatters/stringFormatter.js
- lib/reference/keywordSets.js
- lib/rules/block-closing-brace-newline-before/index.js
- lib/rules/font-weight-notation/index.js
- lib/rules/function-max-empty-lines/index.js
- lib/rules/function-url-quotes/index.js
- lib/rules/indentation/index.js
- lib/rules/max-empty-lines/index.js
- lib/rules/no-duplicate-selectors/index.js
- lib/rules/selector-class-pattern/index.js
- lib/rules/selector-max-empty-lines/index.js
- lib/rules/selector-pseudo-element-colon-notation/index.js
- lib/rules/value-list-max-empty-lines/index.js
- lib/testUtils/mergeTestDescriptions.js
- lib/utils/addEmptyLineAfter.js
- lib/utils/addEmptyLineBefore.js
- lib/utils/blurFunctionArguments.js
- lib/utils/getFormatterOptionsText.js
- lib/utils/isCounterIncrementCustomIdentValue.js
- lib/utils/isCounterResetCustomIdentValue.js
- lib/utils/isStandardSyntaxCombinator.js
- lib/utils/isStandardSyntaxProperty.js
- lib/utils/isStandardSyntaxRule.js
- lib/utils/isStandardSyntaxTypeSelector.js
- lib/utils/validateObjectWithArrayProps.js
* chain
* compact
* endsWith
* includes
* isArray
* isFinite
* isUndefined
* repeat
* startsWith
* sum
* toArray
* values
Refs #4412
> Replace some of lodash functions with native ones.

- lib/formatters/compactFormatter.js
- lib/formatters/unixFormatter.js
> Replace `_.map` with the native solution

- lib/rules/at-rule-no-vendor-prefix/index.js
- lib/rules/block-closing-brace-newline-after/index.js
- lib/rules/block-closing-brace-space-after/index.js
- lib/rules/comment-whitespace-inside/index.js
- lib/rules/font-family-name-quotes/index.js
- lib/rules/function-url-quotes/index.js
- lib/rules/value-no-vendor-prefix/index.js
- lib/utils/getUnitFromValueNode.js
- lib/utils/isStandardSyntaxProperty.js
- lib/utils/isStandardSyntaxTypeSelector.js
- lib/utils/isStandardSyntaxUrl.js
- lib/utils/isStandardSyntaxValue.js
Fixes #4415
I need to go through the codebase one more time.
> Use startsWith/endsWith in more places.

- lib/assignDisabledRanges.js
> Remove `_.clone`

- lib/augmentConfig.js
- lib/formatters/stringFormatter.js
> Replace `_.uniq` with `Set`

- lib/__tests__/plugins.test.js
- lib/__tests__/standalone.test.js
- lib/assignDisabledRanges.js
- lib/rules/block-closing-brace-newline-after/index.js
- lib/rules/block-closing-brace-newline-before/index.js
- lib/rules/block-closing-brace-space-before/index.js
- lib/rules/block-opening-brace-newline-after/index.js
- lib/rules/block-opening-brace-newline-before/index.js
- lib/rules/block-opening-brace-space-after/index.js
- lib/rules/block-opening-brace-space-before/index.js
- lib/rules/comment-empty-line-before/index.js
- lib/rules/declaration-block-semicolon-newline-after/index.js
- lib/rules/declaration-block-semicolon-space-after/index.js
- lib/rules/declaration-block-semicolon-space-before/index.js
- lib/rules/declaration-colon-space-after/index.js
- lib/rules/font-family-name-quotes/index.js
- lib/rules/function-url-no-scheme-relative/index.js
- lib/rules/functionCommaSpaceFix.js
- lib/rules/media-query-list-comma-newline-after/index.js
- lib/rules/media-query-list-comma-space-after/index.js
- lib/rules/media-query-list-comma-space-before/index.js
- lib/rules/no-invalid-double-slash-comments/index.js
- lib/rules/selector-list-comma-newline-after/index.js
- lib/rules/selector-list-comma-newline-before/index.js
- lib/rules/selector-list-comma-space-after/index.js
- lib/rules/value-list-comma-newline-after/index.js
- lib/rules/value-list-comma-space-after/index.js
- lib/rules/value-list-comma-space-before/index.js
- lib/utils/isStandardSyntaxSelector.js
Requires #4417 to be merged first and then I'll rebase.
>  Use String.startsWith in more places. 

- lib/augmentConfig.js
- system-tests/systemTestUtils.js
> Replace `_.omit` with object spread

- lib/createStylelint.js
- lib/getConfigForFile.js
- lib/lintSource.js
- lib/postcssPlugin.js
- lib/rules/indentation/index.js
- lib/rules/max-nesting-depth/index.js
- lib/rules/time-min-milliseconds/index.js
- lib/utils/whitespaceChecker.js
- system-tests/systemTestUtils.js
> Use default params when possible.

- lib/postcssPlugin.js
I'm not sure why this suppression, but it's the only place there's a prettier suppression.
If this is wrong, just close the PR :)
> Remove prettier ignore

- lib/formatters/disableOptionsReportStringFormatter.js
- lib/formatters/stringFormatter.js
- lib/rules/indentation/index.js
- lib/rules/no-missing-end-of-source-newline/index.js
- lib/utils/isCustomMediaQuery.js
- lib/utils/isCustomProperty.js
- lib/utils/isCustomPropertySet.js
- lib/utils/isCustomSelector.js
- lib/utils/isStandardSyntaxRule.js
- lib/utils/isVariable.js
> Use String.startsWith/endsWith in more places

- lib/__tests__/fixtures/processor-fenced-blocks.js
- lib/reference/keywordSets.js
- lib/rules/indentation/index.js
- lib/rules/shorthand-property-no-redundant-values/index.js
- lib/testUtils/mergeTestDescriptions.js
- lib/utils/ruleMessages.js
- scripts/benchmark-rule.js
Split from #4453 
Lint needs fixing, any help welcome!
> Use arg rest/spread when possible.

- lib/utils/blurFunctionArguments.js
Unfortunately, I'm not aware of an ESLint rule to enforce this. Only https://github.com/sindresorhus/eslint-plugin-unicorn
> Use String.includes

- docs/user-guide/complementary-tools.md
> Docs: Add up-to-date link for VS Code extension

- README.md
Found a link to the old repo, figured it should be updated
> Update reference to vscode extension

- lib/assignDisabledRanges.js
- lib/cli.js
- lib/createStylelintResult.js
- lib/formatters/disableOptionsReportStringFormatter.js
- lib/formatters/stringFormatter.js
- lib/formatters/verboseFormatter.js
- lib/reportUnknownRuleNames.js
- lib/rules/color-named/generateColorFuncs.js
- lib/rules/declaration-bang-space-before/index.js
- lib/rules/declaration-colon-newline-after/index.js
- lib/rules/declarationColonSpaceChecker.js
- lib/rules/function-whitespace-after/index.js
- lib/rules/indentation/index.js
- lib/rules/length-zero-no-unit/index.js
- lib/rules/max-empty-lines/index.js
- lib/rules/max-line-length/__tests__/index.js
- lib/rules/number-leading-zero/index.js
- lib/rules/selector-max-specificity/index.js
- lib/standalone.js
- lib/utils/__tests__/ruleMessages.test.js
- lib/utils/beforeBlockString.js
- lib/utils/validateOptions.js
- package.json
This should probably be enforced with an ESLint rule, so until this happens we may don't want to land it.
> Use template literals

- .dependabot/config.yml
Any existent PRs will need to be recreated I think with `@dependabot recreate`
> Dependabot: always increase versions

- lib/utils/FileCache.js
Better check the [non-whitespace diff](https://github.com/stylelint/stylelint/pull/4459/files?utf8=%E2%9C%93&diff=unified&w=1) for this. Also please confirm this is safe, I didn't test it a lot :)
> FileCache.js: switch to a Class

- .dependabot/config.yml
None.
All pull request labels are [prefixed with "PR:"](https://github.com/stylelint/stylelint/labels).
> Fix dependabot label

- .github/workflows/nodejs.yml
Non-whitespace diff: <https://github.com/stylelint/stylelint/pull/4529/files?w=1>
> Tweak CI config

- docs/user-guide/usage/cli.md
- lib/__tests__/cli.test.js
- lib/cli.js
- system-tests/cli/__snapshots__/cli.test.js.snap
- system-tests/cli/cli.test.js
- system-tests/cli/config.json
> Add --stdin flag

- lib/cli.js
- system-tests/cli/cli.test.js
> Fix open handles test issue

- lib/__tests__/fixtures/extension-sensitive.ts
- package.json
- types/autoprefixer/index.d.ts
- types/postcss/extensions.d.ts
- types/postcss/index.d.ts
- types/style-search/index.d.ts
- types/stylelint/index.d.ts
- types/write-file-atomic/index.d.ts
> Fix TypeScript files with Prettier too

- lib/rules/value-keyword-case/README.md
https://github.com/stylelint/stylelint/issues/4622#issuecomment-597091089, but it's a documentation fix.
> Fix option name in rule README

- package-lock.json
- package.json
Updating postcss-sass to 0.4.4
[Security](https://github.com/AleshaOleg/postcss-sass/pull/143) and dependencies update.
> Update postcss-sass to 0.4.4

- lib/rules/indentation/__tests__/javascript.js
- lib/rules/indentation/index.js
> Fix false positives for nested template literals in indentation

- lib/rules/rule-empty-line-before/README.md
> Fix example in rule-empty-line-before docs

- lib/rules/value-keyword-case/__tests__/index.js
- lib/rules/value-keyword-case/index.js
> Fix false positives regression for mixed-case ignoreProperties in value-keyword-case

- docs/developer-guide/plugins.md
Relates to https://github.com/stylelint/stylelint/pull/4758
> Document Jest preset for testing plugins

- docs/user-guide/rules/list.md
- lib/rules/color-function-notation/README.md
- lib/rules/color-function-notation/__tests__/index.js
- lib/rules/color-function-notation/index.js
- lib/rules/index.js
Closes #4718
I thought I'd give this one a whirl as it's been a while since I wrote a rule.
The `"modern"` option is autofixable, and I've addressed the edge-cases I can think of.
There may be a neater way to write the fixing code that doesn't rely on a count.
> Add color-function-notation

- lib/__tests__/fixtures/disableOptions/file-config/.stylelintrc.json
- lib/__tests__/fixtures/disableOptions/file-config/disabled-ranges-1.css
- lib/__tests__/invalidScopeDisables.test.js
- lib/invalidScopeDisables.js
- lib/lintSource.js
- lib/standalone.js
- types/stylelint/index.d.ts
> Fix false positives for all scope disables in `--report-invalid-scope-disables`

- lib/cli.js
Closes #4862
No, it's self-explanatory
> Add missing newline to CLI error output

- package-lock.json
- package.json
Closes https://github.com/stylelint/stylelint/issues/4906
> Add support for *.cjs config files

- docs/user-guide/integrations/editor.md
> Add coc-stylelint

- lib/utils/__tests__/isLessVariable.test.js
> Fix `isLessVariable.test.js` that use callbacks

- lib/utils/__tests__/isStandardSyntaxRule.test.js
- lib/utils/isStandardSyntaxRule.js
This simply rewriting causes some test failures, but I'm not sure which they are due to the incorrectness of the tests or the implementation... 🤷 
Could you let me know if anyone knows the cause?
> Fix `isStandardSyntaxRule.test.js` that use callbacks

- lib/utils/isLessVariable.js
- lib/utils/isStandardSyntaxAtRule.js
- lib/utils/isStandardSyntaxDeclaration.js
- lib/utils/isStandardSyntaxRule.js
- package-lock.json
- package.json
- types/global.d.ts
This is a part of #4496 and improves type-checking about LESS. (fixing `// @ts-ignore`)
See <https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/postcss-less>
> Add `@types/postcss-less`

- docs/user-guide/usage/cli.md
Closes #4925 
Nothing that comes to mind.
> Add example to cli usage guide

- lib/utils/__tests__/isStandardSyntaxCombinator.test.js
> Fix `isStandardSyntaxCombinator.test.js` that use callbacks

- lib/utils/__tests__/isSharedLineComment.test.js
> Fix `isSharedLineComment.test.js` that uses callbacks

- docs/user-guide/configure.md
It's a documentation fix. Add #4906.
> refactor documentation config

- lib/formatters/stringFormatter.js
- lib/rules/comment-whitespace-inside/index.js
- lib/rules/declaration-bang-space-before/index.js
- lib/rules/max-line-length/index.js
- lib/rules/no-eol-whitespace/index.js
Part of #5013.
I wanted to take a crack at doing some of the work for this PR, but I also wanted to make sure that I'm taking the right approach! Within some of these commits, I try a few different approaches - I just want to make sure that I'm doing things properly/fitting conventions.
* some of the are trivial renamings (ex `root` -> `rootNode`)
* some of them are logical renmaings (ex `output` -> `accum` for a reducer)
* some times, I move the function out of scope, if there's no dependence/reliance and the function seems bite-sized enough 
Any thoughts here? More than happy to change my strategy on this. I can gradually work through the rest of the cases over several PRs (not …
> Resolves some ESLint no-shadow violations

- docs/developer-guide/processors.md
> docs: fix grammar

- docs/user-guide/integrations/editor.md
This is to prevent people like myself missing the right option and wasting time creating spurious issues like this one: https://github.com/stylelint/stylelint/issues/5274
> Mention alternative integration with Emacs

- lib/utils/isNonNegativeInteger.js
We will no longer need the polyfill on the next major release (v14).
Closes #5219
> Refactor to remove `Number.isInteger` polyfill

- lib/assignDisabledRanges.js
- lib/rules/comment-whitespace-inside/index.js
- lib/rules/no-descending-specificity/index.js
- lib/rules/unit-no-unknown/index.js
- lib/utils/addEmptyLineAfter.js
> Remove `_.last`

- lib/assignDisabledRanges.js
- lib/normalizeRuleSettings.js
- lib/rules/declaration-property-value-allowed-list/index.js
- lib/rules/declaration-property-value-disallowed-list/index.js
> Remove `_.isEmpty`

- README.md
https://github.com/stylelint/stylelint.io/pull/193
Minimal changes that we can rebase into `v14`.
> Prepare README for Docusaurus 2

- lib/createPartialStylelintResult.js
- lib/needlessDisables.js
> Refactor to remove `_.remove`

- lib/normalizeRuleSettings.js
> Refactor to remove `_.isNil`

- lib/formatters/compactFormatter.js
- lib/formatters/stringFormatter.js
- lib/formatters/unixFormatter.js
> Refactor to remove `_.flatMap`

- package.json
https://github.com/stylelint/stylelint.io/pull/193
It seems we may need to explicitly add CHANGELOG to files for it to appear when installing from GitHub...
> Add CHANGELOG to files

- lib/normalizeRuleSettings.js
- lib/utils/validateObjectWithArrayProps.js
- lib/utils/validateOptions.js
> Refactor to remove `_.isPlainObject`

- lib/createStylelint.js
- lib/rules/max-empty-lines/index.js
- lib/standalone.js
Ref #4412.
`_.partial` does not modify the `this` binding, but `fn.bind` does. I verified that none of the functions touched in this PR use `this`, so the behavior difference is not an issue.
> Refactor to remove `_.partial`

- lib/formatters/verboseFormatter.js
- lib/rules/named-grid-areas-no-invalid/utils/findNotContiguousOrRectangular.js
> Refactor to remove `_.flatten`

- lib/__tests__/standalone-fix.test.js
- lib/testUtils/uniqueId.js
- system-tests/systemTestUtils.js
> Refactor to remove `_.uniqueId`

- lib/formatters/stringFormatter.js
> Refactor to remove `_.uniqBy`

- lib/__tests__/disableRanges.test.js
- lib/assignDisabledRanges.js
- lib/createPartialStylelintResult.js
- lib/createStylelintResult.js
- lib/descriptionlessDisables.js
- lib/getPostcssResult.js
- lib/index.js
- lib/needlessDisables.js
- lib/postcssPlugin.js
- lib/utils/addEmptyLineAfter.js
- lib/utils/eachDeclarationBlock.js
- lib/utils/findAtRuleContext.js
- lib/utils/isAfterStandardPropertyDeclaration.js
- lib/utils/isBlocklessAtRuleAfterBlocklessAtRule.js
- lib/utils/isBlocklessAtRuleAfterSameNameBlocklessAtRule.js
- lib/utils/isFirstNodeOfRoot.js
- lib/utils/isKeyframeRule.js
- lib/utils/isSharedLineComment.js
- lib/utils/isStandardSyntaxDeclaration.js
- lib/utils/nodeContextLookup.js
- lib/utils/typeGuards.js
- types/postcss/index.d.ts
- types/stylelint/index.d.ts
> Fix types issues after PostCSS update

- lib/formatters/stringFormatter.js
> Refactor to remove `_.sortBy`

- lib/rules/declaration-block-no-redundant-longhand-properties/index.js
> Refactor to remove `_.transform`

- lib/rules/declaration-property-unit-allowed-list/index.js
- lib/rules/declaration-property-unit-disallowed-list/index.js
- lib/rules/declaration-property-value-allowed-list/index.js
- lib/rules/declaration-property-value-disallowed-list/index.js
- lib/rules/media-feature-name-value-allowed-list/index.js
> Refactor to remove `_.find`

- lib/rules/named-grid-areas-no-invalid/index.js
> Refactor to remove `_.compact`

- lib/rules/no-duplicate-selectors/index.js
> Refactor to remove `_.union`

- lib/utils/checkInvalidCLIOptions.js
> Refactor to remove `_.kebabCase`

- lib/utils/whitespaceChecker.js
A part of #4496
Similar to #5363, this PR improves the use of types in the `whitespaceChecker()` utility function.
> Refactor to improve types in `lib/utils/whitespaceChecker.js`

- lib/__tests__/disableRanges.test.js
- lib/needlessDisables.js
> Refactor to remove `_.cloneDeep`

- lib/formatters/__tests__/stringFormatter.test.js
- lib/formatters/stringFormatter.js
- package-lock.json
> Refactor to remove `_.escapeRegExp`

- lib/utils/arrayEqual.js
- lib/utils/declarationValueIndex.js
- lib/utils/getAtRuleParams.js
- lib/utils/getDeclarationValue.js
- lib/utils/getRuleSelector.js
- lib/utils/isStandardSyntaxRule.js
- lib/utils/setAtRuleParams.js
- lib/utils/setDeclarationValue.js
- lib/utils/validateTypes.js
A part of #4496
- Avoid `any` as possible
- Use `unknown`
- Use `@ts-expect-error`
(see <https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments>)
> Fix some type problems

- .github/workflows/code-scanning.yml
- .github/workflows/linting.yml
- .github/workflows/testing.yml
Related to #5205
I think we always need to check HEAD on the [`v14`](https://github.com/stylelint/stylelint/tree/v14) branch.
Also, I leave TODO comments to remove the `v14` branches when releasing v14.
> Run CI on v14 branch

- lib/lintPostcssResult.js
- lib/rules/alpha-value-notation/index.js
- lib/rules/at-rule-allowed-list/index.js
- lib/rules/at-rule-disallowed-list/index.js
- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/at-rule-name-case/index.js
- lib/rules/at-rule-name-newline-after/index.js
- lib/rules/at-rule-name-space-after/index.js
- lib/rules/at-rule-no-unknown/index.js
- lib/rules/at-rule-no-vendor-prefix/index.js
- lib/rules/at-rule-property-required-list/index.js
- lib/rules/at-rule-semicolon-newline-after/index.js
- lib/rules/at-rule-semicolon-space-before/index.js
- lib/rules/atRuleNameSpaceChecker.js
- lib/utils/addEmptyLineBefore.js
- lib/utils/getPreviousNonSharedLineCommentNode.js
- lib/utils/hasEmptyLine.js
- lib/utils/removeEmptyLinesBefore.js
- lib/utils/report.js
- lib/utils/ruleMessages.js
- lib/utils/validateOptions.js
- lib/utils/whitespaceChecker.js
- types/stylelint/index.d.ts
This change removes `// @ts-nocheck` comments in `at-rule-*` rules.
> Improve types for `at-rule-*` rules

- lib/utils/beforeBlockString.js
None.
- Remove extra type annotations.
- Simplify the logic.
> Refactor `lib/utils/beforeBlockString.js`

- package-lock.json
- package.json
None.
We've just released <https://github.com/stylelint/remark-preset/releases/tag/3.0.0>.
This PR aims to confirm the new major version works fine on our main repository.
> Bump @stylelint/remark-preset from 2.0.0 to 3.0.0

- lib/augmentConfig.js
- lib/prepareReturnValue.js
- lib/rules/declaration-block-no-redundant-longhand-properties/index.js
- lib/rules/font-family-name-quotes/index.js
- lib/rules/function-comma-newline-after/index.js
- lib/rules/function-comma-newline-before/index.js
- lib/rules/function-comma-space-after/index.js
- lib/rules/function-comma-space-before/index.js
- lib/rules/length-zero-no-unit/index.js
- lib/utils/nodeContextLookup.js
Some changes are subjective and since the rule isn't enforced, I can revert them :)
> Refactor to use arrow return

- lib/rules/at-rule-no-unknown/README.md
- lib/rules/max-nesting-depth/README.md
- lib/rules/no-invalid-position-at-import-rule/README.md
> Use dashed indents in examples of custom at-rule constructs

- lib/cli.js
- lib/formatters/stringFormatter.js
- lib/formatters/verboseFormatter.js
- lib/utils/__tests__/checkInvalidCLIOptions.test.js
- lib/utils/checkInvalidCLIOptions.js
- package-lock.json
- package.json
- scripts/benchmark-rule.js
The copy of https://github.com/stylelint/stylelint/pull/5559 but on top for `v14` branch
> Refactor to replace chalk with nanocolors

- docs/migration-guide/to-14.md
No, it's self-explanatory. :-)
> fix preferred typo

- package-lock.json
- package.json
- scripts/benchmark-rule.mjs
Stems from the conversation in and closes #5773.
This PR's original goal was to remove `got` as a dependency (and use something more lightweight, in this case `node-fetch`) but the scope has increased a bit. Here's a chronological step-by-step of what I had to do:
1. Removed `got` in favour of `node-fetch`. This involves slightly changing the promise structure.
2. In realizing that the latest version of `node-fetch` is ESM-only, and that the benchmark script is still in CJS, upgrades it to ESM. While this is mostly routine,
* I rename the file extension to `.mjs`. This doesn't seem breaking, since nobody consumes this script.
* `picocolors` is still a CJS module, so I implement …
> Refactor benchmark script to ESM and node-fetch

- docs/user-guide/integrations/editor.md
> docs: Update information about JetBrains IDEs.

- lib/rules/font-family-name-quotes/README.md
> Remove duplicated code sample in `font-family-name-quotes` doc

- lib/reference/keywordSets.js
- lib/rules/no-descending-specificity/__tests__/index.js
- lib/rules/no-descending-specificity/index.js
Which issue, if any, is this issue related to?
Closes [#5032](https://github.com/stylelint/stylelint/issues/5032)
This looks like a simple fix ?
I tried to run all the test and it looks OK.
Do you see any issue that could come from this ?
> Fix false positive for ::-moz-focus-inner in no-descending-specificity

- docs/developer-guide/syntaxes.md
> Document use of overrides in custom syntax configs

- docs/user-guide/rules/about.md
Ref: https://github.com/stylelint/stylelint/issues/4065#issuecomment-1016368681
> Document *-notation rules

- .vscode/settings.json
- lib/rules/unit-allowed-list/README.md
- lib/rules/unit-allowed-list/__tests__/index.js
- lib/rules/unit-allowed-list/index.js
> Add ignoreFunctions: [] to unit-allowed-list

- lib/assignDisabledRanges.js
- lib/formatters/__tests__/verboseFormatter.test.js
- lib/formatters/verboseFormatter.js
- lib/lintPostcssResult.js
- lib/lintSource.js
- lib/utils/report.js
- lib/utils/validateOptions.js
- types/stylelint/index.d.ts
Ref:
- #5835 
- #5845
This pull request supports plugin rule links on a terminal, only if a plugin rule has an URL within its metadata.
See also https://github.com/stylelint/stylelint/pull/5835#discussion_r785246463
> Support plugin rule links on terminal

- lib/assignDisabledRanges.js
- lib/cli.js
- lib/createPartialStylelintResult.js
- lib/formatters/index.js
- lib/rules/index.js
- lib/rules/shorthand-property-no-redundant-values/index.js
- lib/rules/string-no-newline/index.js
- lib/rules/string-quotes/index.js
- lib/rules/time-min-milliseconds/index.js
- lib/rules/unicode-bom/index.js
- lib/rules/unit-allowed-list/index.js
- lib/rules/unit-case/index.js
- lib/rules/unit-disallowed-list/index.js
- lib/rules/unit-no-unknown/index.js
- lib/rules/value-keyword-case/index.js
- lib/rules/value-list-comma-newline-after/index.js
- lib/rules/value-list-comma-newline-before/index.js
- lib/rules/value-list-comma-space-after/index.js
- lib/rules/value-list-comma-space-before/index.js
- lib/rules/value-list-max-empty-lines/index.js
- lib/rules/value-no-vendor-prefix/index.js
- lib/rules/valueListCommaWhitespaceChecker.js
- lib/utils/declarationValueIndex.js
- lib/utils/nodeContextLookup.js
- lib/utils/validateObjectWithArrayProps.js
- lib/utils/validateTypes.js
- types/postcss-media-query-parser/index.d.ts
Closes #4496
This change:
- fixes all `// @ts-nocheck` comments
- fixes all `// TODO TYPES` comments (some are replaced with `@ts-expect-error`)
> Refactor to fix all type problems

- docs/user-guide/usage/cli.md
- docs/user-guide/usage/node-api.md
- docs/user-guide/usage/options.md
> Document allowEmptyInput option for the node js API

- docs/user-guide/get-started.md
- docs/user-guide/usage/options.md
None, as it's a documentation fix. Although, it touches on a couple of issues we've had recently.
Notes inline. Main change is using sub headings to break "linting everything else" into 3 parts:
- linting with shared configs
- directly using custom syntaxes
- linting more than one thing
> Revise getting started guide

- lib/rules/no-descending-specificity/README.md
> Document nesting in no-descending-specificity

- lib/rules/length-zero-no-unit/__tests__/index.js
Closes #4754
This issue seems to have been resolved.
Added a test to confirm normal operation.
> Add test case for autofix of values containing comments in length-zero-no-unit

- docs/developer-guide/rules.md
Refs: https://github.com/stylelint/stylelint/pull/5920 https://github.com/stylelint/stylelint/pull/5925
It's been a while since we touched these, and they needed cleaning up. This pull request consolidates the conventions into the tests section and updates the README example section to reference them.
> Document test and README example conventions

- lib/rules/at-rule-allowed-list/__tests__/index.js
- lib/testUtils/mergeTestDescriptions.js
- lib/testUtils/replaceBackslashes.js
- lib/testUtils/uniqueId.js
- tsconfig.json
- types/stylelint/test.d.ts
Ref: #5937
This pull request aims to improve our testing experience a bit with better types.
- Add types to the `lib/testUtils/*.js` files.
- Definte the `testRule` type of `jest-preset-stylelint`
> Refactor to improve testing with better types

- README.md
changed typo from perffered to preffered
> fixed preffered typo

- lib/reference/keywordSets.js
see https://github.com/stylelint/stylelint/pull/5970#pullrequestreview-913559407
> Fix false positives for SVG elements in selector-type-case

- .github/workflows/testing.yml
Ref: #5877
The workaround seems no longer necessary.
> Remove workaround for npm installation on CI

- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/maintainer-guide/pull-requests.md
> Fix `master` branch to `main` in docs

- lib/rules/unit-allowed-list/README.md
> Unify wording in `unit-allowed-list` doc

- lib/reference/keywordSets.js
- lib/rules/at-rule-no-unknown/__tests__/index.js
> Fix `at-rule-no-unknown` false positives for `@layer`

- lib/rules/no-invalid-position-at-import-rule/README.md
- lib/rules/no-invalid-position-at-import-rule/__tests__/index.js
- lib/rules/no-invalid-position-at-import-rule/index.js
> Fix `no-invalid-position-at-import-rule` false positives for `@layer`

- docs/maintainer-guide/releases.md
> Fix typo in stylelint team name

- lib/rules/no-descending-specificity/README.md
> Fix missing heading in `no-descending-specificity` doc

- docs/maintainer-guide/releases.md
This pull request just fixes small mistakes in the guide.
> Update maintainer guide for releasing

- lib/rules/value-no-vendor-prefix/__tests__/index.js
- lib/rules/value-no-vendor-prefix/index.js
Part of #5694.
No, this one was pretty simple 😊
> Fix end positions for `value-no-vendor-prefix`

- lib/rules/selector-not-notation/__tests__/index.js
- lib/rules/selector-not-notation/index.js
> Fix end positions for `selector-not-notation`

- docs/migration-guide/to-14.md
> Fix doc minor grammar mistakes

- lib/rules/no-unknown-animations/__tests__/index.js
- lib/rules/no-unknown-animations/index.js
> Fix `no-unknown-animations` end positions

- package-lock.json
- package.json
> chore(deps): upgrade postcss to ^8.4.16

- lib/rules/selector-nested-pattern/__tests__/index.js
- lib/rules/selector-nested-pattern/index.js
> Fix `selector-nested-pattern` end positions

- .github/workflows/releasing.yml
Ref: #6274
To keep consistency with other workflows:
> Update releasing workflow name

- lib/rules/at-rule-empty-line-before/index.js
- lib/rules/declaration-block-trailing-semicolon/index.js
- lib/rules/no-extra-semicolons/index.js
- lib/rules/no-invalid-position-at-import-rule/index.js
- lib/rules/number-leading-zero/index.js
- lib/rules/number-max-precision/index.js
- lib/rules/number-no-trailing-zeros/index.js
- lib/rules/selector-pseudo-class-no-unknown/index.js
- lib/rules/string-quotes/index.js
- lib/rules/unit-no-unknown/index.js
Closes #6291
No, it's self-explanatory
> Refactor to use `isAtRule` util

- lib/rules/function-name-case/README.md
- Use dashed idents in examples
- Remove incorrect example
Part of #5523
- Use dashed idents in examples
- Remove incorrect example
> Improve `function-name-case` document

- lib/rules/no-duplicate-selectors/README.md
- lib/rules/selector-class-pattern/README.md
- lib/rules/selector-id-pattern/README.md
- lib/rules/selector-max-attribute/README.md
- lib/rules/selector-max-id/README.md
- lib/rules/selector-max-specificity/README.md
- lib/rules/selector-max-type/README.md
- lib/rules/selector-pseudo-element-allowed-list/README.md
- lib/rules/selector-pseudo-element-disallowed-list/README.md
Part of #5523 (I believe the last one)
> Improve rule docs using dashed idents

- docs/maintainer-guide/pull-requests.md
- docs/maintainer-guide/releases.md
Closes #6253 
I've also removed the `pr: needs *` labels as we weren't using them as they're redundant; GitHub already surfaces information like "Changes requested", "Review required" and "Approved".
> Document pull request and release changes

- docs/user-guide/usage/options.md
> Document configuration object options subset

- .github/dependabot.yml
Ref:
- #5453
- #6439
- #6409
We have started preparing v15.0.0 (see #6409).
> Set `target-branch: v15` for Dependabot

- lib/rules/media-feature-name-unit-allowed-list/index.js
- lib/utils/parseMediaQuery.js
- package-lock.json
- package.json
This adds the utility for media query parsing.
Fixes : https://github.com/stylelint/stylelint/issues/6559
I've also update the packages relevant to media query parsing.
This includes some bug fixes and a simpler API for common actions.
> Refactor to add parse media query list util

- CHANGELOG.md
- docs/migration-guide/to-15.md
- docs/user-guide/customize.md
- docs/user-guide/get-started.md
- lib/rules/block-opening-brace-newline-after/README.md
- lib/rules/block-opening-brace-newline-before/README.md
Ref https://github.com/stylelint/stylelint.io/pull/303
Fixes warnings and makes tweaks for a better experience on the website.
> Prepare docs for website

- .github/dependabot.yml
- .github/workflows/code-scanning.yml
- .github/workflows/releasing.yml
- .github/workflows/testing.yml
Ref: #6618
The `v15` branch was deleted via PR #6618.
```console
$ git grep v15 || echo 'no match'
no match
```
> Refactor to remove needless code about `v15` branch

- .github/workflows/releasing.yml
> Remove 15.0.0 from release title

- docs/user-guide/customize.md
> Document `reportDisables` in the customising guide

- .github/workflows/testing.yml
- package.json
Ref: https://github.com/stylelint/.github/pull/18
- Split a test job for coverage from matrix
- Use npm 9 (latest)
> Improve test workflow on CI

- lib/rules/declaration-property-value-no-unknown/README.md
> Document `declaration-property-value-no-unknown` appropriate languages

- docs/maintainer-guide/releases.md
> Fix period (.) typos in release guide

- .changeset/thin-candles-cross.md
- lib/__tests__/applyOverrides.test.js
- lib/augmentConfig.js
> Fix `overrides.extends` order when including same rules

- .changeset/cyan-kangaroos-hope.md
- lib/rules/declaration-property-value-no-unknown/__tests__/index.js
- lib/rules/declaration-property-value-no-unknown/index.js
> Fix `declaration-property-value-no-unknown` false positives for descriptors

- docs/user-guide/customize.md
The scoped package will be deprecated in favour of this unscoped one.
> Fix stylelint-scales package link in docs

- docs/maintainer-guide/releases.md
Ref: https://github.com/stylelint/stylelint-demo/pull/352
The new demo automatically installs the latest versions of Stylelint and the standard config.
> Document demo release

- docs/user-guide/get-started.md
Ref: https://github.com/stylelint/stylelint/issues/6698
> Document init tool in getting started guide

- docs/migration-guide/to-15.md
> Fix typo in `docs/migration-guide/to-15.md`

- .changeset/afraid-emus-admire.md
- docs/user-guide/cli.md
- docs/user-guide/options.md
- lib/__tests__/__snapshots__/cli.test.js.snap
- lib/__tests__/cli.test.js
- lib/__tests__/fixtures/quiet-deprecation-warnings/config.json
- lib/__tests__/fixtures/quiet-deprecation-warnings/style.css
- lib/__tests__/standalone-quiet-deprecation-warnings.test.js
- lib/augmentConfig.js
- lib/cli.js
- lib/lintPostcssResult.js
- lib/standalone.js
- types/stylelint/index.d.ts
Closes #6677.
This is my first time adding a CLI option, so I'm uncertain if I'm missing anything "obvious" that's normally done when doing so!
> Add `--quiet-deprecation-warnings` flag

- .changeset/poor-queens-battle.md
- lib/__tests__/standalone-deprecations.test.js
- lib/lintPostcssResult.js
> Fix deprecation warnings for disabled rules

- lib/rules/declaration-property-unit-allowed-list/index.js
- lib/rules/declaration-property-unit-disallowed-list/index.js
- lib/rules/unit-allowed-list/index.js
- lib/rules/unit-disallowed-list/index.js
- lib/utils/validateOptions.js
Resolve remaining code quality feedback from : https://github.com/stylelint/stylelint/pull/6751
I am unsure if a minor change like this needs to be mentioned in the changelog.
As far as I can tell these changes won't have any noticeable effect for users, even when they do improve the code quality a bit.
> Fix remaining feedback from CodeQL code quality rules

- .changeset/swift-falcons-battle.md
- lib/rules/declaration-block-no-duplicate-custom-properties/README.md
- lib/rules/declaration-block-no-duplicate-custom-properties/__tests__/index.js
- lib/rules/declaration-block-no-duplicate-custom-properties/index.js
> Add `ignoreProperties: []` to `declaration-block-no-duplicate-custom-properties`

- .changeset/many-toes-smell.md
- lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
- lib/rules/declaration-block-no-duplicate-properties/index.js
Closes https://github.com/stylelint/stylelint/issues/6796
> Fix `declaration-block-no-duplicate-properties` false positives with option `consecutive-duplicates-with-different-syntaxes`

- .changeset/six-bats-love.md
- lib/formatters/__tests__/githubFormatter.test.js
- lib/formatters/githubFormatter.js
- close #6821 
To prevent unexpected string concatenation
> Fix `github` formatter for missing final newline

- lib/rules/media-feature-name-no-unknown/__tests__/index.js
- lib/rules/media-feature-name-no-unknown/index.js
See : https://github.com/stylelint/stylelint/issues/6848
> Refactor to migrate `media-feature-name-no-unknown` to `findMediaFeatureNames` utility

- lib/utils/getAtRuleParams.js
See : https://github.com/stylelint/stylelint/pull/6850#discussion_r1198846441
> Refactor `getAtRuleParams` utility

- lib/rules/media-feature-name-allowed-list/__tests__/index.js
- lib/rules/media-feature-name-allowed-list/index.js
see : https://github.com/stylelint/stylelint/issues/6848
No, it's self-explanatory
> Refactor to migrate `media-feature-name-allowed-list` to `findMediaFeatureNames` utility

- lib/__tests__/applyOverrides.test.mjs
- lib/__tests__/defaultSeverity.test.mjs
- lib/__tests__/descriptionlessDisables.test.mjs
- lib/__tests__/disableRanges-integration.test.mjs
- lib/__tests__/disableRanges.test.mjs
- lib/__tests__/extends.test.mjs
- lib/__tests__/formatters.test.mjs
- lib/__tests__/getConfigForFile.test.mjs
- lib/__tests__/writeOutputFile.test.mjs
- lib/testUtils/readJSONFile.mjs
- lib/testUtils/safeChdir.js
Ref:
- #5291
- #6940
Some tests keep `__dirname` to minimize diffs.
> Rewrite some tests (`lib/__tests__/*`) to ESM

- docs/maintainer-guide/issues.md
Ref: https://github.com/stylelint/stylelint/issues/6869#issuecomment-1606071380
> Document assignees for issues in maintainer guide 

- lib/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js
Closes https://github.com/stylelint/stylelint/issues/6986
This change isn't user facing, omitting a changelog entry
> Fix `function-linear-gradient-no-nonstandard-direction` test cases

- scripts/benchmark-rule.mjs
Ref #6869
Includes more modern syntax like custom properties:
https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.css
> Refactor to use latest Bootstrap for benchmark

- .changeset/bright-suits-reflect.md
- lib/rules/function-name-case/index.js
Before:
Mean: 148.49660561538457 ms
Deviation: 14.86421482337638 ms
After:
Mean: 116.04665178571427 ms
Deviation: 17.283854733889434 ms
> Fix function-name-case performance

- .changeset/tender-apes-count.md
- lib/rules/function-url-quotes/index.js
Before:
Mean: 139.03539278571427 ms
Deviation: 19.870834517620747 ms
After:
Mean: 96.23857735714284 ms
Deviation: 12.178951548182841 ms
> Fix function-url-quotes performance

- .changeset/fifty-hotels-admire.md
None.
We've consistently followed the conventions of:
- Fixed & Security = Patch
- Added & Deprecated = Minor
- Removed & Changed = Major
This pull request removes the inconsistent changelog entry, which isn't user-facing and is "patch" for "Removed".
> Revert removed changelog entry

- docs/user-guide/rules.md
See https://github.com/stylelint/stylelint/issues/7038
> Fix rules documentation for `media-query-no-invalid`

- package-lock.json
- tsconfig.json
Ref #5291
~~Note that this PR cherry-picks #7058 to pass CI. Neet to merge #7058 first.~~ Done.
> Exclude `*.test.mjs` from TypeScript check

- package-lock.json
Closes https://github.com/stylelint/stylelint/issues/7077
No changeset, this isn't user facing.
> Update `package-lock.json` to lock file version `3`

- .changeset/popular-fishes-behave.md
- package-lock.json
- package.json
> Fix `property-no-unknown` false positives for scroll-driven animations

- docs/maintainer-guide/releases.md
Follow-up to #7102
"Prepare release" is now incorrect. The PR title includes a version number.
> Improve Pull Request title example in maintainer guide

- docs/migration-guide/to-16.md
This PR aligns the v16 migration with our style from the previous ones by:
- listing the changes by impactfulness
- leading with details of the change
- then explaining how to migrate
> Refine v16 migration guide

- lib/__tests__/descriptionlessDisables.test.mjs
- lib/__tests__/extends.test.mjs
- lib/__tests__/ignore.test.mjs
- lib/__tests__/ignoreDisables.test.mjs
- lib/__tests__/invalidScopeDisables.test.mjs
- lib/__tests__/message.test.mjs
- lib/__tests__/needlessDisables.test.mjs
- lib/__tests__/normalizeRuleSettings-integration.test.mjs
- lib/__tests__/overrides.test.mjs
- lib/__tests__/reportDisables.test.mjs
- lib/__tests__/reportUnknownRuleNames.test.mjs
- lib/__tests__/standalone-cache.test.mjs
- lib/__tests__/standalone-deprecations.test.mjs
- lib/__tests__/standalone-fix.test.mjs
- lib/__tests__/standalone-formatter.test.mjs
- lib/__tests__/standalone-glob-parent-test/folder/another-folder/standalone-glob-parent-wildcard.test.mjs
- lib/__tests__/standalone-glob-parent-test/folder/standalone-glob-parent.test.mjs
- lib/__tests__/standalone-globs.test.mjs
- lib/__tests__/standalone-maxWarnings.test.mjs
- lib/__tests__/standalone-parseErrors.test.mjs
- lib/__tests__/standalone-quiet-deprecation-warnings.test.mjs
- lib/__tests__/standalone-quiet.test.mjs
- lib/__tests__/standalone-syntax.test.mjs
- lib/__tests__/standalone.test.mjs
- lib/__tests__/stylelintignore-test/stylelintignore.test.mjs
- lib/cli.mjs
- lib/index.js
- lib/standalone.cjs
- lib/standalone.mjs
> Migrate `lib/standalone` to ESM

- .changeset/thin-guests-smell.md
> Remove unneeded changelog entry

- lib/rules/color-hex-length/index.js
- lib/rules/color-no-hex/index.js
- lib/utils/__tests__/isIgnoredFunction.test.mjs
- lib/utils/isIgnoredFunction.js
Added `isIgnoredFunction` utility function and replaced duplicated isIgnoredFunction functions throughout codebase.
Also added a unit test for the function. 
Closes #7249
> Refactor to add `isIgnoredFunction` utility

- lib/rules/unit-no-unknown/index.js
> Refactor `lib/rules/unit-no-unknown/index.js`

- lib/rules/selector-not-notation/index.js
> Refactor `lib/rules/selector-not-notation/index.js`

- lib/rules/color-named/__tests__/colordUtils.test.mjs
- lib/rules/color-named/colordUtils.cjs
- lib/rules/color-named/colordUtils.mjs
- lib/rules/color-named/index.js
> Refactor `color-named/colordUtils.js` to ESM

- .github/workflows/testing.yml
Closes #7302
For the `current` syntax, see: https://github.com/actions/setup-node#supported-version-syntax
> Test on Node.js 21 and coverage on 20

- package.json
> Fix incorrect `main` field in `package.json`

- README.md
> Add link to migration guide v16 in README.md [skip ci]

- docs/user-guide/configure.md
Ref #7322
The [Prettier document](https://prettier.io/docs/en/configuration) was referenced.
> Improve config file description in "Configuring" user guide

- docs/migration-guide/to-16.md
Ref https://github.com/stylelint/jest-preset-stylelint/pull/87#discussion_r1403790643
> Document Jest light runner in migration guide

- docs/developer-guide/plugins.md
> Document node:test testRule

- .changeset/new-bananas-sell.md
- lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
- lib/utils/hasScssInterpolation.cjs
- lib/utils/hasScssInterpolation.mjs
> Fix `declaration-property-value-no-unknown` and other false positives for multiline SCSS interpolation

- docs/migration-guide/to-16.md
> Document testing options in more detail in the v16 migration guide

- docs/user-guide/rules.md
> Sort rules alphabetically in `docs/user-guide/rules.md`

- docs/developer-guide/plugins.md
- docs/user-guide/configure.md
Closes #7072
See https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
> Document benefits from TypeScript annotation

- .changeset/nervous-seas-retire.md
- lib/reference/atKeywords.cjs
- lib/reference/atKeywords.mjs
- lib/rules/at-rule-no-unknown/__tests__/index.mjs
- lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
> Fix `at-rule-no-unknown` false positives for `@starting-style`

- docs/maintainer-guide/releases.md
See https://github.com/stylelint/stylelint.io/pull/385
Just a documentation update. Let's try this new workflow in the next release.
> Document simplified website releasing in maintainer guide

- .changeset/silver-actors-jam.md
- lib/rules/selector-max-class/__tests__/index.mjs
- lib/rules/selector-max-class/index.cjs
- lib/rules/selector-max-class/index.mjs
See : https://github.com/stylelint/stylelint/issues/6234
Follows the same patterns as : https://github.com/stylelint/stylelint/pull/7518
> Fix `selector-max-class` end positions

- .changeset/strong-spies-dance.md
- lib/rules/function-no-unknown/__tests__/index.mjs
- lib/rules/function-no-unknown/index.cjs
- lib/rules/function-no-unknown/index.mjs
Closes #7566
https://chromestatus.com/feature/5124922471874560
> Fix `function-no-unknown` false positives for `anchor` and `anchor-size`

- CHANGELOG.md
- lib/rules/function-no-unknown/index.cjs
- lib/rules/function-no-unknown/index.mjs
#7623
#7640
niksy/css-functions-list#8
At one point we will have to vendor the package if the non-existing functions are not removed.
For now it's just a minor bother.
https://github.com/stylelint/stylelint/blob/main/lib/rules/function-no-unknown/__tests__/index.mjs#L25
https://github.com/stylelint/stylelint/blob/main/lib/rules/function-no-unknown/__tests__/index.mjs#L31
https://github.com/stylelint/stylelint/blob/main/lib/rules/function-no-unknown/__tests__/index.mjs#L34
> Refactor `function-no-unknown` to remove exceptions

- .github/dependabot.yml
https://github.com/stylelint/stylelint/pull/7708#discussion_r1613715827
> Change `dependabot.yml` to only ignore eslint major updates and add postcss group

- .changeset/poor-cups-flash.md
- lib/reference/selectors.cjs
- lib/reference/selectors.mjs
- lib/rules/selector-type-no-unknown/__tests__/index.mjs
> Fix `selector-type-no-unknown` false positive for `model`

- docs/user-guide/rules.md
- lib/rules/__tests__/index.test.mjs
N/A
https://github.com/stylelint/stylelint/commit/aa9be6f181613c695e80ddf97b0518b1ac674198#diff-b49ac02da5ff95ce9ef8c2de7f0b2ae24f8bed1f6789825bec7d7d133905a01fL36
> Fix typo in rules.md

- .changeset/mighty-chefs-rhyme.md
- lib/__tests__/standalone-fix.test.mjs
- lib/rules/keyframe-selector-notation/index.cjs
- lib/rules/keyframe-selector-notation/index.mjs
- lib/rules/no-duplicate-selectors/__tests__/index.mjs
- lib/utils/report.cjs
- lib/utils/report.mjs
#2643
I wanted to start with a rule that uses `word`.
After that PR most rule refactors will be quite straight forward.
> `keyframe-selector-notation` fix callback refactor

- .changeset/angry-days-shave.md
- .changeset/grumpy-shoes-cross.md
- lib/rules/function-name-case/__tests__/index.mjs
- lib/rules/function-name-case/index.cjs
- lib/rules/function-name-case/index.mjs
> Fix `function-name-case` end positions and refactor to use `fix` callback instead of `context.fix`

- .changeset/real-insects-flash.md
- lib/rules/selector-type-case/__tests__/index.mjs
- lib/rules/selector-type-case/index.cjs
- lib/rules/selector-type-case/index.mjs
> Fix `selector-type-case` end positions and refactor to use `fix` callback instead of `context.fix`

- .changeset/moody-terms-change.md
- lib/__tests__/standalone-fix.test.mjs
- lib/rules/selector-not-notation/__tests__/index.mjs
- lib/rules/selector-not-notation/index.cjs
- lib/rules/selector-not-notation/index.mjs
> Fix `selector-not-notation` end positions and refactor to use `fix` callback instead of `context.fix`

- .changeset/cold-trainers-pump.md
- lib/rules/value-keyword-case/index.cjs
- lib/rules/value-keyword-case/index.mjs
> Fix `value-keyword-case` end positions and refactor to use `fix` callback instead of `context.fix`

- lib/__tests__/standalone-fix.test.mjs
- lib/utils/report.cjs
- lib/utils/report.mjs
https://github.com/stylelint/stylelint/pull/7762#discussion_r1642584242
N/A
> Simplify `report` util even further

- .changeset/eighty-insects-love.md
- lib/rules/media-feature-name-no-vendor-prefix/__tests__/index.mjs
- lib/rules/media-feature-name-no-vendor-prefix/index.cjs
- lib/rules/media-feature-name-no-vendor-prefix/index.mjs
#2643
[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBbGUCWBDABACgFoB3GAIwGsMAXAlDAOwNgDcMwYCAHDADxgBsCAJyxUMEeDgAMAShxZ6UfMTKUaKLDyYxW7LrwHDR4yQCY5wAL4gANCABmGfjAByWNAhAwe7zs4B0YADOQbbgEPSOAOaewAA69Dg4cSBCAK7OQSmS8YlJySBomFgE9jCiaUIc9O7VEATMMIoQQlxVjjzZOFTpMAlJlgnWdpCRGFEAYi0aVJ4AVkERYbCcoYi5SSlBVACezvwMVF0p-KIw2yk2-QXbewKHBKPRBNsKUFhCUMcgp1TnRyAhiBLEA) of the bug
> Fix `media-feature-name-no-vendor-prefix` autofix and refactor to use `fix` callback instead of `context.fix`

- .changeset/yellow-feet-provide.md
- lib/rules/no-invalid-double-slash-comments/__tests__/index.mjs
- lib/rules/no-invalid-double-slash-comments/index.cjs
- lib/rules/no-invalid-double-slash-comments/index.mjs
> Fix `no-invalid-double-slash-comments` reported ranges

- lib/rules/property-no-vendor-prefix/index.cjs
- lib/rules/property-no-vendor-prefix/index.mjs
- lib/rules/selector-no-vendor-prefix/index.cjs
- lib/rules/selector-no-vendor-prefix/index.mjs
- lib/rules/value-no-vendor-prefix/index.cjs
- lib/rules/value-no-vendor-prefix/index.mjs
> Refactor `*-no-vendor-prefix` to use `fix` callback instead of `context.fix`

- lib/utils/report.cjs
- lib/utils/report.mjs
None
See review comments.
These are some minor and superficial nitpicks.
I don't feel strongly about these, but I think they improve readability.
> Refactor `report()` variable names

- types/stylelint/index.d.ts
Ref https://github.com/stylelint/stylelint/issues/7784#issuecomment-2183252282
We cannot publish this feature because we're still discussing the signature etc.
> Make `Problem.fix()` internal

- lib/rules/lightness-notation/index.cjs
- lib/rules/lightness-notation/index.mjs
> Refactor `lightness-notation` to use `fix` callback instead of `context.fix`

- lib/rules/hue-degree-notation/index.cjs
- lib/rules/hue-degree-notation/index.mjs
> Refactor `hue-degree-notation` to use `fix` callback instead of `context.fix`

- lib/rules/color-function-notation/index.cjs
- lib/rules/color-function-notation/index.mjs
> Refactor `color-function-notation` to use `fix` callback instead of `context.fix`

- lib/rules/selector-pseudo-element-colon-notation/index.cjs
- lib/rules/selector-pseudo-element-colon-notation/index.mjs
> Refactor `selector-pseudo-element-colon-notation` to use `fix` callback instead of `context.fix`

- lib/rules/alpha-value-notation/index.cjs
- lib/rules/alpha-value-notation/index.mjs
> Refactor `alpha-value-notation` to use `fix` callback instead of `context.fix`

- lib/rules/import-notation/index.cjs
- lib/rules/import-notation/index.mjs
> Refactor `import-notation` to use `fix` callback instead of `context.fix`

- lib/rules/color-hex-length/index.cjs
- lib/rules/color-hex-length/index.mjs
> Refactor `color-hex-length` to use `fix` callback instead of `context.fix`

- lib/rules/media-feature-range-notation/index.cjs
- lib/rules/media-feature-range-notation/index.mjs
> Refactor `media-feature-range-notation` to use `fix` callback instead of `context.fix`

- lib/rules/length-zero-no-unit/index.cjs
- lib/rules/length-zero-no-unit/index.mjs
- lib/utils/__tests__/checkAgainstRule.test.mjs
> Refactor `length-zero-no-unit` to use `fix` callback instead of `context.fix`

- lib/rules/shorthand-property-no-redundant-values/index.cjs
- lib/rules/shorthand-property-no-redundant-values/index.mjs
> Refactor `shorthand-property-no-redundant-values` to use `fix` callback instead of `context.fix`

- lib/reference/functions.cjs
- lib/reference/functions.mjs
- lib/rules/font-weight-notation/index.cjs
- lib/rules/font-weight-notation/index.mjs
- lib/utils/__tests__/checkAgainstRule.test.mjs
> Refactor `font-weight-notation` to use `fix` callback instead of `context.fix`

- .changeset/tiny-actors-switch.md
- lib/rules/string-no-newline/__tests__/index.mjs
- lib/rules/string-no-newline/index.cjs
- lib/rules/string-no-newline/index.mjs
- package-lock.json
- package.json
Closes https://github.com/stylelint/stylelint/issues/4057
> Fix `string-no-newline` false positives for escaped multi-line

- lib/rules/function-calc-no-unspaced-operator/index.cjs
- lib/rules/function-calc-no-unspaced-operator/index.mjs
- package-lock.json
- package.json
None
- ensure that all tokenizer and parser packages are up to date
- use the new `isWhiteSpaceOrCommentNode` helper
> Update `css-parser-algorithms` and `media-query-list-parser` packages

- .changeset/nine-ants-film.md
- lib/utils/__tests__/checkAgainstRule.test.mjs
- lib/utils/__tests__/fixtures/custom-rule-async.mjs
- lib/utils/checkAgainstRule.cjs
- lib/utils/checkAgainstRule.mjs
> Fix `stylelint.utils.checkAgainstRule()` for Promise-based rules

- docs/user-guide/cli.md
> Fix document to correct stdout to stderr since v16

- lib/utils/__tests__/report.test.mjs
- lib/utils/report.cjs
- lib/utils/report.mjs
- types/stylelint/index.d.ts
https://github.com/stylelint/stylelint/pull/7819#issuecomment-2210064821
#7860
> Refactor to remove `Range` from the return type of the `fix` callback

- lib/createPartialStylelintResult.cjs
- lib/createPartialStylelintResult.mjs
- lib/formatters/calcSeverityCounts.cjs
- lib/formatters/calcSeverityCounts.mjs
- lib/formatters/preprocessWarnings.cjs
- lib/formatters/preprocessWarnings.mjs
- lib/lintPostcssResult.cjs
- lib/lintPostcssResult.mjs
- lib/prepareReturnValue.cjs
- lib/prepareReturnValue.mjs
- lib/reportDisables.cjs
- lib/reportDisables.mjs
- lib/reportUnknownRuleNames.cjs
- lib/reportUnknownRuleNames.mjs
- lib/utils/reportCommentProblem.cjs
- lib/utils/reportCommentProblem.mjs
- lib/validateDisableSettings.cjs
- lib/validateDisableSettings.mjs
> Refactor to use severity constants

- docs/developer-guide/plugins.md
- docs/developer-guide/rules.md
- docs/user-guide/options.md
> Update rules.md, options.md and plugins.md

- .changeset/loud-humans-join.md
- lib/formatters/__tests__/githubFormatter.test.mjs
- lib/formatters/githubFormatter.cjs
- lib/formatters/githubFormatter.mjs
Closes #7447
https://github.com/stylelint/stylelint/issues/7447#issuecomment-2269174803
> Add deprecation notice to `github` formatter's output

- .changeset/soft-snails-do.md
- lib/rules/keyframe-block-no-duplicate-selectors/__tests__/index.mjs
- lib/rules/keyframe-block-no-duplicate-selectors/index.cjs
- lib/rules/keyframe-block-no-duplicate-selectors/index.mjs
See: https://github.com/stylelint/stylelint/issues/7904
> Fix `keyframe-block-no-duplicate-selectors` reported ranges

- .changeset/fast-cameras-walk.md
- lib/rules/no-duplicate-selectors/__tests__/index.mjs
- lib/rules/no-duplicate-selectors/index.cjs
- lib/rules/no-duplicate-selectors/index.mjs
Fixes: https://github.com/stylelint/stylelint/issues/6075
See: https://github.com/stylelint/stylelint/issues/7904
> Fix `no-duplicate-selectors` reported ranges

- .changeset/tall-pumpkins-do.md
- docs/developer-guide/rules.md
- lib/__tests__/standalone-quiet-deprecation-warnings.test.mjs
- lib/createPartialStylelintResult.cjs
- lib/createPartialStylelintResult.mjs
- lib/lintPostcssResult.cjs
- lib/lintPostcssResult.mjs
- lib/utils/emitDeprecationWarning.cjs
- lib/utils/emitDeprecationWarning.mjs
> Honour `--no-deprecation` flag for deprecated rules

- .changeset/tame-jars-travel.md
- lib/rules/color-function-notation/__tests__/index.mjs
- lib/rules/color-function-notation/index.cjs
- lib/rules/color-function-notation/index.mjs
> `color-function-notation`: add more criteria to the function that determines the notation

- docs/about/semantic-versioning.md
Addresses <https://github.com/stylelint/stylelint/pull/7949#discussion_r1727448021> by @Mouvedia 
No.
> Update semantic-versioning.md to remove duplication about deprecation

- .changeset/khaki-singers-drive.md
- lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
- lib/rules/declaration-property-value-no-unknown/index.cjs
- lib/rules/declaration-property-value-no-unknown/index.mjs
Closes #7952 
Details are mentioned in Issue link.
Resources:
https://csstree.github.io/docs/validator.html
https://caniuse.com/mdn-css_properties_text-wrap
https://caniuse.com/mdn-css_properties_text-wrap-mode
> Fix `declaration-property-value-no-unknown` false negatives for `text-wrap` and `text-wrap-mode`

- .changeset/fuzzy-cheetahs-smash.md
- lib/reference/atKeywords.cjs
- lib/reference/atKeywords.mjs
- lib/rules/at-rule-no-unknown/__tests__/index.mjs
Closes #7965
I hope I didn't forget anything 🌸
> Fix `at-rule-no-unknown` false positives for `@position-try`

- .changeset/tame-steaks-invite.md
- lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
- lib/rules/declaration-property-value-no-unknown/index.cjs
- lib/rules/declaration-property-value-no-unknown/index.mjs
Closes https://github.com/stylelint/stylelint/issues/8002
> Fix `declaration-property-value-no-unknown` reported ranges and message

- docs/maintainer-guide/issues.md
To remove duplication of labels and issue types.
> Document issue types for maintainers

- .changeset/honest-coats-roll.md
- lib/rules/selector-attribute-name-disallowed-list/__tests__/index.mjs
- lib/rules/selector-attribute-name-disallowed-list/index.cjs
- lib/rules/selector-attribute-name-disallowed-list/index.mjs
> Fix `selector-attribute-name-disallowed-list` reported ranges

- .changeset/shiny-rivers-rescue.md
- lib/rules/selector-attribute-operator-allowed-list/__tests__/index.mjs
- lib/rules/selector-attribute-operator-allowed-list/index.cjs
- lib/rules/selector-attribute-operator-allowed-list/index.mjs
> Fix `selector-attribute-operator-allowed-list` reported ranges

- .changeset/witty-snakes-guess.md
- lib/rules/selector-attribute-operator-disallowed-list/__tests__/index.mjs
- lib/rules/selector-attribute-operator-disallowed-list/index.cjs
- lib/rules/selector-attribute-operator-disallowed-list/index.mjs
> Fix `selector-attribute-operator-disallowed-list` reported ranges

- lib/rules/selector-attribute-quotes/__tests__/index.mjs
> Add test case for `selector-attribute-quotes` reported ranges

- .changeset/fast-waves-camp.md
- lib/rules/selector-class-pattern/__tests__/index.mjs
- lib/rules/selector-class-pattern/index.cjs
- lib/rules/selector-class-pattern/index.mjs
> Fix `selector-class-pattern` reported ranges

- .changeset/green-pianos-mate.md
- lib/rules/selector-id-pattern/__tests__/index.mjs
- lib/rules/selector-id-pattern/index.cjs
- lib/rules/selector-id-pattern/index.mjs
> Fix `selector-id-pattern` reported ranges

- .changeset/empty-feet-protect.md
- lib/rules/selector-combinator-allowed-list/__tests__/index.mjs
- lib/rules/selector-combinator-allowed-list/index.cjs
- lib/rules/selector-combinator-allowed-list/index.mjs
> Fix `selector-combinator-allowed-list` reported ranges

- .changeset/clever-buckets-shop.md
- lib/rules/selector-max-id/__tests__/index.mjs
- lib/rules/selector-max-id/index.cjs
- lib/rules/selector-max-id/index.mjs
> Fix `selector-max-id` reported ranges

- .changeset/angry-fans-walk.md
- lib/rules/selector-combinator-disallowed-list/__tests__/index.mjs
- lib/rules/selector-combinator-disallowed-list/index.cjs
- lib/rules/selector-combinator-disallowed-list/index.mjs
> Fix `selector-combinator-disallowed-list` reported ranges

- .changeset/chilled-oranges-buy.md
- lib/rules/selector-max-attribute/__tests__/index.mjs
- lib/rules/selector-max-attribute/index.cjs
- lib/rules/selector-max-attribute/index.mjs
> Fix `selector-max-attribute` reported ranges

- .changeset/curvy-pandas-brush.md
- lib/rules/selector-max-class/__tests__/index.mjs
- lib/rules/selector-max-class/index.cjs
- lib/rules/selector-max-class/index.mjs
> Fix `selector-max-class` reported ranges

- .changeset/yellow-eels-camp.md
- lib/rules/selector-max-combinators/__tests__/index.mjs
- lib/rules/selector-max-combinators/index.cjs
- lib/rules/selector-max-combinators/index.mjs
> Fix `selector-max-combinators` reported ranges

- .changeset/proud-mugs-share.md
- lib/rules/selector-max-pseudo-class/__tests__/index.mjs
- lib/rules/selector-max-pseudo-class/index.cjs
- lib/rules/selector-max-pseudo-class/index.mjs
> Fix `selector-max-pseudo-class` reported ranges

- .changeset/gold-balloons-promise.md
- lib/rules/selector-max-specificity/__tests__/index.mjs
- lib/rules/selector-max-specificity/index.cjs
- lib/rules/selector-max-specificity/index.mjs
> Fix `selector-max-specificity` reported ranges

- .changeset/stupid-needles-wave.md
- lib/rules/selector-max-universal/__tests__/index.mjs
- lib/rules/selector-max-universal/index.cjs
- lib/rules/selector-max-universal/index.mjs
> Fix `selector-max-universal` reported ranges

- .changeset/sour-deers-pretend.md
- lib/rules/selector-pseudo-class-disallowed-list/__tests__/index.mjs
- lib/rules/selector-pseudo-class-disallowed-list/index.cjs
- lib/rules/selector-pseudo-class-disallowed-list/index.mjs
> Fix `selector-pseudo-class-disallowed-list` reported ranges

- .changeset/yellow-spoons-relate.md
- lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs
- lib/rules/selector-pseudo-class-no-unknown/index.cjs
- lib/rules/selector-pseudo-class-no-unknown/index.mjs
> Fix `selector-pseudo-class-no-unknown` reported ranges

- .changeset/sixty-olives-remain.md
- lib/rules/selector-pseudo-class-allowed-list/__tests__/index.mjs
- lib/rules/selector-pseudo-class-allowed-list/index.cjs
- lib/rules/selector-pseudo-class-allowed-list/index.mjs
> Fix `selector-pseudo-class-allowed-list` reported ranges

- lib/rules/selector-type-case/__tests__/index.mjs
> Add test case for `selector-type-case` reported ranges

- .changeset/sixty-kings-join.md
- lib/rules/selector-disallowed-list/__tests__/index.mjs
- lib/rules/selector-disallowed-list/index.cjs
- lib/rules/selector-disallowed-list/index.mjs
> Fix `selector-disallowed-list` reported ranges

- .changeset/small-dragons-help.md
- lib/rules/selector-pseudo-element-allowed-list/__tests__/index.mjs
- lib/rules/selector-pseudo-element-allowed-list/index.cjs
- lib/rules/selector-pseudo-element-allowed-list/index.mjs
> Fix `selector-pseudo-element-allowed-list` reported ranges

- .changeset/lovely-phones-beam.md
- lib/rules/selector-pseudo-element-disallowed-list/__tests__/index.mjs
- lib/rules/selector-pseudo-element-disallowed-list/index.cjs
- lib/rules/selector-pseudo-element-disallowed-list/index.mjs
> Fix `selector-pseudo-element-disallowed-list` reported ranges

- .changeset/calm-suns-prove.md
- lib/rules/selector-pseudo-element-no-unknown/__tests__/index.mjs
- lib/rules/selector-pseudo-element-no-unknown/index.cjs
- lib/rules/selector-pseudo-element-no-unknown/index.mjs
> Fix `selector-pseudo-element-no-unknown` reported ranges

- .changeset/shiny-mangos-learn.md
- lib/rules/selector-no-vendor-prefix/__tests__/index.mjs
- lib/rules/selector-no-vendor-prefix/index.cjs
- lib/rules/selector-no-vendor-prefix/index.mjs
> Fix `selector-no-vendor-prefix` reported ranges

- .changeset/honest-ghosts-watch.md
- lib/rules/selector-type-no-unknown/__tests__/index.mjs
- lib/rules/selector-type-no-unknown/index.cjs
- lib/rules/selector-type-no-unknown/index.mjs
> Fix `selector-type-no-unknown` reported ranges

- docs/user-guide/ignore-code.md
> Document `scope` in the context of configuration comments

- docs/user-guide/ignore-code.md
> Document new `.gitignore` examples

- lib/rules/selector-class-pattern/__tests__/index.mjs
- lib/rules/selector-class-pattern/index.cjs
- lib/rules/selector-class-pattern/index.mjs
- lib/rules/selector-disallowed-list/__tests__/index.mjs
- lib/rules/selector-disallowed-list/index.cjs
- lib/rules/selector-disallowed-list/index.mjs
- lib/rules/selector-max-type/index.cjs
- lib/rules/selector-max-type/index.mjs
- lib/rules/selector-pseudo-class-allowed-list/index.cjs
- lib/rules/selector-pseudo-class-allowed-list/index.mjs
- lib/rules/selector-pseudo-class-disallowed-list/index.cjs
- lib/rules/selector-pseudo-class-disallowed-list/index.mjs
- lib/rules/selector-pseudo-element-allowed-list/index.cjs
- lib/rules/selector-pseudo-element-allowed-list/index.mjs
- lib/rules/selector-pseudo-element-colon-notation/index.cjs
- lib/rules/selector-pseudo-element-colon-notation/index.mjs
- lib/rules/selector-pseudo-element-disallowed-list/index.cjs
- lib/rules/selector-pseudo-element-disallowed-list/index.mjs
- lib/rules/selector-pseudo-element-no-unknown/index.cjs
- lib/rules/selector-pseudo-element-no-unknown/index.mjs
- lib/rules/selector-type-case/index.cjs
- lib/rules/selector-type-case/index.mjs
- lib/rules/selector-type-no-unknown/index.cjs
- lib/rules/selector-type-no-unknown/index.mjs
See: https://github.com/stylelint/stylelint/issues/7904
After all the fixes for the reported ranges of selector problems there were still a few opportunities to cleanup existing code, slightly improve test coverage, and a few very minor improvements.
I bundled these because they were so minor but I also don't mind splitting this up.
I don't think a changeset is needed because most changes aren't user facing and those that are, already have a relevant changeset.
> Refactor to cleanup after selector report range fixes

- .changeset/little-wasps-ring.md
- docs/user-guide/configure.md
- lib/__tests__/overrides.test.mjs
- types/stylelint/index.d.ts
> Add `name` configuration property under `overrides`

- lib/utils/report.cjs
- lib/utils/report.mjs
None, this PR addresses feedback from https://github.com/stylelint/stylelint/pull/8074#discussion_r1817684975.
> Refactor `report` to call `rangeBy` only when needed

- .changeset/dirty-rings-search.md
- lib/reference/mediaFeatures.cjs
- lib/reference/mediaFeatures.mjs
- lib/rules/media-feature-name-value-no-unknown/__tests__/index.mjs
#8112
[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBbGUCWBDABACkwGcAHAGywE8BaFaGeHYjMAFwFcAnGKjAOyqatOMAJQ5gAXxAAaEADMMpGADksaBCBgAPNWRgA6MIUIzwEXgoDmG4AB1eOHLZAc2Sws4Z2HjpyDSYWFRyMFjsXFS8atwAblikbNy8EFRsvADWyQDuvJ44LK4w9o4S9lKykBYYlgBiEBwoYRoAVoTmprDEJojejs6ELBRKpHwsec7kLDADzmUgEkA)
> Fix `media-feature-name-value-no-unknown` false positives for `display-mode: picture-in-picture`

- .changeset/fair-shirts-love.md
- lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs
- lib/rules/custom-property-no-missing-var-function/index.cjs
- lib/rules/custom-property-no-missing-var-function/index.mjs
N/A
https://developer.mozilla.org/en-US/docs/Web/CSS/container-name#browser_compatibility
> Fix `custom-property-no-missing-var-function` false positives for `container-name`

- .changeset/cyan-cows-approve.md
- .changeset/silly-brooms-beg.md
- lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs
- lib/rules/custom-property-no-missing-var-function/index.cjs
- lib/rules/custom-property-no-missing-var-function/index.mjs
- lib/rules/function-no-unknown/__tests__/index.mjs
- lib/rules/function-no-unknown/index.cjs
- lib/rules/function-no-unknown/index.mjs
#5742
https://www.w3.org/TR/css-gcpm-3/#running-syntax
https://www.princexml.com/doc/styling/#position
https://www.antenna.co.jp/AHF/help/en/ahf-css6.html#css3-functions
> Fix `function-no-unknown` and `custom-property-no-missing-var-function` false positives for `running()`

- .changeset/mean-ads-cry.md
- lib/rules/selector-pseudo-class-allowed-list/__tests__/index.mjs
- lib/rules/selector-pseudo-class-allowed-list/index.cjs
- lib/rules/selector-pseudo-class-allowed-list/index.mjs
Closes #1871
I am having a hard time getting consistent results out of the _benchmark-rule_ script.
i.e. walkRules/WalkAtRules vs walk/switch
> Add `selector-pseudo-class-allowed-list` `@page` support

- docs/about/vision.md
- docs/developer-guide/rules.md
> Document the shift in the criteria for inclusion of rules

- .changeset/witty-weeks-complain.md
- lib/rules/selector-type-no-unknown/__tests__/index.mjs
- lib/rules/selector-type-no-unknown/index.cjs
- lib/rules/selector-type-no-unknown/index.mjs
> Fix `selector-type-no-unknown` false positives for idents in functional pseudo-classes

- lib/rules/declaration-property-value-no-unknown/README.md
> Document `declaration-property-value-no-unknown` syntax reference

- docs/developer-guide/rules.md
Ref https://github.com/stylelint/stylelint/pull/8214#issuecomment-2559977052
> Document updating types when adding an option

- docs/user-guide/configure.md
> Document using type import in CommonJS config example

- README.md
- docs/about/governance.md
> Document governance of our organisation roles

- docs/maintainer-guide/issues.md
- docs/maintainer-guide/pull-requests.md
A small tidy-up of the maintainer guide to clarify a couple of things around titles and commit messages.
> Document to clarify maintainer guide conventions

- docs/developer-guide/rules.md
- lib/rules/declaration-property-value-no-unknown/README.md
> Document prior art in our rule READMEs

- lib/rules/function-no-unknown/index.cjs
- lib/rules/function-no-unknown/index.mjs
See https://github.com/stylelint/stylelint/issues/8243
> Refactor `function-no-unknown` to have unambiguous position arguments

- lib/rules/block-no-empty/index.cjs
- lib/rules/block-no-empty/index.mjs
See https://github.com/stylelint/stylelint/issues/8243
> Refactor `block-no-empty` to have unambiguous position arguments

- lib/rules/declaration-property-value-no-unknown/README.md
- lib/rules/media-feature-name-value-no-unknown/README.md
Ref: https://github.com/stylelint/stylelint/issues/8133
The rules have been used for a while, and we're readying to use them in our config.
> Document rules becoming stable

- .changeset/short-lobsters-end.md
- lib/rules/media-feature-name-unit-allowed-list/README.md
- lib/rules/media-feature-name-unit-allowed-list/index.cjs
- lib/rules/media-feature-name-unit-allowed-list/index.mjs
- lib/rules/selector-pseudo-element-colon-notation/README.md
- lib/rules/selector-pseudo-element-colon-notation/index.cjs
- lib/rules/selector-pseudo-element-colon-notation/index.mjs
> Add `messageArgs` to `selector-pseudo-element-colon-notation` and `media-feature-name-unit-allowed-list`

- docs/user-guide/rules.md
> Document rules alphabetically

- docs/user-guide/customize.md
Part of our efforts to make it easier for first-time users to get up and running with common use cases.
> Document alphabetical order config

- lib/rules/at-rule-descriptor-no-unknown/README.md
- lib/rules/at-rule-descriptor-value-no-unknown/README.md
- lib/rules/at-rule-prelude-no-invalid/README.md
- lib/rules/color-no-invalid-hex/README.md
- lib/rules/declaration-property-value-no-unknown/README.md
- lib/rules/function-linear-gradient-no-nonstandard-direction/README.md
- lib/rules/function-no-unknown/README.md
- lib/rules/media-feature-name-value-no-unknown/README.md
- lib/rules/media-query-no-invalid/README.md
- lib/rules/string-no-newline/README.md
- lib/rules/unit-no-unknown/README.md
Although we handle this for most users via our shared config, we should document the overlaps for people who craft their own config.
> Document overlapping rules

- docs/user-guide/get-started.md
> Document correct config in SCSS getting started guide

- .changeset/soft-kiwis-admire.md
- lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
- lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
- lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs
> Fix `declaration-block-no-redundant-longhand-properties` false positives for properties with `!important`

- .github/workflows/pkg.pr.new-comment.yml
- .github/workflows/pkg.pr.new.yml
- package-lock.json
- package.json
- scripts/pkg.pr.new-custom-comment.mjs
Closes #8352
To enable pkg.pr.new we need to install the <https://github.com/apps/pkg-pr-new>.
If consensus was reached in #8352, install it.
-> I have pkg-pr-new installed in this repository.
> Introduce pkg.pr.new

- .github/workflows/commenting-on-old-issues.yml
None
Reduce the amount of noise.
> Fix old issue threshold to 6 months

- scripts/pkg.pr.new-custom-comment.mjs
Related to https://github.com/stylelint/stylelint/issues/8352
This PR is follow-up to https://github.com/stylelint/stylelint/pull/8353.
This PR fixes the broken links provided by the automatic comment posting script.
Sorry for having to fix it so many times 😓
> Fix pkg.pr.new-comment workflow

- .changeset/gold-steaks-grab.md
- lib/rules/function-url-quotes/__tests__/index.mjs
- lib/rules/function-url-quotes/index.cjs
- lib/rules/function-url-quotes/index.mjs
> Added `function-url-quotes` support for computing `EditInfo`

- .changeset/brown-hounds-teach.md
- lib/rules/length-zero-no-unit/README.md
- lib/rules/length-zero-no-unit/__tests__/index.mjs
- lib/rules/length-zero-no-unit/index.cjs
- lib/rules/length-zero-no-unit/index.mjs
- types/stylelint/index.d.ts
> Add `ignorePreludeOfAtRules: []` to `length-zero-no-unit`

- lib/__tests__/standalone-compute-edit-info.test.mjs
> Test `EditInfo` through standalone unit tests

- docs/user-guide/options.md
> Document `computeEditInfo` option

- scripts/pkg.pr.new-custom-comment.mjs
None, it's a content change.
The pkg.pr.new is working well for us. This PR quietens the message content and reduces the space it takes.
> Fix pkg.pr.new comment content

- types/stylelint/index.d.ts
Ref https://github.com/stylelint/stylelint/pull/8473#issuecomment-2746516204
> Fix types for stable editinfo

- lib/rules/container-name-pattern/index.cjs
- lib/rules/container-name-pattern/index.mjs
Ref: https://github.com/stylelint/stylelint/pull/8513#pullrequestreview-2742792664
Caught prior to release. No changeset needed.
> Fix `container-name-pattern` mutation of shared reference set

- .changeset/clear-llamas-push.md
- lib/formatters/__tests__/compactFormatter.test.mjs
- lib/formatters/compactFormatter.cjs
- lib/formatters/compactFormatter.mjs
> Fix `compact` formatter with pnpm to newline the exit code

- lib/rules/alpha-value-notation/README.md
Part of #4808
This is the first try of #4808, so I welcome any feedback.
I believe that including a rule name in the config code block should be helpful for many people, especially those who are unfamiliar with Stylelint. Folks can easily copy and paste the code block to their Stylelint config files.
> Document `alpha-value-notation` full configs

- scripts/pkg.pr.new-custom-comment.mjs
None. Related to DX only.
To provider simpler information, this PR reduces lines of the comment.
> Improve PR comment by `pkg.pr.new`

- docs/developer-guide/rules.md
Adds `example.org` to the list of conventions.
> Document `example.org` in rule README conventions

- .changeset/sour-fishes-fetch.md
- lib/rules/media-feature-range-notation/README.md
- lib/rules/media-feature-range-notation/__tests__/index.mjs
- lib/rules/media-feature-range-notation/index.cjs
- lib/rules/media-feature-range-notation/index.mjs
- types/stylelint/index.d.ts
Closes #8652 
No, the thread contains all the info
> Add `except: ["exact-value"]` to `media-feature-range-notation`

- docs/user-guide/rules.md
None, as related to the release.
Caught this missing doc change as part of the [release process](https://stylelint.io/maintainer-guide/releases/).
> Document config rules for 39.0.0

- CHANGELOG.md
I'm so rusty and still in summer holiday mode that I forgot to add the summary before merging the changeset PR 😅
> Document changelog summary

- .github/workflows/pkg.pr.new-comment.yml
- .github/workflows/pkg.pr.new.yml
- .github/workflows/preparing-github-release.yml
- .github/workflows/releasing.yml
- .github/workflows/testing.yml
None.
Ref https://docs.github.com/en/actions/reference/security/secure-use#using-third-party-actions
> Pin actions for security

- docs/developer-guide/rules.md
Ref: https://github.com/stylelint/stylelint/pull/8781
> Document trailing semicolon convention in developer guide
