stylelint/stylelint

docs/user-guide/rules/list.md
lib/rules/alpha-value-notation/README.md
lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js
lib/rules/index.js

Closes #4720 
I added an `exceptProperties` option as support for percentage alpha-values for `opacity` was added in a [later spec](https://drafts.csswg.org/css-color/#transparency), it [isn't supported in some browsers like Safari](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#Browser_compatibility), and  I don't think [postcss-preset-env](https://preset-env.cssdb.org/) transpiles it yet.
When this rule and the other two new rules are in, I'll create a follow-up issue to refactor some of the shared functions into utils, e.g. `getValue` and `setValue`.

Add alpha-value-notation

---

README.md
package.json

https://github.com/stylelint/stylelint/issues/4787

Add minimum node version to engine field in package.json

---

lib/augmentConfig.js
lib/normalizeAllRuleSettings.js

In a future PR this module will be required by the new `browser.js` module. This change has been extracted from: https://github.com/stylelint/stylelint/pull/4796
Related to issue https://github.com/stylelint/stylelint/issues/3935
This change is a small part of the changes in PR https://github.com/stylelint/stylelint/pull/4796

Move function normalizeAllRuleSettings() out to a separate module

---

lib/createPartialStylelintResult.js
lib/createStylelintResult.js

In a future PR this module will be required by the new browser.js module. This change has been extracted from: #4796
This change is a small part of the changes in PR #4796

Create new 'createPartialStylelintResult' module

---

lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js

Hi there,
This is a PR that aims to tackle a problem addressed in #4792, namely that with floating-point conversions, the error messages (and "fixed" outputs) have numbers that are unpleasant to look at/unreasonable. 
My preliminary shot at this (which might need some feedback) is to use Javascript's in-built [`.toPrecision()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision) function. I used this instead of [`.toFixed()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) as the latter rounds down very small numbers to 0 (e.g. `0.003`, which I included as a test case), which would create an incorrect error message. I added these precision-specifies to `asNumber()` and `asPercentage()`.
I am …

Fix error message percentage/number precision for alpha-value-notation

---

lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.js
lib/rules/font-family-no-missing-generic-family-keyword/index.js

Fixes #4765
Yes, this introduces a second parse loop through a font-family.
To avoid this, we could add an parameter to findFontFamily which
dictates whether to include variables in the result, but the function
would need to blindly include variables, without sanity checking them
(like whether a variable represents a number or something).

Fix false positives for variables in font-family-no-missing-generic-family-keyword

---

lib/__tests__/fixtures/html.js
lib/__tests__/standalone-syntax.test.js
lib/getPostcssResult.js

Closes #4793
It's not clear what's happening here, and a deeper investigation is needed. It appears the HTML syntax is somehow interfering with JavaScript files that contain the word "html".
We can workaround the issue by not lazy loading the HTML syntax ourselves and instead relying on postcss-syntax mechanism. We can do this because we are using the original postcss-html module, unlike with postcss-markdown and postcss-css-in-js where we are using our own forks.
I'll create a follow-up issue at some point to discuss what we do about postcss-syntax going forward. At the moment the syntax inferring is being handled by an unmaintained package.

Fix with workaround a TypeError thrown for "html"

---

lib/__tests__/cli.test.js
lib/cli.js

Write error information to STDERR

---

lib/lintPostcssResult.js
lib/lintSource.js

In a future PR this module will be required by the new `browser.js` module. This change has been extracted from: #4796 
This change is a small part of the changes in PR #4796

Create new 'lintPostcssResult' module

---

lib/rules/max-empty-lines/__tests__/index.js
lib/rules/max-empty-lines/index.js

https://github.com/stylelint/stylelint/issues/4820
max-empty-lines/index.js line 58
https://github.com/stylelint/stylelint/blob/master/lib/rules/max-empty-lines/index.js#L60
```javascript
if (!ignoreComments) {
node.raws.left = getChars(node.raws.left);
node.raws.right = getChars(node.raws.right);
}
```
for sugarss inline comment node.raws.right may get a undefined.

Fix TypeError for inline comments and autofix for sugarss in max-empty-lines 

---

lib/rules/property-no-unknown/__tests__/index.js
lib/utils/__tests__/isScssVariable.test.js
lib/utils/__tests__/isStandardSyntaxDeclaration.test.js
lib/utils/__tests__/isStandardSyntaxProperty.test.js
lib/utils/isScssVariable.js
lib/utils/isStandardSyntaxDeclaration.js
lib/utils/isStandardSyntaxProperty.js

Closes #4544
I didn't add test cases of `isStandardSyntaxDeclaration` for Sass indented syntax because the `postcss-sass` parser does not understand `@use` syntax yet (https://github.com/AleshaOleg/postcss-sass/issues/145).

Fix false positives for namespaced variables in property-no-unknown

---

docs/developer-guide/formatters.md
lib/formatters/compactFormatter.js
lib/formatters/jsonFormatter.js
lib/formatters/stringFormatter.js
lib/formatters/unixFormatter.js
lib/formatters/verboseFormatter.js
lib/standalone.js
types/stylelint/index.d.ts

Add a named type for formatter functions.
This change is a small part of the changes in PR #4796. On its own this change is quite small. The new type will be used as part of a follow up PR. See [this diff for details](https://github.com/stylelint/stylelint/pull/4796/files#diff-9b6919035950137210a76ab06b9f141aR290-R293).

Add type `Formatter` for formatter functions

---

lib/__tests__/syntaxes.test.js
lib/syntaxes/syntax-css-in-js.js

This change is a small part of the changes in PR #4796.
The CSS-in-JS syntax was previously being exported as a function instead of an object. This worked because functions can still have properties attached to them. It was a bit confusing though. 
This PR updates the syntax to export an object.
After the first commit in this PR, the test should fail like this:
```
FAIL  lib/__tests__/syntaxes.test.js
● syntaxes › syntax is an object with parse and stringify keys: css-in-js
expect(received).toMatchObject(expected)
Matcher error: received value must be a non-null object
Received has type:  function
Received has value: [Function syntax]
10 | describe('syntaxes', () => {
11 | …
```

Export an object from the CSS-in-JS syntax

---

lib/rules/selector-type-no-unknown/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js
lib/utils/isStandardSyntaxTypeSelector.js

Fix shadow part ident falsly parsed as type selector

---

lib/prepareReturnValue.js
lib/standalone.js

In a future PR this module will be required by the new `browser.js` module. This change has been extracted from: https://github.com/stylelint/stylelint/pull/4796.
This change is a small part of the changes in PR #4796

Create new 'prepareReturnValue' module

---

lib/rules/selector-max-id/README.md
lib/rules/selector-max-id/__tests__/index.js
lib/rules/selector-max-id/index.js

Hi there, 
This PR implements an option requested in #4619, the verbose `ignoreContextFunctionalPseudoClasses` to `selector-max-id`. In addition to modifying the rule, it also introduces a set of simple test cases (only testing on `:not`, `:has`, and `:matches` currently), and adds documentation to explain the usage of the rule.
Closes #4619.
As mentioned in the issue discussion, it looks like `stylelint/lib/utils/isLogicalCombination.js` needs to be updated to support more pseudo-classes, such as `:is` and `:where` (and possibly `:nth-child`); will follow up on this!

Add ignoreContextFunctionalPseudoClasses to selector-max-id

---

lib/getPostcssResult.js
lib/standalone.js
types/stylelint/index.d.ts

Another refactor. This moves a couple of chunks of functionality out to separate functions. It's not particularly essential, but (imo) makes it easier to understand what's happening in each file.
This should be the last bit of refactoring from PR #4796.  The remaining follow-on PRs should result in new (or changed) functionality instead of rearranging internals.
This change is a small part of the changes in PR #4796

A small refactor

---

CHANGELOG.md
lib/rules/comment-empty-line-before/README.md
lib/rules/comment-empty-line-before/__tests__/index.js
lib/rules/comment-empty-line-before/index.js

Closes #4814.
It is pretty self explanatory, I mostly followed instructions from the issue.

Add ignoreComments[] to comment-empty-line-before

---

docs/user-guide/usage/cli.md
docs/user-guide/usage/node-api.md
docs/user-guide/usage/options.md
lib/__tests__/standalone.test.js
lib/getPostcssResult.js
types/stylelint/index.d.ts

This overloads the `customSyntax` option to also accept a syntax object. The option also maintains its previous behaviour of accepting a string. This should be a fully backwards compatible change. 
The signature of this option has changed from `string` to `string | { parse: Function }`. This follows the convention of the `formatter` option, which [has similar behaviour](https://stylelint.io/user-guide/usage/options#formatter). 
https://github.com/stylelint/stylelint/issues/3935. 
This is based on a section of https://github.com/stylelint/stylelint/pull/4796. This is the only part of that PR that changes existing functionality.
The change itself is fairly straightforward, but it's …

Accept syntax object in `customSyntax` option

---

docs/user-guide/ignore-code.md
lib/__tests__/disableRanges-integration.test.js
lib/__tests__/disableRanges.test.js
lib/assignDisabledRanges.js

Closes #4840.
Let me know if there is.

Add support for descriptions in stylelint command comments

---

package-lock.json
package.json
types/global.d.ts

This is a part of #4399.
This change installs the type definition `@types/table` of the `table` package.
The package is used in `lib/formatters/stringFormatter.js`:
https://github.com/stylelint/stylelint/blob/cecacb9d4fe3b5bae5f264efa6e60c414a0f4946/lib/formatters/stringFormatter.js#L8
See also:
- https://www.npmjs.com/package/table
- https://www.npmjs.com/package/@types/table

Install `@types/table` type definition

---

types/postcss-syntax/index.d.ts
types/postcss/index.d.ts

This is a part of #4399.
This change adds a type definition for the `postcss-syntax` package.
To find the definition easily, this extracts a new file from the `types/postcss/index.d.ts` file.
Note that there is no `@types/postcss-syntax` package.
(see <https://www.npmjs.com/search?q=%40types%2Fpostcss-syntax>)
Here is a main source of the package:
https://github.com/gucong3000/postcss-syntax/blob/v0.36.2/index.js
Also, `postcss-syntax` is used only in `lib/getPostcssResult.js`:
https://github.com/stylelint/stylelint/blob/cecacb9d4fe3b5bae5f264efa6e60c414a0f4946/lib/getPostcssResult.js#L64-L75

Add type definition for `postcss-syntax`

---

types/global.d.ts

The `postcss-scss` package has own types already.
https://github.com/postcss/postcss-scss/blob/2.1.1/lib/scss-syntax.d.ts

Use official `postcss-scss` types

---

lib/createPlugin.js
lib/rules/index.js
lib/utils/checkAgainstRule.js
types/stylelint/index.d.ts

#4399
We're currently using DefinitelyTyped for stylelint types, but it's lacking in a number of respects. I'm excited to see stylelint writing its own types, and I wanted to contribute some types that have been particular pain points for us with DefinitelyTyped.

Add types for plugin objects

---

docs/user-guide/rules/list.md
lib/rules/at-rule-no-vendor-prefix/README.md
lib/rules/at-rule-no-vendor-prefix/__tests__/index.js
lib/rules/at-rule-no-vendor-prefix/index.js
lib/rules/media-feature-name-no-vendor-prefix/README.md
lib/rules/media-feature-name-no-vendor-prefix/__tests__/index.js
lib/rules/media-feature-name-no-vendor-prefix/index.js
lib/rules/property-no-vendor-prefix/README.md
lib/rules/property-no-vendor-prefix/__tests__/index.js
lib/rules/property-no-vendor-prefix/index.js
lib/rules/selector-no-vendor-prefix/README.md
lib/rules/selector-no-vendor-prefix/__tests__/index.js
lib/rules/selector-no-vendor-prefix/index.js
lib/rules/value-no-vendor-prefix/README.md
lib/rules/value-no-vendor-prefix/__tests__/index.js
lib/rules/value-no-vendor-prefix/index.js
lib/utils/isAutoprefixable.js

Autofix for *-no-vendor rules

---

lib/rules/length-zero-no-unit/__tests__/index.js
lib/rules/length-zero-no-unit/index.js

e.g.
```css
font: var(--Funnel-header-font, 600 16px/1.5 var(--font-header));
```
lineHeightNode is undefined, so we just need to check for it.

Fix TypeError for custom properties fallback in length-zero-no-unit

---

CHANGELOG.md
lib/__tests__/disableRanges.test.js
lib/assignDisabledRanges.js
types/postcss/index.d.ts

Fixes #4886. 
This works around postcss/postcss-scss#109 by combining adjacent `//` comments into a single node before passing it to `checkComment`.

Support multi-line disable descriptions

---

docs/developer-guide/formatters.md
docs/user-guide/configure.md
lib/__tests__/cli.test.js
lib/__tests__/fixtures/config-block-no-empty-report-disables.json
lib/__tests__/fixtures/empty-block-with-relevant-disable.css
lib/__tests__/invalidScopeDisables.test.js
lib/__tests__/needlessDisables.test.js
lib/__tests__/reportDisables.test.js
lib/__tests__/standalone-invalidScopeDisables.test.js
lib/__tests__/standalone-needlessDisables.test.js
lib/__tests__/stylelintignore-test/stylelintignore.test.js
lib/cli.js
lib/formatters/__tests__/disableOptionsReportStringFormatter.test.js
lib/formatters/disableOptionsReportStringFormatter.js
lib/invalidScopeDisables.js
lib/needlessDisables.js
lib/prepareReturnValue.js
lib/reportDisables.js
lib/utils/validateOptions.js
system-tests/001/__snapshots__/fs.test.js.snap
system-tests/001/__snapshots__/no-fs.test.js.snap
system-tests/002/__snapshots__/fs.test.js.snap
system-tests/002/__snapshots__/no-fs.test.js.snap
system-tests/003/__snapshots__/fs.test.js.snap
system-tests/003/__snapshots__/no-fs.test.js.snap
types/stylelint/index.d.ts

This allows config authors to specify that certain rules may not be disabled by authors.

Add a reportDisables secondary option

---

lib/rules/selector-combinator-space-after/__tests__/index.js
lib/rules/selectorCombinatorSpaceChecker.js
lib/utils/__tests__/isStandardSyntaxCombinator.test.js
lib/utils/isStandardSyntaxCombinator.js

Hey there!
This is a PR that tries to fix the false positive brought up in #4584, namely that a trailing combinator (such as the general sibling combinator, `~`) is not properly handled by `selector-combinator-space-after`.
After some discussion in #4849, this PR implements a fix by updating the `isStandardSyntaxCombinator` rule util to ignore certain combinators that are the first or last combinator in their container. Since combinators should *generally* be between two different selectors, we can rule out combinators that... aren't. Then, we use this new utility in `selectorCombinatorSpaceChecker`, which then fixes the false positive in `selector-combinator-space-after`.
I also added some test to verify our functionality, for `isStandardSyntaxCombinator` and for the case mentioned in …

Fix false positives for trailing combinator in selector-combinator-space-after

---

lib/utils/__tests__/atRuleParamIndex.test.js
lib/utils/__tests__/declarationValueIndex.test.js
lib/utils/__tests__/isCustomPropertySet.test.js
lib/utils/__tests__/isFirstNested.test.js

Fix callbacks in tests

---

CHANGELOG.md

Currently, the CI fails. This pull request will fix the failure:
https://github.com/stylelint/stylelint/runs/1042012333?check_suite_focus=true#step:6:31

Fix CHANGELOG.md format via Prettier

---

lib/__tests__/__snapshots__/cli.test.js.snap
lib/__tests__/cli.test.js
lib/__tests__/descriptionlessDisables.test.js
lib/__tests__/disableRanges.test.js
lib/assignDisabledRanges.js
lib/cli.js
lib/descriptionlessDisables.js
lib/prepareReturnValue.js
lib/standalone.js
types/stylelint/index.d.ts

Fixes #4868.
This now adds the description, if any to the `DisabledRange` objects and then reports any ranges without descriptions if the flag is passed. For adding the new flag, I mostly mirrored what already exists for needless and invalid-scope disables, so let me know if I missed anything.

Add a reportDescriptionlessDisables flag

---

lib/__tests__/disableRanges.test.js
lib/assignDisabledRanges.js

Fixes #4911.
This checks line numbers before combining adjacent `//` comments.

Avoid combining disable comments with a blank line

---

lib/utils/__tests__/isKeyframeRule.test.js

Fix `isKeyframeRule.test.js` that use callbacks

---

lib/__tests__/disableRanges.test.js
lib/assignDisabledRanges.js

Fixes #4937.
This now only starts a merge when the comment begins with `stylelint-` and either the first line contains `--` or the second line starts with `--`.
The merge will end whenever another line starts with `stylelint-` to allow for adjacent stylelint commands.

Improve inline comment merging

---

docs/user-guide/configure.md
docs/user-guide/usage/node-api.md
docs/user-guide/usage/options.md

This documentation change adds missing descriptions about:
- the `reportedDisables` property in the returned data of Node.js API
- Ref: #4897
- the `reportDescriptionlessDisables` option (flag)
- Ref: #4907 
Close #4912
In addition, this change unifies the labeling of the `stylelint-disable` comment for clarity.
If there are any weird phrases, please point them out to me. 🙏

Describe missing `reportedDisables` and `reportDescriptionlessDisables`

---

docs/user-guide/rules/list.md

This PR adds the missing `media-feature-name-value-whitelist` rule to the rule list document.
https://github.com/stylelint/stylelint/blob/7449dc004c9e75119423cd7e4f3780ba895b5c89/lib/rules/media-feature-name-value-whitelist/README.md

Add missing `media-feature-name-value-whitelist` to rule list

---

lib/utils/__tests__/isStandardSyntaxAtRule.test.js

It seems [`postcss-sass`](https://github.com/AleshaOleg/postcss-sass) does not support `@mixin`, so maybe the following test case is incorrect:
https://github.com/stylelint/stylelint/blob/65ab12ebfa08cf92525626836bd9847c8e740da9/lib/utils/__tests__/isStandardSyntaxAtRule.test.js#L70-L80
In this PR, I've marked the case above as skipped.

Fix `isStandardSyntaxAtRule.test.js` that use callbacks

---

package-lock.json
package.json

Bump known-css-properties from 0.19.0 to 0.20.0

---

.github/workflows/linting.yml
.github/workflows/testing.yml

None.
Node.js 14 [goes LTS on 27.10.2020](https://nodejs.org/en/about/releases/). We need to be sure stylelint works there. ~~As soon it went LTS we could switch default Node.js version for linting and coverage to 14.~~ Decided to change it now, because I see no downsides of not doing so now.

Add Node.js 14 to CI

---

lib/utils/__tests__/findAtRuleContext.test.js
lib/utils/__tests__/isContextFunctionalPseudoClass.test.js
lib/utils/__tests__/isMap.test.js
lib/utils/__tests__/isStandardSyntaxFunction.test.js

This PR fixes the following tests that use callbacks:
- `lib/utils/__tests__/findAtRuleContext.test.js`
- `lib/utils/__tests__/isContextFunctionalPseudoClass.test.js`
- `lib/utils/__tests__/isMap.test.js`
- `lib/utils/__tests__/isStandardSyntaxFunction.test.js`
This PR includes some indentation changes, so I recommend viewing with [hidden whitespace changes](https://github.com/stylelint/stylelint/pull/4970/files?w=1).

Fix some tests that use callbacks

---

lib/rules/custom-media-pattern/__tests__/index.js
lib/rules/custom-media-pattern/index.js
lib/rules/custom-property-pattern/__tests__/index.js
lib/rules/custom-property-pattern/index.js
lib/rules/keyframes-name-pattern/__tests__/index.js
lib/rules/keyframes-name-pattern/index.js
lib/rules/selector-class-pattern/__tests__/index.js
lib/rules/selector-class-pattern/index.js
lib/rules/selector-id-pattern/__tests__/index.js
lib/rules/selector-id-pattern/index.js
lib/rules/selector-nested-pattern/__tests__/index.js
lib/rules/selector-nested-pattern/index.js

Show the pattern in "*-pattern" rule messages (#4974)

---

docs/user-guide/rules/list.md
lib/rules/comment-pattern/README.md
lib/rules/comment-pattern/__tests__/index.js
lib/rules/comment-pattern/index.js
lib/rules/index.js
lib/utils/__tests__/isSharedLineComment.test.js

Closes [#4887](https://github.com/stylelint/stylelint/issues/4887)
I do want to mention that it is my first PR for an open source project. I'll appreciate any input :)

Add "comment-pattern" rule

---

lib/rules/property-no-unknown/README.md
lib/rules/property-no-unknown/__tests__/index.js
lib/rules/property-no-unknown/index.js

Add ignoreAtRules to property-no-unknown

---

lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js
lib/rules/color-function-notation/__tests__/index.js
lib/rules/color-function-notation/index.js
lib/rules/hue-degree-notation/__tests__/index.js
lib/rules/hue-degree-notation/index.js

*-notation: fix false negatives for $ vars (#5010)

---

lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js

I disable some test cases due to failure as follows:
```
● isStandardSyntaxTypeSelector › shadow-piercing descendant combinator
TypeError: Cannot read property 'parent' of undefined
14 | 	// The fake-tag's "parent" is actually a selector node, whose parent
15 | 	// should be the :nth-child pseudo node.
> 16 | 	if (!node.parent || !node.parent.parent) {
| 	          ^
17 | 		return false;
18 | 	}
19 |
at isStandardSyntaxTypeSelector (lib/utils/isStandardSyntaxTypeSelector.js:16:12)
at Object.<anonymous> (lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js:49:10)
```
The cause seems due to [`postcss-selector-parser`](https://github.com/postcss/postcss-s …

Fix `isStandardSyntaxTypeSelector.test.js` that use callbacks

---

lib/__tests__/disableRanges.test.js

This change uses `async/await` a lot to avoid callbacks.
Also, it uses [`.rejects`](https://jestjs.io/docs/en/tutorial-async.html#rejects) of Jest to test thrown errors, instead of `throw/catch`.
Besides, it uses template literals a lot for the readability of multi-line CSS code.
---
Recommended **splitted** diff view: https://github.com/stylelint/stylelint/pull/4991/files?diff=split&w=1

Fix `disableRanges.test.js` that uses callbacks

---

lib/__tests__/fixtures/plugin-async.js

Noticed it while looking at lgtm.com https://lgtm.com/projects/g/stylelint/stylelint/latest/files/lib/__tests__/fixtures/plugin-async.js?sort=name&dir=ASC&mode=heatmap&showExcluded=true

Remove superfluous argument passed to Promise

---

CHANGELOG.md
lib/rules/selector-attribute-name-disallowed-list/__tests__/index.js
lib/rules/selector-attribute-name-disallowed-list/index.js

Fix false positives for valueless attribute selectors in selector-attribute-name-disallowed-list

---

docs/user-guide/rules/regex.md

I'm not sure that I'm right, but your example with negative lookahead regex doesn't work for me. We can write positive lookbehind or just "^my-".

Fix incorrect enforce prefix regex documentation

---

docs/user-guide/integrations/other.md

Just integrated `stylelint` into [Putout code transformer](https://github.com/coderaiser/putout) as [processor-css](https://github.com/coderaiser/putout/tree/master/packages/processor-css), so now it can be used with `eslint`, `remark`, `putout` itself, and other [processors](https://github.com/coderaiser/putout#processors) :).

docs: other: add putout

---

docs/user-guide/integrations/other.md

In added stylelint in Mega-Linter, with associated documentation
Is this ok for you ?
Doc page -> https://nvuillam.github.io/mega-linter/descriptors/css_stylelint/
None, as it's a documentation enhancement
No, it's self-explanatory

docs: add Mega-Linter in Other integrations

---

lib/prepareReturnValue.js
system-tests/003/__snapshots__/fs.test.js.snap
system-tests/003/fs.test.js
system-tests/004/__snapshots__/fs.test.js.snap
system-tests/004/__snapshots__/no-fs.test.js.snap
system-tests/004/config.json
system-tests/004/fs.test.js
system-tests/004/no-fs.test.js
system-tests/004/stylesheet.css

This sets the `errored` property (and thus the exit code) as long as
any warning has severity "error", which includes warnings generated by
--report options.
Closes #5046

Properly set the errored property for --report options

---

docs/user-guide/usage/options.md
lib/__tests__/__snapshots__/cli.test.js.snap
lib/__tests__/standalone-formatter.test.js
lib/formatters/__tests__/tapFormatter.test.js
lib/formatters/index.js
lib/formatters/tapFormatter.js
lib/utils/__tests__/getFormatterOptionsText.test.js
types/stylelint/index.d.ts

This PR adds support for a TAP formatter using an update to the code snippet from @danielsamuels discussed in #3889.
Closes #3889
No, it is self explanatory. Used #3524 as a starting point.

Add support for a TAP formatter

---

lib/rules/color-hex-length/__tests__/index.js
lib/rules/color-hex-length/index.js

Continuing on the change made in #5101 (for issue #4826), this updates
`color-hex-length` to switch to using `postcss-value-parser` because
`style-search` returns false positives when used with `css-in-js` object
notation.
Unit tests have also been added to check the `css-in-js` syntax for this
rule.

Fix false negatives for css-in-js object notation in color-hex-length

---

lib/rules/color-hex-case/__tests__/index.js
lib/rules/color-hex-case/index.js

As discussed in #4826, `style-search` has false positives when used with `css-in-js` object notation. This change updates the `color-hex-case` rule to use `postcss-value-parser` instead, which has support for `css-in-js` as a syntax.
The unit tests now also include a suite for testing both `upper` and `lower` options for `color-hex-case` with the `css-in-js` syntax.

Fix false negatives for css-in-js object notation in color-hex-case

---

docs/user-guide/rules/list.md
lib/rules/declaration-block-no-duplicate-custom-properties/README.md
lib/rules/declaration-block-no-duplicate-custom-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-custom-properties/index.js
lib/rules/index.js

Add declaration-block-no-duplicate-custom-properties

---

docs/user-guide/usage/cli.md

It's inconvenient to find documentation for a CLI parameters, because all parameters are split into two pages: [CLI](https://stylelint.io/user-guide/usage/cli) and [Options](https://stylelint.io/user-guide/usage/options).
This pull request introduce some information duplication, however it makes finding description of a CLI parameter easier. As they all gathered, where is is expected — on a CLI page.

Document all CLI parameters in one place

---

lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js

Closes https://github.com/stylelint/stylelint/issues/5129
I ran into this bug while preparing a new release of [stylelint-scales](https://github.com/signal-noise/stylelint-scales).
As mentioned in https://github.com/stylelint/stylelint/issues/5129, the best we can do is narrow down the possibilities of what a particular node could represent. This pull request uses in the slash within modern colour function notation as a fallback to find the `<alpha-value>`.

Fix false negatives for CSS variables in alpha-value-notation

---

lib/rules/declaration-property-value-allowed-list/README.md

the patterns `a { background: pink; }` and `a { color: pink; }` are both considered violations and not considered violations. See https://github.com/stylelint/stylelint/tree/64078f5b7fb7cdf892a32840ee9a9c906c7c5a1e/lib/rules/declaration-property-value-allowed-list#options
Not only does this not make sense, but it is not consistent with the tests
https://github.com/stylelint/stylelint/blob/64078f5b7fb7cdf892a32840ee9a9c906c7c5a1e/lib/rules/declaration-property-value-allowed-list/__tests__/index.js#L26-L31
which checks accepts only the color green, not pink.

fix rule doc on declaration-property-value-allowed

---

lib/reference/keywordSets.js

#5157
lh and rlh units are supported by Safari.
https://trac.webkit.org/changeset/259703/webkit/
caveat: https://bugs.webkit.org/show_bug.cgi?id=211351
the commit message lists \@​property but GitHub displays it as @property

Fix some false positives in *-no-unknown rules

---

lib/reference/keywordSets.js

Closes #5168
I consider removing `:contains()` a breaking change hence it will have to wait for the next major.
FYI it was dropped ["due to a lack of implementations"](https://lists.w3.org/Archives/Public/www-style/2012Apr/0377.html).
e.g. Selenium used Sizzle which supported `:contains()`.
`:val()` was erroneously added because it was listed in [one of the specification's examples](https://drafts.csswg.org/selectors-4/#example-37a1ab6b).
ref: https://github.com/lloyd/JSONSelect/blob/master/JSONSelect.md#language-overview

Fix false positives for :autofill in selector-pseudo-class-no-unknown

---

package-lock.json
package.json

`@types/browserslist@4.15.0` has been deprecated because `browserslist@4.16.3` provides its own type definitions.
So, this change removes `@types/browserslist` and updates `browserslist` to the latest version.
I execute the following commands to update `package.json` and `package-lock.json`:
```shell
npm rm @types/browserslist
npm up browserslist
```
See below:
- https://www.npmjs.com/package/@types/browserslist/v/4.15.0
- https://github.com/browserslist/browserslist/blob/4.16.3/index.d.ts
Close #5118

Remove `@types/browserslist` and update `browserslist`

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/named-grid-areas-no-invalid/README.md
lib/rules/named-grid-areas-no-invalid/__tests__/index.js
lib/rules/named-grid-areas-no-invalid/index.js
lib/rules/named-grid-areas-no-invalid/utils/__tests__/findNotContiguousOrRectangular.test.js
lib/rules/named-grid-areas-no-invalid/utils/__tests__/isRectangular.test.js
lib/rules/named-grid-areas-no-invalid/utils/findNotContiguousOrRectangular.js
lib/rules/named-grid-areas-no-invalid/utils/isRectangular.js

Closes #5155
Adds rule to validate CSS grid areas to the spec defined here: https://drafts.csswg.org/css-grid/#grid-template-areas-property

Add named-grid-areas-no-invalid

---

lib/rules/alpha-value-notation/index.js
lib/rules/color-function-notation/index.js
lib/rules/color-hex-case/index.js
lib/rules/color-hex-length/index.js
lib/rules/declaration-bang-space-after/index.js
lib/rules/declaration-bang-space-before/index.js
lib/rules/declaration-block-semicolon-space-before/index.js
lib/rules/function-max-empty-lines/index.js
lib/rules/function-name-case/index.js
lib/rules/function-parentheses-newline-inside/index.js
lib/rules/function-parentheses-space-inside/index.js
lib/rules/function-whitespace-after/index.js
lib/rules/functionCommaSpaceChecker.js
lib/rules/hue-degree-notation/index.js
lib/rules/value-keyword-case/index.js
lib/rules/value-list-comma-newline-after/index.js
lib/rules/value-list-comma-space-after/index.js
lib/rules/value-list-comma-space-before/index.js
lib/rules/value-list-max-empty-lines/index.js
lib/utils/getDeclarationValue.js
lib/utils/setDeclarationValue.js

This change adds two utility functions, `getDeclarationValue` and `setDeclarationValue`, that replace a pattern found across many rule files. Extracting the `getValue` and `setValue` functions across the rule files was mentioned by @jeddy3 in #5106. (But if we want a specific issue to track this as well, I can still file one.)
I was about to tackle replacing another `style-search` based rule, but remembered that I'd probably want this utility function. And this change felt large enough to make on its own without also updating an additional rule.

Refactor getting and setting declaration values into utils

---

lib/rules/declaration-block-trailing-semicolon/README.md
lib/rules/declaration-block-trailing-semicolon/__tests__/index.js
lib/rules/declaration-block-trailing-semicolon/index.js

Closes #5159
It cannot be named `"except"` because it would require `foo { property: value; }` to be valid for `"never"` which is useless/stupid. Or do you imagine a use case for it that would warrant it?
Should it be supported just for consistency?
**Can an option be exclusive to `"always"`?** If so do you have an example?

Add ignore: [single-declaration] to declaration-block-trailing-semicolon

---

lib/rules/named-grid-areas-no-invalid/README.md

The invalid patterns aren't given a red background [on the website](https://stylelint.io/user-guide/rules/named-grid-areas-no-invalid). We should have used the ["expanded description"](https://stylelint.io/user-guide/rules/about#readmes) instead.

Fix named-grid-area-no-invalid README

---

lib/rules/color-no-hex/__tests__/index.js
lib/rules/color-no-hex/index.js

`style-search` returns false positives when used with `css-in-js` object notation. This change continues with the discussion in #4826 and moves another test towards using `postcss-value-parser`.

Fix false positives for css-in-js in color-no-hex

---

.husky/pre-commit
package-lock.json
package.json

`husky` no longer requires `pinst` and `is-ci` since v5.1.2.
(see <https://github.com/typicode/husky/commit/84be6755c77ee81b14260765f2224e70f6bca8df>)
So, this change simplifies the `husky` configuration and removes the needless packages.
See also <https://typicode.github.io/husky>.
None.
None.

Fix husky configuration and remove needless packages

---

lib/reference/mathFunctions.js
lib/rules/length-zero-no-unit/__tests__/index.js

Closes #5199
First commit is simply small styling alignment, not part of the issue, but small enough to simply include here I guess.

Fix false positives for level 4 math functions in length-zero-no-unit

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/no-invalid-position-at-import-rule/README.md
lib/rules/no-invalid-position-at-import-rule/__tests__/index.js
lib/rules/no-invalid-position-at-import-rule/index.js

Add no-invalid-position-at-import-rule

---

lib/utils/validateOptions.js

This refactoring aims to make the code a bit more readable in `lib/utils/validateOptions.js`.
None.

Refactor `lib/utils/validateOptions.js`

---

lib/rules/linebreaks/index.js

This refactoring aims to simplify the code and fix `no-shadow` violations of ESLint (#5013) in `lib/rules/linebreaks/index.js`.
Related to #5013

Refactor `lib/rules/linebreaks/index.js`

---

lib/rules/selector-max-specificity/index.js

This refactoring aims to simplify the code a bit and resolve `no-shadow` violations of ESLint (#5013).
Related to #5013

Refactor `lib/rules/selector-max-specificity/index.js`

---

lib/rules/keyframe-declaration-no-important/README.md

- `foo` matches the conventions
- `opacity` is a better real-world example as animating `margin` isn't performant

Improve examples for keyframe-declaration-no-important

---

lib/__tests__/defaultSeverity.test.js

This refactoring removes callbacks via `async/await`.
See also <https://jestjs.io/docs/asynchronous#asyncawait>.
Part of #4881

Refactor `lib/__tests__/defaultSeverity.test.js`

---

lib/__tests__/postcssPlugin.test.js

This refactoring aims to make the usage of `Promise` in the test safer.
(via `.resolves`, `.rejects`, and other Jest matchers)
See also <https://jestjs.io/docs/expect>.
As a result, we can remove callbacks (which may not be performed) from the test.
Part of #4881

Refactor `lib/__tests__/postcssPlugin.test.js`

---

lib/__tests__/descriptionlessDisables.test.js

This refactoring aims to clarify the test code:
- Use `async/await` to remove callbacks
- Indent template literals with tabs
Part of #4881
I recommend viewing the diff [ignoring whitespaces](https://github.com/stylelint/stylelint/pull/5234/files?diff=unified&w=1).

Refactor `lib/__tests__/descriptionlessDisables.test.js`

---

lib/__tests__/createLinter.test.js

This refactoring removes callbacks via Jest `.resolves`.
See also <https://jestjs.io/docs/asynchronous#resolves--rejects>
Part of #4881

Refactor `lib/__tests__/createLinter.test.js`

---

lib/utils/__tests__/nodeContextLookup.test.js

This refactoring aims to avoid asynchronous callbacks in the test code.
Part of #4881

Refactor `lib/utils/__tests__/nodeContextLookup.test.js`

---

lib/formatters/index.js
types/global.d.ts

This change uses the built-in type definitions of the `import-lazy` package.
`importLazy()` accepts an argument as a module ID:
https://github.com/sindresorhus/import-lazy/blob/v4.0.0/index.js#L2-L3
If omitting a module ID, the following TS error occurs:
```console
$ npm run lint:types
> stylelint@13.12.0 lint:types
> tsc
lib/formatters/index.js:6:11 - error TS2554: Expected 1 arguments, but got 0.
6  compact: importLazy(() => require('./compactFormatter'))(),
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/import-lazy/index.d.ts:24:5
24 ): (moduleId: string) => T;
~~~~~~~~~~~~~~~~
An argument for 'moduleId' was not provided.
Found 1 error.
```
See:
- https://github.com/stylelint/stylelint/issues/4399#issuecomment-803565238
- …

Use built-in type definitions of `import-lazy`

---

lib/rules/color-named/index.js
lib/rules/declaration-property-unit-allowed-list/README.md
lib/rules/declaration-property-unit-allowed-list/__tests__/index.js
lib/rules/declaration-property-unit-allowed-list/index.js

Resolves #5140
This should help support SCSS functions as well, such as the `lighten` color function.

Add ignore: ["inside-function"] to declaration-property-unit-allowed-list

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/no-irregular-whitespace/README.md
lib/rules/no-irregular-whitespace/__tests__/index.js
lib/rules/no-irregular-whitespace/index.js

This PR proposes an implementation for `no-irregular-whitespace` rule, which has been previously approved for implementation in the referenced issue.
Closes #5201

new rule: no-irregular-whitespace

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/selector-disallowed-list/README.md
lib/rules/selector-disallowed-list/__tests__/index.js
lib/rules/selector-disallowed-list/index.js

Have added a new `selector-disallowed-list` rule as discussed in issue [#5116](https://github.com/stylelint/stylelint/issues/5116) .

Add selector-disallowed-list rule

---

lib/rules/selector-attribute-quotes/README.md
lib/rules/selector-attribute-quotes/__tests__/index.js
lib/rules/selector-attribute-quotes/index.js
lib/utils/getRuleSelector.js

Have added autofix to `selector-attribute-quotes` rule as dicussed in issue [#5211](https://github.com/stylelint/stylelint/issues/5211) 
Some of the unit tests can be a bit confusing. They cover pretty unusual but valid selectors:
```css
[href=te\'s\"t] { }
[href=\"test\"] { }
[href=\'test\'] { }
[href="te'st"] { }
[href='te"st'] { }
[href='te\'st'] { }
[href="te\"st"] { }
```

Add autofix to selector-attribute-quotes

---

lib/rules/length-zero-no-unit/__tests__/index.js
lib/rules/length-zero-no-unit/index.js
lib/utils/getAtRuleParams.js
lib/utils/setAtRuleParams.js

Closes #5255
It makes use of patterns found in our more recent rules.

Fix trailing zeroes being removed by autofix in length-zero-no-unit

---

lib/__tests__/cli.test.js

This refactoring aims to make the code more readable by reducing duplication.
E.g.
```diff
-replaceBackslashes(path.join(fixturesPath, 'config-block-no-empty.json')),
+fixturesPath('config-block-no-empty.json'),
```
Preparation for #5265

Refactor cli.test.js

---

.github/workflows/testing.yml

Node.js 16 has been recently released. See also:
- https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70
- https://nodejs.org/en/blog/release/v16.0.0
- https://github.com/nodejs/Release#release-schedule
According to the release schedule, Node.js 16 will be LTS on **2021-10-26**.
None.

Add test against Node.js 16

---

lib/__tests__/standalone-fix.test.js
package-lock.json
package.json

- Remove the `del` package that will be needless.
- Use async/await syntax for readability. (#4881)
- Fix CSS code indent for consistency.
`del` is still in `package-lock.json` as a sub-dependency of `np`:
```console
$ npm ls del
stylelint@13.13.0 /Users/masafumi.koba/git/stylelint/stylelint
└─┬ np@7.4.0
└── del@6.0.0
```

Refactor `lib/__tests__/standalone-fix.test.js`

---

lib/rules/no-invalid-position-at-import-rule/__tests__/index.js
lib/rules/no-invalid-position-at-import-rule/index.js

Closes #5263
Switches the logic around so that the `invalidPosition` flag is set when a standard syntax rule or at-rule (that isn't `charset` or another `import`) is encountered.
It maps neatly onto [the spec](https://drafts.csswg.org/css-cascade/#at-import):
> Any `@import` rules must precede all other valid at-rules and style rules in a style sheet (ignoring `@charset`), or else the `@import` rule is invalid.

Fix false positives for dollar variables in no-invalid-position-at-import-rule

---

lib/__tests__/cli.test.js
lib/__tests__/fixtures/default-severity-warning.json
lib/cli.js

I think stylelint should output any error or warning messages to STDERR instead of STDOUT.
Because users should expect that *piping* is available.
For example, here is an example of using the `jq` command:
```console
$ stylelint --formatter=json --max-warnings=0 a.css | jq .
Max warnings exceeded: 1 found. 0 allowed
[
{
"source": "/tmp/a.css",
"deprecations": [],
"invalidOptionWarnings": [],
"parseErrors": [],
"errored": false,
"warnings": [
{
"line": 1,
"column": 2,
"rule": "block-no-empty",
"severity": "warning",
"text": "Unexpected empty block (block-no-empty)"
}
]
}
]
```
Fix #5265 
In addition, I have inserted `EOL` at the beginning of the warning message so that users can …

Fix invalid json for max warnings option

---

lib/__tests__/ignore.test.js

This change aims to improve the test code readability via async/await syntax or Jest's matchers.
(avoiding callbacks as much possible)
See also <https://jestjs.io/docs/asynchronous>
I think it easier to view the diff if using ["Hide whitespace changes"](https://github.com/stylelint/stylelint/pull/5281/files?w=1).

Refactor `lib/__tests__/ignore.test.js`

---

lib/__tests__/ignoreDisables.test.js

This change aims to improve the test code readability via async/await syntax.
(avoiding callbacks as much possible)
See also <https://jestjs.io/docs/asynchronous>
I think it easier to view the diff if using ["Hide whitespace changes"](https://github.com/stylelint/stylelint/pull/5283/files?w=1).

Refactor `lib/__tests__/ignoreDisables.test.js`

---

lib/__tests__/normalizeRuleSettings-integration.test.js

- Reduce callbacks as much as possible via `async/await` syntax. (see also <https://jestjs.io/docs/asynchronous>)
- Reduce duplication via a new utility `fixture()`.

Refactor `lib/__tests__/normalizeRuleSettings-integration.test.js`

---

lib/__tests__/message.test.js

Reduce callbacks as much as possible via `async/await` syntax.
(see also <https://jestjs.io/docs/asynchronous>)

Refactor `lib/__tests__/message.test.js`

---

lib/__tests__/invalidScopeDisables.test.js

- Reduce callbacks as much as possible via `async/await` syntax. (see also <https://jestjs.io/docs/asynchronous>)
- ~~Replace the use of `stripIndent()` with `trim()`. (avoiding indentation in template string literals)~~
- Re-indent template string literals with TABs.
It's easier to review the diffs if using ["Hide whitespace changes"](https://github.com/stylelint/stylelint/pull/5285/files?w=1).

Refactor `lib/__tests__/invalidScopeDisables.test.js`

---

lib/__tests__/integration.test.js

- Reduce callbacks as much as possible via `async/await` syntax. (see also <https://jestjs.io/docs/asynchronous>)
- Unify indentation of tested CSS-like code for readability.
- Add a utility function to reduce duplication.
It's easier to review the diffs if using ["Hide whitespace changes"](https://github.com/stylelint/stylelint/pull/5284/files?w=1).

Refactor `lib/__tests__/integration.test.js`

---

lib/__tests__/needlessDisables.test.js

- Reduce callbacks as much as possible via `async/await` syntax. (see also <https://jestjs.io/docs/asynchronous>)
- ~~Replace the use of `stripIndent()` with `trim()`. (avoiding indentation in template string literals)~~
- Reindent template string literals for consistency.
It's easier to review the diffs if using ["Hide whitespace changes"](https://github.com/stylelint/stylelint/pull/5287/files?w=1).

Refactor `lib/__tests__/needlessDisables.test.js`

---

lib/__tests__/plugins.test.js

Reduce callbacks as much as possible via `async/await` syntax.
(see also <https://jestjs.io/docs/asynchronous>)
A part of #4881 
I recommend viewing the diffs by ["Hide whitespace changes"](https://github.com/stylelint/stylelint/pull/5300/files?diff=unified&w=1).

Refactor `lib/__tests__/plugins.test.js`

---

lib/rules/string-no-newline/index.js

Relates to https://github.com/stylelint/stylelint/pull/5304
The opening quote doesn't seem to be included in the `leftContext` anymore, so we need to account for it.

Fix invalid position for attribute selector

---

lib/__tests__/plugins.test.js
lib/__tests__/standalone-cache.test.js
lib/__tests__/standalone-fix.test.js
lib/__tests__/standalone-formatter.test.js
lib/__tests__/standalone-syntax.test.js
lib/__tests__/standalone.test.js
lib/getPostcssResult.js
lib/utils/__tests__/isMap.test.js
package-lock.json
package.json
system-tests/systemTestUtils.js

Closes #5271
I hope it's ok that I've picked up this issue. It seemed like a small one to pick up. I've followed some existing converstions to fs/promises found in the repo. These look like:
```javascript
const { promises: fs } = require('fs');
```
When these are converted to ESM, they are simpler to do than the alternative `const fs = require('fs').promises`.
```javascript
import { promises as fs } from 'fs';
```
In later versions of node the alternative is available:
```javascript
import fs from 'node:fs/promises';
```
but node 12 does not support `'node:fs/promises'` or `'fs/promises'` as imports as later versions do.
I've targeted this PR at the v14 branch.

Update async calls to fs to use fs/promises (#5271)

---

lib/__tests__/standalone-cache.test.js

- Reduce redundant callbacks via `async/await` syntax. (#4881)
- Use `fs.existsSync()` instead of `fs.access()`.
See <https://nodejs.org/api/fs.html#fs_fs_existssync_path>
- Fix the disabled test. (#5309)
- Inline redundant local variables.
- Make expectations using `typeof` more accurate.
Fix #5309
This PR's base branch is `v14`.

Refactor `lib/__tests__/standalone-cache.test.js`

---

lib/rules/length-zero-no-unit/__tests__/index.js
lib/rules/length-zero-no-unit/index.js

Closes #4831
Closes #5024
Implements https://github.com/stylelint/stylelint/pull/5024#issuecomment-826058241

Fix false positives for flex in length-zero-no-unit

---

lib/utils/isAutoprefixable.js

Follow-up of #5312
See also <https://github.com/stylelint/stylelint/pull/5312/files#r636018013> for details. Thanks to @victor-homyakov! 👏🏼  
This PR aims to remove invalid prefixed property values with `-webkit- old`, e.g. `-webkit- oldlinear-gradient`.
We can produce the new list of values as below:
`package.json`:
```json
{
"dependencies": {
"autoprefixer": "10.2.5"
}
}
```
`index.js`:
```js
const autoprefixer = require('autoprefixer');
const Browsers = require('autoprefixer/lib/browsers');
const Prefixes = require('autoprefixer/lib/prefixes');
const utils = require('autoprefixer/lib/utils');
const prefixes = new Prefixes(autoprefixer.data.prefixes, new …
```

Remove invalid `-webkit- old***` from `isAutoprefixable()`

---

lib/assignDisabledRanges.js
lib/formatters/verboseFormatter.js
lib/normalizeAllRuleSettings.js
lib/normalizeRuleSettings.js
lib/printConfig.js
lib/reportDisables.js
lib/rules/max-line-length/index.js
lib/rules/no-duplicate-selectors/index.js
lib/rules/property-no-unknown/index.js
lib/rules/selector-class-pattern/index.js
lib/rules/selector-max-type/index.js
lib/rules/string-quotes/index.js
lib/standalone.js
lib/utils/getNextNonSharedLineCommentNode.js
lib/utils/getPreviousNonSharedLineCommentNode.js
lib/utils/isAfterStandardPropertyDeclaration.js
lib/utils/isBlocklessAtRuleAfterSameNameBlocklessAtRule.js
lib/utils/report.js
lib/utils/validateOptions.js
types/stylelint/index.d.ts

Ref #4412.
Most of the code is self-explanatory. I replaced the simpler uses of `_.get` and `_.set` with native code.
I had to change a couple of `array.forEach` loops to regular `for … of array` loops to make `tsc` happy. I also updated the JSDoc types in a couple places for the same reason.

Refactor to remove some uses of `_.get` and `_.set`

---

docs/user-guide/rules/list.md
lib/rules/color-hex-alpha/README.md
lib/rules/color-hex-alpha/__tests__/index.js
lib/rules/color-hex-alpha/index.js
lib/rules/index.js

Closes https://github.com/stylelint/stylelint/pull/4891
Closes https://github.com/stylelint/stylelint/issues/4880
Implements the remaining requested changes in https://github.com/stylelint/stylelint/pull/4891.
Most of the tests were failing, so refactored to tidy things up and fixed the bugs.

Add color-hex-alpha rule

---

docs/user-guide/rules/list.md
lib/rules/custom-property-no-missing-var-function/README.md
lib/rules/custom-property-no-missing-var-function/__tests__/index.js
lib/rules/custom-property-no-missing-var-function/index.js
lib/rules/index.js

Closes #5000
Closes #5044
This replaces #5044.
I've thought about this rule on and off for a while now. I thought I'd unpacked it all in https://github.com/stylelint/stylelint/issues/5000#issuecomment-713702408, but there's more.
From the [`<dashed-ident>` spec](https://drafts.csswg.org/css-values-4/#dashed-idents):
> Some contexts accept both author-defined identifiers and CSS-defined identifiers. If not handled carefully, this can result in difficulties adding new CSS-defined values; UAs have to study existing usage and gamble that there are sufficiently few author-defined identifiers in use matching the new CSS-defined one, so giving the new value a special CSS-defined meaning …

Add custom-property-no-missing-var-function rule

---

lib/lintPostcssResult.js
lib/postcssPlugin.js
lib/rules/function-whitespace-after/index.js
lib/rules/linebreaks/index.js
lib/rules/max-empty-lines/index.js
lib/rules/media-feature-name-case/index.js
lib/rules/media-feature-parentheses-space-inside/index.js
lib/rules/selector-attribute-brackets-space-inside/index.js
lib/rules/selector-attribute-operator-space-after/index.js
lib/rules/selector-attribute-operator-space-before/index.js
lib/rules/selector-type-case/index.js
lib/utils/declarationValueIndex.js
lib/utils/getAtRuleParams.js
lib/utils/getDeclarationValue.js
lib/utils/getNextNonSharedLineCommentNode.js
lib/utils/getPreviousNonSharedLineCommentNode.js
lib/utils/getRuleSelector.js
lib/utils/isCustomPropertySet.js
lib/utils/isSharedLineComment.js
lib/utils/isStandardSyntaxRule.js
lib/utils/setAtRuleParams.js
lib/utils/setDeclarationValue.js

Ref #4412.
Most of the code is self-explanatory. I replaced the remaining uses of `_.get` and `_.set` with native code.
I had to cast to `any` in a few places to get around the fact that the TypeScript definitions don't include all the properties that we use.

Refactor to remove remaining uses of `_.get` and `_.set`

---

types/stylelint/index.d.ts

Closes #4899.
Relatively short PR that follows up on the change made in #4897. Pretty sure this is a quick and simple change, but let me know if I've missed anything!

Removes DisableReportRange.unusedRule from types

---

lib/formatters/verboseFormatter.js

Ref #4412.
Since `_.groupBy` is used twice in this file and only in this file, I avoided repeating code by adding a `groupBy` function to this file.

Refactor to remove `_.groupBy`

---

lib/__tests__/defaultSeverity.test.js
lib/__tests__/ignoreDisables.test.js
lib/__tests__/postcssPlugin.test.js
lib/index.js
lib/lintPostcssResult.js
lib/postcssPlugin.js
lib/standalone.js
types/stylelint/index.d.ts

Related to #4942
That was easier than I though. Basically I needed to change only our PostCSS plugin part to Visitors API to avoid warnings in tests. Nothing changes in execution order.
I think for us to embrace Visitors API in rules many changes needs to be done. Currently `stylelint` is not a PostCSS plugin. It uses PostCSS internals like `LazyResult` to go around PostCSS API. And then we call rule functions, which looks like PostCSS 7- plugins, but not exactly. So we don't use PostCSS API to parse code and run rules as plugins.
Project to use Visitors API could be a big refactor, and change in how stylelint works internally. I think we can do it after `v14` release.

Migrate stylelint PostCSS plugin to Visitors API

---

lib/rules/function-url-no-scheme-relative/index.js
lib/rules/function-url-scheme-allowed-list/index.js
lib/rules/function-url-scheme-disallowed-list/index.js

Ref #4412.
The regular expression `/^[ '"]+|[ '"]+$/g` matches one or more space, `'`, or `"` characters at the beginning or end of the string. Therefore, `string.replace(/^[ '"]+|[ '"]+$/g, '')` is equivalent to `_.trim(string, ' \'"')`.
`string.trim()` is a built-in function that removes whitespace, so `string.trim()` is equivalent to `_.trim(string, ' ')`.

Refactor to remove `_.trim`

---

lib/utils/checkAgainstRule.js
lib/utils/eachDeclarationBlock.js
lib/utils/functionArgumentsSearch.js
lib/utils/parseSelector.js
lib/utils/ruleMessages.js
lib/utils/transformSelector.js

A part of #4496
This refactoring makes abstract function types more specific, such as just `Function`.
I believe this will help code changes for ESM.
Note:
- Some files to be refactored similarly are still left, like `lib/utils/validateOptions.js`.
- This document has been helpful to me:
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

Refactor to more specific function types

---

lib/rules/declaration-block-no-redundant-longhand-properties/index.js
lib/rules/named-grid-areas-no-invalid/utils/findNotContiguousOrRectangular.js
lib/utils/__tests__/arrayEqual.test.js
lib/utils/arrayEqual.js
lib/utils/validateOptions.js

Ref #4412.
Since all uses of `_.isEqual` are comparing two arrays, I added a simple utility function to compare arrays.

Refactor to remove `_.isEqual`

---

lib/augmentConfig.js
lib/testUtils/mergeTestDescriptions.js
package-lock.json
package.json

Ref #4412.
`_.merge` replaces values at each index (`_.merge([1, 2], [3])` becomes `[3, 2]`). The `replaceSameIndex` array merging function in [`lib/augmentConfig.js`](https://github.com/stylelint/stylelint/pull/5369/files#diff-231823848e62de25699c7b9a8e92b05cc45aaf489c7c1fa417286295d37fcdf6) causes `deepmerge` to use that strategy.
`deepmerge` defaults to concatenating arrays, so the `mergeCustomizer` function used with `_.mergeWith` in [`lib/testUtils/mergeTestDescriptions.js`](https://github.com/stylelint/stylelint/pull/5369/files#diff-124f7773abf544ee51d0acd57be0e09ecf1636008b085830434668f0a1a4adb5) can simply be replaced with the default behavior of `deepmerge`.

Refactor to remove `_.merge` and `_.mergeWith`

---

lib/utils/validateOptions.js

- Improve types avoiding `any`
- Use `for...of` instead of `forEach` (`continue` is clearer than `return`)
- Use `flat()` instead of `[].concat()` idiom (avoiding type errors)

Refactor `validateOptions()` utility

---

lib/rules/property-no-unknown/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxDeclaration.test.js
lib/utils/isStandardSyntaxDeclaration.js

Fix false positives for Less maps in property-no-unknown

---

lib/rules/block-closing-brace-empty-line-before/index.js
lib/rules/block-closing-brace-newline-after/index.js
lib/rules/block-closing-brace-newline-before/index.js
lib/rules/block-closing-brace-space-after/index.js
lib/rules/block-closing-brace-space-before/index.js
lib/rules/block-no-empty/index.js
lib/rules/block-opening-brace-newline-after/index.js
lib/rules/block-opening-brace-newline-before/index.js
lib/rules/block-opening-brace-space-after/index.js
lib/rules/block-opening-brace-space-before/index.js
lib/utils/__tests__/blockString.test.js
lib/utils/addEmptyLineAfter.js
lib/utils/addEmptyLineBefore.js
lib/utils/blockString.js
lib/utils/removeEmptyLinesAfter.js

(see also #5418)
This change removes `// @ts-nocheck` from the `block-*` rules.
In addition, it improves the types of some utilities.

Refactor to improve types for `block-*` rules

---

lib/reference/keywordSets.js

This is a new media query added to CSS Media Queries Level 5 to utilize the contrast preference operating systems provide.
Closes #5427
Please see issue #5427

Fix false positives for prefers-contrast in media-feature-name-no-unknown

---

.github/dependabot.yml

See #5439
Currently, we have mainly developed on the `v14` branch.
See also:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit
**Note: This PR's base branch should be `master`.**

Disable Dependabot on default branch

---

.github/dependabot.yml

See #5439 and #5452
This change is a retry of PR #5439 and also a revert of PR #5452.
Maybe, `target-branch: v14` should be set on the `master` branch, not `v14`.
Note: This PR's base branch should be set to `master`.

Set `target-branch:v14` for Dependabot again

---

lib/reference/namedColorData.js
lib/rules/color-function-notation/index.js
lib/rules/color-hex-alpha/index.js
lib/rules/color-hex-case/index.js
lib/rules/color-hex-length/index.js
lib/rules/color-named/generateColorFuncs.js
lib/rules/color-named/index.js
lib/rules/color-no-hex/index.js
lib/rules/color-no-invalid-hex/index.js

(see also #5426)
This change removes `// @ts-nocheck` from the `color-*` rules.
In addition, it improves the types of some utilities.

Refactor to improve types for `color-*` rules

---

lib/rules/custom-media-pattern/index.js
lib/rules/custom-property-empty-line-before/index.js
lib/rules/custom-property-no-missing-var-function/index.js
lib/rules/custom-property-pattern/index.js

This change removes `// @ts-nocheck` from the `custom-*` rules.

Refactor to improve types for `custom-*` rules

---

.github/workflows/linting.yml
.github/workflows/testing.yml

None.
Also, this change sets `cache: npm` (available since v2.2.0). See below:
- https://github.com/actions/setup-node/releases/tag/v2.2.0
- https://github.com/actions/setup-node#caching-packages-dependencies

Bump actions/setup-node from v1 to v2

---

.github/dependabot.yml

See <https://github.com/stylelint/stylelint/pull/5481#issuecomment-899056059>
Note: `versioning-strategy` is unsupported for `github-actions`.
See also:
- https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

Add GitHub Actions for Dependabot configuration

---

lib/rules/declaration-bang-space-after/index.js
lib/rules/declaration-bang-space-before/index.js
lib/rules/declarationBangSpaceChecker.js

Part of #4496
This change removes `// @ts-nocheck` from the `declaration-bang-space-*` rules.
Also, it improves the `declarationBangSpaceChecker()` utility.

Refactor to improve types for `declaration-bang-space-*` rules

---

lib/reference/shorthandData.js
lib/rules/declaration-block-no-duplicate-custom-properties/index.js
lib/rules/declaration-block-no-duplicate-properties/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js
lib/rules/declaration-block-no-shorthand-property-overrides/index.js
lib/rules/declaration-block-semicolon-newline-after/index.js
lib/rules/declaration-block-semicolon-newline-before/index.js
lib/rules/declaration-block-semicolon-space-after/index.js
lib/rules/declaration-block-semicolon-space-before/index.js
lib/rules/declaration-block-single-line-max-declarations/index.js
lib/rules/declaration-block-trailing-semicolon/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `declaration-block-*` rules.

Refactor to improve types for `declaration-block-*` rules

---

lib/rules/declaration-bang-space-after/index.js
lib/rules/declaration-bang-space-before/index.js
lib/rules/declaration-colon-newline-after/index.js
lib/rules/declaration-colon-space-after/index.js
lib/rules/declaration-colon-space-before/index.js
lib/rules/declaration-empty-line-before/index.js
lib/rules/declaration-no-important/index.js
lib/rules/declaration-property-unit-allowed-list/index.js
lib/rules/declaration-property-unit-disallowed-list/index.js
lib/rules/declaration-property-value-allowed-list/index.js
lib/rules/declaration-property-value-disallowed-list/index.js
lib/rules/declarationBangSpaceChecker.js
lib/rules/declarationColonSpaceChecker.js
types/stylelint/index.d.ts

Part of #4496
This change removes  `// @ts-nocheck` from the remaining `declaration-*` rules.
Also, this adds 2 type parameters to the `StylelintRule` type to pass the type-check.

Refactor to improve types for `declaration-*` rules

---

lib/rules/font-family-name-quotes/index.js
lib/rules/font-family-no-duplicate-names/index.js
lib/rules/font-family-no-missing-generic-family-keyword/index.js
lib/rules/font-weight-notation/index.js
lib/utils/findFontFamily.js

Part of #4496
This change removes  `// @ts-nocheck` from the `font-*` rules.

Refactor to improve types for `font-*` rules

---

lib/rules/hue-degree-notation/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `hue-*` rules.

Refactor to improve types for `hue-*` rules

---

lib/rules/indentation/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `indentation` rule.
But, it uses `// @ts-expect-error` to suppress TypeScript errors that I cannot resolve.

Refactor to improve types for `indentation` rule

---

lib/rules/keyframe-declaration-no-important/index.js
lib/rules/keyframes-name-pattern/index.js
lib/rules/length-zero-no-unit/index.js
lib/rules/linebreaks/index.js

Part of #4496
This change removes `// @ts-nocheck` from the following rules:
- `keyframe-declaration-no-important`
- `keyframes-name-pattern`
- `length-zero-no-unit`
- `linebreaks`

Refactor to improve types for some rules

---

lib/rules/media-feature-colon-space-after/index.js
lib/rules/media-feature-colon-space-before/index.js
lib/rules/mediaFeatureColonSpaceChecker.js

Part of #4496
This change removes `// @ts-nocheck` from the `media-feature-colon-*` rules.

Refactor to improve types for `media-feature-colon-*` rules

---

lib/rules/max-empty-lines/index.js
lib/rules/max-line-length/index.js
lib/rules/max-nesting-depth/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `max-*` rules.

Refactor to improve types for `max-*` rules

---

lib/rules/media-query-list-comma-newline-after/index.js
lib/rules/media-query-list-comma-newline-before/index.js
lib/rules/media-query-list-comma-space-after/index.js
lib/rules/media-query-list-comma-space-before/index.js
lib/rules/mediaQueryListCommaWhitespaceChecker.js

Part of #4496
This change removes `// @ts-nocheck` from the `media-query-*` rules.

Refactor to improve types for `media-query-*` rules

---

lib/rules/findMediaOperator.js
lib/rules/media-feature-parentheses-space-inside/index.js
lib/rules/media-feature-range-operator-space-after/index.js
lib/rules/media-feature-range-operator-space-before/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `media-feature-*` rules.

Refactor to improve types for `media-feature-*` rules

---

lib/rules/named-grid-areas-no-invalid/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `named-grid-areas-no-invalid` rule.

Refactor to improve types for `named-grid-areas-no-invalid` rule

---

lib/rules/named-grid-areas-no-invalid/__tests__/index.js
lib/rules/named-grid-areas-no-invalid/index.js

Ref: https://github.com/stylelint/stylelint/pull/5513#pullrequestreview-746590742
[`grid`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) and [`grid-template`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template).

Fix false negatives for grid shorthands in named-grid-areas-no-invalid

---

lib/rules/unit-no-unknown/__tests__/index.js
lib/rules/unit-no-unknown/index.js

PR is related to discussion in #5500 - introduce isStandardAtRule. 

Refactor atrule statement in unit-no-unknown

---

docs/user-guide/configure.md
lib/__tests__/applyOverrides.test.js
lib/__tests__/fixtures/config-overrides/extending-plugin-and-one-rule.json
lib/__tests__/fixtures/config-overrides/extending-simple-rule.json
lib/__tests__/fixtures/config-overrides/plugin-and-one-rule.json
lib/__tests__/fixtures/config-overrides/simple-rule.json
lib/__tests__/fixtures/config-overrides/style.css
lib/__tests__/fixtures/config-overrides/style.module.css
lib/__tests__/fixtures/config-overrides/testPrintConfig/.stylelintrc
lib/__tests__/fixtures/config-overrides/testPrintConfig/style.css
lib/__tests__/overrides.test.js
lib/__tests__/printConfig.test.js
lib/augmentConfig.js
lib/createStylelint.js
lib/createStylelintResult.js
lib/getConfigForFile.js
lib/isPathIgnored.js
lib/lintSource.js
lib/printConfig.js
types/stylelint/index.d.ts

Closes #3128.
It took quite some time to figure out how config resolutions works. Codebase is very tangled in my opinion :(
For every linted file we produce new config from initial config. All overrides are resolved and applied on a config and file gets normal config with no `overrides` property.
I took `overrides` docs from [ESLint documentation](https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns) with some modifications.
Interesting thing that all properties that regular config support, are supported by overrides. So when we https://github.com/stylelint/stylelint/issues/5142 is done, all options would be working automatically …

Add `overrides` option to config (#3128)

---

lib/rules/no-descending-specificity/index.js
lib/utils/nodeContextLookup.js
types/postcss-resolve-nested-selector/index.d.ts

Part of #4496
This change removes `// @ts-nocheck` from the `no-descending-specificity` rule.
Also, this adds the types for `postcss-resolve-nested-selector` and improves the types of `lib/utils/nodeContextLookup.js`.

Refactor to improve types for `no-descending-specificity` rule

---

lib/rules/no-invalid-position-at-import-rule/README.md
lib/rules/no-invalid-position-at-import-rule/__tests__/index.js
lib/rules/no-invalid-position-at-import-rule/index.js

Add ignoreAtRules option to no-invalid-position-at-import

---

lib/rules/indentation/index.js

Fixes #5128.
RegExp in question was added in https://github.com/stylelint/stylelint/pull/3557 for `baseIndentLevel` and it is only for HTML and CSS-in-JS files. Since we don't support these syntaxes and tests are skipped, no tests are failing :)
In fact we have no running tests for `baseIndentLevel`.

Fix ReDoS issue (#5128)

---

lib/__tests__/fixtures/custom-parser.js
lib/__tests__/fixtures/custom-syntax.js
lib/__tests__/standalone-syntax.test.js
lib/augmentConfig.js
lib/getPostcssResult.js
lib/lintSource.js
types/stylelint/index.d.ts

Closes #4843.
It was easier than I though :) Two previous PRs I made recently definitely helped :)
---
Something that we might need to document somewhere or changes. Probably I had to write this in `overrides` PR.
It is true for v13 (except `overrides`) and for all options which could be specified in config, API, and CLI.
Priority of options:
1. `overrides` in config.
2. Option specified in CLI/API.
3. Option in config.
For example, if we have this config:
```json
{
"customSyntax": "postcss-sass",
"rules": {
"block-no-empty": true
},
"overrides": [{
"files": "*.css",
"customSyntax": "postcss-safe-parser"
}]
}
```
And run stylelint like this:
```
stylelint --custom-syntax …
```

Add `customSyntax` option to configuration object (#4843)

---

.github/dependabot.yml
docs/user-guide/configure.md
lib/__tests__/standalone-fix.test.js
lib/lintPostcssResult.js
lib/standalone.js
lib/utils/validateOptions.js
types/stylelint/index.d.ts

>  Which issue, if any, is this issue related to? 
Closes #5431 
no

Add disableFix secondary option

---

lib/rules/no-duplicate-at-import-rules/index.js
lib/rules/no-duplicate-selectors/index.js
types/normalize-selector/index.d.ts

Part of #4496
This change removes `// @ts-nocheck` from the `no-duplicate-*` rules.
Also, this adds the type definition for the [`normalize-selector`](http://github.com/getify/normalize-selector) package.

Refactor to improve types for `no-duplicate-*` rules

---

lib/augmentConfig.js
lib/isPathIgnored.js
package-lock.json
package.json

See https://github.com/stylelint/stylelint/pull/5541#issuecomment-921656346
This change replaces the [`slash`](https://github.com/sindresorhus/slash) package with the [`normalize-path`](https://github.com/jonschlinkert/normalize-path) package. It just removes `slash`.

Refactor to remove `slash` package

---

docs/user-guide/usage/options.md
lib/__tests__/cli.test.js
lib/__tests__/plugins.test.js
lib/__tests__/standalone-quiet.test.js
lib/__tests__/standalone.test.js
lib/assignDisabledRanges.js
lib/augmentConfig.js
lib/cli.js
lib/createStylelint.js
lib/createStylelintResult.js
lib/descriptionlessDisables.js
lib/getConfigForFile.js
lib/getPostcssResult.js
lib/invalidScopeDisables.js
lib/isPathIgnored.js
lib/lintSource.js
lib/needlessDisables.js
lib/normalizeAllRuleSettings.js
lib/normalizeRuleSettings.js
lib/prepareReturnValue.js
lib/printConfig.js
lib/standalone.js
types/stylelint/index.d.ts

Related to #5529, but not closes it.
Refactored as much as possible to async-await in core. Also noticed some improvements to code.
Accidentally found that `quite` flag in Node.js API didn't work. It's probably worked only in CLI only for a long time, even thought stylelint have it since [v2.0.0](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#200). This option wasn't even documented. I fixed it and added tests. *UPD:* found that there is an issue #4476 :)

Add `quiet` option to Node.js API

---

package.json

This allows the other scripts to finish instead of the process exiting when any error is first encountered in any of the scripts.
BTW @jeddy3 the v14 isn't protected, not sure if it's intentional :)

lint script: add `--continue-on-error`

---

lib/utils/isCounterIncrementCustomIdentValue.js
lib/utils/isCounterResetCustomIdentValue.js

I believe `10` is meant to be used here. Either way, I think the ESLint config should have the rule enabled to catch these :)

Refactor to add missing radix

---

lib/createStylelint.js
lib/getConfigForFile.js

See https://github.com/stylelint/stylelint/issues/5291#issuecomment-921846766
This change aims to make the ESM migration easier.
`__dirname` is used only for testing, so I think there are no problems to replace it.

Refactor to replace `__dirname` with `process.cwd()` in runtime code

---

lib/cli.js

Removing the extra `require` may make the ESM migration easier. See <https://github.com/stylelint/stylelint/issues/5291#issuecomment-920778090>.
- Remove the `pkg` option of `meow`. By default, `meow` finds the closest `package.json`.
See <https://github.com/sindresorhus/meow/blob/v9.0.0/readme.md#pkg>
- Change `@ts-ignore` to `@ts-expect-error`.

Refactor `cli.js` a bit

---

lib/augmentConfig.js
lib/getConfigForFile.js
types/stylelint/index.d.ts

Part of #4496
This refactoring does:
- fix the `// @ts-ignore` comment for `cosmiconfig`
- improve the `CosmiconfigResult` type renaming `StylelintCosmiconfigResult`
See also <https://github.com/davidtheclark/cosmiconfig/blob/v7.0.1/src/types.ts#L6-L10>

Refactor to fix `cosmiconfig` type error

---

lib/createStylelint.js
lib/getConfigForFile.js
lib/standalone.js
types/stylelint/index.d.ts

Part of #4496
This refactoring mainly improves the `StylelintInternalApi` type:
- remove needless properties
- make some properties stricter
- remove extra type annotations

Refactor to improve types for `StylelintInternalApi`

---

lib/utils/isStandardSyntaxDeclaration.js

Refactor to fix `@ts-ignore` in `isStandardSyntaxDeclaration()`

---

lib/formatters/stringFormatter.js
package-lock.json
package.json

Related to PR #5560
This refactoring replaces the `log-symbols` package with a custom implementation to remove the dependency on the `chalk` package as a sub-dependency.
(its direct dependency was removed with PR #5560)
Note that this custom implementation does not have a fallback like `log-symbols` which supports Unicode unsupported environments.
See also:
- https://github.com/sindresorhus/log-symbols/blob/v5.0.0/index.js

Refactor to replace `log-symbols` with custom implementation

---

.github/ISSUE_TEMPLATE/REPORT_A_DOCS_ISSUE.yml
.github/ISSUE_TEMPLATE/REQUEST_A_FEATURE.yml

Ref https://github.com/stylelint/.github/tree/main/.github/ISSUE_TEMPLATE
Sadly, the other templates aren't inherited if we override one of them. Although, It makes sense that this is the behaviour.
I'm going to quick merge this to fix up the template choice menu.

Add uninherited templates

---

lib/utils/__tests__/isStandardSyntaxDeclaration.test.js
lib/utils/isStandardSyntaxDeclaration.js

Closes #5639.
Adds a condition to the SCSS maps & lists check to ensure it's not used in cases like `height: (0);`.

Fix false positives for values wrapped in parentheses in declaration-empty-line-before

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/rule-selector-property-disallowed-list/README.md
lib/rules/rule-selector-property-disallowed-list/__tests__/index.js
lib/rules/rule-selector-property-disallowed-list/index.js

The new rule rule-selector-property-disallowed-list that is mentioned in #5433 has been added.
@jeddy3 I see that the branch `v14` has been merged and my previous [PR #5489](https://github.com/stylelint/stylelint/pull/5489), targeted to that branch, has been closed. So, I am creating this one to the `main` branch. 
I made [the change](https://github.com/stylelint/stylelint/pull/5489#pullrequestreview-780769606) that you asked me to do in comments to the previous PR. Namely, added a new test which checks multiple errors in one CSS block.
---
Closes #5433

Add rule-selector-property-disallowed-list

---

lib/__tests__/fixtures/config-overrides/at-rule-no-unknown.json
lib/__tests__/fixtures/config-overrides/indent4.json
lib/__tests__/fixtures/config-overrides/indent8.json
lib/__tests__/fixtures/config-overrides/scss.json
lib/__tests__/fixtures/config-overrides/style.scss
lib/__tests__/overrides.test.js
lib/augmentConfig.js
lib/createStylelint.js

Fix extending rules within overrides

---

lib/rules/no-eol-whitespace/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `no-eol-whitespace` rule and refactors the rule code for type-safety.

Refactor to improve types for `no-eol-whitespace` rule

---

lib/rules/no-empty-first-line/index.js
lib/rules/no-empty-source/index.js

Part of #4496
This change removes `// @ts-nocheck` from the `no-empty-*` rules.

Refactor to improve types for `no-empty-*` rules

---

docs/user-guide/configure.md

This is a documentation fix to repair links that should link to [https://github.com/stylelint/stylelint/tree/main/docs](https://github.com/stylelint/stylelint/tree/main/docs), but currently links to the root directory of the page.
It's self explanatory.

Fix id links in documentation for the customSyntax feature

---

CHANGELOG.md
lib/utils/configurationError.js
types/stylelint/index.d.ts

Adds the ConfigurationError type. Currently, we [define this type downstream](https://github.com/stylelint/vscode-stylelint/blob/77c0719/types/index.d.ts#L68-L73) since it isn't defined in Stylelint, but it really belongs here.

Add `ConfigurationError` type

---

lib/__tests__/cli.test.js
lib/__tests__/standalone-globs.test.js
lib/__tests__/writeOutputFile.test.js
lib/rules/named-grid-areas-no-invalid/utils/__tests__/isRectangular.test.js
lib/utils/__tests__/validateOptions.test.js
lib/utils/__tests__/vendor.test.js
package-lock.json
package.json

Not an issue, but part of the discussion in #5645.
This PR slightly took on scope creep (from the initial ask to just update `eslint-shared-config` to major version 15. Here's my thought process:
1. First, I bumped the above
2. Then, this causes an error with `eslint-plugin-jest`. I could resolve this by manually reinstalling it as a dev dependency. **I'm not sure if this is the right move**; if it isn't, let me know and I can move this commit out of the PR.
3. Finally, I address the newly enabled [`jest/prefer-to-be`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-to-be.md) rule, which was a simple find-and-replace.
Let me know if we'd prefer …

Pre-work to update to ESLint 8

---

lib/utils/beforeBlockString.js
lib/utils/blockString.js
lib/utils/hasBlock.js

Fixes the type error on #5689
Instead of `import('postcss').Rule | import('postcss').AtRule`, this refactoring uses the `import('postcss').Container` type.
This type includes also `import('postcss').Root` so has more flexibility. 
See the type definitions of PostCSS below:
- `Container` - https://github.com/postcss/postcss/blob/77c2e73/lib/container.d.ts#L23-L30
- `AtRule` - https://github.com/postcss/postcss/blob/77c2e73/lib/at-rule.d.ts#L73
- `Rule` - https://github.com/postcss/postcss/blob/77c2e73/lib/rule.d.ts#L66
- `Root` - https://github.com/postcss/postcss/blob/77c2e73/lib/root.d.ts#L51

Refactor to use PostCSS `Container` type for more flexibility

---

lib/rules/color-no-invalid-hex/__tests__/index.js
lib/rules/color-no-invalid-hex/index.js
lib/utils/__tests__/isStandardSyntaxDeclaration.test.js
lib/utils/__tests__/isStandardSyntaxHexColor.test.js
lib/utils/isStandardSyntaxDeclaration.js
lib/utils/isStandardSyntaxHexColor.js

Fix false positives for maps in property-no-unknown

---

lib/rules/declaration-bang-space-before/__tests__/index.js
lib/rules/declaration-block-no-duplicate-custom-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.js
lib/rules/declaration-empty-line-before/__tests__/index.js
lib/rules/function-url-no-scheme-relative/__tests__/index.js
lib/rules/function-url-quotes/__tests__/index.js
lib/rules/indentation/__tests__/html.js
lib/rules/indentation/index.js
lib/rules/max-empty-lines/__tests__/index.js
lib/rules/max-empty-lines/index.js
lib/rules/max-line-length/__tests__/index.js
lib/rules/no-empty-source/__tests__/index.js
lib/rules/no-eol-whitespace/__tests__/index.js
lib/rules/no-extra-semicolons/__tests__/index.js
lib/rules/no-missing-end-of-source-newline/__tests__/index.js
lib/rules/property-no-unknown/__tests__/index.js
lib/rules/string-no-newline/__tests__/index.js
lib/rules/unicode-bom/__tests__/index.js
package-lock.json
package.json

This is a follow up to issue #5289, because PR #5297 did not replace `syntax: 'html'` and `syntax: 'css-in-js'` in rules tests. Those test-cases were disabled instead, and some of those were broken at the same time by accidentally removing some whitespace, where it was required for the tests.
The first and second commits replace `syntax: ...` everywhere and remove the `skip: true` in those cases. The third commit brings back the accidentally removed whitespace. After that, a few tests still fail:
- the indentation and max-empty-lines rules were using `raws.beforeStart` and `raws.afterEnd`. Not sure where those came from (`postcss-syntax` maybe?), but it seems they should be replace with `raws.codeBefore` and `raws.codeAfter`. (fourth commit)
- the declaration-empty-line-before rule seems …

Fix TypeError for baseIndentLevel: 1 option and vue file in indentation

---

.gitignore
lib/reference/keywordSets.js
lib/rules/selector-type-case/__tests__/index.js
lib/rules/selector-type-case/index.js

[SVG elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element) with mixed case (e.g. "foreignObject") should be ignored by the "selector-type-case" rule.
Closes #5712
Added `.idea` to `.gitignore`. Let me know if a separate PR should be done for this.

Fix false positives for SVG type selectors in selector-type-case (#5712)

---

lib/rules/declaration-empty-line-before/__tests__/index.js
lib/rules/declaration-empty-line-before/index.js

This is taken out of #5657 to be able to merge the agreed-on parts ahead of other stuff.
The first 3 commits are from that yet unmerged PR right now, the change is only in the 4th commit. After re-enabling those tests by replacing the `syntax: 'html'` with `customSyntax`, those two tests would still fail and were left skipped in #5657.
The fix seems simple enough, but needs some improvement regarding typescript typing.

Fix support for HTML files in declaration-empty-line-before

---

docs/developer-guide/syntaxes.md

Document requiring custom syntaxes in shared configs

---

docs/user-guide/usage/node-api.md
lib/__tests__/resolveConfig.test.js
lib/index.js
lib/printConfig.js
lib/resolveConfig.js
types/stylelint/index.d.ts
types/stylelint/type-test.ts

Closes #5723 
Allows resolving the effective configuration for a given file, similar to `--print-config` on the CLI.

Add `resolveConfig` to Node.js API

---

package.json

Unsure if you all want these in the coverage report, so if you do, feel free to drop the PR :)

Jest: ignore __tests__ and testUtils from coverage

---

.github/workflows/testing.yml
codecov.yml

Closes #5748
This change aims to migrate Coveralls to Codecov as a test coverage SaaS.
See also:
- https://github.com/codecov/codecov-action
- https://github.com/apps/codecov

Migrate Coveralls to Codecov

---

lib/rules/declaration-block-no-duplicate-properties/README.md

To follow the decision in #5592. They were overlooked in #5609.

Replace "violations" with "problems" in `declaration-block-no-duplicate-properties` rule doc

---

lib/getPostcssResult.js

Closes #5761
I'm not sure if the added `console.error` is beneficial. What are your thoughts?

Fix showing of incorrect missing package in customSyntax require handling 

---

README.md

Refactor to use markdown syntax for images in README

---

lib/rules/indentation/__tests__/document-with-roots.js
lib/rules/indentation/index.js

Fixes #5767 
I changed `beforeStart` to `codeBefore`  and added a truthy check

Fix TypeError for syntaxes that use Document in indentation

---

lib/__tests__/ignore.test.js
lib/standalone.js
lib/utils/getFileIgnorer.js

None.
This PR aims to reduce duplication using the `ignore` package. The duplication is in both `lib/standalone.js` and `lib/utils/getFileIgnorer.js`.

Refactor `getFileIgnorer()` to reduce duplication

---

lib/rules/no-extra-semicolons/index.js

Part of #4496
- Narrow the scope of some local variables.

Refactor to improve types for `no-extra-semicolons` rule

---

lib/rules/color-function-notation/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxColorFunction.test.js
lib/utils/isStandardSyntaxColorFunction.js

Fix false positives for variables and color functions in color-function-notation

---

docs/user-guide/rules/combine.md

Closes #5796 
Changed - `value-list-comma-newline-after`: `"always"|"always-multi-line|"never-multi-line"` to - `value-list-comma-newline-after`: `"always"|"always-multi-line"|"never-multi-line"` in combine.md

corrected a typo in combine.md

---

lib/rules/no-invalid-double-slash-comments/index.js
lib/rules/no-invalid-position-at-import-rule/index.js

Part of #4496
- Improve the code a bit for more type-consistency.

Refactor to improve types for `no-invalid-*` rules

---

lib/rules/no-irregular-whitespace/__tests__/index.js
lib/rules/no-irregular-whitespace/index.js

Part of #4496
- Convert the internal logic to a more type-safe way; not using `***Schema` objects for nodes, but accessing directly to each node's properties.

Refactor to improve types for `no-irregular-whitespace` rule

---

lib/rules/no-missing-end-of-source-newline/index.js
lib/rules/no-unknown-animations/index.js

Refactor to improve types for `no-missing-*` / `no-unknown-*` rules

---

lib/rules/number-leading-zero/index.js
lib/rules/number-max-precision/index.js
lib/rules/number-no-trailing-zeros/index.js
lib/utils/optionsMatches.js

Part of #4496
- Improve the code a bit for type-safety.

Refactor to improve types for `number-*` rules

---

lib/rules/property-allowed-list/index.js
lib/rules/property-case/index.js
lib/rules/property-disallowed-list/index.js
lib/rules/property-no-unknown/index.js
lib/rules/property-no-vendor-prefix/index.js

Refactor to improve types for `property-*` rules

---

lib/rules/rule-empty-line-before/index.js

Refactor to improve types for `rule-empty-line-before` rule

---

lib/rules/selector-attribute-brackets-space-inside/index.js
lib/rules/selector-attribute-name-disallowed-list/index.js
lib/rules/selector-attribute-operator-allowed-list/index.js
lib/rules/selector-attribute-operator-disallowed-list/index.js
lib/rules/selector-attribute-operator-space-after/index.js
lib/rules/selector-attribute-operator-space-before/index.js
lib/rules/selector-attribute-quotes/index.js
lib/rules/selectorAttributeOperatorSpaceChecker.js
lib/utils/parseSelector.js

Refactor to improve types for `selector-attribute-*` rules

---

docs/user-guide/rules/list.md

Ref: https://github.com/stylelint/stylelint/issues/5674
Ref: https://github.com/stylelint/stylelint/issues/5153
A pretty printer like Prettier [seems to address is](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgPgB0oACEgQxOBIG4SATJEgIzppoF9izUB6TXARAAaEBAAOMAJbR0yUOQBOiiAHcACkoRyU5HKvJY5o5ovJgA1nBgBlcgFs4AGSlQ4yAGZ70cE2cvWNuLmrgDmyDCKAK6+IHD2zHD09ElO5FChUeShcABiEIr25DDSGcgg5FEwECIgABYw9jgA6nVS8OjBYHA22u1SAG7tWOVg6MYgrj6KMOpmoUWe3rEAVugAHjZheACKURDwSzg+osGK0+UNTbXiiq4wzVL0MHXIABwADKcqPs1m4uVbnBpgN3KIAI77eBzCQ6CroAC0biSSVqijgkKk6Lm2UWSC8x1iPnsUgi0SJ2zgewO7nxy1EMHIzEez1eSAATAyzFIcGEAMIQex4uLoACstSiPgAKkydASTiABjEAJJQFKwGxgO6SACCaps2DwRx8HA4QA).

Document no-extra-semicolons as stylistic

---

lib/reference/keywordSets.js
lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.js

Fix false positives for revert and revert-layer in font-family-no-missing-generic-family-keyword

---

lib/rules/selector-class-pattern/index.js
lib/rules/selector-combinator-allowed-list/index.js
lib/rules/selector-combinator-disallowed-list/index.js
lib/rules/selector-combinator-space-after/index.js
lib/rules/selector-combinator-space-before/index.js
lib/rules/selector-descendant-combinator-no-non-space/index.js
lib/rules/selector-disallowed-list/index.js
lib/rules/selector-id-pattern/index.js
lib/rules/selectorCombinatorSpaceChecker.js
package-lock.json
package.json

Refactor to improve types for `selector-(class|combinator|descendant|disallowed|id)-*` rules

---

lib/rules/selector-list-comma-newline-after/index.js
lib/rules/selector-list-comma-newline-before/index.js
lib/rules/selector-list-comma-space-after/index.js
lib/rules/selector-list-comma-space-before/index.js
lib/rules/selectorListCommaWhitespaceChecker.js

Refactor to improve types for `selector-list-*` rules

---

lib/rules/selector-max-attribute/index.js
lib/rules/selector-max-class/index.js
lib/rules/selector-max-combinators/index.js
lib/rules/selector-max-compound-selectors/index.js
lib/rules/selector-max-empty-lines/index.js
lib/rules/selector-max-id/index.js
lib/rules/selector-max-pseudo-class/index.js
lib/rules/selector-max-specificity/index.js
lib/rules/selector-max-type/index.js
lib/rules/selector-max-universal/index.js
lib/utils/isContextFunctionalPseudoClass.js

Refactor to improve types for `selector-max-*` rules

---

lib/lintPostcssResult.js

None, just a bit refactoring for `lib/lintPostcssResult.js`.
This refactoring improves the rule iteration code:
- More accurate variable names
- Avoid redundant `Object.keys()` in loop

Refactor `lib/lintPostcssResult.js`

---

.github/workflows/testing.yml

None.
Currently, our CI jobs for Windows fail due to npm@8.4 (see <https://github.com/npm/cli/issues/4341>). So this change downgrades to npm@8.3 as a workaround.
E.g. https://github.com/npm/cli/issues/4341

Downgrade npm to 8.3 as workaround

---

lib/rules/value-no-vendor-prefix/index.js

- Part of #5499
Replacing `style-search` with [`postcss-value-parser`](https://github.com/TrySound/postcss-value-parser).

Refactor to replace `style-search` for `value-no-vendor-prefix` rule

---

lib/rules/rangeContextNodeParser.js

Part of #5499
Replacing `style-search` with `postcss-value-parser`.

Refactor to replace `style-search` for `rangeContextNodeParser()`

---

docs/developer-guide/plugins.md

I think the snippet is understandable even with the typo, but worth fixing nonetheless.

Fix typo / inconsistency in stylelint.rules API docs for plugins

---

docs/user-guide/rules/list.md
lib/rules/function-no-unknown/README.md
lib/rules/function-no-unknown/__tests__/index.js
lib/rules/function-no-unknown/index.js
lib/rules/index.js
lib/utils/__tests__/isCustomFunction.test.js
lib/utils/isCustomFunction.js
package-lock.json
package.json

Closes #5853
"No, it's self-explanatory."

Add function-no-unknown

---

lib/rules/custom-property-pattern/__tests__/index.js
lib/rules/custom-property-pattern/index.js

Closes #3655
The following problem has not been solved.
You will need to create another isuue.
> The following is a false positive (as it's invalid syntax) and should be ignored by this rule. We > can either squish that bug within this issue or create a separate issue for it.
>  ```--invalid-custom-property-variable: #fff;```
https://github.com/stylelint/stylelint/issues/3655#issuecomment-420942480

Fix false negatives for custom properties within var() in custom-property-pattern

---

lib/rules/function-linear-gradient-no-nonstandard-direction/index.js
lib/utils/__tests__/functionArgumentsSearch.test.js
lib/utils/functionArgumentsSearch.js

Closes #5499 
(I think this PR is the last one of #5499)
Replacing `style-search` with `postcss-value-parser`.

Refactor to replace `style-search` for `functionArgumentsSearch()`

---

codecov.yml

See https://github.com/stylelint/stylelint/pull/5891#issuecomment-1031201884
See https://docs.codecov.com/docs/commit-status

Configure coverage threshold on commit status

---

lib/rules/no-descending-specificity/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxSelector.test.js
lib/utils/isStandardSyntaxSelector.js

Closes #5739
The following triggered a parse error in the selector parser.
```less
a,
// comment2
b {}
```

Fix parseError for double-slash comments within selector lists in no-descending-specificity

---

lib/rules/alpha-value-notation/index.js
lib/rules/number-max-precision/__tests__/index.js
lib/rules/number-max-precision/index.js
lib/rules/selector-attribute-quotes/index.js
types/stylelint/index.d.ts
types/stylelint/type-test.ts

None.
Making the argument type more accurate. (avoiding `any`)

Refactor to improve types for `ruleMessages()`

---

docs/user-guide/integrations/other.md

Closes #5373. The integration should be working the same as before, the only difference is in how it’s installed. I’ve also spent more time to document common customisations in the README.
For people wanting to switch to this, here are [migration instructions](https://github.com/thibaudcolas/pre-commit-stylelint#migrating-from-awebdeveloperpre-commit-stylelint).

Document new pre-commit integration

---

lib/rules/function-no-unknown/README.md
lib/rules/function-no-unknown/__tests__/index.js
lib/rules/function-no-unknown/index.js

Add `ignoreFunctions` option to `function-no-unknown`

---

lib/rules/function-no-unknown/index.js
package-lock.json
package.json

- Closes #5904
- Closes #5918
This change bumps `css-functions-list` from 3.0.0 to 3.0.1.
See https://github.com/niksy/css-functions-list/releases/tag/v3.0.1
```shell
npm i css-functions-list
```
`css-functions-list@3.0.1` improves handling paths on Windows. So, it's no longer necessary to use `URL` in our code.

Fix ENOENT and TypeErrors in `function-no-unknown`

---

lib/rules/function-no-unknown/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxFunction.test.js
lib/utils/isStandardSyntaxFunction.js

This PR tweaks `function-no-unknown` so that `ignoreFunctions` are also supported in the custom properties syntax (e.g. `--primary-color: #{custom-mixin(#fff)};`
Fixes https://github.com/stylelint/stylelint/issues/5913

Fix false positives for interpolation in `function-no-unknown`

---

lib/normalizeRuleSettings.js
lib/rules/at-rule-property-required-list/index.js
lib/rules/declaration-property-unit-allowed-list/index.js
lib/rules/declaration-property-unit-disallowed-list/index.js
lib/rules/declaration-property-value-allowed-list/index.js
lib/rules/declaration-property-value-disallowed-list/index.js
lib/rules/media-feature-name-value-allowed-list/index.js
lib/rules/rule-selector-property-disallowed-list/index.js
lib/utils/validateObjectWithArrayProps.js
lib/utils/validateOptions.js
lib/utils/validateTypes.js

None, as it's a refactoring.
- Add a type-guard function `isPlainObject()` to our `validateTypes.js` module.
- The new type-guard function uses internally the `is-plain-object` package.
- Use the new function via `validateTypes.js`, instead of directly using `is-plain-object`.

Refactor to add type-guard of `isPlainObject()`

---

lib/utils/__tests__/validateOptions.test.js
lib/utils/validateOptions.js

None.
When an object is embedded into a message, it's not user-friendly. E.g.
```
Invalid option value "[object Object]" for rule "foo"
```

Fix clarity of invalid option warning message for objects

---

lib/rules/at-rule-property-required-list/index.js
lib/rules/declaration-property-unit-allowed-list/index.js
lib/rules/declaration-property-unit-disallowed-list/index.js
lib/rules/declaration-property-value-allowed-list/index.js
lib/rules/declaration-property-value-disallowed-list/index.js
lib/rules/media-feature-name-value-allowed-list/index.js
lib/rules/rule-selector-property-disallowed-list/index.js
lib/utils/__tests__/matchesStringOrRegExp.test.js
lib/utils/__tests__/optionsMatches.test.js
lib/utils/validateObjectWithArrayProps.js

None.
This change aims to tighten rule validations having object options like [`at-rule-property-required-list`](https://github.com/stylelint/stylelint/blob/f1ee719fe537bfa41b248df1bc7ae5528c153fff/lib/rules/at-rule-property-required-list/README.md#options).
For example, when the following configuration is given,
```json
{
"rules": {
"at-rule-property-required-list": {
"font-family": [1]
}
}
}
```
a validation error should be expected,
```
Invalid Option: Invalid option value "{"font-family":[1]}" for rule "at-rule-property-required-list"
```
but actually no errors.

Fix false negatives for invalid options in *-list

---

docs/user-guide/rules/list.md

If I'm not mistaken, it seems correct that `declaration-block-no-redundant-longhand-properties` is inside the *Declaration block* section, not *Declaration*.

Fix `declaration-block-*` position in rule list doc

---

lib/rules/custom-property-pattern/__tests__/index.js
lib/rules/custom-property-pattern/index.js

Fix false positives for interpolation in property name in custom-property-pattern

---

lib/reference/keywordSets.js

Closes #5173
check the commit message for details
prompted by https://github.com/stylelint/stylelint/issues/5205#issuecomment-1060017652

Fix false positives/negatives in selector-pseudo-class-no-unknown

---

lib/rules/comment-whitespace-inside/index.js
lib/rules/comment-word-disallowed-list/index.js
lib/rules/function-whitespace-after/index.js
lib/rules/max-line-length/__tests__/index.js
lib/rules/max-nesting-depth/index.js
lib/rules/selector-list-comma-newline-after/index.js

None, it's just a small refactoring.
The `String.prototype.substr()` method is deprecated.
This change replaces it with the `String.prototype.slice()` method.
See also:
- https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/substr
- https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/slice
`substr()` will be not found after this change:
```console
$ git grep -w substr || echo 'no match'
no match
```

Refactor to replace deprecated `String.prototype.substr()`

---

docs/user-guide/usage/node-api.md
docs/user-guide/usage/options.md

Closes https://github.com/stylelint/stylelint/issues/5964
No, it’s documentation related.

Document fix and output behaviour for Node.js API usage

---

lib/rules/custom-property-pattern/__tests__/index.js
lib/rules/custom-property-pattern/index.js

Closes #5972.
In the issue description, @jeddy3 mentions to check if `nodes` exists before restructuring. My understanding is that `nodes` will always exist, and the bug arises from if the array is empty (and thus, `nodes[0]` doesn't exist). ~~So, this approach checks if `nodes` is an empty array, and returns early if so.~~ So, this approach checks if `nodes[0]` exists instead.
I've also added a test case (that previously failed with the same error, and now is resolved).

Fix TypeError error "Cannot destructure property..." in custom-property-pattern

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/selector-not-notation/README.md
lib/rules/selector-not-notation/__tests__/index.js
lib/rules/selector-not-notation/index.js

#5974
read https://github.com/stylelint/stylelint/issues/5974#issuecomment-1071396510

Add selector-not-notation

---

lib/utils/__tests__/validateTypes.test.js
lib/utils/validateTypes.js
lib/utils/whitespaceChecker.js

Part of #5983
This refactoring does the following:
- Move utility functions in `lib/utils/whitespaceChecker.js` to `lib/utils/validateTypes.js`
- Add new utility functions to `validateTypes.js`
- Add a unit test for `validateTypes.js`
- Resolve type errors in `whitespaceChecker.js` via the `noUncheckedIndexedAccess` TypeScript compiler option
We can see the error resolution via the following commands:
```console
$ git checkout tsconfig-noUncheckedIndexedAccess -- tsconfig.json
$ npm run lint:types
```

Refactor to improve types for `validateTypes` and `whitespaceChecker`

---

lib/utils/checkInvalidCLIOptions.js

None, as it's a small refactoring.
This small refactoring aims to make `buildAllowedOptions()` more readable.
The number of loops is doubled (`Object.keys()` and `Object.values()`),
but it will not degrade performance since `allowedOptions` is a small array.

Refactor `lib/utils/checkInvalidCLIOptions.js`

---

lib/rules/font-weight-notation/README.md
lib/rules/font-weight-notation/__tests__/index.js
lib/rules/font-weight-notation/index.js

- Closes #3855
- Prepares for #5725
This change uses `postcss-value-parser` instead of `postcss.list.space()` for more accurate parsing.

Fix column position and ignore Sass function for `font-weight-notation`

---

lib/rules/selector-not-notation/index.js
lib/utils/validateTypes.js

Ref: #5983
We can confirm the improvements via the following command:
```shell
npm run lint:types -- --noUncheckedIndexedAccess | grep selector-not-notation
```

Refactor to improve type-check for `selector-not-notation`

---

lib/utils/__tests__/report.test.js
lib/utils/report.js

Closes #6015
This PR is modified so that stylelint-disable is enabled when the start line of the report matches.

Fix no-disable regression for some rules

---

docs/developer-guide/rules.md

A follow-up to #5972 and #5982. From the former:
> Follow-up PR to add "empty functions" to [commonly overlooked edge cases](https://stylelint.io/developer-guide/rules#commonly-overlooked-edge-cases).
---
N/A - pretty trivial. Let me know if a different example/location is preferred.

Add "empty functions" to commonly overlooked edge cases

---

lib/rules/property-allowed-list/README.md
lib/rules/property-allowed-list/__tests__/index.js
lib/rules/property-allowed-list/index.js
lib/rules/property-disallowed-list/README.md
lib/rules/property-disallowed-list/__tests__/index.js
lib/rules/property-disallowed-list/index.js
lib/utils/matchesStringOrRegExp.js

Closes https://github.com/stylelint/stylelint/issues/5981
The parameter types for matchesStringOrRegExp had to be fixed. It didn't include Array<string>.

 Add support for vendor prefixes in ﻿`property-*-list`

---

lib/rules/at-rule-no-unknown/__tests__/index.js
lib/rules/at-rule-no-unknown/index.js

Part of #5694
I think the range should be at an at-rule name, not an at-rule block. E.g.,
```css
@unknown (max-width: 960px) {}
/** ↑------↑ */
```

Fix end positions for `at-rule-no-unknown`

---

.github/workflows/testing.yml

None.
Node.js 18 recently [has been released](https://nodejs.org/uk/blog/announcements/v18-release-announce/). This version will be LTS in October 2022.

Add Node.js 18 to CI matrix

---

docs/user-guide/rules/list.md
lib/rules/index.js
lib/rules/keyframe-block-no-duplicate-selectors/README.md
lib/rules/keyframe-block-no-duplicate-selectors/__tests__/index.js
lib/rules/keyframe-block-no-duplicate-selectors/index.js

Closes #5991.
Still newish to the overall codebase! A couple of questions I had (and of course, general feedback is much appreciated):
1. Should I explicitly be handling case-insensitivity? Alternatively, should I document that the rule is case-sensitive (as of now)
2. How comprehensive are the test cases and documentation? I'm not sure if I'm missing any common cases where this would be a problem.
3. I've added vendored prefixes to the regex for finding keyframes as well as in the test cases - is this good practice?

Add `keyframe-block-no-duplicate-selectors`

---

lib/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js
lib/rules/function-linear-gradient-no-nonstandard-direction/index.js

None.
Thanks to @Mouvedia (https://github.com/stylelint/stylelint/commit/4b0f57d7b491342af1370b6f1222cb84c115e10c#r71832295), I can open this pull request. Thank you.

Fix false negative about `-ms-linear-gradient` in `function-linear-gradient-no-nonstandard-direction`

---

lib/rules/function-calc-no-unspaced-operator/README.md
lib/rules/function-calc-no-unspaced-operator/__tests__/index.js
lib/rules/function-calc-no-unspaced-operator/index.js

- Close #5695
- Close #6044 
This pull request does 2 major things:
- dropping the support of the `*` and `/` operators since they are not required (see also [`calc()` notes on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#notes))
- preventing a potential infinite-loop by mutating an array inside a loop (see also the [issue comment](https://github.com/stylelint/stylelint/issues/6044#issuecomment-11128788))

Fix false positives and memory leak for `function-calc-no-unspaced-operator`

---

lib/rules/no-duplicate-selectors/README.md

This change just corrects the position of `↑`.

Fix typo in `no-duplicate-selectors` doc

---

lib/rules/function-calc-no-unspaced-operator/__tests__/index.js
lib/rules/function-calc-no-unspaced-operator/index.js

Closes #6052
This pull request aims to fix false positives for non-standard variables (e.g. SCSS, Less, and so on.) in the `function-calc-no-unspaced-operator` rule.
I think [`isStandardSyntaxValue()`](https://github.com/stylelint/stylelint/blob/e017583128863ee75634cb15e721779163b571e5/lib/utils/isStandardSyntaxValue.js) is more appropriate than [`isStandardSyntaxMathFunction()`](https://github.com/stylelint/stylelint/blob/e017583128863ee75634cb15e721779163b571e5/lib/utils/isStandardSyntaxMathFunction.js) suggested on <https://github.com/stylelint/stylelint/issues/6052#issuecomment-1114004679> because `isStandardSyntaxMathFunction()` fails the cases using non-standard variables. …

Fix false positives for non-standard variables in `function-calc-no-unspaced-operator`

---

lib/rules/at-rule-no-vendor-prefix/README.md
lib/rules/media-feature-name-no-vendor-prefix/README.md
lib/rules/property-no-vendor-prefix/README.md
lib/rules/selector-no-vendor-prefix/README.md
lib/rules/value-no-vendor-prefix/README.md

Closes #5664.
I've applied the change to all 5 rules that have `*-no-vendor-prefix`. A bit unsure if the language makes sense for the `value-no-vendor-prefix` rule - is it possible for there to be duplicate values (I'm not sure what a duplicate value use-case would look like)? Happy to adjust this if there is better wording.

Document autofix behaviour better for `*-no-vendor-prefix`

---

lib/rules/no-invalid-double-slash-comments/__tests__/index.js
lib/rules/no-invalid-double-slash-comments/index.js
lib/rules/no-invalid-position-at-import-rule/__tests__/index.js
lib/rules/no-invalid-position-at-import-rule/index.js

Part of the umbrella issue #5694.
For `no-invalid-double-slash-comments`, there was one test case I was confused about:
```js
code: 'a, //div { color: pink; }',
description: 'between rules',
message: messages.rejected,
line: 1,
column: 1,
endLine: 1,
endColumn: 26,
```
I haven't changed the behaviour of this test case, but to me I'm not sure why it's `column: 1` - the comment starts at index `4` (where the double-slash is). I might be misunderstanding how this rule works, though!

Fix end positions for `no-invalid-*`

---

lib/rules/comment-empty-line-before/README.md

Unify wording in `comment-empty-line-before` doc

---

lib/rules/length-zero-no-unit/__tests__/index.js
lib/rules/length-zero-no-unit/index.js

Closes #6074
I tested these changes in the reproduction repository and
- works well with .0rem (.0rem -> 0)
- doesn't work with .0 (still .0 -> '')
So should we fix it for the second case? It doesn't seem to be the problem with this rule. @ybiquitous correct me if I'm wrong.

Fix `length-zero-no-unit` autofix for `.0` values

---

lib/rules/keyframe-declaration-no-important/README.md

Fix typo in `keyframe-declaration-no-important` doc

---

lib/rules/no-duplicate-selectors/__tests__/index.js
lib/rules/no-duplicate-selectors/index.js

Closes #6103
<del>
I'm getting the following error, so I have to add `skip: true` like the other test case for `postcss-css-in-js` above in the same test file:
```log
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
|     property 'nodes' -> object with constructor 'Array'
|     index 0 -> object with constructor 'Object'
--- property 'parent' closes the circle
at stringify (<anonymous>)
at writeChannelMessage (node:internal/child_process/serialization:127:20)
at process.target._send (node:internal/child_process:839:17)
at process.target.send (node:internal/child_process:739:19)
at reportSuccess …
```

fix: ignore non-standard selectors for rule no-duplicate-selectors

---

lib/rules/no-duplicate-selectors/__tests__/index.js
lib/rules/no-duplicate-selectors/index.js

Closes [#6110#issuecomment-1137211409](https://github.com/stylelint/stylelint/issues/6110#issuecomment-1137211409)

fix: `no-duplicate-selectors` false positives for SCSS/Less nested interpolations

---

lib/rules/time-min-milliseconds/README.md

Fix missing word in `time-min-milliseconds` doc

---

lib/rules/selector-max-id/README.md

Fix missing heading in `selector-max-id` doc

---

docs/developer-guide/plugins.md
docs/developer-guide/processors.md
docs/user-guide/usage/node-api.md

Arrow Function is now widely-used and becomes simpler code.
This change replaces `function` expressions with arrow functions in docs.

Use arrow functions in docs

---

lib/rules/selector-max-specificity/__tests__/index.js
lib/rules/selector-max-specificity/index.js

Closes #6139
This pull request aims to fix a `TypeError` raised when parsing `:nth-child` (or `:nth-last-child`) pseudo-classes without arguments in the `selector-max-specificity` rule.
Even if the `@csstools/selector-specificity` package would be updated to parse `:nth-child` without errors (see csstools/postcss-plugins#439), please note that it's necessary Stylelint may have own logic processing `:nth-child(...)`, in order to support `<complex-selector-list>` with the `ignoreSelectors` option, e.g. `:nth-child(even of .foo)`.
See also [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child#syntax):
```
:nth-child( <nth> [ of <complex-selector-list> ]? )
```

Fix false positives with `:nth-child` in `selector-max-specificity` rule

---

types/stylelint/index.d.ts
types/stylelint/type-test.ts

Currently, users writing custom rules and using `RuleMessageFunc` are required to handle all kinds of parameters with TypeScript's strict mode enabled. e.g.
```ts
const messages = utils.ruleMessages(ruleName, {
invalid: (rule: string) =>
`Failed to extract namespace from ${rule}. material/no-unused-` +
`imports Stylelint rule likely needs to be updated.`,
});
```
results in
```
tools/stylelint/no-unused-import.ts:7:12 - error TS2322: Type '(rule: string) => string' is not assignable to type 'string | RuleMessageFunc'.
Type '(rule: string) => string' is not assignable to type 'RuleMessageFunc'.
Types of parameters 'rule' and 'args' are incompatible.
Type 'string | number | boolean | RegExp' is not assignable to type 'string'.
7   invalid: (rule: string) =>
~~~~~~~~~~~~~~~~~
8     `Failed …
```

Fix rule message function type to not require users to handle all kind of arguments

---

lib/__tests__/printConfig.test.js
lib/__tests__/processors.test.js
lib/__tests__/reportDisables.test.js
lib/__tests__/reportUnknownRuleNames.test.js
lib/__tests__/standalone-deprecations.test.js
lib/__tests__/standalone-formatter.test.js
lib/__tests__/standalone-maxWarnings.test.js
lib/__tests__/standalone-quiet.test.js
lib/__tests__/standalone-syntax.test.js
lib/__tests__/standalone.test.js
lib/__tests__/stylelintignore-test/stylelintignore.test.js
lib/rules/linebreaks/__tests__/integration.test.js

Closes #4881
I had completely forgotten to work on #4881. 😅 
This pull request should be the last.
```console
$ git grep  -E '\.(then|catch|finally)' '**/*.test.js' || echo 'no match'
no match
```
Recommended view: [files?w=1](https://github.com/stylelint/stylelint/pull/6149/files?w=1)

Refactor to remove callbacks in test examples

---

lib/rules/unit-no-unknown/README.md
lib/rules/unit-no-unknown/__tests__/index.js

Part of umbrella issue #5523.
Tried to follow #5555 but used the foo, bar, baz naming conventions in the docs. Also updated tests to mostly match. Let me know if I should do something different.
In looking for custom unit constructs (mostly skimming the rule list), I only found them in `unit-no-unknown`. Let me know if I should add any others.

Use dashed indents in examples of custom unit constructs

---

docs/user-guide/rules/list.md
lib/reference/keywordSets.js
lib/rules/annotation-no-unknown/README.md
lib/rules/annotation-no-unknown/__tests__/index.js
lib/rules/annotation-no-unknown/index.js
lib/rules/index.js

Closes #4508.
A late turnaround on this one! I think there's probably a few missing things before this is mergeable.
Possible questions with my implementation:
- how should I be checking for nonstandard syntax? ex just at the declaration level?
- should `!important` be case-insensitive? on one hand, syntax highlighters and the literal reading of the spec only allow for lowercase, but it seems like Chrome respects any capitalization. 
- I've opted to include the `!` in the secondary options; is that too clunky?
- should I add any testcases for nonstandard syntax?

Add `annotation-no-unknown`

---

lib/reference/mathFunctions.js
lib/reference/shorthandData.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js
lib/rules/declaration-block-no-shorthand-property-overrides/index.js
lib/utils/isMathFunction.js

Ref: https://github.com/stylelint/stylelint/issues/6151#issuecomment-1161953568
This pull request is prepared for #6151, unifying reference data structures.

Refactor to use `Set` for `shorthandData` and `mathFunctions` types

---

docs/developer-guide/formatters.md
lib/__tests__/stylelintignore-test/stylelintignore.test.js
lib/formatters/__tests__/githubFormatter.test.js
lib/formatters/__tests__/prepareFormatterOutput.js
lib/formatters/githubFormatter.js
lib/formatters/verboseFormatter.js
lib/prepareReturnValue.js
system-tests/001/__snapshots__/fs.test.js.snap
system-tests/001/__snapshots__/no-fs.test.js.snap
system-tests/002/__snapshots__/fs.test.js.snap
system-tests/002/__snapshots__/no-fs.test.js.snap
system-tests/003/__snapshots__/fs.test.js.snap
system-tests/003/__snapshots__/no-fs.test.js.snap
system-tests/004/__snapshots__/fs.test.js.snap
system-tests/004/__snapshots__/no-fs.test.js.snap
types/stylelint/index.d.ts

Closes #6082
This pull request adds a new property `ruleMetadata` to the `LinterResult` type as a public API. The new property should make it easier to write a custom formatter using rule metadata.
Also, this change includes:
- refactor the `verboseFormatter` code by using the new property
- add a rule URL to the `githubFormatter` output. See the [demo](https://github.com/ybiquitous/stylelint-github-actions-formatter/pull/3/files) and screenshot:
- <img width="917" alt="Screen Shot 2022-06-22 at 0 37 33" src="https://user-images.githubusercontent.com/473530/174840473-f911c26f-2546-422e-9053-4cf5ec503e0b.png">

Add rule metadata to public `LinterResult` API

---

lib/__tests__/cli.test.js
lib/cli.js

Closes #5150.
Seems *too simple* - am I missing something?
Also, is this a breaking change? I did change the behaviour that was captured in a test.

Fix exit code when nothing is passed to stylelint command

---

lib/index.js
lib/reference/properties.js
lib/reference/shorthandData.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js
lib/rules/declaration-block-no-shorthand-property-overrides/index.js
types/stylelint/index.d.ts
types/stylelint/type-test.ts

- Closes #6151
- #6152
This pull request is following the suggestion below by @jeddy3 in <https://github.com/stylelint/stylelint/issues/6151#issuecomment-1160488202>:
> - align and expose data as it's requested (starting with the shorthand data)
The type definition is generated by the following script:
```js
const shorthandData = require("./lib/reference/shorthandData")
console.log('export type ShorthandData = {')
for (const key of Object.keys(shorthandData).sort()) {
console.log(`\t'${key}': Set<string>;`)
}
console.log('};')
```

Add shorthand properties reference to public API

---

lib/__tests__/fixtures/processor-fenced-blocks.js
lib/__tests__/fixtures/processor-triple-question-marks.js
lib/rules/max-line-length/index.js
package-lock.json
package.json

None.
We can replace `execall` with `String.prototype.matchAll()` which has been supported since Node.js v12.
See also:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
- https://github.com/sindresorhus/execall
FYI. We have supported Node.js v12+:
https://github.com/stylelint/stylelint/blob/0ffb27fa2dc01d46f9df96e5f2c9377b00b30a46/package.json#L192-L194

Refactor to remove `execall` dependency

---

lib/__tests__/cli.test.js
lib/cli.js
lib/utils/__tests__/getStdin.test.js
lib/utils/getStdin.js
package-lock.json
package.json

None.
The `get-stdin` package is a tiny library, so we can replace it with its utility and reduce an extra dependency.
Also, since the package is used only by `cli.js`, replacing it is easy.
See https://github.com/sindresorhus/get-stdin

Refactor to remove `get-stdin` dependency

---

lib/rules/declaration-property-value-allowed-list/__tests__/index.js
lib/rules/declaration-property-value-allowed-list/index.js

Closes #6187
This fix is similar to #6188.
See also https://github.com/stylelint/stylelint/issues/6187#issuecomment-1170618875

Fix false positives for multiple match in `declaration-property-value-allowed-list`

---

lib/rules/no-unknown-animations/__tests__/index.js
lib/utils/__tests__/findAnimationName.test.js
lib/utils/findAnimationName.js

Closes #5532.
This "early return" feels unnatural - I'm not even actually returning early, since I'm not breaking out of the AST walk. Any suggestions on how to make this cleaner?

Fix false positives for SCSS interpolation in `no-unknown-animations`

---

lib/rules/keyframe-selector-notation/README.md
lib/rules/keyframe-selector-notation/__tests__/index.js
lib/rules/keyframe-selector-notation/index.js

Closes #6191
It's necessary to call `.walkRules()` twice to get all selectors in a `@keyframes` block. In most cases, I don't believe there will not pay a performance penalty.

Add `percentage-unless-within-keyword-only-block` primary option to `keyframe-selector-notation`

---

lib/rules/selector-attribute-quotes/__tests__/index.js
lib/rules/selector-attribute-quotes/index.js

Fix `selector-attribute-quotes` end positions

---

lib/rules/selector-class-pattern/__tests__/index.js
lib/rules/selector-class-pattern/index.js

Part of #5694
This changes the implementation of `messages.expect` a bit:
```diff
- messages.expected('foo', /^[A-Z]+$/)
- Expected class selector ".${selector}" to match pattern "${pattern}"
+ messages.expected('.foo', /^[A-Z]+$/)
+ Expected class selector "${selector}" to match pattern "${pattern}"
```
Because I think it's clear to pass a full selector explicitly. The output message remains the same in both cases.

Fix `selector-class-pattern` end positions

---

.gitignore
docs/user-guide/usage/options.md
lib/__tests__/__mocks__/stylelint-test-custom-formatter.js
lib/__tests__/__snapshots__/cli.test.js.snap
lib/__tests__/cli.test.js
lib/__tests__/fixtures/formatters/customFormatter.js
lib/__tests__/resolveCustomFormatter.test.js
lib/cli.js
lib/resolveCustomFormatter.js

Add support for loading custom formatter from package

---

lib/rules/selector-id-pattern/__tests__/index.js
lib/rules/selector-id-pattern/index.js

Part of #5694
This change also performs a refactoring to pass a full selector to the `messages.expected()` function, instead of just a selector value. This refactoring is to make the function's caller code clearer:
```diff
- messages.expected('foo', /^[A-Z]+$/)
+ messages.expected('#foo', /^[A-Z]+$/)
```

Fix `selector-id-pattern` end positions

---

lib/__tests__/fixtures/plugin-async.js
lib/rules/selector-no-qualifying-type/index.js
lib/utils/__tests__/validateOptions.test.js
lib/utils/validateOptions.js

Closes #5091
see also #2027 #5221 #3516 #1953
~check the message of the first commit~
https://github.com/stylelint/stylelint/commit/101f2740f85315cb48f27714cfe4119b79beb6a3#diff-ea40f7b7d9827960e2d8e1590b37c7490648acb555d8fe8c22d0c2328449c95fR64

Add invalid rule primary option message for `false`

---

lib/rules/keyframe-selector-notation/README.md

Last two block code of [`keyframe-selector-notation`](https://stylelint.io/user-guide/rules/list/keyframe-selector-notation/#percentage-unless-within-keyword-only-block) are red, but there isn't error. I think it's because the _pattern_ is missing an _s_ (and it doesn't respect the pattern to put in green).

docs: add an 's' because there are several patterns

---

lib/rules/selector-no-vendor-prefix/__tests__/index.js
lib/rules/selector-no-vendor-prefix/index.js

Fix `selector-no-vendor-prefix` end positions

---

docs/developer-guide/plugins.md
lib/__tests__/fixtures/plugin-warn-about-foo.js
lib/__tests__/plugins.test.js
lib/createPlugin.js
types/stylelint/index.d.ts
types/stylelint/type-test.ts

Closes #6245
This PR mainly fixes the incorrect examples on the [plugin document](https://stylelint.io/developer-guide/plugins). Also, this improves the type definition of the `stylelint.createPlugin()` API, although it may be called *refactorings*.
The incorrect part on the doc is here: ⬇️ 
https://github.com/stylelint/stylelint/blob/e424be5eca77c5532b13147c4a7dad14085a4276/docs/developer-guide/plugins.md?plain=1#L53-L55
Because `stylelint.createPlugin()` returns an object `{ ruleName: string, rule: Function }`,
https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/lib/createPlugin.js#L10-L15
the following code using `module.exports` produces an …

Fix `plugins.md` document and `createPlugin` type definition

---

lib/rules/keyframes-name-pattern/__tests__/index.js
lib/rules/keyframes-name-pattern/index.js
lib/utils/__tests__/isStandardSyntaxKeyframesName.test.js
lib/utils/isStandardSyntaxKeyframesName.js

Fix false positives for interpolation in keyframes-name-pattern

---

lib/rules/shorthand-property-no-redundant-values/__tests__/index.js
lib/rules/shorthand-property-no-redundant-values/index.js

Part of #5694
This PR fixes the message to use double quotes for consistency with other rules:
```diff
- Unexpected longhand value '1px 1px' instead of '1px'
+ Unexpected longhand value "1px 1px" instead of "1px"
```
This also adds test cases for end positions (#5694).

Fix `shorthand-property-no-redundant-values` message

---

lib/rules/selector-max-id/README.md

Fix selector-max-id rule docs so it's parsed properly

---

docs/maintainer-guide/releases.md

The following JS snippet can create the URL:
```js
const params = new URLSearchParams();
params.append('title', 'Release {version}');
params.append('labels', 'status: needs discussion');
console.log(`https://github.com/stylelint/stylelint/issues/new?${params}`);
```
https://github.com/stylelint/stylelint/issues/new?title=Release+%7Bversion%7D&labels=status%3A+needs+discussion

Add parameters to a release issue URL

---

lib/rules/selector-max-universal/README.md
lib/rules/selector-max-universal/__tests__/index.js
lib/rules/selector-max-universal/index.js

Closes #5792
No, it's self-explanatory, I guess.

Add `ignoreAfterCombinators: []` to `selector-max-universal`

---

.changeset/calm-tables-hide.md
.changeset/chatty-eagles-act.md
.changeset/cold-peas-push.md
.changeset/cool-baboons-cross.md
.changeset/empty-humans-bake.md
.changeset/modern-mayflies-scream.md
.changeset/modern-plants-nail.md
.changeset/plenty-timers-learn.md
.changeset/serious-teachers-juggle.md
.changeset/shy-clouds-joke.md
.changeset/sour-socks-type.md
.changeset/wise-kiwis-repeat.md
CHANGELOG.md

See https://github.com/stylelint/stylelint/pull/6282#issuecomment-1221456083
This PR reverts `CHANGELOG.md` on aff9a8efe5923113e899d40b3bed0685d508697d for the existing release workflow. We'll try the new workflow in the next iteration.

Revert CHANGELOG.md and remove `.changeset/*.md` except for README.md

---

lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js

see stylelint/stylelint-config-standard#257
- a PR has been opened on stylelint-config-standard: stylelint/stylelint-config-standard#258
- ensure that stylelint and stylelint-config-standard are synced

Fix false negatives for SVG properties in alpha-value-notation

---

docs/maintainer-guide/issues.md

No, it's self-explanatory. See also https://github.com/stylelint/stylelint/labels

Fix typos in `maintainer-guide/issues.md`

---

.changeset/nice-lemons-reflect.md
docs/user-guide/rules/list.md
lib/rules/declaration-block-no-duplicate-properties/README.md
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-properties/index.js
system-tests/001/__snapshots__/fs.test.js.snap
system-tests/001/__snapshots__/no-fs.test.js.snap
system-tests/003/__snapshots__/fs.test.js.snap
system-tests/003/__snapshots__/no-fs.test.js.snap

Add autofix to declaration-block-no-duplicate-properties

---

docs/user-guide/integrations/editor.md

Wasn't obvious for Neovim users that the easiest option is using null-ls as this has built-in support for Stylelint. Added that to the list. 👍
> Is there anything in the PR that needs further explanation

Added null-ls option for Neovim users

---

lib/rules/annotation-no-unknown/README.md

I think this typo is causing a problem in stylelint.io page of the `annotation-no-unknown` rule.
The color of box-shadow in the code block  is red (invalid-pattern color) even though the pattern is not considered a problem.
https://stylelint.io/user-guide/rules/list/annotation-no-unknown/

Fix typo in annotation-no-unknown document

---

.changeset/big-crabs-tap.md
lib/rules/selector-pseudo-class-no-unknown/README.md
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
lib/rules/selector-pseudo-class-no-unknown/index.js

Part of #5523
While working on #5523, I notice the `selector-pseudo-class-no-unknown` rule doesn't support a real regex.

Add regex support for `ignorePseudoClasses` option of `selector-pseudo-class-no-unknown`

---

.changeset/silver-baboons-dress.md
lib/rules/selector-pseudo-element-no-unknown/README.md
lib/rules/selector-pseudo-element-no-unknown/__tests__/index.js
lib/rules/selector-pseudo-element-no-unknown/index.js

Part of #5523
Similar reason with #6316.

Add regex support for `ignorePseudoElements` option of `selector-pseudo-element-no-unknown`

---

.changeset/spicy-toes-rule.md
lib/reference/atKeywords.js
lib/reference/units.js
lib/rules/at-rule-no-unknown/__tests__/index.js

Fix false positives for container queries in `*-no-unknown`

---

.changeset/fast-papayas-dress.md
lib/rules/selector-type-case/README.md
lib/rules/selector-type-case/__tests__/index.js
lib/rules/selector-type-case/index.js

None.
The `ignoreTypes` option of the `selector-type-case` rule has supported a regex-like string already. Supporting also regex expressions in JS config files should be helpful.

Add regex support to `ignoreTypes` option of `selector-type-case`

---

.changeset/rotten-onions-occur.md
lib/rules/selector-no-vendor-prefix/README.md
lib/rules/selector-no-vendor-prefix/__tests__/index.js
lib/rules/selector-no-vendor-prefix/index.js

Similar to #6326
See the description on #6326.

Add regex support to `ignoreSelectors` option of `selector-no-vendor-prefix`

---

.github/workflows/releasing.yml

Ref: #6253
I notice [`changesets/action`](https://github.com/changesets) creates a release PR also in a forked repository, e.g., <https://github.com/kawaguchi1102/stylelint/pull/1>.
This PR adds a workaround to avoid the problem. See also https://github.com/changesets/action/issues/4#issuecomment-647322349

Stop creating release PR in forked repos

---

.changeset/famous-cobras-clean.md
lib/rules/font-family-name-quotes/__tests__/index.js
lib/rules/font-family-name-quotes/index.js

Closes #4154
I updated to change the timing of executing `isStandardSyntaxValue` to ignore problematic cases.
However, if `customSyntax` is not set to `'postcss-scss'`, `CssSyntaxError` is raised.
I think this error is correct because this bug is SCSS syntax.

Fix false positives for interpolation and shorthand in `font-family-name-quotes`

---

.changeset/unlucky-dolphins-fetch.md
lib/rules/selector-disallowed-list/README.md
lib/rules/selector-disallowed-list/__tests__/index.js
lib/rules/selector-disallowed-list/index.js

Closes #6294 
A bit of a shuffle, but I added an additional ```iterateThroughSelectorList``` flag which iterates through ruleNode.selectors rather than just the single ruleNode.selector or raw.selector.raw. The RegExp can get a bit unwieldy.
I consider the following ```.foo, .bar {}``` to be 2 separate selectors, so a dev may prefer to parse each of these individually ( ```.foo``` and ```.bar```) than to have to parse a string like ```.foo,\n.bar```

Add `ignore: ["inside-block"]` and `splitList` to selector-disallowed-list

---

.changeset/real-items-wait.md
docs/user-guide/usage/cli.md
docs/user-guide/usage/options.md
lib/__tests__/__snapshots__/cli.test.js.snap
lib/__tests__/cli.test.js
lib/__tests__/fixtures/ignore-2.txt
lib/__tests__/ignore.test.js
lib/__tests__/invalidScopeDisables.test.js
lib/__tests__/needlessDisables.test.js
lib/__tests__/postcssPlugin.test.js
lib/__tests__/stylelintignore-test/stylelintignore.test.js
lib/cli.js
lib/utils/getFileIgnorer.js
types/stylelint/index.d.ts
types/stylelint/type-test.ts

Closes #4680
Please let me know if I'm missing a unit test.

Add support for multiple `--ignore-path` flags

---

docs/developer-guide/syntaxes.md
docs/migration-guide/to-14.md
docs/user-guide/configure.md
docs/user-guide/errors.md
docs/user-guide/usage/cli.md

Closes #6346
I replaced the docs folder in my local [stylelint.io](https://github.com/stylelint/stylelint.io) and checked the page transitions.

Fix incorrect URL hashes in documents

---

.changeset/cool-zebras-sparkle.md
docs/user-guide/rules/list.md
lib/reference/keywords.js
lib/rules/font-weight-notation/README.md
lib/rules/font-weight-notation/__tests__/index.js
lib/rules/font-weight-notation/index.js
lib/utils/__tests__/isNumbery.test.js
lib/utils/isNumbery.js
system-tests/002/__snapshots__/fs.test.js.snap
system-tests/002/__snapshots__/no-fs.test.js.snap

Closes #3158
I've refactored the rule implementation much to support autofix:
- check each value node by the `postcss-value-parser` module
- unify some logic between the `font` and `font-weight` properties (though a few conditional branches remain)
- remove specific logic for the `@font-face` at-rule
Here is the code outline after the refactoring:
```js
root.walkDecls(/^font(-weight)?$/i, (decl) => {
const parsedValue = valueParser(getDeclarationValue(decl));
for (const [index, valueNode] of valueNodes.entries()) {
// checking each value node...
}
});
```

Add autofix to `font-weight-notation`

---

.changeset/eleven-monkeys-return.md
tsconfig.json
types/stylelint/index.d.ts

Fix type declarations for custom message arguments

---

.gitignore
lib/__tests__/extends.test.js
lib/__tests__/ignore.test.js
lib/__tests__/plugins.test.js
lib/__tests__/postcssPlugin.test.js
lib/__tests__/processors.test.js
lib/__tests__/standalone-cache.test.js
lib/__tests__/standalone-fix.test.js
lib/__tests__/standalone.test.js
lib/__tests__/stylelintignore-test/stylelintignore.test.js
lib/testUtils/removeFile.js
lib/testUtils/safeChdir.js

None.
New helpers aim to reduce duplication in the test code.

Refactor to add test utils

---

.changeset/mighty-apricots-cheat.md
docs/user-guide/usage/cli.md
docs/user-guide/usage/options.md
lib/__tests__/__snapshots__/cli.test.js.snap
lib/__tests__/cli.test.js
lib/__tests__/standalone-cache.test.js
lib/cli.js
lib/standalone.js
lib/utils/FileCache.js
types/stylelint/index.d.ts

Add cacheStrategy option

---

.changeset/nasty-tomatoes-confess.md
lib/reference/selectors.js

Fix `selector-pseudo-element-no-unknown` false positives for `::highlight` pseudo-element

---

package.json

None.
There is a file with `.mjs` extension: [`scripts/benchmark-rule.mjs`](https://github.com/stylelint/stylelint/blob/2d3a3fb37a76e2a34f0732a2239d1d350ceffb7a/scripts/benchmark-rule.mjs)

Fix lint settings to honor `.mjs` files

---

.changeset/old-moles-sort.md
lib/reference/units.js
lib/rules/unit-no-unknown/__tests__/index.js

Closes #6373
I've updated the unit list based on the ["CSS Values and Units Module Level 4" spec](https://w3c.github.io/csswg-drafts/css-values-4/#font-relative-lengths).

Fix `unit-no-unknown` false positives for font-relative length units

---

.github/workflows/preparing-github-release.yml
docs/maintainer-guide/releases.md
package.json
scripts/remark-changelog-to-github-release.mjs

Ref: https://github.com/stylelint/stylelint/issues/6343#issuecomment-1250353973
Ref: #6253
I believe this PR can omit the following step of releasing:
https://github.com/stylelint/stylelint/blob/eee9deb35190f46c5f964769d521fef5d7d1d7a8/docs/maintainer-guide/releases.md?plain=1#L16
This is not just a copy-and-paste of `CHANGELOG.md`. Instead, it rewrites user links to user mentions (e.g. `@ybiquitous`) so that the "Contributors" section should be displayed on a release page [like this](https://github.com/postcss/postcss/releases/tag/8.4.14).
But, one downside. This PR increase complexity: a remark script and a GitHub action. It may be too much for this automation. I'll close the …

Automate GitHub Release

---

package-lock.json
package.json

Ref: #6377
We no longer need to specify the `func-names` rule. Instead, the new version includes it.
See https://github.com/stylelint/eslint-config-stylelint/releases/tag/17.0.0

Bump eslint-config-stylelint from 16.0.0 to 17.0.0

---

lib/rules/property-no-vendor-prefix/README.md

Fix `property-no-vendor-prefix` example in doc

---

.changeset/poor-ducks-relate.md
lib/assignDisabledRanges.js
lib/rules/block-no-empty/__tests__/index.js
lib/rules/block-no-empty/index.js
lib/utils/__tests__/stylelintCommand.test.js
lib/utils/hasEmptyBlock.js
lib/utils/stylelintCommand.js

Closes #5388
As suggested in <https://github.com/stylelint/stylelint/issues/5388#issuecomment-879005796>, this PR extracts a new utility from `assignDisabledRanges.js`, and then it ignores a Stylelint command comment in the `block-no-empty` rule by using the new utility.

Fix `block-no-empty` false positives for `reportNeedlessDisables`

---

.changeset/strong-lions-listen.md
lib/utils/__tests__/report.test.js
lib/utils/report.js

Ref: #6312
The Node.js [`util.format()`](https://nodejs.org/api/util.html#utilformatformat-args) API can concatenate extra arguments to the result string. This behavior is not suitable for custom messages. So, this commit replace `util.format()` with our implementation.
> If there are more arguments passed to the `util.format()` method than the number of specifiers, the extra arguments are concatenated to the returned string, separated by spaces:
>
> ```js
> util.format('%s:%s', 'foo', 'bar', 'baz');
> // Returns: 'foo:bar baz'
> ```

Fix `printf`-like formatting for custom messages

---

.changeset/fix-unused-type-import.md
types/stylelint/index.d.ts

Fixes https://github.com/stylelint/stylelint/issues/6392
This type import was added in https://github.com/stylelint/stylelint/pull/6356, but during code review that PR was refactored to obviate the `file-entry-cache` types in the public API. The import was never removed. Keeping the import here results in [compilation errors](https://app.circleci.com/pipelines/github/palantir/blueprint/3156/workflows/9eda97ec-3a2f-4aa6-aa6c-89d5b65b8491/jobs/61694) for downstream consumers.
cc @jeddy3 @kimulaco

Fix TS compilation error due to needless `file-entry-cache` import

---

docs/user-guide/get-started.md
docs/user-guide/usage/cli.md

Closes #6395
As an aside, GitHub copilot wrote the example after I typed "if you are using npm scripts...". Was kinda cool to see 😆

Document using stylelint inside npm-scripts

---

CHANGELOG.md
docs/user-guide/rules.md
docs/user-guide/usage/options.md
lib/__tests__/standalone.test.js
lib/formatters/__tests__/jsonFormatter.test.js
lib/resolveConfig.js
lib/rules/at-rule-no-unknown/__tests__/index.js
lib/rules/color-hex-case/__tests__/index.js
lib/rules/comment-empty-line-before/__tests__/index.js
lib/rules/declaration-block-single-line-max-declarations/__tests__/index.js
lib/rules/function-linear-gradient-no-nonstandard-direction/README.md
lib/rules/selector-max-specificity/index.js
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
lib/rules/unit-no-unknown/__tests__/index.js
lib/utils/__tests__/findAnimationName.test.js
lib/utils/__tests__/functionArgumentsSearch.test.js
lib/utils/isOnlyWhitespace.js
types/stylelint/index.d.ts

Closes #6400
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/IoT-For-Beginners/commit/152f85d8f8ced0c5b63649a5e9fb622ee2d36705#commitcomment-86437888
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/stylelint/commit/bd2b632047e1b0d9e707e8ed7af4f2b7d50c642a
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

Fix spelling mistakes

---

lib/rules/shorthand-property-no-redundant-values/README.md

Document shorthand-property-no-redundant-values extended description

---

.changeset/yellow-seals-kick.md
lib/rules/shorthand-property-no-redundant-values/index.js

Fix shorthand-property-no-redundant-values message to be consistent

---

.changeset/fair-oranges-love.md
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js

Closes #6394
I think this CSS spec is often overlooked. So, I added a description and example to the docs. https://github.com/stylelint/stylelint/commit/94a21c3dd197144ac92c4803641b86c4fb6402c0

Fix `declaration-block-no-redundant-longhand-properties` false positives for `inherit` keyword

---

.github/workflows/code-scanning.yml
.github/workflows/releasing.yml
.github/workflows/testing.yml

Ref:
- #6409 
- #6311
- Add `v15` branch to the triggers
- Drop Node.js 12 from the matrix
- Collect test coverage on Node.js 18 (comming soon LTS)

Prepare v15 on CI

---

.changeset/nervous-insects-design.md
lib/__tests__/cli.test.js
lib/__tests__/standalone-syntax.test.js
lib/cli.js
lib/getPostcssResult.js
lib/standalone.js
types/stylelint/index.d.ts
types/stylelint/type-test.ts

Remove `syntax` option

---

package-lock.json
package.json

Close #6456
This PR's base branch is `main` instead of `v15`. Also, this commit is created by:
```shell
git cherry-pick 90e09c28cd6ead99b4236629b0740060d1c61092
```

Bump eslint from 8.26.0 to 8.27.0

---

.changeset/khaki-flowers-suffer.md
lib/utils/__tests__/report.test.js
lib/utils/report.js
types/stylelint/index.d.ts

This PR introduces the ability to report warnings with custom rule severities:
```js
stylelint.utils.report({ ruleName, severity: 'warning' })
```
My team is working on a rule that is used for both linting and gathering metrics on warnings and have encountered a need to set custom rule severities per report. In short our rule dynamically categorizes warnings and reports with a modified rule name that we target on an external metrics dashboard e.g.
```js
stylelint.utils.report({ ruleName: `${ruleName}/colors`, ... })
stylelint.utils.report({ ruleName: `${ruleName}/layout`, ... })
// etc.
```
However, because we report dynamically created rule names the warning's `severity` is set to `undefined`.
This small restructure and override mechanism gives us more programmatic control when handling …

Add support for reporting with custom severity

---

.github/workflows/testing.yml

I believe this PR should fix the CI failures with PR #6463.
See the announcement about npm v9:
https://github.blog/changelog/2022-11-09-npm-cli-v9-is-now-generally-available/
See the failed job:
https://github.com/stylelint/stylelint/actions/runs/3433111899

Use npm v8 instead of v9 on CI testing

---

.changeset/several-cucumbers-wonder.md
lib/rules/at-rule-disallowed-list/README.md
lib/rules/at-rule-disallowed-list/index.js
lib/rules/declaration-property-unit-disallowed-list/README.md
lib/rules/declaration-property-unit-disallowed-list/index.js
lib/rules/declaration-property-value-disallowed-list/README.md
lib/rules/declaration-property-value-disallowed-list/index.js
lib/rules/function-disallowed-list/README.md
lib/rules/function-disallowed-list/index.js
lib/rules/property-disallowed-list/README.md
lib/rules/property-disallowed-list/index.js

Closes https://github.com/stylelint/stylelint/issues/6453,
Closes https://github.com/stylelint/stylelint/issues/6454,
Closes https://github.com/stylelint/stylelint/issues/6455,
Closes https://github.com/stylelint/stylelint/issues/6461, and
Closes https://github.com/stylelint/stylelint/issues/6462
No, it's modeled after the `color-no-hex` changes in #6312

Increase experimental `messageArgs` support

---

.changeset/little-forks-burn.md
docs/developer-guide/plugins.md
lib/__tests__/normalizeRuleSettings.test.js
lib/lintPostcssResult.js
lib/normalizeAllRuleSettings.js
lib/normalizeRuleSettings.js
lib/utils/__tests__/checkAgainstRule.test.js
lib/utils/checkAgainstRule.js
lib/utils/getStylelintRule.js
types/stylelint/index.d.ts

Closes #6446
- Added support to `checkAgainstRule` with custom rules
- Added test cases to validate passing/failing custom rules and a missing `result` option
- Updated the internal `normalizeRuleSettings` utility to handle custom rules
- This utility is tested thoroughly and thus I feel very confident about the refactor
- Updated the `checkAgainstRule` documentation to describe the new behavior

Add support to `checkAgainstRule` with custom rules

---

.changeset/tricky-wolves-collect.md
docs/developer-guide/plugins.md
lib/utils/__tests__/checkAgainstRule.test.js
lib/utils/checkAgainstRule.js
types/stylelint/index.d.ts

Add support autofix with `checkAgainstRule`

---

.changeset/cyan-cats-destroy.md
lib/formatters/stringFormatter.js

None.
|Before|After|
|-|-|
|<img width="363" alt="image" src="https://user-images.githubusercontent.com/473530/199387277-d4bae7f6-eea6-49fe-aca4-7127605b09ce.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/473530/199387328-db2eaff5-1da2-4238-9470-9385206674d6.png">|
You can confirm the output above by running the `(cd scripts ; ./visual.sh)` command.

Colorize tally output of `string` formatter

---

.github/workflows/testing.yml

None.
Dependabot branches always come with pull requests, so I believe duplicate CI jobs on `push` and `pull_request` are useless. For example, see below:

Stop CI testing on Dependabot branches pushed

---

lib/rules/__tests__/index.test.js
lib/rules/custom-media-pattern/README.md
lib/rules/custom-property-pattern/README.md
lib/rules/keyframes-name-pattern/README.md
lib/rules/selector-class-pattern/README.md
lib/rules/selector-id-pattern/README.md
lib/rules/selector-nested-pattern/README.md

Follow-up of #6391
This change also adds test cases to prevent such mistakes.

Add missing link about custom message option to rule docs

---

types/stylelint/index.d.ts

Ref: #6466
The `PluginContext` type has been marked as deprecated in PR #6466.
Note that the base branch of this PR is `v15`.

Remove deprecated `PluginContext` type

---

.changeset/nice-carpets-yawn.md
lib/formatters/__tests__/compactFormatter.test.js
lib/formatters/__tests__/githubFormatter.test.js
lib/formatters/__tests__/stringFormatter.test.js
lib/formatters/__tests__/tapFormatter.test.js
lib/formatters/__tests__/unixFormatter.test.js
lib/formatters/calcSeverityCounts.js
lib/formatters/compactFormatter.js
lib/formatters/githubFormatter.js
lib/formatters/preprocessWarnings.js
lib/formatters/stringFormatter.js
lib/formatters/tapFormatter.js
lib/formatters/terminalLink.js
lib/formatters/unixFormatter.js

Ref: https://github.com/stylelint/stylelint/pull/6444#issuecomment-1316994695
In this pull request, I try fixing a few bugs over all the formatters except for `jsonFormatter`:
- Add missing output by `parseErrors`
- Fix output of warnings without rule and severity
- Fix error `Unknown severity: "undefined"` with `stringFormatter`
- Add missing output with `unixFormatter` summary line (consistency with `string` and `verbose`)
In line-oriented formatters, I think it’s necessary to preprocess lint warnings (problems) before outputting them to the console:
- convert parse errors to warnings (only `string` did it)
- normalize severity (warnings sometimes have no severity)
- sort …

Fix incorrect output by all formatters except for `json`

---

.changeset/changelog-stylelint.js
.eslintignore
package.json

Ref: https://github.com/stylelint/eslint-config-stylelint/pull/199
(`eslint-config-stylelint` will update `parserOptions.ecmaVersion` soon.)
- Because ESLint ignores dot-folders by default, adding an entry to the `.eslintignore` file is needed.
- Because an optional chaining operator (ES2020 syntax) is used, updating `parserOptions.ecmaVersion` is needed.

Refactor to fix ESLint issues in `.changeset/`

---

package-lock.json
package.json

None.
Overriding the `parserOptions.ecmaVersion` option is no longer needed.
- https://github.com/stylelint/eslint-config-stylelint/releases/tag/17.1.0
- https://github.com/stylelint/eslint-config-stylelint/compare/17.0.0...17.1.0

Bump eslint-config-stylelint from 17.0.0 to 17.1.0

---

.changeset/fast-cats-tan.md
docs/user-guide/configure.md
lib/__tests__/plugins.test.js
lib/augmentConfig.js
types/stylelint/index.d.ts

Closes #6452
Allow users to pass Plugin functions, as well as string names for plugin config.

Add support for plugin objects as config values

---

.changeset/healthy-suns-yawn.md
docs/user-guide/rules.md
lib/reference/mediaFeatures.js
lib/rules/index.js
lib/rules/media-feature-range-notation/README.md
lib/rules/media-feature-range-notation/__tests__/index.js
lib/rules/media-feature-range-notation/index.js

Closes #6161 
Part of cleaning up our pull requests as we prepare for v15.
As mentioned in https://github.com/stylelint/stylelint/pull/6430#issuecomment-1296797593, this pull request doesn't include autofix. I'll open a new issue for that. CssTools dropped [a new media query parser](https://www.npmjs.com/package/@csstools/media-query-list-parser) the other day that may make implementating autofix more viable.
Additionally, I believe the edge-case of:
```css
@media (min-width: 500px) and screen and (max-width: 1200px) {}
```
Should be transformed by this rule into:
```css
@media (width >= 500px) and screen and (width <= 1200px) {}
```
That could then be merged into:
```css
@media …
```

Add media-feature-range-notation

---

.changeset/early-penguins-know.md
types/stylelint/index.d.ts
types/stylelint/type-test.ts

Follow-up for #6481
The `Plugin` type should be used as a return type of the `createPlugin()` function.
Type-checking failures may occur if people use the types changed in this PR, but I believe they accept the failures because of the major update (v15).

Change type names to be more consistent

---

.changeset/strong-hounds-exercise.md
lib/rules/value-keyword-case/__tests__/index.js
lib/rules/value-keyword-case/index.js

Fix `value-keyword-case` false positives for mixed case `ignoreFunctions` option

---

.changeset/rude-hornets-begin.md
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-properties/index.js

Fixes https://github.com/stylelint/stylelint/issues/6523
No, that's it.

Fix `declaration-block-no-duplicate-properties` autofix for `!important`

---

.changeset/itchy-seas-care.md
lib/rules/function-no-unknown/__tests__/index.js
lib/rules/function-no-unknown/index.js

Closes #6537
see https://github.com/stylelint/stylelint/issues/6537#issuecomment-1363471880

Fix `function-no-unknown` false positives for `scroll`, `-webkit-gradient`, `color-stop`, `from`, and `to`

---

docs/developer-guide/syntaxes.md
docs/user-guide/get-started.md

None, as it's a documentation update.

Add @linaria/postcss-linaria to list of compatible custom syntaxes

---

docs/migration-guide/to-15.md

Fix typo in `docs/migration-guide/to-15.md`

---

.changeset/fifty-donuts-arrive.md
docs/user-guide/usage/cli.md
docs/user-guide/usage/options.md
lib/__tests__/__snapshots__/cli.test.js.snap
lib/__tests__/cli.test.js
lib/__tests__/fixtures/invalid-hex.scss
lib/__tests__/standalone-syntax.test.js
lib/cli.js
lib/getPostcssResult.js
lib/utils/getModulePath.js

Ref #6525
This PR fixes resolution of the `customSyntax` (`--custom-syntax`) option. The option should be able to be read from `configBasedir` (`--config-basedir`) like `plugins` or `extends`.

Fix `customSyntax` resolution with `configBasedir`

---

.changeset/sharp-papayas-grab.md
lib/augmentConfig.js
lib/createPlugin.js
lib/createStylelint.js
lib/descriptionlessDisables.js
lib/formatters/index.js
lib/index.js
lib/invalidScopeDisables.js
lib/needlessDisables.js
lib/normalizeAllRuleSettings.js
lib/reportDisables.js
lib/resolveConfig.js
lib/rules/index.js
lib/standalone.js
lib/utils/checkAgainstRule.js
lib/utils/configurationError.js
lib/utils/report.js
lib/utils/ruleMessages.js
lib/utils/validateOptions.js
types/stylelint/index.d.ts

Closes #6508
- remove unused types
- stop using `namespace` to prevent internal types from being published
- mark `@internal` to internal types
Note that I've marked `@internal` conservatively when a type is unknown whether it's internal or not. If an *internal* type proves to be inconvenient or there are requests from people, let's consider removing `@internal` from the type.

Reorganize type definitions

---

.changeset/lemon-cheetahs-complain.md
lib/__tests__/standalone-fix.test.js
lib/lintPostcssResult.js
lib/standalone.js
types/stylelint/index.d.ts

Closes #6542
and by that should also fix https://github.com/stylelint/vscode-stylelint/issues/369
Issue: The API did not return the fixed css in `output` if any rule contained `ruleDisableFix`.
I have removed the `ruleDisableFix` code, because it did not affect the code fixing itself and I assume was wrongly used to change the content format of `output`. I have adjusted some tests to adapt to the changed behavior and extended the test conditions to check that the returned code has the correct fixes applied.
Issue was introduced in https://github.com/stylelint/stylelint/pull/5460

Fix unexpected `output` in Node.js API lint result when any rule contains `disableFix: true`

---

lib/rules/declaration-block-no-duplicate-properties/index.js

Refactor declaration-block-no-duplicate-properties

---

.changeset/nice-ligers-type.md
lib/reference/atKeywords.js
lib/rules/at-rule-no-unknown/__tests__/index.js

Closes #6548.
Pretty self-explanatory - added failing test case, then used @Mouvedia's proposed solution.

Fixes `at-rule-no-unknown` false positives for `@scroll-timeline`

---

.changeset/perfect-suits-unite.md
lib/rules/declaration-property-unit-allowed-list/README.md
lib/rules/declaration-property-unit-allowed-list/index.js

Closes #6454.
Seems like it *should* be a simple addition, but perhaps I'm missing something?
Huge thanks to @ybiquitous for doing a great job implementing this feature!

Add message arguments to `declaration-property-unit-allowed-list`

---

.changeset/quiet-adults-leave.md
lib/rules/function-no-unknown/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxFunction.test.js
lib/utils/isStandardSyntaxFunction.js

Fixes #6564
Tests for the rule are skipped, because there is no CSS-in-JS syntax added to the repo yet. ~~Waiting for https://github.com/stylelint/stylelint/pull/6556.~~

Fix `isStandardSyntaxFunction` false positives for interpolation and backticks in CSS-in-JS

---

.changeset/rude-dryers-fry.md
docs/user-guide/rules.md
lib/rules/function-url-quotes/README.md
lib/rules/function-url-quotes/__tests__/index.js
lib/rules/function-url-quotes/index.js
system-tests/002/__snapshots__/fs.test.js.snap
system-tests/002/__snapshots__/no-fs.test.js.snap

Closes #6500.
~~Two possible code smells I want to call out. In both cases, I opted to pick a "dirty" solution that doesn't change existing behaviour and minimizes/localizes the changed code. However, there are probably more correct/elegant ways to do this. Advice is welcome!~~
I was able to address these thanks to code review, but I'll leave the comments for posterity.
---
First, this rule operates on both declarations and at-rules. It seems like in `checkArgs`, this type information is "erased". To resolve this, I have my utility functions `addQuotes` and `removeQuotes` take in a union type, and then use a crude `'params' in node` to differentiate the type. 
This ... feels …

Add `function-url-quotes` autofix

---

patches/@changesets+apply-release-plan+6.1.3.patch

None.
This commit fixes the following warning by `patch-package` when running `npm ci`:
```
Warning: patch-package detected a patch file version mismatch
Don't worry! This is probably fine. The patch was still applied
successfully. Here's the deets:
Patch file created for
@changesets/apply-release-plan@6.1.2
applied to
@changesets/apply-release-plan@6.1.3
At path
node_modules/@changesets/apply-release-plan
This warning is just to give you a heads-up. There is a small chance of
breakage even though the patch was applied successfully. Make sure the package
still behaves like you expect (you wrote tests, right?) and then run
patch-package @changesets/apply-release-plan
to update the …
```

Update `@changesets/apply-release-plan` patch to fix warning

---

.changeset/slow-dots-hug.md
lib/__tests__/overrides.test.js
lib/augmentConfig.js
lib/isPathIgnored.js

Closes #6525
This change fixes the `overrides.files` property in config to allow basename glob patterns like `*.css` or `*.html`.
For example, let's consider `stylelint-config-standard-vue`:
```js
{
overrides: [
{
files: ["*.vue", "**/*.vue"],
extends: [/* ... */],
},
]
}
```
People should expect the `*.vue` pattern matches any `.vue` files in any directories.
See <https://github.com/ota-meshi/stylelint-config-standard-vue/blob/v1.0.0/lib/index.js#L6>
See also the `basename` option `micromatch`:
<https://github.com/micromatch/micromatch/tree/4.0.5#optionsbasename>

Fix `overrides.files` in config to allow basename glob patterns

---

.changeset/chilly-ties-trade.md
lib/rules/selector-attribute-quotes/__tests__/index.js
lib/rules/selector-attribute-quotes/index.js
lib/utils/__tests__/isValidIdentifier.test.js
lib/utils/isValidIdentifier.js

Closes #4300.
First - should I add some documentation to explain this new behaviour? Or do we think the current setup is enough.
There's a bit of discussion in #4300. To reiterate @Mouvedia's point: 
> so to me
> ```
> [href='te\'s\'t'] { }
> [href="te\"s\"t"] { }
> ```
> 
> can be processed and become
> ```
> [href=te\'s\'t] { }
> [href=te\"s\"t] { }
> ```
> 
> but
> ```
> [href="te'st"] { }
> [href='te"st'] { }
> ```
> 
> should remain untouched.
As such, I've adjusted the relevant test cases. The latter two are moved from being rejected to accepted; let me know if that was the desired change (or if instead we should still report, but not fix).
I realized that the CSS grammar …

Fix `selector-attribute-quotes` false positives for "never"

---

lib/rules/unit-allowed-list/README.md

Motivated from [discussion for `ignoreFunctions` in `unit-disallowed-list`](https://github.com/stylelint/stylelint/pull/6592#discussion_r1089815580).
I'm not sure how to best title this PR (tried to base it off of the CHANGELOG groups in the maintainer guide), feel free to re-title with a better wording!

Change documentation for `unit-allowed-list` `ignoreFunctions` option

---

.changeset/shy-ladybugs-bathe.md
lib/rules/unit-disallowed-list/README.md
lib/rules/unit-disallowed-list/__tests__/index.js
lib/rules/unit-disallowed-list/index.js

Add `ignoreFunctions: []` to `unit-disallowed-list`

---

.changeset/spotty-baboons-train.md
lib/rules/keyframe-selector-notation/__tests__/index.js
lib/rules/keyframe-selector-notation/index.js

Closes #6538
Fix to stop linting if the selector of the keyframe has multiple tags.
Please let me know if there is a better approach.

Fix `keyframe-selector-notation` false positives for named timeline range

---

lib/rules/declaration-property-value-no-unknown/index.js
patches/@types+css-tree+2.0.1.patch

Follow-up for #6511
According to the [CSSTree doc](https://github.com/csstree/csstree/blob/v2.3.1/README.md#usage), it is likely a typical case to pass a node to `lexer.matchProperty()`.
<details>
<summary>CSSTree Usage</summary>
```js
// parse CSS to AST as a declaration value
const ast = csstree.parse('red 1px solid', { context: 'value' });
// match to syntax of `border` property
const matchResult = csstree.lexer.matchProperty('border', last);
```
</details>
I guess this change may reduce extra parsing, but I'm not sure about the implementation details of CSSTree.

Refactor `declaration-property-value-no-unknown` to reuse parsed CSSTree node

---

docs/migration-guide/to-15.md

"_Removed support for Node.js 12_" should be under "_Breaking changes_".

Fix heading level typo in `to-15.md`

---

.github/workflows/testing.yml

Pull request merge queue is now public beta. We try it out.
See also:
- https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Note: I've already enabled a merge queue for the `main` branch.

Enable merge queue

---

.changeset/silver-owls-develop.md
lib/rules/function-calc-no-unspaced-operator/__tests__/index.js
lib/rules/function-calc-no-unspaced-operator/index.js

Closes https://github.com/stylelint/stylelint/issues/6633
`calc()` is not valid, or useful but it also isn't an error that is related to this rule specifically.
This rule should not throw when processing `calc()`

Fix `function-calc-no-unspaced-operator` TypeError on empty `calc()`

---

lib/__tests__/writeOutputFile.test.js

Part of #6631
This change aims to fix the following warning:
```
[DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed.
Use fs.rm(path, { recursive: true }) instead
```
Note that `fs.rm()` has been added in Node.js 14.14.0, and our `engines.node` (`^14.13.1 || >=16.0.0`) doesn't satisfy the version.
But I believe this is used only in tests, so no problem.
See also:
- https://nodejs.org/api/fs.html#fsrmpath-options-callback
- https://github.com/stylelint/stylelint/blob/15.0.0/package.json#L199-L201

Fix `fs.rmdir()` warning by `fs.rm()` in test

---

.changeset/serious-moose-applaud.md
lib/rules/declaration-property-value-no-unknown/__tests__/index.js
lib/rules/declaration-property-value-no-unknown/index.js

Closes https://github.com/stylelint/stylelint/issues/6635

Fix `declaration-property-value-no-unknown` false positives for `env()`

---

.changeset/clever-humans-hunt.md
lib/__tests__/overrides.test.js
lib/getPostcssResult.js

Closes #6631
Also, this change mocks `console.warn()` to clean test output.

Fix inaccurate `customSyntax` inference

---

.changeset/clean-snakes-cheat.md
lib/rules/declaration-property-value-no-unknown/__tests__/index.js
lib/rules/declaration-property-value-no-unknown/index.js

Closes https://github.com/stylelint/stylelint/issues/6649

Fix `declaration-property-value-no-unknown` parse error for `alpha(opacity=n)` to report as violation

---

.changeset/odd-chefs-battle.md
types/stylelint/index.d.ts

Export types for plugin authoring.
Related to https://github.com/stylelint/stylelint/issues/6662

Fix TypeScript error to export `Plugin` and `RuleContext`

---

docs/migration-guide/to-15.md

Closes #6668
It adds more information for those wanting to continue using Stylelint to enforce stylistic conventions.
Like the [custom syntax section](https://stylelint.io/migration-guide/to-15#removed-processors-configuration-property), we can add package links to the migration guide when someone publishes them.

Document migrating deprecate rules to a plugin

---

.changeset/five-waves-relax.md
lib/rules/annotation-no-unknown/__tests__/index.js
lib/rules/annotation-no-unknown/index.js
lib/rules/function-name-case/__tests__/index.js
lib/rules/function-name-case/index.js
lib/rules/function-no-unknown/index.js
lib/rules/unit-no-unknown/__tests__/index.js
lib/rules/unit-no-unknown/index.js
lib/rules/value-keyword-case/index.js

Fixes #6659.
All rules has same issues: trying to lint non-standard value. Based on test one rule (`unit-no-unknown`) has a “regression”. Since the fix ignores declaration with non-standard values. It means that previous linted declaration with dollar-variables are now ignored as well. Given focus of Stylelint on standard CSS only, and policy to ignore non-standard syntax, I consider this “regression” acceptable as it doesn't break builds or report new violation.

Fix `*-case|*-unknown` false positives for CSS-in-JS template literals

---

lib/rules/declaration-property-value-no-unknown/index.js

Follow-up to #6683 (see also DefinitelyTyped/DefinitelyTyped#64410)
By updating `@types/css-tree`, we no longer need to use `@ts-expect-error` to suppress TypeScript errors about `css-tree`.
In addition, this pull request refactors the code to use the `isAtRule` type guard. If not using the type guard, `parent` is not inferred as `AtRule` and so another error occurs.

Refactor `declaration-property-value-no-unknown` to fix `@ts-expect-error`

---

lib/testUtils/safeChdir.js

None.
The `@jest/globals` package is included in Jest by default:
```console
$ npm ls '@jest/globals'
stylelint@15.2.0 /Users/masafumi.koba/git/stylelint/stylelint
└─┬ jest@29.4.3
└─┬ @jest/core@29.4.3
└─┬ jest-runtime@29.4.3
└── @jest/globals@29.4.3
```
Also, because the refactored util is used for only tests, we can use the modern module syntax `node:fs/promises` for Node.js. See also: <https://nodejs.org/api/fs.html>

Refactor `safeChdir()` test util to fix `@ts-expect-error`

---

lib/utils/__tests__/validateTypes.test.js
lib/utils/declarationValueIndex.js
lib/utils/validateTypes.js

None.
This change also adds a new util `isObject()`.

Refactor `declarationValueIndex` util to fix `@ts-expect-error`

---

lib/utils/checkAgainstRule.js

None.
- Name more readable variables.
- Leave comments for `@ts-expect-error` reasons.

Refactor `checkAgainstRule()` util to make code readable

---

docs/user-guide/rules.md

None, as it’s a documentation fix.
The [rule is enabled by stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard/blob/30.0.1/index.js#L81).

Document `media-feature-name-no-vendor-prefix` as standard rule

---

.changeset/yellow-dodos-juggle.md
lib/index.js
types/stylelint/index.d.ts

close: https://github.com/stylelint/stylelint/issues/6694
No.

Fix TypeScript error for CommonJS importing

---

.changeset/mighty-games-kick.md
lib/reference/properties.js
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/shorthand-property-no-redundant-values/README.md
lib/rules/shorthand-property-no-redundant-values/__tests__/index.js
lib/rules/shorthand-property-no-redundant-values/index.js
types/stylelint/index.d.ts

Closes #6613
This PR updates these 2 rules to support the `inset` property
- `declaration-block-no-redundant-longhand-properties`
- `shorthand-property-no-redundant-values`

Fix `*-no-redundant-*` false negatives for `inset` shorthand

---

.changeset/purple-meals-visit.md
lib/reference/keywords.js
lib/rules/value-keyword-case/__tests__/index.js

This adds the [CSS Color Module Level 4 system colours](https://www.w3.org/TR/css-color-4/#css-system-colors) to the list of keywords that are not changed.

Fix `value-keyword-case` false positives for Level 4 system colours

---

.changeset/purple-avocados-help.md
lib/rules/rule-selector-property-disallowed-list/README.md
lib/rules/rule-selector-property-disallowed-list/__tests__/index.js
lib/rules/rule-selector-property-disallowed-list/index.js

Closes #6688.
I'm a bit confused why this wasn't caught by the test suite when the rule was first made/messages were added; presumably, I should write a regression test here. Any suggestions?

Fix `rule-selector-property-disallowed-list` secondary options

---

lib/rules/unit-no-unknown/README.md

Remove erroneous example from `unit-no-unknown` doc

---

.changeset/tasty-carrots-camp.md
docs/user-guide/rules.md
lib/rules/index.js
lib/rules/no-unknown-custom-properties/README.md
lib/rules/no-unknown-custom-properties/__tests__/index.js
lib/rules/no-unknown-custom-properties/index.js

Adds new rule, `no-unknown-custom-properties`, which disallows unknown custom properties. Initial implementation is to consider custom properties defined within the same source.
Relates to #6361. Could close the issue if a new one is created to track a potential `importFrom` option, or a `resolver` option once #4088 is addressed.

Add `no-unknown-custom-properties` rule

---

.changeset/olive-dolphins-reply.md
lib/rules/function-url-quotes/__tests__/index.js
lib/rules/function-url-quotes/index.js

Fix `function-url-quotes` autofix for double-slash comments in SCSS maps

---

.changeset/lovely-ligers-sip.md
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js

Closes #6738.
The scope of this PR is broader than autofixing, since we also shouldn't flag instances which use a basic keyword. Let me know if additional test cases / documentation are desired!
Note that we already had this feature for `inherit`; this PR just expands it to use `basicKeywords`.
If we'd like, we could also create a more "aggressive" approach that converts
```css
margin-top: inset;
margin-bottom: inset;
margin-right: inset;
margin-left: inset;
```
to
```css
margin: inset;
```
which is valid (to my understanding). The rule doesn't currently behave this way with `inherit`; but, happy to add this if we think it's helpful!
---
Spec ref for [shorthand properties not …

Fix `declaration-block-no-redundant-longhand-properties` with basic keywords

---

.changeset/twelve-pandas-hide.md
lib/rules/declaration-block-no-duplicate-properties/README.md
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-properties/index.js

None.
The `ignoreProperties` option of other rules also supports raw regex.

Add raw regex support to `ignoreProperties` for `declaration-block-no-duplicate-properties`

---

.changeset/short-suits-knock.md
lib/__tests__/fixtures/postcss-naive-css-in-js.js
lib/rules/custom-property-empty-line-before/__tests__/index.js
lib/utils/__tests__/isFirstNested.test.js
lib/utils/isFirstNested.js
lib/utils/typeGuards.js

Closes #6766
This change fixes the `isFirstNested()` utility that the `custom-property-empty-line-before` rule internally uses.
~~The rule's test does not change in order to avoid adding an extra dependency for CSS-in-JS.~~
See also the PostCSS API for the `Document` node: <https://postcss.org/api/#document>

Fix `custom-property-empty-line-before` false positives for CSS-in-JS

---

.changeset/popular-ducks-marry.md
lib/rules/color-function-notation/__tests__/index.js
lib/utils/__tests__/isStandardSyntaxColorFunction.test.js
lib/utils/isStandardSyntaxColorFunction.js

Closes #6610.
Ref for searching for `.$`: [SCSS highlights those characters as errors for invalid namespace imports](https://sass-lang.com/documentation/variables#built-in-variables).
I noticed that `rgba` was misspelt in some of the test cases for `isStandardSyntaxColorFunction.test.js`, so I've changed those too.

Fix `color-function-notation` false positives for namespaced imports

---

.changeset/kind-cobras-peel.md
lib/rules/declaration-block-no-duplicate-properties/README.md
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-properties/index.js

Add `ignore: ["consecutive-duplicates-with-different-syntaxes"]` to `declaration-block-no-duplicate-properties`

---

.changeset/tricky-kangaroos-whisper.md
lib/rules/function-url-quotes/__tests__/index.js
lib/rules/function-url-quotes/index.js

Fix `function-url-quotes` autofix for comments in SCSS function

---

.changeset/lucky-forks-fold.md
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.js
lib/rules/declaration-block-no-duplicate-properties/index.js

Fix `declaration-block-no-duplicate-properties` autofix for 3 or more duplicates

---

.changeset/seven-coats-perform.md
docs/user-guide/configure.md
lib/__tests__/standalone-cache.test.js
lib/__tests__/standalone-fix.test.js
lib/__tests__/standalone.test.js
lib/augmentConfig.js
lib/lintPostcssResult.js
lib/standalone.js
types/stylelint/index.d.ts

Part of (but does not close) #5142. This PR handles all the `boolean` flags (which should be relatively simple).
Sorry about the CodeQL alerts - it was an approach that I tried (and chose to abandon) that I forgot to remove 😅 
As well as my note below on `cache`, two quick questions:
1. For the configuration docs, what orders should the options go in? I may have missed a pattern - I was confused since it's not in the same order as the flags.
2. Any tests I should add?
---
Note that I didn't `augmentConfig` for `allowEmptyInput` and `cache`, since we never access them through the `config` object outside of `standalone.js`; including them drops code coverage. That being said, maybe …

Add `allowEmptyInput`, `cache`, `fix` options to configuration object

---

.changeset/popular-jeans-tap.md
lib/rules/color-function-notation/README.md
lib/rules/color-function-notation/__tests__/index.js
lib/rules/color-function-notation/index.js

Add `ignore: ["with-var-inside"]` to `color-function-notation`

---

package-lock.json

Closes #6813
Ref: https://github.com/stylelint/stylelint-config-standard/pull/291
This commit fixes CVE-2023-2251 via the `npm update yaml` command.
See also https://github.com/advisories/GHSA-f9xv-q969-pqx4
Note that I manually created this commit because Dependabot failed to create a pull request.

Bump yaml from 2.2.1 to 2.2.2

---

.github/ISSUE_TEMPLATE/REPORT_A_BUG.yml

None.
This pull request improves the bug report template so that we can easily reproduce a reported issue.
Changes summary:
- Add description and placeholder to `reproduce-bug` section
- Avoid deprecated rule `number-leading-zero`
- Add a demo link for easy reproduction
- Add an example of dependencies
- Use `textarea` instead of `input` so that people can easily input
I've prepared a test repository to try this PR's change easily:
https://github.com/ybiquitous/stylelint-pull-6817/issues/new?template=REPORT_A_BUG.yml

Improve bug report template

---

.changeset/neat-poems-tie.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js

Closes #6812.
This one required some non-trivial CSS spec reading, hence the complicated-ish behaviour!

Fix `declaration-block-no-redundant-longhand-properties` autofix for `transition`

---

.changeset/many-mugs-camp.md
lib/reference/selectors.js
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js

Fix `selector-pseudo-class-no-unknown` false positive for `:modal`

---

README.md

Fix the CI badge since https://github.com/stylelint/stylelint/pull/6752.
Related to https://github.com/stylelint/stylelint/pull/5811.

Fix CI badge on homepage

---

docs/user-guide/rules.md

The `selector-anb-no-unmatchable` rule is actually has been included in the recommended and standard.
https://github.com/stylelint/stylelint-config-recommended/blob/b35e61355d4a9853532a9f977219453456d6b1bc/index.js#L36

Fix `selector-anb-no-unmatchable` doc to include in recommended and standard configs

---

.changeset/soft-islands-relax.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js

Closes https://github.com/stylelint/stylelint/issues/6839

Fix `declaration-block-no-redundant-longhand-properties` `autofix` with `cubic-bezier()`

---

.changeset/healthy-planets-hide.md
lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js

Closes https://github.com/stylelint/stylelint/issues/6823
This didn't require any logic changes because this rule just scans ahead for the first `/`.
This works for all color functions and for relative color syntax.
I've added a few more tests to verify that everything is working as expected.
Happy to add more if needed.

Fix `alpha-value-notation` false negatives for `oklab()`, `oklch()`, and `color()`

---

docs/user-guide/rules.md

I'm reviewing my stylelint config, and found two doc mistakes:
- `declaration-block-single-line-max-declarations` has been included in the `standard` last month ([link](https://github.com/stylelint/stylelint-config-standard/blob/5aa5dd57ac814edd98c656da35f2ccc99a64d433/index.js#L56))
- `shorthand-property-no-redundant-values` has been included in the `standard` 2 years ago ([link](https://github.com/stylelint/stylelint-config-standard/blob/5aa5dd57ac814edd98c656da35f2ccc99a64d433/index.js#L110))

Fix `declaration-block-single-line-max-declarations`, and `shorthand-property-no-redundant-values` doc

---

.changeset/mean-trees-serve.md
lib/rules/function-no-unknown/__tests__/index.js
lib/rules/function-no-unknown/index.js

Closes https://github.com/stylelint/stylelint/issues/6582
This change migrates this rule from `postcss-value-parser` to `@csstools/css-parser-algorithms`.

Fix `function-no-unknown` false positives for unspaced operators against nested brackets

---

lib/rules/media-feature-name-case/__tests__/index.js
lib/rules/media-feature-name-case/index.js
lib/utils/findMediaFeatureNames.js
lib/utils/findMediaFeatureNamesSearch.js

See : https://github.com/stylelint/stylelint/issues/6848
I started with `media-feature-name-case` because it is the only rule for media feature names that also has an autofix option. Any utility that works for that rule will also work for rules without an autofix option.
Almost all of the complexity in this new utility is the result of trying to have some support for non-standard syntax.
There are two issues with non-standard syntax :
1. `@media @foo and (min-width: 320px) {}`
Top level non-standard syntax doesn't have any fallbacks in the media query parser. It's just an invalid list item.
To resolve this I moved to a "two stage" parser.
- first pass tokenizes and parses into …

Refactor to add utility for media feature names and migrate `media-feature-name-case`

---

lib/rules/unit-no-unknown/README.md
lib/rules/unit-no-unknown/__tests__/index.js

Ref: #6721 (I found this PR's problem during the issue discussion)
The `unit-no-unknown` rule handles the `image-set()` function and the `x` unit.
So, specifying `image-set` to the `ignoreFunctions` option doesn't make sense.
Additionally, this change removes duplicate cases in the test for `unit-no-unknown`.
See also the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilAjJYA1gOYBOEArplALQCWAtksTPCo8zDQM4wAuACiw4cAcgD0HFt3HcIDLlK4BGAB4A6AFYAHYqJRqANMJESlMuQvpMWNAEwadelA+PZTkmzAvzFXmgDMjrr6QSYAlADcWAC+IIYgAGZ0ADYwAHJICgggMKpZ2mnqYNzc8eAQmMnEORju6CCkFGncDWx1IigNVHR8NJgQNFSEAwDumG0ofE0wJjGx5ZBVdMQAYhCkTHw5mnKY5bDaZYgdXSDcfACeaSl0mHyTDSlIfN4P8SYNF9cwt-c0S2qPD4SGoSFIUEeIGerw …

Change more suitable examples in `unit-no-unknown` doc

---

.changeset/late-otters-behave.md
lib/formatters/__tests__/stringFormatter.test.js
lib/formatters/stringFormatter.js

See issus: [stringFormatter.js truncate non-ASCII characters unexpectedly](https://github.com/stylelint/stylelint/issues/6860)
Closes #6860
The reason that why don't I just contribute code to repository `table`, is: make it to support full ability about non-ASCII seems like a lot of work. before it, we can solve the problem in this way first。

Fix `string` formatter for unexpected truncation on non-ASCII characters

---

.changeset/tricky-gorillas-drive.md
lib/rules/alpha-value-notation/index.js
scripts/benchmark-rule.mjs

See : https://github.com/stylelint/stylelint/issues/6853
I was curious about performance and if there were any benchmark tools in place.
I found that the current benchmark script is just checking PostCSS performance, not rule performance in specific. I've refactored this script to separate the initial parsing phase and the plugin processing.
This gives a more relevant result to Stylelint plugins.
I also found that processing Bootstrap only once doesn't give meaningful results.
PostCSS is just too fast, the deviation too high and the actual duration per cycle with or without a code change isn't clear.
I found that duplicating the Bootstrap source 20 times gives a more useful …

Fix `alpha-value-notation` performance with improved benchmark script

---

.changeset/tender-cows-invite.md
lib/rules/at-rule-property-required-list/index.js
lib/utils/createMapWithSet.js

See:
- https://github.com/stylelint/stylelint/issues/6853
- https://github.com/stylelint/stylelint/issues/6869
In this `at-rule-property-required-list` two types of work were less than ideal :
- formatting of plugin options
- nested loops

Fix `at-rule-property-required-list` performance

---

.changeset/calm-rivers-wink.md
lib/reference/functions.js
lib/rules/length-zero-no-unit/__tests__/index.js

Closes https://github.com/stylelint/stylelint/issues/6870

Fix `length-zero-no-unit` false positives on new math functions

---

package-lock.json
package.json
scripts/benchmark-rule.mjs

None.
Summary:
- Uninstall no longer `node-fetch`.
- Global `fetch()` has been available on Node.js current LTS versions (18.x)
- See https://nodejs.org/api/globals.html#fetch
- We recommend using a Node.js LTS version during development
- See https://github.com/stylelint/stylelint/blob/a7cf5abdaa/CONTRIBUTING.md?plain=1#L18-L20
- Refactor the script to improve readability a bit.
- Use `console.error()` (stderr) for error logs.
Test (my local machine):
```console
$ npm run benchmark-rule -- alpha-value-notation '["number", {"exceptProperties": ["/opacity/"]}]'
> stylelint@15.6.2 benchmark-rule
> node scripts/benchmark-rule.mjs alpha-value-notation ["number", {"exceptProperties": …
```

Refactor benchmark script

---

.github/workflows/code-scanning.yml
.github/workflows/preparing-github-release.yml
.github/workflows/releasing.yml
.github/workflows/testing.yml

Closes https://github.com/stylelint/stylelint/issues/6880
CI for Stylelint seems to take ±6 minutes on most runs, sometimes a little bit over 10 minutes.
30 minutes seems like a safe multiple of the current duration.
Sufficient headroom so that no one will ever encounter this timeout during normal operations.
I've lowered this to 20 minutes for jobs that don't do any heavy lifting.

Fix: add timeouts for GitHub Workflows

---

lib/rules/unit-no-unknown/__tests__/index.js
lib/rules/unit-no-unknown/index.js
package-lock.json
package.json

See : https://github.com/stylelint/stylelint/issues/6848
Supersedes : https://github.com/stylelint/stylelint/pull/6726
- ~~this will fail because it uses unreleased features of the media query parser~~
- also happens to resolve #6726
before :
```
npm run benchmark-rule unit-no-unknown true
Warnings: 0
Mean: 143.3089323125 ms
Deviation: 10.593647978441565 ms
```
after : 
```
npm run benchmark-rule unit-no-unknown true
Warnings: 0
Mean: 109.86287500000002 ms
Deviation: 9.320724134887374 ms
```

Fix `unit-no-unknown` false positives for the second and subsequent `image-set()` with `x` descriptor

---

.changeset/neat-owls-knock.md
lib/rules/alpha-value-notation/__tests__/index.js
lib/rules/alpha-value-notation/index.js

Closes https://github.com/stylelint/stylelint/issues/6884

Fix `alpha-value-notation` false positives for `color()`

---

.changeset/chilled-lizards-film.md
lib/rules/selector-nested-pattern/README.md
lib/rules/selector-nested-pattern/__tests__/index.js
lib/rules/selector-nested-pattern/index.js

Closes #2430 
As @jeddy3 said, we could consider a better name for the option.
https://github.com/stylelint/stylelint/issues/2430#issuecomment-1160156212
> (Prehaps there's a better name?. Prior art is [the disallowInList option](https://stylelint.io/user-guide/rules/list/no-duplicate-selectors/#disallowinlist-true--false-default-false). [Spec ref for "list"](https://www.w3.org/TR/selectors-4/#grouping).)
I guess `splitList` is not bad because `selector-disallowed-list` rule has [similar option](https://stylelint.io/user-guide/rules/selector-disallowed-list/#splitlist-true--false-default-false).

Add `splitList: boolean` to `selector-nested-pattern`

---

.changeset/shiny-toys-chew.md
lib/rules/unit-no-unknown/__tests__/index.js
lib/rules/unit-no-unknown/index.js
lib/utils/isUnicodeRangeDescriptor.js

Closes https://github.com/stylelint/stylelint/issues/6891
I forgot about [`<urange>` productions](https://www.w3.org/TR/css-syntax-3/#urange) when migrating rules to `@csstools/css-tokenizer`.
Parsing `<urange>` requires special handling and should only be done when inside a context that expects such values.
I've added a helper (`isUnicodeRangeDescriptor`) to make it easier for rules to skip `@font-face { unicode-range: U+0100-024F; }`

Fix `unit-no-unknown` false positives for `unicode-range` descriptors

---

.changeset/blue-lions-guess.md
lib/createStylelint.js
lib/getConfigForFile.js

See : https://github.com/stylelint/stylelint/issues/6898
The `sync` loaders from `cosmiconfig` for `.js` and `.cjs` still use the old logic/code.
Only the `async` loaders were changed.
Switching back to the `sync` loaders makes the errors go away.

Fix Segmentation fault errors for Cosmiconfig 8.2

---

.changeset/early-dodos-invent.md
bin/stylelint.js
package-lock.json
package.json

Closes #6904
Closes #6901
`v8-compile-cache` no longer has performance benefits on Node.js 20.
Please see the benchmark on <https://github.com/stylelint/stylelint/issues/6904#issuecomment-1579131889>.

Remove `v8-compile-cache`

---

.changeset/swift-pugs-matter.md
docs/user-guide/configure.md
lib/__tests__/__snapshots__/cli.test.js.snap
lib/cli.js
scripts/visual-config.cjs
scripts/visual-config.mjs
scripts/visual.sh

Closes #6905
This PR mainly does the following:
- Update the CLI help.
- Update the user guide.
In addition, this PR improves files in the `scripts` folder so that we can easily try the `.mjs` support. Try running the following at the project root.
```console
$ (cd scripts ; ./visual.sh)
```

Support `.mjs` configuration files

---

.changeset/cyan-dingos-own.md
lib/rules/max-nesting-depth/__tests__/index.js
lib/rules/max-nesting-depth/index.js

Fix `max-nesting-depth` error for at-rules in Sass syntax

---

.changeset/sixty-masks-sip.md
docs/user-guide/cli.md
lib/__tests__/__snapshots__/cli.test.js.snap
lib/cli.js

None.
The `--print-config` option never requires an argument. For example:
```console
$ bin/stylelint.js --print-config -c scripts/visual-config.json scripts/visual.css
{
"rules": {
...
```
On the other hand, the following example is mistaken:
```console
$ bin/stylelint.js --print-config scripts/visual-config.json
Error: No configuration provided for /Users/masafumi.koba/git/stylelint/stylelint/scripts/visual-config.json
...
```

Fix `--print-config` description in CLI help

---

.changeset/brave-balloons-rescue.md
lib/rules/function-no-unknown/__tests__/index.js
lib/utils/isStandardSyntaxValue.js

Closes https://github.com/stylelint/stylelint/issues/6920

 Fix `function-no-unknown` false positives for SCSS functions with namespace

---

.changeset/heavy-pandas-cheer.md
lib/rules/custom-property-no-missing-var-function/index.js

See : https://github.com/stylelint/stylelint/issues/6869
----
before :
```
Warnings: 0
Mean: 106.64779905882351 ms
Deviation: 14.50380702371365 ms
```
after :
```
Warnings: 0
Mean: 98.50316917647058 ms
Deviation: 11.405372458359288 ms
```

Fix `custom-property-no-missing-var-function` performance

---

.changeset/wet-countries-think.md
lib/rules/function-calc-no-unspaced-operator/index.js

See : https://github.com/stylelint/stylelint/issues/6869
----
before :
```
Warnings: 0
Mean: 90.56110877777778 ms
Deviation: 11.54085198893875 ms
```
after : 
```
Warnings: 0
Mean: 83.60294444444445 ms
Deviation: 10.305877029720664 ms
```

Fix `function-calc-no-unspaced-operator` performance

---

.changeset/sour-tables-lick.md
lib/__tests__/fixtures/config-allow-empty-input.json
lib/__tests__/standalone.test.js
lib/standalone.js

Fix `allowEmptyInput` in configuration files

---

.changeset/popular-cougars-build.md
lib/rules/function-linear-gradient-no-nonstandard-direction/index.js

See https://github.com/stylelint/stylelint/issues/6869
-----
before :
```
Warnings: 0
Mean: 89.20350494117648 ms
Deviation: 11.294021704297947 ms
```
after : 
```
Warnings: 0
Mean: 77.0127245 ms
Deviation: 7.537474958126632 ms
```

Fix `function-linear-gradient-no-nonstandard-direction` performance

---

.changeset/modern-numbers-impress.md
lib/rules/selector-anb-no-unmatchable/index.js
lib/utils/hasANPlusBNotationPseudoClasses.js

See : https://github.com/stylelint/stylelint/issues/6869
-----
before : 
```
Warnings: 0
Mean: 171.01108333333332 ms
Deviation: 11.09835497913841 ms
```
after :
```
Warnings: 0
Mean: 115.6843908125 ms
Deviation: 7.734276833118593 ms
```

Fix `selector-anb-no-unmatchable` performance

---

lib/rules/function-no-unknown/index.js
lib/rules/unit-disallowed-list/index.js
lib/rules/unit-no-unknown/index.js

None, it's a minor code quality fix that I noticed while working on a different issue.
This isn't a user facing change, so I am omitting a changelog entry.
----
`parseCommaSeparatedListOfComponentValues` :
- list of lists of component values
- split by comma
- doesn't include the comma as a component value
- useful for : 
- media query lists
- selectors
- function params (`rgb(0, 0, 0)`)
`parseListOfComponentValues` :
- list of component values
- no splits
- does include the comma as a `TokenNode`
- useful for anything
This distinction is important when writing specialized parsers (like the media query parser) but it isn't relevant when validating component values.
Using …

Refactor value parsing to use a simpler algorithm

---

package-lock.json
package.json

Ref: https://github.com/stylelint/stylelint/pull/6941#discussion_r1236002418
For example:
```diff
-import replaceBackslashes from '../lib/testUtils/replaceBackslashes.js';
+import replaceBackslashes from '../lib/testUtils/replaceBackslashes';
```
```console
$ npm run lint:js
...
/Users/masafumi.koba/git/stylelint/stylelint/system-tests/systemTestUtils.mjs
6:32  error  Missing file extension "js" for "../lib/testUtils/replaceBackslashes"  import/extensions
```
See https://github.com/import-js/eslint-plugin-import/blob/88dd8153571373151c3c7b508c5944cb2bba1588/docs/rules/extensions.md

Add `eslint-plugin-import` to detect missing file extensions in `import`

---

lib/testUtils/safeChdir.js
package-lock.json
package.json

Ref: #5291
`@jest/globals` is already installed by `jest`, but we need to import `@jest/globals` in ESM.
In this case, a comment like `// eslint-disable-line node/no-extraneous-require` is noisy.
```console
$ npm ls '@jest/globals'
stylelint@15.8.0 /Users/masafumi.koba/git/stylelint/stylelint
├── @jest/globals@29.5.0
└─┬ jest@29.5.0
└─┬ @jest/core@29.5.0
└─┬ jest-runtime@29.5.0
└── @jest/globals@29.5.0 deduped
```

Install `@jest/globals` explicitly

---

CHANGELOG.md
docs/developer-guide/syntaxes.md

This change ensures that an at-mark unexpectedly is not handled as a user mention, especially generating the website pages (stylelint.io).

Avoid at-mark use in Markdown files

---

docs/user-guide/rules.md
lib/rules/__tests__/index.test.js

Follow-up to #6937
Instead of `✅`, reusing symbols makes people to read the doc easier, especially on small-width devices.
See https://github.com/stylelint/stylelint/issues/6928#issuecomment-1599111520
Example: https://typescript-eslint.io/rules/

Replace `✅` with corresponding symbols in rule doc tables

---

.changeset/sixty-lies-repair.md
lib/reference/properties.js
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js

Closes #6947.
Sorry that I missed this! Happy to quickly cut a new release if we'd like.

Fix `declaration-block-no-redundant-longhand-properties` autofix for `border-width` shorthand

---

.changeset/violet-otters-rule.md
lib/reference/properties.js
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js

Ref: https://github.com/stylelint/stylelint/pull/6956#issuecomment-1603347258

Fix `declaration-block-no-redundant-longhand-properties` autofix for `border-radius` shorthand

---

.changeset/wet-houses-warn.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js
lib/rules/declaration-block-no-redundant-longhand-properties/index.js

Closes #6918.
Also fixed the one for `grid-row`, since it's the same syntax.

Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-column` and `grid-row`

---

docs/user-guide/rules.md
lib/rules/__tests__/index.test.js

Follows on from https://github.com/stylelint/stylelint/pull/6937 & https://github.com/stylelint/stylelint/pull/6946
(The use of tables and the introduction of 🔧 for autofix were excellent changes!)
We can improve the onboarding experience for new users by only mentioning our `standard` config in our docs. 
We don't mention our `recommended` config in the first 3 steps of the onboarding process:
- [Getting started](https://stylelint.io/user-guide/get-started)
- [Customising](https://stylelint.io/user-guide/customize)
- [Configuring](https://stylelint.io/user-guide/configure)
Before this pull request, we'd then introduce it in the 4th step …

Document only our standard config

---

lib/formatters/__tests__/compactFormatter.test.mjs
lib/formatters/__tests__/githubFormatter.test.mjs
lib/formatters/__tests__/jsonFormatter.test.mjs
lib/formatters/__tests__/prepareFormatterOutput.mjs
lib/formatters/__tests__/stringFormatter.test.mjs
lib/formatters/__tests__/tapFormatter.test.mjs
lib/formatters/__tests__/terminalLink.test.mjs
lib/formatters/__tests__/unixFormatter.test.mjs
lib/formatters/__tests__/verboseFormatter.test.mjs

Refactor to rewrite `lib/formatters/__tests__/*` to ESM

---

package.json

Ref: https://github.com/stylelint/stylelint/pull/6964#discussion_r1240432958
See https://docs.npmjs.com/cli/v9/commands/npm-test#ignore-scripts

Fix typo for `--ignore-scripts` in `package.json`

---

lib/rules/__tests__/index.test.js

None.
For example, if a URL were incorrect, the test case would fail:
```
● all rules › "alpha-value-notation" should have metadata
expect(received).toBe(expected) // Object.is equality
Expected: "https://stylelint.io/user-guide/rules/alpha-value-notation"
Received: "https://stylelint.io/user-guide/rules/alpha-value-notation_"
```

Add test case to check `rule.meta.url` more precisely

---

package.json

Ref: https://github.com/stylelint/stylelint/pull/6964#discussion_r1240545427
Difference between `npm test` and `npm run test-only`:
- `npm test` - run linting before testing
- `npm run test-only` - without linting (useful for local development)
Example:
```console
$ npm run test-only -- cli
...
PASS  lib/__tests__/cli.test.mjs
PASS  lib/utils/__tests__/checkInvalidCLIOptions.test.js
...
```

Add `npm run test-only` script for development

---

docs/migration-guide/to-15.md

Closes https://github.com/stylelint/stylelint/issues/6753
Let's list both for now so that they are at least discoverable by users. If the plugin authors consolidate efforts and one package is deprecated, we can update the migration guide again.

Document stylistic plugin in migration guide

---

.changeset/great-feet-brake.md
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js
lib/rules/selector-pseudo-class-no-unknown/index.js

Closes #6878
I have added a test for `:placeholder` because `:-moz-placeholder` and `:-ms-input-placeholder` exist.
i.e. it's a good example of something that the rule will pick up from now on

Fix `selector-pseudo-class-no-unknown` false negatives for pseudo-elements with matching names

---

.changeset/tough-shrimps-walk.md
lib/rules/media-feature-name-no-vendor-prefix/__tests__/index.js
lib/rules/media-feature-name-no-vendor-prefix/index.js

Closes https://github.com/stylelint/stylelint/issues/6975

Fix `media-feature-name-no-vendor-prefix` positions for `*-device-pixel-ratio`

---

.changeset/hot-planets-rest.md
lib/__tests__/descriptionlessDisables.test.mjs
lib/__tests__/needlessDisables.test.mjs
lib/__tests__/reportDisables.test.mjs
lib/prepareReturnValue.js
system-tests/004/__snapshots__/fs.test.mjs.snap
system-tests/004/__snapshots__/no-fs.test.mjs.snap

Closes #6982
This pull request fixes the `errored` property calculation in `prepareReturnValue()`.
---
Internal details:
`standalone()` just returns a return value from `prepareReturnValue()`. This value includes a correct `errored` property.
https://github.com/stylelint/stylelint/blob/9ddba420d9f146331a55d0f62d3154331ce4291c/lib/standalone.js#L268-L272
https://github.com/stylelint/stylelint/blob/9ddba420d9f146331a55d0f62d3154331ce4291c/lib/prepareReturnValue.js#L40-L48
Before this pull request's change, `returnValue.errored` could differ from `returnValue.results[*].errored`.
https://github.com/stylelint/stylelint/blob/9ddba420d9f146331a55d0f62d3154331ce4291c/lib/prepareReturnVal …

Fix inconsistent `errored` properties in `stylelint.lint()` return value

---

.changeset/strong-cycles-raise.md
lib/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js
lib/rules/function-linear-gradient-no-nonstandard-direction/index.js

Closes https://github.com/stylelint/stylelint/issues/6951

Fix `function-linear-gradient-no-nonstandard-direction` false positives for `<color-interpolation-method>`

---

docs/migration-guide/to-15.md

https://github.com/stylelint/stylelint/pull/6979#discussion_r1243272645, it's a documentation fix.
It's placed where it shouldn't conflict with the `v16` branch changes.

Document `quietDeprecationWarnings` in migration guide

---

.github/ISSUE_TEMPLATE/REPORT_A_BUG.yml

A few recent bug reports have included large examples or configurations. This pull request tweaks the template's wording and makes things more consistent to encourage more minimal examples.

Refine the bug template to encourage minimal examples

---

lib/utils/__tests__/addEmptyLineAfter.test.mjs
lib/utils/__tests__/addEmptyLineBefore.test.mjs
lib/utils/__tests__/arrayEqual.test.mjs
lib/utils/__tests__/atRuleParamIndex.test.mjs
lib/utils/__tests__/beforeBlockString.test.mjs
lib/utils/__tests__/blockString.test.mjs
lib/utils/__tests__/blurInterpolation.test.mjs
lib/utils/__tests__/checkInvalidCLIOptions.test.mjs
lib/utils/__tests__/configurationComment.test.mjs
lib/utils/__tests__/containsString.test.mjs
lib/utils/__tests__/declarationValueIndex.test.mjs
lib/utils/__tests__/filterFilePaths.test.mjs
lib/utils/__tests__/findAnimationName.test.mjs
lib/utils/__tests__/findAtRuleContext.test.mjs
lib/utils/__tests__/findFontFamily.test.mjs

Ref: #5291
This change rewrites some `lib/utils/__tests__/*.js` files to ESM.

Refactor utils tests to migrate to ESM

---

lib/rules/no-duplicate-at-import-rules/__tests__/index.js
lib/rules/no-duplicate-at-import-rules/index.js

See : https://github.com/stylelint/stylelint/issues/6848
I found that this rule doesn't actually require parsing media queries.
It only used the media query parser to split on comma's.
This is something that can be easily done with the `postcss-value-parser` AST nodes.

Refactor `no-duplicate-at-import-rules` to remove `postcss-media-query-parser`

---

.changeset/nasty-shoes-bathe.md
lib/rules/no-duplicate-at-import-rules/__tests__/index.js
lib/rules/no-duplicate-at-import-rules/index.js

Closes https://github.com/stylelint/stylelint/issues/6997

Fix `no-duplicate-at-import-rules` false negatives for imports with `supports` and `layer` conditions

---

.changeset/shy-tools-rest.md
lib/rules/function-no-unknown/index.js

Ref #6869 
Before:
Mean: 104.89167158823528 ms
Deviation: 9.601897806542654 ms
After:
Mean: 71.84089116666665 ms
Deviation: 10.215987936599932 ms

Fix function-no-unknown performance

---

.changeset/smooth-tigers-wink.md
lib/rules/selector-pseudo-element-no-unknown/index.js

Aborting as early as possible, i.e. before any `isStandardSyntax*` checks, helps too. I've added that as the third aspect of https://github.com/stylelint/stylelint/issues/6869#issuecomment-1605428748.
Before:
Mean: 159.1181665714286 ms
Deviation: 18.599824916664016 ms
After:
Mean: 138.47696128571428 ms
Deviation: 16.776228134868457 ms

Fix selector-pseudo-element-no-unknown performance

---

lib/rules/function-no-unknown/index.js
lib/rules/media-feature-name-unit-allowed-list/index.js
lib/rules/media-feature-name-value-no-unknown/index.js
lib/rules/media-feature-range-notation/index.js
lib/rules/media-query-no-invalid/index.js
lib/rules/number-max-precision/index.js
lib/rules/unit-disallowed-list/index.js
lib/rules/unit-no-unknown/index.js

See https://github.com/stylelint/stylelint/issues/6848
- consistent naming of `state`, `inititalState`
- consistently destructure `entry` into `{ node, state, ... }` 
- refactor `media-feature-name-unit-allowed-list` to use the `state` mechanic instead of dual walking
_this might not be the final refactor_

Refactor AST walking with `@csstools` parsers for code consistency

---

docs/developer-guide/rules.md
scripts/benchmark-rule.mjs

None.
- Add the help output (usage and examples).
- Replace deprecated rule in the doc.
```console
$ npm run benchmark-rule -s
Usage: node benchmark-rule.mjs <ruleName> <ruleOptions> [ruleContext]
Examples:
node benchmark-rule.mjs value-keyword-case lower
node benchmark-rule.mjs value-keyword-case '["lower", {"camelCaseSvgKeywords": true}]'
node benchmark-rule.mjs value-keyword-case '["lower", {"camelCaseSvgKeywords": true}]' '{"fix": true}'
```
Ref: https://github.com/stylelint/stylelint/blob/15.9.0/lib/rules/value-keyword-case/README.md

Improve `npm run benchmark-rule` script and doc

---

.changeset/hot-doors-jump.md
lib/rules/custom-property-pattern/index.js

Before: 
Mean: 148.86722335714288 ms
Deviation: 14.868270718260428 ms
After:
Mean: 120.50095842857144 ms
Deviation: 18.926086943302593 ms

Fix custom-property-pattern performance

---

.changeset/silly-eagles-grow.md
lib/rules/selector-id-pattern/index.js

Mean: 240.67508675000005 ms
Deviation: 20.382065001610304 ms
To
Mean: 85.73348046666666 ms
Deviation: 8.678100769643914 ms
Avoiding unnecessary selector parsing is a win. We seldom see id selectors in the wild.

Fix selector-id-pattern performance

---

.changeset/empty-starfishes-leave.md
lib/rules/hue-degree-notation/index.js

Mean: 120.86200307142857 ms
Deviation: 19.25088932105957 ms
To
Mean: 85.13097773333334 ms
Deviation: 8.810119272059223 ms

Fix hue-degree-notation performance

---

.changeset/ten-mirrors-clean.md
lib/rules/hue-degree-notation/__tests__/index.js
lib/rules/hue-degree-notation/index.js

Closes https://github.com/stylelint/stylelint/issues/7014

Fix `hue-degree-notation` false negatives for `oklch`

---

.changeset/short-onions-play.md
lib/reference/prefixes.js
lib/rules/selector-no-vendor-prefix/index.js
lib/rules/value-no-vendor-prefix/index.js
lib/utils/hasPrefix.js

https://github.com/stylelint/stylelint/issues/6869
selector-no-vendor-prefix
Mean: 246.52507291666666 ms
Deviation: 22.75678614753106 ms
To
Mean: 91.62227779999999 ms
Deviation: 7.8451629248369095 ms
value-no-vendor-prefix
Mean: 102.0994388 ms
Deviation: 11.78154094781758 ms
To
Mean: 91.27013606666667 ms
Deviation: 15.351019516794766 ms

Fixed selector|value-no-vendor-prefix performance

---

.changeset/angry-mails-give.md
lib/rules/unit-disallowed-list/__tests__/index.js
lib/rules/unit-disallowed-list/index.js

See https://github.com/stylelint/stylelint/issues/6848
I noticed inconsistent handling of values in at rule preludes vs. declarations.

Fix `unit-disallowed-list` false negatives with percentages

---

package.json

Closes #4562
This change should prevent potential out-of-memory errors. See <https://github.com/stylelint/stylelint/pull/7024#issuecomment-1616548676>.
Ref:
- https://jestjs.io/docs/29.0/configuration#coverageprovider-string
- https://jestjs.io/blog/2020/01/21/jest-25#v8-code-coverage

Switch Jest `coverageProvider` from `babel` (default) to `v8`

---

lib/rules/media-feature-name-unit-allowed-list/index.js
lib/rules/media-feature-name-value-allowed-list/index.js
lib/rules/media-feature-name-value-no-unknown/index.js
lib/rules/media-feature-range-notation/index.js
lib/rules/media-query-no-invalid/index.js
package-lock.json
package.json

None, this is more cleanup after migrating to parsers from `@csstools`.

Refactor to use `sourceIndices` utility from `@csstools/css-parser-algorithms`

---

lib/__tests__/cli.test.mjs
lib/__tests__/ignore.test.mjs
lib/__tests__/invalidScopeDisables.test.mjs
lib/__tests__/needlessDisables.test.mjs
lib/__tests__/printConfig.test.mjs
lib/__tests__/resolveConfig.test.mjs
lib/__tests__/standalone-cache.test.mjs
lib/__tests__/standalone-fix.test.mjs
lib/__tests__/standalone-globs.test.mjs
lib/__tests__/standalone-maxWarnings.test.mjs
lib/__tests__/standalone-parseErrors.test.mjs
lib/__tests__/standalone-syntax.test.mjs
lib/__tests__/standalone.test.mjs
lib/__tests__/stylelintignore-test/stylelintignore.test.mjs
lib/testUtils/replaceBackslashes.mjs
system-tests/systemTestUtils.mjs

Refactor `replaceBackslashes()` test utility to migrate to ESM

---

patches/@changesets+apply-release-plan+6.1.4.patch

None.
This change fixes the following warning when running `npm install`:
```
Warning: patch-package detected a patch file version mismatch
Don't worry! This is probably fine. The patch was still applied
successfully. Here's the deets:
Patch file created for
@changesets/apply-release-plan@6.1.3
applied to
@changesets/apply-release-plan@6.1.4
At path
node_modules/@changesets/apply-release-plan
This warning is just to give you a heads-up. There is a small chance of
breakage even though the patch was applied successfully. Make sure the package
still behaves like you expect (you wrote tests, right?) and then run
patch-package @changesets/apply-release-plan
to update the version in …
```

Fix `patch-package` warning

---

.changeset/gorgeous-cobras-beam.md
lib/__tests__/extends.test.mjs
lib/__tests__/fixtures/config-block-no-empty.mjs
lib/__tests__/fixtures/config-extending-with-object.mjs
lib/augmentConfig.js

Add support JS objects for extends config option

---

.changeset/friendly-candles-deny.md
lib/rules/selector-type-case/index.js
lib/rules/selector-type-no-unknown/index.js

See https://github.com/stylelint/stylelint/issues/6869
Before :
```
Warnings: 0
Mean: 298.4487499090909 ms
Deviation: 21.21196081587678 ms
```
After :
```
Warnings: 0
Mean: 103.26133328571427 ms
Deviation: 9.239254247553538 ms
```

Fix `selector-type-case` performance

---

.changeset/twenty-camels-promise.md
bin/stylelint.js
bin/stylelint.mjs
lib/__tests__/cli.test.mjs
lib/cli.mjs
package-lock.json
package.json
patches/meow++type-fest+1.4.0.patch
tsconfig.json

Closes https://github.com/stylelint/stylelint/issues/5042
Closes https://github.com/stylelint/stylelint/issues/7040
Not sure how to describe this change within the conventions of the project.
Suggestions welcome.
-----
How do we verify that #5042 is fixed?
Comments within that issue describe that updating `meow` is the solution, but it would be nice to verify this and to have a test that prevents regressions.
----
#7040 :
```
npm audit --production
found 0 vulnerabilities
```

Security fix for `semver` vulnerability

---

docs/maintainer-guide/releases.md
lib/rules/__tests__/index.test.mjs

Closes #7045 
(Diff is mainly whitespace for test.)

Document check of configs in release process

---

docs/maintainer-guide/pull-requests.md

Ref: https://github.com/stylelint/stylelint/pull/7043#discussion_r1253104796

Document security changelog group

---

docs/developer-guide/plugins.md
docs/developer-guide/rules.md

Document approach to using private utils

---

package-lock.json

None.
This change fixes the following error when running `npm ci`.
```console
$ npm ci
npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Invalid: lock file's semver@7.5.3 does not satisfy semver@7.5.4
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! …
```

Update `semver` in `package-lock.json`

---

.github/dependabot.yml

None.
This PR aims to reduce Dependabot PRs.
The new feature is now public beta. See:
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
Including only dev dependencies is intentional. Welcome any feedback.
Here's an example in my personal repository: https://github.com/ybiquitous/npm-audit-fix-action/pull/759

Introduce Dependabot group updates

---

.changeset/lazy-geese-begin.md
lib/reference/selectors.js

Resolves https://github.com/stylelint/stylelint/issues/7069
No, it's self-explanatory. I've added some details in the linked issue.

Fix `selector-pseudo-element-no-unknown` false positives for `view-transition` pseudo-elements

---

docs/user-guide/rules.md

Currently migrating a project to v15 and noticed a [misformatted section](https://stylelint.io/user-guide/rules/#declaration-block) in the deprecated rules guide (btw, thank you for such a clear and thorough migration guide).

[Docs] Fix table formatting in deprecated rules user guide

---

scripts/visual.sh

Ref #7043 (where renaming happened)
This change fixes the following error. The correct path is `bin/stylelint.mjs`, not `bin/stylelint.js`.
```console
$ ./scripts/visual.sh
...
node:internal/modules/cjs/loader:1051
throw err;
^
Error: Cannot find module '/Users/masafumi.koba/git/stylelint/bin/stylelint.js'
at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
at Module._load (node:internal/modules/cjs/loader:901:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
at node:internal/main/run_main_module:23:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
...
```

Fix broken `scripts/visual.sh`

---

.github/workflows/testing.yml

None.
This change aims to avoid the following error that sometimes happens with the CI test coverage job.
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
See https://github.com/stylelint/stylelint/actions/runs/5670173698/job/15364468310#step:6:263
I refered to this solution on <https://github.com/actions/runner-images/issues/70#issuecomment-1191708172>.

Avoid heap out of memory with CI coverage job

---

.github/workflows/releasing.yml

Ref #7089
This change aims to make a Pull Request title for preparing release clearer.
For example, changing from `Prepare release` to `Prepare 15.10.3`.
For example, we can locally confirm the script:
```console
$ npx changeset status --output .changeset/status.json
$ new_version=$(jq -r '.releases[0].newVersion' < .changeset/status.json)
$ echo "new-version=${new_version}"
new-version=15.10.3
```

Improve Pull Request title for preparing release

---

.github/dependabot.yml

Ref:
- #7105 
- #7106
- #7107
This change aims to assemble Dependabot Pull Requests about `@csstools/*` parser packages.
@romainmenke Any thoughts?

Group Dependabot updates by `@csstools/*` parser packages

---

lib/rules/no-descending-specificity/index.js
lib/rules/selector-pseudo-element-colon-notation/index.js
lib/rules/unit-allowed-list/index.js
lib/testUtils/replaceBackslashes.mjs
lib/utils/__tests__/checkInvalidCLIOptions.test.mjs
tsconfig.json

None.
Node.js 16 is 100% compatible with ES2021.
See https://node.green/#ES2021
<details>
<summary>Screenshot</summary>
</details>
In addition, this change uses [`String.prototype.replaceAll()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) as possible for readability. This method has been available since ES2021.
---
Context: Stylelint 16.0.0 will support Node.js 16 or later. See #7020.

Update `tsconfig.json` for ES2021

---

lib/__tests__/disableRanges.test.mjs
lib/__tests__/normalizeRuleSettings.test.mjs
lib/assignDisabledRanges.cjs
lib/assignDisabledRanges.mjs
lib/createPartialStylelintResult.cjs
lib/createPartialStylelintResult.mjs
lib/createPlugin.cjs
lib/createPlugin.mjs
lib/descriptionlessDisables.cjs
lib/descriptionlessDisables.mjs
lib/index.js
lib/invalidScopeDisables.cjs
lib/invalidScopeDisables.mjs
lib/lintPostcssResult.js
lib/needlessDisables.cjs
lib/needlessDisables.mjs
lib/normalizeAllRuleSettings.js
lib/normalizeRuleSettings.cjs
lib/normalizeRuleSettings.mjs
lib/prepareReturnValue.cjs
lib/prepareReturnValue.mjs
lib/reportDisables.cjs
lib/reportDisables.mjs
lib/standalone.js
lib/utils/checkAgainstRule.js
lib/validateDisableSettings.cjs
lib/validateDisableSettings.mjs
scripts/benchmark-rule.mjs

Ref #5291
This change rewrites relatively simpler `lib/*.js` files to ESM.

Migrate simpler `lib/*` files to ESM

---

lib/__tests__/cli.test.mjs
lib/cli.mjs

None.
- Remove no longer needed JSDoc types.
- Use type-guard functions for type-safety.
- Make the code more readable with new local variables.
If anyone knows a way to use type inference by `meow()` in this `cli.mjs` module, please let me know.

Refactor `lib/cli.mjs`

---

.changeset/orange-dancers-compete.md
.changeset/twelve-ladybugs-mate.md
docs/migration-guide/to-16.md
lib/__tests__/cli.test.mjs
lib/cli.mjs

Closes #3401
This commit changes the following:
1. To avoid waiting for stdin without any input. For example, just running the `stylelint` command
immediately exits, instead of waiting. I believe this behavior is more user-friendly.
2. To avoid different outputs on empty files and empty stdin. This is achieved by allowing an empty
string input (`''`) from stdin. See the example below:
```sh
bin/stylelint.mjs
echo -n '' | bin/stylelint.mjs
```
See also [`process.stdin.isTTY`](https://nodejs.org/api/tty.html#readstreamistty).

Fix CLI to avoid waiting for stdin without any input and avoid different outputs

---

.github/dependabot.yml

None.
This change reduces our work (rebasing, resolving conflicts, etc.) to update dependencies since we have already committed many changes on the `v16` branch.

Change Dependabot target branch to v16

---

.github/dependabot.yml

Retry for #7151
We had to push changes in `dependabot.yml` into the `main` branch rather than the `v16` branch.

Change Dependabot target branch to v16 (retry)

---

lib/__tests__/fixtures/plugin-async.js
lib/__tests__/fixtures/plugin-conditionally-check-color-named.js
lib/__tests__/fixtures/plugin-primary-array.js
lib/__tests__/fixtures/plugin-slashless-warn-about-foo.js
lib/__tests__/fixtures/plugin-warn-about-bar.js
lib/__tests__/fixtures/plugin-warn-about-foo.js
lib/__tests__/formatters.test.mjs
lib/__tests__/integration.test.mjs
lib/__tests__/plugins.test.mjs
lib/__tests__/resolveConfig.test.mjs
lib/index.cjs
lib/index.mjs
package.json
system-tests/001/fs.test.mjs
system-tests/001/no-fs.test.mjs
system-tests/002/fs.test.mjs
system-tests/002/no-fs.test.mjs
system-tests/003/fs.test.mjs
system-tests/003/no-fs.test.mjs
system-tests/004/fs.test.mjs
system-tests/004/no-fs.test.mjs

Ref #5291
This PR needs to wait for the merge of:

Migrate `lib/index` to ESM

---

.changeset/fifty-rice-knock.md
.changeset/red-bottles-invite.md
docs/migration-guide/to-16.md
docs/user-guide/options.md
lib/__tests__/formatters.test.mjs
lib/__tests__/standalone-formatter.test.mjs
lib/formatters/index.cjs
lib/formatters/index.mjs
lib/standalone.cjs
lib/standalone.mjs
types/stylelint/index.d.ts

Related to #5291
This commit avoids using the `import-lazy` package in the `formatters` module.
As a result, `formatters` can be a pure ESM module, which means `require` is no longer needed.
In addition, this change accepts a `Promise` function as a custom formatter.
Note that `import-lazy` is still used:
```console
$ git grep -w 'import-lazy' lib/
lib/rules/index.cjs:4:  const importLazy = require('import-lazy');
lib/rules/index.mjs:5:  import importLazy from 'import-lazy';
```

Avoid `import-lazy` in `formatters`

---

lib/rules/declaration-block-no-redundant-longhand-properties/index.js

`Array.from` has optional second argument, so calling `map` after is not required.

Simplify array-from in rules

---

lib/rules/__tests__/index.test.mjs
lib/rules/alpha-value-notation/__tests__/index.mjs
lib/rules/alpha-value-notation/index.cjs
lib/rules/alpha-value-notation/index.mjs
lib/rules/index.cjs
lib/rules/index.mjs

Migrate `alpha-value-notation` rule to ESM

---

.changeset/functional-severity.md
docs/user-guide/configure.md
lib/__tests__/defaultSeverity.test.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/report.cjs
lib/utils/report.mjs
types/stylelint/index.d.ts

Let me know if I should add more tests (if so, where?), or change something in the docs.
I did implement the feature as described in the https://github.com/stylelint/stylelint/issues/6863#issuecomment-1567238888 comment.
Closes https://github.com/stylelint/stylelint/issues/6863

Add an ability to pass a function for severity secondary option

---

.changeset/shy-ghosts-report.md
lib/rules/max-nesting-depth/README.md
lib/rules/max-nesting-depth/__tests__/index.mjs
lib/rules/max-nesting-depth/index.js

Closes #6529 (and thus, closes #2696 and closes #4805).
1. I've add co-author annotations to credit @sjarva and @ybiquitous with their contributions in the original PR; we should keep these when/if we merge. Also happy to merge this back into #6529 if @sjarva would like; I think we should give her the authorship for this commit if possible.
2. I noticed that there's a possibility where if both `ignoreRules` and `ignorePseudoClasses` are used together (as siblings), the original PR does not properly treat that combination as fully ignored. I've added a test case to verify that and then fix it in https://github.com/stylelint/stylelint/commit/cfa98ab42904aa6953819fabe140ade4649e87b9. …

Add `ignoreRules` to `max-nesting-depth`

---

.changeset/tricky-horses-watch.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.js

Closes #7228.
Added the test case from the issue + the swapped version with `rows` instead of `columns`.
Are we interested in making a `repeat` parser? I could add it to my personal backlog (though this would probably be after the ESM migration, etc.). I'm also not sure what existing tooling is here (maybe there's some existing csstools/postcss/other parser that we can use)?

Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-template` with `repeat()`

---

lib/__tests__/disableRanges.test.mjs
lib/reference/properties.js
lib/rules/declaration-property-value-no-unknown/index.js
lib/rules/selector-class-pattern/index.js
lib/rules/selector-max-class/__tests__/index.mjs
lib/rules/selector-max-combinators/__tests__/index.mjs
lib/rules/selector-max-specificity/__tests__/index.mjs
lib/rules/selector-max-specificity/index.js
lib/utils/__tests__/isStandardSyntaxAtRule.test.mjs

see tasklist on #7060
I didn't tick the review because I couldn't resolve all the TODOs; 6 files are left:
- `lib/rules/functionCommaSpaceChecker.js`
- `lib/rules/color-named/index.js`
- <del>`lib/rules/selector-class-pattern/index.js`</del>
- `lib/rules/selector-descendant-combinator-no-non-space/index.js`
- `lib/rules/string-quotes/index.js`
- v16:
- `lib/formatters/__tests__/terminalLink.test.mjs`
- `.github/dependabot.yml`

Remove some TODOs

---

.changeset/silver-pumas-rest.md
lib/rules/function-no-unknown/__tests__/index.mjs
lib/rules/function-no-unknown/index.js
package-lock.json
package.json

Closes #7236 and closes #7226 (and related to #7231).
I intentionally broke this up into two commits so that you can see the failed test cases (false positives), and then showing how the version bump fixes them. 
Let me know if this PR's title should instead be the changeset entry!

Bump css-functions-list from 3.2.0 to 3.2.1

---

package-lock.json
package.json

Closes #7237; ref https://github.com/stylelint/stylelint/issues/7243#issuecomment-1765472324.
Getting dependabot to update `main` instead of `v16` was a bit of a struggle earlier, hence the manual PR :(

Bump known-css-properties from 0.28.0 to 0.29.0

---

lib/rules/color-hex-alpha/index.js
lib/rules/color-hex-length/index.js
lib/rules/color-no-hex/index.js
lib/utils/__tests__/isHexColor.test.mjs
lib/utils/isHexColor.js

Added `isHexcolor` utility function and replaced duplicated isHexColor functions and added unit test for the function.
Also removed unused `isValidHex` in `.../color-hex-alpha/index.js`.
Closes #7245

Refactor to add `isHexColor` utility

---

lib/__tests__/fixtures/broken-syntax/stylelint.config.cjs
lib/__tests__/fixtures/broken-syntax/stylelint.config.mjs

Ref #5291
If migrating to ESM, CI would fail due to SIGSEGV errors. For example:
https://github.com/stylelint/stylelint/actions/runs/6578275243/job/17871645000?pr=7265#step:8:890

Refactor `fixtures/broken-syntax/stylelint.config.js` to CJS

---

package-lock.json
package.json

Reverts stylelint/stylelint#7223
We should revert the update to `postcss-safe-parser@7.0.0` because the version drops the support of Node.js 16. We need to support Node.js 16 until the next major version (v16.0.0) of Stylelint. See #7240.
---
```console
$ npm view postcss-safe-parser@7.0.0 engines
{ node: '>=18.0' }
$ npm view postcss-safe-parser@6.0.0 engines
{ node: '>=12.0' }
```

Revert "Bump postcss-safe-parser from 6.0.0 to 7.0.0"

---

lib/__tests__/standalone-parseErrors.test.mjs

Ref #5291
I believe we should avoid mocking in tests if possible.

Refactor `standalone-parseErrors.test.mjs` to avoid CJS

---

CHANGELOG.md

Ref stylelint/stylelint.io#357
This change will make the hack unneeded in [stylelint.io](https://github.com/stylelint/stylelint.io). See https://github.com/stylelint/stylelint.io/pull/357/files#r1379011358

Fix `#{&}` as inline code in `CHANGELOG.md`

---

docs/user-guide/configure.md
docs/user-guide/ignore-code.md
docs/user-guide/node-api.md
docs/user-guide/options.md
lib/rules/comment-no-empty/README.md
lib/rules/comment-whitespace-inside/README.md
lib/rules/comment-word-disallowed-list/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/font-family-name-quotes/README.md
lib/rules/font-family-no-duplicate-names/README.md
lib/rules/max-nesting-depth/README.md
package.json

Ref stylelint/stylelint.io#357
GitHub provides more rich UI for alerts in Markdown files (beta).
This is similar to Docusaurus Admonitions (which is used in stylelint.io),
and should improve our documentation readability.
See:
- https://github.com/orgs/community/discussions/16925
- https://docusaurus.io/docs/markdown-features/admonitions
- https://github.com/stylelint/stylelint.io/pull/357/files#r1378999753
Source:
```markdown
> [!NOTE]
> Highlights information that users should take into account, even when skimming.
> [!IMPORTANT]
> Crucial information necessary for users to succeed.
> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.
``` …

Use special alerts in GitHub Markdown

---

lib/__tests__/extends.test.mjs
lib/__tests__/standalone-deprecations.test.mjs
lib/__tests__/standalone-fix.test.mjs
lib/__tests__/standalone-formatter.test.mjs
lib/__tests__/standalone.test.mjs

Follow-up to #7183
This change aims to reduce redundant warnings in test reports.
Note that it still cannot be removed completely where needed.

Refactor tests to remove deprecated `output` property as possible

---

jest.setup.mjs
lib/__tests__/formatters.test.mjs
lib/formatters/__tests__/githubFormatter.test.mjs
lib/utils/__tests__/isFirstNodeOfRoot.test.mjs
lib/utils/__tests__/isKeyframeRule.test.mjs
package.json

Ref #5291
Follow-up to #7279
~~Note that this change uses the unpublished version of `jest-preset-stylelint`:~~
~~https://github.com/stylelint/jest-preset-stylelint/pull/81~~
New version is published: https://github.com/stylelint/jest-preset-stylelint/releases/tag/6.3.2
This change should increase test coverage.

Test ESM rules

---

.changeset/loud-insects-camp.md
.changeset/weak-crews-swim.md
docs/migration-guide/to-16.md
package.json

Closes #6258
Ref #5291
This Pull Request is necessary for [Conditional exports](https://nodejs.org/api/packages.html#conditional-exports) (ESM and CJS).
Note: For backward compatibility, we may need to export `stylelint/lib/utils/*` files.
The following script can easily output many `lib/utils/` settings.
<details><summary>Script</summary>
<p>
```js
import path from 'node:path';
import fg from 'fast-glob';
const exports = {
'.': {
import: './lib/index.mjs',
require: './lib/index.cjs',
},
'./package.json': './package.json',
};
const files = fg.sync('lib/utils/isStandardSyntax*.mjs', { ignore: '**/__tests__/**' });
for (const file of files) {
const base = path.basename(file, …
```

Add `exports` field to `package.json`

---

.github/dependabot.yml

Remove `target-branch: v16` from Dependabot config

---

docs/developer-guide/formatters.md
docs/maintainer-guide/issues.md
docs/user-guide/customize.md
docs/user-guide/get-started.md
lib/rules/no-unknown-custom-properties/README.md

This change for consistency will enable us to deal with syntax highlighting more easily in the <https://stylelint.io> website.

Refactor code block languages in Markdown files

---

docs/developer-guide/plugins.md
docs/developer-guide/syntaxes.md
docs/user-guide/options.md

Links to the PostCSS website should be more understandable than links to Markdown file blobs on GitHub.

Improve links to PostCSS documentation

---

docs/developer-guide/plugins.md
docs/developer-guide/rules.md
docs/user-guide/node-api.md

Currently, <https://api.postcss.org/> is redirected to <https://postcss.org/api/>.

Fix outdated PostCSS API links in documentation

---

docs/developer-guide/rules.md

It's a documentation fix related to https://github.com/stylelint/stylelint/issues/7338
Although already used by the `verbose` formatter, the `fixable` `meta` property becomes more important if we tally the fixable problems in the default `string` formatter, especially for plugin authors.

Document `fixable: true` meta

---

system-tests/005/commonjs.test.cjs

None. Just test fix.
This change tries fixing a flaky system test case for CommonJS.
The case sometimes fails only on Node.js 20 and Windows OS. See the example:
```
FAIL system-tests/005/commonjs.test.cjs (8.098 s)
● CommonJS API and config
thrown: "Exceeded timeout of 5000 ms for a test.
Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
9 | const testFn = Number(nodeMajorVersion) >= 20 ? test : test.skip;
10 |
> 11 | testFn('CommonJS API and config', async () => {
| ^
12 | 	const result = await stylelint.lint({
13 | 		files: [caseFilePath('stylesheet.css')],
14 | 		configFile: …
```

Fix flaky system test case for CommonJS

---

package.json

None.
For some reason, the `lib/rules/*/README.md` addition to the `files` field is necessary.
The following is the report by `npm pack --dry-run`: **-37 kB** (266.9 kB - 303.9 kB)
Before:
```
npm notice === Tarball Details ===
npm notice name:          stylelint
npm notice version:       16.0.0-3
npm notice filename:      stylelint-16.0.0-3.tgz
npm notice package size:  303.9 kB
npm notice unpacked size: 1.6 MB
npm notice shasum:        a403d04490cd9c56f0c5dfb9c0d42c4062dc8733
npm notice integrity:     sha512-s3x9tg3tEZyhy[...]a416SkvGgWtzg==
npm notice total files:   717
```
After:
```
npm notice === Tarball Details ===
npm notice name:          stylelint
npm notice version: …
```

Reduce package size by removing rule README files

---

docs/migration-guide/to-16.md

Ref https://github.com/stylelint/stylelint-test-rule-node/pull/4#pullrequestreview-1770870717
We've published the new package `stylelint-test-rule-node`, which is an alternative to `jest-preset-stylelint`
See https://www.npmjs.com/package/stylelint-test-rule-node
Also, this change fixes indentation in `diff` code blocks.

Add `stylelint-test-rule-node` to migration guide for 16.0.0

---

.changeset/sixty-lamps-type.md
lib/rules/selector-disallowed-list/README.md
lib/rules/selector-disallowed-list/__tests__/index.mjs
lib/rules/selector-disallowed-list/index.cjs
lib/rules/selector-disallowed-list/index.mjs

Closes #7162.
Two quick questions:
1. ~~I used the `isKeyframeSelector` util (used elsewhere) to heuristically guess if the item is a keyframe selector, rather than seeing if it's actually *in* a keyframe. Does this make sense?~~ Am now using `isKeyframeRule` instead!
2. ~~I assumed that there should be nothing "special" about this option's interaction with `splitList`; in particular, if the list is not split, given `/from/` the current implementation will still flag `from, to`; it's only if the rule is given `/from/, { splitList: true }` that `from, to` is properly ignored. However, it'd be simple for me to reverse this behaviour - what are our thoughts?~~ Resolved by the former …

Add `ignore: ["keyframe-selectors"]` to `selector-disallowed-list`

---

lib/rules/function-no-unknown/index.cjs
lib/rules/function-no-unknown/index.mjs
lib/rules/number-max-precision/index.cjs
lib/rules/number-max-precision/index.mjs
lib/rules/unit-disallowed-list/index.cjs
lib/rules/unit-disallowed-list/index.mjs
lib/rules/unit-no-unknown/index.cjs
lib/rules/unit-no-unknown/index.mjs
package-lock.json
package.json

None, this is a refactor after an upstream API addition
Starting an AST walk when you have a list of component values was a bit cumbersome because the list is plain JavaScript array. So you have to iterate the top levels manually and do all your checks there first and then start walking down simple blocks and functions.
I've added a `walk` function that takes a list of component values as its argument.
This makes it possible to remove some duplicate code here.
-----
_This isn't a user facing change so I don't think a changelog entry is needed._

Refactor to use `@csstools/css-parser-algorithms` `walk` helper

---

.changeset/quiet-toes-accept.md
lib/cli.mjs

Fix `ERR_UNSUPPORTED_ESM_URL_SCHEME` for  `--custom-formatter` on Windows

---

.changeset/friendly-garlics-jog.md
lib/__tests__/standalone.test.mjs
lib/standalone.cjs
lib/standalone.mjs

Closes #7440
[`meow`](https://github.com/sindresorhus/meow) automatically sets the default value `false` for boolean flags when the flags are unspecified.
https://github.com/stylelint/stylelint/blob/804bb24c75248aba55b009994e4bfb561593a990/lib/cli.mjs#L203-L206

Fix `allowEmptyInput` option ignored in configuration object regression

---

.changeset/beige-peaches-add.md
lib/utils/__tests__/hasInterpolation.test.mjs
lib/utils/hasTplInterpolation.cjs
lib/utils/hasTplInterpolation.mjs

#7442 
The regular expression that checks template literals in js has been changed.

Fix `function-no-unknown|value-keyword-case` false positives for template literals with line breaks

---

docs/migration-guide/to-16.md

Document `--output-file` flag in migration guide for CLI stderr change

---

.changeset/healthy-donkeys-appear.md
lib/rules/media-query-no-invalid/__tests__/index.mjs
lib/rules/media-query-no-invalid/index.cjs
lib/rules/media-query-no-invalid/index.mjs

Closes https://github.com/stylelint/stylelint/issues/7401
I've added a second argument for the `rejected` message.
- is there an existing pattern in other rules for what I want to do here?
- is `hint` a good name for the second argument? (maybe `reason`, ...)
I am also unsure what the best wording is.
I don't think most people are familiar with the wording of the specification, e.g. `range context`, `plain feature`, ...
So I've opted to label everything as a query : `range query`, `boolean query`.

Add `media-query-no-invalid` specific problem messages

---

.changeset/cyan-mice-enjoy.md
lib/reference/atKeywords.cjs
lib/reference/atKeywords.mjs
lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs

None, it's a false negative fix for `declaration-property-value-no-unknown` rule.
This false negative is explained here - https://github.com/stylelint/stylelint/pull/7438#discussion_r1439118910

Fix `declaration-property-value-no-unknown` false negatives for `@starting-style`

---

.changeset/ten-rivers-hammer.md
lib/__tests__/overrides.test.mjs
lib/augmentConfig.cjs
lib/augmentConfig.mjs

Fix `overrides.files` negated pattern regression

---

docs/developer-guide/formatters.md
docs/user-guide/cli.md

Previously the documentation did not include the piping of stderr to stdout which meant that in error cases stylint would write to stderr and the stdin of the consuming process never received anything. This remedies the situation by writing both stdout & stderr to stdin of the consuming process
https://github.com/stylelint/stylelint/issues/7467
Pretty much a one liner documentation update. The explanation from the commit body should hopefully suffice.

Document CLI piping example

---

.changeset/gold-donkeys-lie.md
lib/rules/selector-max-specificity/__tests__/index.mjs
lib/rules/selector-max-specificity/index.cjs
lib/rules/selector-max-specificity/index.mjs

Config:
```json
{"ignoreSelectors": [".foo"]}
```
CSS code:
```css
:nth-child(even of .foo) {}
/* ↓ Calculates specificity ignoring 'of .foo' in `ignoreSelectors` */
:nth-child(even) {}
```
Closes #6615

Fix `selector-max-specificity` false positives with `ignoreSelectors` option for `of <selector>` syntax

---

.changeset/weak-maps-tease.md
lib/utils/__tests__/report.test.mjs
lib/utils/report.cjs
lib/utils/report.mjs

Closes #7172
Including a rule name in the error message helps us understand why an error happens.

Fix `report()` error message responsibility for a missing node or line number

---

CHANGELOG.md

This change retroactively adds a changelog item in the 16.0.0 section.
For the background of this change, see: https://github.com/stylelint/stylelint/issues/5192#issuecomment-1902091854
Ref #5192
We have not often updated the changelog retroactively. If any problems, feel free to let me know.

Document dependency name support for `--custom-formatter` in CHANGELOG

---

lib/rules/selector-max-compound-selectors/README.md

A whitespace represents a *descendant combinator*.

Fix combinator example in `selector-max-compound-selectors` README

---

.changeset/curly-seals-confess.md
lib/rules/custom-property-no-missing-var-function/README.md
lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs
lib/rules/custom-property-no-missing-var-function/index.cjs
lib/rules/custom-property-no-missing-var-function/index.mjs

Fix `custom-property-no-missing-var-function` false positives for properties that can contain author-defined identifiers

---

.github/workflows/commenting-on-old-issues.yml

Closes #7459
~~How about labeling with `stale` to avoid duplicate comments? Is this irregular label acceptable only for this action?~~
This action will comment on older issues than one month, and will replace the "ready to implement" label with "ask to implement". See https://github.com/stylelint/stylelint/pull/7486#discussion_r1460976731

Add GitHub action to change the label and add a warning comment on issues older than a month

---

.github/workflows/commenting-on-old-issues.yml

This fixes the following error in the GitHub action:
```
failed to run git: fatal: not a git repository (or any of the parent directories): .git
```
https://github.com/stylelint/stylelint/actions/runs/7609612527/job/20721207993#step:2:19
The failure reason is that the `gh` command tries reading the `.git` repository.
This change provides the repository info through an environment variable supported by `gh`.
(see also https://cli.github.com/manual/gh_help_environment)
Follow-up to PR #7486
By the way, if cli/cli#3556 was realized, this PR would be no longer needed.

Provide repository info to `gh` command in GitHub action

---

.changeset/friendly-poems-taste.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs

Closes #7477
I am planning a followup PR for the missing media pseudo-elements.
see https://github.com/stylelint/stylelint/pull/5959#issuecomment-1065330459

Fix `selector-pseudo-class-no-unknown` false positives for `:seeking`, the media loading state and sound state pseudo-classes

---

.changeset/olive-experts-breathe.md
lib/utils/__tests__/validateOptions.test.mjs
lib/utils/validateOptions.cjs
lib/utils/validateOptions.mjs

Fix `validateOptions` to report when secondary option object is an empty object or null

---

package.json
scripts/benchmark-rule.mjs

This fixes the broken benchmark script (`npm run benchmark`)
The error reason is that `rules[ruleName]` has returned a `Promise` since 16.0.0.
```sh-session
$ npm run benchmark-rule -- value-keyword-case lower
...
const rule = ruleFunc(primary, secondary, context);
^
TypeError: ruleFunc is not a function
...
```
Also, this changes `parserOptions.ecmaVersion` in the ESLint config to allow top-level `await`.
None.
If we release `eslint-config-stylelint` including stylelint/eslint-config-stylelint#252 and bump the package version first, the ESLint config's change in this PR will be needless.
Of course, we can revisit it later.

Fix benchmark script

---

docs/user-guide/cli.md

See: https://github.com/stylelint/stylelint/blob/382961fb6eb67557910a1ff7430a7a180f888bcc/lib/cli.mjs#L81

Document CLI user guide to fix typo for `—custom-syntax`

---

CHANGELOG.md

Stylelint 15.0.0 removed the support for processors.
EDIT: Also, I feel like it's inconsistent that only this item has a link. See https://github.com/stylelint/stylelint/pull/7508#discussion_r1474480259

Fix broken link "processors" in CHANGELOG

---

.changeset/little-hotels-flash.md
lib/rules/selector-pseudo-class-allowed-list/__tests__/index.mjs
lib/rules/selector-pseudo-class-allowed-list/index.cjs
lib/rules/selector-pseudo-class-allowed-list/index.mjs
lib/rules/selector-pseudo-element-allowed-list/__tests__/index.mjs
lib/rules/selector-pseudo-element-allowed-list/index.cjs
lib/rules/selector-pseudo-element-allowed-list/index.mjs

Fix `selector-pseudo-*-allowed-list` false positives for vendor prefixes

---

.changeset/four-roses-refuse.md
lib/rules/rule-selector-property-disallowed-list/__tests__/index.mjs
lib/rules/rule-selector-property-disallowed-list/index.cjs
lib/rules/rule-selector-property-disallowed-list/index.mjs

Closes https://github.com/stylelint/stylelint/issues/7488
I noticed that this walks down the entire sub tree for each rule node.
This might not be what users expect.
But changing it to `.each()` also has issues.
It will no longer give errors on :
```css
.bad-selector {
@media screen {
color: red;
}
}
```
Edit: I've found a more complete patch

Fix `rule-selector-property-disallowed-list` false positives for nesting selectors

---

.changeset/silent-hornets-accept.md
lib/__tests__/plugins.test.mjs
lib/__tests__/standalone-deprecations.test.mjs
lib/__tests__/standalone-quiet-deprecation-warnings.test.mjs
lib/augmentConfig.cjs
lib/augmentConfig.mjs
lib/createStylelint.cjs
lib/prepareReturnValue.cjs
lib/prepareReturnValue.mjs
rollup.config.mjs

Add support for `*-deprecation` command-line flags of Node.js

---

.changeset/red-fans-wait.md
lib/utils/report.cjs
lib/utils/report.mjs
package-lock.json
package.json

None, but related to https://github.com/stylelint/stylelint/pull/7518#discussion_r1532505205
```css
a {}
```
This stylesheet has a selector with a length `1` at the start of a stylesheet.
This is passed to PostCSS as `index: 0` and `endIndex: 0` since `endIndex` is exclusive.
However both Stylelint and PostCSS have boolean checks for `endIndex` instead of a check that it is a number.
So the warning is reported as if no `endIndex` was set.
This does a fallback to the entire length of the node. 
```
a {}
^  ^
```
-------
PostCSS has already been fixed but awaiting release : https://github.com/postcss/postcss/pull/1932
-------
This should have a unit test, but I noticed that there …

Fix `report()` for `index`/`endIndex` zero values

---

lib/rules/selector-max-compound-selectors/README.md

I noticed the `[!WARNING]` section is broken the our website (stylelint.io)
because starting with an inline code (`:not()`).
Follow-up to #7544
No, it's self-explanatory. Just a document fix.

Fix `selector-max-compound-selectors` document in website

---

.changeset/three-pumas-help.md
lib/utils/__tests__/resolveSilent.test.mjs
lib/utils/resolveSilent.cjs
lib/utils/resolveSilent.mjs

Closes #7576
Closes #7577
Ref #7532
This PR fixes an issue where cannot resolve paths in configurations that expect `index.js` to resolve implicitly by Node.js.

Fix import errors for configs and plugins omitting `/index.js`

---

.changeset/violet-boxes-dream.md
lib/rules/selector-max-combinators/__tests__/index.mjs
lib/rules/selector-max-combinators/index.cjs
lib/rules/selector-max-combinators/index.mjs

See : https://github.com/stylelint/stylelint/issues/6234
Follows the same patterns as : https://github.com/stylelint/stylelint/pull/7518

Fix `selector-max-combinators` end positions

---

lib/utils/__tests__/parseSelectorAST.test.mjs

relates to #7518
```sh
console.warn
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
at warnOnce (node_modules/postcss/lib/warn-once.js:11:13)
at NoWorkResult.then (node_modules/postcss/lib/no-work-result.js:67:9)
```

Refactor to silence PostCSS stderr warning 

---

.github/workflows/testing.yml

None.
This PR fixes the Codecov upload error below:
```
Error: Codecov token not found. Please provide Codecov token with -t flag.
```
For example, see https://github.com/stylelint/stylelint/actions/runs/8654881284/job/23732901535#step:7:31
See also the reference of Codecov GitHub Action: https://github.com/codecov/codecov-action

Fix Codecov upload by specifying token

---

.changeset/funny-jobs-work.md
lib/reference/functions.cjs
lib/reference/functions.mjs
lib/rules/function-calc-no-unspaced-operator/README.md
lib/rules/function-calc-no-unspaced-operator/__tests__/index.mjs
lib/rules/function-calc-no-unspaced-operator/index.cjs
lib/rules/function-calc-no-unspaced-operator/index.mjs
lib/rules/length-zero-no-unit/index.cjs
lib/rules/length-zero-no-unit/index.mjs
lib/utils/typeGuards.cjs
lib/utils/typeGuards.mjs

Closes #7618
A follow-up PR will be necessary to support these: `min`, `max`, `hypot`, `clamp`, `round`, `mod`, `rem`, `atan2`, `pow`, `log`.
> [As it's fixing false negatives, it'd be a minor release, in line with our semantic-versioning policy.](https://github.com/stylelint/stylelint/issues/5695#issuecomment-1079960257)

Fix `function-calc-no-unspaced-operator` false negatives for some math functions

---

.changeset/flat-bananas-hug.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-type-no-unknown/__tests__/index.mjs
lib/utils/isCustomElement.cjs
lib/utils/isCustomElement.mjs

check the "concrete example" in #7510
compare https://github.com/sindresorhus/html-tags/blob/main/html-tags.json and https://github.com/sindresorhus/html-tags/commit/d3b931ee8dc7c5bbbe20761ebbe4dad257cf39bc
- `selectlist`: https://github.com/openui/open-ui/issues/773#issuecomment-1664421419
- `listbox`: https://issues.chromium.org/issues/40146374#comment98
- `portal`: https://caniuse.com/mdn-html_elements_portal
- for the rest check https://developer.mozilla.org/en-US/docs/Web/HTML/Element/
I chose not to include the previous names of the tag names that I am introducing; we need to settle #7510 first.
e.g. not `selectmenu`

Fix `selector-type-no-unknown` false positives for experimental and deprecated HTML tags

---

.changeset/selfish-plums-dream.md
.changeset/sharp-buses-drop.md
lib/reference/properties.cjs
lib/reference/properties.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs

Closes #7232
To understand why a fix is being accompanied by an option check the discussion starting with https://github.com/stylelint/stylelint/issues/7232#issuecomment-1762654301
tl;dr: CSS Text Decoration Module Level 3 vs CSS Text Decoration Module Level 4 means that a granular option is necessary for the `text-decoration` fix not be considered a downgrade

Add `ignoreLonghands: []` to `declaration-block-no-redundant-longhand-properties`

---

.changeset/large-olives-press.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs

Fix `declaration-block-no-redundant-longhand-properties` autofix conflicts

---

docs/user-guide/rules.md

There is an extra column in some tables:
- [Max & min](https://stylelint.io/user-guide/rules#max--min)
- [Pattern](https://stylelint.io/user-guide/rules#pattern)

Remove extra column in some tables in Rules docs

---

.github/workflows/testing.yml

None.
At this point, `"current"` equals `"22"` for Node.js versions.
See also https://nodejs.org/en/blog/announcements/v22-release-announce

Specify version number for Node.js 22 on CI

---

.husky/pre-push
rollup.config.mjs

None.
This aims to prevent us from forgetting commits of built files (`*.cjs`).
Additionally, this lower the log level of Rollup.
Example:
```sh-session
$ git push
...
You must commit the following files:
lib/utils/matchesStringOrRegExp.cjs
husky - pre-push script failed (code 1)
error: failed to push some refs to 'https://github.com/stylelint/stylelint.git'
```
If you want to bypass the pre-push hook, use `--no-verify`:
```sh-session
$ git push --no-verify
```

Check uncommitted build files on pre-push

---

lib/utils/matchesStringOrRegExp.cjs
lib/utils/matchesStringOrRegExp.mjs

None.
This change aims to improve readability in the `matchesStringOrRegExp()` utility module.

Refactor `matchesStringOrRegExp()` utility

---

.changeset/serious-bees-burn.md
lib/reference/prefixes.cjs
lib/reference/prefixes.mjs
lib/rules/value-no-vendor-prefix/README.md
lib/rules/value-no-vendor-prefix/__tests__/index.mjs
lib/utils/isAutoprefixable.cjs
lib/utils/isAutoprefixable.mjs

related to #7624
While working on #7624 I realised how the rule was intended to work. We can't change that behaviour after the fact.
It reports if the value can be unprefixed safely, else it bails-out.
**In practice this is what you want and actually that's better for us: we don't have to update `stylelint-config-standard` with an `-apple-system` exception anymore because it is not an unprefixable value.**
This PR mainly fixes the documentation and some false negatives.
We can close #7624 after that because it's not on scope with the rule.
I didn't add all the missing values; I might some day.
I couldn't find use cases for `-konq-` so I left it out.

Fix `value-no-vendor-prefix` false negatives

---

.changeset/hungry-teachers-bow.md
lib/rules/value-no-vendor-prefix/README.md
lib/rules/value-no-vendor-prefix/__tests__/index.mjs
lib/utils/isAutoprefixable.cjs
lib/utils/isAutoprefixable.mjs

follow-up of #7654
- unprefixed value doesn't exist
- [autoprefixer](https://github.com/postcss/autoprefixer/blob/main/test/cases/flexbox.out.css), [whatwg](https://compat.spec.whatwg.org/#css-keyword-mappings)
- `-khtml-box`, `-moz-box` and `-webkit-box`
- `-moz-inline-box`, `-ms-inline-flexbox` and `-webkit-inline-box`
- https://caniuse.com/intrinsic-width
- `-moz-available`
- `-webkit-fill-available`
- https://caniuse.com/css-crisp-edges
- Opera only supported `-o-crisp-edges` (i.e. not `-o-pixelated`)
- `-webkit-optimize-contrast`
- https://caniuse.com/mdn-css_properties_unicode-bidi_plaintext
- `-webkit-plaintext` was missing
I reviewed each values one by one.

Fix `value-no-vendor-prefix` false positives/negatives

---

.changeset/famous-deers-build.md
lib/rules/shorthand-property-no-redundant-values/__tests__/index.mjs
lib/rules/shorthand-property-no-redundant-values/index.cjs
lib/rules/shorthand-property-no-redundant-values/index.mjs
lib/utils/typeGuards.cjs
lib/utils/typeGuards.mjs

Ref #7656
I think supporting all functions makes sense, including ~~`var()`~~ or `calc()` etc.
-> Dropped `var()` support. See https://github.com/stylelint/stylelint/issues/7656#issuecomment-2079826514

Fix `shorthand-property-no-redundant-values` false negatives for functions

---

lib/rules/function-calc-no-unspaced-operator/__tests__/index.mjs
lib/rules/function-calc-no-unspaced-operator/index.cjs
lib/rules/function-calc-no-unspaced-operator/index.mjs

Closes #7618
<hr />
@ybiquitous This rule and the implementation was a lot more complex that I originally thought it would be. Doing pure code review was tricky for me and I needed to take a deep dive.
_The code in this PR is a mess, but it also isn't intended to be used as is.
It can be used, we can continue work from this. But I haven't spend much time on self-review to get it into a really good state._
As I understand it know there are multiple issues and layers.
Steps:
1. Fix units : `10px-20px` -> `10px -20px` (`px-20px` is the entire unit here)
2. Fix missing operators : `10px -20px` -> `10px -|20px` (`|` to indicate that these are separate)
3. Insert whitespace : `10px -|20px` -> `10px - 20px`
4. Normalize whitespace : `10px -\t20px` …

Add support for multi-argument functions to `function-calc-no-unspaced-operator`

---

lib/rules/function-calc-no-unspaced-operator/__tests__/index.mjs
lib/rules/function-calc-no-unspaced-operator/index.cjs
lib/rules/function-calc-no-unspaced-operator/index.mjs
lib/utils/typeGuards.cjs
lib/utils/typeGuards.mjs
package-lock.json
package.json

See : https://github.com/stylelint/stylelint/pull/7655
- Switch to upstream type guards
- Use the ident and unit mutation helpers from `@csstools/css-tokenizer`
- Also support trailing `-` found in ident tokens `calc(g- 10px)`

Fix `function-calc-no-unspaced-operator` unit and ident escaping

---

lib/augmentConfig.cjs
lib/augmentConfig.mjs
lib/reference/properties.cjs
lib/reference/properties.mjs
lib/rules/alpha-value-notation/index.cjs
lib/rules/alpha-value-notation/index.mjs
lib/rules/number-max-precision/index.cjs
lib/rules/number-max-precision/index.mjs
lib/rules/value-no-vendor-prefix/index.cjs
lib/rules/value-no-vendor-prefix/index.mjs
lib/utils/getCacheFile.cjs
lib/utils/getCacheFile.mjs
lib/utils/getFileIgnorer.cjs
lib/utils/getFileIgnorer.mjs

N/A
- eslint-plugin-perf-standard/check-function-inline for 3 functions
- 2 try…catch refactors
- 1 typo

Refactor to slightly simplify the code

---

lib/rules/selector-max-attribute/index.cjs
lib/rules/selector-max-attribute/index.mjs
lib/rules/selector-max-class/index.cjs
lib/rules/selector-max-class/index.mjs
lib/rules/selector-max-combinators/index.cjs
lib/rules/selector-max-combinators/index.mjs
lib/rules/selector-max-compound-selectors/index.cjs
lib/rules/selector-max-compound-selectors/index.mjs
lib/rules/selector-max-id/index.cjs
lib/rules/selector-max-id/index.mjs
lib/rules/selector-max-pseudo-class/index.cjs
lib/rules/selector-max-pseudo-class/index.mjs
lib/rules/selector-max-type/index.cjs
lib/rules/selector-max-type/index.mjs
lib/rules/selector-max-universal/index.cjs
lib/rules/selector-max-universal/index.mjs
lib/rules/selector-not-notation/index.cjs
lib/rules/selector-not-notation/index.mjs

None
`isStandardSyntaxRule` already calls `isStandardSyntaxSelector`.
see : https://github.com/stylelint/stylelint/blob/main/lib/utils/isStandardSyntaxRule.mjs#L19

Refactor to remove redundant calls to `isStandardSyntaxSelector`

---

lib/rules/selector-max-universal/index.cjs
lib/rules/selector-max-universal/index.mjs

None
This rule no longer uses `postcss-resolve-nested-selector` directly.
Removing this part of the comment to:
- make it easier to search for "postcss-resolve-nested-selector" and get relevant results
- avoid confusion after the planned changes to `flattenNestedSelectorsForRule` in a later major

Refactor to remove reference to `postcss-resolve-nested-selector`

---

lib/formatters/jsonFormatter.cjs
lib/formatters/jsonFormatter.mjs

`JSON.stringify` has a second argument for filtering output. So we can easily simplify this function without reduce, filter, Object.entries.

Refactor to jsonFormatter

---

.changeset/eight-falcons-scream.md
lib/rules/selector-not-notation/__tests__/index.mjs
lib/rules/selector-not-notation/index.cjs
lib/rules/selector-not-notation/index.mjs

N/A
While I was working on #2643 I uncovered a bug.
`:not()` is mostly used as a suffix so no one reported it.
@ybiquitous  we should release once that's merged.
i.e. `foo:not()` is not affected

Fix `selector-not-notation` autofix of the `"simple"` option

---

.changeset/tricky-pigs-talk.md
CONTRIBUTING.md
package-lock.json
package.json

We forgot to add our [GitHub Sponsor](https://github.com/sponsors/stylelint) to `package.json` (`funding`) when we started it.
```sh-session
$ npm fund stylelint
1: opencollective funding available at the following URL: https://opencollective.com/stylelint
2: github funding available at the following URL: https://github.com/sponsors/stylelint
Run `npm fund [<package-spec>] --which=1`, for example, to open the first funding URL listed in that package
```
In addition, this improves the financial section in the contribution guide:
- Add GitHub Sponsor
- Simplify links to Open Collective, including unsupported `#backer` or `#sponsor`
None.
I've also added a changelog item so that …

Fix missing GitHub Sponsor for `npm fund`

---

.github/dependabot.yml

Closes #7695
We cannot bump `eslint` to v9 until all dependent plugins support v9.

Temporarily exclude `eslint` from Dependabot group updates

---

.changeset/hot-pens-joke.md
lib/rules/no-descending-specificity/__tests__/index.mjs
lib/rules/no-descending-specificity/index.cjs
lib/rules/no-descending-specificity/index.mjs

Closes https://github.com/stylelint/stylelint/issues/7723
We didn't have coverage for nested selectors where the nested part is the same while the parent is different.
I should have double checked this when refactoring this rule.
I am certain that this case is very common.
Do we have capacity to ship a patch in the next few days?

Fix `no-descending-specificity` false positives for nested selectors

---

.prettierignore

None.
The `.gitignore` file already has the same setting:
https://github.com/stylelint/stylelint/blob/62b58bc2616fd1420c0adb7090e1e3c03b64597a/.gitignore#L10

Ignore `tmp/` from Prettier

---

lib/__tests__/disableRanges.test.mjs
lib/assignDisabledRanges.cjs
lib/assignDisabledRanges.mjs
lib/lintPostcssResult.cjs
lib/lintPostcssResult.mjs
lib/lintSource.cjs
lib/lintSource.mjs
lib/rules/no-duplicate-selectors/__tests__/index.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/__tests__/validateOptions.test.mjs
lib/utils/checkAgainstRule.cjs
lib/utils/checkAgainstRule.mjs
lib/utils/report.cjs
lib/utils/report.mjs
lib/utils/validateOptions.cjs
lib/utils/validateOptions.mjs

Ref #7706
When reviewing PR #7706, I noticed that we can reduce the repetitive initialization of the `PostcssResult.stylelint` property. This refactoring PR will help us easily add a new property to `PostcssResult.stylelint` in the future.
See also the type definitions:
- https://github.com/stylelint/stylelint/blob/d902c0b7cc1233b74cc4959eff864cb3e2d87f73/types/stylelint/index.d.ts#L178-L181
- https://github.com/stylelint/stylelint/blob/d902c0b7cc1233b74cc4959eff864cb3e2d87f73/types/stylelint/index.d.ts#L156-L168

Refactor to simplify initialization of `PostcssResult.stylelint` property

---

lib/rules/keyframe-selector-notation/index.cjs
lib/rules/keyframe-selector-notation/index.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/report.cjs
lib/utils/report.mjs
types/stylelint/index.d.ts

#7730 and #7192
What was actually missing wasn't the original range but the range of the replaced text.
i.e. `fix` return type is now `void | never | Range`
Returning the new range from the fixer is not a hard requirement for refactors though.
Nothing was exploiting `range` yet so it's safe.
Ill stop sending new rule refactor PRs until this is merged.
see discussion starting with https://github.com/stylelint/stylelint/issues/7192#issuecomment-2159321591

Save range of replaced text instead of range of original text in `report()`

---

.changeset/selfish-birds-smash.md
lib/reference/atKeywords.cjs
lib/reference/atKeywords.mjs

Closes #7750 
No, it's self-explanatory. Only adds view-transition to the list of known keywords.
Apologies if I missed something!

Fix `at-rule-no-unknown` false positives for `@view-transition`

---

package.json

This `reportUnusedDisableDirectives` option reports unused `// eslint-disable` comments.
For example, assume the following JS file:
```js
const a = 1; // eslint-disable-line no-unused-vars
a;
```
Run ESLint with this option on or off:
```sh-session
$ npx eslint tmp/eslint-test.js
(success)
$ npx eslint tmp/eslint-test.js
/Users/masafumi.koba/git/stylelint/stylelint/tmp/eslint-test.js
1:14  warning  Unused eslint-disable directive (no problems were reported from 'no-unused-vars')
```
None.

Refactor to turn on `reportUnusedDisableDirectives` for ESLint

---

lib/rules/comment-whitespace-inside/index.cjs
lib/rules/comment-whitespace-inside/index.mjs

#2643
It used to fix both sides for `"always"` regardless of the current `complain`.
i.e. in certain cases it was attempting 2 more fixes for nothing

Refactor `comment-whitespace-inside` to use `fix` callback instead of `context.fix`

---

.changeset/three-cars-pull.md
lib/reference/properties.cjs
lib/reference/properties.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.mjs
types/stylelint/index.d.ts

Closes https://github.com/stylelint/stylelint/issues/7620
Hi, I have updated the properties file and added few tests, let me know if there is anything missing or can be improved

Fix `declaration-block-no-redundant-longhand-properties`/`declaration-block-no-shorthand-property-overrides` false negatives for `font-variant`

---

.changeset/silly-insects-ring.md
lib/rules/selector-no-vendor-prefix/__tests__/index.mjs
lib/rules/selector-no-vendor-prefix/index.cjs
lib/rules/selector-no-vendor-prefix/index.mjs

#4856
1.
[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICWA7ADgVwC73gWgFsBnPMAGxgEMAnAAgGpbVMd8CIAvPNMysGABYQysOsAC+AHRQgANCABmSCgDlKBOIhgAPdTxgA6MESJzwEFEoDmCEMGm1akkNQwUiz+LXspHj50QwFGBYENR4KBB4AG4wKFBh3NQwStqetFiuMA60UijiZpCWSFYAYmEElFi2AFZEFmawaKaIPv4gRFgAnhRkqFjpzrxYMJ3OsjkB3b39pBbWeJ2U8TRQgyDDowMg0gXiQA)
2.
A node of type `"pseudo"` cannot be passed directly to `report`.
3.
codecov can be ignored.

Fix `selector-no-vendor-prefix` autofix

---

.changeset/afraid-windows-play.md
lib/rules/at-rule-no-vendor-prefix/index.cjs
lib/rules/at-rule-no-vendor-prefix/index.mjs
lib/utils/__tests__/isAutoprefixable.test.mjs
lib/utils/isAutoprefixable.cjs
lib/utils/isAutoprefixable.mjs

#2643
- false negatives
- `@-moz-document`: https://developer.mozilla.org/en-US/docs/Web/CSS/@document#browser_compatibility
- `@-webkit-viewport`
- https://trac.webkit.org/browser/webkit/trunk/LayoutTests/css3/device-adapt/viewport-at-rule-parsing.html?rev=133084
- https://github.com/WebKit/WebKit/commit/faab0fc796cf0ac3af2a05f928f032d433d3a726
- don't exist
- `@resolution`
- https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L815-L823
- https://caniuse.com/css-media-resolution
- `@-khtml-keyframes`
- https://github.com/postcss/autoprefixer/blob/main/data/prefixes.js#L109
- https://github.com/postcss/autoprefixer/commit/fa4d7263ce9e6a3792201577d57ebcfdce8afde9

Refactor `at-rule-no-vendor-prefix` to use `fix` callback instead of `context.fix` and fix false negatives

---

.changeset/lucky-grapes-listen.md
lib/reference/atKeywords.cjs
lib/reference/atKeywords.mjs
lib/rules/at-rule-no-unknown/__tests__/index.mjs

#1515
1.
`@historical-forms` was added after #1537 was merged.
ref: https://www.w3.org/TR/2018/WD-css-fonts-4-20180920/#font-feature-values-syntax
2.
[`@font-palette-values`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-palette-values)

Fix `at-rule-no-unknown` false positives for `@historical-forms` and `@font-palette-values`

---

.github/workflows/testing.yml

Ref #7777
This aims to avoid codecov-action upload failures in a PR by forked repositories. The old Codecov CLI version is used, instead of `latest`.
See also https://github.com/codecov/codecov-action/issues/1487

Add workaround for codecov-action

---

.changeset/khaki-eels-love.md
.github/workflows/testing.yml
lib/reference/keywords.cjs
lib/reference/keywords.mjs
lib/rules/font-family-name-quotes/__tests__/index.mjs
lib/rules/font-family-name-quotes/index.cjs
lib/rules/font-family-name-quotes/index.mjs

#2643
ref
https://github.com/WebKit/WebKit/blob/main/Source/WebCore/css/CSSValueKeywords.in
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266-font
https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions#font-family
http://help.dottoro.com/lclmgrtl.php
https://groups.google.com/a/chromium.org/g/blink-dev/c/TVRkV9XrFGo

Refactor `font-family-name-quotes` to use `fix` callback instead of `context.fix` and fix false negatives

---

lib/rules/selector-attribute-quotes/index.cjs
lib/rules/selector-attribute-quotes/index.mjs

#2643
nit
off-topic
`color-hex-alpha` and `no-irregular-whitespace` should be refactored to follow the `rejected` convention

Refactor `selector-attribute-quotes` to use `fix` callback instead of `context.fix`

---

lib/rules/no-invalid-double-slash-comments/index.cjs
lib/rules/no-invalid-double-slash-comments/index.mjs
lib/rules/selector-no-vendor-prefix/index.cjs
lib/rules/selector-no-vendor-prefix/index.mjs
lib/utils/report.cjs
lib/utils/report.mjs

Closes #7779
This PR
1. revert this change
```diff
-rangeBy({ index, endIndex })
+rangeBy({ index, endIndex, word })
```
2. addresses the recent changes that assumed that `index` would shift the search for the needle when used with `word`
</hr>
As an aside, we have legitimate cases where passing just `node` is simpler than passing let's say `node`+`word`.
e.g. if we have to take into account the last semicolon
i.e. we cannot be as strict as not allowing passing `word` or at least it won't be covered by that PR

Refactor to remove `word` from the object passed to `rangeBy` in `report` util

---

.changeset/quick-gifts-shop.md
lib/rules/function-no-unknown/index.cjs
lib/rules/function-no-unknown/index.mjs
lib/utils/mathMLTags.cjs
lib/utils/mathMLTags.mjs
tsconfig.json

None.
I happened to notice this chance for performance improvement.
In the `(root, result) => {}` function, `fs.readFileSync()` is called many times for each scanned file.
However, `functionsList` is immutable, so we can call it only once.
Benchmark:
```sh-session
$ cat tmp/stylelint.config.mjs
export default {
rules: { 'function-no-unknown': true },
};
$ cat tmp/test.css
a {
width: cal(1 + 2);
}
$ for i in $(seq 1 1000); do cp tmp/test.css "tmp/test-${i}.css"; done
$ time bin/stylelint.mjs -c tmp/stylelint.config.mjs "tmp/*.css" 2>/dev/null
```
On the main branch:
```
0.92s user 0.32s system 133% cpu 0.928 total
```
On this branch:
```
0.88s user 0.29s system 132% cpu 0.878 …
```

Fix `function-no-unknown` performance by reducing file read count

---

lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs

Refactor `declaration-block-no-redundant-longhand-properties` to use `fix` callback instead of `context.fix`

---

docs/developer-guide/rules.md

Change summary:
- Add `@csstools/css-parser-algorithms`, `@csstools/css-tokenizer`, and `css-tree` that we have used heavily.
- Unify the package link URLs to `https://www.npmjs.com`.
See also:
```sh-session
$ npm ls | grep -E '@csstools|css-tree'
├── @csstools/css-parser-algorithms@2.6.3
├── @csstools/css-tokenizer@2.3.1
├── @csstools/media-query-list-parser@2.1.11
├── @csstools/selector-specificity@3.1.1
├── @types/css-tree@2.3.8
├── css-tree@2.3.1
```

Add recommended parser packages to developer guide

---

.github/workflows/testing.yml

Reverts stylelint/stylelint#7778
Closes #7783
Closes #7804 
The new CLI version is released: https://github.com/codecov/codecov-cli/releases/tag/v0.7.1
See also https://github.com/codecov/codecov-action/issues/1487

Revert "Add workaround for codecov-action"

---

lib/__tests__/fixtures/plugin-fixer-buggy.mjs
lib/__tests__/fixtures/plugin-fixer.mjs
lib/__tests__/fixtures/plugin-fixes.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/report.cjs
lib/utils/report.mjs

Related to #7784
This change aims to prevent inconsistency between `fixable` metadata and `fix` callback.
> [!NOTE]
> The `fix` callback is not published yet, so this PR doesn't need a changelog entry.

Require `meta.fixable` to be truthy when using `fix` callback for `report()`

---

.changeset/slow-timers-relax.md
lib/reference/keywords.cjs
lib/reference/keywords.mjs
lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.mjs

N/A
This _might_ impact these rules:
- `font-family-name-quotes`
- `font-family-no-duplicate-names`
- `font-family-no-missing-generic-family-keyword`
https://github.com/stylelint/stylelint/blob/4ccec36357b9669f1ea5158c5fd2be10f434c1e8/lib/utils/findFontFamily.mjs#L75-L91
> References
https://developer.mozilla.org/en-US/docs/Web/CSS/font
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size

Update `fontSizeKeywords` set and fix `fontShorthandKeywords` set

---

.changeset/short-goats-mix.md
lib/rules/no-duplicate-selectors/__tests__/index.mjs
lib/utils/__tests__/checkAgainstRule.test.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/checkAgainstRule.cjs
lib/utils/checkAgainstRule.mjs
lib/utils/report.cjs
lib/utils/report.mjs

Follow-up to PR #7730
To make the `fix` callback work with `utils.checkAgainstRule()`, we need to use `result.stylelint` in `checkAgainstRule()` because `report()` now depends on `result.stylelint.config.fix` instead of `context.fix`.
See:
https://github.com/stylelint/stylelint/blob/2dfe7cea14159b536b83a35ab9423cd643b36a7e/lib/utils/report.mjs#L174

Fix `utils.checkAgainstRule()` to support `fix` callback in `utils.report()`

---

lib/rules/function-calc-no-unspaced-operator/__tests__/index.mjs
lib/rules/function-calc-no-unspaced-operator/index.cjs
lib/rules/function-calc-no-unspaced-operator/index.mjs

Each mutation of the AST now corresponds to a single warning and a single fix.
See : https://github.com/stylelint/stylelint/pull/7831
The order of the warnings changes, but I hope this is fine?

Refactor `function-calc-no-unspaced-operator` to have atomic fixes

---

lib/rules/function-calc-no-unspaced-operator/__tests__/index.mjs
lib/rules/function-calc-no-unspaced-operator/index.cjs
lib/rules/function-calc-no-unspaced-operator/index.mjs
lib/utils/__tests__/checkAgainstRule.test.mjs

Part of #2643
This PR aims to perform refactoring for #2643. But, this work was not as easy as just replacing `context.fix` with the `fix` callback. Before switching to the `fix` callback, I needed a big refactoring to rewrite the code to class-based logic for the code readability. Please look at each commit for details.

Refactor `function-calc-no-unspaced-operator` to use `fix` callback instead of `context.fix`

---

.changeset/pretty-crabs-battle.md
lib/__tests__/standalone-deprecations.test.mjs
lib/prepareReturnValue.cjs
lib/prepareReturnValue.mjs
lib/standalone.cjs
lib/standalone.mjs

This change fixes `quietDeprecationWarnings: true` to suppress the `stylelint:003` warning.
For example:
```js
// test.mjs
import stylelint from 'stylelint';
const result = await stylelint.lint({
code: 'a {}',
config: { rules: {} },
quietDeprecationWarnings: true,
});
console.log(result.output);
```
When running before this change, the warning is shown regardless of `quietDeprecationWarnings: true`:
```sh-session
$ node test.mjs
[{"source":"<input css B6wTu8>","deprecations":[],"invalidOptionWarnings":[],"parseErrors":[],"errored":false,"warnings":[]}]
(node:30570) [stylelint:003] DeprecationWarning: `output` is deprecated.
Use `report` or `code` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
When running after this change, no warning is shown: …

Fix `quietDeprecationWarnings` to suppress with `stylelint:003` warning

---

docs/developer-guide/formatters.md
docs/developer-guide/plugins.md

Related to #7838
These keywords would help us find packages more easily.
Common keywords: `stylelint-plugin`, `stylelint-config`, `stylelint-formatter`
See:
- https://www.npmjs.com/search?q=keywords%3Astylelint-plugin
- https://www.npmjs.com/search?q=keywords%3Astylelint-config
- https://www.npmjs.com/search?q=keywords%3Astylelint-formatter

Encourage using common keywords for plugins, configs, and formatters in documentation

---

.changeset/grumpy-insects-compete.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs

Fix `selector-pseudo-class-no-unknown` false positives for `:active-view-transition` and `:active-view-transition-type()`

---

.changeset/rewrite-changelog.mjs

None.
This PR will sorts the order:
https://github.com/stylelint/stylelint/blob/ac1d085255f355c90c64e48468958d85495edb21/CHANGELOG.md?plain=1#L6-L9

Improve rewriting changelog to sort items with the same prefixes

---

docs/maintainer-guide/releases.md

Ref https://github.com/stylelint/stylelint/issues/7880#issuecomment-2254217924
See https://github.com/stylelint/stylelint-ecosystem-tester

Document to add ecosystem test check in releasing task list

---

.changeset/cold-months-notice.md
lib/rules/no-duplicate-selectors/__tests__/index.mjs
lib/rules/no-duplicate-selectors/index.cjs
lib/rules/no-duplicate-selectors/index.mjs

Closes https://github.com/stylelint/stylelint/issues/7887
`flattenNestedSelectorsForRule` can return an empty list on invalid syntax.
This forgiving behavior is intended as it also allows us to lint partially standard selector lists.
However in `no-duplicate-selectors` we also use these lists (after normalizing) to detect duplicates. And when the entire list is non-standard the resulting selector will be an empty string.
Each empty string is equal to any other empty string, so in turn each non-standard selector list is considered a duplicate of every other non-standard selector list.
Adding a check that `flattenNestedSelectorsForRule` did return at least one selector resolves any …

Fix `no-duplicate-selectors` false positives with Less syntax

---

.changeset/giant-days-play.md
lib/rules/no-invalid-double-slash-comments/__tests__/index.mjs
lib/rules/no-invalid-double-slash-comments/index.cjs
lib/rules/no-invalid-double-slash-comments/index.mjs

I also noticed that rules were eagerly serialized, this is quite expensive.
This change:
```
;node benchmark-rule.mjs no-invalid-double-slash-comments 'true'                               
Warnings: 0
Mean: 95.35613458823532 ms
Deviation: 9.862092026552252 ms
```
Main:
```
;node benchmark-rule.mjs no-invalid-double-slash-comments 'true'
Warnings: 0
Mean: 118.80464825 ms
Deviation: 23.471924727353816 ms
```

Fix `no-invalid-double-slash-comments` reported ranges

---

.changeset/strange-nails-give.md
lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs
lib/rules/custom-property-no-missing-var-function/index.cjs
lib/rules/custom-property-no-missing-var-function/index.mjs

https://github.com/stylelint/stylelint/issues/7911#issuecomment-2278017759
N/A

Fix `custom-property-no-missing-var-function` false positives for `view-transition-name`

---

rollup.config.mjs

We found this issue in <https://github.com/stylelint/stylelint/pull/7918#issuecomment-2283016175>.
This change eliminates *all* `.cjs` files before the build to prevent us from forgetting to delete unused `.cjs` files.
Verification:
```shell
echo "export default 'foo';" > lib/foo.mjs
npm run build
git add lib/foo.*
git commit -m 'add lib/foo module'
rm lib/foo.mjs
npm run build
npm run build-check
```
Then, we see the following message:
```
You must commit the following files:
lib/foo.cjs
lib/foo.mjs
```

Fix `.cjs` files clean up

---

lib/formatters/__tests__/compactFormatter.test.mjs
lib/formatters/__tests__/githubFormatter.test.mjs
lib/formatters/__tests__/stringFormatter.test.mjs
lib/formatters/__tests__/tapFormatter.test.mjs
lib/formatters/__tests__/unixFormatter.test.mjs
types/stylelint/index.d.ts

slightly related to #7845
1. There are 2 places where we set `stylelintType` to `'parseError'`:
https://github.com/stylelint/stylelint/blob/860acdccb666ee3429d8509e596ce81708448b3f/lib/utils/transformSelector.mjs#L13
https://github.com/stylelint/stylelint/blob/860acdccb666ee3429d8509e596ce81708448b3f/lib/utils/parseSelector.mjs#L22
I chose the first one for the formatter tests.
i.e. the second one would have 2 parentheses
https://github.com/stylelint/stylelint/blob/860acdccb666ee3429d8509e596ce81708448b3f/lib/formatters/preprocessWarnings.mjs#L39
The tests wouldn't fail without these changes; I just thought it would be more accurate.
2. `Result.Message`'s index signature is `any` …

Refactor to add `WarningOptions.StylelintWarningType` union type

---

.changeset/famous-glasses-trade.md
lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
lib/rules/declaration-property-value-no-unknown/index.cjs
lib/rules/declaration-property-value-no-unknown/index.mjs

Closes #6667
Closes #7939
[I warned about the very situation we are in](https://github.com/stylelint/stylelint/pull/6511#issuecomment-1407586913) when we were adding this rule.
I was getting impatient so I went ahead and fixed some false positives.
If `css-tree` eventually catches up, we will remove the default extension.
I only added properties that have at least some browser support.
i.e. not block-step-insert, block-step-size, line-fit-edge, text-autospace, text-group-align, etc.
https://caniuse.com/css-text-box-trim
https://caniuse.com/mdn-css_properties_text-spacing-trim
https://caniuse.com/mdn-css_properties_text-wrap-style …

Fix `declaration-property-value-no-unknown` false positives

---

.changeset/stupid-walls-glow.md
lib/rules/selector-no-qualifying-type/__tests__/index.mjs
lib/rules/selector-no-qualifying-type/index.cjs
lib/rules/selector-no-qualifying-type/index.mjs
lib/utils/flattenNestedSelectorsForRule.cjs
lib/utils/flattenNestedSelectorsForRule.mjs
system-tests/002/__snapshots__/fs.test.mjs.snap
system-tests/002/__snapshots__/no-fs.test.mjs.snap

See:
- https://github.com/stylelint/stylelint/issues/7904
- https://github.com/stylelint/stylelint/issues/6234
This was the last one in this series and I was still unhappy with the reduced precision of reported ranges for regular, not-nested, selectors.
For all nested selectors it becomes impossible to know if the problematic part of the selector appears exactly in the same form in source or if it was artificially constructed when resolving the nested selector. So it also becomes impossible to have a report range for a part of a selector.
However this restriction only exists for nested selectors.
I've added a boolean flag to `flattenNestedSelectorsForRule` so that we have better …

Fix `selector-no-qualifying-type` reported ranges

---

docs/about/semantic-versioning.md

Related to <https://github.com/stylelint/stylelint/pull/7895#issuecomment-2304280449> by @silverwind
This change aims to prevent us from releasing incorrect patch versions in the future when introducing a new deprecation.
According to <https://semver.org/#how-should-i-handle-deprecating-functionality>:
> issue a new minor release with the deprecation in place

Update semantic-versioning.md for new deprecations

---

lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
lib/rules/declaration-property-value-no-unknown/index.cjs
lib/rules/declaration-property-value-no-unknown/index.mjs

follow-up of #7944
[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilTNgAsIAnAWkyQFsZ4BuLHANwEsYB3UgF2eoBtnMMUkgAezAM7wUAMwgR62FC3ZceMfoNIDxMTlNnyGS1h258BQitTpHlptRpoy5Cpia7E845twiZyVE4GCgC+WCAANCDSzLwwAHKBCCAwIlQADnEAdGDi4pHgfjEA5skYiuggxACuceKVUuU4OJWwYLxInr7+6cQQ6TDEnACepIxIvNWWEKTVmADWmBBsmA0onDUwRmGYIQWQmCUAYiSUSJzJAFbifgWw6fmITSiV4iNxGpxrlR2cMG+VCJGV7vdQCTikA4lUhvPBQTpQb4gX7-L4gLB7EJAA)
https://caniuse.com/mdn-css_properties_view-transition-name
https://caniuse.com/?search=view-timeline
https://caniuse.com/mdn-css_properties_anchor-name
https://csstree.github.io/docs/validator.html
The changeset of #7944 will be modified in #7946 to include #7957.
see …

Fix `declaration-property-value-no-unknown` false negatives

---

types/stylelint/index.d.mts
types/stylelint/index.d.ts

see https://github.com/stylelint/stylelint/pull/7954#discussion_r1731601791 and https://github.com/stylelint/stylelint/pull/7954#discussion_r1731266595
`index.d.mts` exposed too many types.

Change `PublicApi['rules']` type

---

types/stylelint/index.d.ts

https://github.com/stylelint/stylelint/pull/7954#discussion_r1731291043 and https://github.com/stylelint/stylelint/pull/7954#discussion_r1731611549
This PR switch from the documentation to the implementation as the source of truth for the type of the rules.
This is required if we want to validate configs in the wild.
e.g. ESLint has [`defineConfig`](https://github.com/eslint-types/eslint-define-config)
#7954 was not controversial because it was just reflecting the documentation.
Now that we are planning to actually use the type, it needs to be accurate.
e.g. for `PublicApi['rules']` or to auto-generate the documentation
i.e. you should consider this PR a documentation fix because in the long run it will be
There's a convention which a lot …

Refactor to fix `CoreRules` type inconsistencies

---

.changeset/fair-crews-think.md
lib/rules/value-no-vendor-prefix/__tests__/index.mjs
lib/rules/value-no-vendor-prefix/index.cjs
lib/rules/value-no-vendor-prefix/index.mjs
types/stylelint/index.d.ts

see exceptions section of https://github.com/stylelint/stylelint/pull/7967#issue-2489168630
```diff
-               'value-no-vendor-prefix': CoreRule<true, { ignoreValues: Array<StringOrRegex> }>;
+               'value-no-vendor-prefix': CoreRule<true, { ignoreValues: OneOrMany<StringOrRegex> }>;
```

Add support for `string | RegExp` to `ignoreValues` option of `value-no-vendor-prefix`

---

.changeset/clever-cycles-share.md
lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs
types/stylelint/index.d.ts

see exceptions section of https://github.com/stylelint/stylelint/pull/7967#issue-2489168630
```diff
-                               ignoreLonghands: string[];
+                               ignoreLonghands: OneOrMany<string>;
```

Add support for `string` to `ignoreLonghands` option of `declaration-block-no-redundant-longhand-properties`

---

docs/developer-guide/formatters.md
docs/developer-guide/rules.md
docs/migration-guide/to-14.md
docs/user-guide/configure.md
lib/rules/declaration-property-max-values/README.md
lib/rules/no-empty-source/README.md
lib/rules/selector-disallowed-list/README.md
lib/rules/selector-max-attribute/README.md
lib/rules/selector-nested-pattern/README.md
lib/rules/string-no-newline/README.md

Summary:
- Fix syntax errors (thanks to [`remark-lint-code-block-syntax`](https://www.npmjs.com/package/remark-lint-code-block-syntax))
- Make code examples more consistent in `user-guide/configure.md`
To verify syntax, temporarily update `package.json` and run `npm i && npm run lint:md`:
```diff
--- a/package.json
+++ b/package.json
@@ -118,7 +118,8 @@
},
"remarkConfig": {
"plugins": [
-      "@stylelint/remark-preset"
+      "@stylelint/remark-preset",
+      "remark-lint-code-block-syntax"
]
},
"jest": {
@@ -239,6 +240,7 @@
"postcss-sass": "^0.5.0",
"postcss-scss": "^4.0.9",
"remark-cli": "^12.0.1",
+    "remark-lint-code-block-syntax": …
```

Fix code block in Markdown documents

---

lib/rules/no-descending-specificity/README.md

Closes https://github.com/stylelint/stylelint/issues/3052

Document `!important` caveat in `no-descending-specificity`

---

README.md

I want to respect and be thankful for them, but there is no proper place for us to do that now.
For example, the Rust team mentions its alumni in this document:
https://www.rust-lang.org/governance/teams/leadership-council

Document alumni in README

---

.changeset/many-baboons-care.md
lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs
lib/rules/declaration-property-value-no-unknown/index.cjs
lib/rules/declaration-property-value-no-unknown/index.mjs
package-lock.json
package.json

Close #7995
- [Release notes](https://github.com/csstree/csstree/releases/tag/v3.0.0)
- [Commits](https://github.com/csstree/csstree/compare/v2.3.1...v3.0.0)
Unknown properties are ignored by `declaration-property-value-no-unknown`.
i.e. most regressions will be picked up by `reject`, not `accept`
It doesn't c l o s e #7964 because `position-try-options` is still unknown.

Bump css-tree from 2.3.1 to 3.0.0

---

.changeset/funny-pets-cover.md
lib/rules/selector-anb-no-unmatchable/__tests__/index.mjs
lib/rules/selector-anb-no-unmatchable/index.cjs
lib/rules/selector-anb-no-unmatchable/index.mjs

The reported ranges for this rule were incorrect in various ways :)
Most impactful was the use of `column` instead of `offset` leading to cases like these: https://stylelint.io/demo/#N4Igxg9gJgpiBcICG8B2AXAFgWjJglgDZQAUADAJQA0AOqgEZpa4HHnV1hM55GmXA6NdJEIQATvAAE4mFADcdAL4gqIAGZEYAOSQBbOIhgAPfQAdCMAHRgAzrdXgIqTQHMEIQailSaIE+gwqFC2ftIA2nQ+Pn626ACeloT4GLjObthxSMFI4lB+UVIAusqOkC74rgBiEnpI6B4AVrbOjrBmDoheMSBxiTDJGGG+IIT1MHF+tN4jfUkp6GkVrpno2VC5+QgjY4GTIKVKQA

Fix `selector-anb-no-unmatchable` reported ranges and message

---

.changeset/yellow-chairs-laugh.md
docs/user-guide/cli.md
docs/user-guide/options.md
lib/__tests__/__snapshots__/cli.test.mjs.snap
lib/__tests__/cli.test.mjs
lib/__tests__/standalone.test.mjs
lib/augmentConfig.cjs
lib/augmentConfig.mjs
lib/cli.mjs
lib/standalone.cjs
lib/standalone.mjs
lib/utils/__tests__/validateOptions.test.mjs
lib/utils/validateOptions.cjs
lib/utils/validateOptions.mjs
types/stylelint/index.d.ts

It was inspired by:
> […by it's very nature Stylelint runs should gravitate towards becoming a `noop`.](https://github.com/stylelint/stylelint/issues/6869#issue-1729397616)
1.
Most of the time your config is valid. Hence we ought to provide a way to turn `validateOptions` into a noop.
i.e. if you know what you are doing then skipping the validation of the options should be possible
e.g. faster CI, vscode extension
The default is `true`.
i.e. it's not a disruptive change
2.
My very basic/crude perf test compared `main` and `flag-option-validate` using time and [bulma](https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css):
```console
$ time ./bin/stylelint.mjs bulma.min.css …
```

Add `--[no-]validate` flag and `validate` option

---

lib/__tests__/cli.test.mjs
lib/__tests__/standalone-formatter.test.mjs
lib/formatters/__tests__/stringFormatter.test.mjs
lib/testUtils/getCleanOutput.mjs
lib/writeOutputFile.cjs
lib/writeOutputFile.mjs
package-lock.json
package.json

- Closes #8016 
This pull request replaces all instances of `strip-ansi` in all file(s) with `util.stripVTControlCharacters`.
The utility is available since Node 16.11, so there shouldn't be any compatibility issues as the latest version of `stylelint` requires Node 18.12 at minimum.

Refactor to replace `strip-ansi` with `stripVTControlCharacters` from `node:util`

---

.changeset/lemon-dots-learn.md
lib/__tests__/overrides.test.mjs
lib/getConfigForFile.cjs
lib/getConfigForFile.mjs
types/stylelint/index.d.ts

Closes #8014
(This bug was introduced in #7826)
The bug's root cause is present in caching in the `getConfigForFile()` function. The current logic depends on the `overrides` property like this:
https://github.com/stylelint/stylelint/blob/baf7c0e4448e6e1b1d472b53df8a3dd35291449a/lib/getConfigForFile.mjs#L31-L35
But, in the case that `overrides` is only in nested config files, `optionsConfig.overrides` is falsy, and then an incorrect cached config is returned unexpectedly, for example:
```js
standalone({
config: {
extends: './with-overrides.js',
rules: {},
},
});
```
```js
// with-overrides.js
export default {
overrides: [ 
{ 
files: ["*.css"],
rules: {
'block-no-empty': true,
}, …
```

Fix incorrect `config` option for Node.js API with `extends` and `overrides`

---

.changeset/heavy-dryers-promise.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs

Closes https://github.com/stylelint/stylelint/issues/7933
This follows the approach from a previous PR that fixed similar longhand property issues.
ref: https://github.com/stylelint/stylelint/pull/7626

Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-column`/`grid-row`

---

.changeset/wet-foxes-fail.md
lib/rules/length-zero-no-unit/__tests__/index.mjs
lib/rules/length-zero-no-unit/index.cjs
lib/rules/length-zero-no-unit/index.mjs

Closes https://github.com/stylelint/stylelint/issues/8034

Fix `length-zero-no-unit` false positives for Sass variables

---

.changeset/silent-bats-tap.md
lib/rules/selector-max-compound-selectors/__tests__/index.mjs
lib/rules/selector-max-compound-selectors/index.cjs
lib/rules/selector-max-compound-selectors/index.mjs

Fix `selector-max-compound-selectors` reported ranges

---

.changeset/flat-tomatoes-kick.md
lib/reference/functions.cjs
lib/reference/functions.mjs
lib/rules/function-calc-no-unspaced-operator/__tests__/index.mjs
lib/rules/function-no-unknown/__tests__/index.mjs
lib/utils/__tests__/isMathFunction.test.mjs

Added new CSS function `calc-size`.
N/A.
Read more:
https://chromestatus.com/feature/5196713071738880
https://blog.webdevsimplified.com/2024-07/css-calc-size/
https://caniuse.com/?search=calc-size

Fix `function-calc-no-unspaced-operator` false negatives for `calc-size`

---

.eslintignore
eslint.config.mjs
lib/cli.mjs
lib/rules/declaration-block-no-duplicate-properties/index.cjs
lib/rules/declaration-block-no-duplicate-properties/index.mjs
lib/rules/declaration-property-value-no-unknown/index.cjs
lib/rules/declaration-property-value-no-unknown/index.mjs
lib/rules/selector-anb-no-unmatchable/index.cjs
lib/rules/selector-anb-no-unmatchable/index.mjs
package-lock.json
package.json

None, as it's a dependency update.
The [`no-used-vars` rule](https://eslint.org/docs/latest/rules/no-unused-vars) is stricter around [unused vars in caught errors](https://eslint.org/docs/latest/rules/no-unused-vars#caughterrors).
```console
jeddy3@mac stylelint % npm run lint:js
> stylelint@16.10.0 lint:js
> eslint . --cache --max-warnings=0
/Users/jeddy3/Projects/stylelint/lib/cli.mjs
591:11  error  '_' is defined but never used  no-unused-vars
/Users/jeddy3/Projects/stylelint/lib/rules/declaration-block-no-duplicate-properties/index.mjs
104:11  error  'error' is defined but never used  no-unused-vars
/Users/jeddy3/Projects/stylelint/lib/rules/declaration-property-value-no-unkno …
```

Bump ESLint from 8.x to 9.x

---

lib/getPostcssResult.cjs
lib/getPostcssResult.mjs
lib/lintSource.cjs
lib/lintSource.mjs
types/stylelint/index.d.ts

Ref https://github.com/stylelint/stylelint/pull/8086/files#r1818082556
This refactors using only PostCSS public API to reduce our custom code.
https://postcss.org/api/
PostCSS's `Processor#process` returns an object of `LazyResult` or `NoWorkResult`:
https://github.com/postcss/postcss/blob/8.4.47/lib/processor.js#L44-L55

Refactor to remove direct dependencies on PostCSS internals

---

.changeset/twenty-dragons-accept.md
docs/developer-guide/rules.md
scripts/benchmark-rule.mjs

Related to #8044
Related to #8085
This fixes the following `TypeError` by using the Stylelint Public API, instead of PostCSS and Stylelint internals.
```
TypeError: Cannot read properties of undefined (reading 'config')
at validateOptions (file:///Users/masafumi/git/stylelint/stylelint/lib/utils/validateOptions.mjs:19:40)
```
> [!WARNING]
> This makes the benchmark script slower (about 2x slower in my machine), while the script will be less fragile.
In addition, this converts the script's third argument from a rule context to a lint config because the `context.fix` property is now deprecated.
```sh-session
$ node --run benchmark-rule -- value-keyword-case '["lower", …
```

Fix `benchmark-rule` script to resolve `TypeError`

---

.changeset/thick-seas-fail.md
lib/__tests__/cli-deprecation.test.mjs
lib/__tests__/standalone-deprecations.test.mjs
lib/formatters/githubFormatter.cjs
lib/formatters/githubFormatter.mjs
lib/standalone.cjs
lib/standalone.mjs

Change deprecation warning to link to `https://stylelint.io/awesome-stylelint#formatters`

---

.github/workflows/testing.yml

Follow-up to #8127
Since this project's source code and its Codecov pages are completely open, we should not need any tokens for coverage data.
I think the tokenless upload is valuable to reduce our maintenance work for tokens.
In addition to this code change, there are the following manual tasks by admins:
See also:
- https://github.com/codecov/codecov-action/releases/tag/v5.0.0
- https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token

Enable tokenless upload for Codecov

---

lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.mjs
lib/rules/font-family-no-missing-generic-family-keyword/index.cjs
lib/rules/font-family-no-missing-generic-family-keyword/index.mjs

Fix `font-family-no-missing-generic-family-keyword` false positives for `font-family` descriptor in `@font-palette-values`

---

.changeset/curly-lies-serve.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs

#2445
https://www.princexml.com/doc/css-at-rules/#nested-at-rules
https://pagedjs.org/documentation/5-web-design-for-print/#pseudo-class-selectors-for-pages
https://github.com/Kozea/WeasyPrint/pull/846
https://drafts.csswg.org/css-logical/#page
https://www.w3.org/TR/css-gcpm-3/#document-page-selectors

Fix `selector-pseudo-class-no-unknown` false positives for `:recto`, `:verso` and `:nth()`

---

.changeset/stupid-seals-clap.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs

Closes https://github.com/stylelint/stylelint/issues/8175
`::details-content` is a new pseudo element, specced [here](https://drafts.csswg.org/css-pseudo/#details-content-pseudo). See [this](https://developer.chrome.com/blog/styling-details#the_details-content_pseudo) chrome blog post for more details.

Fix `selector-pseudo-element-no-unknown` false positives for `::details-content`

---

.changeset/dirty-fishes-approve.md
.changeset/fresh-seahorses-grab.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-disallowed-list/__tests__/index.mjs
lib/rules/selector-pseudo-class-disallowed-list/index.cjs
lib/rules/selector-pseudo-class-disallowed-list/index.mjs

#1871
1. `:blank` references
https://developer.mozilla.org/en-US/docs/Web/CSS/:blank
https://caniuse.com/mdn-css_selectors_-moz-only-whitespace
https://drafts.csswg.org/selectors-4/#blank-pseudo
web-platform-tests/interop#595
https://www.npmjs.com/package/css-blank-pseudo
2. I tried using a combination of `walkAtRules` and `walkRules` instead of `walk`, the performance hit was negligible.

Add `selector-pseudo-class-disallowed-list` support for `@page`

---

lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs
lib/rules/selector-max-specificity/index.cjs
lib/rules/selector-max-specificity/index.mjs
lib/standalone.cjs
lib/standalone.mjs
package-lock.json
package.json

None.
Here is an official blog post for the latest version 3.4 of Prettier:
https://prettier.io/blog/2024/11/26/3.4.0
In addition, this change explicitly adds `prettier` to `package.json` because `prettier` is installed as a peer dependency of `@stylelint/prettier-config` and so it is not updated unless `@stylelint/prettier-config` is updated.
```sh-session
$ NODE_OPTIONS=--no-warnings npm v @stylelint/prettier-config peerDependencies
{ prettier: '>=3.0.0' }
```

Bump prettier from 3.0.0 to 3.4.2

---

.changeset/tiny-lobsters-float.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs

Closes https://github.com/stylelint/stylelint/issues/8183
See issue for more details on this new pseudo class. See https://groups.google.com/a/chromium.org/g/blink-dev/c/Pdo4oOXYKcA for the Chromium intent to ship for this.

Fix `selector-pseudo-class-no-unknown` false positives for `:open`

---

docs/user-guide/rules.md
lib/rules/at-rule-property-required-list/README.md

This change was produced by the discussion on <https://github.com/stylelint/stylelint/issues/8148#issuecomment-2531031990>.
We probably should have named the `at-rule-property-required-list` as `at-rule-descriptor-required-list` because declarations in at-rules are semantically descriptors rather than properties.
See also <https://drafts.csswg.org/css-syntax/#declaration>.

Document `at-rule-property-required-list`  difference between properties and descriptors

---

.changeset/blue-carrots-share.md
lib/rules/at-rule-property-required-list/index.cjs
lib/rules/at-rule-property-required-list/index.mjs

Follow-up PR #8185
See also <https://github.com/stylelint/stylelint/issues/8148#issuecomment-2531031990>
Note that it doesn't rename local variables to minimize code diffs and keep git-blame easy.

Fix `at-rule-property-required-list` message to use "descriptor" for accuracy

---

.changeset/curvy-buses-rhyme.md
lib/rules/at-rule-property-required-list/README.md
lib/rules/at-rule-property-required-list/index.cjs
lib/rules/at-rule-property-required-list/index.mjs

Ref https://github.com/stylelint/stylelint/pull/8185
People can use this rule to require properties for nested at-rule. 
```css
a {
@media (min-width: 10px } {
color: red;
}
}
```
[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilABAtjFAJaoAUA7sVAC4AWKAfCgIwAMADgB4CUaWOHJAA2EAE7wUYogG4BKAL5YFIADQgAZsWEwAckkIIQMLgY46AdGADO1teAiYtAcyMZsKdMa40YmKNZekgDa8jhe1jQAnjrCxJg0ALSQTsTOiZFI-khiUF7yALqq8l5iAK46gQj8HuHISeU6iRxiEBwwYtGJ0gCOZcTSUIlxkUE1goJehCRIY6EgJNbmSFFeBWGK8kqYKuopLgBi4vhINEYAVtaO9rAcdojudZExMHEJY17CpzCjaiUgz1i8SS+zSGRoWSgOTy1U+31+yhACiAA).
As a generic rule that applies to properties and descriptors, we can tweak the wording from …

Fix `at-rule-property-required-list` message for inclusion of properties and descriptors

---

.changeset/gold-suns-notice.md
lib/reference/atKeywords.cjs
lib/reference/atKeywords.mjs
lib/rules/at-rule-allowed-list/README.md
lib/rules/at-rule-disallowed-list/README.md
lib/rules/at-rule-empty-line-before/README.md
lib/rules/at-rule-no-unknown/README.md
lib/rules/at-rule-no-unknown/__tests__/index.mjs
lib/rules/no-irregular-whitespace/__tests__/index.mjs
lib/rules/string-no-newline/__tests__/index.mjs
lib/utils/__tests__/isStandardSyntaxAtRule.test.mjs
lib/utils/isStandardSyntaxAtRule.cjs
lib/utils/isStandardSyntaxAtRule.mjs

Ref https://github.com/stylelint/stylelint/issues/7492#issuecomment-1907995564
Ref https://github.com/stylelint/stylelint/pull/8214#pullrequestreview-2518665122
Fixes `@charset` being treated as an at-rule in our examples and tests.
It felt like an appropriate time to address this as we're adding new rules to shore up our capabilities around at-rules.

Fix `atrule-*` false positives and negatives for `@charset` rule

---

lib/rules/color-hex-alpha/__tests__/index.mjs
lib/rules/color-hex-alpha/index.cjs
lib/rules/color-hex-alpha/index.mjs
lib/rules/no-irregular-whitespace/__tests__/index.mjs
lib/rules/no-irregular-whitespace/index.cjs
lib/rules/no-irregular-whitespace/index.mjs

N/A
I am planning to send a PR that will add the possibility to add the types of the core rule's `messages`.
i.e.
```ts
type CoreRule<
P extends Primary,
S extends Secondary = CommonOptions,
M extends RuleMessages = Messages
> = Rule<P, S, M>;
```
This will permit to document the order and names of the arguments.
e.g.
- distinguish between `(property: string, keyword: string) => string` and `(keyword: string, property: string) => string`
- hypothetical documentation generation
- autocompletion for configurations
This preliminary PR is to prepare the codebase for that change.
i.e. these rules are the only ones that produce errors for
```ts
type Messages = {
[key in …
```

Refactor `color-hex-alpha` and `no-irregular-whitespace` to use consistent `ruleMessage` keys

---

docs/developer-guide/rules.md

This PR tweaks the documentation to imply that the `isStandardSyntax*` utils should always be used.

Document use of `isStandardSyntax*` utils

---

docs/user-guide/configure.md
docs/user-guide/get-started.md

It's a documentation fix that relates to https://github.com/stylelint/create-stylelint/pull/92#issuecomment-2564129562
A while back, we:
- updated many of our examples to use ESM
- decided to only implement things that would be compatible with a flat config
This PR brings the _getting started_ and _configuring_ docs in line with that by recommending people use a `stylelint.config.{js,mjs}` file.

Document preferred config file format

---

lib/rules/selector-not-notation/index.cjs
lib/rules/selector-not-notation/index.mjs

See https://github.com/stylelint/stylelint/issues/8243

Refactor `selector-not-notation` to have unambiguous position arguments

---

docs/user-guide/customize.md
lib/rules/at-rule-descriptor-no-unknown/README.md
package.json
scripts/remark-plugins/lint-link-to-rule.mjs

None. This only affects the documentation.
This aims to check all links to rule documents in Markdown files using a new custom remark-lint plugin.
Conditions:
- The links must end with `README.md`.
- ❌ `[...](../lib/rules/unit-allowed-list)`
- ✅ `[...](../lib/rules/unit-allowed-list/README.md)`
- The links must have an inline code instead of just a text.
- ❌ `[unit-allowed-list](...)`
- ✅ ``[`unit-allowed-list`](...)``
- The links must include a correct rule name.
- ❌ ``[`unit-disallowed-list`](../lib/rules/unit-allowed-list/README.md)``
- ✅ ``[`unit-allowed-list`](../lib/rules/unit-allowed-list/README.md)``
Result:
```sh-session
docs/user-guide/customize.md
18:17-18:73   warning …
```

Document links to rules correctly with remark plugin

---

.changeset/dull-pears-burn.md
.changeset/little-bobcats-punch.md
.changeset/shy-zebras-wave.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs
lib/rules/selector-type-no-unknown/index.cjs
lib/rules/selector-type-no-unknown/index.mjs

#8225
> Resources
- pseudo-classes
- [`:top-layer`](https://issues.chromium.org/issues/40860536)
- [`:popup-open`](https://issues.chromium.org/issues/40218886#comment39)
- [`:focus-ring`](https://web.archive.org/web/20171209101655/https://drafts.csswg.org/selectors-4/)
- [`:matches`](https://caniuse.com/css-matches-pseudo)
- [`:drop`](https://drafts.csswg.org/selectors-4/#changes-2018-02)
- [GTK](https://github.com/GNOME/gtk/commit/158dbbc88f2c2735c417d27bbc96dbecd7a67656) 
- [`:user-error`](https://drafts.csswg.org/selectors-4/#changes-2013)
- [`:contains`](https://www.w3.org/TR/2001/CR-css3-selectors-20011113/#content-selectors)
- [sizzle](https://github.com/jquery/sizzle/wiki#additions)
- [Beautiful …

Fix `selector-{type,pseudo-class}-no-unknown` and `selector-type-case` false positives for deprecated selectors

---

lib/__tests__/standalone-cache.test.mjs
lib/utils/FileCache.cjs
lib/utils/FileCache.mjs

See https://github.com/stylelint/stylelint/pull/8256
The latest version of `file-entry-cache` considers any file with either a changed check sum or changed meta data as changed. This is different from the previous version.
As I understood the current code and tests we want to skip linting files that still have the same content, even when a timestamp or other metadata has changed.
In support of that I added a `hasFileCheckSumChanged` method to `FileCache` and updated `hasFileChanged` to restore the old behavior.

Refactor `FileCache` to support `file-entry-cache` version 10

---

lib/__tests__/standalone-cache.test.mjs
lib/utils/FileCache.cjs
lib/utils/FileCache.mjs

See https://github.com/stylelint/stylelint/pull/8256
It seems we made a small mistake in https://github.com/stylelint/stylelint/pull/8262 and that we didn't have sufficient test coverage.
`this._fileCache.getFileDescriptor(absoluteFilepath);` also writes the new content hash to `this._fileCache.cache` even though it is a getter method.
Any reads from the cache to compare the file hash after already calling `getFileDescriptor` would return the new hash, not the previous one.
So to compare content hashes we need to first read from the cache and only after call `getFileDescriptor`.

Fix `FileCache` false negatives when only contents have changed

---

lib/formatters/__tests__/verboseFormatter.test.mjs
lib/formatters/verboseFormatter.cjs
lib/formatters/verboseFormatter.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/report.cjs
lib/utils/report.mjs
types/stylelint/index.d.ts

Closes https://github.com/stylelint/stylelint/issues/8233
`fixersData` is not part of our public API and the verbose formatter still produces the same reports as before.

Refactor to remove `fixed` from `FixerData`

---

lib/rules/__tests__/index.test.mjs

None.
This increases the test coverage when invalid options are passed to all the rules.
```js
if (!validOptions) {
return; //<- This line is now covered.
}
```
See the coverage on Codecov: https://app.codecov.io/gh/stylelint/stylelint/pull/8270

Test invalid options for all rules

---

lib/formatters/__tests__/verboseFormatter.test.mjs
lib/formatters/verboseFormatter.cjs
lib/formatters/verboseFormatter.mjs
lib/utils/__tests__/report.test.mjs
lib/utils/report.cjs
lib/utils/report.mjs
types/stylelint/index.d.ts

follow-up of #8267
1.
With the removal of `fixed`, it was absurd to keep `FixerData` if we were not even planning to add `range` to it.
see https://github.com/stylelint/stylelint/pull/8267#pullrequestreview-2528238317
2.
`StylelintPostcssResult['fixersData']` could be renamed in #8234 to avoid confusion with [`fixData`](https://github.com/stylelint/stylelint/pull/8234/files#diff-cba25f954347e963307879ca83b95b319e9003d9b4b51fd350d3f4110566d3a8R72).
i.e. semantic creep

Refactor to remove `FixerData` type

---

docs/developer-guide/plugins.md
docs/user-guide/options.md

Closes #8249 
I'd also like to add something for plugin authors that describes https://github.com/stylelint/stylelint/issues/8249#issuecomment-2564755567, i.e. handling warning events, but I could only silence all warnings in a plugin using:
```js
process.removeAllListeners("warning");
```
I thought I'd be able to silence individual warnings using:
```js
process.on("warning", (warning) => {
if (warning.code === "stylelint:005") return;
});
```
But that didn't work. Am I missing something?

Document how to handle emitted deprecation warnings

---

.changeset/perfect-pots-destroy.md
lib/rules/at-rule-allowed-list/__tests__/index.mjs
lib/rules/at-rule-allowed-list/index.cjs
lib/rules/at-rule-allowed-list/index.mjs
lib/rules/at-rule-disallowed-list/__tests__/index.mjs
lib/rules/at-rule-disallowed-list/index.cjs
lib/rules/at-rule-disallowed-list/index.mjs
lib/rules/at-rule-no-vendor-prefix/__tests__/index.mjs
lib/rules/at-rule-no-vendor-prefix/index.cjs
lib/rules/at-rule-no-vendor-prefix/index.mjs
lib/rules/at-rule-property-required-list/__tests__/index.mjs
lib/rules/at-rule-property-required-list/index.cjs
lib/rules/at-rule-property-required-list/index.mjs
lib/rules/custom-property-pattern/index.cjs
lib/rules/custom-property-pattern/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs
lib/rules/no-unknown-custom-media/__tests__/index.mjs
lib/rules/no-unknown-custom-media/index.cjs
lib/rules/no-unknown-custom-media/index.mjs
lib/rules/no-unknown-custom-properties/index.cjs
lib/rules/no-unknown-custom-properties/index.mjs

> Which PR, if any, is this related to?
follow-up of #8236 and #8252
1.
`at-rule-descriptor-no-unknown`, `at-rule-no-deprecated`, `at-rule-prelude-no-invalid` and `at-rule-no-unknown` pass `'@foo'`.
`at-rule-(dis)allowed-list`, `at-rule-no-vendor-prefix`, `at-rule-property-required-list` used to pass `'foo'`.
2.
`at-rule-no-vendor-prefix` had the right message but the wrong argument.
i.e. the @ should not be added in the message itself
3.
13 rules that have a message that starts with `Unexpected unknown` use the `rejected` key for it.
`no-unknown-custom-media` used `expected`.
4.
The argument passed should respect the current style of the user's codebase.
i.e. [`"at-rule-name-case": …

Fix `at-rule-(dis)allowed-list`, `at-rule-no-vendor-prefix`, `at-rule-property-required-list` message argument

---

docs/developer-guide/plugins.md
docs/developer-guide/rules.md

Closes https://github.com/stylelint/stylelint/issues/8261
If someone has time, it may be worth adding a small section to the "writing rules" about the `report()` function to give examples of how `node`, `index` and `endIndex` are likely used.

Document best practices for position arguments in `utils.report()`

---

.changeset/pink-panthers-fix.md
lib/utils/getFileIgnorer.cjs
lib/utils/getFileIgnorer.mjs
package-lock.json
package.json

Closes https://github.com/stylelint/stylelint/issues/8304

Fix `ignore.default is not a function`

---

lib/rules/shorthand-property-no-redundant-values/README.md

Document `shorthand-property-no-redundant-values` README description without grammatical error

---

.changeset/lucky-garlics-compare.md
types/stylelint/index.d.ts

#8308
doesn't c l o s e it (a new enhancement issue must be created)
1.
guilty commit: 0f92394
We failed to detect the problem during the review.
2.
So that it doesn't happen again here are some suggestions:
- improve `type-test.ts`
- review the errors reported by `stylelint-ecosystem-tester` more carefully during the pre-release phase
- increase the number of approvals needed when the number of `mjs` files reach a certain threshold—e.g. 3 approvals
These are just suggestions—i.e. overcompensating can be bad too—maybe it was simply an oversight and it can't be helped.

Fix `RuleContext['fix']` type

---

.changeset/violet-shirts-dream.md
lib/rules/declaration-property-value-keyword-no-deprecated/__tests__/index.mjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.cjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs
lib/utils/isStandardSyntaxValue.cjs
lib/utils/isStandardSyntaxValue.mjs

Closes #8327
`${foo(({ background }) => background.bar)}` cannot be tested in the `accept` array because it gives a `CssSyntaxError` without `postcss-styled-syntax` which shan't be added as a dependency.
i.e. no `customSyntax: 'postcss-styled-syntax',` testRule
see discussion in #6556
ref: https://styled-components.com/docs/advanced#tagged-template-literals

Fix `declaration-property-value-keyword-no-deprecated` false positives for non-standard syntax values

---

.changeset/lovely-monkeys-yell.md
lib/reference/properties.cjs
lib/reference/properties.mjs
lib/rules/declaration-property-value-keyword-no-deprecated/__tests__/index.mjs

#8327
1.
`border-color` is not a single value color property.
i.e. it accepts 1, 2, 3 and 4
This was missed during the review of #8223.
2.
[shorthand properties are not supported](https://github.com/stylelint/stylelint/pull/8223#issue-2758167186)

Fix `declaration-property-value-keyword-no-deprecated` false positives for `border-color`

---

.changeset/friendly-feet-tie.md
lib/formatters/stringFormatter.cjs
lib/formatters/stringFormatter.mjs

Vendor "table" not work with default import at mjs.
Fixed to named import

Fix `SyntaxError: The requested module 'table'...` 

---

.changeset/nine-needles-grow.md
lib/rules/declaration-block-no-duplicate-properties/__tests__/index.mjs
lib/rules/declaration-block-no-duplicate-properties/index.cjs
lib/rules/declaration-block-no-duplicate-properties/index.mjs

This is the first PR in a series.
This rule didn't have any tests without `fix: true` in the test config.
I opted to only add a few new tests as the fixer itself has good coverage.
The needed change is simpler if a rule has existing tests without `fix: true`.
In such a case we could add `computeEditInfo: true` to the test config and add the `fix` expects.

Add `declaration-block-no-duplicate-properties` support for computing `EditInfo`

---

lib/utils/report.cjs
lib/utils/report.mjs

Closes https://github.com/stylelint/stylelint/issues/8364

Refactor `utils.report` to not restore mutated nodes in `computeEditInfo`

---

.changeset/red-clouds-sit.md
lib/rules/at-rule-empty-line-before/README.md
lib/rules/at-rule-empty-line-before/__tests__/index.mjs
lib/rules/at-rule-empty-line-before/index.cjs
lib/rules/at-rule-empty-line-before/index.mjs
types/stylelint/index.d.ts

Add regex support to `ignoreAtRules` option of `at-rule-empty-line-before`

---

.changeset/long-onions-know.md
lib/rules/declaration-property-value-keyword-no-deprecated/__tests__/index.mjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.cjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs

follow-up of #8329
see https://github.com/stylelint/stylelint/issues/8327#issuecomment-2650992504
To test you have to
1.
```sh
npm i -D postcss-styled-syntax
```
reminder: we don't support these syntaxes officially but if the fix is trivial we do make exceptions
2.
add
```js
testRule({
ruleName,
customSyntax: 'postcss-styled-syntax',
config: true,
accept: [
{
code: `
export const s = styled.a\`
background-color: \${palette(({ background }) => background.primary)};
\`;
`,
},
],
});
```
to `declaration-property-value-keyword-no-deprecated/__tests__/index.mjs`

Fix `declaration-property-value-keyword-no-deprecated` false positives for styled components interpolated functions

---

.changeset/witty-needles-flow.md
lib/reference/keywords.cjs
lib/reference/keywords.mjs
lib/rules/font-family-name-quotes/__tests__/index.mjs

follow-up of https://github.com/stylelint/stylelint/pull/7823/files#diff-55ac48e2b42df1382f80e3eb95f6e4aeb8ae0764fd62398512da7a9d3597c0c0R127
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266-font-size
w3c/csswg-drafts#3907
https://github.com/KDE/kdelibs/commit/4feea2dd7aa1b6a604ce1fd382853afcbe0b692c
[demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgMwkx3hQA9yBaAGyQCcBzGFdEAQVoEskqWAaFAM5JMAigJic8Abiy4CREhQDuMAEYBrDjgrlS1Oo2ZtO3PoOGjxkmdnyFiKCusIBHHZRoMmLdlx4h+IRExCQ5pLABfLACQPA4qGAA5JABbOEQYUlSABwSAOjABARjITDj6BBAMTBQjWgBXBIEWEmra2pZ5bTxU+IBPCkxUmAoXeog …

Fix `font-family-name-quotes` false positives for vendor-prefixed font-size values

---

.github/workflows/pkg.pr.new-comment.yml

Related to #8352
This PR is follow-up to #8353. 
This PR fixes the workflow of `pkg.pr.new-comment` to allow the automatic comment posting script to work.
The automatic comment posting script requires `lz-string`, but since `npm ci` was not run, `lz-string` was not found and it failed 😓 
https://github.com/stylelint/stylelint/actions/runs/13360990127/job/37310591018

Fix pkg.pr.new-comment workflow

---

.github/workflows/pkg.pr.new-comment.yml

Related to #8352
This PR is follow-up to #8353, and #8401. 
This PR fixes the workflow of `pkg.pr.new-comment` to allow commenting on pull requests.
`pkg.pr.new-comment` tries to comment a link to the Demo site in the pull request, but it fails with 403 😓 
https://github.com/stylelint/stylelint/actions/runs/13448325443/job/37578178501

Add permissions to pkg.pr.new comment workflow

---

.changeset/rude-phones-sit.md
lib/rules/color-function-notation/__tests__/index.mjs
lib/rules/color-function-notation/index.cjs
lib/rules/color-function-notation/index.mjs

Add `color-function-notation` support for computing `EditInfo`

---

.changeset/metal-impalas-divide.md
lib/rules/at-rule-empty-line-before/__tests__/index.mjs
lib/rules/at-rule-empty-line-before/index.cjs
lib/rules/at-rule-empty-line-before/index.mjs

Add `at-rule-empty-line-before` support for computing `EditInfo`

---

.changeset/heavy-seas-drop.md
lib/rules/at-rule-no-deprecated/__tests__/index.mjs
lib/rules/at-rule-no-deprecated/index.cjs
lib/rules/at-rule-no-deprecated/index.mjs

Add `at-rule-no-deprecated` support for computing `EditInfo`

---

.changeset/sixty-boats-dream.md
lib/rules/at-rule-no-vendor-prefix/__tests__/index.mjs
lib/rules/at-rule-no-vendor-prefix/index.cjs
lib/rules/at-rule-no-vendor-prefix/index.mjs

Add `at-rule-no-vendor-prefix` support for computing `EditInfo`

---

.changeset/rotten-pumas-post.md
lib/rules/declaration-property-value-keyword-no-deprecated/__tests__/index.mjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.cjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs

Add `declaration-property-value-keyword-no-deprecated` support for computing `EditInfo`.

---

.changeset/grumpy-teeth-send.md
lib/rules/import-notation/__tests__/index.mjs
lib/rules/import-notation/index.cjs
lib/rules/import-notation/index.mjs

Add `import-notation` support for computing `EditInfo`.

---

.changeset/stale-paws-lie.md
lib/rules/selector-type-case/__tests__/index.mjs
lib/rules/selector-type-case/index.cjs
lib/rules/selector-type-case/index.mjs

Added `selector-type-case` support for computing `EditInfo`

---

.changeset/six-ties-cry.md
lib/rules/shorthand-property-no-redundant-values/__tests__/index.mjs
lib/rules/shorthand-property-no-redundant-values/index.cjs
lib/rules/shorthand-property-no-redundant-values/index.mjs

Added `shorthand-property-no-redundant-values` support for computing `EditInfo`

---

.changeset/chatty-bushes-remain.md
lib/rules/selector-pseudo-element-colon-notation/__tests__/index.mjs
lib/rules/selector-pseudo-element-colon-notation/index.cjs
lib/rules/selector-pseudo-element-colon-notation/index.mjs

Added `selector-pseudo-element-colon-notation` support for `EditInfo`

---

.changeset/wicked-mammals-attack.md
lib/rules/selector-not-notation/__tests__/index.mjs
lib/rules/selector-not-notation/index.cjs
lib/rules/selector-not-notation/index.mjs

Added `selector-not-notation` support for computing `EditInfo`

---

.changeset/big-doodles-follow.md
lib/rules/selector-no-vendor-prefix/__tests__/index.mjs
lib/rules/selector-no-vendor-prefix/index.cjs
lib/rules/selector-no-vendor-prefix/index.mjs

Added `selector-no-vendor-prefix` support for `EditInfo`

---

.changeset/sweet-ants-post.md
lib/rules/property-no-vendor-prefix/__tests__/index.mjs
lib/rules/property-no-vendor-prefix/index.cjs
lib/rules/property-no-vendor-prefix/index.mjs

Added `property-no-vendor-prefix` support for computing `EditInfo`

---

.changeset/green-trains-invite.md
lib/rules/rule-empty-line-before/__tests__/index.mjs
lib/rules/rule-empty-line-before/index.cjs
lib/rules/rule-empty-line-before/index.mjs

Added `rule-empty-line-before` support for computing `EditInfo`

---

.changeset/sad-sloths-sell.md
lib/rules/length-zero-no-unit/__tests__/index.mjs
lib/rules/length-zero-no-unit/index.cjs
lib/rules/length-zero-no-unit/index.mjs

Added `length-zero-no-unit` support for computing `EditInfo`.

---

.changeset/great-dots-shine.md
lib/rules/lightness-notation/__tests__/index.mjs
lib/rules/lightness-notation/index.cjs
lib/rules/lightness-notation/index.mjs

Added `lightness-notation` support for computing `EditInfo`

---

.changeset/tasty-buttons-hang.md
lib/rules/keyframe-selector-notation/__tests__/index.mjs
lib/rules/keyframe-selector-notation/index.cjs
lib/rules/keyframe-selector-notation/index.mjs

Added `keyframe-selector-notation` support for computing `EditInfo`

---

.changeset/plain-mice-allow.md
lib/rules/media-feature-name-no-vendor-prefix/__tests__/index.mjs
lib/rules/media-feature-name-no-vendor-prefix/index.cjs
lib/rules/media-feature-name-no-vendor-prefix/index.mjs

Added `media-feature-name-no-vendor-prefix` support for computing `EditInfo`

---

.changeset/fast-forks-look.md
lib/rules/value-no-vendor-prefix/__tests__/index.mjs
lib/rules/value-no-vendor-prefix/index.cjs
lib/rules/value-no-vendor-prefix/index.mjs

Added `value-no-vendor-prefix` support for computing `EditInfo`

---

.changeset/weak-mugs-begin.md
lib/rules/custom-property-pattern/__tests__/index.mjs
lib/rules/custom-property-pattern/index.cjs
lib/rules/custom-property-pattern/index.mjs

This PR fixes issue [#8430](https://github.com/stylelint/stylelint/issues/8430), where the custom-property-pattern rule was not reporting the correct error location for custom property names declared via @property at-rules.
- **Code Changes:**  
In `lib/rules/custom-property-pattern/index.mjs`, the error location calculation for @property at-rules has been adjusted. The fix computes the base error index using the at-rule’s source column plus an offset (and optionally adds an extra offset for property names ending with a hyphen) so that the reported start and end columns match the expected values.
- **Test Changes:**  
New test cases were added to `lib/rules/custom-property-pattern/__tests__/index.mjs` to ensure that:
- A valid @property rule with a properly formatted custom property name …

Fix `custom-property-pattern` false negatives for `@property` preludes

---

.changeset/old-symbols-kneel.md
docs/user-guide/configure.md
lib/__tests__/fixtures/config-language-options.json
lib/__tests__/languageOptions.test.mjs
lib/rules/at-rule-no-unknown/README.md
lib/rules/at-rule-no-unknown/index.cjs
lib/rules/at-rule-no-unknown/index.mjs

Closes #8453 
This is slightly off-topic, but I created an issue because tests currently only support `standalone`. 
It would be better if `languageOptions` could be configured per rule.
https://github.com/stylelint/jest-preset-stylelint/issues/143

Add `at-rule-no-unknown` support for `languageOptions`

---

.changeset/stale-coins-guess.md
lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs
lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs

Add `declaration-block-no-redundant-longhand-properties` support for computing `EditInfo`

---

.changeset/chilly-mice-say.md
lib/rules/selector-attribute-quotes/__tests__/index.mjs
lib/rules/selector-attribute-quotes/index.cjs
lib/rules/selector-attribute-quotes/index.mjs

Added `selector-attribute-quotes` support for computing `EditInfo`

---

.changeset/honest-fans-drive.md
docs/user-guide/configure.md
lib/__tests__/fixtures/config-language-options.json
lib/__tests__/languageOptions.test.mjs
lib/rules/property-no-unknown/README.md
lib/rules/property-no-unknown/index.cjs
lib/rules/property-no-unknown/index.mjs

Closes #8454 
Related: https://github.com/stylelint/stylelint/pull/8475

Add `property-no-unknown` support for `languageOptions`

---

lib/rules/selector-not-notation/README.md

This PR updates the documentation for the selector-not-notation rule to clarify how specificity differs between simple and complex :not() forms.
Issue Summary:
Currently, the rule recommends using the complex form (a:not([href], [class])) instead of the simple form (a:not([href]):not([class])). However, this can lead to unexpected specificity changes, potentially breaking existing styles.
Key Changes:
✅ Added a warning explaining that converting to complex notation may reduce specificity.
✅ Provided examples illustrating how specificity differs between simple and complex forms.
✅ Introduced ignoreSpecificity: true option to allow developers to bypass specificity warnings.
✅ Included a real-world example (Bootstrap's link styling issue) to demonstrate the impact.
This update ensures …

Document `selector-not-notation` specificity note

---

lib/rules/declaration-block-no-redundant-longhand-properties/README.md
lib/rules/selector-not-notation/README.md

Closes #8497
Added short descriptions for `ignoreLonghands` and `ignoreShorthands` options in the documentation for the `declaration-block-no-redundant-longhand-properties` rule.
Also, added examples for `ignoreShorthands` to clarify the intended behavior of the option.

Document `declaration-block-no-redundant-longhand-properties` secondary options descriptions

---

docs/developer-guide/rules.md

These came up in https://github.com/stylelint/stylelint/pull/8498

Document css-wide keywords and `languageOptions` in writing rules

---

lib/reference/atKeywords.cjs
lib/reference/atKeywords.mjs
lib/reference/functions.cjs
lib/reference/functions.mjs
lib/reference/keywords.cjs
lib/reference/keywords.mjs
lib/reference/mediaFeatures.cjs
lib/reference/mediaFeatures.mjs
lib/reference/prefixes.cjs
lib/reference/prefixes.mjs
lib/reference/properties.cjs
lib/reference/properties.mjs
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/reference/units.cjs
lib/reference/units.mjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.cjs
lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs

None.
TypeScript's `Readonly*` types can prevent a mistake like this:
```js
lib/reference/units.mjs:67:17 - error TS2339: Property 'add' does not exist on type 'ReadonlySet<string>'.
67 resolutionUnits.add('foo');
~~~
```

Refactor to prevent unexpected mutation of shared objects

---

.github/workflows/pkg.pr.new-comment.yml

Potential fix for [https://github.com/stylelint/stylelint/security/code-scanning/78](https://github.com/stylelint/stylelint/security/code-scanning/78)
To fix the problem, we need to ensure that the artifact contents are treated as untrusted and are extracted to a temporary directory to prevent them from overwriting existing files. Additionally, we should verify the contents of the artifact before using them.
1. Create a temporary directory for the artifact extraction.
2. Modify the `actions/download-artifact` step to extract the artifact to the temporary directory.
3. Verify the contents of the artifact before using them in the subsequent steps.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 78: Artifact poisoning

---

.github/workflows/testing.yml

Fixes https://github.com/stylelint/stylelint/security/code-scanning/77
Explicitly having permissions in GitHub Actions workflows is a good security practice.
Ref https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/assigning-permissions-to-jobs

Specify permissions to testing workflow for security

---

.github/workflows/preparing-github-release.yml
.github/workflows/releasing.yml
.github/workflows/testing.yml

This fixes the code scanning alerts:
- https://github.com/stylelint/stylelint/security/code-scanning/79
- https://github.com/stylelint/stylelint/security/code-scanning/80
- https://github.com/stylelint/stylelint/security/code-scanning/81
Note that this PR doesn't update all actions; only for third-party actions, e.g. not `actions/*`.
This pinning technique generally mitigates risks for supply chain attacks, and GitHub officially suggests:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Pin third party actions on CI

---

.changeset/curvy-parrots-doubt.md
lib/rules/no-empty-source/__tests__/index.mjs
lib/rules/no-empty-source/index.cjs
lib/rules/no-empty-source/index.mjs

Closes https://github.com/stylelint/stylelint/issues/8441
I found this one a bit counter intuitive :)
We resolve the reported issue by reporting more errors, not less.
By reporting an error when the source only contains configuration comments we ensure that there is an error and that `--report-needless-disables` won't report any needless disables.
When the configuration comment matches `no-empty-source` the final result will be that no errors are emitted, neither for empty files nor for needless disables.

Fix `no-empty-source` false positives for `--report-needless-disables`

---

.changeset/smart-groups-lie.md
lib/__tests__/fixtures/postcss-naive-css-in-js.cjs
lib/rules/no-empty-source/__tests__/index.mjs
lib/rules/no-empty-source/index.cjs
lib/rules/no-empty-source/index.mjs

Closes #8547
This fixes false positives for the `no-empty-source` rule in a non-standard syntax.
For example, [`postcss-styled-syntax`](https://github.com/hudochenkov/postcss-styled-syntax) produces the following AST.
Like this case, even if `root.nodes` is empty, we should consider that `root` contains a notable child.
```js
styled.a` ${VAR} `;
/*=>
Root {
raws: {
styledSyntaxRangeStart: 9,
styledSyntaxRangeEnd: 17,
isRuleLike: true,
styledSyntaxIsComponent: true,
after: ' ${VAR} ',
codeBefore: 'styled.a`',
codeAfter: '`;\n'
},
type: 'root',
nodes: [],
}
*/
```

Fix `no-empty-source` false positives for non-standard syntaxes

---

lib/rules/block-no-empty/index.cjs
lib/rules/block-no-empty/index.mjs
lib/rules/comment-empty-line-before/index.cjs
lib/rules/comment-empty-line-before/index.mjs
lib/rules/no-empty-source/index.cjs
lib/rules/no-empty-source/index.mjs
lib/utils/__tests__/configurationComment.test.mjs
lib/utils/configurationComment.cjs
lib/utils/configurationComment.mjs

None.
This allows a PostCSS node as an argument for the `isConfigurationComment()` private utility.
It can simplify the caller code because of no need for type guards, such as `isComment()`.
```js
// Before
isComment(node) && isConfigurationComment(node.text);
// After
isConfigurationComment(node);
```

Refactor to allow node for `isConfigurationComment()` private utility

---

lib/rules/declaration-property-unit-allowed-list/README.md

Part of #4808 and #3372
In addition to #4808, this PR aims to help the discussion in #3372. My points are:
- A typical valid JSON defining a schema is enough, e.g., not using an invalid syntax like `|` for union types.
- If necessary, supplement a schema with additional descriptions.
- Good examples are provided to help users understand how to use a rule.

Document `declaration-property-unit-allowed-list` full configs

---

docs/developer-guide/rules.md

This fixes JavaScript syntax errors in code examples in the document. The errors are like so:
```
});
^
SyntaxError: Unexpected token '}'
```

Fix JS syntax errors in `docs/developer-guide/rules.md`

---

.changeset/pink-chicken-clean.md
lib/utils/checkInvalidCLIOptions.cjs
lib/utils/checkInvalidCLIOptions.mjs

Sorry I didn't create an issue first, I think this is a small change and didn't think it would require a big discussion.
I am using stylelint in a project and in this project I bundle stylelint.
It just so happens that `fastest-levenshtein` is an hybrid ESM module that doesn't have a default export. it can however be imported with `require("fatstest-levenshtein")`.
In stylelint it's already done this way in one place; https://github.com/stylelint/stylelint/blob/93d1af12d62bda32d5b29561691d7a3667616799/lib/reportUnknownRuleNames.mjs#L1 this PR adjusts the second place to use the same style of import
None yet.
I don't think so

Fix `fastest-levenshtein` import when bundling

---

lib/rules/custom-property-empty-line-before/README.md

Ref https://github.com/stylelint/stylelint/pull/8627#discussion_r2153147227
I checked through the other `*-empty-line-before` rules, and it's only this one that the LLM tripped up on the `ignore` examples.

Document `custom-property-empty-line-before` ignore examples correctly

---

.changeset/proud-flowers-know.md
lib/rules/custom-property-empty-line-before/README.md
lib/rules/custom-property-empty-line-before/__tests__/index.mjs
lib/rules/custom-property-empty-line-before/index.cjs
lib/rules/custom-property-empty-line-before/index.mjs
types/stylelint/index.d.ts

Closes #8615
The tests are intended to mimic (read: copied from) those for `declaration-empty-line-before`.

Add `ignore: ["after-custom-property"]` to `custom-property-empty-line-before`

---

.changeset/brown-hotels-notice.md
lib/rules/media-feature-range-notation/__tests__/index.mjs
lib/rules/media-feature-range-notation/index.cjs
lib/rules/media-feature-range-notation/index.mjs

Closes https://github.com/stylelint/stylelint/issues/8647
[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBbGUCWBDABACgHcMoAXAC3hwDYAGGgBwA8BKHYAXxABoQAzDADYwAcljQIQMRmPpCAdGADOi7uAgA7fgHMJwADrqcOPSABOAVyGKTlfYaPGQaTFgC0vGFhLnTMV6ax1LT91CBIvDA0bR0h1EikSEwMjdgNOHljtADEIUxQvCQArRQ1VWHoVRDsjE0USAE8hAQw46JMyEhIK+AB6HvoAay05elM5dRgCHrrGmGa4pAAOXgBGRYAWACYAZhMuZMcZppaSV0yMLVc6wKgsUyg2kAEvGDqk9U52IA)

Fix `media-feature-range-notation` autofix for exact values

---

lib/utils/resolveFilePath.cjs
lib/utils/resolveFilePath.mjs

Follow-up to PR #8655
This just refactor the internal code in the `resolveFilePath()` utility to improve the code readability:
- Avoid assigning to an argument.
- Use `endsWith` over `[]` for a string.
- Inline an private function to avoid needless function creation.

Refactor `resolveFilePath()` internal utility

---

.changeset/major-seals-bathe.md
lib/rules/lightness-notation/__tests__/index.mjs
lib/rules/lightness-notation/index.cjs
lib/rules/lightness-notation/index.mjs

Closes #8659
The implementation of the current `roundToNumberOfDigits()` private function seems a bit too simple. This PR fixes the function only.

Fix `lightness-notation` crash with `"number"` option and single-digit percentage

---

.changeset/easy-oranges-punch.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs

followup of #8623
https://ladybird.org/newsletter/2025-07-31/#statefoo-and-unchecked-pseudo-classes
https://drafts.csswg.org/selectors/#checked

Fix `selector-pseudo-class-no-unknown` false positives for `:unchecked`

---

.changeset/clear-suns-trade.md
.changeset/modern-days-try.md
lib/rules/property-no-deprecated/README.md
lib/rules/property-no-deprecated/__tests__/index.mjs
lib/rules/property-no-deprecated/index.cjs
lib/rules/property-no-deprecated/index.mjs

Closes #8698 
This PR consists of two fixes: the discussion of the first one can be found in thread #8698 , and the second one is [here](https://github.com/stylelint/stylelint/pull/8682#discussion_r2247806673).
Both are related to inaccuracies made when adding the `property-no-deprecated` rule in the previous release.

Fix `property-no-deprecated` false positive for `-webkit-box-orient: vertical`

---

lib/__tests__/fixtures/postcss-naive-css-in-js.cjs

Ref https://github.com/stylelint/stylelint/pull/8701#discussion_r2250793041
This makes the `postcss-naive-css-in-js` fixture stricter for a case when an input source doesn't contain a valid CSS-in-JS code.
Example:
```
● color-hex-length › accept › [ 'short' ] › 'css` color: #aaa; `' › no description
No CSS-in-JS code found in the input source. Ensure it contains valid CSS-in-JS code, such as "css` color: red; `;"
```

Improve `postcss-naive-css-in-js` test fixture

---

.changeset/fair-sloths-visit.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-type-no-unknown/__tests__/index.mjs

#8713
followup of #7612
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/selectedcontent

Fix `selector-type-no-unknown` false positives for `selectedcontent`

---

lib/rules/nesting-selector-no-missing-scoping-root/README.md
lib/rules/nesting-selector-no-missing-scoping-root/__tests__/index.mjs
lib/rules/nesting-selector-no-missing-scoping-root/index.cjs
lib/rules/nesting-selector-no-missing-scoping-root/index.mjs
types/stylelint/index.d.ts

Closes #8728
Useful for at-rules like `@mixin` from SCSS and `@utility` from Tailwind CSS.

Add `ignoreAtRules: []` to `nesting-selector-no-missing-scoping-root`

---

.changeset/yummy-actors-serve.md
lib/reference/selectors.cjs
lib/reference/selectors.mjs
lib/rules/selector-pseudo-class-no-unknown/__tests__/index.mjs

N/A
LadybirdBrowser/ladybird#5830
https://developer.mozilla.org/en-US/docs/Web/CSS/:heading_function#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/:heading#browser_compatibility

Fix `selector-pseudo-class-no-unknown` false positives for `:heading`

---

CHANGELOG.md

None, as it's a documentation fix to the changelog.
Ref: https://github.com/stylelint/stylelint/pull/8564#pullrequestreview-3225654245
This is the last mention of violation after we standardised on problem a while back.

Document problem rather than violation to be consistent

---

README.md

Closes #8765
Our messaging around sponsorship got a bit mixed up since we enabled GitHub sponsors alongside our existing Open Collective. For example, we have a $100 GitHub sponsor tier that states your logo will appear in our README, but that only happens for our Open Collective sponsors because we use Open Collective's embed, or the fact that we also display Open Collective _backer_ logos in our README, undermining a perk of being a _sponsor_.
The wording used across GitHub sponsors and Open Collective differs, adding to the confusion. For example, Open Collective uses "financial contributions" as an umbrella term for sponsors, backers and donations (which can be one-off or …

Document sponsors, backers and donors

---

.github/workflows/release-pr.yml

Blocked by <https://github.com/stylelint/.github/pull/66>
This PR fixes the error below:
```
Error: Either `new-version` or `new-version-command` input is required.
```
Ref https://github.com/stylelint/stylelint/actions/runs/18218125564/job/51871855921#step:6:25

Fix `release-pr` workflow failure
