package.json
Tweaks the npm run-scripts so they are compatible on windows.
Did I do this PR right?
=> 0.1.0 windows compat

docs/adding-a-new-rule.md
Making a start on getting the documentation ready for contributors.
Ref: #14 & #15
=> Add adding-a-new-rule.md doc

src/rules/declaration-no-important/README.md, src/rules/declaration-no-important/__tests__/index.js, src/rules/declaration-no-important/index.js, src/rules/index.js
If you guys have a moment, could you look over it?
Is the "if `false` do nothing" thing weird?
The readme is super basic:
* Rule name
* One line description
* Example CSS code
* Options
@davidtheclark I'll wait until you've got something for `rule-set-no-single-line` and then I'll, if needed, align this PR with the your code as that is also a `*-no-*` rule and I'll follow your lead on it. Sound good? 
Documentation ref: #11 
Closes #17
=> New rule: declaration-no-important

README.md
To make them nice and neat :)
Ref #15
=> Standardise badges

CONTRIBUTING.md, README.md, docs/adding-a-new-rule.md
Continuing to get things ready for potential new contributors.
It's a very basic start, but it's something. Is it Ok?
Ref #15
=> Contributing

src/rules/declaration-bang-space/index.js, src/rules/declaration-block-trailing-semicolon/index.js, src/rules/declaration-colon-space/index.js, src/rules/declaration-no-important/index.js, src/rules/number-leading-zero/index.js, src/rules/rule-set-no-single-line/index.js, src/rules/selector-combinator-space/index.js
=> Standardise messages across rules. Closes #46.

src/rules/declaration-comma-space/__tests__/index.js, src/rules/declaration-comma-space/index.js
Very similar to `function-comma-space`.
=> Create and test declaration-comma-space

src/rules/function-comma-space/__tests__/index.js, src/rules/function-comma-space/index.js
I think there's nothing new or strange about this one ... finally.
Except ... anybody know of valid comma-requiring functions that might nest inside each other? I have an `rgb()` nested inside `color()`, but `color()` itself doesn't take commas ... that's just another test case to try.
=> Create and test function-comma-space

src/rules/block-opening-brace-space/README.md, src/rules/declaration-bang-space/README.md, src/rules/declaration-block-trailing-semicolon/README.md, src/rules/declaration-colon-space/README.md, src/rules/declaration-no-important/README.md, src/rules/number-leading-zero/README.md, src/rules/rule-set-no-single-line/README.md, src/rules/selector-combinator-space/README.md
=> Add documentation to remaining rules

src/rules/block-closing-brace-newline/__tests__/index.js, src/rules/block-closing-brace-newline/index.js, src/rules/block-closing-brace-space/__tests__/index.js
Also fixed copy-paste mistake in block-closing-brace-space tests.
=> Create and test block-closing-brace-newline; closes #21

src/rules/number-leading-zero/index.js, src/rules/number-no-trailing-zeros/__tests__/index.js, src/rules/number-no-trailing-zeros/index.js
If anybody has any ideas of other important tests to include, please toss 'em out. I couldn't think of much --- really simple.
=> Create and test number-no-trailing-zeros; closes #66

src/rules/function-token-no-space/__tests__/index.js, src/rules/function-token-no-space/index.js
Two things I wanted to point out, not specific to this PR:
- The latest batch of PRs I've been submitting instead of just merging directly into master just to make sure the commits were on people's radar and you had the chance to look and make suggestions for different methods or other tests. If you'd prefer that I just merge things into master unless there's a question of theory, let me know :)
- In case it's not clear already, when I have periods of time to work on this my goal is to pound out rules pretty quickly, try to find the unanswered questions and weak spots, etc. Because I'm moving quickly every once and a while I look back at things and notice little typos here and there, etc. I'm thinking that we're still at the stage where fast iteration is top priority --- I fully intend to …
=> Create and test function-token-no-space; closes #83

src/rules/declaration-comma-space-after/__tests__/index.js, src/rules/declaration-comma-space-after/index.js, src/rules/declaration-comma-space-before/__tests__/index.js, src/rules/function-comma-space-after/__tests__/index.js, src/rules/function-comma-space-after/index.js, src/rules/function-comma-space-before/__tests__/index.js, src/rules/function-parentheses-inside-space/__tests__/index.js, src/rules/function-parentheses-inside-space/index.js, src/rules/function-space-after/__tests__/index.js, src/rules/function-space-after/index.js, src/rules/function-token-no-space/__tests__/index.js, src/rules/function-token-no-space/index.js, src/utils/index.js, src/utils/valueIndexOf.js
=> Create valueIndexOf which handles strings and functions; fixes #85

src/rules/block-no-empty/__tests__/index.js, src/rules/block-no-empty/index.js
=> Create and test block-no-empty; closes #100

package.json, src/rules/indentation/__tests__/at-rules.js, src/rules/indentation/__tests__/index.js, src/rules/indentation/__tests__/rules.js, src/rules/indentation/index.js, src/utils/__tests__/valueIndexOf-test.js, src/utils/valueIndexOf.js
I think this is a solid start on `indentation` now, including functionality for the `block` and `value` options.
I used lodash's _.repeat function because it wasn't immediately clear how to best use babel's polyfill in this setting. If anybody wants to figure that out, feel free to do so and replace the lodash function.
=> Indentation

src/rules/selector-delimiter-newline-after/__tests__/index.js, src/rules/selector-delimiter-newline-after/index.js, src/rules/selector-delimiter-newline-before/__tests__/index.js, src/rules/selector-delimiter-newline-before/index.js, src/rules/selector-delimiter-space-after/__tests__/index.js, src/rules/selector-delimiter-space-after/index.js, src/rules/selector-delimiter-space-before/__tests__/index.js, src/rules/selector-delimiter-space-before/index.js, src/testUtils/ruleTester.js
=> Selector delimiter

src/rules/function-url-quotes/__tests__/index.js, src/rules/function-url-quotes/index.js, src/utils/functionArguments.js, src/utils/ruleMessages.js
This would have to be merged after the function-calc-operator-space branch.
=> Create and test function-url-quotes; closes #117

src/rules/at-rule-no-vendor-prefix/__tests__/index.js, src/rules/at-rule-no-vendor-prefix/index.js, src/rules/property-no-vendor-prefix/index.js, src/rules/property-value-no-vendor-prefix/__tests__/index.js, src/rules/property-value-no-vendor-prefix/index.js, src/rules/selector-no-vendor-prefix/__tests__/index.js, src/rules/selector-no-vendor-prefix/index.js, src/utils/index.js, src/utils/isAutoprefixable.js
property, property-value, selector, and at-rule.
I tried to whatever I could find in Autoprefixer to make the check as complete as possible.
=> no-vendor-prefix rules

src/rules/at-rule-no-vendor-prefix/README.md, src/rules/block-no-empty/README.md, src/rules/color-no-invalid-hex/README.md, src/rules/declaration-block-no-duplicate-properties/README.md, src/rules/declaration-no-important/README.md, src/rules/function-calc-no-unspaced-operator/README.md, src/rules/function-parentheses-inside-space/README.md, src/rules/function-space-after/README.md, src/rules/function-token-no-space/README.md, src/rules/function-url-quotes/README.md, src/rules/media-feature-colon-space-after/README.md, src/rules/media-feature-colon-space-before/README.md, src/rules/media-feature-range-operator-space-after/README.md, src/rules/media-feature-range-operator-space-before/README.md, src/rules/media-query-parentheses-inside-space/README.md, src/rules/no-eol-whitespace/README.md, src/rules/no-missing-eof-newline/README.md, src/rules/number-no-trailing-zeros/README.md, src/rules/property-no-vendor-prefix/README.md, src/rules/property-value-no-vendor-prefix/README.md, src/rules/root-no-standard-properties/README.md, src/rules/rule-set-non-nested-empty-line-before/README.md, src/rules/selector-delimiter-newline-after/README.md, src/rules/selector-delimiter-newline-before/README.md, src/rules/selector-delimiter-space-after/README.md, src/rules/selector-delimiter-space-before/README.md, src/rules/selector-no-vendor-prefix/README.md, src/rules/selector-root-no-composition/README.md, src/rules/string-quotes/README.md
There wasn't a power socket on the train and my battery is dead, so I'm only just making a start of these now.
Ref: #92
=> Add docs for some of the outstanding rules

src/rules/index.js
@stylelint/owners Is this the correct syntax?
=> ES6-style rule imports. Closes #154

src/rules/media-query-list-comma-newline-after/__tests__/index.js, src/rules/media-query-list-comma-newline-after/index.js, src/rules/media-query-list-comma-newline-before/__tests__/index.js, src/rules/media-query-list-comma-newline-before/index.js, src/rules/media-query-list-comma-space-after/__tests__/index.js, src/rules/media-query-list-comma-space-after/index.js, src/rules/media-query-list-comma-space-before/__tests__/index.js, src/rules/media-query-list-comma-space-before/index.js
=> media-query-list-comma-*

docs/rules.md, src/rules/number-zero-length-no-unit/README.md
I quite like writing these docs as it helps me familiarize myself with the expected behaviour of each rule :)
=> Add doc for zero-length rule

package.json, src/rules/selector-no-id/__tests__/index.js, src/rules/selector-no-id/index.js
This is the first effort to use postcss-selector-parser.
@ben-eb if you wouldn't mind, please take a look and see if I'm using the selector-parser as you intended :)
=> Create and test selector-no-id

src/rules/rule-nested-empty-line-before/README.md, src/rules/rule-nested-empty-line-before/__tests__/index.js, src/rules/rule-non-nested-empty-line-before/index.js
=> Added -except-first options to rule-nested-empty. Closes #185.

src/rules/number-leading-zero/__tests__/index.js, src/rules/number-leading-zero/index.js, src/rules/number-no-trailing-zeros/__tests__/index.js, src/rules/number-no-trailing-zeros/index.js, src/rules/number-zero-length-no-unit/__tests__/index.js, src/rules/number-zero-length-no-unit/index.js
=> Number media

src/rules/index.js, src/rules/rule-properties-order/README.md, src/rules/rule-properties-order/__tests__/index.js, src/rules/rule-properties-order/index.js
I thought I'd make a start on this one.
You can specify either alphabetical or supply your own list of properties.
Ok with you guys?
=> Add rule-properties-order

docs/rules.md, src/rules/index.js, src/rules/property-blacklist/README.md, src/rules/property-blacklist/__tests__/index.js, src/rules/property-blacklist/index.js
Have I used the arrow functions appropriately?
=> Property blacklist

README.md
=> Add requirements to readme. Closes #201.

src/rules/index.js, src/rules/selector-no-type/README.md, src/rules/selector-no-type/__tests__/index.js, src/rules/selector-no-type/index.js, src/rules/selector-no-universal/README.md, src/rules/selector-no-universal/__tests__/index.js, src/rules/selector-no-universal/index.js
These ones are easy thanks to postcss-selector-parser.
=> A couple more selector-no rules

package.json, src/index.js, src/rules/at-rule-empty-line-before/README.md, src/rules/at-rule-empty-line-before/__tests__/index.js, src/rules/at-rule-empty-line-before/index.js, src/rules/comment-empty-line-before/README.md, src/rules/comment-empty-line-before/__tests__/index.js, src/rules/comment-empty-line-before/index.js, src/rules/indentation/__tests__/at-rules.js, src/rules/indentation/__tests__/rules.js, src/rules/indentation/index.js, src/rules/rule-nested-empty-line-before/README.md, src/rules/rule-nested-empty-line-before/__tests__/index.js, src/rules/rule-nested-empty-line-before/index.js, src/rules/rule-non-nested-empty-line-before/README.md, src/rules/rule-non-nested-empty-line-before/index.js, src/testUtils/ruleTester.js, src/utils/index.js, src/utils/optionsHaveException.js, src/utils/optionsHaveIgnored.js
@jeddy3 I found a minute to try taking care of this. I think this does what we want. If you start building a rule with secondary options give it a shot and let me know if it doesn't :)
=> Allow for both primary and secondary options

src/rules/rule-nested-empty-line-before/__tests__/index.js, src/rules/rule-non-nested-empty-line-before/__tests__/index.js, src/rules/rule-non-nested-empty-line-before/index.js
=> Can ignore empty line before rules after comments; closes #228

src/rules/property-whitelist/README.md, src/rules/property-whitelist/__tests__/index.js, src/rules/property-whitelist/index.js
=> Create and test property-whitelist

src/rules/declaration-block-semicolon-newline-after/README.md, src/rules/declaration-block-semicolon-newline-after/__tests__/index.js, src/rules/declaration-block-semicolon-newline-after/index.js, src/rules/declaration-block-semicolon-newline-before/README.md, src/rules/declaration-block-semicolon-newline-before/__tests__/index.js, src/rules/declaration-block-semicolon-newline-before/index.js, src/rules/declaration-block-semicolon-space-after/__tests__/index.js
Ref #231 .
Another 3 sets to go and then I think we're going pretty close to being able to cut our first release. :)
=> Standardise decl-block-semi options

src/rules/media-query-list-comma-newline-after/README.md, src/rules/media-query-list-comma-newline-after/__tests__/index.js, src/rules/media-query-list-comma-newline-after/index.js, src/rules/media-query-list-comma-newline-before/README.md, src/rules/media-query-list-comma-newline-before/__tests__/index.js, src/rules/media-query-list-comma-newline-before/index.js, src/rules/media-query-list-comma-space-after/README.md, src/rules/media-query-list-comma-space-after/index.js, src/rules/media-query-list-comma-space-before/README.md, src/rules/media-query-list-comma-space-before/index.js
@davidtheclark Thanks again for the `whitespaceChecker` changes. It made updating these `media-query-list-*` rules much easier!
=> Standardise media-query-list-* options

src/rules/at-rule-empty-line-before/README.md, src/rules/at-rule-empty-line-before/__tests__/index.js, src/rules/at-rule-empty-line-before/index.js
I see now that this still needs some more tests and documentation. Hold on a minute ...
=> Except and ignore options for at-rule-line-before; closes #256

README.md
Ref #15 
@davidtheclark Merge this in when you're ready to do the release :)
=> Add note about accurate line numbers

README.md
So people won't come to complain :)
=> Add a note about rules configuration using integer

README.md
=> Add with css processor instructions

src/rules/indentation/README.md, src/rules/indentation/__tests__/at-rules.js, src/rules/indentation/__tests__/comments.js, src/rules/indentation/__tests__/hierarchical.js, src/rules/indentation/__tests__/index.js, src/rules/indentation/__tests__/rules.js, src/rules/indentation/index.js, src/testUtils/ruleTester.js
@MoOx and @magsout: I'm particularly interested in your input on this implementation, because you would end up using this. If you can think of more situations we should test, let me know.
=> Hierarchical indentation; closes #278

README.md
Added link to https://github.com/kungfusheep/SublimeLinter-contrib-stylelint which is a Sublime Text plugin for Stylelint
=> Update to include Sublime Text plugin

README.md
=> Add cssfmt to readme

src/rules/indentation/__tests__/rules.js, src/rules/indentation/index.js
@jeddy3: If you want to cut a patch release after merging this, I think @onigoetz will have a version that fixes his problems.
=> Indentation handles * hacks; fixes #358

src/rules/indentation/__tests__/at-rules.js, src/rules/indentation/__tests__/comments.js, src/rules/indentation/__tests__/hierarchical.js, src/rules/indentation/__tests__/rules.js, src/rules/indentation/__tests__/selectors.js, src/rules/indentation/index.js
Set to merge into "position-accuracy" branch.
=> Make indentation message consistent with other root rules

README.md
Morning. 
Just a quick update to the readme. Is there anything else to do, or shall I release `1.0.0` today? :)
=> Remove comment about position accuracy from readme

CHANGELOG.md, README.md
I figured the best place for the compatibility note was within "Installation". OK with you?
=> V1 documentation

CHANGELOG.md, docs/rules.md, src/rules/function-linear-gradient-no-nonstandard-direction/README.md, src/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js, src/rules/function-linear-gradient-no-nonstandard-direction/index.js, src/rules/index.js
Closes #362 ... unless we want to validate other parts of the linear-gradient syntax, or other gradient functions.
=> Add function-linear-gradient-no-nonstandard-direction rule

.travis.yml, appveyor.yml
A bit of repo spring cleaning before the big release.
=> Add node v4 to CI

package.json, src/__tests__/standalone-test.js, src/plugin.js
Thanks to the wonderfully serendipitous discovery of https://github.com/sindresorhus/resolve-from (thanks @sindresorhus! so wonderful to have found that module!), I think I was able to solve the problems in #413 while actually *simplifying* the code.
@jeddy3 : Could you see if this works in all the situations you've contrived?
=> Smarter relative requires for extends and plugins; fixes #413

CHANGELOG.md, docs/user-guide/rules.md, src/rules/function-comma-newline-after/README.md, src/rules/function-comma-newline-after/__tests__/index.js, src/rules/function-comma-newline-after/index.js, src/rules/function-comma-newline-before/README.md, src/rules/function-comma-newline-before/__tests__/index.js, src/rules/function-comma-newline-before/index.js, src/rules/function-comma-space-after/README.md, src/rules/function-comma-space-after/__tests__/index.js, src/rules/function-comma-space-after/index.js, src/rules/function-comma-space-before/README.md, src/rules/function-comma-space-before/__tests__/index.js, src/rules/function-comma-space-before/index.js, src/rules/index.js
Addresses #405.
@jeddy3 : Would you mind adding documentation for these new rules and options?
=> Function comma improvements

CHANGELOG.md, docs/user-guide/rules.md, src/rules/color-no-hex/README.md, src/rules/color-no-hex/__tests__/index.js, src/rules/color-no-hex/index.js, src/rules/index.js
ref : #425.
Simply added by imitating `color-no-invalid-hex`.
=> add rule-color-no-hex

CHANGELOG.md, docs/user-guide/rules.md, src/rules/function-blacklist/index.js, src/rules/function-whitelist/README.md, src/rules/function-whitelist/__tests__/index.js, src/rules/function-whitelist/index.js, src/rules/index.js
to use new indexOffset utility
=> Add function-whitelist and update blacklist

CHANGELOG.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/unit-blacklist/README.md, src/rules/unit-blacklist/__tests__/index.js, src/rules/unit-blacklist/index.js
=> Add rule : unit-blacklist

CHANGELOG.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/unit-whitelist/README.md, src/rules/unit-whitelist/__tests__/index.js, src/rules/unit-whitelist/index.js
=> Add rule : unit-whitelist

CHANGELOG.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/property-unit-blacklist/README.md, src/rules/property-unit-blacklist/__tests__/index.js, src/rules/property-unit-blacklist/index.js
Ref: https://github.com/stylelint/stylelint/issues/430
=> Add rule : property-unit-blacklist

CHANGELOG.md, src/rules/function-space-after/README.md, src/rules/function-space-after/__tests__/index.js, src/rules/function-space-after/index.js
This implements the plan described here: https://github.com/stylelint/stylelint/issues/451#issuecomment-150824043
=> Allow arbitrary whitespace in function-space-after; closes #451

CHANGELOG.md, src/rules/comment-space-inside/README.md, src/rules/comment-space-inside/__tests__/index.js, src/rules/comment-space-inside/index.js, src/rules/function-space-after/README.md
If we merge this, we'd want to create an issue like https://github.com/stylelint/stylelint/issues/472 for the renaming.
=> Allow arbitrary whitespace in comment-space-inside; closes #403

docs/user-guide/css-processors.md
=> Add a small note about parsing scss to docs

src/rules/property-unit-blacklist/index.js
Ref: https://github.com/stylelint/stylelint/pull/471
=> Retrun early in same way as property-unit-whitelist

CHANGELOG.md, docs/user-guide/rules.md, src/rules/function-parentheses-newline-inside/README.md, src/rules/function-parentheses-newline-inside/__tests__/index.js, src/rules/function-parentheses-newline-inside/index.js, src/rules/function-parentheses-space-inside/README.md, src/rules/function-parentheses-space-inside/__tests__/index.js, src/rules/function-parentheses-space-inside/index.js, src/rules/index.js
I added `"always-single-line"` and `"never-multi-line"` options to `function-parentheses-space-inside`, and created `function-parentheses-newline-inside`. I have not yet documented but did write a fair number of tests.
=> Function paren newline (undocumented)

CHANGELOG.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-class-pattern/README.md, src/rules/selector-class-pattern/__tests__/index.js, src/rules/selector-class-pattern/index.js, src/rules/selector-id-pattern/README.md, src/rules/selector-id-pattern/__tests__/index.js, src/rules/selector-id-pattern/index.js, src/utils/validateOptions.js
=> selector-id-pattern and selector-class-pattern 

CHANGELOG.md, src/rules/selector-no-type/__tests__/index.js, src/rules/selector-no-type/index.js
=> Exclude nesting selector in selector-no-type

CHANGELOG.md, src/rules/comment-whitespace-inside/__tests__/index.js, src/rules/comment-whitespace-inside/index.js
Merges into `v3` as rule has been renamed.
=> Ignore sourcemap and copyright comments. Closes #532

CHANGELOG.md, src/rules/rule-no-duplicate-properties/__tests__/index.js, src/rules/rule-no-duplicate-properties/index.js
=> Ignore duplicate src properties.

CHANGELOG.md, docs/user-guide/configuration.md, package.json, src/__tests__/fixtures/config-color-no-invalid-hex.json, src/__tests__/fixtures/config-extending-and-ignoring.json, src/__tests__/standalone-test.js, src/buildConfig.js, src/postcssPlugin.js
This adds ignoreFiles functionality. Hopefully the docs included explain the feature.
=> Add ignoreFiles config option; closes #530

src/rules/rule-properties-order/README.md
@davidtheclark My bad. I missed the configuration examples in this README when I did the update. I’ve had a quick look through the other rule READMEs and I couldn’t see anymore.
Ref: https://github.com/stylelint/stylelint/issues/575
=> Update config syntax in examples

CHANGELOG.md, src/rules/rule-properties-order/__tests__/flat.js, src/rules/rule-properties-order/index.js
Some of this refactoring was not necessary, but just helped me read/understand the code better.
=> Fix rule-properties-order bug caused by unspecified props; fixes #576

src/postcssPlugin.js
Ref: https://github.com/stylelint/stylelint/issues/607#issuecomment-169672720
=> Expand configError message

docs/user-guide/postcss-plugin.md
Closes: https://github.com/stylelint/stylelint/issues/543
Sorry it took so long to get around to this one…
=> Add scss example to postcss plugin docs

package.json
Ref: https://github.com/stylelint/stylelint/issues/401
Just tidying up a couple of simple loose-ends issues.
We can give it a whirl on the next release.
=> Add release npm script

src/rules/selector-no-vendor-prefix/__tests__/index.js, src/rules/selector-no-vendor-prefix/index.js
Closes #624
@davidtheclark Is this the best way to protect against this?
=> Protect against custom properties

CHANGELOG.md, docs/user-guide/configuration.md, src/__tests__/fixtures/config-block-empty-ok.json, src/__tests__/integration.js, src/__tests__/standalone-test.js, src/buildConfig.js, src/postcssPlugin.js
All that deleted code is nice.
I caught all the places I could think of.
=> Remove support for numbered severities; closes #633

README.md
=> A hundred rules

README.md
=> Move understanding of SCSS to features

CHANGELOG.md, src/rules/function-whitespace-after/README.md, src/rules/function-whitespace-after/__tests__/index.js, src/rules/function-whitespace-after/index.js
=> Anticipate Sass interpolation; fixes #631

CHANGELOG.md, src/postcssPlugin.js, src/utils/__tests__/validateOptions-test.js, src/utils/validateOptions.js
@TrySound : Please try this branch out and see if it helps for the unhelpful error that you were seeing.
=> More helpful error when option should be object; closes #650

docs/user-guide/cli.md
Wondering if this would be helpful to add here?
=> cli.md: Add scss example

docs/user-guide/postcss-plugin.md
I forgot that `plugins` won't process entry point. Also we need to show that we process only one entry point.
=> Fix postcss-import recipe

CHANGELOG.md, docs/user-guide/rules.json, docs/user-guide/rules.md, src/rules/media-feature-no-missing-punctuation/README.md, src/rules/media-feature-no-missing-punctuation/__tests__/index.js, src/rules/media-feature-no-missing-punctuation/index.js
Any better name ideas are more than welcome.
=> Add media-feature-no-missing-punctuation; closes #692

package.json
1. For [offline doc reading](https://github.com/postcss/postcss/pull/716)
2. To trial idea I have for the stylelint website.
=> Add docs to package

CONTRIBUTING.md, README.md
Just sneaking in little docs amends before any release… :)
I’m not sure what you think of this one, but neither of us seems to use gitter - preferring issues over the expectation of real-time in gitter.
Perhaps we should be pointing to stack overflow instead for support?
=> Remove gitter

docs/developer-guide/plugins.md, src/__tests__/fixtures/plugin-conditionally-check-color-hex-case.js, src/__tests__/plugins-test.js, src/index.js
@kangax I think this was a good idea you had, making stylelint even more extensible. Could you please review this PR and see if the functionality it enables fits what you envisioned? And if the docs make sense?
=> Expose rules at stylelint.rules; closes #709

CHANGELOG.md, docs/user-guide/configuration.md, docs/user-guide/node-api.md, package.json, src/__tests__/standalone-test.js, src/buildConfig.js, src/postcssPlugin.js, src/standalone.js
@1000ch, @Arcanemagus: Does this look like it will work for the Atom linter plugin?
=> Add codeFilename option to Node API; closes #722

LICENSE
Just like https://github.com/stylelint/stylelint/commit/aa5f687f681ec2e809640be3806e8be2397e4c9e
=> Update to this year

package.json
=> Fix error "Cannot find module './testUtils/ruleTester'"

src/rules/declaration-no-important/README.md
Ref: https://github.com/stylelint/stylelint/issues/669
=> Add postcss-safe-important note

CHANGELOG.md, src/rules/font-weight-notation/README.md, src/rules/font-weight-notation/__tests__/index.js, src/rules/font-weight-notation/index.js
=> Add ignore relative option to font-weight-notation

CHANGELOG.md, src/rules/font-weight-notation/__tests__/index.js, src/rules/font-weight-notation/index.js, src/rules/rule-properties-order/README.md, src/rules/rule-properties-order/__tests__/flat.js, src/rules/rule-properties-order/index.js
=> Add bottomAlphabetical option

docs/user-guide/example-config.md
Mainly:
- where to did find the list of rules
- how to turn rules off
- rule naming conventions.
=> Provide more context to the example config

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, package.json, src/rules/index.js, src/rules/no-browser-hacks/README.md, src/rules/no-browser-hacks/__tests__/index.js, src/rules/no-browser-hacks/index.js
There is one problem I will comment on below. Otherwise, it's documented and ready to go.
=> Add no-browser-hacks rule; closes #787

README.md, docs/user-guide.md, docs/user-guide/css-processors.md, docs/user-guide/postcss-plugin.md
To make it a bit clearer what needs to be done to use stylelint on scss files.
=> Expand scss syntax docs

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, package.json, src/rules/index.js, src/rules/selector-max-specificity/README.md, src/rules/selector-max-specificity/__tests__/index.js, src/rules/selector-max-specificity/index.js
Closes #721.
Thanks to @benfrain for this one!
I’ve wired up the rule and documentation.
I quickly aligned the rule code with some of our idiomatic conventions.
Same with the README.
=> Add selector-max-specificity

CHANGELOG.md, docs/user-guide/configuration.md, src/__tests__/integration.js, src/__tests__/normalizeRuleSettings-test.js, src/__tests__/standalone-test.js, src/postcssPlugin.js, src/utils/validateOptions.js
@jeddy3 If you have the time I'd appreciate some extra help integration/regression testing this change. I think it works, but just want to make sure before it doesn't make things go haywire before we release.
=> Add severity secondary option; deprecate warn; closes #776

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, package.json, src/rules/index.js, src/rules/no-unsupported-browser-features/README.md, src/rules/no-unsupported-browser-features/__tests__/index.js, src/rules/no-unsupported-browser-features/index.js
=> Add no-unsupported-browser-features; closes #644

package.json, src/rules/no-browser-hacks/index.js
=> Update stylehacks and take advantage; closes #828

CHANGELOG.md, src/rules/selector-no-vendor-prefix/__tests__/index.js, src/rules/selector-no-vendor-prefix/index.js
=> Fix bug with double-coloned vendor-prefixed psuedos; fixes #827

CHANGELOG.md, src/rules/at-rule-empty-line-before/__tests__/index.js, src/rules/at-rule-empty-line-before/index.js, src/rules/comment-empty-line-before/__tests__/index.js, src/rules/comment-empty-line-before/index.js, src/rules/rule-nested-empty-line-before/__tests__/index.js, src/rules/rule-non-nested-empty-line-before/__tests__/index.js, src/rules/rule-non-nested-empty-line-before/index.js
=> Fix handling of mixed line endings

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/plugins.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/max-nesting-depth/README.md, src/rules/max-nesting-depth/__tests__/index.js, src/rules/max-nesting-depth/index.js
If anybody wants to put some work in trying this out, testing the logic, hunting for edge-cases --- or has feedback about the options/naming --- all input welcome!
=> Add max-nesting-depth; closes #854

CHANGELOG.md, src/rules/declaration-colon-newline-after/__tests__/index.js, src/rules/declaration-colon-newline-after/index.js, src/rules/declaration-colon-space-after/__tests__/index.js, src/rules/declaration-colon-space-after/index.js, src/rules/declaration-colon-space-before/__tests__/index.js
=> Fix more false positives with urls(); closes #841

package.json
=> Pin ESLint 2.2.0

CHANGELOG.md, src/rules/no-duplicate-selectors/__tests__/index.js, src/rules/no-duplicate-selectors/index.js
=> Ignore keyframe selectors in no-duplicate-selectors

CHANGELOG.md, docs/user-guide/configuration.md, src/__tests__/disableRanges-test.js, src/disableRanges.js, src/utils/__tests__/report-test.js, src/utils/report.js
Interesting, tricky one here. Any additional help with integration and regression testing would be much appreciated.
=> Support overlapping disabled ranges; closes #840

docs/user-guide/rules.md
Correct reference of `property-value-whiteist` to the right doc.
=> Corrected rules list reference

docs/user-guide/cli.md
Ref: #915
A quick, late night, doc fix before I crash :)
=> Wrap globs in quotes within the docs

docs/user-guide/plugins.md
Added my personal plugin for stylelint `stylelint-declaration-use-variable` in the user documentation.
@davidtheclark Please review. Thanks.
=> Added plugin in docs.

README.md, docs/developer-guide/rules.md
What do you think of these additions?
=> Add more contribution docs; closes #912

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-type-case/README.md, src/rules/selector-type-case/__tests__/index.js, src/rules/selector-type-case/index.js
Added rule for selector-type-case that checks the upper and lower case-sensitivity for selectors.
=> Refs #908 - Added selector-type-case rule.

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, package.json, src/rules/index.js, src/rules/no-indistinguishable-colors/__tests__/index.js, src/rules/no-indistinguishable-colors/index.js
=> Upgrade colorguard

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/at-rule-blockless-newline-after/README.md, src/rules/at-rule-blockless-newline-after/__tests__/index.js, src/rules/at-rule-blockless-newline-after/index.js, src/rules/index.js
Any feedback or review on this is very welcome.
=> Add new rule at-rule-blockless-newline-after

CHANGELOG.md, src/rules/font-weight-notation/__tests__/index.js, src/rules/font-weight-notation/index.js
=> Issue #934

CHANGELOG.md, src/rules/indentation/__tests__/selectors.js, src/rules/indentation/index.js, src/testUtils/createStylelintRuleTester.js
=> Fix at-rule nest treatment in indentation; closes #921

CHANGELOG.md, src/rules/number-no-trailing-zeros/__tests__/index.js, src/rules/number-no-trailing-zeros/index.js
=> Fix false positive in number-no-trailing-zeros

CHANGELOG.md, docs/user-guide/rules.md, src/rules/stylelint-disable-reason/README.md, src/rules/stylelint-disable-reason/__test__/index.js, src/rules/stylelint-disable-reason/index.js
Previous PR broke my IDE, sorry.
=> Add rule stylelint-disable-reason

CHANGELOG.md, src/rules/root-no-standard-properties/__tests__/index.js, src/rules/root-no-standard-properties/index.js
=> Fix false positive in root-no-standard-properties

src/rules/function-comma-newline-after/__tests__/index.js, src/rules/function-comma-newline-before/__tests__/index.js, src/rules/function-comma-space-after/__tests__/index.js, src/rules/function-comma-space-after/index.js, src/rules/function-comma-space-before/__tests__/index.js, src/rules/function-parentheses-newline-inside/__tests__/index.js, src/rules/function-parentheses-newline-inside/index.js, src/rules/function-parentheses-space-inside/__tests__/index.js, src/rules/function-parentheses-space-inside/index.js
=> Ignore scss maps within function-* rules

CHANGELOG.md, docs/user-guide/rules.md, src/rules/function-max-empty-lines/README.md, src/rules/function-max-empty-lines/__test__/index.js, src/rules/function-max-empty-lines/index.js
=> function-max-empty-lines rule

CHANGELOG.md, src/rules/function-max-empty-lines/__test__/index.js, src/rules/index.js
change `stylelint-test-rule-tape` to `testRule`, correct import new rule, fix typo in CHANGELOG.md
=> issue with merge rule `function-max-empty-lines`

CHANGELOG.md, src/rules/selector-class-pattern/__tests__/index.js, src/rules/selector-class-pattern/index.js, src/rules/selector-id-pattern/__tests__/index.js, src/rules/selector-id-pattern/index.js
=> Fixing: selector-class-pattern and selector-id-pattern SCSS interpolation

docs/developer-guide/rules.md
Ref: https://github.com/stylelint/stylelint/issues/882#issuecomment-203513933
With the quantity of new rule and options requests we’re getting, I figured I’d quickly document our secondary options conventions before things go awry as (as far as I can tell) they’re all spot on at the moment.
=> Expand secondary options documentation

CHANGELOG.md, src/rules/block-closing-brace-newline-after/README.md, src/rules/block-closing-brace-newline-after/__tests__/index.js, src/rules/block-closing-brace-newline-after/index.js, src/rules/block-closing-brace-space-after/__tests__/index.js, src/rules/block-opening-brace-newline-after/index.js
=> Allow single-line comments after closing brace in closing-brace-newline-after

CHANGELOG.md, src/rules/block-closing-brace-newline-after/index.js
=> Correct closing-brace-newline messages

README.md, docs/user-guide/about-rules.md, docs/user-guide/css-processors.md, docs/user-guide/example-config.md, docs/user-guide/faq.md
A few fixes after reading through the recent doc changes with a fresh pair of eyes.
=> Fix typos and broken links

src/rules/declaration-block-trailing-semicolon/__tests__/index.js
=> Add failing test for #1043

package.json
v0.4.0 adds regular expression support
• https://github.com/juliangruber/balanced-match/compare/v0.3.0...v0.4.0
=> Update balanced-match NPM module

CHANGELOG.md, src/rules/indentation/README.md, src/rules/indentation/__tests__/at-rules.js, src/rules/indentation/__tests__/functions.js, src/rules/indentation/__tests__/hierarchical.js, src/rules/indentation/__tests__/rules.js, src/rules/indentation/__tests__/selectors.js, src/rules/indentation/index.js
=> Indentation enhancements

README.md
As the build tools plugins and editor plugins are out of our control.
=> Swap usage methods around

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-pseudo-class-parentheses-space-inside/README.md, src/rules/selector-pseudo-class-parentheses-space-inside/__test__/index.js, src/rules/selector-pseudo-class-parentheses-space-inside/index.js
https://github.com/stylelint/stylelint/issues/1073
=> `selector-pseudo-class-parentheses-space-inside` rule

CHANGELOG.md, src/rules/value-keyword-case/README.md, src/rules/value-keyword-case/__test__/index.js, src/rules/value-keyword-case/index.js
https://github.com/stylelint/stylelint/issues/1082
=> add `ignoreKeywords` option for `value-keyword-case`.

src/utils/__tests__/matchesStringOrRegExp-test.js, src/utils/matchesStringOrRegExp.js
Needed for https://github.com/stylelint/stylelint/pull/1080
=> Add match data to output of `matchesStringOrRegExp`

CHANGELOG.md, src/rules/value-keyword-case/__test__/index.js, src/rules/value-keyword-case/index.js
https://github.com/stylelint/stylelint/issues/1089
=> ignore camel case keywords in rule `value-keyword-case`

CHANGELOG.md, src/rules/font-weight-notation/__tests__/index.js, src/utils/__tests__/isStandardValue-test.js, src/utils/isStandardValue.js
Ref: https://github.com/stylelint/stylelint/issues/1133
=> Ignore scss interpolation in font-weight-notation

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/no-extra-semicolons/README.md, src/rules/no-extra-semicolons/__tests__/index.js, src/rules/no-extra-semicolons/index.js
I spent the whole day in the attempt to write this rule, a lot of difference algorithms and logic, the only thing that could do, it was hard to come to this solution :crying_cat_face: . I think need some more test.
=> New rule `no-extra-semicolons`.

package.json
=> Update `postcss-less` to v0.10.0

docs/user-guide/articles.md
I figured it was worth adding a note to each article if it advocates something we’d now advise against.
=> Add article doc. Closes #1172

CHANGELOG.md, src/rules/function-url-data-uris/__tests__/index.js, src/rules/function-url-data-uris/index.js, src/rules/function-url-quotes/__tests__/index.js, src/rules/function-url-quotes/index.js
=> issue with spaces in `function-url-quotes`

src/rules/stylelint-disable-reason/index.js
https://github.com/stylelint/stylelint/issues/1173
@jeddy3 @davidtheclark
=> fix issue 1173

CHANGELOG.md, src/rules/number-max-precision/__tests__/index.js, src/rules/number-max-precision/index.js
=> Ignore at-import and url functions in number-max-precision

src/rules/declaration-block-no-ignored-properties/index.js
=> fix crash on nested selectors

CHANGELOG.md, src/rules/block-closing-brace-newline-before/__tests__/index.js, src/rules/block-closing-brace-newline-before/index.js
https://github.com/stylelint/stylelint/issues/1212
=> Extra semicolon causes false positive.

src/testUtils/createRuleTester.js
Right now `only` doesn't work very well. It ends up only *printing* the results of the one test but in fact *runs* the code from every test. This is annoying if you want to use the console to log something to help with debugging.
What I tried to do here is alter `createRuleTester` so that a test-case with `only` will be the only case whose code runs.
There's a built-in assumption here that the rule tester will not be used asynchronously (`process.nextTick()`). Haven't had any trouble with this in my experiments. If it does become a problem someone would have to build in a `.plan()` function, probably, like what `tape` has.
=> Improve only functionality in rule tester

CHANGELOG.md, src/rules/font-family-name-quotes/__tests__/index.js, src/rules/font-family-name-quotes/index.js
=> Case sensitive problem with `font-family`

src/__tests__/integration.js
=> SCSS integration test

src/rules/index.js
@davidtheclark i think we should write tests, sometimes accidentally forget
=> forgot import

CHANGELOG.md, src/rules/function-blacklist/__tests__/index.js, src/rules/function-blacklist/index.js, src/rules/function-whitelist/__tests__/index.js, src/rules/function-whitelist/index.js, src/rules/no-unknown-animations/__tests__/index.js, src/rules/no-unknown-animations/index.js, src/rules/property-unit-blacklist/__tests__/index.js, src/rules/property-unit-blacklist/index.js, src/rules/property-unit-whitelist/__tests__/index.js, src/rules/property-unit-whitelist/index.js, src/rules/selector-pseudo-class-no-unknown/__tests__/index.js, src/rules/selector-pseudo-class-no-unknown/index.js, src/rules/selector-pseudo-element-no-unknown/__tests__/index.js, src/rules/selector-pseudo-element-no-unknown/index.js, src/rules/unit-blacklist/__tests__/index.js, src/rules/unit-blacklist/index.js, src/rules/unit-no-unknown/__tests__/index.js, src/rules/unit-no-unknown/index.js, src/rules/unit-whitelist/__tests__/index.js, src/rules/unit-whitelist/index.js
Also we should add `i` flag to regex in `matchesStringOrRegExp`, if you agree, i fire this PR and add tests
=> issue with case sensitivity in some rules

CHANGELOG.md, src/rules/font-family-name-quotes/__tests__/index.js, src/rules/font-family-name-quotes/index.js, src/rules/media-feature-no-missing-punctuation/__tests__/index.js, src/rules/media-feature-no-missing-punctuation/index.js, src/rules/media-query-list-comma-newline-after/__tests__/index.js, src/rules/media-query-list-comma-newline-before/__tests__/index.js, src/rules/media-query-list-comma-space-after/__tests__/index.js, src/rules/media-query-list-comma-space-after/index.js, src/rules/media-query-list-comma-space-before/__tests__/index.js
https://github.com/stylelint/stylelint/issues/1239
=> Rules now better ignore SCSS and Less variables.

CHANGELOG.md, src/rules/no-unknown-animations/__tests__/index.js, src/rules/no-unknown-animations/index.js
https://github.com/stylelint/stylelint/issues/1240
=> `no-unknown-animations` now ignores `ease` value.

src/rules/selector-attribute-brackets-space-inside/__tests__/index.js
=> Add tests to selector `E[foo="bar" i]`.

src/rules/at-rule-empty-line-before/__tests__/index.js, src/rules/at-rule-name-space-after/__tests__/index.js, src/rules/color-hex-case/__tests__/index.js, src/rules/color-hex-length/__tests__/index.js, src/rules/comment-empty-line-before/__tests__/index.js, src/rules/comment-word-blacklist/__tests__/index.js, src/rules/function-max-empty-lines/__tests__/index.js, src/rules/indentation/__tests__/functions.js, src/rules/no-duplicate-selectors/__tests__/index.js, src/rules/no-extra-semicolons/__tests__/index.js, src/rules/selector-class-pattern/__tests__/index.js, src/rules/selector-id-pattern/__tests__/index.js, src/rules/selector-max-empty-lines/__tests__/index.js, src/rules/selector-no-qualifying-type/__tests__/index.js, src/rules/shorthand-property-no-redundant-values/__tests__/index.js
=> Fix tests.

CHANGELOG.md, src/rules/unit-no-unknown/__tests__/index.js, src/rules/unit-no-unknown/index.js
=> Bug with interpolation inside function

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, package.json, src/rules/index.js, src/rules/selector-type-no-unknown/README.md, src/rules/selector-type-no-unknown/__tests__/index.js, src/rules/selector-type-no-unknown/index.js
=> New rule `selector-type-no-unknown`.

src/rules/selector-type-no-unknown/index.js
=> Replace postcss-selector-parser on parseSelector.

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/keyframe-declaration-no-important/README.md, src/rules/keyframe-declaration-no-important/__tests__/index.js, src/rules/keyframe-declaration-no-important/index.js
=> New rule `keyframe-declaration-no-important`.

src/rules/selector-type-no-unknown/__tests__/index.js
=> Add tests.

CHANGELOG.md, src/__tests__/standalone-test.js, src/utils/validateOptions.js
Addresses #1232.
Notice this PR is set to merge into v7.
=> Invalid configuration sets stylelintError to true; closes #1232

src/__tests__/buildConfig-test.js, src/__tests__/fixtures/config-extending-with-plugin.json, src/__tests__/fixtures/ignore_config/.stylelintignore, src/buildConfig.js
Also refactored some parts of `buildConfig` while I was at it.
=> Add buildConfig unit tests; closes #570

CHANGELOG.md, src/reference/keywordSets.js, src/rules/value-keyword-case/__tests__/index.js, src/rules/value-keyword-case/index.js
=> Part of issue 1101

package.json
=> Update eslint config

src/rules/property-unit-blacklist/index.js, src/rules/property-unit-whitelist/index.js, src/rules/value-keyword-case/index.js
=> Refactoring rules use `getUnitFromValueNode`.

src/rules/at-rule-name-space-after/index.js, src/rules/font-family-name-quotes/__tests__/index.js, src/rules/font-weight-notation/__tests__/index.js
=> Add tests for coverage.

docs/user-guide/plugins.md
I wasn't sure what name to use for the header, so I used "Multiple rules".
=> Add stylelint-scss to plugins list

src/rules/color-named/index.js
=> Color named check is standard value

src/rules/function-blacklist/__tests__/index.js, src/rules/function-blacklist/index.js, src/rules/function-name-case/index.js, src/rules/function-url-data-uris/index.js
=> Add checks to function for faster their.

src/rules/shorthand-property-no-redundant-values/index.js
=> Add checks for speed rule.

src/rules/value-no-vendor-prefix/__tests__/index.js, src/rules/value-no-vendor-prefix/index.js
=> Refactoring and add tests.

src/rules/media-query-parentheses-space-inside/index.js
=> Add checks to media-query-parentheses-space-inside for faster their.

src/rules/at-rule-no-vendor-prefix/index.js
=> Speed up rule.

src/rules/media-feature-colon-space-after/index.js, src/rules/media-feature-name-no-vendor-prefix/index.js, src/rules/media-feature-range-operator-space-after/index.js, src/rules/media-feature-range-operator-space-before/index.js
=> Refactoring.

docs/developer-guide/plugins.md, docs/developer-guide/rules.md, docs/user-guide/configuration.md
=> Add npm plugin and config keywords to docs

CHANGELOG.md, src/rules/selector-pseudo-class-case/__tests__/index.js, src/rules/selector-pseudo-class-case/index.js, src/rules/selector-pseudo-class-no-unknown/__tests__/index.js, src/rules/selector-pseudo-class-no-unknown/index.js, src/rules/selector-pseudo-class-parentheses-space-inside/index.js, src/rules/selector-pseudo-element-case/__tests__/index.js, src/rules/selector-pseudo-element-case/index.js, src/rules/selector-pseudo-element-colon-notation/index.js, src/rules/selector-pseudo-element-no-unknown/__tests__/index.js, src/rules/selector-pseudo-element-no-unknown/index.js
=> Fix interpolation bug and checks.

CHANGELOG.md, src/rules/selector-max-compound-selectors/README.md, src/rules/selector-max-compound-selectors/__tests__/index.js
Did these tweaks myself instead of dragging out that PR any longer and being a jerk :)
=> Cleanup related to selector-max-compound-selectors

CHANGELOG.md, src/rules/selector-type-case/__tests__/index.js, src/rules/selector-type-no-unknown/__tests__/index.js, src/utils/__tests__/isStandardSelector-test.js, src/utils/isStandardSelector.js
=> Ignore SCSS placeholders in selector-type-* rules

docs/user-guide/release-planning.md
Ref: https://github.com/stylelint/stylelint/issues/1308
=> Update scope of deprecations in release planning doc

CHANGELOG.md, docs/user-guide/configuration.md, docs/user-guide/node-api.md, docs/user-guide/postcss-plugin.md, src/__tests__/buildConfig-test.js, src/__tests__/fixtures/ignore_config/foo.txt, src/__tests__/standalone-test.js, src/buildConfig.js, src/cli.js, src/standalone.js
I tried smoke-testing this locally, as well as the unit tests, and it seems to work as expected.
=> Add ignorePath option; closes #1127

src/reference/keywordSets.js, src/utils/__tests__/findListStyleType-test.js, src/utils/findListStyleType.js
/cc @davidtheclark @jeddy3 
Do not merge.
First we should merge https://github.com/stylelint/stylelint/pull/1224, after i rebase and merge `keywordSets`.
=> Add util `findListStyleType`.

CHANGELOG.md, src/rules/selector-combinator-space-after/__tests__/index.js, src/rules/selector-combinator-space-after/index.js, src/rules/selector-combinator-space-before/__tests__/index.js, src/rules/selector-no-combinator/__tests__/index.js
=> Ignore escaped combinator-like chars

README.md, docs/developer-guide/rule-testers.md, docs/developer-guide/rules.md, docs/user-guide/cli.md, docs/user-guide/configuration.md, docs/user-guide/faq.md, docs/user-guide/node-api.md, docs/user-guide/postcss-plugin.md, docs/user-guide/rules.md, src/rules/no-browser-hacks/README.md
and other docs revisions.
I had the opportunity to look through all the docs in one sitting with a fresh pair of eyes last week. Here’s some amends. Each is a separate commit to make the review easier.
=> Add installation instructions

CHANGELOG.md, docs/developer-guide/plugins.md
=> Deprecate stylelint.util.styleSearch

CHANGELOG.md, src/reference/keywordSets.js, src/rules/value-keyword-case/__tests__/index.js, src/rules/value-keyword-case/index.js, src/utils/__tests__/findListStyleType-test.js, src/utils/findFontFamily.js
=> Close issue 1101.

src/rules/declaration-block-trailing-semicolon/README.md
=> Add compatibility note

docs/developer-guide/rules.md
=> Add tests checklist

CHANGELOG.md, src/cli.js
=> Add -h alias for --help flag

CHANGELOG.md, scripts/visual.sh, src/cli.js
Closes https://github.com/stylelint/stylelint/issues/1450
=> Remove verbose flag

docs/user-guide/configuration.md
=> Update example to show multiple keywords

src/rules/at-rule-empty-line-before/README.md
=> Add ignore blockless-group docs

README.md
Closes https://github.com/stylelint/stylelint.io/issues/11
=> Add growing community feature

CHANGELOG.md, src/rules/no-unsupported-browser-features/README.md, src/rules/no-unsupported-browser-features/__tests__/index.js, src/rules/no-unsupported-browser-features/index.js
Closes #1474 
Ref: https://github.com/stylelint/stylelint/issues/1401
=> Clarify that only fully supported features pass

CHANGELOG.md, src/rules/function-name-case/README.md, src/rules/function-name-case/__tests__/index.js, src/rules/function-name-case/index.js, src/rules/value-keyword-case/__tests__/index.js
Close https://github.com/stylelint/stylelint/issues/1394
=> Add `ignoreFunctions` option to `function-name-case`

src/rules/indentation/__tests__/functions.js
=> Add indentInsideParens tabbed list tests

docs/user-guide/rules.md, src/rules/block-closing-brace-newline-after/README.md, src/rules/block-opening-brace-space-before/README.md, src/rules/declaration-block-properties-order/README.md, src/rules/font-family-name-quotes/README.md, src/rules/function-name-case/README.md, src/rules/indentation/README.md, src/rules/max-line-length/README.md, src/rules/max-nesting-depth/README.md, src/rules/no-browser-hacks/README.md, src/rules/no-indistinguishable-colors/README.md, src/rules/no-unsupported-browser-features/README.md, src/rules/selector-max-compound-selectors/README.md, src/rules/selector-max-specificity/README.md, src/rules/selector-pseudo-class-no-unknown/README.md, src/rules/selector-pseudo-element-no-unknown/README.md, src/rules/selector-type-no-unknown/README.md, src/rules/unit-no-unknown/README.md, src/rules/value-keyword-case/README.md
Ref: https://github.com/stylelint/stylelint.io/pull/14#issuecomment-227539891
=> Standardise wording in rule READMEs

docs/user-guide/complementary-tools.md
=> Added build tool plugins to readme

docs/user-guide/postcss-plugin.md
There are [more build tool plugins](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#build-tool-plugins) for stylelint now, including one for Grunt.
This PR updates the stylelint PostCSS plugin doc to use the PostCSS JS API in the examples as to discourage the use of `postcss-grunt`.
Using the PostCSS JS API means we don’t have to update this doc again when whenever PostCSS runner we use is replaced by a dedicated stylelint plugin.
=> Use PostCSS JS API within PostCSS plugin doc examples

docs/user-guide/faq.md
=> Add `lint-staged` Git pre-commit hooks to FAQ

docs/user-guide/faq.md
This PR consolidates the task runner questions into a more coherent whole. 
I shifted a few things around so that similar questions are grouped together.
=> Consolidate task runner FAQs

README.md
=> Add Wikimedia to growing community list of stylelint users

CHANGELOG.md, src/rules/font-family-name-quotes/README.md, src/rules/font-family-name-quotes/__tests__/index.js, src/rules/font-family-name-quotes/index.js
=> Update `font-family-name-quotes` to also check `font` properties

src/formatters/__tests__/verboseFormatter-test.js, src/formatters/stringFormatter.js
Closes #1473
First of the two new tests is for https://github.com/stylelint/stylelint/issues/1405
=> Ensure a minimum width of 80 for formatters

src/formatters/__tests__/jsonFormatter-test.js
Closes #1359
Supersedes: https://github.com/stylelint/stylelint/pull/1434
=> Add JSON formatter test

docs/user-guide/configuration.md
Ref #1460, see https://github.com/stylelint/stylelint/issues/1460#issuecomment-228731520
=> Update example except/ignore rule option

CHANGELOG.md, docs/user-guide/release-planning.md
Ref: https://github.com/stylelint/stylelint/pull/1535
=> Deprecate e and extract CLI flags

src/__tests__/standalone-test.js, src/cli.js, src/standalone.js
=> Add friendly error messages for incorrect options values

CHANGELOG.md, docs/user-guide/configuration.md, docs/user-guide/faq.md, src/__tests__/defaultSeverity-test.js, src/postcssPlugin.js
=> Add defaultSeverity config option; closes #1475

src/__tests__/integration.js
=> Add integration tests for each primary option type

CHANGELOG.md, src/rules/selector-max-specificity/README.md, src/rules/selector-max-specificity/__tests__/index.js, src/rules/selector-max-specificity/index.js
=> Ignore :not() pseudo-class selectors in selector-max-specificity

CHANGELOG.md, src/rules/function-calc-no-unspaced-operator/__tests__/index.js, src/rules/function-calc-no-unspaced-operator/index.js
=> Correctly interpret negative fractional numbers without a leading zero

docs/developer-guide/rules.md
=> Further expand the inclusion criteria

CHANGELOG.md, src/cli.js
Close https://github.com/stylelint/stylelint/issues/1557
=> Run `stylelint` CLI without input output help

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-attribute-quotes/README.md, src/rules/selector-attribute-quotes/__tests__/index.js, src/rules/selector-attribute-quotes/index.js
Closes https://github.com/stylelint/stylelint/issues/1137
=> New rule `selector-attribute-quotes` (#1137)

src/rules/at-rule-empty-line-before/README.md, src/rules/block-closing-brace-newline-after/README.md
Close #1593
@Nirazul Thanks for spotting these oversights.
=> At-rule-* doc fixes

src/rules/value-keyword-case/README.md
=> Document automatic ignore behaviour

CHANGELOG.md, src/rules/keyframe-declaration-no-important/__tests__/index.js, src/rules/keyframe-declaration-no-important/index.js, src/rules/no-unknown-animations/__tests__/index.js, src/rules/no-unknown-animations/index.js, src/rules/time-no-imperceptible/__tests__/index.js, src/rules/time-no-imperceptible/index.js
Close https://github.com/stylelint/stylelint/issues/1437
=> support prefixed

package.json
See https://github.com/stylelint/stylelint/issues/1409#issuecomment-230714400
=> PostCSS-Less 0.14.0

package.json
See https://github.com/stylelint/stylelint/issues/1580#issuecomment-230821962
=> Pinning ESLint 3.0.0

.travis.yml, CHANGELOG.md, package.json
=> Require NodeJS 4.x LTS

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/function-url-no-scheme-relative/README.md, src/rules/function-url-no-scheme-relative/__tests__/index.js, src/rules/function-url-no-scheme-relative/index.js, src/rules/index.js
https://github.com/stylelint/stylelint/issues/1084
=> New rule `function-url-no-scheme-relative`

CHANGELOG.md, src/rules/selector-attribute-quotes/__tests__/index.js, src/rules/selector-attribute-quotes/index.js
=> Better handling quotes in selector attribute with multiple attributes

src/rules/at-rule-no-unknown/README.md, src/rules/selector-pseudo-class-no-unknown/README.md, src/rules/selector-pseudo-element-no-unknown/README.md, src/rules/selector-type-no-unknown/README.md, src/rules/unit-no-unknown/README.md
=> Define known in *no-unknown READMEs

package.json
https://github.com/istanbuljs/nyc/blob/master/CHANGELOG.md#700-2016-07-09
https://github.com/istanbuljs/nyc/compare/v6.6.1...v7.0.0
=> Update devDependency `nyc` to `^7.0.0`

CHANGELOG.md, src/__tests__/buildConfig-test.js, src/__tests__/fixtures/config-plugin-extending-with-plugin.json, src/__tests__/fixtures/plugin-warn-about-bar.js, src/__tests__/plugins-test.js, src/buildConfig.js
=> Add tests for concatenating plugins array

CHANGELOG.md, src/rules/indentation/README.md, src/rules/indentation/__tests__/functions.js, src/rules/indentation/index.js
Closes #1517
Only two more [`7.0.0` issues](https://github.com/stylelint/stylelint/milestone/14) to go after this one :)
=> Check indentation inside of parens by default

CHANGELOG.md, docs/developer-guide/plugins.md, docs/developer-guide/rules.md, package.json, src/__tests__/fixtures/plugin-primary-array.js, src/__tests__/normalizeRuleSettings-test.js, src/__tests__/plugins-test.js, src/normalizeRuleSettings.js, src/postcssPlugin.js, src/rules/declaration-block-properties-order/index.js, src/rules/function-blacklist/index.js, src/rules/function-whitelist/index.js, src/rules/property-blacklist/index.js, src/rules/property-unit-blacklist/index.js, src/rules/property-value-blacklist/index.js, src/rules/property-whitelist/index.js, src/rules/unit-blacklist/index.js, src/rules/unit-whitelist/index.js
Ref #1579.
Let me know if you think there are further tests or documentation needed.
=> Allow primary option arrays in plugins; closes #1579

src/rules/declaration-block-semicolon-newline-after/README.md, src/rules/declaration-block-semicolon-newline-before/README.md, src/rules/declaration-block-semicolon-space-after/README.md, src/rules/declaration-block-semicolon-space-before/README.md
=> Add less mixin note to semi whitespace rule docs

src/rules/declaration-block-trailing-semicolon/README.md
=> Expand ignore constructs list for trailing-semi

.travis.yml
Via https://github.com/stylelint/stylelint/pull/1618#discussion_r70294157
=> Travis CI: Run `npm prune` before `npm update`

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, package.json, src/rules/index.js, src/rules/property-no-unknown/README.md, src/rules/property-no-unknown/__tests__/index.js, src/rules/property-no-unknown/index.js
- Rel: https://github.com/stylelint/stylelint/issues/950
- Close: https://github.com/betit/stylelint-known-property/issues/6
=> Add property-no-unknown rule

package.json
https://github.com/betit/known-css-properties/compare/v0.0.2...v0.0.3
=> Update known-css-properties to v0.0.3

docs/user-guide/css-processors.md
=> Put flag at end of CLI options

CHANGELOG.md
Couple of broken links in the changelog - fixed them.
=> Fix links to processors guide in CHANGELOG

CHANGELOG.md, src/rules/no-descending-specificity/__tests__/index.js, src/rules/selector-max-specificity/README.md, src/rules/selector-max-specificity/__tests__/index.js, src/rules/selector-max-specificity/index.js
=> fixes selector-max-specificity crash

src/rules/declaration-block-semicolon-space-after/__tests__/index.js
Updated test coverage to 100%.
If this is okay, I will update remaining test-cases where the coverage is not 100% 
@davidtheclark @jeddy3
=> declaration-block-semicolon-space-after test coverage increased

src/rules/comment-empty-line-before/README.md, src/rules/comment-empty-line-before/__tests__/index.js, src/rules/comment-empty-line-before/index.js, src/rules/declaration-block-trailing-semicolon/README.md
=> Use consistent terminology for shared-line comments

README.md
=> Remove setting the syntax reminder

README.md, docs/user-guide/configuration.md
We’ve passed the 150 mark.
Congrats everyone :)
=> Increase rule count in docs

CHANGELOG.md, src/rules/no-descending-specificity/index.js
=> Fix order within no-descending-selector message

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-pseudo-class-whitelist/README.md, src/rules/selector-pseudo-class-whitelist/__tests__/index.js, src/rules/selector-pseudo-class-whitelist/index.js, src/utils/__tests__/isStandardSyntaxSelector-test.js
Ref #1119
It feels like it’s been yonks since I wrote a rule. There’s one or two proposals that I know I’d use on my next project, so I figured I'd try getting them done.
=> Add selector-pseudo-class-whitelist rule

src/rules/block-no-empty/__tests__/index.js
=> Add tests to `block-no-empty`

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/block-closing-brace-empty-line-before/README.md, src/rules/block-closing-brace-empty-line-before/__tests__/index.js, src/rules/block-closing-brace-empty-line-before/index.js, src/rules/index.js
=> Add block-closing-brace-empty-line-before

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-pseudo-class-blacklist/README.md, src/rules/selector-pseudo-class-blacklist/__tests__/index.js, src/rules/selector-pseudo-class-blacklist/index.js
=> Add selector-pseudo-class-blacklist rule

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/comment-no-empty/README.md, src/rules/comment-no-empty/__tests__/index.js, src/rules/comment-no-empty/index.js, src/rules/index.js
fixes #1677 
is it really this `simple` or am i `missing` something here?
=> add comment-no-empty rule

package.json
https://github.com/sindresorhus/globby/compare/v5.0.0...v6.0.0
No changes appear to affect stylelint
=> chore(package): Update globby to version 6.0.0

CHANGELOG.md, src/reference/keywordSets.js, src/rules/font-family-name-quotes/__tests__/index.js, src/utils/__tests__/findFontFamily-test.js, src/utils/findFontFamily.js
=> added support for font-weight as number in font-short hand property

CHANGELOG.md, src/rules/selector-no-type/README.md, src/rules/selector-no-type/__tests__/index.js, src/rules/selector-no-type/index.js
=> Add  to selector-no-type.

CHANGELOG.md, src/reference/propertySets.js, src/rules/color-named/__tests__/index.js, src/rules/color-named/index.js
=> Ignore declarations that accept custom idents in color-named

src/rules/indentation/__tests__/at-rules.js, src/rules/indentation/__tests__/comments.js, src/rules/indentation/__tests__/functions.js, src/rules/indentation/__tests__/rules.js, src/rules/indentation/__tests__/selectors.js, src/rules/indentation/index.js
Demonstrates the problem discussed in #1708
=> Account for windows carriage returns in parens in indentation

src/rules/function-linear-gradient-no-nonstandard-direction/README.md, src/rules/no-empty-source/README.md
=> Adds missing options to docs

CHANGELOG.md, src/rules/at-rule-empty-line-before/README.md, src/rules/at-rule-empty-line-before/__tests__/index.js, src/rules/at-rule-empty-line-before/index.js
=> Add blockless name matching option to at-rule-empty-; closes #1366

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-nested-pattern/README.md, src/rules/selector-nested-pattern/__tests__/index.js, src/rules/selector-nested-pattern/index.js
=> Add selector-nested-pattern; closes #962

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/value-list-max-empty-lines/README.md, src/rules/value-list-max-empty-lines/__tests__/index.js, src/rules/value-list-max-empty-lines/index.js
Close https://github.com/stylelint/stylelint/issues/1713
=> Added: new rule `value-list-max-empty-lines`.

CHANGELOG.md, src/rules/no-unknown-animations/__tests__/index.js, src/rules/unit-blacklist/__tests__/index.js, src/utils/__tests__/getUnitFromValueNode-test.js, src/utils/getUnitFromValueNode.js
=> fixes false positive for no-unknown animations

src/__tests__/fixtures/standaloneNoParsing/no-syntax-error.css, src/__tests__/fixtures/standaloneNoParsing/syntax-error-ignored.scss, src/__tests__/ignore-test.js, src/__tests__/stylelintignore-test/stylelintignore-test.js, src/postcssPlugin.js, src/standalone.js, src/utils/getIgnoredFilter.js, src/utils/getIsFileIgnored.js
=> Completely ignore files when using standalone

src/rules/max-nesting-depth/README.md, src/rules/max-nesting-depth/__tests__/index.js, src/rules/max-nesting-depth/index.js
=> Add ignoreAtRules option to max-nesting-depth

src/rules/max-line-length/README.md, src/rules/max-line-length/__tests__/index.js, src/rules/max-line-length/index.js
=> Add ignore comments option to max-line-length

docs/developer-guide/rules.md, src/rules/at-rule-empty-line-before/README.md, src/rules/at-rule-no-unknown/README.md, src/rules/block-closing-brace-newline-after/README.md, src/rules/block-opening-brace-space-before/README.md, src/rules/comment-empty-line-before/README.md, src/rules/custom-property-empty-line-before/README.md, src/rules/declaration-block-properties-order/README.md, src/rules/declaration-empty-line-before/README.md, src/rules/font-weight-notation/README.md, src/rules/function-name-case/README.md, src/rules/indentation/README.md, src/rules/max-line-length/README.md, src/rules/max-nesting-depth/README.md, src/rules/media-feature-name-no-unknown/README.md, src/rules/no-browser-hacks/README.md, src/rules/no-eol-whitespace/README.md, src/rules/no-indistinguishable-colors/README.md, src/rules/no-unsupported-browser-features/README.md, src/rules/property-no-unknown/README.md, src/rules/rule-nested-empty-line-before/README.md, src/rules/rule-non-nested-empty-line-before/README.md, src/rules/selector-class-pattern/README.md, src/rules/selector-no-qualifying-type/README.md, src/rules/selector-no-type/README.md, src/rules/selector-pseudo-class-no-unknown/README.md, src/rules/selector-pseudo-element-no-unknown/README.md, src/rules/selector-type-no-unknown/README.md, src/rules/unit-no-unknown/README.md, src/rules/value-keyword-case/README.md
=> Use consistent wording for secondary options

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/function-url-scheme-whitelist/README.md, src/rules/function-url-scheme-whitelist/__tests__/index.js, src/rules/function-url-scheme-whitelist/index.js, src/rules/index.js
=> Add `function-url-scheme-whitelist` rule

docs/user-guide/faq.md
=> Add FAQ item about bundling configs

CHANGELOG.md, src/rules/selector-no-type/__tests__/index.js, src/rules/selector-no-type/index.js
=> Handles descendants within a selector list

CHANGELOG.md, src/reference/propertySets.js, src/rules/color-named/README.md, src/rules/color-named/__tests__/index.js, src/rules/color-named/index.js
=> Ignore composes declaration for color-named

docs/user-guide/about-rules.md
Closes #1848
This is something I’ve been meaning to do for a while…
=> Add empty-line docs

CHANGELOG.md, src/reference/keywordSets.js
=> Add support for Shadow DOM selectors

README.md
Ref #1851
I figured I’d knock something up for this while it’s on my mind.
=> Add Need help? section to README

docs/user-guide/faq.md
=> Add FAQ entry for empty-line-before rules

.github/ISSUE_TEMPLATE.md
=> Update issue template lead-in

src/rules/declaration-block-semicolon-newline-after/README.md, src/rules/declaration-block-semicolon-space-after/README.md
=> Clarify ignoring of last semicolon in declaration-block-semicolon-*-after

src/__tests__/ignore-test.js, src/__tests__/stylelintignore-test/stylelintignore-test.js
=> Fix brittle globs in tests

CHANGELOG.md, src/cli.js
=> Add --config-basedir CLI option; closes #1853

CHANGELOG.md, src/rules/no-descending-specificity/README.md, src/rules/no-descending-specificity/__tests__/index.js, src/rules/no-descending-specificity/index.js
Ref #1811.
I feel a little weird about this change, so please speak up if you have reservations. I think there may be no perfectly intuitive way to handle the situation, so the increased leniency of this approach is probably preferable to the way it was.
@eviltwin: Can you please take a look at this PR and see if it matches your expectations?
=> Separate treatment for selectors with pseudo-elements; closes #1811

CHANGELOG.md, docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-descendant-combinator-no-non-space/README.md, src/rules/selector-descendant-combinator-no-non-space/__tests__/index.js, src/rules/selector-descendant-combinator-no-non-space/index.js
Ref: https://github.com/stylelint/stylelint/issues/1592
=> Added: new rule `selector-descendant-combinator-no-non-space`.

CHANGELOG.md, README.md
=> Add stylelint semantic versioning policy 

src/rules/declaration-block-no-ignored-properties/README.md
=> Fix typo in declaration-block-no-ignored-properties doc

CHANGELOG.md, src/rules/color-named/README.md, src/rules/color-named/__tests__/index.js, src/rules/color-named/index.js
=> Add ignore: [inside-function] option to color-named

CHANGELOG.md, src/rules/property-no-unknown/__tests__/index.js, src/rules/property-no-unknown/index.js, src/utils/__tests__/isStandardSyntaxDeclaration-test.js, src/utils/isStandardSyntaxDeclaration.js
=> Make property-no-unknown ignore SCSS nested properties, fixes #1870

.github/PULL_REQUEST_TEMPLATE.md
=> Initial pass of PULL_REQUEST_TEMPLATE.md

docs/user-guide/plugins.md
Thank you for all your work on stylelint!
https://github.com/rstacruz/stylelint-rscss
http://rscss.io
=> docs(Plugins): add stylelint-rscss

docs/developer-guide/rules.md
=> Remove references to adding/updating changelogs

docs/user-guide/configuration.md, src/__tests__/disableRanges-integration-test.js, src/__tests__/disableRanges-test.js, src/disableRanges.js
=> Add stylelint-disable-next-line

src/formatters/__tests__/stringFormatter-test.js
Now out build are failed after last merge. Because we update `eslint-config-stylelint` and our code have errors. @stylelint/core May be any one of us knows how to solve this problem other repositories or it is normal?
=> Chore: javascript stylistics-error.

docs/user-guide/complementary-tools.md
=> Add WebStorm to complementary tools doc

docs/user-guide/faq.md
=> Add FAQ "How do I disable a rule?"

docs/developer-guide/processors.md, docs/user-guide.md, docs/user-guide/configuration.md, docs/user-guide/processors.md
=> Add curated list of processors to docs

src/rules/number-leading-zero/__tests__/index.js, src/rules/number-leading-zero/index.js, src/rules/number-max-precision/__tests__/index.js, src/rules/number-max-precision/index.js, src/rules/number-no-trailing-zeros/__tests__/index.js, src/rules/number-no-trailing-zeros/index.js
=> False positives for numbers within strings in number-* (#1898)

src/rules/function-linear-gradient-no-nonstandard-direction/__tests__/index.js, src/rules/function-linear-gradient-no-nonstandard-direction/index.js
=> Fix rule for linear-gradient with vendor prefix

docs/user-guide/plugins.md
Ref: https://github.com/stylelint/stylelint/issues/1575
=> Add property-groups-structure plugin to list

src/reference/keywordSets.js, src/rules/value-keyword-case/__tests__/index.js, src/rules/value-keyword-case/index.js
Ref #1957.
@ntwb already found the reference and made the plan, so this was an easy fix.
=> Ignore system colors in value-keyword-case

src/__tests__/integration.js, src/__tests__/normalizeRuleSettings-test.js, src/lintSource.js, src/normalizeRuleSettings.js
=> More fixes for null rule settings

src/rules/declaration-block-no-duplicate-properties/README.md
=> Fix subtitle #1986

src/__tests__/fixtures/processor-invalid-transformation.js, src/__tests__/standalone-test.js, src/augmentConfig.js
=> Move config merging block to where it belongs

docs/user-guide/example-config.md, docs/user-guide/rules.md, src/rules/index.js, src/rules/selector-no-empty/README.md, src/rules/selector-no-empty/__tests__/index.js, src/rules/selector-no-empty/index.js
=> Add selector-no-empty rule

docs/user-guide/faq.md
=> Add FAQ entry about regex patterns

.eslintignore, .flowconfig, decls/lodash.js, decls/postcss.js, decls/stylelint.js, package.json, src/__tests__/standalone-test.js, src/assignDisabledRanges.js, src/augmentConfig.js, src/createStylelint.js, src/createStylelintResult.js, src/getConfigForFile.js, src/getPostcssResult.js, src/isPathIgnored.js, src/lintSource.js, src/needlessDisables.js, src/normalizeRuleSettings.js, src/standalone.js
This PR significantly improves the usage of Flow. It also adds Lodash Flow definitions from flow-typed.
Because I improved the usage of Flow, Flow was able to catch some errors — hence the changes to some code.
=> Improve flow definitions

docs/user-guide/faq.md
=> Add FAQ entry about pinning to branch of stylelint

.travis.yml, appveyor.yml
Support new version of `nodejs`.
=> Added: support `nodejs` 7.

src/rules/media-feature-parentheses-space-inside/__tests__/index.js
#2018
This is just failing tests, not a solution. See #2018 for more information.
=> Add failing tests for #2018

docs/developer-guide/rules.md
Ref: https://github.com/stylelint/stylelint/pull/2030#issuecomment-258155507
=> Documentation: improved `developer-guide/rules.md`.

CHANGELOG.md, docs/user-guide/plugins.md, docs/user-guide/release-planning.md
=> Deprecate declaration-block-properties-order

decls/postcss.js, src/utils/atRuleParamIndex.js, src/utils/isStandardSyntaxAtRule.js
#1974 
This is a very small PR to confirm that I'm doing the right thing.
=> Add Flow definitions to atRule utils

src/cli.js
=> Allow absolute paths for --custom-formatter argument in CLI.

docs/user-guide/faq.md
=> Flesh out rule & plugin difference FAQ entry

docs/user-guide/complementary-tools.md
=> Add code climate engine to docs

docs/user-guide/configuration.md
=> Fix typo; closes #2082

decls/postcss.js, src/utils/atRuleParamIndex.js, src/utils/beforeBlockString.js, src/utils/blockString.js, src/utils/blurComments.js, src/utils/blurFunctionArguments.js, src/utils/blurInterpolation.js
#1974
This adds Flow type definitions to a few more of the util files.
=> Add more Flow definitions to utils

src/rules/rule-non-nested-empty-line-before/__tests__/index.js, src/rules/selector-type-no-unknown/__tests__/index.js, src/utils/__tests__/isStandardSyntaxRule-test.js, src/utils/isStandardSyntaxRule.js
https://github.com/stylelint/stylelint/issues/2088
=> Fixed: false positives with LESS detached rulesets.

system-tests/002/002.test.js, system-tests/002/__snapshots__/002.test.js.snap, system-tests/002/config.json, system-tests/002/stylesheet.css
Added new _system test_ for https://github.com/necolas/normalize.css
See #2052
=> test: Add Normalize.css system test

system-tests/003/003.test.js, system-tests/003/__snapshots__/003.test.js.snap, system-tests/003/config.json, system-tests/003/stylesheet.css
Added new _system test_ for https://github.com/jonathantneal/sanitize.css
See #2052
=> test: Add sanitize.css system test

src/rules/block-closing-brace-empty-line-before/index.js, src/rules/block-closing-brace-newline-before/index.js
Manually created AST node without `raws` or custom syntaxes like `postcss-js` or SugarSS.
No, it's small fix.
=> Safer raws checks

src/__tests__/ignore.test.js
None
This change enables an additional 48 tests.
=> Re-enable some skipped tests

lib/rules/atRuleNameSpaceChecker.js, lib/rules/block-closing-brace-newline-after/index.js, lib/rules/comment-empty-line-before/index.js, lib/rules/custom-property-empty-line-before/index.js, lib/rules/declaration-colon-newline-after/index.js, lib/rules/declaration-empty-line-before/index.js, lib/rules/declarationColonSpaceChecker.js, lib/rules/function-calc-no-unspaced-operator/index.js, lib/rules/indentation/index.js, lib/rules/max-empty-lines/index.js, lib/rules/selector-no-vendor-prefix/index.js, lib/rules/value-no-vendor-prefix/index.js, lib/utils/beforeBlockString.js
https://github.com/stylelint/stylelint/issues/2144 and future issue with potential undefined properties in `raws` object.
I hope nothing is missed :smile: 
/сс @davidtheclark @jeddy3
=> Fixed: safer raws checks.

lib/rules/media-feature-name-no-vendor-prefix/__tests__/index.js, lib/rules/media-feature-name-no-vendor-prefix/index.js
https://github.com/stylelint/stylelint/issues/2109
=> Fixed: TypeError for unknown unprefixed variants in `media-feature-name-no-vendor-prefix`.

bin/stylelint, bin/stylelint.js, package.json
`scripts/visual.sh` now works.
Ran `master` against all my local test files. All went well. Also very refreshing not seeing babel transpiling things for a local install :)
=> Include bin directory in package

.travis.yml, lib/utils/__tests__/atRuleParamIndex.test.js, lib/utils/__tests__/declarationValueIndex.test.js, lib/utils/__tests__/isCustomPropertySet.test.js, lib/utils/__tests__/isStandardSyntaxAtRule.test.js, lib/utils/__tests__/isStandardSyntaxDeclaration.test.js, lib/utils/__tests__/isStandardSyntaxFunction.test.js, lib/utils/__tests__/isStandardSyntaxRule.test.js, lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js
These corrections should fix #2164.
=> Cleanup tests

docs/user-guide/plugins.md
Please add my [`stylelint-declaration-strict-value`](https://github.com/AndyOGo/stylelint-declaration-strict-value) `stylelint-plugin` to your [list of plugings page](http://stylelint.io/user-guide/plugins/)
=> Please add stylelint-declaration-strict-value to plugins.md

docs/user-guide/faq.md
https://github.com/stylelint/stylelint/issues/2170
Show clear example that secondary options are overriden
instead of be extended.
=> Add section about extending and overriding rules.

docs/user-guide/about-rules.md, docs/user-guide/faq.md
=> Document how the (dis)allowing rules work together

lib/rules/selector-no-type/__tests__/index.js, lib/rules/selector-no-type/index.js
Refs #1946 
Note that this will merge into the `v8` branch, as it's a breaking change (until after `v8` is released).
=> Fix false negatives with ignore: ["descendant"] in selector-no-type

lib/rules/selector-pseudo-class-no-unknown/README.md, lib/rules/selector-pseudo-element-no-unknown/README.md
=> Fix typo in docs

package.json
=> package.json: update homepage (#2223)

docs/developer-guide/rules.md, docs/user-guide/rules.md, lib/rules/no-unknown-animations/README.md
Ref: https://github.com/stylelint/stylelint/issues/2220#issuecomment-269788153 & https://github.com/stylelint/stylelint/issues/2220#issuecomment-269809806
Vocab ref for extended description: https://www.w3.org/TR/css3-animations/#keyframes
=> Update no-unknown-animations docs

lib/rules/value-no-vendor-prefix/README.md
=> Document warning for standard values in no-vendor-prefix

docs/user-guide/release-planning.md
=> Update release planning doc for 8.0.0

lib/reference/keywordSets.js, lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js, lib/rules/selector-pseudo-class-no-unknown/index.js
=> Fixed: added proprietary webkit pseudo-classes to list of known ones in selector-pseudo-class-no-unknown.

lib/rules/selector-nested-pattern/README.md
Ref: https://github.com/stylelint/stylelint/issues/2269#issuecomment-274261515
=> Use unescaped regex in string

decls/lodash.js, lib/normalizeRuleSettings.js, package.json
=> Upgrade Flow

lib/rules/selector-no-type/README.md, lib/rules/selector-no-type/__tests__/index.js, lib/rules/selector-no-type/index.js
Closes #1942
Merging into the `v8` branch as it works well with the changes from #2200. I've rebased `v8` on to `master`.
=> Add ignore: ["child"] option to selector-no-type

docs/user-guide/configuration.md
=> Expand "rules" configuration object docs

lib/rules/at-rule-name-newline-after/README.md
=> Improve documentation of "always-multi-line" in at-rule-name-newline-after

lib/rules/selector-type-no-unknown/__tests__/index.js
=> Tests: more tests for selector-type-no-unknown (#2336).

lib/rules/selector-class-pattern/__tests__/index.js
Just fixing a bad brace position introduced in #2344
=> Fix brace position

lib/rules/selector-id-pattern/__tests__/index.js
#2334 
Add tests. Note need add `resolveNestedSelectors` option for respect nested selectors and consistently with `selector-class-pattern`. If you agree create issue :smile: 
@kaelig I was a little confusing about name #2334 issue, with `selector-id-pattern` all works fine. Or add tests example where have error.
=> Tests: added tests for nested selectors in `selector-id-pattern` rule.

lib/rules/selector-type-case/__tests__/index.js, lib/utils/__tests__/isStandardSyntaxTypeSelector.test.js, lib/utils/isStandardSyntaxTypeSelector.js
=> Fix placeholder selector case

docs/user-guide/plugins.md, lib/rules/no-browser-hacks/README.md, lib/rules/no-browser-hacks/__tests__/index.js, lib/rules/no-browser-hacks/index.js, system-tests/005/__snapshots__/005.test.js.snap, system-tests/deprecations/001/__snapshots__/001.test.js.snap
https://github.com/stylelint/stylelint/issues/2123#issuecomment-280045108
Feedbacks on the entire [plugin](https://github.com/Slamdunk/stylelint-no-browser-hacks) are welcome.
=> no-browser-hacks: link to external plugin

lib/rules/no-duplicate-selectors/__tests__/index.js
https://github.com/stylelint/stylelint/issues/2198
=> Add a test for a parent selector in no-duplicate-selectors

package.json, system-tests/005/__snapshots__/005.test.js.snap
Closes #2376 
It seems the ordering of the warnings from stylehacks has changed, causing one of the system test snapshots to need updating.
=> Update stylehacks and snapshot

CHANGELOG.md
Ref: https://github.com/stylelint/stylelint/issues/2292#issuecomment-282379774
=> Update stylelint-disable-reason changelog entry

lib/rules/no-missing-end-of-source-newline/__tests__/index.js
#2374
Works as excepted, i think not in rule.
=> Tests: improved tests for `no-missing-end-of-source-newline` rule.

docs/user-guide/configuration.md
https://github.com/stylelint/stylelint/issues/2392
=> Fix the example for Custom Message in docs

jest-setup.js, lib/rules/selector-class-pattern/__tests__/index.js
=> Fix testRule loose behaviour

docs/user-guide/node-api.md
Brings into line with reality.
=> [docs] Correct config lookup in node API

docs/user-guide/plugins.md, lib/rules/custom-property-no-outside-root/README.md, lib/rules/custom-property-no-outside-root/__tests__/index.js, lib/rules/custom-property-no-outside-root/index.js, lib/rules/root-no-standard-properties/README.md, lib/rules/root-no-standard-properties/__tests__/index.js, lib/rules/root-no-standard-properties/index.js, lib/rules/selector-root-no-composition/README.md, lib/rules/selector-root-no-composition/__tests__/index.js, lib/rules/selector-root-no-composition/index.js, system-tests/005/__snapshots__/005.test.js.snap, system-tests/deprecations/001/__snapshots__/001.test.js.snap
Also updates deprecation notices in READMEs and code
Addresses #2226
https://github.com/suitcss/stylelint-suitcss
=> Add stylelint-suitcss to plugin list

lib/rules/declaration-empty-line-before/README.md
https://github.com/stylelint/stylelint/issues/2423
=> Specify `declaration-empty-line-before` scope in readme

lib/rules/selector-type-no-unknown/README.md, lib/rules/selector-type-no-unknown/__tests__/index.js, lib/rules/selector-type-no-unknown/index.js
Closes #2326
It feels like an age since I actually wrote some stylelint code, so I picked a quick-win to whet my appetite… before I delve into issue backlog :)
=> Add ignoreNamespaces and ignore:["default-namespace"] options

lib/rules/media-feature-range-operator-space-after/README.md, lib/rules/media-feature-range-operator-space-after/__tests__/index.js, lib/rules/media-feature-range-operator-space-before/README.md, lib/rules/media-feature-range-operator-space-before/__tests__/index.js
N/A. Corrections to documentation and tests.
=> Corrected `media-feature-range-operator-space-*` documentation and tests

system-tests/systemTestUtils.js
Closes #2357
@davidtheclark Your [suggestion](https://github.com/stylelint/stylelint/issues/2357#issuecomment-282600031) worked a treat.
I had to dig out my old windows laptop to test it. The one I was using when we all first started on stylelint. I think you’ll get a little kick out of the last `git log` entry on it:
```shell
jeddy3@JEDDY3 /d/node/www/stylelint (master)
$ git log
commit ea421b2ab98b293ee8da22231749b1645e1c0b0b
Author: David Clark
Date:   Sun Sep 6 13:47:53 2015 -0700
Prepare 1.0.1
```
How time flies, hey? :)
=> Fix system tests on win32

docs/user-guide/node-api.md
=> Fix markdown typo

docs/user-guide/plugins.md
[stylelint-images](https://github.com/ramasilveyra/stylelint-images/)
**Suggestions about the introduction message are welcome!**
=> Add stylelint-images plugin

lib/reference/keywordSets.js, lib/rules/selector-pseudo-class-no-unknown/__tests__/index.js, lib/rules/selector-pseudo-class-no-unknown/index.js
#1871
If the solution is appropriate, then I will add similar logic to other rules :smile:
=> Add at-page support to selector-pseudo-class-no-unknown

docs/developer-guide/plugins.md, docs/developer-guide/rule-testers.md
https://github.com/stylelint/stylelint/issues/2499
Also added info about test schema.
=> Improving docs about autofixing

lib/rules/no-unsupported-browser-features/__tests__/index.js, system-tests/005/__snapshots__/005.test.js.snap
https://github.com/stylelint/stylelint/issues/2525
Quick fixes to tests. Rule is deprecated anyway.
=> Fix no-unsupported-browser-features tests

docs/developer-guide/plugins.md, docs/developer-guide/rules.md, docs/user-guide/cli.md, docs/user-guide/css-processors.md, docs/user-guide/faq.md, docs/user-guide/node-api.md, lib/rules/max-line-length/README.md
Ref: https://github.com/stylelint/stylelint/pull/2510
=> Use violation wording in User guides

package.json
=> chore(package): update jest to version 20.0.1

docs/user-guide/plugins.md
=> add rule to plugin doc (#2568)

lib/__tests__/standalone-deprecations.test.js, lib/__tests__/standalone.test.js, lib/testUtils/__tests__/createRuleTester.test.js, lib/utils/__tests__/report.test.js, lib/utils/__tests__/validateOptions.test.js, package.json
Issue #2519 
WIP as I'm doing pieces at a time. Will update as I go.
=> Replace sinon with jest mocks

docs/user-guide/complementary-tools.md
An Pre-commit plugin for style-lint 
https://github.com/stylelint/stylelint.io/issues/41
=> Stylelint pre-commit plugin

lib/rules/function-url-scheme-blacklist/index.js, lib/rules/function-url-scheme-whitelist/README.md, lib/rules/function-url-scheme-whitelist/__tests__/index.js, lib/rules/function-url-scheme-whitelist/index.js, lib/utils/__tests__/getSchemeFromUrl.test.js, lib/utils/getSchemeFromUrl.js
=> Add regex support to function-url-scheme-whitelist

docs/user-guide/configuration.md
=> Don't use deprecated rule in example

docs/user-guide/cli.md
=> Document use of CLI negation globs

lib/rules/max-line-length/README.md, lib/rules/max-line-length/__tests__/index.js, lib/rules/max-line-length/index.js
Closes #2647
Notes: merges into `v8`
=> Respect line case for `ignorePattern`

lib/rules/at-rule-empty-line-before/__tests__/index.js, lib/rules/comment-empty-line-before/__tests__/index.js, lib/rules/custom-property-empty-line-before/__tests__/index.js, lib/rules/declaration-empty-line-before/__tests__/index.js, lib/rules/rule-empty-line-before/__tests__/index.js
https://github.com/stylelint/stylelint/issues/2575#issuecomment-311217002
=> Fix tests for *-empty-line-before rules

docs/user-guide/configuration.md
=> Correct extends behaviour in document (fix #2716)

lib/rules/max-nesting-depth/README.md
=> Add brace in max-nesting-depth example (fix #2718)

docs/user-guide/postcss-plugin.md
Changed in postcss-reporter [version 3.0](https://github.com/postcss/postcss-reporter/blob/c33ef36b63aae9a0e7119413c78fecaef5fa785b/CHANGELOG.md#300)
=> Replace clearMessages with clearReportedMessages

docs/developer-guide.md, docs/developer-guide/releases.md, package.json
Closes #2700
@hudochenkov, @ntwb @evilebottnawi If you’d like access to the npm package for performing releases, please pop your npm usernames below and I’ll added you. Likewise, if you’d like access to the stylelint twitter account you’ll need to drop an email address or something so I can send the access details over.
=> Add releases.md

lib/rules/selector-max-type/README.md, lib/rules/selector-max-type/__tests__/index.js, lib/rules/selector-max-type/index.js
=> Change ignore options for selector-max-type

CHANGELOG.md, README.md
Highlights the _three_ types of rules, both in the list of features and within the getting started section.
=> Update README.md to account for VISION.md

docs/developer-guide/releases.md
FYI: I'm not sure I got the #anchor format correct for `template-checklist`, it's hard getting the correct link in a not yet deployed change 😏
=> docs: Add "New Release Issue Template" to releases.md

decls/flow-typed/jest.js, lib/utils/blurInterpolation.js, package-lock.json, package.json
Previously #2687 #2675
Suggestion for fix in https://github.com/stylelint/stylelint/pull/2675#issuecomment-311665840
=> chore(package): update flow-bin to version 0.50.0

docs/developer-guide/processors.md, docs/user-guide/css-processors.md, docs/user-guide/processors.md
None, as it's a documentation update.
=> Add `postcss-html` to documentation

lib/rules/color-hex-length/README.md, lib/rules/color-hex-length/__tests__/index.js, lib/rules/color-hex-length/index.js
#2806  (kind of the same as #2332)
no explanation needed.
just a little sidenote, that the docs about the rule were updated
=> Color hex length fixes

lib/__tests__/fixtures/no-empty-source.html, lib/__tests__/fixtures/postcss-html-syntax.js, lib/__tests__/standalone-syntax.test.js, package-lock.json, package.json
=> tests: Add `no-empty-source` test using `postcss-html` syntax.

CHANGELOG.md
=> fix PR link in CHANGELOG.md

docs/user-guide/node-api.md
=> Remove extraneous semicolon

docs/user-guide/processors.md
Closes https://github.com/styled-components/stylelint-processor-styled-components/issues/37
=> Add stylelint-processor-styled-components to docs

docs/user-guide/postcss-plugin.md
=> readme: add missing comma to example

decls/flow-typed/jest.js, decls/flow-typed/lodash.js
=> Update flowtype definitions

lib/cli.js
https://github.com/stylelint/stylelint/pull/2834 was incomplete.
I totally missed the CLI assignment.
=> fix: Fix --ignorePattern not working for the CLI.

README.md
Correct capitalization of GitHub
=> Correct capitalization of GitHub

.travis.yml
Ref: https://github.com/stylelint/stylelint/issues/2766#issuecomment-326884112
Issue seems fixed in `npm@5.4.1`
=> Unpin CI npm version

lib/rules/length-zero-no-unit/README.md, lib/rules/length-zero-no-unit/__tests__/index.js, lib/rules/length-zero-no-unit/index.js
=> Add autofix support to length-zero-no-unit

docs/developer-guide/plugins.md
#2812
I am not confident in English, so please give me feedbacks for incorrect or strange wording etc. 😓
=> docs: Add description about peer dependency for writing plugin

docs/developer-guide.md, docs/developer-guide/prerequisites.md
Ref: https://github.com/stylelint/stylelint/issues/2866#issuecomment-328456091
=> Add rules of thumb to prerequisites doc

decls/postcss.js, lib/getPostcssResult.js
no
Reduce cyclomatic complexity for  `lib/getPostcssResult.js`
=> Reduce cyclomatic complexity in getPostcssResult.js

docs/user-guide/rules.md
=> mark rule-empty-line-before as fixable in the rules list

docs/user-guide/plugins.md
https://github.com/stylelint/stylelint/issues/2054#issuecomment-331089142
Adding `stylelint-declaration-block-no-ignored-properties` to the list of stylelint plugins.
=> Add link to stylelint-declaration-block-no-ignored-properties

.github/PULL_REQUEST_TEMPLATE.md
Seems that links were outdated. With this change, they are not :)
=> Fix links in PULL_REQUEST_TEMPLATE

decls/stylelint.js, lib/cli.js, lib/lintSource.js, lib/needlessDisables.js
Increasing flow coverage - no open issue right now I believe.
This is a rebase and revision of #2823 and supersedes it. It removes some duplicate code, fixes errors in Flow definitions, and corrects an error made while entering those definitions. Credit to @ivanzusko for the bulk of the work.
=> Increase flow coverage `lib/cli.js`, `lib/lintSource.js`, and `lib/needlessDisables.js`

.gitignore, .npmrc, .travis.yml
Closes https://github.com/stylelint/stylelint/issues/2766
=> Disable package-lock

package.json
#2933 
In contrast to the issue opened by greenkeeper, this looks fine.
=> Cosmiconfig-3.1.0

.gitignore
None, Ignoring yarn.lock in gitignore file
[check comments here](https://github.com/stylelint/stylelint/pull/2941#discussion_r142831325)
=> Adding yarn.lock to .gitignore file

docs/developer-guide/pull-requests.md
Ref: https://github.com/stylelint/stylelint/pull/2947#issuecomment-335546112
=> Tweak the Pull Request guidelines

lib/rules/number-leading-zero/README.md, lib/rules/number-leading-zero/__tests__/index.js, lib/rules/number-leading-zero/index.js, lib/rules/number-no-trailing-zeros/__tests__/index.js
=> Add autofix support to number-leading-zero

package.json
None.
It throws deprecation warning on `npm install` (from the repository). We don't use it :)
=> Remove forgotten dev dependency

docs/user-guide/rules.md
Follow up for #2921, #2947, and #2861.
=> Add (Autofixable) to new supported rules in the rules list

package.json
=> chore(package): update flow-bin to version 0.57.2

lib/rules/length-zero-no-unit/README.md, lib/rules/length-zero-no-unit/__tests__/index.js, lib/rules/length-zero-no-unit/index.js
#2586
I`ve tried to follow all tips in the issue.
=> Add ignore: ["custom-properties"] to length-zero-no-unit

docs/developer-guide/issues.md
=> Document use of standard labels

lib/__tests__/standalone-syntax.test.js
=> fix testcase of postcss-safe-parser

decls/flow-typed/jest.js, decls/flow-typed/lodash.js
Follow up to #3000 
• https://github.com/flowtype/flow-typed/blob/master/definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js
• https://github.com/flowtype/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
=> Update Flow library definitions

lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.js, lib/rules/font-family-no-missing-generic-family-keyword/index.js
=> Fix false positives for font-face in font-family-no-missing-generic-family-keyword

lib/rules/indentation/__tests__/html.js, lib/rules/indentation/index.js
=> Add indentation support for html

lib/cli.js, package.json
Update `meow` to latest version
Guys I did not forget about us, just a lot of work and I was accepted into webpack, where there is a lot of work, but I remember about stylelint and let's continue to do the best style linter :star: :star: :star:
=> chore: update `meow` package to latest version

.travis.yml
None. But #2998 a little bit related.
Added Node.js 9, as it the latest Node.js since yesterday. Keeping `pretest` and `coverage` on Node.js 8 as it more stable for now. `coverage` has higher priority because it takes more time (the sooner it starts, the sooner it finishes).
=> Add Node.js 9 to Travis CI

decls/flow-typed/lodash.js
Follow up to #3084, previously #3074
• https://raw.githubusercontent.com/flowtype/flow-typed/master/definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
=> chore: Update Lodash Flow library definitions

lib/__tests__/standalone.test.js, lib/augmentConfig.js, lib/needlessDisables.js, lib/rules/color-named/generateColorFuncs.js, lib/rules/color-named/index.js, lib/rules/custom-property-empty-line-before/index.js, lib/rules/declaration-empty-line-before/index.js, lib/rules/declaration-property-unit-blacklist/index.js, lib/rules/declaration-property-unit-whitelist/index.js, lib/rules/declaration-property-value-blacklist/index.js, lib/rules/declaration-property-value-whitelist/index.js, lib/rules/media-feature-name-blacklist/index.js, lib/rules/media-feature-name-case/index.js, lib/rules/media-feature-name-no-unknown/index.js, lib/rules/media-feature-name-whitelist/index.js, lib/rules/selector-id-pattern/index.js, lib/rules/selector-max-type/index.js, lib/rules/selector-type-case/index.js, lib/rules/selector-type-no-unknown/index.js, lib/rules/shorthand-property-no-redundant-values/index.js, lib/rules/unit-blacklist/index.js, lib/rules/value-keyword-case/index.js, lib/rules/value-no-vendor-prefix/index.js, lib/utils/isStandardSyntaxDeclaration.js, lib/utils/isStandardSyntaxTypeSelector.js, lib/utils/whitespaceChecker.js, package.json
See https://github.com/stylelint/eslint-config-stylelint/pull/42
=> Update eslint-config-stylelint to v8.1.0

.travis.yml, package.json
=> Bump minimum required Node.js version to `6` and drop 4.x

lib/rules/declaration-empty-line-before/README.md, lib/rules/declaration-empty-line-before/__tests__/index.js, lib/rules/declaration-empty-line-before/index.js
=> Add ignore: ["first-nested"] to declaration-empty-line-before
